
OTMBACCO_FIND_CGFKCSLDCABBANKACCOUNTTYP {
 	SELECT REF_CODE.CODE  BANK_ACCOUNT_TYPE  /* CG$FK */        ,REF_CODE.DOMAIN  DSP_DOMAIN        ,REF_CODE.DESCRIPTION  DSP_DESCRIPTION        ,REF_CODE.ACTIVE_FLAG  DSP_ACTIVE_FLAG        ,REF_CODE.EXPIRED_DATE  DSP_EXPIRED_DATE FROM   REFERENCE_CODES REF_CODE WHERE   REF_CODE.DOMAIN = 'BANK_AC_TYPE'  AND  REF_CODE.ACTIVE_FLAG = 'Y'   AND REF_CODE.EXPIRED_DATE IS NULL
}

OTMBACCO_FIND_CGFKCSLDCABPAYEECORPORATE {
 	SELECT CRP.CORPORATE_ID , CORPORATE_NAME  FROM CORPORATES CRP , CORPORATE_TYPES CTP WHERE CRP.CORPORATE_ID = CTP.CORPORATE_ID  AND CTP.CORPORATE_TYPE NOT IN ('VENDOR' ,'PROGRAM' ) UNION (SELECT CORPORATE_ID ,  CORPORATE_NAME   FROM CORPORATES CRP2  WHERE NOT EXISTS ( SELECT 1 FROM CORPORATE_TYPES CTP2 WHERE CRP2.CORPORATE_ID = CTP2.CORPORATE_ID  )  ) ORDER BY 1
}

OTMBACCO_FIND_CGFKCSLDCABACCOUNTCODE {
-- 	SELECT AC_CODE.ACCOUNT_CODE ACCOUNT_CODE /* CG$FK */  ,AC_CODE.ACCOUNT_NAME DESCRIPTION FROM ACCOUNT_CODES AC_CODE WHERE ACCOUNT_TYPE = 'A' AND CASELOAD_TYPE = ( SELECT CS.CASELOAD_TYPE FROM CASELOADS CS WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = USER))
SELECT
    ac_code.account_code   account_code /* CG$FK */,
    ac_code.account_name   description
FROM
    account_codes ac_code
WHERE
    account_type = 'A'
    AND caseload_type = (
        SELECT
            cs.caseload_type
        FROM
            caseloads cs
        WHERE
            caseload_id = (
                SELECT
                    working_caseload_id
                FROM
                    staff_members
                WHERE
                    user_id = :userId
            )
    )
}

OTMBACCO_CSLDCAB_FIND_CASELOAD_CURRENT_ACCOUNTS_BASE {
 	SELECT CASELOAD_ID, ACCOUNT_CODE, ACCOUNT_PERIOD_ID, CURRENT_BALANCE, BANK_ACCOUNT_TYPE, BANK_ACCOUNT_NUMBER, ACCOUNT_PARTY_TYPE, PAYEE_PERSON_ID, PAYEE_CORPORATE_ID, MODIFY_DATE, ROUTING_NUMBER, LIST_SEQ, CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG FROM CASELOAD_CURRENT_ACCOUNTS_BASE 
 	}
OTMBACCO_CSLDCAB_INSERT_CASELOAD_CURRENT_ACCOUNTS_BASE {
	INSERT INTO CASELOAD_CURRENT_ACCOUNTS_BASE(CASELOAD_ID,ACCOUNT_CODE,ACCOUNT_PERIOD_ID,CURRENT_BALANCE,BANK_ACCOUNT_TYPE,BANK_ACCOUNT_NUMBER,
	ACCOUNT_PARTY_TYPE,PAYEE_PERSON_ID,PAYEE_CORPORATE_ID,MODIFY_DATE,ROUTING_NUMBER,LIST_SEQ,CREATE_DATETIME,
	CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
	VALUES(:caseloadId,:accountCode,:accountPeriodId,:currentBalance,:bankAccountType,:bankAccountNumber,:accountPartyType,:payeePersonId,
	:payeeCorporateId,:modifyDate,:routingNumber,:listSeq,
	current_timestamp,:createUserId,:current_timestamp,:sealFlag)
}

OTMBACCO_CSLDCAB_UPDATE_CASELOAD_CURRENT_ACCOUNTS_BASE {
	UPDATE CASELOAD_CURRENT_ACCOUNTS_BASE set CASELOAD_ID=:caseloadId, ACCOUNT_CODE=:accountCode,
	ACCOUNT_PERIOD_ID=:accountPeriodId, CURRENT_BALANCE=:currentBalance, BANK_ACCOUNT_TYPE=:bankAccountType,
	BANK_ACCOUNT_NUMBER=:bankAccountNumber, ACCOUNT_PARTY_TYPE=:accountPartyType,
	PAYEE_PERSON_ID=:payeePersonId, PAYEE_CORPORATE_ID=:payeeCorporateId,
	MODIFY_USER_ID=:modifyUserId, MODIFY_DATE=:modifyDate, ROUTING_NUMBER=:routingNumber, LIST_SEQ=:listSeq,  MODIFY_DATETIME=current_timestamp, SEAL_FLAG=:sealFlag  WHERE CASELOAD_ID = :caseloadId AND ACCOUNT_CODE = :accountCode
}

OTMBACCO_CSLDCAB_DELETE_CASELOAD_CURRENT_ACCOUNTS_BASE { 
	DELETE FROM CASELOAD_CURRENT_ACCOUNTS_BASE WHERE CASELOAD_ID = :caseloadId AND ACCOUNT_CODE = :accountCode
}

OTMBACCO_BANKAM_FIND_BANK_ACCOUNTS_MAINTENANCES {
 	SELECT CASELOAD_ID, ACCOUNT_CODE, ACTIVE_FLAG, EXPIRY_DATE, CLIENT_ID, ORIGINATOR_ID, BK_ACCOUNT_DESC, COMMENT_TEXT, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM BANK_ACCOUNTS_MAINTENANCES  WHERE ACCOUNT_CODE = :ACCOUNTCODE AND CASELOAD_ID = :CASELOADID
}
OTMBACCO_BANKAM_INSERT_BANK_ACCOUNTS_MAINTENANCES {
	INSERT INTO BANK_ACCOUNTS_MAINTENANCES(CASELOAD_ID, ACCOUNT_CODE, ACTIVE_FLAG, EXPIRY_DATE, CLIENT_ID, ORIGINATOR_ID,
	BK_ACCOUNT_DESC, COMMENT_TEXT, CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG,MODIFY_DATETIME) 
	VALUES(:caseloadId, :accountCode, :activeFlag, :expiryDate, :clientId, :originatorId, :bkAccountDesc, 
	:commentText, current_timestamp, :createUserId, :sealFlag,current_timestamp)
}

OTMBACCO_BANKAM_UPDATE_BANK_ACCOUNTS_MAINTENANCES {
		UPDATE BANK_ACCOUNTS_MAINTENANCES set CASELOAD_ID=:caseloadId, ACCOUNT_CODE=:accountCode, ACTIVE_FLAG=:activeFlag,
		EXPIRY_DATE=:expiryDate, CLIENT_ID=:clientId, ORIGINATOR_ID=:originatorId, BK_ACCOUNT_DESC=:bkAccountDesc, 
		COMMENT_TEXT=:commentText, 
		MODIFY_DATETIME=current_timestamp, MODIFY_USER_ID=:modifyUserId, SEAL_FLAG=:sealFlag WHERE CASELOAD_ID=:caseloadId AND ACCOUNT_CODE=:accountCode
}

OTMBACCO_BANKAM_DELETE_BANK_ACCOUNTS_MAINTENANCES { 
	DELETE FROM BANK_ACCOUNTS_MAINTENANCES WHERE CASELOAD_ID=:caseloadId AND ACCOUNT_CODE=:accountCode
}


OTMBACCO_CSLD_CAB_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM BANK_ACCOUNTS_MAINTENANCES B WHERE B.CASELOAD_ID = :CASELOADID AND B.ACCOUNT_CODE = :ACCOUNTCODE
}

OTMBACCO_CGFKCHK_CSLD_CAB_CSLD_CAB_REF_ {
	SELECT REF_CODE.DOMAIN ,REF_CODE.DESCRIPTION ,REF_CODE.ACTIVE_FLAG ,REF_CODE.EXPIRED_DATE FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :BANKACCOUNTTYPE AND     REF_CODE.DOMAIN = 'BANK_AC_TYPE'  AND REF_CODE.ACTIVE_FLAG = 'Y' AND REF_CODE.EXPIRED_DATE IS NULL
}

OTMBACCO_CGFKCHK_CSLD_CAB_CSLD_CAB_AC__ {
	SELECT AC_CODE.ACCOUNT_NAME FROM   ACCOUNT_CODES AC_CODE WHERE  AC_CODE.ACCOUNT_CODE = :accountCode  AND     ACCOUNT_TYPE = 'A'
}

OTMBACCO_CGFKCHK_CSLD_CAB_CSLD_CAB_COR_ {
	SELECT CORP.CORPORATE_NAME FROM   CORPORATES CORP WHERE  CORP.CORPORATE_ID = :PAYEECORPORATEID
}

OTMBACCO_ACCOUNT_PERIOD_ID_ACCOUNT_PERIODS {
--	SELECT ACCOUNT_PERIOD_ID FROM ACCOUNT_PERIODS WHERE TRUNC(SYSDATE) BETWEEN START_DATE AND END_DATE
SELECT ACCOUNT_PERIOD_ID FROM ACCOUNT_PERIODS WHERE date_trunc('day', current_timestamp) BETWEEN START_DATE AND END_DATE
}

OTMBACCO_CORPORETE_NAME_DATA {
	SELECT DISTINCT CORPORATE_NAME  FROM CORPORATES WHERE CORPORATE_ID = :CORPORATEID
}