insert
	into
	SYSTEM_SETTINGS(SETTING_TYPE,
	SETTING_PROVIDER_CODE,
	SETTING_VALUE,
	CREATE_DATETIME,
	CREATE_USER_ID)
values ('EMAIL_SMS_TEST_FOOTER_CONFIG',
'EMAIL_SMS_TEST_FOOTER_CONFIG',
'[{ "KEY_DESC":"Email Testing Override", "KEY_CODE":"TEST_EM_OV", "VALUE":"N"}, {"KEY_DESC":"SMS Testing Override", "KEY_CODE":"TEST_SMS_OV", "VALUE":"N"}, {"KEY_DESC": "Global Email Footer", "KEY_CODE": "EM_FOOT", "VALUE": "N"}, {"KEY_DESC": "Global SMS Footer", "KEY_CODE": "SMS_FOOT", "VALUE": "N"}]',
CURRENT_TIMESTAMP,
'OMS_OWNER') ;