
OCINAMES_VNSEARCH_FIND_V_PIMS_NAME_SEARCH_FN {
 	SELECT OFFENDER_ID, OFFENDER_ID_DISPLAY, OFFENDER_BOOK_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, BIRTH_DATE, ACTIVE_FLAG, LIVING_UNIT_ID, ROOT_OFFENDER_ID, PRISON_LOCATION,SEAL_FLAG FROM V_PIMS_NAME_SEARCH_FN(:userId)
}
