
OMSYSJNT_FIND_TABLERG {
-- 	SELECT TABLE_NAME DESCRIPTION ,TABLE_NAME CODE FROM ALL_TABLES WHERE OWNER = 'OMS_OWNER' ORDER BY 1
-- 	SELECT TABLE_NAME DESCRIPTION ,TABLE_NAME CODE FROM ALL_TABLES  WHERE OWNER =:OWNER ORDER BY 1
 	 	SELECT upper(TABLE_NAME) DESCRIPTION ,upper(TABLE_NAME) CODE FROM ALL_TABLES WHERE OWNER = lower(:OWNER )ORDER BY 1


}


OMSYSJNT_CREATE_ONE_TR {
	SELECT    COLUMN_NAME, DATA_TYPE, to_char(DATA_LENGTH) DATA_LENGTH, DATA_PRECISION, DATA_SCALE FROM      USER_TAB_COLUMNS WHERE  table_name= :tableName AND     DATA_TYPE IN ('DATE', 'NUMBER', 'CHAR', 'VARCHAR2') ORDER BY  COLUMN_ID
}

CHECK_SYNONYM_CUR {
	SELECT 'Y' FROM ALL_SYNONYMS WHERE SYNONYM_NAME = :TABNAMEJN
}

OMSYSJNT_CREATE_TR {
	SELECT TABLE_NAME FROM ALL_TABLES WHERE TABLE_NAME NOT LIKE '%_JN' AND TABLE_NAME NOT LIKE '%TEMP' AND TABLE_NAME NOT LIKE '%TMP' AND TABLE_NAME NOT LIKE 'TEMP%' AND TABLE_NAME NOT LIKE 'TMP%' AND OWNER = 'oms_owner'
}

OMSYSJNT_CREATE_TRIGGER_JN1_ {
--	SELECT    COLUMN_NAME FROM      USER_TAB_COLUMNS WHERE     TABLE_NAME = TABNAME ORDER BY  COLUMN_ID
 SELECT    COLUMN_NAME FROM      USER_TAB_COLUMNS WHERE     TABLE_NAME = :TABNAME ORDER BY  COLUMN_ID

}
