
OUMAUDIT_FIND_RGDBOBJECTS {
 	SELECT OBJECT_NAME CODE, OBJECT_NAME DESCRIPTION  FROM ALL_OBJECTS  WHERE OBJECT_TYPE = 'TABLE'  AND NOT OBJECT_NAME LIKE 'BIN%'  AND TEMPORARY = 'N'  AND OWNER =  'OMS_OWNER'  AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME                            FROM ALL_AUDIT_POLICIES ) ORDER BY OBJECT_NAME
}

OUMAUDIT_ALLAUDITPOLICIES_FIND_ALL_AUDIT_POLICIES {
 	SELECT * FROM ALL_AUDIT_POLICIES 
}

OUMAUDIT_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OUMAUDIT_CHECK_POLICY_EXISTS {
	SELECT COUNT(*) FROM all_audit_policies WHERE object_schema = 'OMS_OWNER' AND object_name = :p_object_name
    AND policy_name = 'TAG_ALL'
         }
		 
OUMAUDIT_GET_ALL_TABLENAMES {
 	SELECT OBJECT_NAME CODE, OBJECT_NAME DESCRIPTION  FROM ALL_OBJECTS  WHERE OBJECT_TYPE = 'TABLE'  AND NOT OBJECT_NAME LIKE 'BIN%'  AND TEMPORARY = 'N'  AND OWNER =  'OMS_OWNER' ORDER BY OBJECT_NAME
}		 