---- Clear old data first for the database
DELETE FROM oms_owner.oms_modules_help;

---- Version: sysconjusticesystems/online_help:1.10
---- Insert screens: 220 Rows

INSERT INTO oms_owner.oms_modules_help (module_name, help_type, help_url, help_desc,create_user_id,create_datetime)
VALUES
    ('OCDADDRE', 'H', 'OCDADDRE.htm', 'OCDADDRE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDALERT', 'H', 'OCDALERT.htm', 'OCDALERT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDALIAS', 'H', 'OCDALIAS.htm', 'OCDALIAS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDALTCC', 'H', 'OCDALTCC.htm', 'OCDALTCC HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDATPOW', 'H', 'OCDATPOW.htm', 'OCDATPOW HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDBAILO', 'H', 'OCDBAILO.htm', 'OCDBAILO HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDCGPAY', 'H', 'OCDCGPAY.htm', 'OCDCGPAY HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDCLIST', 'H', 'OCDCLIST.htm', 'OCDCLIST HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDCLOGS', 'H', 'OCDCLOGS.htm', 'OCDCLOGS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDCLOSE', 'H', 'OCDCLOSE.htm', 'OCDCLOSE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDCORDS', 'H', 'OCDCORDS.htm', 'OCDCORDS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDEDEMP', 'H', 'OCDEDEMP.htm', 'OCDEDEMP HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDEXPOW', 'H', 'OCDEXPOW.htm', 'OCDEXPOW HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDHEALT', 'H', 'OCDHEALT.htm', 'OCDHEALT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDINTAK', 'H', 'OCDINTAK.htm', 'OCDINTAK HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDIPLAN', 'H', 'OCDIPLAN.htm', 'OCDIPLAN HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDLANGS', 'H', 'OCDLANGS.htm', 'OCDLANGS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDLEGLS', 'H', 'OCDLEGLS.htm', 'OCDLEGLS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDNCODE', 'H', 'OCDNCODE.htm', 'OCDNCODE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDNOQUE', 'H', 'OCDNOQUE.htm', 'OCDNOQUE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDORASS', 'H', 'OCDORASS.htm', 'OCDORASS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDPAROR', 'H', 'OCDPAROR.htm', 'OCDPAROR HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDPERSO', 'H', 'OCDPERSO.htm', 'OCDPERSO HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDPROGR', 'H', 'OCDPROGR.htm', 'OCDPROGR HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDPSREP', 'H', 'OCDPSREP.htm', 'OCDPSREP HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDRLFCC', 'H', 'OCDRLFCC.htm', 'OCDRLFCC HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDSABUS', 'H', 'OCDSABUS.htm', 'OCDSABUS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDSENCH', 'H', 'OCDSENCH.htm', 'OCDSENCH HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDTAPOW', 'H', 'OCDTAPOW.htm', 'OCDTAPOW HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDXPROG', 'H', 'OCDXPROG.htm', 'OCDXPROG HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCICNSRC', 'H', 'OCICNSRC.htm', 'OCICNSRC HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCIDIARY', 'H', 'OCIDIARY.htm', 'OCIDIARY HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCIIPLAN', 'H', 'OCIIPLAN.htm', 'OCIIPLAN HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCINAMES', 'H', 'OCINAMES.htm', 'OCINAMES HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCIOCNOT', 'H', 'OCIOCNOT.htm', 'OCIOCNOT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCIPOWLO', 'H', 'OCIPOWLO.htm', 'OCIPOWLO HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCISCATA', 'H', 'OCISCATA.htm', 'OCISCATA HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCITTPOW', 'H', 'OCITTPOW.htm', 'OCITTPOW HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCSPROGR', 'H', 'OCSPROGR.htm', 'OCSPROGR HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCUCOFFE', 'H', 'OCUCOFFE.htm', 'OCUCOFFE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDBSIAP', 'H', 'OIDBSIAP.htm', 'OIDBSIAP HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDBUTAB', 'H', 'OIDBUTAB.htm', 'OIDBUTAB HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDCAPPR', 'H', 'OIDCAPPR.htm', 'OIDCAPPR HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDCHOLO', 'H', 'OIDCHOLO.htm', 'OIDCHOLO HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDCIPON', 'H', 'OIDCIPON.htm', 'OIDCIPON HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDCNOTE', 'H', 'OIDCNOTE.htm', 'OIDCNOTE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDCUSTAD', 'H', 'OIDCUSTAD.htm', 'OIDCUSTAD HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDDPROP', 'H', 'OIDDPROP.htm', 'OIDDPROP HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDEHLOC', 'H', 'OIDEHLOC.htm', 'OIDEHLOC HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDESCAP', 'H', 'OIDESCAP.htm', 'OIDESCAP HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDIEPLV', 'H', 'OIDIEPLV.htm', 'OIDIEPLV HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDINTMV', 'H', 'OIDINTMV.htm', 'OIDINTMV HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDISTAT', 'H', 'OIDISTAT.htm', 'OIDISTAT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDITRAN', 'H', 'OIDITRAN.htm', 'OIDITRAN HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDMHIST', 'H', 'OIDMHIST.htm', 'OIDMHIST HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDMPITM', 'H', 'OIDMPITM.htm', 'OIDMPITM HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDONONA', 'H', 'OIDONONA.htm', 'OIDONONA HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDPAATT', 'H', 'OIDPAATT.htm', 'OIDPAATT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDPACTI', 'H', 'OIDPACTI.htm', 'OIDPACTI HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDPIDEN', 'H', 'OIDPIDEN.htm', 'OIDPIDEN HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDPINFO', 'H', 'OIDPINFO.htm', 'OIDPINFO HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDPWAIT', 'H', 'OIDPWAIT.htm', 'OIDPWAIT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDRELEA', 'H', 'OIDRELEA.htm', 'OIDRELEA HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDRHLOC', 'H', 'OIDRHLOC.htm', 'OIDRHLOC HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDRPLAN', 'H', 'OIDRPLAN.htm', 'OIDRPLAN HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDRTCON', 'H', 'OIDRTCON.htm', 'OIDRTCON HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDSCEXM', 'H', 'OIDSCEXM.htm', 'OIDSCEXM HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDSCMOV', 'H', 'OIDSCMOV.htm', 'OIDSCMOV HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDSHLOG', 'H', 'OIDSHLOG.htm', 'OIDSHLOG HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDSIAPP', 'H', 'OIDSIAPP.htm', 'OIDSIAPP HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDSTABS', 'H', 'OIDSTABS.htm', 'OIDSTABS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDSTEST', 'H', 'OIDSTEST.htm', 'OIDSTEST HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDSTOJU', 'H', 'OIDSTOJU.htm', 'OIDSTOJU HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDTPCON', 'H', 'OIDTPCON.htm', 'OIDTPCON HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDTROJU', 'H', 'OIDTROJU.htm', 'OIDTROJU HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDTRWJU', 'H', 'OIDTRWJU.htm', 'OIDTRWJU HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDUNCTA', 'H', 'OIDUNCTA.htm', 'OIDUNCTA HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDVCONT', 'H', 'OIDVCONT.htm', 'OIDVCONT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDVIRES', 'H', 'OIDVIRES.htm', 'OIDVIRES HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDVISIT', 'H', 'OIDVISIT.htm', 'OIDVISIT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIDVTOUR', 'H', 'OIDVTOUR.htm', 'OIDVTOUR HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIBOOKS', 'H', 'OIIBOOKS.htm', 'OIIBOOKS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIICIPON', 'H', 'OIICIPON.htm', 'OIICIPON HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIICLASS', 'H', 'OIICLASS.htm', 'OIICLASS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIICMOCI', 'H', 'OIICMOCI.htm', 'OIICMOCI HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIDMOVE', 'H', 'OIIDMOVE.htm', 'OIIDMOVE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIEMOVE', 'H', 'OIIEMOVE.htm', 'OIIEMOVE HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIHLHIS', 'H', 'OIIHLHIS.htm', 'OIIHLHIS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIINAMES', 'H', 'OIINAMES.htm', 'OIINAMES HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIOSCED', 'H', 'OIIOSCED.htm', 'OIIOSCED HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIPCLOC', 'H', 'OIIPCLOC.htm', 'OIIPCLOC HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIPCTRA', 'H', 'OIIPCTRA.htm', 'OIIPCTRA HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIPTRAN', 'H', 'OIIPTRAN.htm', 'OIIPTRAN HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIISCHED', 'H', 'OIISCHED.htm', 'OIISCHED HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIISHLOG', 'H', 'OIISHLOG.htm', 'OIISHLOG HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIIVISIT', 'H', 'OIIVISIT.htm', 'OIIVISIT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIMISREA', 'H', 'OIMISREA.htm', 'OIMISREA HTML Help Topic', CURRENT_USER, current_timestamp),
	('OIVCTMNG', 'H', 'OIVCTMNG.htm', 'OIVCTMNG HTML Help Topic', CURRENT_USER, current_timestamp),
	('OMUVREST', 'H', 'OMUVREST.htm', 'OMUVREST HTML Help Topic', CURRENT_USER, current_timestamp),
	('OSIHRSUM', 'H', 'OSIHRSUM.htm', 'OSIHRSUM HTML Help Topic', CURRENT_USER, current_timestamp),
	('OSINAMES', 'H', 'OSINAMES.htm', 'OSINAMES HTML Help Topic', CURRENT_USER, current_timestamp),
	('OSIOSEAR', 'H', 'OSIOSEAR.htm', 'OSIOSEAR HTML Help Topic', CURRENT_USER, current_timestamp),
	('OSIPSEAR', 'H', 'OSIPSEAR.htm', 'OSIPSEAR HTML Help Topic', CURRENT_USER, current_timestamp),
	('OUMASSMU', 'H', 'OUMASSMU.htm', 'OUMASSMU HTML Help Topic', CURRENT_USER, current_timestamp),
	('OUMCPASS', 'H', 'OUMCPASS.htm', 'OUMCPASS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OUMPERSO', 'H', 'OUMPERSO.htm', 'OUMPERSO HTML Help Topic', CURRENT_USER, current_timestamp),
	('OUMROLES', 'H', 'OUMROLES.htm', 'OUMROLES HTML Help Topic', CURRENT_USER, current_timestamp),
	('OUMSMALA', 'H', 'OUMSMALA.htm', 'OUMSMALA HTML Help Topic', CURRENT_USER, current_timestamp),
	('OUMUCREAT', 'H', 'OUMUCREAT.htm', 'OUMUCREAT HTML Help Topic', CURRENT_USER, current_timestamp),
	('OUMUSERS', 'H', 'OUMUSERS.htm', 'OUMUSERS HTML Help Topic', CURRENT_USER, current_timestamp),
	('OWEACPLN', 'H', 'OWEACPLN.htm', 'OWEACPLN HTML Help Topic', CURRENT_USER, current_timestamp),
	('OCDALIAS', 'E', 'ERD\OCDALIAS.htm', 'OCDALIAS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDALTCC', 'E', 'ERD\OCDALTCC.htm', 'OCDALTCC ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDCLOSE', 'E', 'ERD\OCDCLOSE.htm', 'OCDCLOSE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDCSCH', 'E', 'ERD\OCDCSCH.htm', 'OCDCSCH ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDEDEMP', 'E', 'ERD\OCDEDEMP.htm', 'OCDEDEMP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDINTAK', 'E', 'ERD\OCDINTAK.htm', 'OCDINTAK ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDIPLAN', 'E', 'ERD\OCDIPLAN.htm', 'OCDIPLAN ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDLANGS', 'E', 'ERD\OCDLANGS.htm', 'OCDLANGS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDNOQUE', 'E', 'ERD\OCDNOQUE.htm', 'OCDNOQUE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDPROGR', 'E', 'ERD\OCDPROGR.htm', 'OCDPROGR ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDRLFCC', 'E', 'ERD\OCDRLFCC.htm', 'OCDRLFCC ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDSABUS', 'E', 'ERD\OCDSABUS.htm', 'OCDSABUS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDXPROG', 'E', 'ERD\OCDXPROG.htm', 'OCDXPROG ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCIIPLAN', 'E', 'ERD\OCIIPLAN.htm', 'OCIIPLAN ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCIOCNOT', 'E', 'ERD\OCIOCNOT.htm', 'OCIOCNOT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCISCATA', 'E', 'ERD\OCISCATA.htm', 'OCISCATA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMCNPER', 'E', 'ERD\OCMCNPER.htm', 'OCMCNPER ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMCPREV', 'E', 'ERD\OCMCPREV.htm', 'OCMCPREV ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMNOQUE', 'E', 'ERD\OCMNOQUE.htm', 'OCMNOQUE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMSERVI', 'E', 'ERD\OCMSERVI.htm', 'OCMSERVI ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMSPRAC', 'E', 'ERD\OCMSPRAC.htm', 'OCMSPRAC ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMSVACP', 'E', 'ERD\OCMSVACP.htm', 'OCMSVACP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMWORKS', 'E', 'ERD\OCMWORKS.htm', 'OCMWORKS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCMXPROG', 'E', 'ERD\OCMXPROG.htm', 'OCMXPROG ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDADMIS', 'E', 'ERD\OIDADMIS.htm', 'OIDADMIS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDBSIAP', 'E', 'ERD\OIDBSIAP.htm', 'OIDBSIAP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDBSTRN', 'E', 'ERD\OIDBSTRN.htm', 'OIDBSTRN ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDBUTAB', 'E', 'ERD\OIDBUTAB.htm', 'OIDBUTAB ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDCAPPR', 'E', 'ERD\OIDCAPPR.htm', 'OIDCAPPR ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDCHLOC', 'E', 'ERD\OIDCHLOC.htm', 'OIDCHLOC ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDCHOLO', 'E', 'ERD\OIDCHOLO.htm', 'OIDCHOLO ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDCIPON', 'E', 'ERD\OIDCIPON.htm', 'OIDCIPON ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDCNOTE', 'E', 'ERD\OIDCNOTE.htm', 'OIDCNOTE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDDPROP', 'E', 'ERD\OIDDPROP.htm', 'OIDDPROP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDEHLOC', 'E', 'ERD\OIDEHLOC.htm', 'OIDEHLOC ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDESCAP', 'E', 'ERD\OIDESCAP.htm', 'OIDESCAP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDIEPLV', 'E', 'ERD\OIDIEPLV.htm', 'OIDIEPLV ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDINCDE', 'E', 'ERD\OIDINCDE.htm', 'OIDINCDE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDINTMV', 'E', 'ERD\OIDINTMV.htm', 'OIDINTMV ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDISSUE', 'E', 'ERD\OIDISSUE.htm', 'OIDISSUE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDISTAT', 'E', 'ERD\OIDISTAT.htm', 'OIDISTAT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDITRAN', 'E', 'ERD\OIDITRAN.htm', 'OIDITRAN ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDMBRDT', 'E', 'ERD\OIDMBRDT.htm', 'OIDMBRDT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDMHIST', 'E', 'ERD\OIDMHIST.htm', 'OIDMHIST ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDMPITM', 'E', 'ERD\OIDMPITM.htm', 'OIDMPITM ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDOICAP', 'E', 'ERD\OIDOICAP.htm', 'OIDOICAP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDOICUS', 'E', 'ERD\OIDOICUS.htm', 'OIDOICUS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDOMAIL', 'E', 'ERD\OIDOMAIL.htm', 'OIDOMAIL ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDONONA', 'E', 'ERD\OIDONONA.htm', 'OIDONONA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDOWREL', 'E', 'ERD\OIDOWREL.htm', 'OIDOWREL ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDPACTI', 'E', 'ERD\OIDPACTI.htm', 'OIDPACTI ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDPAWLI', 'E', 'ERD\OIDPAWLI.htm', 'OIDPAWLI ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDPIDEN', 'E', 'ERD\OIDPIDEN.htm', 'OIDPIDEN ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDPINFO', 'E', 'ERD\OIDPINFO.htm', 'OIDPINFO ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDPWAIT', 'E', 'ERD\OIDPWAIT.htm', 'OIDPWAIT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDRHLOC', 'E', 'ERD\OIDRHLOC.htm', 'OIDRHLOC ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDRTCON', 'E', 'ERD\OIDRTCON.htm', 'OIDRTCON ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDSCEXM', 'E', 'ERD\OIDSCEXM.htm', 'OIDSCEXM ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDSCMOV', 'E', 'ERD\OIDSCMOV.htm', 'OIDSCMOV ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDSHLOG', 'E', 'ERD\OIDSHLOG.htm', 'OIDSHLOG ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDSIAPP', 'E', 'ERD\OIDSIAPP.htm', 'OIDSIAPP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDSTABS', 'E', 'ERD\OIDSTABS.htm', 'OIDSTABS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDSTEST', 'E', 'ERD\OIDSTEST.htm', 'OIDSTEST ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDSTOJU', 'E', 'ERD\OIDSTOJU.htm', 'OIDSTOJU ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDTPCON', 'E', 'ERD\OIDTPCON.htm', 'OIDTPCON ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDTROJU', 'E', 'ERD\OIDTROJU.htm', 'OIDTROJU ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDTRWJU', 'E', 'ERD\OIDTRWJU.htm', 'OIDTRWJU ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDUNCTA', 'E', 'ERD\OIDUNCTA.htm', 'OIDUNCTA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDVCONT', 'E', 'ERD\OIDVCONT.htm', 'OIDVCONT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDVIRES', 'E', 'ERD\OIDVIRES.htm', 'OIDVIRES ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDVISIT', 'E', 'ERD\OIDVISIT.htm', 'OIDVISIT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIDVTOUR', 'E', 'ERD\OIDVTOUR.htm', 'OIDVTOUR ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIICMOCI', 'E', 'ERD\OIICMOCI.htm', 'OIICMOCI ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIDMOVE', 'E', 'ERD\OIIDMOVE.htm', 'OIIDMOVE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIGRIEV', 'E', 'ERD\OIIGRIEV.htm', 'OIIGRIEV ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIHISCO', 'E', 'ERD\OIIHISCO.htm', 'OIIHISCO ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIINLOG', 'E', 'ERD\OIIINLOG.htm', 'OIIINLOG ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIISCOU', 'E', 'ERD\OIIISCOU.htm', 'OIIISCOU ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIOICUS', 'E', 'ERD\OIIOICUS.htm', 'OIIOICUS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIPCLOC', 'E', 'ERD\OIIPCLOC.htm', 'OIIPCLOC ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIPCTRA', 'E', 'ERD\OIIPCTRA.htm', 'OIIPCTRA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIPTRAN', 'E', 'ERD\OIIPTRAN.htm', 'OIIPTRAN ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIISCHED', 'E', 'ERD\OIISCHED.htm', 'OIISCHED ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIISHLOG', 'E', 'ERD\OIISHLOG.htm', 'OIISHLOG ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIITGDET', 'E', 'ERD\OIITGDET.htm', 'OIITGDET ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIVISIT', 'E', 'ERD\OIIVISIT.htm', 'OIIVISIT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIIWLTWJ', 'E', 'ERD\OIIWLTWJ.htm', 'OIIWLTWJ ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMADMIS', 'E', 'ERD\OIMADMIS.htm', 'OIMADMIS ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMCOUNT', 'E', 'ERD\OIMCOUNT.htm', 'OIMCOUNT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMCTACT', 'E', 'ERD\OIMCTACT.htm', 'OIMCTACT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMIEPLV', 'E', 'ERD\OIMIEPLV.htm', 'OIMIEPLV ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMILOCA', 'E', 'ERD\OIMILOCA.htm', 'OIMILOCA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMISREA', 'E', 'ERD\OIMISREA.htm', 'OIMISREA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMISSUE', 'E', 'ERD\OIMISSUE.htm', 'OIMISSUE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMOICMP', 'E', 'ERD\OIMOICMP.htm', 'OIMOICMP ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMOICOI', 'E', 'ERD\OIMOICOI.htm', 'OIMOICOI ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMPLDUR', 'E', 'ERD\OIMPLDUR.htm', 'OIMPLDUR ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMPRFCA', 'E', 'ERD\OIMPRFCA.htm', 'OIMPRFCA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMPRFCO', 'E', 'ERD\OIMPRFCO.htm', 'OIMPRFCO ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMSLEVL', 'E', 'ERD\OIMSLEVL.htm', 'OIMSLEVL ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMULOCA', 'E', 'ERD\OIMULOCA.htm', 'OIMULOCA ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMVDTSL', 'E', 'ERD\OIMVDTSL.htm', 'OIMVDTSL ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMVLIMT', 'E', 'ERD\OIMVLIMT.htm', 'OIMVLIMT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OIMWORKR', 'E', 'ERD\OIMWORKR.htm', 'OIMWORKR ERD Help Topic', CURRENT_USER, current_timestamp),
	('OMUVREST', 'E', 'ERD\OMUVREST.htm', 'OMUVREST ERD Help Topic', CURRENT_USER, current_timestamp),
	('OSIPSEAR', 'E', 'ERD\OSIPSEAR.htm', 'OSIPSEAR ERD Help Topic', CURRENT_USER, current_timestamp),
	('OSISTGKW', 'E', 'ERD\OSISTGKW.htm', 'OSISTGKW ERD Help Topic', CURRENT_USER, current_timestamp),
	('OUMEMOVE', 'E', 'ERD\OUMEMOVE.htm', 'OUMEMOVE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OUMINOUT', 'E', 'ERD\OUMINOUT.htm', 'OUMINOUT ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDADDRE', 'E', 'ERD\OCDADDRE.htm', 'OCDADDRE ERD Help Topic', CURRENT_USER, current_timestamp),
	('OCDALERT', 'E', 'ERD\OCDALERT.htm', 'OCDALERT ERD Help Topic', CURRENT_USER, current_timestamp);
	
---- version: sysconjusticesystems/online_help:1.11
---- insert screens: 25 Rows (total 247 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url, help_desc,create_user_id,create_datetime) 
VALUES
     ('OIDADMIS', 'H', 'OIDADMIS.htm', 'Reception/Admission HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMPRFCO', 'H', 'OIMPRFCO.htm', 'Maintain Profile Codes HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMBUNDL', 'H', 'OUMBUNDL.htm', 'Maintain Property Bundles HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMSTATU', 'H', 'OIMSTATU.htm', 'Maintain Statutes HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIDRELSC', 'H', 'OIDRELSC.htm', 'Release Schedules HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIIWLTWJ', 'H', 'OIIWLTWJ.htm', 'Within Jurisdiction Waiting List HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIDPAWLI', 'H', 'OIDPAWLI.htm', 'Activity Waiting List HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIDOFFOB', 'H', 'OIDOFFOB.htm', 'Inmate Observations HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIIOFFOB', 'H', 'OIIOFFOB.htm', 'Inmate Observations Inquiry HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMDSPWD', 'H', 'OCMDSPWD.htm', 'Maintain Default Staff Position Workloads HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMSMUGA', 'H', 'OUMSMUGA.htm', 'Staff Member Access HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMPERSD', 'H', 'OUMPERSD.htm', 'License Details HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUISDIRE', 'H', 'OUISDIRE.htm', 'Staff Directory HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMPCONF', 'H', 'OCMPCONF.htm', 'Component Behaviour HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMWMENU', 'H', 'OUMWMENU.htm', 'Screen Flows HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMEEMOV', 'H', 'OUMEEMOV.htm', 'Edit External Moves HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMAGYRG', 'H', 'OUMAGYRG.htm', 'Agency Location Regions HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMHLHIS', 'H', 'OUMHLHIS.htm', 'Housing Location History HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMINSDB', 'H', 'OUMINSDB.htm', 'Module Dashboard Association HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OMSHELP', 'H', 'OMSHELP.htm', 'Help HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OLISET', 'H', 'OLISET.htm', 'Branding HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMCDTAB', 'H', 'OUMCDTAB.htm', 'Available Copy Tables HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMAGENC', 'H', 'OUMAGENC.htm', 'External Agencies/Corporates HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMPURGE', 'H', 'OUMPURGE.htm', 'Purge Offenders HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMBADMI', 'H', 'OUMBADMI.htm', 'Bookings Administration HTML Help Topic', CURRENT_USER, current_timestamp);

---- version: sysconjusticesystems/online_help:1.12
---- insert screens: 0 Rows (total 247 Rows) --- Comment: Fixed screens

---- version: sysconjusticesystems/online_help:1.13
---- insert screens: 14 Rows (total 261 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url, help_desc,create_user_id,create_datetime) 
VALUES								
     ('OIMADMIS', 'H', 'OIMADMIS.htm', 'Maintain Admissions HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMPRFCA', 'H', 'OIMPRFCA.htm', 'Maintain Profile Category/Types HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMCTACT', 'H', 'OIMCTACT.htm', 'Maintain Person Contacts HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMRCODE', 'H', 'OUMRCODE.htm', 'OMS Reference Codes HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMHOCOD', 'H', 'OUMHOCOD.htm', 'Maintain Offense Categories HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMOFFEN', 'H', 'OIMOFFEN.htm', 'Maintain Charges HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMSTATS', 'H', 'OCMSTATS.htm', 'Maintain Statuses HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMCUSTS', 'H', 'OIMCUSTS.htm', 'Maintain Custody Statuses HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMLESET', 'H', 'OCMLESET.htm', 'Legals Settings HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMSREQS', 'H', 'OIMSREQS.htm', 'Maintain Sentences HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMSATYP', 'H', 'OIMSATYP.htm', 'Sentence Adjustment Types HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMCRTOR', 'H', 'OIMCRTOR.htm', 'Maintain Court Order Types HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMMEROF', 'H', 'OUMMEROF.htm', 'Merge Offenders HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUIMERGE', 'H', 'OUIMERGE.htm', 'Merge Transaction Inquiry HTML Help Topic', CURRENT_USER, current_timestamp);
	 
	 
---- version: sysconjusticesystems/online_help:1.14
---- insert screens: 18 Rows (total 279 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url, help_desc,create_user_id,create_datetime)
VALUES								
     ('OUMSYPFL', 'H', 'OUMSYPFL.htm', 'System Profiles HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMMENUS', 'H', 'OUMMENUS.htm', 'Menus HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMAGYHT', 'H', 'OUMAGYHT.htm', 'Agency Location History HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OTMLOCKR', 'H', 'OTMLOCKR.htm', 'Module Lock Removal HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMAGLOC', 'H', 'OUMAGLOC.htm', 'Agency Locations HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMRAREA', 'H', 'OUMRAREA.htm', 'Regions/Areas HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMACASE', 'H', 'OUMACASE.htm', 'Caseload HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMSYSET', 'H', 'OUMSYSET.htm', 'System Settings HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMRELMD', 'H', 'OUMRELMD.htm', 'Related Modules HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMSYLAB', 'H', 'OUMSYLAB.htm', 'System Labels HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMFORMS', 'H', 'OUMFORMS.htm', 'Form Access HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OMUNVARY', 'H', 'OMUNVARY.htm', 'Name Variations (Name Search) HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OUMRESTA', 'H', 'OUMRESTA.htm', 'Restricted Access HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OYMHOLID', 'H', 'OYMHOLID.htm', 'Holidays HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMSERVI', 'H', 'OCMSERVI.htm', 'Services HTML Help Topic', CURRENT_USER, current_timestamp),
     ('UPDOFFID', 'H', 'UPDOFFID.htm', 'Update Offender ID HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMSHIER', 'H', 'OCMSHIER.htm', 'Staff Hierarchy HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMORCOD', 'H', 'OCMORCOD.htm', 'Offense Result Codes HTML Help Topic', CURRENT_USER, current_timestamp);

---- ersion: sysconjusticesystems/online_help:1.15
---- insert screens: 14 Rows (total 293 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url, help_desc,create_user_id,create_datetime)
VALUES
     ('OCMCONDI', 'H', 'OCMCONDI.htm', 'Maint. Conditions HTML Help Topic', CURRENT_USER, current_timestamp),					
     ('OIMRELSC', 'H', 'OIMRELSC.htm', 'Release Schedule SettingsHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMMHOLO', 'H', 'OIMMHOLO.htm', 'Housing LocationsHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMULOCA', 'H', 'OIMULOCA.htm', 'Internal Location UsagesHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMCPREV', 'H', 'OCMCPREV.htm', 'Maint. Case Plan Review Periods HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMCNPER', 'H', 'OCMCNPER.htm', 'Maintain Case Note PermissionsHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMCOUNT', 'H', 'OIMCOUNT.htm', 'Maintain CountsHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMVDTSL', 'H', 'OIMVDTSL.htm', 'Maint. Day/Time SlotsHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMVLIMT', 'H', 'OIMVLIMT.htm', 'Maint. Visit LimitsHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMOICMP', 'H', 'OIMOICMP.htm', 'Maint. OIC Maximum PenaltiesHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OIMIITPS', 'H', 'OIMIITPS.htm', 'Maintain Issues PermissionsHTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMNOQUE', 'H', 'OCMNOQUE.htm', 'Maintain Assessment Questionnaires', CURRENT_USER, current_timestamp),
     ('OIMSLEVL', 'H', 'OIMSLEVL.htm', 'Maintain Assessment Scores', CURRENT_USER, current_timestamp),
     ('OIMILOCA', 'H', 'OIMILOCA.htm', 'Maintain Internal Locations', CURRENT_USER, current_timestamp);

---- Current version: sysconjusticesystems/online_help:1.16
---- insert screens: 12 Rows (total 305 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url, help_desc,create_user_id,create_datetime)
VALUES								
     ('OUMEMOVE', 'H', 'OUMEMOVE.htm', 'Movement Type/Reasons HTML Help Topic', CURRENT_USER, current_timestamp),
     ('OCMWORKS', 'H', 'OCMWORKS.htm', 'Maint. Case Notes', CURRENT_USER, current_timestamp),
     ('OIMPLDUR', 'H', 'OIMPLDUR.htm', 'Maint. Placement Durations', CURRENT_USER, current_timestamp),
     ('OIMIEPLV', 'H', 'OIMIEPLV.htm', 'Incentives & Earned Privileges', CURRENT_USER, current_timestamp),
     ('OIMOICOI', 'H', 'OIMOICOI.htm', 'Maint. OIC Offenses', CURRENT_USER, current_timestamp),
     ('OIMISSUE', 'H', 'OIMISSUE.htm', 'Maint. Inmate Issues', CURRENT_USER, current_timestamp),
     ('OIMTGNGS', 'H', 'OIMTGNGS.htm', 'Maint. STG Groups', CURRENT_USER, current_timestamp),
     ('OIDFIXAD', 'H', 'OIDFIXAD.htm', 'Fixed Assets Details', CURRENT_USER, current_timestamp),
     ('OIMROUTE', 'H', 'OIMROUTE.htm', 'Maintain Routes', CURRENT_USER, current_timestamp),
     ('OIMWORKR', 'H', 'OIMWORKR.htm', 'Maintain Work Release', CURRENT_USER, current_timestamp),
     ('OCMPSSET', 'H', 'OCMPSSET.htm', 'Programs and Services Settings', CURRENT_USER, current_timestamp),
     ('OCMPSPAY', 'H', 'OCMPSPAY.htm', 'Maintain Program and Services Pay', CURRENT_USER, current_timestamp);

