INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
 SELECT 'PROSDEAC', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, 'OMS_OWNER', NULL 
 WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'PROSDEAC' AND role_id = 444);

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
 SELECT 'OCDSENCH', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, 'OMS_OWNER', NULL 
 WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OCDSENCH' AND role_id = 444);

DELETE FROM MODULE_PRIVILEGES
WHERE module_name = 'OIDSENHY';

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
 SELECT 'OCMDSPWD', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, 'OMS_OWNER', NULL 
 WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OCMDSPWD' AND role_id = 444); 


INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
 SELECT 'OCMLESET',444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, 'OMS_OWNER', NULL 
 WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OCMLESET' AND role_id = 444); 

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
 SELECT 'OIDPAROE', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, 'OMS_OWNER', NULL 
 WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OIDPAROE' AND role_id = 444); 


INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
 SELECT 'OCDONOST', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, 'OMS_OWNER', NULL 
 WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OCDONOST' AND role_id = 444); 