package net.syscon.s4.pkgs.purge_offender_bookings;

import java.math.BigDecimal;
import java.util.List;

import net.syscon.s4.cm.programsservices.OffenderCourseApptGrp;
import net.syscon.s4.common.beans.Addresses;
import net.syscon.s4.common.beans.Images;
import net.syscon.s4.common.beans.OffenderAssocPrtyContact;
import net.syscon.s4.common.beans.OffenderBookings;
import net.syscon.s4.common.beans.OffenderClothingIssue;
import net.syscon.s4.common.beans.OffenderCurfews;
import net.syscon.s4.common.beans.OffenderDrugAdmission;
import net.syscon.s4.common.beans.OffenderDrugSample;
import net.syscon.s4.common.beans.OffenderExternalMovements;
import net.syscon.s4.common.beans.OffenderHwd;
import net.syscon.s4.common.beans.OffenderOicSanctions;
import net.syscon.s4.common.beans.Orders;
import net.syscon.s4.im.beans.AgyIncInvestigations;
import net.syscon.s4.im.beans.CasePlans;
import net.syscon.s4.im.beans.CourseActivities;
import net.syscon.s4.im.beans.OffenderCaseNotes;
import net.syscon.s4.im.beans.OffenderCases;
import net.syscon.s4.im.beans.OffenderGrievances;
import net.syscon.s4.im.beans.OffenderPrgObligations;
import net.syscon.s4.im.beans.OffenderProgramProfiles;
import net.syscon.s4.im.beans.OffenderStgAffiliations;
import net.syscon.s4.im.beans.ReleasePlans;
import net.syscon.s4.im.incidentsoic.beans.AgencyIncidentCharges;
import net.syscon.s4.im.incidentsoic.beans.AgencyIncidentParties;
import net.syscon.s4.im.incidentsoic.beans.OicHearingResults;
import net.syscon.s4.im.incidentsoic.beans.OicHearings;
import net.syscon.s4.inst.booking.beans.OffenderContactPersons;
import net.syscon.s4.inst.casemanagement.beans.OffenderCaseConditions;
import net.syscon.s4.inst.casemanagement.beans.OffenderCriminogenicNeeds;
import net.syscon.s4.inst.casemanagement.beans.PlanDetails;
import net.syscon.s4.inst.casemanagement.beans.WorkFlows;
import net.syscon.s4.inst.classification.beans.AssessmentResults;
import net.syscon.s4.inst.incidentsoic.maintenance.OffenderOicAppealIncidents;
import net.syscon.s4.inst.institutionalactivities.maintenance.beans.CourseSchedules;
import net.syscon.s4.inst.legals.beans.OffenderProceedings;
import net.syscon.s4.inst.legals.beans.OffenderSentences;
import net.syscon.s4.inst.legalscreens.maintenance.bean.OffenderCharges;
import net.syscon.s4.inst.property.bean.OffenderPptyItemTxns;
import net.syscon.s4.inst.schedules.bean.CourtEvents;
import net.syscon.s4.inst.schedules.bean.OffenderIndSchedules;
import net.syscon.s4.inst.schedules.bean.VOffExtMovements;
import net.syscon.s4.inst.visitsmanagement.beans.VOffenderVisits;
import net.syscon.s4.pkgs.OffenderAssociatedParties;
import net.syscon.s4.triggers.HdcRequestReferrals;
import net.syscon.s4.triggers.OffenderCourseAttendances;
import net.syscon.s4.triggers.OffenderOasysSections;
import net.syscon.s4.triggers.OffenderPtr;
import net.syscon.s4.triggers.QmActivitiesIns;

public interface PurgeOffenderBookingsRepository {
	List<AgencyIncidentParties> prAgencyIncidentParties(Integer pOffenderBookId);
	List<AgyIncInvestigations> prAgyIncInvestigations(Integer pAgencyIncidentId, Integer partySeq);
	List<OffenderBookings> getOffenderBookId(Long pOffenderBookId);
	List<AgencyIncidentCharges> getAgencyIncidentCharges(Integer pAgencyIncidentId,Integer partySeq);
	List<OicHearingResults> prOicHearingResults1(BigDecimal pOicHearingId);
	List<OffenderOicAppealIncidents> prOffenderOicAppelIncidnts(Integer oicHearingId, Integer resultSeq);
	Integer prOffenderOicAppealPenltis(Integer oicApprealId, Integer oicHearingId,Integer resultSeq, String modifyUserId);
	Integer deleteOffenderOicAppealIncidents(Integer oicHearingId, Integer resultSeq, String modifyUserId);
	List<OffenderOicSanctions> prOffenderOicSanctions1(Integer oicHearingId, Integer resultSeq);
	List<OffenderOicSanctions> prOffenderOicSanctions2(Integer consecutiveOffenderBookId,Integer consecutiveSanctionSeq);
	Integer prOffenderOicSancReviews(BigDecimal pOffenderBookId, BigDecimal pSanctionSeq, String modifyUserId);
	Integer deleteOffenderOicSanctions(Integer oicHearingId, Integer resultSeq, String modifyUserId);
	Integer deleteOicHearingResults(BigDecimal pOicHearingId, String modifyUserId);
	List<OicHearingResults> prOicHearingResults(BigDecimal agencyIncidentId, BigDecimal chargeSeq);
	Integer deleteprOicHearingResults(BigDecimal agencyIncidentId, BigDecimal chargeSeq, String modifyUserId);
	Integer deleteprAgencyIncidentCharges(Integer pAgencyIncidentId, Integer partySeq, String modifyUserId);
	Integer deleteprAgyIncInvStatements(Integer agyIncInvestigationId, String modifyUserId);
	Integer deleteprAgyIncInvestigations(Integer pAgencyIncidentId, Integer partySeq, String modifyUserId);
	List<OffenderGrievances> prOffenderGrievances1(Long agencyIncidentId, Long partySeq);
	Integer deleteprOffenderGrievanceTxns(Long grievanceId, String modifyUserId);
	Integer deleteprOffenderGrievStaffs(Long grievanceId, String modifyUserId);
	Integer deleteprOffenderGrievances1(Long agencyIncidentId, Long partySeq, String modifyUserId);
	Integer deleteprOffenderIncidentDetails(BigDecimal pAgencyIncidentId, BigDecimal pPartySeq, String modifyUserId);
	List<OicHearings> prOicHearings(Integer oicIncidentId);
	Integer deleteprOicHearingComments(BigDecimal pOicHearingId, String modifyUserId);
	Integer deleteprOicHearingNotices(Integer oicHearingId, String modifyUserId);
	Integer deleteprOicHearingReviews(BigDecimal oicHearingId, String modifyUserId);
	Integer deleteprAgencyIncidentParties(Integer pOffenderBookId, String modifyUserId);
	Integer deleteprArrests(Long offenderBookId, String modifyUserId);
	Integer deleteprAssignments(Long offenderBookId, String modifyUserId);
	Integer deleteprBedAssignmentHistories(Long offenderBookId, String modifyUserId);
	Integer deleteprCaseAssociatedPersons(Long offenderBookId, String modifyUserId);
	Integer deleteprCaseNotes(Long offenderBookId, String modifyUserId);
	List<CasePlans> prCasePlans(Long offenderBookId);
	Integer deleteprAssessmentSummaries(Long offenderBookId, Long casePlanId, String modifyUserId);
	List<OffenderCaseConditions> prOffenderCaseConditions(Long offenderBookId, Long casePlanId);
	Integer deleteprOffenderActionPlans(BigDecimal offCaseCondId, String modifyUserId);
	Integer deleteprOffenderCaseConditions(Long offenderBookId, Long casePlanId, String modifyUserId);
	List<OffenderCriminogenicNeeds> prOffenderCriminogenicNeeds(BigDecimal offenderBookId, BigDecimal casePlanId);
	Integer deleteprOffenderCriminogenicNeeds(BigDecimal offenderBookId, BigDecimal casePlanId, String modifyUserId);
	List<PlanDetails> prPlanDetails(Long offenderBookId, Long casePlanId);
	Integer deleteprCaseworkSteps(Long offenderBookId, Long casePlanId, Long detailSeq, String modifyUserId);
	Integer deleteprPlanDetails(Long offenderBookId, Long casePlanId, String modifyUserId);
	Integer deleteprCasePlans(Long offenderBookId, String modifyUserId);
	List<CourtEvents> prCourtEvents(Integer offenderBookId);
	Integer deleteprCourtEventCharges(BigDecimal eventId, String modifyUserId);
	Integer deleteprCourtEventSentences(BigDecimal eventId, String modifyUserId);
	Integer deleteprLinkCaseTxns(BigDecimal eventId, String modifyUserId);
	Integer deleteprCourtEvents(Integer offenderBookId, String modifyUserId);
	Integer deleteprDocumentTemplateQueues(BigDecimal offenderBookId, String modifyUserId);
	Integer updateprGlTransactions(BigDecimal offenderBookId);
	List<HdcRequestReferrals> prHdcRequestReferrals(Long offenderBookId);
	Integer deleteprHdcBoardDecisions(BigDecimal pHdcRequestReferralId, String modifyUserId);
	Integer deleteprHdcGovernorDecisions(BigDecimal pHdcRequestReferralId, String modifyUserId);
	Integer deleteprHdcProbStaffComments(BigDecimal pHdcRequestReferralId, String modifyUserId);
	Integer deleteprHdcProbStaffResponses(BigDecimal pHdcRequestReferralId, String modifyUserId);
	List<HdcRequestReferrals> prHdcRequestReferrals1(Long parentHdcRequestReferralId);
	Integer deleteprHdcRequestReferrals1(Long parentHdcRequestReferralId, String modifyUserId);
	Integer deleteprHdcRequestReferrals(Long offenderBookId, String modifyUserId);
	Integer deleteprIncidentCaseParties(BigDecimal offenderBookId, String modifyUserId);
	Integer deleteprIwpDocuments(BigDecimal offenderBookId, String modifyUserId);
	Integer deleteprOffenderActivityEvents(BigDecimal offenderBookId, String modifyUserId);
	Integer deleteprOffenderAlerts(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderAssessments(Long offenderBookId, String modifyUserId);
	List<OffenderAssociatedParties> prOffenderAssociatedParties(Long offenderBookId);
	Integer deleteprOffenderAssocPartyNotes(Long associatedPartyId, String modifyUserId);
	List<OffenderAssocPrtyContact>  prOffenderAssocPrtyContcts(Long associatedPartyId);
	Integer deleteprOffenderAssocPCntNotifs(Long associatedPartyId, Long partySeq, String modifyUserId);
	Integer deleteprOffenderAssocPrtyContcts(Long associatedPartyId, String modifyUserId);
	Integer deleteprOffenderAssocPNotifs(Long associatedPartyId, String modifyUserId);
	Integer deleteprOffenderAssociatedParties(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderAuthorisdVisitors(BigDecimal offenderBookId, String modifyUserId);
	Integer deleteprOffenderAthorisdVisitors1(BigDecimal offenderBookId, String modifyUserId);
	Integer deleteprOffenderBailDetails(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderBookingAgyLocs(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderBookingDetails(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderBookingEvents(Long offenderBookId, String modifyUserId);
	List<OffenderCases> prOffenderCases(Long offenderBookId);
	List<CourtEvents> prCourtEvents1(BigDecimal offenderBookId);
	Integer deleteprCourtEvents1(BigDecimal eventID, String modifyUserId);
	Integer deleteprLinkCaseTxns1(BigDecimal eventId);
	Integer deleteprLinkCaseTxns2(BigDecimal eventId, String modifyUserId);
	List<OffenderAssociatedParties> prOffenderAssociatedPartis1(BigDecimal eventId);
	List<OffenderCaseNotes> prOffenderCaseNotes(Integer offenderBookId);
	Integer deleteprOffenderCaseNoteSents1(Integer caseNoteId, String modifyUserId);
	Integer deleteprOffCaseNoteRecipients(Integer caseNoteId, String modifyUserId);
	Integer deleteprOffenderCaseNotes(Integer offenderBookId, String modifyUserId);
	List<OffenderCharges> prOffenderCharges(Long offenderBookId);
	Integer deleteprCourtEventCharges1(BigDecimal pOffenderChargeId, String modifyUserId);
	Integer deleteprLinkCaseTxns3(BigDecimal pOffenderChargeId, String modifyUserId);
	Integer deleteprOffenderSentenceCharges(BigDecimal pOffenderChargeId, String modifyUserId);
	Integer deleteprOffenderCharges(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderCipDetails(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderClassPrograms(Long offenderBookId, String modifyUserId);
	Integer prOffenderClothes(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderClothingBundles(Long offenderBookId, String modifyUserId);
	List<OffenderClothingIssue> prOffenderClothingIssue(Long offenderBookId);
	Integer deleteprOffenderClothingItems1(Long offenderClothingIssueId, String modifyUserId);
	Integer deleteprOffenderClothingIssue(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderClothingItems(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderCodefendants(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderCodefendants1(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderComments(Long offenderBookId, String modifyUserId);
	Integer deleteprOffendrCommnityConditions(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderCommSupHistories(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderCompactAgreements(Long offenderBookId, String modifyUserId);
	List<OffenderContactPersons> prOffenderContactPersons(BigDecimal offenderBookId);
	Integer deleteprOffenderPersonRestricts(Integer offenderContactPersonId, String modifyUserId);
	Integer deleteprOffenderContactPersons(BigDecimal offenderBookId, String modifyUserId);
	List<OffenderCourseAttendances> prOffenderCourseAttendances(Long offenderBookId);
	Integer deleteprOffenderCourseSkills(Long eventId, String modifyUserId);
	Integer deleteprOffenderCourseAttendances(Long offenderBookId, String modifyUserId);
	List<OffenderCurfews> prOffenderCurfews(BigDecimal offenderBookId);
	List<OffenderCurfews> prCurfewAddresses(BigDecimal pOffenderCurfewId);
	Integer deleteprCurfewAddressOccupants(BigDecimal pOffenderCurfewId,String modifyUserId);
	Integer deleteprCurfewAddresses(BigDecimal pOffenderCurfewId, String modifyUserId);
	Integer deleteprHdcPrisonStaffComments(BigDecimal pOffenderCurfewId, String modifyUserId);
	List<HdcRequestReferrals> prHdcRequestReferrals2(BigDecimal pOffenderCurfewId);
	Integer deleteprHdcRequestReferrals2(BigDecimal pOffenderCurfewId, String modifyUserId);
	Integer deleteprOffenderCurfews(BigDecimal offenderBookId, String modifyUserId);
	List<OffenderDrugAdmission> prOffenderDrugAdmissions(BigDecimal offenderBookId);
	Integer deleteprOffenderDrugAdmDrugs(Long offenderDrugAdmissionId, String modifyUserId);
	Integer deleteprOffenderDrugAdmissions(BigDecimal offenderBookId, String modifyUserId);
	List<OffenderDrugSample> prOffenderDrugSamples(BigDecimal offenderBookId);
	Integer deleteprOffenderDrugResults(Long offenderDrugSampleId, String modifyUserId);
	Integer deleteprOffenderDrugSamples(BigDecimal offenderBookId, String modifyUserId);
	Integer deleteprOffenderEducations(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderEmployments(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderEscapes(Integer offenderBookId, String modifyUserId);
	Integer deleteprOffenderExpenses(BigDecimal offenderBookId, String modifyUserId);
	Integer deleteprOffenderExternalMovements(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderFileLocations(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderGangAffiliations(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderGangEvidences(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderGangInvests(Long offenderBookId, String modifyUserId);
	List<OffenderGrievances> prOffenderGrievances(Long offenderBookId);
	Integer deleteprOffenderGrievances(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderHospitalVisits(Long offenderBookId, String modifyUserId);
	List<OffenderHwd> prOffenderHwd(Long offenderBookId);
	Integer deleteprOffenderHwdCharges(Long hwdId, String modifyUserId);
	Integer deleteprOffenderHwdHty(Long hwdId, String modifyUserId);
	Integer deleteprOffenderHwd(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderIdentifyingMarks(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderIepLevels(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderImages(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderImprisonStatuses(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderIncome(Long offenderBookId, String modifyUserId);
	List<OffenderIndSchedules> prOffenderIndSchedules(Integer offenderBookId);
	Integer deleteprOffenderIndSchSents1(Integer eventId, String modifyUserId);
	Integer deleteprOffenderIndSchWaitLists(Integer eventId, String modifyUserId);
	Integer deleteprOffenderIndSchedules(Integer offenderBookId, String modifyUserId);
	List<OffenderExternalMovements> prOffenderInternalMovements(Long offenderBookId);
	Integer deleteprOffenderIntMovPersons(Long offenderBookId, Long movementSeq, String modifyUserId);
	Integer deleteprOffenderInternalMovements(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderInternalStatuses(Integer offenderBookId, String modifyUserId);
	Integer deleteprOffenderInterventionTiers(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderLanguages(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderLiabilities(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderMailLogs(Long offenderBookId);
	Integer deleteprOffenderMailRestrictions(Long offenderBookId, String modifyUserId);
	Integer deleteprOffendrMilitryDiscCtions(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderMilitaryRecords(Long offenderBookId, String modifyUserId);
	Integer prOffenderMilitaryWarZones(Long offenderBookId, String modifyUserId);
	List<OffenderOicSanctions> prOffenderOasysPlans(Long offenderBookId);
	Integer deleteprOffenderOasysConcerns(Long offenderBookId,Long pPlanSeq, String modifyUserId);
	Integer deleteprOffenderOsysRiskToOthrs(Long offenderBookId, Long pPlanSeq, String modifyUserId);
	List<OffenderOasysSections> prOffenderOasysSections(Long offenderBookId, Integer planSeq);
	List<OffenderOasysSections> prOffenderOasysObjectives(Long offenderBookId, Integer planSeq,String sectionCode);
	List<OffenderOasysSections> prOffenderOasysActions(BigDecimal objectiveId);
	Integer deleteprOffenderOasysSupervisions(BigDecimal objectiveId,Long actionseq);
	Integer deleteprOffenderOasysActions(BigDecimal objectiveId, String modifyUserId);
	Integer deleteprOffenderOasysObjectives(Long offenderBookId, Integer planSeq,String sectionCode, String modifyUserId);
	List<OffenderOicSanctions> prOffenderOicSanctions(Integer offenderBookId);
	Integer deleteprOffenderOicSanctions(Integer offenderBookId, String modifyUserId);
	List<OffenderOicSanctions> prOffenderParoleHearings(Long offenderBookId);
	List<OffenderOicSanctions> prOffenderParoleDecisions(Long offenderBookId, Long paroleHearingSeq);
	Integer deleteprOffenderParoleConditions(Long pScheduleId, Long pParoleDecisionSeq, String modifyUserId);
	Integer deleteprOffenderParoleStipultions(Long pScheduleId, Long pParoleDecisionSeq, String modifyUserId);
	Integer deleteprOffenderParoleDecisions(Long offenderBookId, Long paroleHearingSeq, String modifyUserId);
	Integer deleteprOffenderParolePlans(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderPlanedActivities(Long offenderBookId, String modifyUserId);
	Integer deleteprOffenderPptyContainers(Integer offenderBookId, String modifyUserId);
	Integer deleteprOffenderPptyItems(Integer offenderBookId, String modifyUserId);
	List<OffenderPptyItemTxns> prOffenderPptyItemEvents(Integer offenderBookId);
	Integer deleteprOffenderPptyItemTxns(Integer offenderBookId, Integer eventSeq);
	Integer deleteprOffenderPptyItemEvents(Integer offenderBookId);
	List<OffenderPrgObligations> prOffenderPrgObligations(Long offenderBookId);
	List<OffenderCourseAttendances> prOffenderCourseAttendancs1(Long offenderPrgObligationId);
	Integer deleteprOffenderCourseAttendancs1(Long offenderPrgObligationId);
	List<OffenderIndSchedules> prOffenderIndSchedules1(Integer offenderPrgObligationId);
	Integer deleteprOffenderIndSchedules1(Integer offenderPrgObligationId);
	Integer deleteprOffenderObligationAdjs(Integer offenderPrgObligationId);
	Integer deleteprOffenderPrgObligationHty(Integer offenderPrgObligationId);
	List<OffenderProgramProfiles> prOffenderProgramProfiles1(Integer offenderPrgObligationId);
	List<OffenderCourseApptGrp> prOffenderCourseApptGrps(BigDecimal offPrgrefId);
	Integer deleteprOffenderCourseApptRules(Long offenderCourseApptGrpId,String modifyUserId);
	Integer deleteprOffenderCourseApptGrps(BigDecimal offPrgrefId,String modifyUserId);
	List<OffenderCourseAttendances> prOffenderCourseAttendancs2(Long offPrgrefId);
	Integer deleteprOffenderCourseAttendancs2(Long offPrgrefId);
	List<OffenderProgramProfiles> prOffenderProgramProfiles2(Long offPrgrefId);
	Integer deleteprOffenderProgramProfiles2(Long offPrgrefId,String modifyUserId);
	Integer deleteprOffenderProgramProfiles1(Integer offenderPrgObligationId);
	Integer deleteprOffenderPrgObligations(Long offenderBookId);
	List<OffenderProceedings> prOffenderProceedings(BigDecimal offenderBookId);
	List<CourtEvents> prCourtEvents2(Integer offenderProceedingId);
	Integer deleteprCourtEvents2(Integer offenderProceedingId);
	Integer deleteprOffenderProceedingSents1(BigDecimal offenderProceedingId);
	Integer deleteprOffenderProceedings(BigDecimal offenderBookId);
	Integer deleteprOffenderProfiles(Long offenderBookId);
	List<OffenderProgramProfiles> prOffenderProgramProfiles(Long offenderBookId);
	Integer deleteprOffenderProgramProfiles(Long offenderBookId);
	Integer deleteprOffenderPropertyBundles(BigDecimal offenderBookId);
	List<VOffExtMovements> prOffenderProposedMvmnts(Long offenderBookId);
	Integer deleteprOffenderMovementDetails(Long offenderBookId,Long movememntseq);
	Integer deleteprOffenderProposedMvmnts(Long offenderBookId);
	List<OffenderPtr> prOffenderPtr(Long offenderBookId);
	Integer deleteprExtOwnershipTransfer(Long ptrId);
	Integer deleteprOffenderBookingAgyLocs1(Long ptrId);
	Integer deleteprOffenderPtrDetails(Long ptrId);
	Integer deleteprOffenderPtr(Long offenderBookId);
	Integer deleteprOffenderReferrals(Long offenderBookId);
	Integer deleteprOffenderReleaseDetails(Long offenderBookId);
	Integer deleteprOffenderResidences(Long offenderBookId);
	Integer deleteprOffenderRiskPredictors(Long offenderBookId);
	Integer deleteprOffenderSentCalculations(Long offenderBookId);
	List<OffenderStgAffiliations> prOffenderStgAffiliations(BigDecimal offenderBookId);
	Integer deleteprOffenderStgDetails(BigDecimal offenderBookId, BigDecimal stgSeq);
	Integer deleteprOffenderStgAffiliations(BigDecimal offenderBookId);
	Integer deleteprOffenderStgAssociations(BigDecimal offenderBookId);
	Integer deleteprOffenderSubstanceAbuses(BigDecimal offenderBookId);
	List<AssessmentResults> prOffenderSupervisionLevels(BigDecimal offenderBookId);
	List<OffenderOicSanctions> prOffenderSupervisionPlans(Integer offenderBookId, Long planSeq);
	Integer deleteprOffenderPlanedActivities1(Integer offenderBookId, Long pSupervisionLevelType);
	Integer deleteprOffenderSupervisionPlans(Integer offenderBookId, Long pSupervisionLevelType);
	Integer deleteprOffenderSupervisionRates(Integer offenderBookId, Long pSupervisionType);
	Integer deleteprOffenderSupervisionLevels(BigDecimal offenderBookId);
	Integer deleteprOffenderTeamAssignments(Integer offenderBookId);
	Integer deleteprOffenderTeamAssignHty(Long offenderBookId);
	Integer deleteprOffenderTemporaryAbsences(Long offenderBookId);
	Integer deleteprOffenderTmpRelSchedules(Long offenderBookId);
	List<VOffenderVisits> prOffenderVisits(Long offenderBookId);
	Integer deleteprOffenderVisitVisitors(Long offenderVisitVisitorId);
	Integer deleteprOffenderVisits(Long offenderBookId);
	Integer deleteprOffenderVitalSigns(BigDecimal offenderBookId);
	List<Orders> prOrders(BigDecimal offenderBookId);
	List<OffenderSentences> prOffenderSentences1(BigDecimal orderId);
	Integer deleteprCourtEventSentences1(Long offenderBookId, Long sentenceSeq);
	Integer deleteprOffenderCaseNoteSents(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffndrCommnityConditions1(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderIndSchSents(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderLicenceSentences1(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderLicenceSentences2(Long offenderBookId, Long sentenceSeq) ;
	Integer deleteprOffenderProceedingSents(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderSentenceAdjusts(Long offenderBookId, Long sentenceSeq);
	Integer deleteprOffenderSentenceCharges1(Long offenderBookId, Long sentenceSeq);
	Integer deleteprOffenderSentenceHty(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderSentenceStatuses(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderSentenceTerms(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderSentenceUaEvents(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderUnpaidWorkAdj(Long offenderBookId, Long sentenceSeq,String modifyUserId);
	Integer deleteprOffenderSentences1(BigDecimal orderId,String modifyUserId);
	Integer deleteprOrderPurposes(BigDecimal orderId,String modifyUserId);
	Integer deleteprOrders(BigDecimal offenderBookId);
	List<ReleasePlans> prReleasePlans(Long offenderBookId);
	Integer deleteprRpOtherOccupants(Long releasePlanId);
	Integer deleteprReleasePlans(Long offenderBookId);
	List<Orders> prStaffWorks(Long offenderBookId);
	Integer deleteprStaffWorkAssignments(BigDecimal staffId);
	Integer deleteprStaffWorks(Long offenderBookId);
	Integer deleteprSupervisionTransactions(Long offenderBookId);
	Integer deleteprTaskAssignmentHty(BigDecimal offenderBookId);
	List<Addresses> prAddresses(BigDecimal ownerId, String ownerClass);
	Integer deleteprAddressUsages(Long addressId,String modifyUserId);
	List<CourseActivities> prCourseActivities(Long servicesAddressId);
	Integer deleteprCourseActivityAreas(Long parentCrsActyId,String modifyUserId);
	Integer deleteprCourseActivityParties(Long crsActyId,String modifyUserId);
	Integer deleteprCourseActivityProfiles(Long crsActyId,String modifyUserId);
	Integer deleteprCourseActivityReviews(Long crsActyId);
	List<CourseSchedules> prCourseSchedules(Long crsActyId);
	List<CourseSchedules> prCourseSchedules1(Long catchUpCrsSchId);
	Integer deleteprCourseScheduleStaffs(BigDecimal crsSchId,String modifyUserId);
	List<OffenderCurfews> prVideoReviewSummaries(BigDecimal crsSchId);
	List<OffenderCurfews> prVideoReviewSections(Long pVideoReviewSummaryId);
	Integer deleteprVideoReviewSubsections(String sectionCode, BigDecimal pVideoReviewSummaryId);
	Integer deleteprVideoReviewSections(Long pVideoReviewSummaryId);
	Integer deleteprVideoReviewSummaries(BigDecimal crsSchId);
	Integer deleteprCourseSchedules(Long crsActyId);
	Integer deleteprCourseScheduleRules(Long crsActyId,String modifyUserId);
	List<OffenderCourseAttendances> prOffenderCourseAttendancs3(Long crsActyId);
	Integer deleteprOffenderCourseAttendancs3(Long crsActyId);
	List<OffenderProgramProfiles> prOffenderProgramProfiles3(Long crsActyId);
	Integer deleteprCourseActivities(Long servicesAddressId,String modifyUserId);
	List<OffenderCurfews> prCurfewAddresses1(BigDecimal pAddressId);
	Integer deleteprCurfewAddresses1(BigDecimal pAddressId);
	Integer deleteprOffenderExternalMovemnts1(BigDecimal toAddressId,String modifyUserId);
	Integer deleteprOffenderExternalMovemnts2(BigDecimal fromAddressId,String modifyUserId);
	Integer deleteprOffenderMailLogs1(BigDecimal pMailAddressId,String modifyUserId);
	Integer deleteprOffenderMailRestrictions1(BigDecimal pRestrictionAddressId,String modifyUserId);
	Integer deleteprPhones(BigDecimal ownerId, String ownerClass);
	Integer deleteprAddresses(BigDecimal ownerId, String ownerClass);
	Integer deleteprInternetAddresses(BigDecimal ownerId, String ownerClass);
	List<Images> prImages(BigDecimal imageObjectId, String imageObjectType);
	Integer deleteprImageOriginals(Long imageId);
	Integer deleteprImageProperties(Integer imageId);
	Integer deleteprImages(BigDecimal imageObjectId, String imageObjectType);
	Integer deleteprOffenderCaseAssociations(Long offenderBookId);
	Integer deleteprOffenderCaseAssociations1(BigDecimal pAssociatedOffBookId);
	List<WorkFlows> prWorkFlows(BigDecimal objectId);
	Integer deleteprWorkFlowLogs(Long workFlowId);
	Integer deleteprWorkFlows(BigDecimal objectId);
	Integer deleteprOffenderProfileDetails(Long offenderBookId);
	Integer deleteprOffenderBillingProfiles(Long offenderBookingId);
	List<QmActivitiesIns> prQmProcessesIns(String detail);
	Integer deleteprQmActivitiesIns(BigDecimal pProcessInsId);
	Integer deleteprQmObjectIns(BigDecimal pProcessInsId);
	Integer deleteprQmProcessesIns(String detail);
	List<QmActivitiesIns> prQmProcessesInsHist(String detail);
	Integer deleteprQmActivitiesInsHist(BigDecimal pProcessInsId);
	Integer deleteprQmObjectInsHist(BigDecimal pProcessInsId);
	Integer deleteprOffenderSupervisingCourts(BigDecimal offenderBookId);
	Integer deleteproffenderrestrictions(BigDecimal offenderBookId);
	Integer deleteprOffenderBookings(Long pOffenderBookId);
	Integer deleteprOffenderOffIncentivesEarnPrivs(Long offenderBookId);
	Integer deleteprOffenderAssets(Long offenderBookId, String modifyUserId);
	Integer purgeDeleteOffenderCustodyStatus(Long offenderBookId,String modifyUserId);
	
}
