 
OCIPPHIS_VPAYMENTPLANHISTORIES_FIND_V_PAYMENT_PLAN_HISTORIES {
 	SELECT PAYMENT_PLAN_ID ,PAYMENT_PLAN_SEQ ,INFORMATION_NUMBER ,GROUP_ID ,GROUP_CODE ,START_DATE ,END_DATE ,FREQUENCY ,PAYMENT_CLOSED_DATE ,PAYMENT_DATE ,TRANSACTION_DATE ,PAYMENT_AMOUNT ,OFFENDER_ID ,PAID_AMOUNT   FROM V_PAYMENT_PLAN_HISTORIES
}

OCIPPHIS_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION  FROM   OMS_MODULES WHERE  MODULE_NAME = :V_FORM_NAME
}

OCIPPHIS_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE(),upper(USER) as USER FROM  DUAL
}
