 
OCUOTRAH_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 	SELECT TXN_ID, TXN_ENTRY_SEQ ,CASELOAD_ID, OFFENDER_ID, OFFENDER_BOOK_ID, TXN_POSTING_TYPE, TXN_TYPE, TXN_ENTRY_DESC, TXN_ENTRY_AMOUNT, TXN_ENTRY_DATE, SUB_ACCOUNT_TYPE, TXN_REFERENCE_NUMBER, MODIFY_DATE, RECEIPT_NUMBER, SLIP_PRINTED_FLAG, TRANSFER_CASELOAD_ID, RECEIPT_PRINTED_FLAG, PRE_WITHHOLD_AMOUNT, DEDUCTION_FLAG, CLOSING_CHEQUE_NUMBER, REMITTER_NAME, PAYEE_CODE, PAYEE_NAME_TEXT, PAYEE_CORPORATE_ID, PAYEE_PERSON_ID,
 ADJUST_TXN_ID, ADJUST_TXN_ENTRY_ID, ADJUST_OFFENDER_ID, ADJUST_ACCOUNT_CODE ,TXN_ADJUSTED_FLAG, DEDUCTION_TYPE ,INFO_NUMBER, HOLD_CLEAR_FLAG, HOLD_UNTIL_DATE, HOLD_NUMBER, GROSS_AMOUNT ,GROSS_NET_FLAG ,REMITTER_ID,
APPLY_SPENDING_LIMIT_AMOUNT, RECEIPT_PENDING_PRINT_FLAG ,SEAL_FLAG ,ORG_TXN_TYPE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME ,MODIFY_USER_ID  
 FROM OFFENDER_TRANSACTIONS
}
OCUOTRAH_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT  * FROM SYSTEM_PROFILES  /* where  */
 	
 OCUOTRAH_OFFTXN_FIND_OFFENDER_TRANSACTIONS_TXN_ENTRY_TIME {
 	 SELECT TXN_ENTRY_TIME, TXN_REVERSED_FLAG, REVERSED_TXN_ID        
     FROM GL_TRANSACTIONS
     WHERE TXN_ID = :TXN_ID
     limit 1
}
