OCUINCFE_STAFF_FORCE_SELECT_DATA{

SELECT 
			ISF.SEQUENCE_NUMBER,
			ISF.AGENCY_INCIDENT_ID,
			ISF.PARTY_SEQ,
			ISF.STAFF_ID,
			ISF.FORCE_USED,
			ISF.FORCE_DETAIL,
			ISF.CREATE_DATETIME,
			ISF.CREATE_USER_ID,
			ISF.MODIFY_USER_ID,
			ISF.MODIFY_DATETIME,
			ISF.SEAL_FLAG
			FROM INCIDENT_STAFF_FORCES ISF
}

OCUINCFE_STAFF_EQUIPMENT_SELECT_DATA{
SELECT 
			ISE.AGENCY_INCIDENT_ID,
			ISE.PARTY_SEQ,
			ISE.STAFF_ID,
			ISE.FORCE_USED,
			ISE.FORCE_DETAIL,
			ISE.CREATE_DATETIME,
			ISE.CREATE_USER_ID,
			ISE.MODIFY_USER_ID,
			ISE.MODIFY_DATETIME,
			ISE.SEAL_FLAG
			FROM INCIDENT_STAFF_EQUIPMENTS ISE
}

OCUINCFE_STAFF_FORCE_INSERT_DATA{
insert into INCIDENT_STAFF_FORCES (SEQUENCE_NUMBER, AGENCY_INCIDENT_ID, PARTY_SEQ, STAFF_ID, FORCE_USED, FORCE_DETAIL, CREATE_USER_ID, CREATE_DATETIME ) values ( :sequenceNumber, :agencyIncidentId, :partySeq, :staffId, :forceUsed, :forceDetail, :createUserId, current_timestamp )
}

OCUINCFE_STAFF_EQUPMENT_INSERT_DATA{
insert into INCIDENT_STAFF_EQUIPMENTS ( AGENCY_INCIDENT_ID, PARTY_SEQ, STAFF_ID, EQUIPMENT_USED, EQUIPMENT_DETAIL, CREATE_USER_ID, CREATE_DATETIME ) values ( :agencyIncidentId, :partySeq, :staffId, :forceUsed, :forceDetail, :createUserId, current_timestamp )
}

OCUINCFE_STAFF_FORCE_UPDATE_DATA{
update INCIDENT_STAFF_FORCES FORCE_DETAIL=:forceDetail, MODIFY_DATETIME=current_timestamp, MODIFY_USERID=:modifyUserid where SEQUENCE_NUMBER=:sequenceNumber and AGENCY_INCIDENT_ID=:agencyIncidentId
}

OCUINCFE_STAFF_EQUIPMENT_UPDATE_DATA{
update INCIDENT_STAFF_EQUIPMENTS set EQUIPMENT_DETAIL=:equipmentDetail, MODIFY_DATETIME=current_timestamp, MODIFY_USERID=:modifyUserid where EQUIPEMENT_USED=:equipmentUsed and AGENCY_INCIDENT_ID=:agencyIncidentId
}

OCUINCFE_STAFF_FORCE_DELETE_DATA{
DELETE FROM INCIDENT_STAFF_FORCE
WHERE SEQUENCE_NUMBER:sequenceNumber AND AGENCY_INCIDENT_ID: agencyIncidentId
}

OCUINCFE_STAFF_EQUIPMENT_DELETE_DATA{
DELETE FROM INCIDENT_STAFF_EQUIPMENT
WHERE EQUIPEMENT_USED:equipmentUsed AND AGENCY_INCIDENT_ID: agencyIncidentId
} 



