
	OCUOICAW_FIND_RGOTHERSANCTIONS {
select OOS.SANCTION_SEQ , OOS.OIC_INCIDENT_ID , OO.OIC_OFFENCE_CODE , OMS_MISCELLANEOUS_GETDESCCODE('OIC_OFN_TYPE' , OO.OIC_OFFENCE_TYPE ) OIC_OFFENCE_TYPE , OO.DESCRIPTION , AIC.OIC_CHARGE_ID , OH.HEARING_DATE , OH.HEARING_TIME , AIC.CHARGE_SEQ from OFFENDER_OIC_SANCTIONS OOS , OIC_HEARINGS OH , OIC_HEARING_RESULTS OHR , AGENCY_INCIDENT_CHARGES AIC , OIC_OFFENCES OO where OOS.OFFENDER_BOOK_ID = :OFFENDERBOOKID and OOS.OIC_HEARING_ID = OH.OIC_HEARING_ID and OOS.OIC_HEARING_ID = OHR.OIC_HEARING_ID and OOS.RESULT_SEQ = OHR.RESULT_SEQ and OH.OIC_HEARING_ID = OHR.OIC_HEARING_ID and AIC.AGENCY_INCIDENT_ID = OHR.AGENCY_INCIDENT_ID and AIC.CHARGE_SEQ = OHR.CHARGE_SEQ and AIC.CHARGED_OIC_OFFENCE_ID = OO.OIC_OFFENCE_ID and OOS.SANCTION_SEQ != :SANCTIONSEQ and OOS.SANCTION_SEQ not in (with recursive cte as ( select SANCTION_SEQ from OFFENDER_OIC_SANCTIONS OS where OS.OFFENDER_BOOK_ID = :OFFENDERBOOKID and OS.SANCTION_SEQ = :SANCTIONSEQ union all select OS.SANCTION_SEQ from OFFENDER_OIC_SANCTIONS OS join cte c on (c.SANCTION_SEQ = OS.CONSECUTIVE_SANCTION_SEQ and OS.OFFENDER_BOOK_ID= :OFFENDERBOOKID)

) select * from cte

) order by 2 , 1 , 9
}
	OCUOICAW_FIND_RGSANCT {
 SELECT REF_CODE.DESCRIPTION  DESCRIPTION  ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'OIC_SANCT' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR 'ENTER-QUERY' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ
}
	OCUOICAW_FIND_RGSANCTST {
 SELECT REF_CODE.DESCRIPTION  DESCRIPTION  ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'OIC_SANCT_ST' AND ((ACTIVE_FLAG = 'Y' AND   EXPIRED_DATE IS NULL ) OR 'ENTER-QUERY' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ
}
OCUOICAW_OICSANC_FIND_OFFENDER_OIC_SANCTIONS {
 SELECT OFFENDER_BOOK_ID ,SANCTION_SEQ ,OIC_SANCTION_CODE ,COMPENSATION_AMOUNT ,SANCTION_MONTHS ,SANCTION_DAYS ,COMMENT_TEXT ,EFFECTIVE_DATE ,APPEALING_DATE ,CONSECUTIVE_OFFENDER_BOOK_ID ,CONSECUTIVE_SANCTION_SEQ ,OIC_HEARING_ID ,STATUS ,OFFENDER_ADJUST_ID ,RESULT_SEQ ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,STATUS_DATE ,OIC_INCIDENT_ID ,LIDS_SANCTION_NUMBER ,SEAL_FLAG   FROM OFFENDER_OIC_SANCTIONS where OIC_HEARING_ID = :oicHearingId
and RESULT_SEQ = :resultSeq  ORDER BY EFFECTIVE_DATE DESC
}

OCUOICAW_OICSANC_INSERT_OFFENDER_OIC_SANCTIONS {
insert into OFFENDER_OIC_SANCTIONS(OFFENDER_BOOK_ID , SANCTION_SEQ , OIC_SANCTION_CODE , COMPENSATION_AMOUNT , SANCTION_MONTHS , SANCTION_DAYS , COMMENT_TEXT , EFFECTIVE_DATE , APPEALING_DATE , CONSECUTIVE_OFFENDER_BOOK_ID , CONSECUTIVE_SANCTION_SEQ , OIC_HEARING_ID , STATUS , OFFENDER_ADJUST_ID , RESULT_SEQ , CREATE_DATETIME , CREATE_USER_ID , STATUS_DATE , OIC_INCIDENT_ID , LIDS_SANCTION_NUMBER , SEAL_FLAG , modify_datetime) values(:offenderBookId , :sanctionSeq , :oicSanctionCode , :compensationAmount , :sanctionMonths , :sanctionDays , :commentText , :effectiveDate , :appealingDate , :consecutiveOffenderBookId , :consecutiveSanctionSeq , :oicHearingId , :status , :offenderAdjustId , :resultSeq , current_timestamp , :createUserID , :statusDate , :oicIncidentId , :lidsSanctionNumber , :sealFlag , null)
}

OCUOICAW_OICSANC_UPDATE_OFFENDER_OIC_SANCTIONS {
 update OFFENDER_OIC_SANCTIONS set OIC_SANCTION_CODE = :oicSanctionCode, SANCTION_MONTHS = :sanctionMonths, SANCTION_DAYS = :sanctionDays, COMPENSATION_AMOUNT = :compensationAmount, EFFECTIVE_DATE = :effectiveDate, CONSECUTIVE_SANCTION_SEQ = :consecutiveSanctionSeq, OIC_INCIDENT_ID = :oicIncidentId, STATUS = :status, STATUS_DATE = :statusDate, COMMENT_TEXT = :commentText, modify_datetime =current_timestamp , modify_user_id =:modifyUserId where OFFENDER_BOOK_ID = :offenderBookId and SANCTION_SEQ = :sanctionSeq
}


	OCUOICAW_OCUOICAW_WHENVALIDATEITEM_GET_OIC_OFFENCE_CODE_CUR {
 SELECT MAX_PENALTY_MONTHS,MAX_PENALTY_DAYS FROM OIC_OFFENCES WHERE OIC_OFFENCE_CODE = :oicOffenceCode AND ACTIVE_FLAG ='Y'
}

	OCUOICAW_GET_PROFILE_VALUE_2_VS_PROFVAL_CUR {
 SELECT PROFILE_VALUE_2 FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = :profileType AND PROFILE_CODE = :profileCode
}
     OCUOICAW_FIND_SANCTION_SEQ  {
 SELECT COALESCE(MAX(SANCTION_SEQ),0) + 1 FROM  OFFENDER_OIC_SANCTIONS  where OFFENDER_BOOK_ID=:offenderBookId
 }
 
 OCUOICAW_GET_OIC_SANCTION_LIMITS{
         SELECT MAX_MONTH, MAX_DAYS
        FROM OIC_SANCTION_LIMITS
       WHERE OIC_SANCTION_CODE =:SANCTION_CODE
         AND OIC_HEARING_TYPE =:HEARING_TYPE;
 }