	OCUOICHE_FIND_RGOFFENCECODE {
 SELECT OMS_MISCELLANEOUS_GETDESCCODE('OIC_OFN_TYPE' ,OIC_OFFENCE_TYPE ) DESCRIPTION,  OIC_OFFENCE_CODE CODE, OIC_OFFENCE_TYPE , OIC_OFFENCE_ID , OIC_OFFENCE_CATEGORY FROM OIC_OFFENCES WHERE (ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' )/* AND :INCIDENTDATE  BETWEEN START_DATE AND NVL (END_DATE , TO_DATE('01/01/2199' , 'DD/MM/YYYY' ) ) ORDER BY LIST_SEQ*/
}
	OCUOICHE_FIND_RGAGYINCPSTAFFID {
 SELECT  STAFF1.LAST_NAME , STAFF1.FIRST_NAME , STAFF1.STAFF_ID, USER_ID  FROM STAFF_MEMBERS STAFF1  WHERE STAFF1.STAFF_ID IN  (SELECT STAFF_ID   FROM STAFF_ACCESSIBLE_CASELOADS   WHERE CASELOAD_ID = :CASELOADID ) AND  ( (SUSPENDED_FLAG ='N' AND TERMINATION_DATE IS NULL ) OR  :MODE='ENTER-QUERY'  )  ORDER BY STAFF1.LAST_NAME , STAFF1.FIRST_NAME , STAFF1.STAFF_ID
}
	OCUOICHE_FIND_RGHEARINGTYPE {
 SELECT REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'OIC_HEAR' AND ('ENTER-QUERY' = 'ENTER-QUERY' OR ACTIVE_FLAG = 'Y' ) ORDER BY LIST_SEQ , DESCRIPTION
}
	OCUOICHE_FIND_RGINTERNALLOCATIONS {
 SELECT   C.DESCRIPTION  DESCRIPTION,          C.INTERNAL_LOCATION_ID , C.INTERNAL_LOCATION_CODE      FROM INT_LOC_USAGE_LOCATIONS A ,          INTERNAL_LOCATION_USAGES B ,          AGENCY_INTERNAL_LOCATIONS C    WHERE A.INTERNAL_LOCATION_USAGE_ID = B.INTERNAL_LOCATION_USAGE_ID      AND B.INTERNAL_LOCATION_USAGE = 'OIC'      AND B.AGY_LOC_ID IN (SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :CASELOADID )      AND A.INTERNAL_LOCATION_ID = C.INTERNAL_LOCATION_ID      AND (   (C.ACTIVE_FLAG = 'Y' AND C.DEACTIVATE_DATE IS NULL )           OR (:MODE = 'ENTER-QUERY' ) )  AND NOT EXISTS (SELECT 1  FROM INT_LOC_USAGE_LOCATIONS WHERE PARENT_USAGE_LOCATION_ID = A.USAGE_LOCATION_ID ) ORDER BY C.LIST_SEQ ,C.DESCRIPTION
}
	OCUOICHE_FIND_RGINCIDENTCHARGES {
 SELECT OIC_OFFENCE_CODE ,        CHARGE_SEQ , OMS_MISCELLANEOUS_GETDESCCODE('OIC_OFN_TYPE' ,OIC_OFFENCE_TYPE ) OIC_OFFENCE_TYPE ,    DESCRIPTION ,        OIC_CHARGE_ID ,        OIC_OFFENCE_ID FROM AGENCY_INCIDENT_CHARGES ,OIC_OFFENCES WHERE AGENCY_INCIDENT_ID = :agencyIncidentId AND PARTY_SEQ = :partySeq AND OIC_OFFENCE_ID = CHARGED_OIC_OFFENCE_ID AND :INCIDENTDATE  BETWEEN START_DATE AND coalesce (END_DATE , TO_DATE('01/01/2199' , 'DD/MM/YYYY' ) ) 
}
	OCUOICHE_FIND_RGFINDING {
 SELECT REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'OIC_FINDING' AND (:MODE = 'ENTER-QUERY' OR ACTIVE_FLAG = 'Y' ) ORDER BY LIST_SEQ , DESCRIPTION
}
	OCUOICHE_FIND_RGPLEA {
 SELECT REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'OIC_PLEA' AND (:MODE = 'ENTER-QUERY' OR ACTIVE_FLAG = 'Y' ) ORDER BY LIST_SEQ , DESCRIPTION
}
OCUOICHE_OICHEAR_FIND_OIC_HEARINGS {
 SELECT OIC_HEARING_ID ,OIC_HEARING_TYPE ,OIC_INCIDENT_ID ,SCHEDULE_DATE ,SCHEDULE_TIME ,HEARING_DATE ,HEARING_TIME ,HEARING_STAFF_ID ,VISIT_JUSTICE_TEXT ,COMMENT_TEXT ,TAPE_NUMBER ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,INTERNAL_LOCATION_ID ,REPRESENTATIVE_TEXT ,EVENT_ID ,EVENT_STATUS ,SEAL_FLAG   FROM OIC_HEARINGS  where  OIC_INCIDENT_ID = :OIC_INCIDENT_ID ORDER BY  HEARING_DATE DESC, HEARING_TIME DESC 
}

OCUOICHE_OICHEAR_INSERT_OIC_HEARINGS {
insert into OIC_HEARINGS(OIC_HEARING_ID , OIC_HEARING_TYPE , OIC_INCIDENT_ID , SCHEDULE_DATE , SCHEDULE_TIME , HEARING_DATE , HEARING_TIME , HEARING_STAFF_ID , VISIT_JUSTICE_TEXT , COMMENT_TEXT , TAPE_NUMBER , CREATE_DATETIME , CREATE_USER_ID , INTERNAL_LOCATION_ID , REPRESENTATIVE_TEXT , EVENT_ID , EVENT_STATUS , SEAL_FLAG , modify_datetime) values( NEXTVAL('oic_hearing_id') , :oicHearingType , :oicIncidentId , :scheduleDate , :scheduleTime , :hearingDate , :hearingTime , :hearingStaffId , :visitJusticeText , :commentText , :tapeNumber , current_timestamp , :createUserId , :internalLocationId , :representativeText , NEXTVAL('EVENT_ID') , :eventStatus , :sealFlag , null )
}

OCUOICHE_OICHEAR_UPDATE_OIC_HEARINGS {
update OIC_HEARINGS set OIC_HEARING_TYPE =:oicHearingType , OIC_INCIDENT_ID =:oicIncidentId , SCHEDULE_DATE =:scheduleDate , SCHEDULE_TIME =:scheduleTime , HEARING_DATE =:hearingDate , HEARING_TIME =:hearingTime , HEARING_STAFF_ID =:hearingStaffId , VISIT_JUSTICE_TEXT =:visitJusticeText , COMMENT_TEXT =:commentText , TAPE_NUMBER =:tapeNumber , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID =:modifyUserId , INTERNAL_LOCATION_ID =:internalLocationId , REPRESENTATIVE_TEXT =:representativeText , EVENT_ID =:eventId , EVENT_STATUS =:eventStatus , SEAL_FLAG =:sealFlag where OIC_HEARING_ID =:oicHearingId
}

	OCUOICHE_OICHEAR_DELETE_OIC_HEARINGS { 
DELETE FROM OIC_HEARINGS AIP    
         WHERE AIP.OIC_HEARING_ID = :OicHearingId
}

OCUOICHE_OICHEARRES_FIND_OIC_HEARING_RESULTS {
 SELECT OIC_HEARING_ID ,RESULT_SEQ ,AGENCY_INCIDENT_ID ,CHARGE_SEQ ,PLEA_FINDING_CODE ,FINDING_CODE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,OIC_OFFENCE_ID ,SEAL_FLAG ,OIC_RESULT_OFFENCE_ID   FROM OIC_HEARING_RESULTS WHERE OIC_HEARING_ID = :OIC_HEARING_ID
}

OCUOICHE_OICHEARRES_INSERT_OIC_HEARING_RESULTS {
insert into OIC_HEARING_RESULTS(OIC_HEARING_ID , RESULT_SEQ , AGENCY_INCIDENT_ID , CHARGE_SEQ , PLEA_FINDING_CODE , FINDING_CODE , CREATE_DATETIME , CREATE_USER_ID , OIC_OFFENCE_ID , SEAL_FLAG , OIC_RESULT_OFFENCE_ID, modify_datetime ) values(:oicHearingId , :resultSeq , :agencyIncidentId , :chargeSeq , :pleaFindingCode , :findingCode , current_timestamp , :createUserId , :oicOffenceId , :sealFlag , :oicResultOffenceId , null )
}

OCUOICHE_OICHEARRES_UPDATE_OIC_HEARING_RESULTS {
UPDATE OIC_HEARING_RESULTS  set 
RESULT_SEQ =:resultSeq ,
AGENCY_INCIDENT_ID =:agencyIncidentId ,
CHARGE_SEQ =:chargeSeq ,
PLEA_FINDING_CODE =:pleaFindingCode ,
FINDING_CODE =:findingCode ,
MODIFY_DATETIME = current_timestamp,
MODIFY_USER_ID =:modifyUserId ,
OIC_OFFENCE_ID =:oicOffenceId ,
SEAL_FLAG =:sealFlag ,
OIC_RESULT_OFFENCE_ID =:oicResultOffenceId
WHERE OIC_HEARING_ID =:oicHearingId  and RESULT_SEQ =:resultSeq
}


	OCUOICHE_OICHEARRES_DELETE_OIC_HEARING_RESULTS { 
DELETE  FROM OIC_HEARING_RESULTS AIP    
         WHERE AIP.OIC_HEARING_ID = :oicHearingId and AIP.CHARGE_SEQ =:chargeSeq and AIP.RESULT_SEQ  = :resultSeq
}


	OCUOICHE_OIC_HEAR_PREQUERY {
 SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = CASELOADID ) AND INTERNAL_LOCATION_TYPE IN (''AREA'',''LEVEL'') AND UPPER(DESCRIPTION) LIKE UPPER('''|| NBTINTERNALLOCATION || '''))
}

	OCUOICHE_OIC_HEAR_ONCHECKDELETEMASTER_OIC_HEAR_RES_CUR {
 SELECT 1 FROM OIC_HEARING_RESULTS O WHERE O.OIC_HEARING_ID =:OICHEARINGID AND ROWNUM = 1
}

	OCUOICHE_OCUOICHE_KEYDELREC_OIC_SANC_CUR {
 SELECT 1 FROM OFFENDER_OIC_SANCTIONS O WHERE O.OIC_HEARING_ID =:OICHEARINGID AND   O.RESULT_SEQ = :RESULTSEQ AND ROWNUM = 1
}

	OIC_HEARING_ID_PREINSERTC_SQL{
 SELECT coalesce(max(OIC_HEARING_ID),0) + 1  FROM  OIC_HEARINGS
 }

 OCUOICCH_AGY_INCI_CHG_POSTQUERY {
 SELECT * FROM OIC_OFFENCES OO WHERE OO.OIC_OFFENCE_ID = :OIC_OFFENCE_ID
}

OIC_HEARING_RESULTS_PREINSERTC_SQL{
SELECT coalesce (max(RESULT_SEQ),0) + 1  FROM  OIC_HEARING_RESULTS where OIC_HEARING_ID = :oicHearingId
}

	OCUOICHE_FIND_LASTNAME {
 SELECT  STAFF1.LAST_NAME , STAFF1.FIRST_NAME , STAFF1.STAFF_ID, USER_ID  FROM STAFF_MEMBERS STAFF1  WHERE STAFF1.STAFF_ID = :STAFF_ID
}
}