
  OCUOICCH_FIND_RGOFFENCECODE {
SELECT DESCRIPTION ,  OMS_MISCELLANEOUS_GETDESCCODE('OIC_OFN_TYPE' ,OIC_OFFENCE_TYPE ) OIC_OFFENCE_TYPE ,  OIC_OFFENCE_CODE , 
	OIC_OFFENCE_TYPE , OIC_OFFENCE_ID , OIC_OFFENCE_CATEGORY FROM OIC_OFFENCES WHERE (ACTIVE_FLAG = 'Y' OR '' = 'ENTER-QUERY' )
	AND :INCIDENTDATE  BETWEEN START_DATE AND coalesce (END_DATE , TO_DATE('01/01/2199' , 'DD/MM/YYYY' ) ) ORDER BY OIC_OFFENCE_ID DESC
}
  OCUOICCH_AGYINCICHG_FIND_AGENCY_INCIDENT_CHARGES {
 SELECT AGENCY_INCIDENT_ID ,CHARGE_SEQ ,PARTY_SEQ ,OIC_CHARGE_ID ,FINDING_CODE ,GUILTY_EVIDENCE_TEXT ,REPORT_TEXT ,EVIDENCE_DISPOSE_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,LIDS_CHARGE_NUMBER ,CHARGED_OIC_OFFENCE_ID ,RESULT_OIC_OFFENCE_ID ,SEAL_FLAG   FROM AGENCY_INCIDENT_CHARGES  
 where AGENCY_INCIDENT_ID = :AGENCY_INCIDENT_ID AND PARTY_SEQ = :PARTY_SEQ ORDER BY CHARGE_SEQ 
}

  OCUOICCH_AGYINCICHG_INSERT_AGENCY_INCIDENT_CHARGES {
insert into AGENCY_INCIDENT_CHARGES(AGENCY_INCIDENT_ID , CHARGE_SEQ , PARTY_SEQ , OIC_CHARGE_ID , FINDING_CODE , GUILTY_EVIDENCE_TEXT , REPORT_TEXT , EVIDENCE_DISPOSE_TEXT , CREATE_DATETIME , CREATE_USER_ID , LIDS_CHARGE_NUMBER , CHARGED_OIC_OFFENCE_ID , RESULT_OIC_OFFENCE_ID , SEAL_FLAG, modify_datetime) values(:agencyIncidentId , :chargeSeq , :partySeq , :oicChargeId , :findingCode , :guiltyEvidenceText , :reportText , :evidenceDisposeText , current_timestamp , :createUserId , :lidsChargeNumber , :chargedOicOffenceId , :resultOicOffenceId , :sealFlag, null)
}

  OCUOICCH_AGYINCICHG_UPDATE_AGENCY_INCIDENT_CHARGES {
update AGENCY_INCIDENT_CHARGES set PARTY_SEQ =:partySeq , OIC_CHARGE_ID =:oicChargeId , FINDING_CODE =:findingCode , GUILTY_EVIDENCE_TEXT =:guiltyEvidenceText , REPORT_TEXT =:reportText , EVIDENCE_DISPOSE_TEXT =:evidenceDisposeText , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID =:modifyUserId , LIDS_CHARGE_NUMBER =:lidsChargeNumber , CHARGED_OIC_OFFENCE_ID =:chargedOicOffenceId , RESULT_OIC_OFFENCE_ID =:resultOicOffenceId , SEAL_FLAG =:sealFlag where AGENCY_INCIDENT_ID =:agencyIncidentId and CHARGE_SEQ =:chargeSeq
}

  OCUOICCH_AGY_INCIDENT_CHG_POSTQUERY_NEW {
	SELECT OIC_OFFENCE_CODE,DESCRIPTION,OMS_MISCELLANEOUS_GETDESCCODE('OIC_OFN_TYPE',OIC_OFFENCE_TYPE) OIC_OFFENCE_TYPE,OIC_OFFENCE_CATEGORY FROM OIC_OFFENCES WHERE OIC_OFFENCE_ID = :OIC_OFFENCE_ID
  }

  OCDADDRE_AGY_INCI_CHG_PREINSERT {
	SELECT coalesce (MAX(CHARGE_SEQ),0)+1 FROM AGENCY_INCIDENT_CHARGES where AGENCY_INCIDENT_ID = :AGENCY_INCIDENT_ID
  }
  OCUOICCH_AGYINCICHG_DELETE_AGENCY_INCIDENT_CHARGES { 
DELETE FROM AGENCY_INCIDENT_CHARGES where AGENCY_INCIDENT_ID  = :agencyIncidentId and CHARGE_SEQ  = :chargeSeq
}
  OCUOICCH_DELETE_AGENCY_INCIDENT_CHARGES_PREQUERY { 
select * from OIC_HEARING_RESULTS where AGENCY_INCIDENT_ID = :AGENCY_INCIDENT_ID and CHARGE_SEQ  = :CHARGE_SEQ
}
}