	
	OCUOICIN_FIND_RGSTATEMENTTYPE {
 SELECT REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.CODE  CODE   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'OIC_STMT_TYP'     AND (:MODE = 'ENTER-QUERY'         OR (ACTIVE_FLAG = 'Y'              AND EXPIRED_DATE IS NULL )         ) ORDER BY LIST_SEQ
}
	OCUOICIN_FIND_RGAGYINCPSTAFFID {
 SELECT STAFF1.LAST_NAME || ', ' ||STAFF1.FIRST_NAME DESCRIPTION , STAFF1.STAFF_ID STAFF_ID  FROM STAFF_MEMBERS STAFF1  WHERE STAFF1.STAFF_ID IN  (SELECT STAFF_ID   FROM STAFF_ACCESSIBLE_CASELOADS   WHERE CASELOAD_ID = :CASELOADID ) AND  ( (SUSPENDED_FLAG ='N' AND TERMINATION_DATE IS NULL ) OR   :MODE='ENTER-QUERY'  ) ORDER BY STAFF1.LAST_NAME , STAFF1.FIRST_NAME , STAFF1.STAFF_ID
}
OCUOICIN_OICINVEST_FIND_AGY_INC_INVESTIGATIONS {
 SELECT AGY_INC_INVESTIGATION_ID ,AGENCY_INCIDENT_ID ,INVESTIGATOR_ID ,ASSIGNED_DATE ,COMMENT_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,PARTY_SEQ ,SEAL_FLAG   
 FROM AGY_INC_INVESTIGATIONS WHERE AGENCY_INCIDENT_ID = :AGENCY_INCIDENT_ID AND PARTY_SEQ = :PARTY_SEQ ORDER BY ASSIGNED_DATE DESC
}

OCUOICIN_OICINVEST_INSERT_AGY_INC_INVESTIGATIONS {
insert into AGY_INC_INVESTIGATIONS(AGY_INC_INVESTIGATION_ID , AGENCY_INCIDENT_ID , INVESTIGATOR_ID , ASSIGNED_DATE , COMMENT_TEXT , CREATE_DATETIME , CREATE_USER_ID , PARTY_SEQ , SEAL_FLAG , modify_datetime ) values(NEXTVAL('agy_inc_investigation_id') , :agencyIncidentId , :investigatorId , :assignedDate , :commentText , current_timestamp , :createUserId , :partySeq , :sealFlag , null )
}

OCUOICIN_OICINVEST_UPDATE_AGY_INC_INVESTIGATIONS {
update
	AGY_INC_INVESTIGATIONS
set
	AGENCY_INCIDENT_ID =:agencyIncidentId,
	INVESTIGATOR_ID =:InvestigatorId,
	ASSIGNED_DATE =:AssignedDate,
	COMMENT_TEXT =:CommentText,
	MODIFY_DATETIME = current_timestamp,
	MODIFY_USER_ID =:ModifyUserId,
	PARTY_SEQ =:PartySeq,
	SEAL_FLAG =:SealFlag
where
	AGY_INC_INVESTIGATION_ID =:AgyIncInvestigationId
}


	OCUOICIN_OICINVEST_DELETE_AGY_INC_INVESTIGATIONS { 
 DELETE  FROM AGY_INC_INVESTIGATIONS AIP    
         WHERE AIP.AGY_INC_INVESTIGATION_ID = :agyIncInvestigationId and  AIP.PARTY_SEQ = :PartySeq 
}        


OCUOICIN_OICINVESTSTA_FIND_AGY_INC_INV_STATEMENTS {
 SELECT AGY_II_STATEMENT_ID ,AGY_INC_INVESTIGATION_ID ,STATEMENT_TYPE ,NAME_OF_STATEMENT_TAKER ,DATE_OF_STATEMENT_TAKEN ,STATEMENT_DETAIL ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM AGY_INC_INV_STATEMENTS where AGY_INC_INVESTIGATION_ID = :AGY_INC_INVESTIGATION_ID
}

OCUOICIN_OICINVESTSTA_INSERT_AGY_INC_INV_STATEMENTS {
insert into AGY_INC_INV_STATEMENTS(AGY_II_STATEMENT_ID , AGY_INC_INVESTIGATION_ID , STATEMENT_TYPE , NAME_OF_STATEMENT_TAKER , DATE_OF_STATEMENT_TAKEN , STATEMENT_DETAIL , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG , modify_datetime ) values(NEXTVAL('agy_ii_statement_id') , :agyIncInvestigationId , :statementType , :nameOfStatementTaker , :dateOfStatementTaken , :statementDetail , current_timestamp , :createUserId , :sealFlag , null )
}

OCUOICIN_OICINVESTSTA_UPDATE_AGY_INC_INV_STATEMENTS {
update
	AGY_INC_INV_STATEMENTS
set
	AGY_INC_INVESTIGATION_ID =:AgyIncInvestigationId,
	STATEMENT_TYPE =:StatementType,
	NAME_OF_STATEMENT_TAKER =:NameOfStatementTaker,
	DATE_OF_STATEMENT_TAKEN =:DateOfStatementTaken,
	STATEMENT_DETAIL =:StatementDetail,
	MODIFY_DATETIME = current_timestamp,
	MODIFY_USER_ID =:ModifyUserId,
	SEAL_FLAG =:SealFlag
where
	AGY_II_STATEMENT_ID =:AgyIiStatementId
}


	OCUOICIN_OICINVESTSTA_DELETE_AGY_INC_INV_STATEMENTS { 

 DELETE  FROM AGY_INC_INV_STATEMENTS AI    
         WHERE AI.AGY_II_STATEMENT_ID = :AgyIiStatementId 


}

	OCUOICIN_OIC_INVEST_ONCHECKDELETEMASTER_OIC_INVEST_STA_CUR {
 SELECT 1 FROM AGY_INC_INV_STATEMENTS A WHERE A.AGY_INC_INVESTIGATION_ID = :AgyIncInvestigationId
}

OCUOICIN_AGY_INV_INVESTIGATIONSPREINSERTC_SQL{
select coalesce (max(AGY_INC_INVESTIGATION_ID),0) + 1 from  AGY_INC_INVESTIGATIONS
}


 OCUOICIN_AGY_INV_INVESTMENTSPREINSERTC_SQL {
select coalesce (max(AGY_II_STATEMENT_ID),0) + 1  from  AGY_INC_INV_STATEMENTS
}