OIDOICAP_FIND_RGHEARINGOFFENCES {
 	SELECT
    AIP.OIC_INCIDENT_ID            OIC_INCIDENT_ID,
    OIC_IC.OIC_HEARING_ID          code,
    OIC_IC.RESULT_SEQ              RESULT_SEQ,
    OIC_IC.CHARGE_SEQ              CHARGE_SEQ,
    OIC_IC.OIC_RESULT_OFFENCE_ID   OIC_RESULT_OFFENCE_ID,
    OIC_OFN.OIC_OFFENCE_CODE       OIC_OFFENCE_CODE,
    OIC_OFN.DESCRIPTION            description,
    OIC_OFN.OIC_OFFENCE_ID         OIC_OFFENCE_ID,
    OIC_IC.AGENCY_INCIDENT_ID      AGENCY_INCIDENT_ID,
    OH.HEARING_DATE                HEARING_DATE
FROM
    OIC_HEARING_RESULTS       OIC_IC,
    OIC_HEARINGS              OH,
    OIC_OFFENCES              OIC_OFN,
    AGENCY_INCIDENT_PARTIES   AIP,
    AGENCY_INCIDENT_CHARGES   AIC
WHERE
    OIC_IC.OIC_RESULT_OFFENCE_ID = OIC_OFN.OIC_OFFENCE_ID
    AND AIP.AGENCY_INCIDENT_ID = OIC_IC.AGENCY_INCIDENT_ID
    AND AIP.OFFENDER_BOOK_ID = :offenderBookId
    AND AIP.AGENCY_INCIDENT_ID = AIC.AGENCY_INCIDENT_ID
    AND AIC.CHARGE_SEQ = OIC_IC.CHARGE_SEQ
    AND OIC_IC.OIC_HEARING_ID = OH.OIC_HEARING_ID
 }

OIDOICAP_FIND_RGOICSEQLOG {
 	SELECT
    OFF_OICAP1.SEQ                OIC_SEQ_LOG ,
    OFF_OICAP1.RESULT_SEQ         OIC_RESULT_SEQ_LOG,
    OFF_OICAP1.OIC_HEARING_ID     OIC_HEARING_ID_LOG,
    OFF_OICAP1.OIC_APPREAL_ID     OIC_APPEAL_ID_LOG,
    OFF_OICAP1.OIC_PENALTY_TYPE   OIC_PENALTY_TYPE,
    TO_CHAR(OFF_OICA1.HEARING_DATE, 'MM/DD/YYYY') HEARING_DATE,
    TO_CHAR(OFF_OICA1.HEARING_TIME, 'HH24:MI') HEARING_TIME
FROM
    OFFENDER_OIC_APPEAL_PENALTIES   OFF_OICAP1,
    OFFENDER_OIC_APPEALS            OFF_OICA1
WHERE
    OFF_OICA1.OIC_APPREAL_ID = OFF_OICAP1.OIC_APPREAL_ID
    AND OFF_OICA1.OFFENDER_BOOKING_ID = :offenderBookId
    AND ( :seq IS NULL
          OR ( OFF_OICAP1.SEQ <> :seq
               OR OFF_OICAP1.OIC_APPREAL_ID <> :oicApprealId
               OR OFF_OICAP1.OIC_HEARING_ID <> :oicHearingId
               OR OFF_OICAP1.RESULT_SEQ <> :resultSeq ) )
ORDER BY
    3,
    1,
    6
}

OIDOICAP_FIND_RGHEARDBY {
 SELECT STAFF.LAST_NAME || ', ' || STAFF.FIRST_NAME DESCRIPTION     , STAFF.STAFF_ID CODE  FROM STAFF_MEMBERS STAFF  WHERE TERMINATION_DATE IS NULL AND SUSPENDED_FLAG = 'N' ORDER BY STAFF.LAST_NAME, STAFF.FIRST_NAME
}

OIDOICAP_OFFOICA_FIND_OFFENDER_OIC_APPEALS {
 	SELECT
    OIC_APPREAL_ID,
    OFFENDER_BOOKING_ID,
    APPREAL_DATE,
    APRREAL_REASON_CODE,
    HEARING_DATE,
    HEARING_RESULT_CODE,
    HEARING_TIME,
    HEARD_BY,
    SUMMARY,
    REVIEW_DATE,
    OTHER_REPRESENTATIVE,
    CREATE_DATETIME,
    CREATE_USER_ID,
    MODIFY_DATETIME,
    MODIFY_USER_ID,
    SEAL_FLAG
FROM
    OFFENDER_OIC_APPEALS OFF_OICA
WHERE
    off_oica.offender_booking_id = :offenderBookId
ORDER BY
    APPREAL_DATE DESC
}
OIDOICAP_OFFOICA_INSERT_OFFENDER_OIC_APPEALS {
insert into OFFENDER_OIC_APPEALS(OIC_APPREAL_ID , OFFENDER_BOOKING_ID , APPREAL_DATE , APRREAL_REASON_CODE , HEARING_DATE , HEARING_RESULT_CODE , HEARING_TIME , HEARD_BY , SUMMARY , REVIEW_DATE , OTHER_REPRESENTATIVE , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG , modify_datetime ) values(:oicApprealId , :offenderBookingId , :apprealDate , :aprrealReasonCode , :hearingDate , :hearingResultCode , :hearingTime , :heardBy , :summary , :reviewDate , :otherRepresentative , current_timestamp , :createUserId , :sealFlag , null )
}

OIDOICAP_OFFOICA_UPDATE_OFFENDER_OIC_APPEALS {
UPDATE OFFENDER_OIC_APPEALS SET  APPREAL_DATE =:apprealDate, APRREAL_REASON_CODE =:aprrealReasonCode, HEARING_DATE =:hearingDate, HEARING_RESULT_CODE =:hearingResultCode, HEARING_TIME =:hearingTime, HEARD_BY =:heardBy, SUMMARY =:summary, OTHER_REPRESENTATIVE =:otherRepresentative, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID =:modifyUserId where OIC_APPREAL_ID = :oicApprealId and OFFENDER_BOOKING_ID = :offenderBookingId
}

OIDOICAP_OFFOICA_DELETE_OFFENDER_OIC_APPEALS { 
DELETE FROM OFFENDER_OIC_APPEALS  where OIC_APPREAL_ID = :oicApprealId and OFFENDER_BOOKING_ID = :offenderBookingId
}

OIDOICAP_OFFOICAI_FIND_OFFENDER_OIC_APPEAL_INCIDENTS {
 	SELECT
    OIC_APPREAL_ID,
    OIC_HEARING_ID,
    RESULT_SEQ,
    CREATE_DATETIME,
    CREATE_USER_ID,
    MODIFY_DATETIME,
    MODIFY_USER_ID,
    SEAL_FLAG
FROM
    OFFENDER_OIC_APPEAL_INCIDENTS OFF_OICAI
WHERE
    OFF_OICAI.OIC_APPREAL_ID = :OicApprealId
}
OIDOICAP_OFFOICAI_INSERT_OFFENDER_OIC_APPEAL_INCIDENTS {
insert into OFFENDER_OIC_APPEAL_INCIDENTS(OIC_APPREAL_ID , OIC_HEARING_ID , RESULT_SEQ , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG , modify_datetime ) values(:oicApprealId , :oicHearingId , :resultSeq , CURRENT_TIMESTAMP , :createUserId , :sealFlag , null )
}

OIDOICAP_OFFOICAI_UPDATE_OFFENDER_OIC_APPEAL_INCIDENTS {
UPDATE OFFENDER_OIC_APPEAL_INCIDENTS set OIC_APPREAL_ID  =:oicApprealId ,OIC_HEARING_ID  =:oicHearingId ,RESULT_SEQ  =:resultSeq ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  =:modifyUserId ,SEAL_FLAG  =:sealFlag 
}

OIDOICAP_OFFOICAI_DELETE_OFFENDER_OIC_APPEAL_INCIDENTS { 
DELETE FROM OFFENDER_OIC_APPEAL_INCIDENTS where OIC_APPREAL_ID  = :oicApprealId AND OIC_HEARING_ID  = :oicHearingId AND RESULT_SEQ  = :resultSeq 
}

OIDOICAP_OFFOICAP_FIND_OFFENDER_OIC_APPEAL_PENALTIES {
 	SELECT
    OIC_APPREAL_ID,
    OIC_HEARING_ID,
    RESULT_SEQ,
    SEQ,
    OIC_PENALTY_TYPE,
    EFFECT_DATE,
    MONTH,
    DAYS,
    COMPENSATION,
    OIC_COMMENT,
    OIC_APPEAL_ID_LOG,
    OIC_SEQ_LOG,
    OIC_HEARING_ID_LOG,
    RESULT_SEQ_LOG,
    STATUS,
    OFFENDER_ADJUST_ID,
    CREATE_DATETIME,
    CREATE_USER_ID,
    MODIFY_DATETIME,
    MODIFY_USER_ID,
    SEAL_FLAG
FROM
    OFFENDER_OIC_APPEAL_PENALTIES OFF_OICAP
WHERE
    OFF_OICAP.OIC_APPREAL_ID = :oicApprealId
    AND OFF_OICAP.OIC_HEARING_ID = :oicHearingId
    AND OFF_OICAP.RESULT_SEQ = :resultSeq
}
OIDOICAP_OFFOICAP_INSERT_OFFENDER_OIC_APPEAL_PENALTIES {
insert into OFFENDER_OIC_APPEAL_PENALTIES(OIC_APPREAL_ID , OIC_HEARING_ID , RESULT_SEQ , SEQ , OIC_PENALTY_TYPE , EFFECT_DATE , month , DAYS , COMPENSATION , OIC_COMMENT , OIC_APPEAL_ID_LOG , OIC_SEQ_LOG , OIC_HEARING_ID_LOG , RESULT_SEQ_LOG , STATUS , OFFENDER_ADJUST_ID , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG , modify_datetime ) values(:oicApprealId , :oicHearingId , :resultSeq , :seq , :oicPenaltyType , :effectDate , :month , :days , :compensation , :oicComment , :oicAppealIdLog , :oicSeqLog , :oicHearingIdLog , :resultSeqLog , :status , :offenderAdjustId , CURRENT_TIMESTAMP , :createUserId , :sealFlag , null )
}

OIDOICAP_OFFOICAP_UPDATE_OFFENDER_OIC_APPEAL_PENALTIES {
update OFFENDER_OIC_APPEAL_PENALTIES set OIC_PENALTY_TYPE =:oicPenaltyType , EFFECT_DATE =:effectDate , month =:month , DAYS =:days , COMPENSATION =:compensation , OIC_COMMENT =:oicComment , OIC_APPEAL_ID_LOG =:oicAppealIdLog , OIC_SEQ_LOG =:oicSeqLog , OIC_HEARING_ID_LOG =:oicHearingIdLog , RESULT_SEQ_LOG =:resultSeqLog , STATUS =:status , OFFENDER_ADJUST_ID =:offenderAdjustId , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID =:modifyUserId , SEAL_FLAG =:sealFlag where OIC_APPREAL_ID =:oicApprealId and OIC_HEARING_ID =:oicHearingId and RESULT_SEQ =:resultSeq and SEQ =:seq
}

OIDOICAP_OFFOICAP_DELETE_OFFENDER_OIC_APPEAL_PENALTIES { 
DELETE FROM OFFENDER_OIC_APPEAL_PENALTIES WHERE OIC_APPREAL_ID  = :oicApprealId AND OIC_HEARING_ID  = :oicHearingId AND RESULT_SEQ  = :resultSeq AND SEQ  = :seq
}


OIDOICAP_OFF_BKG_ONCHECKDELETEMASTER {
SELECT 1 FROM OFFENDER_OIC_APPEAL_INCIDENTS O WHERE O.OIC_APPREAL_ID = :oicApprealId
}

OIDOICAP_OFFOICAI_FIND_OFFENDER_OIC_APPEAL_INCIDENTS_POST_QUERY{
SELECT
    AIP.OIC_INCIDENT_ID            OIC_INCIDENT_ID,
    OIC_IC.RESULT_SEQ              RESULT_SEQ,
    OIC_IC.CHARGE_SEQ              CHARGE_SEQ,
    OIC_IC.OIC_RESULT_OFFENCE_ID   OIC_RESULT_OFFENCE_ID,
    OIC_OFN.OIC_OFFENCE_CODE       OIC_OFFENCE_CODE,
    OIC_OFN.DESCRIPTION            description,
    OIC_OFN.OIC_OFFENCE_ID         OIC_OFFENCE_ID,
    OIC_IC.AGENCY_INCIDENT_ID      AGENCY_INCIDENT_ID,
    OH.HEARING_DATE                HEARING_DATE
FROM
    OIC_HEARING_RESULTS       OIC_IC,
    OIC_HEARINGS              OH,
    OIC_OFFENCES              OIC_OFN,
    AGENCY_INCIDENT_PARTIES   AIP,
    AGENCY_INCIDENT_CHARGES   AIC
WHERE
    OIC_IC.OIC_RESULT_OFFENCE_ID = OIC_OFN.OIC_OFFENCE_ID
    AND AIP.AGENCY_INCIDENT_ID = OIC_IC.AGENCY_INCIDENT_ID
    AND AIP.OFFENDER_BOOK_ID = :offenderBookId
    AND AIP.AGENCY_INCIDENT_ID = AIC.AGENCY_INCIDENT_ID
    AND AIC.CHARGE_SEQ = OIC_IC.CHARGE_SEQ
    AND OIC_IC.OIC_HEARING_ID = OH.OIC_HEARING_ID
    AND OIC_IC.OIC_HEARING_ID = :oicHearingId
      and OIC_IC.result_seq =:resultSeq
}

OIDOICAP_OFFOICA_PRE_INSERT{
SELECT NEXTVAL('OIC_APPREAL_ID') FROM DUAL
}

OIDOICAP_OFFOICAP_PRE_INSERT{
SELECT COALESCE(MAX(OOA.SEQ),0) + 1 FROM OFFENDER_OIC_APPEAL_PENALTIES OOA WHERE EXISTS (SELECT 1 FROM OFFENDER_OIC_APPEALS WHERE OFFENDER_BOOKING_ID = :offenderBookingId AND OIC_APPREAL_ID = OOA.OIC_APPREAL_ID)
}

OIDOICAP_OFFENDER_OIC_APPEAL_PENALTIES_ONCHECKDELETEMASTER{
 SELECT 1 FROM OFFENDER_OIC_APPEAL_PENALTIES O WHERE O.OIC_APPEAL_ID_LOG = :oicApprealId and O.OIC_HEARING_ID_LOG = :oicHearingId and O.RESULT_SEQ_LOG = :resultSeq and O.OIC_SEQ_LOG = :seq
}

OIDOICAP_OICAI_ONCHECKDELETEMASTER{
SELECT 1 FROM OFFENDER_OIC_APPEAL_PENALTIES O WHERE O.OIC_APPREAL_ID = :oicApprealId and O.OIC_HEARING_ID = :oicHearingId and O.RESULT_SEQ = :resultSeq
}

OIDOICAP_ORIGINAL_PENALTY{
SELECT OIC_CHARGE_ID   FROM AGENCY_INCIDENT_CHARGES  WHERE AGENCY_INCIDENT_ID = :agencyIncidentId AND CHARGE_SEQ = :chargeSeq
}

OIDOICAP_OIDOICAP_WHENVALIDATERECORD{
SELECT MAX_PENALTY_MONTHS,MAX_PENALTY_DAYS FROM OIC_OFFENCES WHERE OIC_OFFENCE_ID = :oicOffenceId AND ACTIVE_FLAG ='Y'
}
