
OIDOICUS_FIND_RGINCTYPE {
	SELECT REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'INC_TYPE'  AND ((ACTIVE_FLAG = 'Y' AND coalesce(EXPIRED_DATE ::date, '2021-01-10') = '2021-01-10' ) OR :MODE = 'ENTER-QUERY' ) ORDER BY LIST_SEQ
}

OIDOICUS_VOICINCI_FIND_V_OIC_INCIDENTS {
 	SELECT OFFENDER_BOOK_ID ,REPORTED_STAFF_ID ,BOOKING_NO ,AGENCY_INCIDENT_ID ,PARTY_SEQ ,INCIDENT_DATE ,INT_LOC_DESCRIPTION ,INCIDENT_TIME ,INCIDENT_TYPE ,INCIDENT_TYPE_DESC ,INCIDENT_DETAILS ,REPORT_DATE ,AGY_LOC_ID ,OIC_INCIDENT_ID ,OIC_CHARGE_FLAG   FROM V_OIC_INCIDENTS
}

OIDOICUS_OFF_BKG_ONCHECKDELETEMASTER_V_OIC_INCI_CUR {
	SELECT 1 FROM V_OIC_INCIDENTS V WHERE V.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}
OIDOICUS_FIND_STAFFID_DESCRIPTION {
	SELECT STAFF1.LAST_NAME || ', ' ||STAFF1.FIRST_NAME DESCRIPTION  FROM STAFF_MEMBERS STAFF1 where STAFF1.STAFF_ID = :STAFFID
}
OIDOICUS_FIND_LOCATION_LIST {
	SELECT DISTINCT INT_LOC_DESCRIPTION FROM V_OIC_INCIDENTS
}

OIDSTFRPPOP_SELECT_STAFF_REPORT_ALL_DATA{
select aip.staff_id STAFF_ID,
isr.incident_report_id INCIDENT_REPORT_ID,
(select ai.report_date  from AGENCY_INCIDENTS ai where ai.agency_incident_id =aip.agency_incident_id) as REPORT_DATE,
ISR.REPORT_TIME,
ISR.REPORT_TYPE,
ISR.LOCK_FLAG,
ISR.CREATE_DATETIME,
ISR.CREATE_USER_ID,
ISR.MODIFY_USER_ID,
ISR.MODIFY_DATETIME,
ISR.AGENCY_INCIDENT_ID,
ISR.PARTY_SEQ,
ISR.SEAL_FLAG,
ISR.REPORT_DETAILS INCIDENT_DETAILS,
(select ai.incident_details  from AGENCY_INCIDENTS ai where ai.agency_incident_id =aip.agency_incident_id) as REPORT_DETAILS
 from agency_incident_parties aip,incident_staff_reports isr where aip.agency_incident_id =:agencyIncidentId 
and aip.agency_incident_id  = isr.agency_incident_id and aip.party_seq = isr.party_seq
}