	
	OIIINLOG_FIND_RGOCCURTYPE {
 SELECT DESCRIPTION , CODE   FROM REFERENCE_CODES   WHERE DOMAIN = 'INC_TYPE'    AND ACTIVE_FLAG = 'Y'     AND EXPIRED_DATE IS NULL   ORDER BY LIST_SEQ
}
	OIIINLOG_FIND_RGAGYLOC {
 SELECT  AGY_LOC.DESCRIPTION DESCRIPTION ,  AGY_LOC.AGY_LOC_ID FROM AGENCY_LOCATIONS AGY_LOC  WHERE AGENCY_LOCATION_TYPE = 'INST'    AND AGY_LOC_ID IN (SELECT AGY_LOC_ID                         FROM CASELOAD_AGENCY_LOCATIONS                        WHERE CASELOAD_ID = :CASELOADID )    AND AGY_LOC_ID NOT IN ('OUT' , 'TRN' )
}
	OIIINLOG_FIND_RGLEVELLOC {
 SELECT C.DESCRIPTION ,        C.INTERNAL_LOCATION_CODE ,        C.INTERNAL_LOCATION_ID   FROM INT_LOC_USAGE_LOCATIONS A ,        INTERNAL_LOCATION_USAGES B ,        AGENCY_INTERNAL_LOCATIONS C  WHERE A.INTERNAL_LOCATION_USAGE_ID = B.INTERNAL_LOCATION_USAGE_ID    AND B.INTERNAL_LOCATION_USAGE = 'OCCUR'    AND B.AGY_LOC_ID = :NBTAGYLOCID    AND A.INTERNAL_LOCATION_ID = C.INTERNAL_LOCATION_ID    AND ((C.ACTIVE_FLAG = 'Y'    AND C.DEACTIVATE_DATE IS NULL )        OR (:MODE = 'ENTER-QUERY' ) )   AND NOT EXISTS (SELECT 1     FROM INT_LOC_USAGE_LOCATIONS      WHERE PARENT_USAGE_LOCATION_ID = A.USAGE_LOCATION_ID ) ORDER BY C.LIST_SEQ
}
	OIIINLOG_FIND_RGSTAFF {
 SELECT   SM.LAST_NAME || ', ' || SM.FIRST_NAME STAFF_NAME , SM.STAFF_ID     FROM STAFF_MEMBERS SM    WHERE SM.STAFF_ID IN ( SELECT SAC.STAFF_ID                            FROM STAFF_ACCESSIBLE_CASELOADS SAC                           WHERE SAC.CASELOAD_ID = :CASELOADID  )      AND SM.SUSPENDED_FLAG = 'N'      AND SM.TERMINATION_DATE IS NULL and SM.status ='ACTIVE'
ORDER BY SM.LAST_NAME , SM.FIRST_NAME
}
OIIINLOG_VAGYINC_FIND_V_AGENCY_INCIDENTS {
SELECT AI.REPORTED_STAFF_ID ,AI.CREATE_USER_ID,VI.AGENCY_INCIDENT_ID ,VI.REPORTED_STAFF_ID ,VI.STAFF_FIRST_NAME ,VI.STAFF_LAST_NAME ,VI.INCIDENT_DATE ,VI.INCIDENT_TIME ,VI.INTERNAL_LOCATION_ID ,VI.INCIDENT_TYPE ,VI.INCIDENT_TYPE_DESC ,VI.INCIDENT_STATUS ,VI.REPORT_DATE ,VI.REPORT_TIME ,VI.AGY_LOC_ID ,VI.INT_LOC_DESCRIPTION ,VI.REPAIR_FLAG  
 FROM AGENCY_INCIDENTS AI ,V_AGENCY_INCIDENTS VI where  AI.AGENCY_INCIDENT_ID=VI.AGENCY_INCIDENT_ID
}

FIND_INCIDENT_TYPE_LIST{
	SELECT DISTINCT INCIDENT_TYPE_DESC FROM V_AGENCY_INCIDENTS
}

FIND_INCIDENT_LOC_LIST{
	SELECT DISTINCT INT_LOC_DESCRIPTION FROM V_AGENCY_INCIDENTS
}

OIIINLOG_FIND_RGLEVELINTERNALLOCATIONIDS  {
	SELECT C.INTERNAL_LOCATION_ID ,
	       C.INTERNAL_LOCATION_CODE ,
	       C.DESCRIPTION  
   FROM INT_LOC_USAGE_LOCATIONS A , INTERNAL_LOCATION_USAGES B , AGENCY_INTERNAL_LOCATIONS C 
   WHERE A.INTERNAL_LOCATION_USAGE_ID = B.INTERNAL_LOCATION_USAGE_ID    AND B.INTERNAL_LOCATION_USAGE = 'OCCUR'  
   AND B.AGY_LOC_ID =:agyLocId       AND A.INTERNAL_LOCATION_ID = C.INTERNAL_LOCATION_ID    AND ((C.ACTIVE_FLAG = 'Y'    AND C.DEACTIVATE_DATE IS NULL )  ) 
}




OIIINLOG_AGENCYINCIDENTS_FIND_AGENCY_INCIDENTS {
     SELECT AI.REPORTED_STAFF_ID,
		    AI.AGENCY_INCIDENT_ID,
			AI.INCIDENT_DATE,
			AI.INTERNAL_LOCATION_ID,
			AI.INCIDENT_TIME,
			AI.INCIDENT_TYPE,
			AI.INCIDENT_STATUS,
			AI.CREATE_DATETIME,
			AI.CREATE_USER_ID,
			AI.MODIFY_USER_ID,
			AI.MODIFY_DATETIME,
			AI.LOCK_FLAG,
			AI.INCIDENT_DETAILS,
			AI.REPORT_DATE,
			AI.REPORT_TIME,
			AI.AGY_LOC_ID,
			AI.LEVEL_CODE,
			AI.LOG_NO,
			AI.INCIDENT_TEXT,
			AI.SEAL_FLAG
		FROM AGENCY_INCIDENTS AI 
 }
 OIIINLOG_AGENCYINCIDENTS_CALL_MODULE_OIDINCDE {
      SELECT ACCESS_PRIVILEGE
       FROM MODULE_PRIVILEGES
      WHERE MODULE_NAME = 'OIDINCDE'
 }
 OIIINLOG_AGENCYINCIDENTS_CALL_MODULE_OIUINCRP {
      SELECT ACCESS_PRIVILEGE
       FROM MODULE_PRIVILEGES
      WHERE MODULE_NAME = 'OIUINCRP'
 }
 OIINLOG_COMMUNITY_INCIDENTS_LOG_INQUIRY_GET_DATA{
 select AI.REPORTED_STAFF_ID , AI.CREATE_USER_ID, VI.AGENCY_INCIDENT_ID , VI.REPORTED_STAFF_ID , VI.STAFF_FIRST_NAME , VI.STAFF_LAST_NAME , VI.INCIDENT_DATE , VI.INCIDENT_TIME , VI.INTERNAL_LOCATION_ID , VI.INCIDENT_TYPE , VI.INCIDENT_TYPE_DESC , VI.INCIDENT_STATUS , VI.REPORT_DATE , VI.REPORT_TIME , VI.AGY_LOC_ID , VI.REPAIR_FLAG, VI.description from AGENCY_INCIDENTS AI , ( select ai.agency_incident_id, ai.reported_staff_id, sm.first_name as staff_first_name, sm.last_name as staff_last_name, ai.incident_date, ai.incident_time, ai.internal_location_id, ai.incident_type, ( select reference_codes.description from reference_codes where reference_codes.domain::text = 'INC_TYPE'::text and reference_codes.code::text = ai.incident_type::text) as incident_type_desc, ai.incident_status, ai.report_date, ai.report_time, ai.agy_loc_id, ( select case when count(*) = 0 then 'N'::text else 'Y'::text end as "case" from agency_incident_repairs air where ai.agency_incident_id = air.agency_incident_id) as repair_flag, al.description from staff_members sm, agency_incidents ai, agency_locations al where sm.staff_id = ai.reported_staff_id and al.agy_loc_id in ( select agy_loc_id from caseload_agency_locations al where caseload_id = :caseLoadId) and ai.agy_loc_id = al.agy_loc_id ) VI where AI.AGENCY_INCIDENT_ID = VI.AGENCY_INCIDENT_ID
 }
}
