OIUINCRP_AGYINC_FIND_AGENCY_INCIDENT_REPAIRS {
 SELECT AGENCY_INCIDENT_ID ,REPAIR_SEQ ,REPAIR_TYPE ,COMMENT_TEXT ,MODIFY_USER_ID ,MODIFY_DATETIME ,REPAIR_COST ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG   FROM AGENCY_INCIDENT_REPAIRS
}


}