
OIUSTGAS_FIND_RGSTG2 {
 	SELECT ST1.DESCRIPTION , ST1.STG_ID STG_ID ,ST1.STG_CODE ,ST1.DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS ST1 WHERE ST1.STG_LEVEL = 'GANG' AND (ST1.ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) UNION SELECT ST2.DESCRIPTION||'-'||ST1.DESCRIPTION , ST1.STG_ID STG_ID ,ST1.STG_CODE ,ST1.DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS ST1 , SECURITY_THREAT_GROUPS ST2  WHERE ST1.STG_LEVEL = 'SET' AND (ST1.ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) AND ST1.PARENT_STG_ID = ST2.STG_ID
}

OIUSTGAS_FIND_RGSTG1 {
 	SELECT ST1.DESCRIPTION , ST1.STG_ID STG_ID ,ST1.STG_CODE , ST1.DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS ST1  WHERE ST1.STG_LEVEL = 'SET' AND (ST1.ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) ORDER BY  LIST_SEQ , DESCRIPTION
}

OIUSTGAS_FIND_RGSTG3 { 
 	SELECT DESCRIPTION , STG_ID , STG_CODE ,DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS WHERE STG_LEVEL = 'NATION' AND (ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) UNION SELECT STG2.DESCRIPTION||'-'||STG1.DESCRIPTION DESCRIPTION , STG1.STG_ID STG_ID , STG1.STG_CODE , STG1.DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS STG1 , SECURITY_THREAT_GROUPS STG2 WHERE STG1.STG_LEVEL = 'GANG' AND (STG1.ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) AND STG1.PARENT_STG_ID = STG2.STG_ID UNION SELECT STG3.DESCRIPTION||'-'||STG2.DESCRIPTION||'-'||STG1.DESCRIPTION DESCRIPTION , STG1.STG_ID STG_ID , STG1.STG_CODE , STG1.DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS STG1 , SECURITY_THREAT_GROUPS STG2 , SECURITY_THREAT_GROUPS STG3  WHERE STG1.STG_LEVEL = 'SET' AND (STG1.ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) AND STG1.PARENT_STG_ID = STG2.STG_ID AND STG2.PARENT_STG_ID = STG3.STG_ID
}

OIUSTGAS_FIND_STGGRP {
 	SELECT DESCRIPTION , STG_ID , STG_CODE ,DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS WHERE STG_LEVEL = 'NATION' AND (ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) UNION SELECT STG2.DESCRIPTION||'-'||STG1.DESCRIPTION DESCRIPTION , STG1.STG_ID STG_ID , STG1.STG_CODE , STG1.DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS STG1 , SECURITY_THREAT_GROUPS STG2 WHERE STG1.STG_LEVEL = 'GANG' AND (STG1.ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) AND STG1.PARENT_STG_ID = STG2.STG_ID UNION SELECT STG3.DESCRIPTION||'-'||STG2.DESCRIPTION||'-'||STG1.DESCRIPTION DESCRIPTION , STG1.STG_ID STG_ID , STG1.STG_CODE , STG1.DESCRIPTION DESCRIPTION1 FROM SECURITY_THREAT_GROUPS STG1 , SECURITY_THREAT_GROUPS STG2 , SECURITY_THREAT_GROUPS STG3  WHERE STG1.STG_LEVEL = 'SET' AND (STG1.ACTIVE_FLAG = 'Y' OR :MODE = 'ENTER-QUERY' ) AND STG1.PARENT_STG_ID = STG2.STG_ID AND STG2.PARENT_STG_ID = STG3.STG_ID
}

OIUSTGAS_AGENCYINCIDENTASSOTOSTG_FIND_AGENCY_INCIDENT_ASSO_TOSTG {
 	SELECT AGENCY_INCIDENT_ID ,SEQ_NO ,STG_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM AGENCY_INCIDENT_ASSO_TOSTG 
}
OIUSTGAS_AGENCYINCIDENTASSOTOSTG_INSERT_AGENCY_INCIDENT_ASSO_TOSTG {
	 insert into AGENCY_INCIDENT_ASSO_TOSTG(AGENCY_INCIDENT_ID , SEQ_NO , STG_ID , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG , modify_datetime ) values(:agencyIncidentId , :seqNo , :stgId , current_timestamp , :createUserId , :sealFlag , null )
	 }

OIUSTGAS_AGENCYINCIDENTASSOTOSTG_UPDATE_AGENCY_INCIDENT_ASSO_TOSTG {
	update AGENCY_INCIDENT_ASSO_TOSTG set AGENCY_INCIDENT_ID = :agencyIncidentId , SEQ_NO = :seqNo , STG_ID = :stgId , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where AGENCY_INCIDENT_ID = :agencyIncidentId and SEQ_NO = :seqNo
}

OIUSTGAS_AGENCYINCIDENTASSOTOSTG_DELETE_AGENCY_INCIDENT_ASSO_TOSTG { 
	DELETE FROM AGENCY_INCIDENT_ASSO_TOSTG where AGENCY_INCIDENT_ID  = :agencyIncidentId AND SEQ_NO  = :seqNo
}


OIUSTGAS_AGENCY_INCIDENT_ASSO_TOSTG_PREINSERTPRE_INSERT {
	SELECT coalesce(MAX(SEQ_NO),0)+1 FROM AGENCY_INCIDENT_ASSO_TOSTG WHERE AGENCY_INCIDENT_ID = :AGENCYINCIDENTID
}

OIUSTGAS_AGENCY_INCIDENT_ASSO_TOSTG_PREINSERT {
	SELECT 'Y' FROM AGENCY_INCIDENT_ASSO_TOSTG WHERE AGENCY_INCIDENT_ID = :AGENCYINCIDENTID AND STG_ID = :STGID
}

OIUSTGAS_CREATE_FORM_GLOBALS {   
    SELECT DESCRIPTION FROM OMS_MODULES WHERE MODULE_NAME = :V_FORM_NAME
}

OIUSTGAS_POPULATE_RG {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'STG_LOV_LVL'
}
