
OCUCORPT_FIND_RGCORPTYPE {
 	SELECT DESCRIPTION  ,CODE FROM REFERENCE_CODES WHERE DOMAIN = 'CORP_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OCUCORPT_CORPORATETYPES_FIND_CORPORATE_TYPES {
 	SELECT CORPORATE_ID, CORPORATE_TYPE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG 
 	FROM CORPORATE_TYPES WHERE CORPORATE_ID = :CORPORATEID AND (coalesce(:corporateType ::text,'') = '' OR CORPORATE_TYPE = :corporateType)
}
OCUCORPT_CORPORATETYPES_INSERT_CORPORATE_TYPES {
	INSERT INTO CORPORATE_TYPES(CORPORATE_ID, CORPORATE_TYPE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) VALUES(:corporateId, :corporateType,CURRENT_TIMESTAMP, :createUserId, NULL, NULL, :sealFlag)
}

OCUCORPT_CORPORATETYPES_UPDATE_CORPORATE_TYPES {
	UPDATE CORPORATE_TYPES set CORPORATE_TYPE = :corporateType, modify_datetime = CURRENT_TIMESTAMP,MODIFY_USER_ID=:modifyUserId WHERE CORPORATE_ID = :corporateId AND CORPORATE_TYPE = :nbtCorporateType
}

OCUCORPT_CORPORATETYPES_DELETE_CORPORATE_TYPES { 
	DELETE FROM CORPORATE_TYPES WHERE CORPORATE_ID=:corporateId AND CORPORATE_TYPE=:nbtCorporateType
}


OCUCORPT_PREV_CASELOAD_CORP_EXISTS {
	SELECT COUNT(*) FROM CORPORATES C, CORPORATE_TYPES CT WHERE C.CORPORATE_ID = CT.CORPORATE_ID AND CT.CORPORATE_TYPE ='TRUST' AND CASELOAD_ID = :CASELOADID
}
