
OUMAGENC_FIND_RGCASELOAD {
 	SELECT  DESCRIPTION            ,CASELOAD_ID   CODE   FROM    CASELOADS   WHERE   ACTIVE_FLAG = 'Y' AND     DEACTIVATION_DATE IS NULL
}

OUMAGENC_FIND_RGTYPE {
 	 SELECT DESCRIPTION  ,CODE FROM REFERENCE_CODES WHERE DOMAIN = 'PHONE_USAGE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ  ,CODE
}

OUMAGENC_FIND_RGICLASS {
 	SELECT DESCRIPTION  ,CODE FROM REFERENCE_CODES  WHERE DOMAIN = 'IADDR_CLASS' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL  ORDER BY LIST_SEQ  ,CODE
}

OUMAGENC_CORP_FIND_CORPORATES {
 	SELECT *  FROM CORPORATES 
}
OUMAGENC_CORP_INSERT_CORPORATES {
--	INSERT INTO CORPORATES(CORPORATE_ID, CORPORATE_NAME, CASELOAD_ID, FEI_NUMBER, TAX_NO, COMMENT_TEXT, ACTIVE_FLAG, EXPIRY_DATE, CREATED_DATE, SUSPENDED_FLAG) VALUES(:corporateId, :corporateName, :caseloadId, :feiNumber, :taxNo, :commentText, :activeFlag, :expiryDate, TRUNC(SYSDATE), 'N')
	insert into CORPORATES(CORPORATE_ID, CORPORATE_NAME, CASELOAD_ID, FEI_NUMBER, TAX_NO, COMMENT_TEXT, ACTIVE_FLAG, 
	EXPIRY_DATE, CREATED_DATE, SUSPENDED_FLAG, CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME  ) 
	values(:corporateId, :corporateName, :caseloadId, :feiNumber, :taxNo, :commentText, :activeFlag, :expiryDate, 
	current_date, 'N', CURRENT_TIMESTAMP , :createUserId ,null )
}

OUMAGENC_CORP_UPDATE_CORPORATES {
--	UPDATE CORPORATES set CORPORATE_NAME = :corporateName, CASELOAD_ID = :caseloadId, FEI_NUMBER = :feiNumber, TAX_NO = :taxNo, COMMENT_TEXT = :commentText, ACTIVE_FLAG = :activeFlag, EXPIRY_DATE = :expiryDate  where CORPORATE_ID = :corporateId
	update CORPORATES set CORPORATE_NAME = :corporateName, CASELOAD_ID = :caseloadId, FEI_NUMBER = :feiNumber, TAX_NO = :taxNo, 
	COMMENT_TEXT = :commentText, ACTIVE_FLAG = :activeFlag, EXPIRY_DATE = :expiryDate, MODIFY_USER_ID = :modifyUserId , 
	MODIFY_DATETIME = CURRENT_TIMESTAMP  where CORPORATE_ID = :corporateId
}

OUMAGENC_CORP_DELETE_CORPORATES { 
	DELETE FROM CORPORATES where CORPORATE_ID = :corporateId 
}

OUMAGENC_ADDR_FIND_V_CORPORATE_ADDRESSES {
 	SELECT  * FROM V_CORPORATE_ADDRESSES WHERE CORPORATE_ID = :corporateId   order by primary_flag desc,mail_flag desc,active_flag,start_date desc
}
OUMAGENC_ADDPH_FIND_PHONES {
 	SELECT  * FROM PHONES where OWNER_CLASS = 'ADDR' AND OWNER_ID = :ownerId order by PHONE_TYPE 
}
OUMAGENC_CRPH_FIND_PHONES {
 	SELECT  * FROM PHONES where OWNER_CLASS = 'CORP' AND OWNER_ID = :ownerId order by PHONE_TYPE 
}
OUMAGENC_ADDPH_INSERT_PHONES {
--	INSERT INTO PHONES(PHONE_ID, OWNER_CLASS, OWNER_ID, PHONE_TYPE, PHONE_NO, EXT_NO) VALUES(PHONE_ID.NEXTVAL, :ownerClass, :ownerId, :phoneType, :phoneNo, :extNo)
	insert into PHONES(PHONE_ID, OWNER_CLASS, OWNER_ID, PHONE_TYPE, PHONE_NO, EXT_NO, CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME ,FORMAT ) 
	values(nextval('PHONE_ID'), :ownerClass, :ownerId, :phoneType, :phoneNo, :extNo, CURRENT_TIMESTAMP , :createUserId ,null,:format  )
}

OUMAGENC_ADDPH_UPDATE_PHONES {
--	UPDATE PHONES set PHONE_TYPE = :phoneType , PHONE_NO = :phoneNo, EXT_NO = :extNo WHERE PHONE_ID = :phoneId
	update PHONES set PHONE_TYPE = :phoneType , PHONE_NO = :phoneNo, EXT_NO = :extNo, MODIFY_USER_ID = :modifyUserId,
	MODIFY_DATETIME = CURRENT_TIMESTAMP,FORMAT=:format where PHONE_ID = :phoneId
}

OUMAGENC_ADDPH_DELETE_PHONES { 
	DELETE FROM PHONES WHERE PHONE_ID = :phoneId
}

OUMAGENC_IADD_FIND_INTERNET_ADDRESSES {
 	SELECT  * FROM INTERNET_ADDRESSES where OWNER_CLASS = 'CORP' AND OWNER_ID = :ownerId
}
OUMAGENC_IADD_INSERT_INTERNET_ADDRESSES {
--	INSERT INTO INTERNET_ADDRESSES(INTERNET_ADDRESS_ID, OWNER_CLASS, OWNER_ID, INTERNET_ADDRESS_CLASS, INTERNET_ADDRESS) VALUES(INTERNET_ADDRESS_ID.NEXTVAL, :ownerClass, :ownerId, :internetAddressClass, :internetAddress)
	 insert into INTERNET_ADDRESSES(INTERNET_ADDRESS_ID, OWNER_CLASS, OWNER_ID, INTERNET_ADDRESS_CLASS, INTERNET_ADDRESS, 
 CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME  ) values(nextval('INTERNET_ADDRESS_ID'), :ownerClass, :ownerId, :internetAddressClass,
 :internetAddress, 
 CURRENT_TIMESTAMP , :createUserId , null  )
}

OUMAGENC_IADD_UPDATE_INTERNET_ADDRESSES {
--	UPDATE INTERNET_ADDRESSES set INTERNET_ADDRESS_CLASS = :internetAddressClass, INTERNET_ADDRESS = :internetAddress WHERE INTERNET_ADDRESS_ID = :internetAddressId
	 update INTERNET_ADDRESSES set INTERNET_ADDRESS_CLASS = :internetAddressClass, INTERNET_ADDRESS = :internetAddress,
	 MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where INTERNET_ADDRESS_ID = :internetAddressId
}

OUMAGENC_IADD_DELETE_INTERNET_ADDRESSES { 
	 DELETE FROM INTERNET_ADDRESSES WHERE INTERNET_ADDRESS_ID = :internetAddressId
}

OUMAGENC_ADDRESSES_FIND_ADDRESSES {
 	SELECT  * FROM ADDRESSES  /* where  */
}
OUMAGENC_ADDRESSES_UPDATE_ADDRESSES {
--	UPDATE ADDRESSES set CONTACT_PERSON_NAME = :contactPersonName, BUSINESS_HOUR = :businessHour  WHERE ADDRESS_ID = :addressId 
	update ADDRESSES set CONTACT_PERSON_NAME = :contactPersonName, BUSINESS_HOUR = :businessHour, 
	MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where ADDRESS_ID = :addressId
}

OUMAGENC_ADDRESSES_DELETE_ADDRESSES { 
	DELETE FROM ADDRESSES/* where */
}


OUMAGENC_CORP_ONCHECKDELETEMASTER_ADDRESS {
	SELECT 1 FROM V_CORPORATE_ADDRESSES V WHERE V.CORPORATE_ID = :corporateId
}

OUMAGENC_CORP_ONCHECKDELETEMASTER_PHONE {
	SELECT 1 FROM PHONES P WHERE P.OWNER_ID = :corporateId
}

OUMAGENC_CORP_ONCHECKDELETEMASTER_INTERNET {
	SELECT 1 FROM INTERNET_ADDRESSES I WHERE I.OWNER_ID = :corporateId
}

OUMAGENC_CORP_POSTQUERY_ {
	SELECT DESCRIPTION FROM CASELOADS WHERE CASELOAD_ID = :caseloadId
}

OUMAGENC_ADDR_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM PHONES P WHERE P.OWNER_ID = :ownerId
}

OUMAGENC_ADDR_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM ADDRESSES A WHERE A.ADDRESS_ID = :ADDRESSID AND A.OWNER_ID = :corporateId
}

OUMAGENC_OUMAGENC_KEYEXIT_ {
	SELECT CORPORATE_TYPE FROM CORPORATE_TYPES CT WHERE CORPORATE_ID =:corporateId AND CORPORATE_TYPE = 'BOS'
}
OUMAGENC_GET_CORPORATE_CHILDS {
SELECT 
(SELECT COUNT(1) FROM V_CORPORATE_ADDRESSES V WHERE V.CORPORATE_ID = :corporateId) +
(SELECT COUNT(1) FROM PHONES P WHERE P.OWNER_ID = :corporateId and P.owner_class='CORP') +
(SELECT COUNT(1) FROM INTERNET_ADDRESSES I WHERE I.OWNER_ID = :corporateId and I.owner_class='CORP') CHILDS FROM DUAL
}
OUMAGENC_GET_CORPORATE_ID {
--SELECT CORPORATE_ID.NEXTVAL FROM DUAL
select NEXTVAL('CORPORATE_ID')

}

OUMAGENC_ADDRESS_OLD_RECORD{
 select * from addresses where address_id =:addressId
}

OUMAGENC_PHONES_OLD_RECORD{
select * from phones p where phone_id =:phoneId 
}
OUMAGENC_ADDRESSES_OLD_RECORD{
select * from addresses a  where address_id =:addressId 
}
