INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2)
    VALUES('DISPLAY','NOTIFY-TIME','Notification Popup Display Duration (in ms)','5000','');

UPDATE SYSTEM_PROFILES 
   SET PROFILE_VALUE = '5000', PROFILE_VALUE_2 = NULL 
 WHERE PROFILE_TYPE = 'DISPLAY' 
   AND PROFILE_CODE = 'NOTIFY-TIME';

COMMIT;

