GET_INTERESTED_PARTIES {
 SELECT * FROM OFFENDER_INTERESTED_PARTIES WHERE
 }
 
INSERT_INTERESTED_PARTIES {
insert into OFFENDER_INTERESTED_PARTIES(PARTY_DESCRIPTION, PARTY_TYPE, PARTY_COMMENT, OFFENDER_BOOK_ID, RECORD_TYPE, RECORD_ID, CREATE_USER_ID, CREATE_DATETIME ,MODIFY_DATETIME, MODIFY_USER_ID) values (:partyDescription, :partyType, :partyComment, :offenderBookId, :recordType, :recordId, :createUserId,current_timestamp, null, null)
}

UPDATE_INTERESTED_PARTIES {
 UPDATE OFFENDER_INTERESTED_PARTIES SET PARTY_DESCRIPTION = :partyDescription, PARTY_TYPE = :partyType, PARTY_COMMENT = :partyComment, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID = :modifyUserId WHERE PARTY_ID = :partyId
}

DELETE_INTERESTED_PARTIES {
 DELETE FROM OFFENDER_INTERESTED_PARTIES WHERE PARTY_ID = :partyId
}
