SENTENCE_HISTORY_GRID_DATA {

SELECT OFF_SENT.offender_book_id, OFF_SENT.RECORD_DATETIME HistoryDate, TO_CHAR (OFF_SENT.RECORD_DATETIME, 'HH24:MI') HistoryTime,OFF_SENT.CALC_REASON_CODE,
      OFF_SENT.OFFENDER_SENT_CALCULATION_ID,
      OFF_SENT.COMMENT_TEXT,SM.STAFF_ID, SM.LAST_NAME || ', ' || SM.FIRST_NAME STAFF_NAME
	  FROM OFFENDER_SENT_CALCULATIONS OFF_SENT, STAFF_MEMBERS SM
	  WHERE OFF_SENT.OFFENDER_BOOK_ID = :offenderBookId
	  AND SM.USER_ID = :userId
	  AND OFF_SENT.CREATE_USER_ID = SM.USER_ID
	  ORDER BY OFF_SENT.CREATE_DATETIME Desc
}