RES_COD {
SELECT RESULT_CODE,
DESCRIPTION,
DISPOSITION_CODE,
oms_miscellaneous_getdesccode('OFF_RESULT',DISPOSITION_CODE) code,
oms_miscellaneous_getdesccode('CHARGE_STS',CHARGE_STATUS)  OFFENSE_STATUS,
CONVICTION_FLAG
FROM OFFENCE_RESULT_CODES
WHERE ACTIVE_FLAG = 'Y'
ORDER BY LIST_SEQ, DESCRIPTION ASC



}