
OIMPLDUR_FIND_RGDURATIONTYPE {
SELECT code, description FROM reference_codes WHERE domain = 'CIP_DURATION' AND ( ( active_flag = 'Y' AND expired_date IS NULL ) OR '' = 'QUERY' ) ORDER BY list_seq;}

OIMPLDUR_FIND_RGPLACEMENTTYPE {
 	SELECT CODE , DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN= 'PLACE_TYPE' AND ((ACTIVE_FLAG ='Y' AND EXPIRED_DATE IS NULL ) OR '' = 'QUERY' ) ORDER BY LIST_SEQ
}

OIMPLDUR_PLACEMENTDUR_FIND_PLACEMENT_DURATIONS {
 	SELECT PLACEMENT_TYPE ,DURATION_TYPE ,MINIMUM_DURATION ,MAXIMUM_DURATION ,LIST_SEQ ,ACTIVE_FLAG ,EXPIRY_DATE ,MODIFY_USER_ID ,MODIFY_DATETIME ,CREATE_DATETIME ,
 	CREATE_USER_ID ,SEAL_FLAG ,ROW_ID ::text FROM PLACEMENT_DURATIONS 
 
}
OIMPLDUR_PLACEMENTDUR_INSERT_PLACEMENT_DURATMODULE_NAMEIONS {
 insert into PLACEMENT_DURATIONS(PLACEMENT_TYPE , DURATION_TYPE , MINIMUM_DURATION , MAXIMUM_DURATION , LIST_SEQ , ACTIVE_FLAG , EXPIRY_DATE, CREATE_DATETIME , CREATE_USER_ID ,MODIFY_USER_ID, MODIFY_DATETIME, SEAL_FLAG ) values(:placementType , :durationType , :minimumDuration , :maximumDuration , :listSeq , :activeFlag , :expiryDate , CURRENT_TIMESTAMP , :createUserId ,null,null, :sealFlag )
}

OIMPLDUR_PLACEMENTDUR_UPDATE_PLACEMENT_DURATIONS {
    update PLACEMENT_DURATIONS set PLACEMENT_TYPE = :placementType , DURATION_TYPE = :durationType , MINIMUM_DURATION = :minimumDuration , MAXIMUM_DURATION = :maximumDuration , LIST_SEQ = :listSeq , ACTIVE_FLAG = :activeFlag , EXPIRY_DATE = :expiryDate , MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP , SEAL_FLAG = :sealFlag where ROW_ID = :rowId1
}

OIMPLDUR_PLACEMENTDUR_DELETE_PLACEMENT_DURATIONS { 
DELETE FROM  PLACEMENT_DURATIONS where ROW_ID = :rowId1
}


OIMPLDUR_PLACEMENT_DUR_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'PLACE_TYPE' AND CODE = :PLACEMENTTYPE
}

OIMPLDUR_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO   V_FORM_DESC FROM   OMS_MODULES WHERE  MODULE_NAME = V_FORM_NAME
}
