
OIDESCAP_FIND_CGFKOFFESCESCAPEAGYLOCID {
  	SELECT AGY_LOC.AGY_LOC_ID  code, AGY_LOC.DESCRIPTION  description, AGY_LOC.ACTIVE_FLAG FROM AGENCY_LOCATIONS AGY_LOC ORDER BY  AGY_LOC.LIST_SEQ ,AGY_LOC.DESCRIPTION
}

OIDESCAP_FIND_CGFKOFFESCESCAPEESCORTCOD {
 	SELECT REF_CODE.CODE  code, REF_CODE.DESCRIPTION  description FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'ESCORT' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OIDESCAP_FIND_CGFKOFFESCESCAPECIRCUMSTAN {
 	SELECT REF_CODE1.CODE  code     ,REF_CODE1.DESCRIPTION  description FROM   REFERENCE_CODES REF_CODE1 WHERE   DOMAIN = 'ESC_CIRC' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OIDESCAP_OFFESC_FIND_OFFENDER_ESCAPES {
 	SELECT ESCAPE_ID ,OFFENDER_BOOK_ID ,ESCAPE_DATE ,ESCAPE_TIME ,ESCAPE_CIRCUMSTANCE_CODE ,ESCAPE_ESCORT_CODE ,ESCAPE_AGY_LOC_ID ,ARREST_AGY_CODE ,ESCAPE_COMMENT_TEXT ,SECURITY_BREACH_CODE ,RECAPTURE_DATE ,RECPATURE_TIME ,RECPATURE_COMMENT_TEXT ,READMISSION_DATE ,READMISSION_TIME ,READMISS_AGY_LOC_ID ,READMISS_COMMENT_TEXT ,ADJUST_SENTENCE_FLAG ,ESCAPE_REGISTRATION_REF ,IN_COMPANY_FLAG ,LAST_SEEN_DATE ,LAST_SEEN_TIME ,INCIDENT_NUMBER ,OFFENDER_ADJUST_ID ,ESCAPE_MOVEMENT_REASON ,RECAPTURE_MOVEMENT_REASON ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_ESCAPES 
}
OIDESCAP_OFFESC_INSERT_OFFENDER_ESCAPES {
	INSERT INTO OFFENDER_ESCAPES(ESCAPE_ID ,OFFENDER_BOOK_ID ,ESCAPE_DATE ,ESCAPE_TIME ,ESCAPE_CIRCUMSTANCE_CODE ,ESCAPE_ESCORT_CODE ,ESCAPE_AGY_LOC_ID ,ARREST_AGY_CODE ,ESCAPE_COMMENT_TEXT ,SECURITY_BREACH_CODE ,RECAPTURE_DATE ,RECPATURE_TIME ,RECPATURE_COMMENT_TEXT ,READMISSION_DATE ,READMISSION_TIME ,READMISS_AGY_LOC_ID ,READMISS_COMMENT_TEXT ,ADJUST_SENTENCE_FLAG ,ESCAPE_REGISTRATION_REF ,IN_COMPANY_FLAG ,LAST_SEEN_DATE ,LAST_SEEN_TIME ,INCIDENT_NUMBER ,OFFENDER_ADJUST_ID ,ESCAPE_MOVEMENT_REASON ,RECAPTURE_MOVEMENT_REASON ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ) VALUES(:escapeId ,:offenderBookId ,:escapeDate ,:escapeTime ,:escapeCircumstanceCode ,:escapeEscortCode ,:escapeAgyLocId ,:arrestAgyCode ,:escapeCommentText ,:securityBreachCode ,:recaptureDate ,:recpatureTime ,:recpatureCommentText ,:readmissionDate ,:readmissionTime ,:readmissAgyLocId ,:readmissCommentText ,:adjustSentenceFlag ,:escapeRegistrationRef ,:inCompanyFlag ,:lastSeenDate ,:lastSeenTime ,:incidentNumber ,:offenderAdjustId ,:escapeMovementReason ,:recaptureMovementReason ,current_timestamp ,:createUserId ,null ,null ,:sealFlag )
}

OIDESCAP_OFFESC_UPDATE_OFFENDER_ESCAPES {
	UPDATE OFFENDER_ESCAPES set ESCAPE_ID  = :escapeId ,OFFENDER_BOOK_ID  = :offenderBookId ,ESCAPE_DATE  = :escapeDate ,ESCAPE_TIME  = :escapeTime ,ESCAPE_CIRCUMSTANCE_CODE  = :escapeCircumstanceCode ,ESCAPE_ESCORT_CODE  = :escapeEscortCode ,ESCAPE_AGY_LOC_ID  = :escapeAgyLocId ,ARREST_AGY_CODE  = :arrestAgyCode ,ESCAPE_COMMENT_TEXT  = :escapeCommentText ,SECURITY_BREACH_CODE  = :securityBreachCode ,RECAPTURE_DATE  = :recaptureDate ,RECPATURE_TIME  = :recpatureTime ,RECPATURE_COMMENT_TEXT  = :recpatureCommentText ,READMISSION_DATE  = :readmissionDate ,READMISSION_TIME  = :readmissionTime ,READMISS_AGY_LOC_ID  = :readmissAgyLocId ,READMISS_COMMENT_TEXT  = :readmissCommentText ,ADJUST_SENTENCE_FLAG  = :adjustSentenceFlag ,ESCAPE_REGISTRATION_REF  = :escapeRegistrationRef ,IN_COMPANY_FLAG  = :inCompanyFlag ,LAST_SEEN_DATE  = :lastSeenDate ,LAST_SEEN_TIME  = :lastSeenTime ,INCIDENT_NUMBER  = :incidentNumber ,OFFENDER_ADJUST_ID  = :offenderAdjustId ,ESCAPE_MOVEMENT_REASON  = :escapeMovementReason ,RECAPTURE_MOVEMENT_REASON  = :recaptureMovementReason ,MODIFY_DATETIME  = current_timestamp ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag  where ESCAPE_ID  = :escapeId
}

OIDESCAP_OFFESC_DELETE_OFFENDER_ESCAPES {
    DELETE FROM OFFENDER_ESCAPES WHERE ESCAPE_ID  = :escapeId
}

OIDESCAP_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  
}

OIDESCAP_OFFESC_PRE_INSERT {
SELECT NEXTVAL ('ESCAPE_ID')
}

OIDESCAP_FIND_CGFKOFFESCSECURITYBREACHC {
 	SELECT REF_CODE.CODE  code       ,REF_CODE.DESCRIPTION  description FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'SEC_BREACH' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.CODE        ,REF_CODE.DESCRIPTION
}

OIDESCAP_FIND_CGFKOFFESCARRESTAGYCODE {
 	SELECT REF_CODE1.CODE  code      ,REF_CODE1.DESCRIPTION  description FROM   REFERENCE_CODES REF_CODE1 WHERE   DOMAIN = 'ARREST_AGY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE1.CODE        ,REF_CODE1.DESCRIPTION
}

OIDESCAP_OFF_ESC_POSTQUERY {
	 SELECT BOOKING_NO FROM  V_HEADER_BLOCK_FN(:USERID)  WHERE  OFFENDER_BOOK_ID = :OFFENDERBOOKID AND    OFFENDER_ID_DISPLAY = :OFFENDERIDDISPLAY
}

OIDESCAP_OFF_ESC_MAX_ESCAPE_DATE {
SELECT MAX(ESCAPE_DATE) FROM OFFENDER_ESCAPES WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND   READMISSION_DATE IS NULL
}
OIDESCAP_ESCAPE_CUR_PRE_QUERY {
SELECT DESCRIPTION  FROM MOVEMENT_REASONS  WHERE MOVEMENT_TYPE='REL'  AND MOVEMENT_REASON_CODE= :MOVEMENT_REASON_CODE
        }
 OIDESCAP_RECAPTURE_CUR_PRE_QUERY {
       SELECT MRRAC.DESCRIPTION FROM MOVEMENT_REASONS MRE,  MOVEMENT_REASONS MRRAC  WHERE MRE.IN_MOVEMENT_REASON_CODE=:RECAPTURE_MOVEMENT_REASON
       AND MRRAC.MOVEMENT_TYPE= MRE.IN_MOVEMENT_TYPE 
       AND MRRAC.MOVEMENT_REASON_CODE= MRE.IN_MOVEMENT_REASON_CODE  AND MRE.MOVEMENT_TYPE='REL' AND MRE.MOVEMENT_REASON_CODE=:ESCAPE_MOVEMENT_REASON
   }
   
OIDESCAP_OFF_ESCAPE_FROM_LOCATION{
select from_agy_loc_id from OFFENDER_EXTERNAL_MOVEMENTS where offender_book_id =:offenderBookId and 
movement_seq =(select max(movement_seq) from OFFENDER_EXTERNAL_MOVEMENTS where offender_book_id =:offenderBookId)
}
