
OIDTROJU_FIND_CGFKOFFEMTOPROVSTATCODE {
 	SELECT CODE , DESCRIPTION, ACTIVE_FLAG FROM   REFERENCE_CODES  WHERE   DOMAIN = 'PROV_STATE' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OIDTROJU_OFFEM_FIND_OFFENDER_EXTERNAL_MOVEMENTS {
 	SELECT OFFENDER_BOOK_ID ,MOVEMENT_SEQ ,MOVEMENT_DATE ,MOVEMENT_TIME ,INTERNAL_SCHEDULE_TYPE ,INTERNAL_SCHEDULE_REASON_CODE ,MOVEMENT_TYPE ,MOVEMENT_REASON_CODE ,DIRECTION_CODE ,ARREST_AGENCY_LOC_ID ,TO_PROV_STAT_CODE ,ESCORT_CODE ,FROM_AGY_LOC_ID ,TO_AGY_LOC_ID ,ACTIVE_FLAG ,ESCORT_TEXT ,COMMENT_TEXT ,REPORTING_DATE ,TO_CITY ,FROM_CITY ,REPORTING_TIME ,EVENT_ID ,PARENT_EVENT_ID ,TO_COUNTRY_CODE ,OJ_LOCATION_CODE ,APPLICATION_DATE ,APPLICATION_TIME ,TO_ADDRESS_ID ,FROM_ADDRESS_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_EXTERNAL_MOVEMENTS  
}
OIDTROJU_OFFEM_INSERT_OFFENDER_EXTERNAL_MOVEMENTS {
	INSERT INTO OFFENDER_EXTERNAL_MOVEMENTS(OFFENDER_BOOK_ID ,MOVEMENT_SEQ ,MOVEMENT_DATE ,MOVEMENT_TIME ,INTERNAL_SCHEDULE_TYPE ,INTERNAL_SCHEDULE_REASON_CODE ,MOVEMENT_TYPE ,MOVEMENT_REASON_CODE ,DIRECTION_CODE ,ARREST_AGENCY_LOC_ID ,TO_PROV_STAT_CODE ,ESCORT_CODE ,FROM_AGY_LOC_ID ,TO_AGY_LOC_ID ,ACTIVE_FLAG ,ESCORT_TEXT ,COMMENT_TEXT ,REPORTING_DATE ,TO_CITY ,FROM_CITY ,REPORTING_TIME ,EVENT_ID ,PARENT_EVENT_ID ,TO_COUNTRY_CODE ,OJ_LOCATION_CODE ,APPLICATION_DATE ,APPLICATION_TIME ,TO_ADDRESS_ID ,FROM_ADDRESS_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ) VALUES(:offenderBookId ,:movementSeq ,:movementDate ,:movementTime ,:internalScheduleType ,:internalScheduleReasonCode ,:movementType ,:movementReasonCode ,:directionCode ,:arrestAgencyLocId ,:toProvStatCode ,:escortCode ,:fromAgyLocId ,:toAgyLocId ,:activeFlag ,:escortText ,:commentText ,:reportingDate ,:toCity ,:fromCity ,:reportingTime ,:eventId ,:parentEventId ,:toCountryCode ,:ojLocationCode ,:applicationDate ,:applicationTime ,:toAddressId ,:fromAddressId ,:sealFlag ,CURRENT_TIMESTAMP ,:createUserId,null ,null )
}

OIDTROJU_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  
}

OIDTROJU_OFF_EM_PREINSERT {
SELECT coalesce (MAX(MOVEMENT_SEQ),0) + 1  MOVEMENT_SEQ FROM   OFFENDER_EXTERNAL_MOVEMENTS WHERE  OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIDTROJU_CGFKCHK_OFF_EM_OFF_EM_REF_TO__ {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :TOPROVSTATCODE AND     DOMAIN = 'PROV_STATE' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OIDTROJU_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  CURRENT_TIMESTAMP , UPPER(USER) FROM    DUAL
}

OIDTROJU_MAX_MOVEDATE {
SELECT MAX(MOVEMENT_DATE) FROM OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID

}
OIDTROJU_CLOSE_CONTACT_FLAG {
  SELECT CLOSE_CONTACT_FLAG FROM MOVEMENT_REASONS WHERE MOVEMENT_REASON_CODE = 'OJ'
  }
  OIDTROJU_COMM_FLAG_CUR {
   SELECT coalesce(COMMUNITY_ACTIVE_FLAG,'N') COMMUNITY_ACTIVE_FLAG,OFFENDER_BOOK_ID, OFFENDER_ID FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID
    }
OIDTROJU_UPDATE_OFFBKG_FOR_N {   
    UPDATE OFFENDER_BOOKINGS
               SET active_flag = 'N',
                   in_out_status = 'OUT',
                   agy_loc_id     = 'OUT',
                   living_unit_id = null,
                   booking_status = 'C',
                   booking_end_date = CURRENT_TIMESTAMP,
	           agency_iml_id = null,
	            MODIFY_DATETIME=current_timestamp ,
	            MODIFY_USER_ID=:modifyUserId
             WHERE OFFENDER_BOOK_ID = :offenderBookId
  }
OIDTROJU_UPDATE_OFFBKG_FOR_Y {
 UPDATE OFFENDER_BOOKINGS
                SET active_flag = 'N',
                    in_out_status = 'OUT', 
                    agy_loc_id = 'OUT',
                    living_unit_id = null,
                    booking_status = 'O',
                    booking_end_date = null,
	            agency_iml_id = null, 
	              MODIFY_DATETIME=current_timestamp ,
	            MODIFY_USER_ID=:modifyUserId
              WHERE OFFENDER_BOOK_ID = :offenderBookId
}
OIDTROJU_UPDATE_OFFBKG {
 UPDATE OFFENDER_BOOKINGS
             SET active_flag    = 'N',
                 in_out_status  = 'OUT',
                 agy_loc_id     = 'OUT',
                 living_unit_id = null,
	         agency_iml_id  = null,
	           MODIFY_DATETIME=current_timestamp ,
	            MODIFY_USER_ID=:modifyUserId  
           WHERE OFFENDER_BOOK_ID = :offenderBookId
}
OIDTROJU_VS_HEADCUR_OFF_ID {
SELECT OFFENDER_ID FROM V_HEADER_BLOCK_FN(:USERID) WHERE OFFENDER_ID_DISPLAY::text = (:OFFENDER_ID_DISPLAY::text) 
        AND ACTIVE_FLAG = 'Y' AND OFFENDER_BOOK_ID IS NOT NULL LIMIT 1
}
        
OIDTROJU_GET_MAX_BED_ASSIGN_SEQ_CUR {
SELECT coalesce(MAX(BED_ASSIGN_SEQ),0) BED_ASSIGN_SEQ FROM BED_ASSIGNMENT_HISTORIES WHERE OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID
 }
 OIDTROJU_OFFENDER_BOOKINGS {
SELECT * FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID= :OFFENDERBOOKID 
}
 OIDTROJU_UPDATE_BED_ASSIGNMENT_HISTORIES {
  UPDATE bed_assignment_histories
	 	     SET ASSIGNMENT_END_DATE = :assignmentEndDate,
	 	         ASSIGNMENT_END_TIME = :assignmentEndTime,
	 	          MODIFY_DATETIME=current_timestamp ,
	            MODIFY_USER_ID=:modifyUserId 
	 	   WHERE offender_book_id    = :offenderBookId
	 	     AND bed_assign_seq      = :bedAssignSeq
	 	     }
	 	     
	 	    
