	
	OIDTRWJU_FIND_CGFKOFFEMMOVEMENTREASONCO {
  SELECT MOVE_RSN.MOVEMENT_REASON_CODE MOVEMENT_REASON_CODE  ,MOVE_RSN.MOVEMENT_TYPE MOVEMENT_TYPE  ,MOVE_RSN.DESCRIPTION DESCRIPTION, MOVE_RSN.ACTIVE_FLAG FROM MOVEMENT_REASONS MOVE_RSN WHERE MOVEMENT_TYPE = 'TRN' AND ACTIVE_FLAG = 'Y' AND EXPIRY_DATE IS NULL AND MOVEMENT_REASON_CODE!='OJ' ORDER BY MOVE_RSN.LIST_SEQ ASC  ,MOVE_RSN.DESCRIPTION ASC
}
	OIDTRWJU_FIND_CGFKOFFEMTOAGYLOCID {
 SELECT AGY_LOC.AGY_LOC_ID , AGY_LOC.DESCRIPTION, AGY_LOC.ACTIVE_FLAG FROM AGENCY_LOCATIONS AGY_LOC WHERE AGENCY_LOCATION_TYPE ='INST' AND AGY_LOC_ID <> :agyLocId AND AGY_LOC_ID NOT IN ( 'TRN' ,'OUT' ) AND DEACTIVATION_DATE IS NULL AND ACTIVE_FLAG = 'Y' ORDER BY DESCRIPTION ,AGY_LOC_ID ASC
}
OIDTRWJU_OFFEM_FIND_OFFENDER_EXTERNAL_MOVEMENTS {
 SELECT OFFENDER_BOOK_ID ,MOVEMENT_SEQ ,MOVEMENT_DATE ,MOVEMENT_TIME ,INTERNAL_SCHEDULE_TYPE ,INTERNAL_SCHEDULE_REASON_CODE ,MOVEMENT_TYPE ,MOVEMENT_REASON_CODE ,DIRECTION_CODE ,ARREST_AGENCY_LOC_ID ,TO_PROV_STAT_CODE ,ESCORT_CODE ,FROM_AGY_LOC_ID ,TO_AGY_LOC_ID ,ACTIVE_FLAG ,ESCORT_TEXT ,COMMENT_TEXT ,REPORTING_DATE ,TO_CITY ,FROM_CITY ,REPORTING_TIME ,EVENT_ID ,PARENT_EVENT_ID ,TO_COUNTRY_CODE ,OJ_LOCATION_CODE ,APPLICATION_DATE ,APPLICATION_TIME ,TO_ADDRESS_ID ,FROM_ADDRESS_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   
 FROM OFFENDER_EXTERNAL_MOVEMENTS   where OFFENDER_BOOK_ID = :offenderBookId AND ACTIVE_FLAG = 'Y'
}

OIDTRWJU_OFFEM_INSERT_OFFENDER_EXTERNAL_MOVEMENTS {
INSERT INTO OFFENDER_EXTERNAL_MOVEMENTS(OFFENDER_BOOK_ID ,MOVEMENT_SEQ ,MOVEMENT_DATE ,MOVEMENT_TIME ,INTERNAL_SCHEDULE_TYPE ,INTERNAL_SCHEDULE_REASON_CODE ,MOVEMENT_TYPE ,MOVEMENT_REASON_CODE ,DIRECTION_CODE ,ARREST_AGENCY_LOC_ID ,TO_PROV_STAT_CODE ,ESCORT_CODE ,FROM_AGY_LOC_ID ,TO_AGY_LOC_ID ,ACTIVE_FLAG ,ESCORT_TEXT ,COMMENT_TEXT ,REPORTING_DATE ,TO_CITY ,FROM_CITY ,REPORTING_TIME ,EVENT_ID ,PARENT_EVENT_ID ,TO_COUNTRY_CODE ,OJ_LOCATION_CODE ,APPLICATION_DATE ,APPLICATION_TIME ,TO_ADDRESS_ID ,FROM_ADDRESS_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ) VALUES(:offenderBookId ,:movementSeq ,:movementDate ,:movementTime ,:internalScheduleType ,:internalScheduleReasonCode ,:movementType ,:movementReasonCode ,:directionCode ,:arrestAgencyLocId ,:toProvStatCode ,:escortCode ,:fromAgyLocId ,:toAgyLocId ,:activeFlag ,:escortText ,:commentText ,:reportingDate ,:toCity ,:fromCity ,:reportingTime ,:eventId ,:parentEventId ,:toCountryCode ,:ojLocationCode ,:applicationDate ,:applicationTime ,:toAddressId ,:fromAddressId ,:sealFlag ,current_timestamp ,:createUserId ,NULL ,NULL )
}

OIDTRWJU_SYSPFL_FIND_SYSTEM_PROFILES {
 SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  
}


	OIDTRWJU_OFF_EM_PREINSERT_C {
 SELECT coalesce (MAX(MOVEMENT_SEQ),0) + 1 FROM   OFFENDER_EXTERNAL_MOVEMENTS WHERE  OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

	OIDTRWJU_CGFKCHK_OFF_EM_OFF_EM_REF_MOV_C {
 SELECT  '1' FROM   REFERENCE_CODES WHERE  CODE = :MOVEMENTREASONCODE
}

	OIDTRWJU_CGFKCHK_OFF_EM_OFF_EM_MOVE_RS_C {
 SELECT  '1' FROM   MOVEMENT_REASONS WHERE  MOVEMENT_REASON_CODE = :MOVEMENTREASONCODE
}

	OIDTRWJU_CGFKCHK_OFF_EM_OFF_EM_MOVE2_C {
	SELECT MOVE_RSN.DESCRIPTION FROM   MOVEMENT_REASONS MOVE_RSN WHERE  (MOVE_RSN.MOVEMENT_TYPE = :MOVEMENTTYPE OR (coalesce (MOVE_RSN.MOVEMENT_TYPE :: text,'') = ''  AND coalesce (:MOVEMENTTYPE :: text,'') ='')) AND    MOVE_RSN.MOVEMENT_REASON_CODE = :MOVEMENTREASONCODE AND     MOVEMENT_TYPE = 'TRN'
 }

	OIDTRWJU_CGFKCHK_OFF_EM_OFF_EM_AGY_LOC_C {
 SELECT AGY_LOC.DESCRIPTION FROM   AGENCY_LOCATIONS AGY_LOC WHERE  AGY_LOC.AGY_LOC_ID = :TOAGYLOCID AND     AGENCY_LOCATION_TYPE IN ('INST','COMM') AND AGY_LOC_ID <> :AGYLOCID
}

	OIDTRWJU_CGWHEN_NEW_FORM_INSTANCE_C {
 SELECT  current_timestamp , upper(user) FROM   DUAL
}

OIDTRWJU_GET_MAX_VALUE
{
SELECT  coalesce(MAX(MOVEMENT_SEQ),0) + 1 seq FROM OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID=:offenderBookId 
}
OIDTRWJU_CHECKWAITLIST_AND_LOCATIONS{
SELECT COUNT (*) FROM OFFENDER_PROGRAM_PROFILES  WHERE (((OFFENDER_END_DATE IS NULL OR OFFENDER_END_DATE > :MOVEMENT_DATE)
AND OFFENDER_PROGRAM_STATUS NOT IN ('WAIT', 'PLAN'))  OR ((REJECT_DATE IS NULL OR REJECT_DATE >  :MOVEMENT_DATE
AND OFFENDER_PROGRAM_STATUS = 'WAIT'))) AND OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID    
         }

OIDTRWJU_OFFEM_UPDATE_OFFENDER_EXTERNAL_MOVEMENTS {
UPDATE OFFENDER_EXTERNAL_MOVEMENTS set MOVEMENT_DATE=:movementDate , MOVEMENT_TIME=:movementTime,MOVEMENT_REASON_CODE=:movementReasonCode ,DIRECTION_CODE=:directionCode ,FROM_AGY_LOC_ID=:fromAgyLocId ,TO_AGY_LOC_ID=:toAgyLocId ,ACTIVE_FLAG=:activeFlag ,COMMENT_TEXT=:commentText ,REPORTING_DATE=:reportingDate ,REPORTING_TIME=:reportingTime,MODIFY_USER_ID=:modifyUserId, MODIFY_DATETIME=current_timestamp
where OFFENDER_BOOK_ID=:offenderBookId and MOVEMENT_SEQ =:movementSeq

}

OIDTRWJU_OLD_OFFENDER_EXTERNAL_MOVEMENTS {

	select * from offender_external_movements where OFFENDER_BOOK_ID=:OFFENDER_BOOK_ID and MOVEMENT_SEQ=:MOVEMENT_SEQ
}