
OIDUNCTA_FIND_CGFKOFFEMFROMCITY {
   select REF_CODE3.CODE FROM_CITY  , REF_CODE3.DESCRIPTION DSP_DESCRIPTION , REF_CODE3.LIST_SEQ DSP_LIST_SEQ from REFERENCE_CODES REF_CODE3 where domain = 'CITY' and ((ACTIVE_FLAG = 'Y' and coalesce(EXPIRED_DATE ,'1010-10-10') = '1010-10-10') or '' = 'ENTER-QUERY' ) order by REF_CODE3.LIST_SEQ , REF_CODE3.DESCRIPTION
}

OIDUNCTA_FIND_CGFKOFFEMFROMAGYLOCID {
	SELECT AGY_LOC.AGY_LOC_ID  CODE ,AGY_LOC.DESCRIPTION  DESCRIPTION, ACTIVE_FLAG FROM   AGENCY_LOCATIONS AGY_LOC WHERE   AGY_LOC_ID = :toagyLocId
}

OIDUNCTA_FIND_CGFKOFFEMTOAGYLOCID {
 	SELECT AGY_LOC1.AGY_LOC_ID  CODE      ,AGY_LOC1.DESCRIPTION  DESCRIPTION, AGY_LOC1.ACTIVE_FLAG FROM   AGENCY_LOCATIONS AGY_LOC1 WHERE   ((AGENCY_LOCATION_TYPE = 'CRT' AND DEACTIVATION_DATE IS NULL AND :directionCode = 'OUT' ) OR (AGENCY_LOCATION_TYPE = (SELECT A.AGENCY_LOCATION_TYPE FROM AGENCY_LOCATIONS A WHERE A.AGY_LOC_ID=:fromAgyLocId ) AND :directionCode = 'IN' ) )
}

OIDUNCTA_FIND_CGFKOFFEMMOVEMENTTYPE {
	select REF_CODE.CODE  , REF_CODE.DOMAIN DSP_DOMAIN2 , REF_CODE.DESCRIPTION , REF_CODE.ACTIVE_FLAG DSP_ACTIVE_FLAG2 , REF_CODE.LIST_SEQ DSP_LIST_SEQ4, REF_CODE.ACTIVE_FLAG from REFERENCE_CODES REF_CODE where ( domain = 'MOVE_TYPE' and ( ( 'OUT' = 'OUT' and ( ACTIVE_FLAG = 'Y' and coalesce(EXPIRED_DATE ,'1010-10-10') = '1010-10-10' and CODE in ( 'CRT' , 'TAP' , 'INTER' ) ) ) or ( '' <> 'OUT' and ( CODE = '' ) ) ) ) order by REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION
}

OIDUNCTA_FIND_CGFKOFFEMMOVEMENTREASONCO {
 	SELECT REF_CODE1.CODE  ,REF_CODE1.DOMAIN DSP_DOMAIN    
     ,REF_CODE1.DESCRIPTION          ,REF_CODE1.ACTIVE_FLAG DSP_ACTIVE_FLAG       
  	,REF_CODE1.EXPIRED_DATE DSP_EXPIRED_DATE         ,REF_CODE1.LIST_SEQ DSP_LIST_SEQ3, REF_CODE1.ACTIVE_FLAG   FROM REFERENCE_CODES REF_CODE1 
	 WHERE DOMAIN = 'MOVE_RSN' AND        CODE IN ( SELECT MOVE_RSN.MOVEMENT_REASON_CODE                    FROM MOVEMENT_REASONS MOVE_RSN    
               WHERE MOVE_RSN.MOVEMENT_TYPE = :movementType                     AND MOVE_RSN.ACTIVE_FLAG = 'Y'                
     AND MOVE_RSN.EXPIRY_DATE IS NULL  )   
	ORDER BY REF_CODE1.LIST_SEQ  ,REF_CODE1.DESCRIPTION
}

OIDUNCTA_FIND_CGFKOFFEMTOCITY {
     select REF_CODE2.CODE  , REF_CODE2.DESCRIPTION , REF_CODE2.LIST_SEQ, REF_CODE2.ACTIVE_FLAG from REFERENCE_CODES REF_CODE2 where domain = 'CITY' and ((ACTIVE_FLAG = 'Y' and coalesce(EXPIRED_DATE ,'1010-10-10') = '1010-10-10' ) or '' = 'QUERY' ) order by REF_CODE2.LIST_SEQ , REF_CODE2.DESCRIPTION
}

OIDUNCTA_OFFEM_FIND_OFFENDER_EXTERNAL_MOVEMENTS {
  select * from ( select * from OFFENDER_EXTERNAL_MOVEMENTS where OFFENDER_BOOK_ID = :offenderBookId order by MOVEMENT_SEQ desc) as record limit 1
}
OIDUNCTA_OFFEM_INSERT_OFFENDER_EXTERNAL_MOVEMENTS {
    insert into OFFENDER_EXTERNAL_MOVEMENTS(OFFENDER_BOOK_ID , MOVEMENT_SEQ , MOVEMENT_DATE , MOVEMENT_TIME , INTERNAL_SCHEDULE_TYPE , INTERNAL_SCHEDULE_REASON_CODE , MOVEMENT_TYPE , MOVEMENT_REASON_CODE , DIRECTION_CODE , ARREST_AGENCY_LOC_ID , TO_PROV_STAT_CODE , ESCORT_CODE , FROM_AGY_LOC_ID , TO_AGY_LOC_ID , ACTIVE_FLAG , ESCORT_TEXT , COMMENT_TEXT , REPORTING_DATE , TO_CITY , FROM_CITY , REPORTING_TIME , EVENT_ID , PARENT_EVENT_ID , TO_COUNTRY_CODE , OJ_LOCATION_CODE , APPLICATION_DATE , APPLICATION_TIME , TO_ADDRESS_ID , FROM_ADDRESS_ID , SEAL_FLAG , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME) values(:offenderBookId , :movementSeq , :movementDate , :movementTime , :internalScheduleType , :internalScheduleReasonCode , :movementType , :movementReasonCode , :directionCode , :arrestAgencyLocId , :toProvStatCode , :escortCode , :fromAgyLocId , :toAgyLocId , :activeFlag , :escortText , :commentText , :reportingDate , :toCity , :fromCity , :reportingTime , :eventId , :parentEventId , :toCountryCode , :ojLocationCode , :applicationDate , :applicationTime , :toAddressId , :fromAddressId , :sealFlag , current_timestamp , :createUserId , null)
}


OIDUNCTA_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OIDUNCTA_OFF_EM_PREINSERT_ {
    SELECT COALESCE(MAX(MOVEMENT_SEQ),0) + 1 FROM   OFFENDER_EXTERNAL_MOVEMENTS WHERE  OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_REF_FRO_ {
    select REF_CODE3.DESCRIPTION , REF_CODE3.LIST_SEQ from REFERENCE_CODES REF_CODE3 where REF_CODE3.CODE = :FROMCITY and domain = 'CITY' and ((ACTIVE_FLAG = 'Y' and coalesce(EXPIRED_DATE ,'1010-10-10') = '1010-10-10') or :mode = 'QUERY')
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_REF_TO__ {
      select REF_CODE2.DESCRIPTION , REF_CODE2.LIST_SEQ from REFERENCE_CODES REF_CODE2 where REF_CODE2.CODE = :TOCITY and domain = 'CITY' and ((ACTIVE_FLAG = 'Y' and coalesce(EXPIRED_DATE ,'1010-10-10') = '1010-10-10') or :mode = 'QUERY')
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_REF_MOV_ {
    select REF_CODE1.DOMAIN , REF_CODE1.DESCRIPTION , REF_CODE1.ACTIVE_FLAG , REF_CODE1.EXPIRED_DATE , REF_CODE1.LIST_SEQ from REFERENCE_CODES REF_CODE1 where REF_CODE1.CODE = :MOVEMENTREASONCODE and ( domain = 'MOVE_RSN' and ( ( :DRVDIRECTIONCODE = 'OUT' and ( CODE in ( select MOVE_RSN.MOVEMENT_REASON_CODE from MOVEMENT_REASONS MOVE_RSN where MOVE_RSN.MOVEMENT_TYPE = :MOVEMENTTYPE and MOVE_RSN.ACTIVE_FLAG = 'Y' and coalesce(MOVE_RSN.EXPIRY_DATE ,'1010-10-10') = '1010-10-10' ) ) ) or ( :DRVDIRECTIONCODE <> 'OUT' and ( CODE = :DRVMOVEMENTREASONCODE ) ) ) )
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_MOVE_RS_ {
	SELECT  '1' FROM   MOVEMENT_REASONS WHERE  MOVEMENT_REASON_CODE = :MOVEMENTREASONCODE
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_DIRECTI_ {
	SELECT  '1' FROM   REFERENCE_CODES WHERE  CODE = :DIRECTIONCODE
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_MOVE_RE_ {
     select REF_CODE.DOMAIN , REF_CODE.DESCRIPTION , REF_CODE.ACTIVE_FLAG , REF_CODE.LIST_SEQ from REFERENCE_CODES REF_CODE where REF_CODE.CODE = :MOVEMENTTYPE and ( domain = 'MOVE_TYPE' and ( ( :DRVDIRECTIONCODE = 'OUT' and ( ACTIVE_FLAG = 'Y' and coalesce(EXPIRED_DATE ,'1010-10-10') = '1010-10-10' and CODE in ( 'CRT' , 'TAP' ) ) ) or ( :DRVDIRECTIONCODE <> 'OUT' and ( CODE = :DRVMOVEMENTTYPE ) ) ) )
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_AGY_LOC {
SELECT AGY_LOC1.AGY_LOC_ID  DESCRIPTION, AGY_LOC1.DESCRIPTION  CODE FROM   AGENCY_LOCATIONS AGY_LOC1 WHERE  
 ((AGENCY_LOCATION_TYPE = 'CRT' AND DEACTIVATION_DATE IS NULL AND 'OUT' = 'OUT')) 
}

OIDUNCTA_CGFKCHK_OFF_EM_OFF_EM_AGY_2_ {
	SELECT AGY_LOC.DESCRIPTION FROM   AGENCY_LOCATIONS AGY_LOC WHERE  AGY_LOC.AGY_LOC_ID = :FROMAGYLOCID AND     AGY_LOC_ID = :DRVTOAGYLOCID
}

OCDUNCTA_GENERATE_MOVEMENTSEQ{
  SELECT COALESCE(max(MOVEMENT_SEQ),0) + 1  FROM  OFFENDER_EXTERNAL_MOVEMENTS  WHERE offender_book_id::text = :offenderBookId
}

OCDUNCTA_GENERATE_TOAGYLOCID{
SELECT AGY_LOC1.AGY_LOC_ID   FROM   AGENCY_LOCATIONS AGY_LOC1 WHERE  AGY_LOC1.DESCRIPTION = :agylocIdDesc
}

OCDUNCTA_GENERATE_TOCITY{
SELECT REF_CODE2.CODE  FROM   REFERENCE_CODES REF_CODE2 WHERE   DOMAIN='CITY' AND REF_CODE2.DESCRIPTION = :toCityDesc
}

OIDUNCTA_OFFEM_UPDATE_OFFENDER_BOOKINGS {
update offender_bookings set agency_iml_id = null, modify_user_id = :modifyUserId, modify_datetime = current_timestamp where offender_book_id = :offenderBookId
}

OIDUNCTA_OFFEM_UPDATE_EXTERNALMOVEMENTS{
update offender_external_movements oem set active_flag = 'N', modify_user_id = :modifyUserId, modify_datetime = current_timestamp where oem.offender_book_id = :offenderBookId and oem.movement_seq < ( select MAX(movement_seq) from offender_external_movements oem1 where oem1.offender_book_id = :offenderBookId)
}

OIDUNCTA_MOVEMENT_CUR_LASTMOVETIMEDATE{
SELECT MOVEMENT_DATE, MOVEMENT_TIME, DIRECTION_CODE  FROM OFFENDER_EXTERNAL_MOVEMENTS  WHERE OFFENDER_BOOK_ID = :offenderBookId
               AND MOVEMENT_SEQ = ( SELECT MAX ( MOVEMENT_SEQ ) FROM OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID = :offenderBookId )
}
GET_OLD_RECORD_OF_OFF_EXE_MVMT{
 select * from offender_external_movements where offender_book_id = :offenderBookId and movement_seq = :movementSeq
}

GET_OLD_OFF_BKGS_BEAN{
 select * from offender_bookings where offender_book_id = :offenderBookId
}