
OMUERRCO_FIND_CGFKOFFESCSECURITYBREACHC {
 	SELECT REF_CODE.CODE  code         ,REF_CODE.DESCRIPTION  description  FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'SEC_BREACH' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.CODE        ,REF_CODE.DESCRIPTION
}

OMUERRCO_FIND_CGFKOFFESCARRESTAGYCODE {
 	SELECT REF_CODE1.CODE  code  ,REF_CODE1.DESCRIPTION  description FROM   REFERENCE_CODES REF_CODE1 WHERE   DOMAIN = 'ARREST_AGY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE1.CODE        ,REF_CODE1.DESCRIPTION
}

OMUERRCO_OFFESC_FIND_OFFENDER_ESCAPES {
 	SELECT ESCAPE_ID ,OFFENDER_BOOK_ID ,ESCAPE_DATE ,ESCAPE_TIME ,ESCAPE_CIRCUMSTANCE_CODE ,ESCAPE_ESCORT_CODE ,ESCAPE_AGY_LOC_ID ,ARREST_AGY_CODE ,ESCAPE_COMMENT_TEXT ,SECURITY_BREACH_CODE ,RECAPTURE_DATE ,RECPATURE_TIME ,RECPATURE_COMMENT_TEXT ,READMISSION_DATE ,READMISSION_TIME ,READMISS_AGY_LOC_ID ,READMISS_COMMENT_TEXT ,ADJUST_SENTENCE_FLAG ,ESCAPE_REGISTRATION_REF ,IN_COMPANY_FLAG ,LAST_SEEN_DATE ,LAST_SEEN_TIME ,INCIDENT_NUMBER ,OFFENDER_ADJUST_ID ,ESCAPE_MOVEMENT_REASON ,RECAPTURE_MOVEMENT_REASON ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_ESCAPES  
}
OMUERRCO_OFFESC_INSERT_OFFENDER_ESCAPES {
insert into OFFENDER_ESCAPES(ESCAPE_ID , OFFENDER_BOOK_ID , ESCAPE_DATE , ESCAPE_TIME , ESCAPE_CIRCUMSTANCE_CODE , ESCAPE_ESCORT_CODE , ESCAPE_AGY_LOC_ID , ARREST_AGY_CODE , ESCAPE_COMMENT_TEXT , SECURITY_BREACH_CODE , RECAPTURE_DATE , RECPATURE_TIME , RECPATURE_COMMENT_TEXT , READMISSION_DATE , READMISSION_TIME , READMISS_AGY_LOC_ID , READMISS_COMMENT_TEXT , ADJUST_SENTENCE_FLAG , ESCAPE_REGISTRATION_REF , IN_COMPANY_FLAG , LAST_SEEN_DATE , LAST_SEEN_TIME , INCIDENT_NUMBER , OFFENDER_ADJUST_ID , ESCAPE_MOVEMENT_REASON , RECAPTURE_MOVEMENT_REASON , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:escapeId , :offenderBookId , :escapeDate , :escapeTime , :escapeCircumstanceCode , :escapeEscortCode , :escapeAgyLocId , :arrestAgyCode , :escapeCommentText , :securityBreachCode , :recaptureDate , :recpatureTime , :recpatureCommentText , :readmissionDate , :readmissionTime , :readmissAgyLocId , :readmissCommentText , :adjustSentenceFlag , :escapeRegistrationRef , :inCompanyFlag , :lastSeenDate , :lastSeenTime , :incidentNumber , :offenderAdjustId , :escapeMovementReason , :recaptureMovementReason , current_timestamp , :createUserId , null , :sealFlag )
}

OMUERRCO_OFFESC_UPDATE_OFFENDER_ESCAPES {
update OFFENDER_ESCAPES set ESCAPE_ID = :escapeId , OFFENDER_BOOK_ID = :offenderBookId , ESCAPE_DATE = :escapeDate , ESCAPE_TIME = :escapeTime , ESCAPE_CIRCUMSTANCE_CODE = :escapeCircumstanceCode , ESCAPE_ESCORT_CODE = :escapeEscortCode , ESCAPE_AGY_LOC_ID = :escapeAgyLocId , ARREST_AGY_CODE = :arrestAgyCode , ESCAPE_COMMENT_TEXT = :escapeCommentText , SECURITY_BREACH_CODE = :securityBreachCode , RECAPTURE_DATE = :recaptureDate , RECPATURE_TIME = :recpatureTime , RECPATURE_COMMENT_TEXT = :recpatureCommentText , READMISSION_DATE = :readmissionDate , READMISSION_TIME = :readmissionTime , READMISS_AGY_LOC_ID = :readmissAgyLocId , READMISS_COMMENT_TEXT = :readmissCommentText , ADJUST_SENTENCE_FLAG = :adjustSentenceFlag , ESCAPE_REGISTRATION_REF = :escapeRegistrationRef , IN_COMPANY_FLAG = :inCompanyFlag , LAST_SEEN_DATE = :lastSeenDate , LAST_SEEN_TIME = :lastSeenTime , INCIDENT_NUMBER = :incidentNumber , OFFENDER_ADJUST_ID = :offenderAdjustId , ESCAPE_MOVEMENT_REASON = :escapeMovementReason , RECAPTURE_MOVEMENT_REASON = :recaptureMovementReason , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where ESCAPE_ID = :escapeId
}


OMUERRCO_OFF_ESC_PREINSERT_ {
	SELECT  NEXTVAL('ESCAPE_ID') FROM    DUAL
}

OMUERRCO_CGFKCHK_OFF_ESC_OFF_ESC_REF_S_ {
	SELECT REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.DESCRIPTION = :SECURITYBREACHCODE AND     DOMAIN = 'SEC_BREACH' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OMUERRCO_CGFKCHK_OFF_ESC_OFF_ESC_REF_A_ {
	SELECT REF_CODE1.CODE FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.DESCRIPTION = :ARRESTAGYCODE AND     DOMAIN = 'ARREST_AGY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OMUERRCO_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}


OMUERRCO_FIND_CGFKOFFESCESCAPEAGYLOCID {
 	SELECT AGY_LOC.AGY_LOC_ID  description    ,AGY_LOC.DESCRIPTION  code        FROM   AGENCY_LOCATIONS AGY_LOC ORDER BY  AGY_LOC.LIST_SEQ ,AGY_LOC.DESCRIPTION
}

OMUERRCO_FIND_CGFKOFFESCESCAPEESCORTCOD {
 	SELECT REF_CODE.CODE  description          ,REF_CODE.DESCRIPTION  code FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'ESCORT' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OMUERRCO_FIND_CGFKOFFESCESCAPECIRCUMSTAN {
 	SELECT REF_CODE1.CODE  description          ,REF_CODE1.DESCRIPTION  code FROM   REFERENCE_CODES REF_CODE1 WHERE   DOMAIN = 'ESC_CIRC' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}
