 
OCMGOBLI_FIND_CGFKGRPOBDEDUCTIONTYPE {
 	SELECT
  DED_TYPE.DEDUCTION_TYPE code, DED_TYPE.DEDUCTION_DESC description
FROM DEDUCTION_TYPES DED_TYPE
WHERE
  DED_TYPE.DEDUCTION_CATEGORY = 'FXOB'
  ORDER BY DED_TYPE.DEDUCTION_TYPE ASC

}

OCMGOBLI_FIND_CGFKSANCTIONNOTICES {
 	SELECT
  SANCTION_NOTICE_CODE CODE, DESCRIPTION, LATE_DAYS, SEQ_NUM
FROM SANCTION_NOTICES SN
WHERE
  ACTIVE_FLAG = 'Y' AND
  SN.LATE_DAYS =
    (SELECT MIN(SNX.LATE_DAYS )
     FROM SANCTION_NOTICES SNX
     WHERE
       SNX.SANCTION_NOTICE_CODE = SN.SANCTION_NOTICE_CODE AND
       SNX.ACTIVE_FLAG = 'Y' )

}

OCMGOBLI_OBGRP_FIND_OBLIGATION_GROUPS {
 	SELECT
  GROUP_ID, GROUP_CODE, GROUP_DESCRIPTION, MODIFY_USER_ID, MODIFY_DATETIME,
  CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG
FROM OBLIGATION_GROUPS

}
OCMGOBLI_OBGRP_INSERT_OBLIGATION_GROUPS {
	INSERT INTO OBLIGATION_GROUPS(GROUP_ID, GROUP_CODE, GROUP_DESCRIPTION, MODIFY_DATETIME, CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG)
	VALUES(:groupId, :groupCode, :groupDescription, current_timestamp, current_timestamp, 
	:createUserId, :sealFlag)
}

OCMGOBLI_OBGRP_UPDATE_OBLIGATION_GROUPS {
	UPDATE OBLIGATION_GROUPS set GROUP_ID = :groupId, GROUP_CODE = :groupCode, GROUP_DESCRIPTION = :groupDescription, MODIFY_USER_ID = :modifyUserId, 
	MODIFY_DATETIME = current_timestamp, SEAL_FLAG = :sealFlag where GROUP_ID = :groupId
} 

OCMGOBLI_OBGRP_DELETE_OBLIGATION_GROUPS { 
	DELETE FROM OBLIGATION_GROUPS where GROUP_ID = :groupId
} 

OCMGOBLI_GRPOB_FIND_GROUPED_OBLIGATIONS {
 	SELECT
  DEDUCTION_TYPE, GROUP_ID, MODIFY_USER_ID, MODIFY_DATETIME,
  SANCTION_NOTICE_CODE, CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG
FROM GROUPED_OBLIGATIONS
where
  GROUP_ID = :groupId
ORDER BY DEDUCTION_TYPE

}
OCMGOBLI_GRPOB_INSERT_GROUPED_OBLIGATIONS {
	INSERT INTO GROUPED_OBLIGATIONS(DEDUCTION_TYPE, GROUP_ID, MODIFY_DATETIME, SANCTION_NOTICE_CODE, CREATE_DATETIME,
	CREATE_USER_ID, SEAL_FLAG)
	VALUES(:deductionType, :groupId, :modifyDatetime, :sanctionNoticeCode, current_timestamp, :createUserId, :sealFlag)
} 

OCMGOBLI_GRPOB_UPDATE_GROUPED_OBLIGATIONS {
	UPDATE GROUPED_OBLIGATIONS set DEDUCTION_TYPE = :deductionType, GROUP_ID = :groupId, MODIFY_USER_ID = :modifyUserId, MODIFY_DATETIME =current_timestamp, 
	SANCTION_NOTICE_CODE = :sanctionNoticeCode, SEAL_FLAG = :sealFlag
	where DEDUCTION_TYPE = :deductionType AND GROUP_ID = :groupId
} 

OCMGOBLI_GRPOB_DELETE_GROUPED_OBLIGATIONS { 
	DELETE FROM GROUPED_OBLIGATIONS where DEDUCTION_TYPE = :deductionType AND GROUP_ID = :groupId 
} 


OCMGOBLI_OB_GRP_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM GROUPED_OBLIGATIONS G WHERE G.GROUP_ID = :GROUPID
}

OCMGOBLI_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION  FROM   OMS_MODULES WHERE  MODULE_NAME = :V_FORM_NAME
}

OCMGOBLI_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE(), upper(user) as USER FROM DUAL
}

OCMGOBLI_CGFKCHK_GRP_OB_GRP_OB_DED_TYP_ {
	SELECT 
  DED_TYPE.DEDUCTION_CATEGORY, DED_TYPE.DEDUCTION_DESC
FROM DEDUCTION_TYPES DED_TYPE
WHERE
  DED_TYPE.DEDUCTION_TYPE = :DEDUCTIONTYPE AND
  DED_TYPE.DEDUCTION_CATEGORY = 'FXOB' 

}
