INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_ACTIVITY' ,'WAPMED' ,'Medical' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_ACTIVITY' ,'WAPEMP' ,'Employment' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_ACTIVITY' ,'WAPEDU' ,'Education' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_ACTIVITY' ,'WAPWEL' ,'Wellbeing' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_ACTIVITY' ,'WAPCAR' ,'Carer' ,5,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_ACTIVITY' ,'WAPLEG' ,'Legal' ,6,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_ACTIVITY' ,'WAPSHO' ,'Shopping' ,7,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_UPD_IND' ,'WAPCAN' ,'Cancelled' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_UPD_IND' ,'WAPERR' ,'Entered in Error' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_UPD_IND' ,'WAPADD' ,'Added' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('WAP_UPD_IND' ,'WAPAME' ,'Amended' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );