INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OFF_PRG_STS' ,'COMP' ,'Completed' ,8,'Y' ,'Y' ,NULL ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OFF_PRG_STS' ,'REF' ,'Referred' ,9,'Y' ,'Y' ,NULL ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OFF_PRG_STS' ,'CANC' ,'Cancelled' ,10,'Y' ,'Y' ,NULL ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );