ECHO Installing components...
call mvn -f Elite2Common\pom.xml clean install -U
call mvn -f Elite2DAO\pom.xml clean install -U
call mvn -f Elite2Business\pom.xml clean install -U
call mvn -f Elite2Web\pom.xml clean install -U
ECHO Undeploying the application...
del %CATALINA_HOME%\webapps\Elite2Web.war
timeout 20 > NUL
ECHO Application undeployed...
copy Elite2Web\target\Elite2Web-1.0.war %CATALINA_HOME%\webapps\Elite2Web.war
ECHO Deployed the application...
pause