INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
select 'OCMPSSET', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.MODULE_PRIVILEGES WHERE MODULE_NAME = 'OCMPSSET' and role_id = 444);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
select 'OCMPSPAY', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.MODULE_PRIVILEGES WHERE MODULE_NAME = 'OCMPSPAY' and role_id = 444);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
select 'OCDCGPAY', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.MODULE_PRIVILEGES WHERE MODULE_NAME = 'OCDCGPAY' and role_id = 444);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
select 'OCIPDETA', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.MODULE_PRIVILEGES WHERE MODULE_NAME = 'OCIPDETA' and role_id = 444);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
select 'OCIPHIST', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.MODULE_PRIVILEGES WHERE MODULE_NAME = 'OCIPHIST' and role_id = 444);


INSERT INTO MODULE_PRIVILEGES (MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
select 'OIVCTMNG',444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',current_timestamp, 'OMS_OWNER', NULL
WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE MODULE_NAME = 'OIVCTMNG' and ROLE_ID=444);


update
	MODULE_PRIVILEGES
set
	MODULE_NAME = 'OCDCORDS',
	modify_datetime = current_timestamp,
	modify_user_id = 'OMS_OWNER'
where
	MODULE_NAME = 'OCDLEGLO';