INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE)
select 'OCMPSSET', 'Programs and Services Settings', 'SCREEN', NULL, NULL, 0, NULL, NULL, current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL, NULL
  WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.OMS_MODULES WHERE MODULE_NAME = 'OCMPSSET');

INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE)
select 'OCMPSPAY', 'Maintain Program and Services Pay', 'SCREEN', NULL, NULL, 0, NULL, NULL, current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL, NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.OMS_MODULES WHERE MODULE_NAME = 'OCMPSPAY');

INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE)
select 'OCDCGPAY', 'Confirm/Generate Pay', 'SCREEN',NULL, NULL, 0, NULL, NULL, current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL, NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.OMS_MODULES WHERE MODULE_NAME = 'OCDCGPAY');

INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE)
select 'OCIPDETA', 'Pay Details', 'SCREEN', NULL, NULL, 0, NULL, NULL, current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL, NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.OMS_MODULES WHERE MODULE_NAME = 'OCIPDETA');

INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE)
select 'OCIPHIST', 'Offender Pay History', 'SCREEN',NULL, NULL, 0, NULL, NULL, current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL, NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_OWNER.OMS_MODULES WHERE MODULE_NAME = 'OCIPHIST');

INSERT INTO OMS_MODULES (MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE, PROCESS_WORKFLOW, USER_TASK, DYNAMIC_FORM, INS_DASHBOARD)
select 'OIVCTMNG','Victim Management','SCREEN', NULL, NULL, NULL, 'OMS4', NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',current_timestamp, 'OMS_OWNER', NULL, NULL, NULL, NULL, NULL, NULL
 WHERE NOT EXISTS (SELECT 1 FROM OMS_MODULES WHERE MODULE_NAME ='OIVCTMNG');

INSERT INTO oms_modules (module_name, description, module_type, print_format_code, preview_flag, default_copy, appln_code, help_directory,create_datetime,create_user_id, modify_datetime,
	modify_user_id,seal_flag,output_type,process_workflow,user_task,dynamic_form,ins_dashboard)
 SELECT 'OCDCORDS', 'Custodial Orders', 'SCREEN', NULL, NULL, NULL, 'OMS4', NULL, CURRENT_TIMESTAMP, 'OMS_OWNER' ,
   CURRENT_TIMESTAMP, 'OMS_OWNER',null,null,null,null,null,NULL
 WHERE NOT EXISTS (SELECT 1 FROM oms_modules WHERE module_name = 'OCDCORDS');
 