alter table areas add column row_id bigserial;
alter table statutes add column row_id bigserial;
alter table CASELOAD_GRP_HOL_COMPENS add column row_id bigserial;
alter table OFFENDER_COURSE_SKILLS add column row_id bigserial;
alter table COMMUNITY_HEADER_STATUSES add column row_id bigserial;
alter table SANCTION_NOTICES add column row_id  bigserial;
alter table OFFENDER_TIER_TXN_FEE_AMOUNTS add column row_id bigserial;
alter table TRANSACTION_FEE_DETAILS add column row_id  bigserial;
alter table TIERED_TRANSACTION_FEE_AMOUNTS add column row_id  bigserial;
alter table TEAM_FUNCTIONS   add column row_id  bigserial;
alter table caseload_adm_alert_profiles   add column row_id  bigserial;
alter table caseload_adm_other_profiles   add column row_id  bigserial;
alter table OFFENDER_CASES add column row_id  bigserial;
alter table OFFENDER_SENTENCES add column row_id  bigserial;
alter table LOCKED_MODULES add column row_id  bigserial;
alter table STAFF_LOCATION_ROLES  add column row_id  bigserial;
alter table agy_int_loc_profiles  add column row_id  bigserial;
alter table OFFENDER_ALERTS  add column row_id  bigserial;
alter table temp_weightings  add column row_id  bigserial;	
alter table REFERENCE_DOMAINS  add column row_id  bigserial;
alter table EVENT_MEASURE_OUTCOMES  add column row_id  bigserial;
alter table OFFENDER_EXTERNAL_MOVEMENTS  add column row_id  bigserial;
alter table offender_case_officers add column row_id  bigserial;
alter table agency_visit_times add column row_id  bigserial;
alter table OFFENDER_SUBSTANCE_USES add column row_id  bigserial;
alter table temp_oidcount add column row_id  bigserial;
alter table staff_member_roles  add row_id bigserial;
alter table PLACEMENT_DURATIONS add column row_id bigserial;
ALTER TABLE OFFENCE_RESULT_CODES ADD row_id bigserial;
ALTER TABLE STAFF_SKILLS   ADD row_id bigserial;
alter table OFFENDER_GRIEV_STAFFS  add row_id bigserial;
alter table order_proposals add column row_id bigserial;
alter table OMS_MODULES_HELP add column row_id bigserial;
alter table offender_course_attendances add column row_id bigserial;
alter table course_activities add row_id bigserial;
alter table case_review_periods add row_id bigserial;
alter table OFFENDER_TXN_FEE_DETAILS add row_id bigserial;
alter table BANK_CLEAR_RECONCILES_TMP add row_id bigserial;