insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(5,'SERIOUS_OFFENDER_FORMATTER', '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId" } }, "seriousOffenders": { "*": { "offender_id_display": "body.prisonerDetails[#2].imprisonmentDetails.dcsId", "offender_id": "body.prisonerDetails[#2].imprisonmentDetails.pin", "middle_name": "body.prisonerDetails[#2].demographics.middleName", "first_name": "body.prisonerDetails[#2].demographics.firstName", "last_name": "body.prisonerDetails[#2].demographics.surName", "birth_date": "body.prisonerDetails[#2].demographics.dob", "datetime": "header.intDatetime" } } } }, { "operation": "default", "spec": { "header": { "intId": "SeriousOffenders" } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);

insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(6,'TRANSFORM_WARNING', '[{"operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "first_name": "body.prisonerDetails[#2].demographics.firstName", "last_name": "body.prisonerDetails[#2].demographics.surName", "sex_code": "body.prisonerDetails[#2].demographics.gender", "birth_date": "body.prisonerDetails[#2].demographics.dob", "offender_id_display": "body.prisonerDetails[#2].imprisonmentDetails.dcsId" } }, "offenderBookingDetails": { "*": { "booking_no": "body.prisonerDetails[#2].imprisonmentDetails.imprisonmentId", "booking_begin_date": "body.prisonerDetails[#2].imprisonmentDetails.intakeDate", "booking_status": "body.prisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } }, "offenderReleaseDetails": { "*": { "movement_date": "body.prisonerDetails[#2].imprisonmentDetails.releaseDateTime", "movement_reason_code": "body.prisonerDetails[#2].imprisonmentDetails.releaseReason" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.prisonerDetails[#2].housing.pod", "housing_lev_2_code": "body.prisonerDetails[#2].housing.unit", "housing_lev_3_code": "body.prisonerDetails[#2].housing.cell" } }, "warnings": { "*": { "description": "body.prisonerDetails[#4].alerts[#2].alertCode", "createdate": "body.prisonerDetails[#4].alerts[#2].alertStartDate", "expirydate": "body.prisonerDetails[#4].alerts[#2].alertEndDate", "comment_text": "body.prisonerDetails[#4].alerts[#2].alertComment" } }, "offenderFinancialDetails": { "*": { "current_balance": "body.prisonerDetails[#2].financials.accountBalance", "balance": "body.prisonerDetails[#2].financials.resettlementAccountBalance" } } } }, { "operation": "default", "spec": { "header": { "intId": "UnilinkWARN" } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);

insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(7,'PRISONER_MOVEMENTS_FORMATTER', '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.prisonerDetails[#2].imprisonmentDetails.offenderNumber", "offender_id": "body.prisonerDetails[#2].imprisonmentDetails.pin" } }, "offenderBookingDetails": { "*": { "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.prisonerDetails[#2].housing.pod", "housing_lev_2_code": "body.prisonerDetails[#2].housing.unit", "housing_lev_3_code": "body.prisonerDetails[#2].housing.cell" } } } }, { "operation": "default", "spec": { "header": { "intId": "Unilink-LOCA" } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);

insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(8,'ACTIVE_PRISONER_FORMATTER', '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.activePrisonerDetails[#2].imprisonmentDetails.dcsId", "offender_id": "body.activePrisonerDetails[#2].imprisonmentDetails.pin", "middle_name": "body.activePrisonerDetails[#2].demographics.middleName", "first_name": "body.activePrisonerDetails[#2].demographics.firstName", "last_name": "body.activePrisonerDetails[#2].demographics.surName", "birth_date": "body.activePrisonerDetails[#2].demographics.dob" } }, "offenderBookingDetails": { "*": { "booking_begin_date": "body.activePrisonerDetails[#2].imprisonmentDetails.intakeDatetime", "booking_status": "body.activePrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.activePrisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.activePrisonerDetails[#2].housing.unit" } }, "offenderReleaseDetails": { "*": { "movement_date": "body.activePrisonerDetails[#2].imprisonmentDetails.releaseDateTime" } } } }, { "operation": "default", "spec": { "header": { "intId": "CurrentPrisoners" } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);
insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(9,'RELEASED_PRISONER_FORMATTER', '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.releasedPrisonerDetails[#2].imprisonmentDetails.dcsId", "offender_id": "body.releasedPrisonerDetails[#2].imprisonmentDetails.pin", "middle_name": "body.releasedPrisonerDetails[#2].demographics.middleName", "first_name": "body.releasedPrisonerDetails[#2].demographics.firstName", "last_name": "body.releasedPrisonerDetails[#2].demographics.surName", "birth_date": "body.releasedPrisonerDetails[#2].demographics.dob" } }, "offenderBookingDetails": { "*": { "booking_begin_date": "body.releasedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime", "booking_status": "body.releasedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.releasedPrisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.releasedPrisonerDetails[#2].housing.unit" } }, "offenderReleaseDetails": { "*": { "movement_date": "body.releasedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime" } } } }, { "operation": "default", "spec": { "header": { "intId": "CurrentPrisoners" } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);

insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(10,'ESCAPED_PRISONER_FORMATTER', '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.escapedPrisonerDetails[#2].imprisonmentDetails.dcsId", "offender_id": "body.escapedPrisonerDetails[#2].imprisonmentDetails.pin", "middle_name": "body.escapedPrisonerDetails[#2].demographics.middleName", "first_name": "body.escapedPrisonerDetails[#2].demographics.firstName", "last_name": "body.escapedPrisonerDetails[#2].demographics.surName", "birth_date": "body.escapedPrisonerDetails[#2].demographics.dob" } }, "offenderBookingDetails": { "*": { "booking_begin_date": "body.escapedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime", "booking_status": "body.escapedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.escapedPrisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.escapedPrisonerDetails[#2].housing.unit" } }, "offenderReleaseDetails": { "*": { "movement_date": "body.escapedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime" } } } }, { "operation": "default", "spec": { "header": { "intId": "CurrentPrisoners" } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);

insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(11,'LEARNING_SYSTEM_FORMATTER', '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "first_name": "body.prisonerDetails[#2].demographics.firstName", "last_name": "body.prisonerDetails[#2].demographics.surName", "offender_id": "body.prisonerDetails[#2].imprisonmentDetails.offenderNumber" } }, "offenderBookingDetails": { "*": { "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } } } }, { "operation": "default", "spec": { "header": { "intId": "LearningSystem" } } } ] ', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);

insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) 
 values(12,'CURRENT_PRISONER_FORMATTER', '[ { "operation": "shift", "spec": { "activePrisoners": { "header": { "*": "header.&" }, "body": { "activePrisonerDetails": { "*": "body.activePrisonerDetails[]" } } }, "escapePrisoners": { "body": { "escapedPrisonerDetails": { "*": "body.escapedPrisonerDetails[]" } } }, "releasePrisoners": { "body": { "releasedPrisonerDetails": { "*": "body.releasedPrisonerDetails[]" } } } } } ] ', current_timestamp, 'OMS_OWNER', current_timestamp, NULL);
 
insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) values(13,'TRANSFORM_SERVICE', '[ { "operation": "shift", "spec": { "ProcessInput": { "body": { "prisonerDetails": { "*": { "imprisonmentDetails": { "pin": "offenderBookId" }, "informationDirective": "RequestType" } } } } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER');
 
insert into JSON_SPEC(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) values(14,'TRANSFORM_ERROR', '[ { "operation": "shift", "spec": { "userDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } } } }, { "operation": "default", "spec": { "body": { "Error": "The prisioner does not Exist in Elite" } } } ]', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER');
 
insert into json_spec(id, spec_key, json_specs, create_datetime, create_user_id, modify_datetime, modify_user_id) values(15,'TRANSFORM_EXTERNAL', '[ { "operation": "shift", "spec": { "userDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "identifierDetails": { "*": { "identifier": "body.personDetails.imprisonmentDetails.pin" } }, "nameDetails": { "*": { "first_name": "body.personDetails.demographics.firstName", "last_name": "body.personDetails.demographics.surName", "sex_code": "body.personDetails.demographics.gender", "birth_date": "body.personDetails.demographics.dob" } }, "aliasDetails": { "*": { "familyname": "body.personDetails.alias[#2].firstName", "eliteoffenderid": "body.personDetails.alias[#2].offenderId", "givenname": "body.personDetails.alias[#2].lastname", "dateofbirth": "body.personDetails.alias[#2].dob" } }, "warningDetails": { "*": { "description": "body.personDetails.alerts[#2].alertCode", "alert_type": "body.personDetails.alerts[#2].alertType", "createdate": "body.personDetails.alerts[#2].alertStartDate", "expirydate": "body.personDetails.alerts[#2].alertEndDate", "comment_text": "body.personDetails.alerts[#2].alertComment" } }, "residenceDetails": { "*": { "streetnumber": "body.personDetails.address.road.roadNumber", "streetname": "body.personDetails.address.road.roadName", "city": "body.personDetails.address.localityName", "state": "body.personDetails.address.stateOrTerritoryCode", "country": "body.personDetails.address.countryName", "postal": "body.personDetails.address.postCode", "address": "body.personDetails.address.unstructuredAddressLine", "recordeddate": "body.personDetails.address.recordedDate" } }, "occupation": { "*": { "employment_type": "body.personDetails.demographics.occupation" } } } }, { "operation": "default", "spec": { "header": { "intId": "OffenderDetail" } } }  ] ', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER');