INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME,
 CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OUMRELMD', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER', NULL);

Insert into MODULE_PRIVILEGES (MODULE_NAME,ROLE_ID,ACCESS_PRIVILEGE,VERIFICATION_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG)
values ('OIIMYOFF',444,'A','Y',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER',null);

Insert into MODULE_PRIVILEGES (MODULE_NAME,ROLE_ID,ACCESS_PRIVILEGE,VERIFICATION_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG)
values ('OCIMYOFF',444,'A','Y',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER',null);


INSERT INTO MODULE_PRIVILEGES
(MODULE_NAME,ROLE_ID,ACCESS_PRIVILEGE,VERIFICATION_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG)
VALUES('OIRMASSET', 444, 'A', 'Y',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER',null);
