TAG_HEADER_CNOTE_CUR{
	SELECT CASE_NOTE_SUB_TYPE 
	FROM OFFENDER_CASE_NOTES 
	WHERE OFFENDER_BOOK_ID = :offenderBookId 
	AND NOTE_SOURCE_CODE = 'COMM' 
	AND CASE_NOTE_TYPE = :caseNoteType
	ORDER BY CONTACT_TIME DESC
}
TAG_HEADER_GET_TYPE_CUR{
	SELECT CASELOAD_TYPE
    FROM CASELOADS
    WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID
          FROM STAFF_MEMBERS
          WHERE USER_ID = :currentUser)
}
TAG_HEADER_GET_COUNT_CUR{
	SELECT   COUNT(ROOT_OFFENDER_ID)
    FROM OFFENDER_BOOKINGS
    WHERE ROOT_OFFENDER_ID = :rootOffenderId
    GROUP BY ROOT_OFFENDER_ID
}
TAG_HEADER_CHECK_MAX_BOOKING{
	 SELECT MAX(OFFENDER_BOOK_ID)
     FROM OFFENDER_BOOKINGS
     WHERE ROOT_OFFENDER_ID = :rootOffenderId
}