
OUMHLHIS_FIND_LIVINGUNIT1RG {
  select LIV_UNIT.LIVING_UNIT_CODE DESCRIPTION , LIV_UNIT.LIVING_UNIT_ID, LIV_UNIT.ACTIVE_FLAG from LIVING_UNITS LIV_UNIT 
where LIV_UNIT.AGY_LOC_ID = coalesce (( select CASELOAD_ID from CASELOADS where UPPER(DESCRIPTION)= 
UPPER(:AGY_LOC_ID)), :AGY_LOC_ID) and LIV_UNIT.PARENT_LIVING_UNIT_ID is null
}


OUMHLHIS_FIND_LIVINGUNIT2RG {
 	SELECT LIV_UNIT.LIVING_UNIT_CODE  DESCRIPTION , LIV_UNIT.LIVING_UNIT_ID , LIV_UNIT.ACTIVE_FLAG FROM   LIVING_UNITS LIV_UNIT WHERE  
 	LIV_UNIT.AGY_LOC_ID= :AGY_LOC_ID 
 	AND LIV_UNIT.PARENT_LIVING_UNIT_ID=:LEVEL1ID 
 	}

OUMHLHIS_FIND_LIVINGUNIT3RG {
 	SELECT LIV_UNIT.LIVING_UNIT_CODE  DESCRIPTION , LIV_UNIT.LIVING_UNIT_ID, LIV_UNIT.ACTIVE_FLAG  FROM   LIVING_UNITS LIV_UNIT WHERE  
 	LIV_UNIT.AGY_LOC_ID=:AGY_LOC_ID  AND LIV_UNIT.PARENT_LIVING_UNIT_ID=:LEVEL2ID 
}

OUMHLHIS_FIND_LIVINGUNIT4RG {
 	SELECT LIV_UNIT.LIVING_UNIT_CODE  DESCRIPTION , LIV_UNIT.LIVING_UNIT_ID , LIV_UNIT.ACTIVE_FLAG  FROM   LIVING_UNITS LIV_UNIT 
 	WHERE   LIV_UNIT.AGY_LOC_ID=:AGY_LOC_ID  AND LIV_UNIT.PARENT_LIVING_UNIT_ID=:LEVEL3ID 
}


OUMHLHIS_SET_LIVING_UNIT_LEVELS_ {
	SELECT LU.LEVEL_1_CODE, LU.LEVEL_2_CODE, LU.LEVEL_3_CODE, LU.LEVEL_4_CODE FROM LIVING_UNITS LU WHERE LU.LIVING_UNIT_ID = :P_LU_ID
}

OUMHLHIS_CASELOAD_ID {
	SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID =UPPER(:userId)
}

OUMHLHIS_CASELOAD_CODE {
	SELECT tag_establishment_get_agy_loc_desc(:CASELOADID) FROM DUAL
}
OUMHLHIS_GET_LIVING_UNIT_ID {
SELECT LU1.LIVING_UNIT_ID LEVEL_1_ID, LU1.LIVING_UNIT_CODE LEVEL_1_CODE,
LU2.LIVING_UNIT_ID LEVEL_2_ID, LU2.LIVING_UNIT_CODE LEVEL_2_CODE,
 LU3.LIVING_UNIT_ID LEVEL_3_ID, LU3.LIVING_UNIT_CODE LEVEL_3_CODE,
 LU4.LIVING_UNIT_ID LEVEL_4_ID, LU4.LIVING_UNIT_CODE LEVEL_4_CODE
FROM LIVING_UNITS LU1,LIVING_UNITS LU2,LIVING_UNITS LU3, LIVING_UNITS LU4
WHERE LU1.AGY_LOC_ID = :AGY_LOC_ID AND
LU2.PARENT_LIVING_UNIT_ID = LU1.LIVING_UNIT_ID AND 
LU3.PARENT_LIVING_UNIT_ID = LU2.LIVING_UNIT_ID AND
LU4.PARENT_LIVING_UNIT_ID = LU3.LIVING_UNIT_ID 
ORDER BY LU1.LIST_SEQ
}
GETTING_CASELOAD_ID{
SELECT CASELOAD_ID FROM CASELOADS WHERE DESCRIPTION=:DESCRIPTION

}
