
OUIMERGE_FIND_RGSTATUS {
 	SELECT DESCRIPTION  , CODE, LIST_SEQ   FROM REFERENCE_CODES   WHERE DOMAIN = 'TRANS_STAT'  ORDER BY LIST_SEQ , DESCRIPTION , CODE
}

OUIMERGE_FIND_RGSOURCE {
 	SELECT DESCRIPTION  ,        CODE   FROM REFERENCE_CODES   WHERE DOMAIN = 'TRANS_SOURCE'  ORDER BY LIST_SEQ , DESCRIPTION , CODE
}

OUIMERGE_TRANSACTIONS_FIND_MERGE_TRANSACTIONS {
 select
	MERGE_TRANSACTION_ID,
	REQUEST_DATE,
	TAG_REFERENCE_CODES_GETDESCCODE ('TRANS_STAT',
	REQUEST_STATUS_CODE) REQUEST_STATUS_CODE,
	QUEUE_MESSAGE_ID,
	TAG_REFERENCE_CODES_GETDESCCODE ('TRANS_SOURCE',
	TRANSACTION_SOURCE) TRANSACTION_SOURCE,
	OFFENDER_BOOK_ID_1,
	ROOT_OFFENDER_ID_1,
	OFFENDER_ID_1,
	OFFENDER_ID_DISPLAY_1,
	LAST_NAME_1,
	FIRST_NAME_1,
	OFFENDER_BOOK_ID_2,
	ROOT_OFFENDER_ID_2,
	OFFENDER_ID_2,
	OFFENDER_ID_DISPLAY_2,
	LAST_NAME_2,
	FIRST_NAME_2,
	MODIFY_USER_ID,
	CREATE_DATETIME,
	CREATE_USER_ID,
	MODIFY_DATETIME,
	SEAL_FLAG,
	TRANSACTION_TYPE ,
	TAG_UTILS_GET_STAFF_NAME(TAG_UTILS_GET_STAFF_ID(CREATE_USER_ID)) STAFFNAME,
	OUMTRNBK_GET_BOOKING_NO(OFFENDER_BOOK_ID_1) TRNBOOKINGNO
from
	MERGE_TRANSACTIONS
where
 	
}
