
OCDPAYOB_FIND_CGFKOFFTXNSUBACCOUNTTYPE {
 	SELECT SUB_ACCOUNT_TYPE CODE , ACCOUNT_NAME DESCRIPTION FROM TRANSACTION_OPERATIONS OT , ACCOUNT_CODES AC
 	WHERE OT.MODULE_NAME = 'OCDPAYOB' AND OT.CASELOAD_ID = :CASELOADID AND OT.DR_ACCOUNT_CODE = AC.ACCOUNT_CODE
}

OCDPAYOB_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 	SELECT TXN_ID ,TXN_ENTRY_SEQ ,CASELOAD_ID ,OFFENDER_ID ,OFFENDER_BOOK_ID ,TXN_POSTING_TYPE ,TXN_TYPE ,TXN_ENTRY_DESC ,TXN_ENTRY_AMOUNT ,TXN_ENTRY_DATE ,SUB_ACCOUNT_TYPE ,TXN_REFERENCE_NUMBER ,MODIFY_DATE ,RECEIPT_NUMBER ,SLIP_PRINTED_FLAG ,TRANSFER_CASELOAD_ID ,RECEIPT_PRINTED_FLAG ,PRE_WITHHOLD_AMOUNT ,DEDUCTION_FLAG ,CLOSING_CHEQUE_NUMBER ,REMITTER_NAME ,PAYEE_CODE ,PAYEE_NAME_TEXT ,PAYEE_CORPORATE_ID ,PAYEE_PERSON_ID ,ADJUST_TXN_ID ,ADJUST_TXN_ENTRY_ID ,ADJUST_OFFENDER_ID ,ADJUST_ACCOUNT_CODE ,TXN_ADJUSTED_FLAG ,DEDUCTION_TYPE ,INFO_NUMBER ,HOLD_CLEAR_FLAG ,HOLD_UNTIL_DATE ,HOLD_NUMBER ,GROSS_AMOUNT ,GROSS_NET_FLAG ,REMITTER_ID ,APPLY_SPENDING_LIMIT_AMOUNT ,RECEIPT_PENDING_PRINT_FLAG ,SEAL_FLAG ,ORG_TXN_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_TRANSACTIONS  /* where  */
}
OCDPAYOB_OFFTXN_INSERT_OFFENDER_TRANSACTIONS {
insert into OFFENDER_TRANSACTIONS(TXN_ID , TXN_ENTRY_SEQ , CASELOAD_ID , OFFENDER_ID , OFFENDER_BOOK_ID , TXN_POSTING_TYPE , TXN_TYPE , TXN_ENTRY_DESC , TXN_ENTRY_AMOUNT , TXN_ENTRY_DATE , SUB_ACCOUNT_TYPE , TXN_REFERENCE_NUMBER , MODIFY_DATE , RECEIPT_NUMBER , SLIP_PRINTED_FLAG , TRANSFER_CASELOAD_ID , RECEIPT_PRINTED_FLAG , PRE_WITHHOLD_AMOUNT , DEDUCTION_FLAG , CLOSING_CHEQUE_NUMBER , REMITTER_NAME , PAYEE_CODE , PAYEE_NAME_TEXT , PAYEE_CORPORATE_ID , PAYEE_PERSON_ID , ADJUST_TXN_ID , ADJUST_TXN_ENTRY_ID , ADJUST_OFFENDER_ID , ADJUST_ACCOUNT_CODE , TXN_ADJUSTED_FLAG , DEDUCTION_TYPE , INFO_NUMBER , HOLD_CLEAR_FLAG , HOLD_UNTIL_DATE , HOLD_NUMBER , GROSS_AMOUNT , GROSS_NET_FLAG , REMITTER_ID , APPLY_SPENDING_LIMIT_AMOUNT , RECEIPT_PENDING_PRINT_FLAG , SEAL_FLAG , ORG_TXN_TYPE , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID ) values(:txnId , :txnEntrySeq , :caseloadId , :offenderId , :offenderBookId , :txnPostingType , :txnType , :txnEntryDesc , :txnEntryAmount , :txnEntryDate , :subAccountType , :txnReferenceNumber , :modifyDate , :receiptNumber , :slipPrintedFlag , :transferCaseloadId , :receiptPrintedFlag , :preWithholdAmount , :deductionFlag , :closingChequeNumber , :remitterName , :payeeCode , :payeeNameText , :payeeCorporateId , :payeePersonId , :adjustTxnId , :adjustTxnEntryId , :adjustOffenderId , :adjustAccountCode , :txnAdjustedFlag , :deductionType , :infoNumber , :holdClearFlag , :holdUntilDate , :holdNumber , :grossAmount , :grossNetFlag , :remitterId , :applySpendingLimitAmount , :receiptPendingPrintFlag , :sealFlag , :orgTxnType , current_timestamp , :createUserId , current_timestamp , :modifyUserId ) 
}

OCDPAYOB_OFFBNC_FIND_OFFENDER_BENEFICIARIES {
 	SELECT BENEFICIARY_ID ,OFFENDER_DEDUCTION_ID ,OFFENDER_ID ,PERSON_ID ,CORPORATE_ID ,PRIORITY ,AMOUNT ,PERCENT ,OVERRIDE_AMOUNT ,RECEIVED_AMOUNT ,MODIFY_USER_ID ,MODIFY_DATETIME ,UNKNOWN_BEN_ID ,COMMENT_TEXT ,MONTHLY_AMOUNT ,RECURSIVE_AMOUNT ,TBD_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG 
 	FROM OFFENDER_BENEFICIARIES  
}
OCDPAYOB_OFFBNC_UPDATE_OFFENDER_BENEFICIARIES {
 UPDATE OFFENDER_BENEFICIARIES SET OVERRIDE_AMOUNT = :OVERRIDEAMOUNT, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID = :modifyUserId WHERE OFFENDER_DEDUCTION_ID = :OFFENDERDEDUCTIONID AND OFFENDER_ID = :OFFENDERID AND BENEFICIARY_ID = :BENEFICIARYID 
}
OCDPAYOB_OFFBNC_UPDATE_OFFENDER_BENEFICIARIES_OVERRIDDEN {
update OFFENDER_BENEFICIARIES set OVERRIDE_AMOUNT = null, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID = :modifyUserId where OFFENDER_DEDUCTION_ID = :OFFENDERDEDUCTIONID and OFFENDER_ID = :OFFENDERID and BENEFICIARY_ID = :BENEFICIARYID
}
OCDPAYOB_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OCDPAYOB_CGFKCHK_OFF_TXN_OFF_TXN_REF_C_ {
	SELECT ACCOUNT_NAME DSP_DESCRIPTION FROM TRANSACTION_OPERATIONS OT, ACCOUNT_CODES AC WHERE OT.MODULE_NAME = 'OCDPAYOB' AND AC.SUB_ACCOUNT_TYPE = :SUBACCOUNTTYPE AND OT.CASELOAD_ID = :CASELOADID AND OT.DR_ACCOUNT_CODE = AC.ACCOUNT_CODE
}

OCDPAYOB_CGWHEN_NEW_FORM_INSTANCE_ {
SELECT SYSDATE(),USER FROM DUAL;
}

OCDPAYOB_CGFKCHK_OFF_BNC_OFF_BNC_CORP {
	SELECT CORP.CORPORATE_NAME FROM   CORPORATES CORP WHERE  CORP.CORPORATE_ID = :CORPORATEID
}

OCDPAYOB_CGFKCHK_OFF_BNC_OFF_BNC_PER_F {
	SELECT PER.LAST_NAME ,PER.FIRST_NAME FROM   PERSONS PER WHERE  PER.PERSON_ID = :PERSONID
}

OCDPAYOB_CGFKCHK_OFF_BNC_OFF_BNC_OFF_D {
	SELECT OFF_DED.DEDUCTION_TYPE ,OFF_DED.INFORMATION_NUMBER ,DED_TYPE.DEDUCTION_DESC 
	FROM   OFFENDER_DEDUCTIONS OFF_DED ,DEDUCTION_TYPES DED_TYPE 
	WHERE  OFF_DED.OFFENDER_DEDUCTION_ID = :OFFENDERDEDUCTIONID AND    DED_TYPE.DEDUCTION_TYPE = OFF_DED.DEDUCTION_TYPE
}
OCDPAYOB_POST_QUERY {
SELECT MAX_TOTAL_AMOUNT, MAX_MONTHLY_AMOUNT, MAX_RECURSIVE_AMOUNT
        FROM OFFENDER_DEDUCTIONS
        WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
  }
OCDPAYOB_WRITE_OFF_CUR {
       SELECT ADJUSTMENT_REASON_CODE,coalesce (ADJUSTMENT_AMOUNT, 0) ADJUSTMENT_AMOUNT
        FROM OFFENDER_DEDUCTIONS
       WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
          }
OCDPAYOB_V_MON_AMT {
  SELECT COALESCE(SUM(CASE TXN_POST_USAGE  WHEN 'CR' THEN  TXN_ENTRY_AMOUNT  WHEN 'DR' THEN  TXN_ENTRY_AMOUNT*-1 END), 0)
           FROM   BENEFICIARY_TRANSACTIONS
           WHERE  OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
           AND    COALESCE(CORPORATE_ID, 0) = COALESCE(:CORPORATE_ID, 0)
           AND    COALESCE(PERSON_ID, 0) = COALESCE(:PERSON_ID, 0)
           AND    date_trunc('month', TXN_ENTRY_DATE) = date_trunc( 'month',current_timestamp) 
           }
OCDPAYOB_V_REC_MAX {
  SELECT MONTHS_BETWEEN(date_trunc('month',SYSDATE()), date_trunc('month',EFFECTIVE_DATE))+1 FROM OFFENDER_DEDUCTIONS
     WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID    
     }
OCDPAYOB_V_BALANCE {
 SELECT coalesce (BALANCE,0)FROM   OFFENDER_SUB_ACCOUNTS WHERE  TRUST_ACCOUNT_CODE = (
     SELECT ACCOUNT_CODE FROM   ACCOUNT_CODES WHERE  SUB_ACCOUNT_TYPE = :subAccountType AND    CASELOAD_TYPE = :caseloadType)
     AND CASELOAD_ID = :caseloadId AND    OFFENDER_ID = :rootOffenderId
       
}
OCDPAYOB_TXN_ID {
	  select nextval('txn_id') from dual
}
OCDPAYOB_TXN_ID_COUNT {
SELECT COUNT(*) FROM GL_TRANSACTIONS
                WHERE TXN_ID = :TXNID
}
OCDPAYOB_TXN_TYPE {
	SELECT TXN_TYPE FROM TRANSACTION_OPERATIONS
        WHERE  DR_ACCOUNT_CODE = (
                  SELECT ACCOUNT_CODE
                  FROM   ACCOUNT_CODES
                  WHERE  SUB_ACCOUNT_TYPE = :SUBACCOUNTTYPE
                  AND    CASELOAD_TYPE = :CASELOADTYPE)
        AND    CASELOAD_ID = :CASELOADID
        AND    MODULE_NAME = 'OCDPAYOB'
}


OCDPAYOB_OFFENDER_FEES_SECTION{
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_CODE = 'CF_DEDUCTION'
}
OCDPAYOB_OFF_FEE_BILL_TRN_DATA{
 SELECT A.BOOKING_NO, A.BILL_GENERATE_DATETIME, A.CASELOAD_ID, A.OFFENDER_FEE_ID, A.FEE_CODE, OFBT.* FROM ( SELECT OFB.*, VHB.BOOKING_NO, OFAP.CASELOAD_ID, OFAP.FEE_CODE FROM OFF_FEE_BILLS OFB, OFF_FEE_ACCOUNT_PROFILE OFAP, V_HEADER_BLOCK VHB WHERE OFAP.OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID AND VHB.OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID AND OFAP.OFFENDER_FEE_ID = OFB.OFFENDER_FEE_ID ) A, OFF_FEE_BILL_TRANSACTIONS OFBT WHERE OFBT.BILL_ID = A.BILL_ID AND OFBT.CREATE_DATETIME = ( SELECT MAX(B.CREATE_DATETIME) FROM OFF_FEE_BILL_TRANSACTIONS B WHERE B.BILL_ID = A.BILL_ID ) ORDER BY A.CREATE_DATETIME ASC 
}
OCDPAYOB_OFF_FEE_BILL_TRANSACTIONS_UPDATE{
UPDATE off_fee_bill_transactions SET bill_txn_amount = :balance, MODIFY_DATETIME=current_timestamp, MODIFY_USER_ID=:modifyUserId WHERE bill_id = :billId AND bill_txn_no = :billTxnNo
 }
  OCDBRECI_GET_CURRENT_STAFFDETAILS{
  SELECT STAFF_ID FROM   STAFF_MEMBERS  STAFF WHERE  USER_ID = :userId	
 }
OCDPAYOB_OFF_FEE_BILLS_TRANSACTIONS_PRE_INSERT{
select coalesce (max(BILL_TXN_NO),0)+1 from OFF_FEE_BILL_TRANSACTIONS where BILL_ID = :BILL_ID;
}
OCDPAYOB_OFF_BILL_TRN_INSERT {
insert into off_fee_bill_transactions ( bill_id, bill_txn_no, bill_txn_datetime, bill_txn_staff_id, bill_txn_user, bill_txn_type, bill_txn_amount, trust_txn_id, trust_txn_entry_seq, off_adj_canc_rsn, off_adj_sub_rsn, off_adj_txn_id, off_adj_rev_rsn, bill_status, bill_aging_start_date, bill_aging_end_date, bill_txn_comment, original_bill_id, original_bill_txn_no, original_off_adj_txn_id, billing_statement_id, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag, txn_statement_generated_flag ) values ( :billId, :billTxnNo, current_timestamp, :billTxnStaffId, :billTxnUser, :billTxnType, :billTxnAmount, :trustTxnId, :trustTxnEntrySeq, :offAdjCancRsn, :offAdjSubRsn, :offAdjTxnId, :offAdjRevRsn, :billStatus, :billAgingStartDate, :billAgingEndDate, :billTxnComment, :originalBillId, :originalBillTxnNo, :originalOffAdjTxnId, :billingStatementId, current_timestamp, :createUserId, null, null, :sealFlag, :txnStatementGeneratedFlag )
}
OCDPAYOB_GET_CR_DEDUCT_TO{
select account_code from caseload_deduction_profiles where deduction_type = :deductionType and caseload_id = :caseLoadId
}

OCDPAYOB_INSERT_INTO_OFFENDER_TRANSACTIONS{
INSERT INTO OFFENDER_TRANSACTIONS ( TXN_ID, TXN_ENTRY_SEQ, CASELOAD_ID, OFFENDER_ID, OFFENDER_BOOK_ID, TXN_POSTING_TYPE, TXN_TYPE, TXN_ENTRY_DESC, TXN_ENTRY_AMOUNT, TXN_ENTRY_DATE, SUB_ACCOUNT_TYPE, MODIFY_DATE, CREATE_USER_ID, SLIP_PRINTED_FLAG, PRE_WITHHOLD_AMOUNT, DEDUCTION_FLAG, PAYEE_CODE, PAYEE_CORPORATE_ID, PAYEE_PERSON_ID, PAYEE_NAME_TEXT, DEDUCTION_TYPE, INFO_NUMBER, REMITTER_NAME, REMITTER_ID, RECEIPT_NUMBER, TXN_REFERENCE_NUMBER, CREATE_DATETIME, MODIFY_DATETIME) SELECT :P_trans_number, :P_trans_seq, :P_csld_id, :P_off_id, :P_off_book_id, :P_trans_post_type, :P_trans_type, :p_trans_desc, :p_trans_amount, :P_trans_date, :p_sub_act_type, CURRENT_TIMESTAMP, :userId, :p_slip_print_flag, :p_pre_ded_amount, :p_deduction_flag, :p_payee_code, :p_payee_corp_id, :p_payee_person_id, :p_payee_name_text, :p_deduction_type, :p_info_number, :p_remitter_name, :p_remitter_id, :p_receipt_number, :p_txn_reference_number, current_timestamp, null FROM DUAL 
}
   
OCDPAYOB_GET_DR_ACCOUNT_CODE {
SELECT dr_account_code FROM TRANSACTION_OPERATIONS WHERE  MODULE_NAME = 'OCDPAYOB' AND TXN_TYPE = :txnType AND CASELOAD_ID = :caseloadId
}

OCDPAYOB_GET_SUB_ACCOUNT_DESC{
SELECT DESCRIPTION FROM TRANSACTION_TYPES WHERE TXN_TYPE = :txnType
}

OCDPAYOB_GET_MAX_TXN_ENTRY_SEQ{
select  coalesce(MAX(TXN_ENTRY_SEQ),0)+1  from OFFENDER_TRANSACTIONS where txn_id=:txnId  and OFFENDER_ID=:offenderId
}

OCDPAYOB_GET_STAFF_ID{
SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID = USER
}

OCDPAYOB_OFF_BILL_STMT_INSERT_QUERY {
insert into OFF_BILLING_STATEMENTS (BILLING_STATEMENT_ID, CASELOAD_ID, ROOT_OFFENDER_ID, BILLING_CYCLE_START_DATE, BILLING_CYCLE_END_DATE, STATEMENT_GENERATE_DATETIME, STATEMENT_GENERATE_STAFF_ID, STATEMENT_GENERATE_USER, BEGINING_BALANCE_AMOUNT, PAYMENTS_CREDITS_AMOUNT, BILLINGS_AMOUNT, ENDING_BALANCE_AMOUNT, OFFENDER_BOOK_ID, CASE_PLAN_ID, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME) values (:billingStatementId, :caseloadId, :rootOffenderId, DATE_TRUNC('day',:billingCycleStartDate), DATE_TRUNC('day',:billingCycleEndDate), DATE_TRUNC('day',:statementGenerateDatetime), :statementGenerateStaffId, :statementGenerateUser, :beginingBalanceAmount, :paymentsCreditsAmount, :billingsAmount, :endingBalanceAmount, :offenderBookId, :casePlanId, :createUserId, :createDatetime, null) 
}

OCDPAYOB_UPDATE_OFF_FEE_BILLS {
update OFF_FEE_BILLS set STATEMENT_GENERATED_FLAG = 'Y', BILLING_STATEMENT_ID =:billingStatementId, BILL_STATEMENT_DATE = trunc(:statementGenerateDatetime), MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID =:modifyUserId, BILL_AR_DUE_DATE = DATE_TRUNC('day',:statementGenerateDatetime)+ 30, BILL_LDPP_START_DATE = DATE_TRUNC('day',:statementGenerateDatetime)+ 31, BILL_LDPP_END_DATE = DATE_TRUNC('day',:statementGenerateDatetime)+ 30 where BILL_ID = :billId 
}
 
 OCDPAYOB_GET_MAX_GL_ENTRY_SEQ{
 select  coalesce(MAX(GL_ENTRY_SEQ),0)  from gl_transactions where txn_id=:txnId  and OFFENDER_ID=:offenderId
 }
 
OCDPAYOB_UPDATE_OFF_FEE_BILLS_DATE{
UPDATE OFF_FEE_BILLS SET BILL_LDPP_START_DATE = DATE_TRUNC('day',:billLdppStartDate), MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId WHERE BILL_ID = :billId
}

OCDPAYOB_OFFENDER_BENEFICIARIES_OLD_DATA{
select * from offender_beneficiaries ob where beneficiary_id=:beneficiaryId 
}