
OCUOBHIS_OFFOBLHTY_FIND_OFFENDER_OBLIGATION_HTY {
 	SELECT OFFENDER_DEDUCTION_ID ,DEDUCTION_SEQ ,INFORMATION_NUMBER ,DEDUCTION_TYPE ,ADJUSTED_AMOUNT ,MODIFIED_USER_ID ,MODIFIED_DATETIME ,MAX_TOTAL_AMOUNT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_OBLIGATION_HTY  /* where  */
}

OCUOBHIS_OCUOBHIS_WHENNEWFORMINSTANCE {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = :P_PROFILE_TYPE AND PROFILE_CODE = :P_PROFILE_CODE
}

OCUOBHIS_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO   V_FORM_DESC FROM   OMS_MODULES WHERE  MODULE_NAME = V_FORM_NAME
}
