
OTDOALLO_FIND_CGFKOFFDEDDEDUCTIONSTATUS {
 	SELECT REF_CODE.CODE  DEDUCTION_STATUS  /* CG$FK */        ,REF_CODE.DESCRIPTION  DSP_DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'DED_STATUS' ORDER BY  REF_CODE.CODE        ,REF_CODE.DESCRIPTION
}

OTDOALLO_FIND_CGFKOFFDRRECEIPTTXNTYPE {
 	SELECT TXN_TYPE.TXN_TYPE  CODE  /* CG$FK */        ,TXN_TYPE.DESCRIPTION  DESCRIPTION FROM   TRANSACTION_TYPES TXN_TYPE WHERE   TXN_USAGE = 'R' AND ACTIVE_FLAG = 'Y'  AND ALL_CASELOAD_FLAG = 'Y' ORDER BY  TXN_TYPE.TXN_TYPE        ,TXN_TYPE.DESCRIPTION
}

OTDOALLO_FIND_CGFKOFFDEDDEDUCTIONTYPE {
 	SELECT DED_TYPE.DEDUCTION_TYPE  CODE  /* CG$FK */        ,DED_TYPE.DEDUCTION_DESC  DESCRIPTION FROM   DEDUCTION_TYPES DED_TYPE WHERE   DEDUCTION_CATEGORY = 'ALCN' AND  DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE  FROM CASELOAD_DEDUCTION_DETAILS WHERE CASELOAD_ID = :caseLoadId ) ORDER BY  DED_TYPE.DEDUCTION_TYPE        ,DED_TYPE.DEDUCTION_DESC
}

OTDOALLO_OFFDED_FIND_OFFENDER_DEDUCTIONS {
 	SELECT OFFENDER_DEDUCTION_ID ,CASELOAD_ID ,OFFENDER_ID ,CREDIT_LIMIT ,DEDUCTION_TYPE ,DEDUCTION_STATUS ,DEDUCTION_PRIORITY ,INFORMATION_NUMBER ,DEDUCTION_PERCENTAGE ,PROCESS_PRIORITY_NUMBER ,EFFECTIVE_DATE ,COMMENT_TEXT ,FIFO_FLAG ,PAYEE_PERSON_ID ,PAYEE_CORPORATE_ID ,MAX_MONTHLY_AMOUNT ,MAX_TOTAL_AMOUNT ,DEDUCTION_AMOUNT ,ADJUSTMENT_REASON_CODE ,ADJUSTMENT_AMOUNT ,ADJUSTMENT_USER_ID ,ADJUSTMENT_TXN_ID ,ADJUSTMENT_TEXT ,MODIFY_DATE ,PAY_DEDUCTION_FLAG ,MAX_RECURSIVE_AMOUNT ,GROUP_ID ,CASE_ID ,PARENT_DEDUCTION_ID ,JS_STATUS ,COLLECT_AGENCY_AMOUNT ,COLLECT_AGENCY_FLAG ,COLLECT_SENT_DATE ,OFFENDER_PAYMENT_PROFILE_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID 
 	FROM OFFENDER_DEDUCTIONS   WHERE CASELOAD_ID = :caseLoadId and OFFENDER_ID = :offenderId and DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE  FROM CASELOAD_DEDUCTION_DETAILS 
WHERE DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE FROM CASELOAD_DEDUCTION_PROFILES WHERE DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE 
 FROM DEDUCTION_TYPES WHERE DEDUCTION_CATEGORY = 'ALCN'))) ORDER BY PROCESS_PRIORITY_NUMBER ,PROCESS_PRIORITY_NUMBER,DEDUCTION_PRIORITY
}
OTDOALLO_OFFDED_INSERT_OFFENDER_DEDUCTIONS {
	INSERT INTO OFFENDER_DEDUCTIONS(OFFENDER_DEDUCTION_ID ,CASELOAD_ID ,OFFENDER_ID ,CREDIT_LIMIT ,DEDUCTION_TYPE ,DEDUCTION_STATUS ,DEDUCTION_PRIORITY ,INFORMATION_NUMBER ,DEDUCTION_PERCENTAGE ,PROCESS_PRIORITY_NUMBER ,EFFECTIVE_DATE ,COMMENT_TEXT ,FIFO_FLAG ,PAYEE_PERSON_ID ,PAYEE_CORPORATE_ID ,MAX_MONTHLY_AMOUNT ,MAX_TOTAL_AMOUNT ,DEDUCTION_AMOUNT ,ADJUSTMENT_REASON_CODE ,ADJUSTMENT_AMOUNT ,ADJUSTMENT_USER_ID ,ADJUSTMENT_TXN_ID ,ADJUSTMENT_TEXT ,MODIFY_DATE ,PAY_DEDUCTION_FLAG ,MAX_RECURSIVE_AMOUNT ,GROUP_ID ,CASE_ID ,PARENT_DEDUCTION_ID ,JS_STATUS ,COLLECT_AGENCY_AMOUNT ,COLLECT_AGENCY_FLAG ,COLLECT_SENT_DATE ,OFFENDER_PAYMENT_PROFILE_ID ,SEAL_FLAG, 	CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME
  ) VALUES(:offenderDeductionId ,:caseloadId ,:offenderId ,:creditLimit ,:deductionType ,:deductionStatus ,:deductionPriority ,:informationNumber ,:deductionPercentage ,:processPriorityNumber ,:effectiveDate ,:commentText ,:fifoFlag ,:payeePersonId ,:payeeCorporateId ,:maxMonthlyAmount ,:maxTotalAmount ,:deductionAmount ,:adjustmentReasonCode ,:adjustmentAmount ,:adjustmentUserId ,:adjustmentTxnId ,:adjustmentText ,:modifyDate ,:payDeductionFlag ,:maxRecursiveAmount ,:groupId ,:caseId ,:parentDeductionId ,:jsStatus ,:collectAgencyAmount ,:collectAgencyFlag ,:collectSentDate ,:offenderPaymentProfileId ,:sealFlag,current_timestamp,:createUserId,current_timestamp
  )
}

OTDOALLO_OFFDED_UPDATE_OFFENDER_DEDUCTIONS {
	UPDATE OFFENDER_DEDUCTIONS set OFFENDER_DEDUCTION_ID  = :offenderDeductionId ,CASELOAD_ID  = :caseloadId ,OFFENDER_ID  = :offenderId ,CREDIT_LIMIT  = :creditLimit ,DEDUCTION_TYPE  = :deductionType ,DEDUCTION_STATUS  = :deductionStatus ,DEDUCTION_PRIORITY  = :deductionPriority ,INFORMATION_NUMBER  = :informationNumber ,DEDUCTION_PERCENTAGE  = :deductionPercentage ,PROCESS_PRIORITY_NUMBER  = :processPriorityNumber ,EFFECTIVE_DATE  = :effectiveDate ,COMMENT_TEXT  = :commentText ,FIFO_FLAG  = :fifoFlag ,PAYEE_PERSON_ID  = :payeePersonId ,PAYEE_CORPORATE_ID  = :payeeCorporateId ,MAX_MONTHLY_AMOUNT  = :maxMonthlyAmount ,MAX_TOTAL_AMOUNT  = :maxTotalAmount ,DEDUCTION_AMOUNT  = :deductionAmount ,ADJUSTMENT_REASON_CODE  = :adjustmentReasonCode ,ADJUSTMENT_AMOUNT  = :adjustmentAmount ,ADJUSTMENT_USER_ID  = :adjustmentUserId ,ADJUSTMENT_TXN_ID  = :adjustmentTxnId ,ADJUSTMENT_TEXT  = :adjustmentText ,MODIFY_DATE  = :modifyDate ,PAY_DEDUCTION_FLAG  = :payDeductionFlag ,MAX_RECURSIVE_AMOUNT  = :maxRecursiveAmount ,GROUP_ID  = :groupId ,CASE_ID  = :caseId ,PARENT_DEDUCTION_ID  = :parentDeductionId ,JS_STATUS  = :jsStatus ,COLLECT_AGENCY_AMOUNT  = :collectAgencyAmount ,COLLECT_AGENCY_FLAG  = :collectAgencyFlag ,COLLECT_SENT_DATE  = :collectSentDate ,OFFENDER_PAYMENT_PROFILE_ID  = :offenderPaymentProfileId ,SEAL_FLAG  = :sealFlag, MODIFY_DATETIME =current_timestamp, MODIFY_USER_ID =:modifyUserId WHERE OFFENDER_DEDUCTION_ID  = :offenderDeductionId
}

OTDOALLO_OFFDED_DELETE_OFFENDER_DEDUCTIONS { 
	DELETE FROM OFFENDER_DEDUCTIONS where OFFENDER_DEDUCTION_ID  = :offenderDeductionId
}

OTDOALLO_OFFDR_FIND_OFFENDER_DEDUCTION_RECEIPTS {
 	SELECT LIST_SEQ ,RECEIPT_PERCENTAGE ,RECEIPT_TXN_TYPE ,OFFENDER_DEDUCTION_ID ,FLAT_RATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG 
 	FROM OFFENDER_DEDUCTION_RECEIPTS   WHERE  OFFENDER_DEDUCTION_ID = :offenderDeductionId ORDER BY RECEIPT_TXN_TYPE
}
OTDOALLO_OFFDR_INSERT_OFFENDER_DEDUCTION_RECEIPTS {
	INSERT INTO OFFENDER_DEDUCTION_RECEIPTS(LIST_SEQ ,RECEIPT_PERCENTAGE ,RECEIPT_TXN_TYPE ,OFFENDER_DEDUCTION_ID ,FLAT_RATE ,SEAL_FLAG ,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME) VALUES(:listSeq ,:receiptPercentage ,:receiptTxnType ,:offenderDeductionId ,:flatRate ,:sealFlag ,current_timestamp,:createUserId,current_timestamp)
}

OTDOALLO_OFFDR_UPDATE_OFFENDER_DEDUCTION_RECEIPTS {
	UPDATE OFFENDER_DEDUCTION_RECEIPTS set LIST_SEQ  = :listSeq ,RECEIPT_PERCENTAGE  = :receiptPercentage ,RECEIPT_TXN_TYPE  = :receiptTxnType ,OFFENDER_DEDUCTION_ID  = :offenderDeductionId ,FLAT_RATE  = :flatRate ,SEAL_FLAG  = :sealFlag WHERE RECEIPT_TXN_TYPE  = :receiptTxnType AND OFFENDER_DEDUCTION_ID  = :offenderDeductionId
}

OTDOALLO_OFFDR_DELETE_OFFENDER_DEDUCTION_RECEIPTS { 
	DELETE FROM OFFENDER_DEDUCTION_RECEIPTS WHERE RECEIPT_TXN_TYPE  = :receiptTxnType AND OFFENDER_DEDUCTION_ID  = :offenderDeductionId
}

OTDOALLO_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OTDOALLO_CGFKCHK_OFF_DED_OFF_DED_REF_C {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :DEDUCTIONSTATUS AND     DOMAIN = 'DED_STATUS'
}

OTDOALLO_CGFKCHK_OFF_DED_OFF_DED_DED_T {
	SELECT DED_TYPE.DEDUCTION_DESC FROM   DEDUCTION_TYPES DED_TYPE WHERE  DED_TYPE.DEDUCTION_TYPE = :DEDUCTIONTYPE AND     DEDUCTION_CATEGORY = 'ALCN' AND DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE FROM CASELOAD_DEDUCTION_DETAILS WHERE CASELOAD_ID = :CASELOADID)
}

OTDOALLO_CGFKCHK_OFF_DR_OFF_DR_TXN_TYP {
	SELECT TXN_TYPE.DESCRIPTION FROM   TRANSACTION_TYPES TXN_TYPE WHERE  TXN_TYPE.TXN_TYPE = :RECEIPTTXNTYPE AND     TXN_USAGE = 'R' AND ACTIVE_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y'
}

OTDOALLO_CGWHEN_NEW_FORM_INSTANCE {
--SELECT  SYSDATE, USER FROM    SYS.DUAL
SELECT current_timestamp, USER FROM DUAL
}

OTDOALLO_GETMODIFYUSERID_CUR {
SELECT CODE  FROM REFERENCE_CODES WHERE DOMAIN = 'BALANCE_TYPE' 
           AND CODE = ( SELECT FROM_BALANCE_TYPE
          FROM DEDUCTION_TYPES 
         WHERE DEDUCTION_CATEGORY = 'ALCN' 
               AND DEDUCTION_TYPE = :deductionType)
}

OTDOALLO_OFFDEDPOSTQUERY {
 SELECT EXTERNAL_PRIORITY_NO,   INTERNAL_PRIORITY_NO, MAX_MONTHLY_AMOUNT, MAX_TOTAL_AMOUNT FROM CASELOAD_DEDUCTION_PROFILES WHERE DEDUCTION_TYPE = :deductionType  AND   CASELOAD_ID = :caseLoadId
}

OTDOALLO_VALIDATE_RECEIPT_TXN_TYPE {
 SELECT PERCENTAGE RECEIPT_PERCENTAGE, FLAT_RATE, RECEIPT_TXN_TYPE   FROM CASELOAD_DEDUCTION_DETAILS
		          WHERE CASELOAD_ID = :caseLoadId
		            AND DEDUCTION_TYPE = :deductionType
		            AND RECEIPT_TXN_TYPE = :receiptTxnType
}

OTDOALLO_OFF_DED_FIND_POST_INSERT {
 SELECT RECEIPT_TXN_TYPE, PERCENTAGE RECEIPT_PERCENTAGE, FLAT_RATE      FROM CASELOAD_DEDUCTION_DETAILS
		          WHERE CASELOAD_ID = :caseLoadId
		            AND DEDUCTION_TYPE = :deductionType
}

OTDOALLO_GETMAX_ID_CUR {
--SELECT DEDUCTION_ID.NEXTVAL   DED_ID   FROM DUAL
SELECT NEXTVAL('DEDUCTION_ID')   DED_ID   FROM DUAL

}

OTDOALLO_FIND_INFORMATIONNUMBER {
--SELECT TO_CHAR(SYSDATE,'MMDDYYYY') info_no FROM   DUAL
SELECT TO_CHAR(current_timestamp ,'MMDDYYYY') info_no FROM   DUAL
}

OTDOALLO_FIND_IN_COUNT {
SELECT COUNT(*)  FROM   OFFENDER_DEDUCTIONS	WHERE  OFFENDER_ID   =  :offenderId
     		AND    DEDUCTION_TYPE =  :deductionType	AND    SUBSTR(INFORMATION_NUMBER,1,8) = :informationNum
}

OTDOALLO_OFF_DR_KEY_DELREC {
	SELECT DEDUCTION_TYPE FROM OFFENDER_TRANSACTIONS WHERE CASELOAD_ID = :caseloadId AND OFFENDER_ID = :offenderId AND DEDUCTION_TYPE = :deductionType
}

OTDOALLO_CNT_DED_RCPT {
SELECT COUNT(*) FROM OFFENDER_DEDUCTION_RECEIPTS WHERE OFFENDER_DEDUCTION_ID = :offenderDeductionId
}
OTDOALLO_OLD_DATA{
select * from OFFENDER_DEDUCTIONS where  offender_deduction_id = :offender_deduction_id 
}