
OTDSDEDU_FIND_CGFKSUSDEDCASELOADID {
 	SELECT CSLD.CASELOAD_ID  CODE  /* CG$FK */        ,CSLD.DESCRIPTION  DESCRIPTION FROM   CASELOADS CSLD WHERE   TRUST_ACCOUNTS_FLAG = 'Y' ORDER BY  CSLD.CASELOAD_ID ASC
}

OTDSDEDU_FIND_CGFKSUSDTDEDUCTIONTYPE {
 	SELECT DED_TYPE.DEDUCTION_TYPE  CODE  /* CG$FK */        ,DED_TYPE.DEDUCTION_DESC  DESCRIPTION        ,DED_TYPE.DEDUCTION_CATEGORY  DEDUCTION_CATEGORY FROM   DEDUCTION_TYPES DED_TYPE WHERE   DED_TYPE.DEDUCTION_CATEGORY IN ('FXOB' ,'CROB' ) AND ((ACTIVE_FLAG = 'Y' AND EXPIRY_DATE IS NULL ) OR '' = 'QUERY' ) AND CASELOAD_CODE IN ('BOTH' ,:CASELOADTYPE )
}

OTDSDEDU_SUSDED_FIND_SUSPEND_DEDUCTIONS {
 	--SELECT SUSPEND_DEDUCTION_ID ,CASELOAD_ID ,START_DATE ,END_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM SUSPEND_DEDUCTIONS
   -- WHERE (:caseloadId IS NULL OR CASELOAD_ID =  :caseloadId) and (:startDate IS NULL OR TO_CHAR(START_DATE, 'DD/MM/YYYY') = :startDate) and (:endDate IS NULL OR TO_CHAR(END_DATE, 'DD/MM/YYYY') = :endDate) 
       -- ORDER BY CASELOAD_ID
   select
	SUSPEND_DEDUCTION_ID ,
	CASELOAD_ID ,
	START_DATE ,
	END_DATE ,
	CREATE_DATETIME ,
	CREATE_USER_ID ,
	MODIFY_DATETIME ,
	MODIFY_USER_ID ,
	SEAL_FLAG
from
	SUSPEND_DEDUCTIONS
where
	(coalesce(:caseloadId ::text,'')=''
		or CASELOAD_ID = :caseloadId)
	and (coalesce(:startDate ::text,'')=''
		or TO_CHAR(START_DATE, 'DD/MM/YYYY') = :startDate)
	and (coalesce(:endDate ::text,'')=''
		or TO_CHAR(END_DATE, 'DD/MM/YYYY') = :endDate)
order by
	--CASELOAD_ID desc
	 modify_datetime  desc 
}
OTDSDEDU_SUSDED_INSERT_SUSPEND_DEDUCTIONS {
	--INSERT INTO SUSPEND_DEDUCTIONS(SUSPEND_DEDUCTION_ID ,CASELOAD_ID ,START_DATE ,END_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ) VALUES(:suspendDeductionId ,:caseloadId ,:startDate ,:endDate ,:createDatetime ,:createUserId ,:modifyDatetime ,:modifyUserId ,:sealFlag )
	INSERT INTO SUSPEND_DEDUCTIONS(SUSPEND_DEDUCTION_ID ,CASELOAD_ID ,START_DATE ,END_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:suspendDeductionId ,:caseloadId ,:startDate ,:endDate ,CURRENT_TIMESTAMP ,:createUserId ,CURRENT_TIMESTAMP,:sealFlag )
}

OTDSDEDU_SUSDED_UPDATE_SUSPEND_DEDUCTIONS {
	--UPDATE SUSPEND_DEDUCTIONS set CASELOAD_ID  = :caseloadId ,START_DATE  = :startDate ,END_DATE  = :endDate ,CREATE_DATETIME  = :createDatetime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = :modifyDatetime ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag WHERE SUSPEND_DEDUCTION_ID  = :suspendDeductionId 
	UPDATE SUSPEND_DEDUCTIONS set CASELOAD_ID  = :caseloadId ,START_DATE  = :startDate ,END_DATE  = :endDate ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag WHERE SUSPEND_DEDUCTION_ID  = :suspendDeductionId 
}

OTDSDEDU_SUSDED_DELETE_SUSPEND_DEDUCTIONS { 
	DELETE FROM SUSPEND_DEDUCTIONS WHERE SUSPEND_DEDUCTION_ID  = :suspendDeductionId
}

OTDSDEDU_SUSDT_FIND_SUSPEND_DEDUCTION_TYPES {
 	SELECT SUSPEND_DEDUCTION_ID ,DEDUCTION_TYPE ,SUSPENDED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM SUSPEND_DEDUCTION_TYPES WHERE SUSPEND_DEDUCTION_ID = :SUSPENDDEDUCTIONID
}
OTDSDEDU_SUSDT_INSERT_SUSPEND_DEDUCTION_TYPES {
	--INSERT INTO SUSPEND_DEDUCTION_TYPES(SUSPEND_DEDUCTION_ID ,DEDUCTION_TYPE ,SUSPENDED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ) VALUES(:suspendDeductionId ,:deductionType ,:suspendedFlag ,:createDatetime ,:createUserId ,:modifyDatetime ,:modifyUserId ,:sealFlag )
	INSERT INTO SUSPEND_DEDUCTION_TYPES(SUSPEND_DEDUCTION_ID ,DEDUCTION_TYPE ,SUSPENDED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:suspendDeductionId ,:deductionType ,:suspendedFlag ,CURRENT_TIMESTAMP ,:createUserId ,CURRENT_TIMESTAMP ,:sealFlag )
}

OTDSDEDU_SUSDT_UPDATE_SUSPEND_DEDUCTION_TYPES {
	--UPDATE SUSPEND_DEDUCTION_TYPES set SUSPENDED_FLAG  = :suspendedFlag ,CREATE_DATETIME  = :createDatetime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = :modifyDatetime ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag WHERE SUSPEND_DEDUCTION_ID  = :suspendDeductionId and DEDUCTION_TYPE  = :deductionType
	UPDATE SUSPEND_DEDUCTION_TYPES set SUSPENDED_FLAG  = :suspendedFlag ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag WHERE SUSPEND_DEDUCTION_ID  = :suspendDeductionId and DEDUCTION_TYPE  = :deductionType
}

OTDSDEDU_SUSDT_DELETE_SUSPEND_DEDUCTION_TYPES { 
	DELETE FROM SUSPEND_DEDUCTION_TYPES WHERE SUSPEND_DEDUCTION_ID  = :suspendDeductionId AND DEDUCTION_TYPE = :deductionType
}


OTDSDEDU_SUS_DED_PREINSERT {
	--SELECT SUSPEND_DEDUCTION_ID.NEXTVAL FROM SYS.DUAL
	SELECT nextval('SUSPEND_DEDUCTION_ID')from DUAL
}

OTDSDEDU_CGFKCHK_SUS_DED_SUS_DED_CASEL_ {
	SELECT CSLD.DESCRIPTION FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID AND     TRUST_ACCOUNTS_FLAG = 'Y'
}

OTDSDEDU_CGFKCHK_SUS_DT_SUS_DT_DED_TYP_ {
	SELECT DED_TYPE.DEDUCTION_DESC ,DED_TYPE.DEDUCTION_CATEGORY FROM   DEDUCTION_TYPES DED_TYPE WHERE  DED_TYPE.DEDUCTION_TYPE = :DEDUCTIONTYPE AND     DED_TYPE.DEDUCTION_CATEGORY IN ('FXOB','CROB') AND ((ACTIVE_FLAG = 'Y' AND EXPIRY_DATE IS NULL) OR :MODE = 'QUERY') AND CASELOAD_CODE IN ('BOTH',:CASELOADTYPE)
}

OTDSDEDU_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
OTDSDEDU_DEDUCTIONS_UPDATE_DEDUCTION_STATUS {
	CALL OMS_OWNER.DEDUCTIONS.UPDATE_DEDUCTION_STATUS(:P_SUS_DED_ID, :P_CASELOAD_ID, :P_SUSPEND_FLAG, :P_DEDUCTION_TYPE)
}
OTDSDEDU_DEDUCTIONS_SUSPEND_OFF_DEDUCTIONS {
 CALL OMS_OWNER.DEDUCTIONS.SUSPEND_OFF_DEDUCTIONS()
}
OTDSDEDU_CHECK_OVERLAP_DATE {
	SELECT count(0) FROM   suspend_deductions WHERE  caseload_id = :caseloadId AND  ((:flag = 'S' AND  TO_DATE(:startDate, 'DD/MM/YYYY') BETWEEN start_date AND end_date /*AND (:endDate IS NULL OR end_date != TO_DATE(:endDate, 'DD/MM/YYYY'))*/)
      OR (:flag = 'E' AND  (TO_DATE(:endDate, 'DD/MM/YYYY') BETWEEN start_date AND end_date OR (start_date BETWEEN TO_DATE(:startDate, 'DD/MM/YYYY') AND TO_DATE(:endDate, 'DD/MM/YYYY')) OR (end_date BETWEEN TO_DATE(:startDate, 'DD/MM/YYYY') AND TO_DATE(:endDate, 'DD/MM/YYYY'))) AND  start_date != TO_DATE(:startDate, 'DD/MM/YYYY'))) 
}