
OTIOPINQ_OFFDED_FIND_OFFENDER_DEDUCTIONS {
 	SELECT OFFENDER_DEDUCTION_ID ,CASELOAD_ID ,OFFENDER_ID ,CREDIT_LIMIT ,DEDUCTION_TYPE ,DEDUCTION_STATUS ,DEDUCTION_PRIORITY ,INFORMATION_NUMBER ,DEDUCTION_PERCENTAGE ,PROCESS_PRIORITY_NUMBER ,EFFECTIVE_DATE ,COMMENT_TEXT ,FIFO_FLAG ,PAYEE_PERSON_ID ,PAYEE_CORPORATE_ID ,MAX_MONTHLY_AMOUNT ,MAX_TOTAL_AMOUNT ,DEDUCTION_AMOUNT ,ADJUSTMENT_REASON_CODE ,ADJUSTMENT_AMOUNT ,ADJUSTMENT_USER_ID ,ADJUSTMENT_TXN_ID ,ADJUSTMENT_TEXT ,MODIFY_DATE ,PAY_DEDUCTION_FLAG ,MAX_RECURSIVE_AMOUNT ,GROUP_ID ,CASE_ID ,PARENT_DEDUCTION_ID ,JS_STATUS ,COLLECT_AGENCY_AMOUNT ,COLLECT_AGENCY_FLAG ,COLLECT_SENT_DATE ,OFFENDER_PAYMENT_PROFILE_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID FROM OFFENDER_DEDUCTIONS WHERE OFFENDER_ID = :offenderId AND CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE FROM DEDUCTION_TYPES WHERE DEDUCTION_CATEGORY IN ('CROB','FXOB', 'TAX'))
}
OTIOPINQ_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 SELECT TXN_ID ,TXN_ENTRY_SEQ ,CASELOAD_ID ,OFFENDER_ID ,OFFENDER_BOOK_ID ,TXN_POSTING_TYPE ,TXN_TYPE ,TXN_ENTRY_DESC ,TXN_ENTRY_AMOUNT ,TXN_ENTRY_DATE ,SUB_ACCOUNT_TYPE ,TXN_REFERENCE_NUMBER ,MODIFY_DATE ,RECEIPT_NUMBER ,SLIP_PRINTED_FLAG ,TRANSFER_CASELOAD_ID ,RECEIPT_PRINTED_FLAG ,PRE_WITHHOLD_AMOUNT ,DEDUCTION_FLAG ,CLOSING_CHEQUE_NUMBER ,REMITTER_NAME ,PAYEE_CODE ,PAYEE_NAME_TEXT ,PAYEE_CORPORATE_ID ,PAYEE_PERSON_ID ,ADJUST_TXN_ID ,ADJUST_TXN_ENTRY_ID ,ADJUST_OFFENDER_ID ,ADJUST_ACCOUNT_CODE ,TXN_ADJUSTED_FLAG ,DEDUCTION_TYPE ,INFO_NUMBER ,HOLD_CLEAR_FLAG ,HOLD_UNTIL_DATE ,HOLD_NUMBER ,GROSS_AMOUNT ,GROSS_NET_FLAG ,REMITTER_ID ,APPLY_SPENDING_LIMIT_AMOUNT ,RECEIPT_PENDING_PRINT_FLAG ,SEAL_FLAG ,ORG_TXN_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID FROM OFFENDER_TRANSACTIONS WHERE CASELOAD_ID = :caseloadId AND OFFENDER_ID = :offenderId AND DEDUCTION_TYPE = :deductionType and upper(INFO_NUMBER) = upper(:infoNumber) order by txn_entry_date desc, txn_id desc 
}
OTIOPINQ_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OTIOPINQ_OFF_BKG_PREDELETEPRE-DELETE {
	DELETE FROM OFFENDER_DEDUCTIONS O WHERE O.OFFENDER_ID = :ROOTOFFENDERID
}

OTIOPINQ_OFF_BKG_PREDELETEPRE-DELETE {
	DELETE FROM OFFENDER_TRANSACTIONS O WHERE O.OFFENDER_ID = :ROOTOFFENDERID
}

OTIOPINQ_CGFKCHK_OFF_DED_OFF_DED_DED_T {
	SELECT DED_TYPE.DEDUCTION_DESC DESCRIPTION ,DED_TYPE.DEDUCTION_TYPE CODE FROM DEDUCTION_TYPES DED_TYPE 
}

OTIOPINQ_CGWHEN_NEW_FORM_INSTANCE_ {
		SELECT SYSDATE(),USER FROM DUAL;
}
OTIOPINQ_CHK_DED_CAT {
SELECT deduction_category FROM deduction_types WHERE deduction_type = :deductionType
}

OTIOPINQ_SUB_MAX_TOT_DEDCT_AMT {
select coalesce(max_total_amount, 0) - coalesce(deduction_amount ,0) from OFFENDER_DEDUCTIONS where offender_id = :offenderId and caseload_id = :caseloadId and deduction_type = :deductionType and deduction_priority = :deductionPriority
}
OTIOPINQ_GET_DED_AMT_ON_DATE {
 select coalesce(deduction_amount, 0) from offender_mon_deductions where offender_deduction_id = :offenderDeductionId and to_char(MONTHLY_DEDUCTION_DATE,'MON') = to_char(current_timestamp,'MON') and to_char(MONTHLY_DEDUCTION_DATE,'YEAR') = to_char(current_timestamp ,'YEAR')
}
OTIOPINQ_ADJUSTMENT_AMOUNT_C {
  SELECT coalesce(Adjustment_Amount,0) FROM Offender_Deductions WHERE Offender_Deduction_ID = :offenderDeductionId
}
OTIOPINQ_LV_TOTAL_AMOUNT {
 SELECT max_total_amount, coalesce(deduction_amount, 0) deduction_amount  FROM OFFENDER_DEDUCTIONS WHERE OFFENDER_DEDUCTION_ID = :offenderDeductionId
}

