
OTUCOBWH_COWOH_FIND_OFFENDER_ADJUSTMENT_TXNS {
 	SELECT TXN_ID ,TXN_ENTRY_SEQ ,OFFENDER_ID ,OFFENDER_DEDUCTION_ID ,TXN_POSTING_TYPE ,ADJUSTMENT_DATE ,ADJUSTMENT_AMOUNT ,ADJUSTMENT_REASON_CODE ,ADJUSTMENT_TEXT ,ADJUSTMENT_USER_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_ADJUSTMENT_TXNS 
}
