INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCUVERKD', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', NULL,NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCUOVKEY', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', NULL,NULL, NULL);