
OCDPNOTE_FIND_RGSUBTYPE {
 	select
	distinct RC.DESCRIPTION ,
	W.WORK_SUB_TYPE CODE ,
	RC.LIST_SEQ
from
	WORKS W ,
	REFERENCE_CODES RC
where
	W.WORKFLOW_TYPE = 'CNOTE'
	and RC.DOMAIN = 'TASK_SUBTYPE'
	and RC.CODE = W.WORK_SUB_TYPE
	and W.WORK_TYPE = 'PROG_NOTE'
	and ((W.MANUAL_SELECT_FLAG = 'Y'
		and W.ACTIVE_FLAG = 'Y' ))
	and RC.ACTIVE_FLAG = 'Y'
order by
	LIST_SEQ ,
	DESCRIPTION ,
	CODE
}


OCDPNOTE_OFFENDERCASENOTES_FIND_OFFENDER_CASE_NOTES {
 	SELECT OFFENDER_BOOK_ID, CONTACT_DATE, CONTACT_TIME, CASE_NOTE_TYPE, CASE_NOTE_SUB_TYPE, STAFF_ID, CASE_NOTE_TEXT, AMENDMENT_FLAG, IWP_FLAG, CHECK_BOX1, CHECK_BOX2, CHECK_BOX3, CHECK_BOX4, CHECK_BOX5, EVENT_ID, CASE_NOTE_ID, NOTE_SOURCE_CODE, DATE_CREATION, TIME_CREATION, SEAL_FLAG, OBJECT_TYPE, OBJECT_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID FROM OFFENDER_CASE_NOTES
}
OCDPNOTE_OFFENDERCASENOTES_INSERT_OFFENDER_CASE_NOTES {
	INSERT INTO OFFENDER_CASE_NOTES(OFFENDER_BOOK_ID,CONTACT_DATE,CONTACT_TIME,CASE_NOTE_TYPE,CASE_NOTE_SUB_TYPE,STAFF_ID,CASE_NOTE_TEXT,AMENDMENT_FLAG,CASE_NOTE_ID,NOTE_SOURCE_CODE,DATE_CREATION,TIME_CREATION,OBJECT_TYPE,OBJECT_ID,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME)
 	VALUES(:offenderBookId, :contactDate, :contactTime, :caseNoteType, :caseNoteSubType, (SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID = upper(:createUserId)), :caseNoteText, 'N', nextval('CASE_NOTE_ID') , :noteSourceCode, :dateCreation, :timeCreation, 'OFF_PRGREF_ID', :objectId,current_timestamp,:createUserId,current_timestamp)
}

OCDPNOTE_OFFENDERCASENOTES_UPDATE_OFFENDER_CASE_NOTES {
	UPDATE OFFENDER_CASE_NOTES set CONTACT_TIME =:contactTime , MODIFY_DATETIME =current_timestamp , MODIFY_USER_ID=:modifyUserId where CASE_NOTE_ID=:caseNoteId
}


OCDPNOTE_OFFENDER_CASE_NOTES_WHENNEWRECORDINSTANCE_ {
	select
	case
		when :CASELOAD_TYPE = 'INST' then 'INSTITUTION'
		when :CASELOAD_TYPE = 'COMM' then 'COMMUNITY'
		else :CASELOAD_TYPE
	end
from
	DUAL
}

OCDPNOTE_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION  FROM OMS_MODULES WHERE MODULE_NAME = :V_FORM_NAME
}

OCDPNOTE_GLOBAL_USER_AND_CASELOADTYPE {
	SELECT CL.CASELOAD_TYPE DESCRIPTION, SM.STAFF_ID CODE FROM CASELOADS CL, STAFF_MEMBERS SM WHERE SM.USER_ID = upper(:userName) AND CL.CASELOAD_ID = SM.WORKING_CASELOAD_ID
}
OCDPNOTE_STAFF_MEMBER_NAME {
	select
	STAFF_ID code ,
	LAST_NAME || ', ' || FIRST_NAME description
from
	staff_members
}