
OCUUPSTA_FIND_RGPSPRGSTAT {
 	SELECT   REF_CODE.DESCRIPTION , REF_CODE.CODE     FROM REFERENCE_CODES REF_CODE    WHERE (:PLOVDOMAIN= 'PS_PRG_STAT'
 	AND DOMAIN = 'PS_PRG_STAT'           AND (ACTIVE_FLAG = 'Y' OR 'ENTER-QUERY' = 'ENTER-QUERY' )    
 	AND (   (:PCURRENTSTATUS = 'REF' AND REF_CODE.CODE IN('REM' , 'SUSP' , 'ABA' , '121' ) ) 
 	OR (:PCURRENTSTATUS = 'ALLOC' AND REF_CODE.CODE IN('SUSP' , 'ABA' , 'COMP' , 'REF' , '121' ) ) 
 	OR (:PCURRENTSTATUS = 'SUSP' AND REF_CODE.CODE IN('ALLOC' , 'ABA' , '121' ) )         
 	OR (:PCURRENTSTATUS = '121' AND REF_CODE.CODE IN('ALLOC' , 'COMP' , 'SUSP' , 'ABA' ) )  
 	OR (:PCURRENTSTATUS = 'ABA' AND REF_CODE.CODE IN('SUSP' ) )              
 	OR (:PCURRENTSTATUS = 'REM' AND REF_CODE.CODE IN('REF' ) )           
 	OR (:PCURRENTSTATUS = 'COMP' AND REF_CODE.CODE IN('ALLOC' , '121' ) ) ) )
 	OR (:PLOVDOMAIN= 'OPO_WR_STAT'           AND DOMAIN = 'OPO_WR_STAT' 
 	AND (ACTIVE_FLAG = 'Y' OR 'ENTER-QUERY' = 'ENTER-QUERY' )  AND ((:PCURRENTSTATUS = 'REF' AND REF_CODE.CODE IN('ACCEP' , 'REJ' ) )
 	OR (:PCURRENTSTATUS = 'ACCEP' AND REF_CODE.CODE IN('END' , 'REF' , 'SUSP' ) ) ) ) ORDER BY REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION , REF_CODE.CODE
}

OCUUPSTA_FIND_RGPSPRGOBSTS {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'PS_PRG_OBSTS' AND 
 	ACTIVE_FLAG = 'Y'   AND PARENT_CODE = :PARENTCODE ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCUUPSTA_OFFPRGOBLHTY_FIND_OFFENDER_PRG_OBLIGATION_HTY {
 	SELECT * FROM OFFENDER_PRG_OBLIGATION_HTY WHERE OFFENDER_PRG_OBLIGATION_ID=:OFFENDER_PRG_OBLIGATION_ID ORDER BY STATUS_CHANGE_DATE DESC
}

OCUUPSTA_CHECK_CHILD_UPDATE_ {
	SELECT OFFENDER_PROGRAM_STATUS FROM   OFFENDER_PROGRAM_PROFILES ,OFFENDER_PRG_OBLIGATIONS WHERE OFFENDER_PROGRAM_PROFILES.OFFENDER_PRG_OBLIGATION_ID = OFFENDER_PRG_OBLIGATIONS .OFFENDER_PRG_OBLIGATION_ID
}

OCUUPSTA_CHECK_CHILD_UPDATE_ {
	SELECT OP.* FROM   OFFENDER_PROGRAM_PROFILES OP , OFFENDER_PRG_OBLIGATIONS OO WHERE  OP.OFFENDER_PRG_OBLIGATION_ID = OO.OFFENDER_PRG_OBLIGATION_ID ORDER BY OP.CRS_ACTY_ID
}
OCUUPSTA_GET_DESCRIPTION{
SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE=:CODE AND DOMAIN = 'PS_PRG_OBSTS'
}
OCUUPSTA_GET_STATUS_DESCRIPTION{
SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE=:CODE AND DOMAIN='PS_PRG_STAT'
}
OCUUPSTA_GET_REFFERAL_DATE {
SELECT REFERRAL_DATE 
 	    FROM OFFENDER_PRG_OBLIGATIONS
 	    WHERE OFFENDER_PRG_OBLIGATION_ID = :OFFENDER_PRG_OBLIGATION_ID
}
OCUUPSTA_GET_MAX_DATE {
SELECT MAX (STATUS_CHANGE_DATE)
        FROM OFFENDER_PRG_OBLIGATION_HTY
       WHERE OFFENDER_PRG_OBLIGATION_ID = :OFFENDER_PRG_OBLIGATION_ID
}
OCUUPSTA_UPDATE_STATUS_BTN{
  SELECT UPDATE_FLAG  FROM MAINTAIN_SPECIALIZED_PRG_STS where DESCRIPTION = :code
}

OCUUPSTA_ADMINISTRATER_USER{
SELECT ROLE_ID FROM STAFF_MEMBER_ROLES WHERE STAFF_ID IN (SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID=:user) AND STAFF_MEMBER_ROLES.ROLE_CODE =:roleCode
}

OCUUPSTA_SYSPFL_FIND_SYSTEM_PROFILES{
SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 profileValue2,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES where PROFILE_CODE = 'PRG_ADM_USER'
}

OCUUPSTA_REASON_FOR_SUSPENDING_OR_ENDING_PROGRAM_DISABLE{
SELECT UPDATE_REASON_FLAG  FROM MAINTAIN_SPECIALIZED_PRG_STS  WHERE CODE = :code
}

OCUUPSTA_GET_ROLE_ID_LIST_USER {
SELECT
to_char(B.ROLE_ID) role_Id
FROM
STAFF_MEMBERS A, STAFF_MEMBER_ROLES B
WHERE
A.STAFF_ID=B.STAFF_ID AND
A.USER_ID= :userName
}