OIUVLCTE_CALL_OCISCATA {
	SELECT CRS_ACTY_ID,PROGRAM_ID,SERVICES_ADDRESS_ID,INTERNAL_LOCATION_ID FROM COURSE_ACTIVITIES WHERE  CRS_ACTY_ID = :CRSACTYID
}
OIUVLCET_VADDRESS{ 
	SELECT ADDRESS_ID ,ADDRESS_TYPE ,ADDRESS_TYPE_DESC  ,HOUSE ,STREET ,AREA ,COUNTRY ,SUITE_NUMBER ,STREET_NUMBER ,STREET_DIRECTION ,STREET_DIRECTION_DESC ,STREET_INFORMATION ,CITY_CODE ,CITY_NAME ,PROV_STATE_CODE ,PROV_STATE_DESC ,ZIP_POSTAL_CODE ,COUNTRY_CODE ,COUNTRY_DESC FROM V_ADDRESSES where ADDRESS_ID=:addressId 
}

OIUVLCET_FACILITY_DET {
	SELECT DESCRIPTION FROM AGENCY_INTERNAL_LOCATIONS WHERE INTERNAL_LOCATION_ID = :P_INTERNAL_LOCATION_ID
}