GET_NEXT_SANCTION_SEQ{
SELECT coalesce ( MAX ( SANCTION_SEQ ), 0 ) + 1 FROM OFFENDER_OIC_SANCTIONS WHERE OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID
}

GET_ADJUDICATION_FROM_SANCTION{
SELECT OH.OIC_INCIDENT_ID FROM OFFENDER_OIC_SANCTIONS OOS, OIC_HEARINGS OH WHERE OOS.OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID AND OOS.SANCTION_SEQ = :P_SANCTION_SEQ AND OOS.OIC_HEARING_ID = OH.OIC_HEARING_ID
}

GET_NEXT_AGENCY_INCIDENT_ID{
  SELECT NEXTVAL ('AGENCY_INCIDENT_ID') 
}
GET_NEXT_PARTY_SEQ{
SELECT coalesce ( MAX ( AIP.PARTY_SEQ ), 0 ) + 1 PARTY_SEQ FROM AGENCY_INCIDENT_PARTIES AIP WHERE AIP.AGENCY_INCIDENT_ID = :P_AGENCY_INCIDENT_ID
}
GET_NEXT_CHARGE_SEQ{
SELECT COALESCE ( MAX ( CHARGE_SEQ ), 0 ) + 1
           FROM AGENCY_INCIDENT_CHARGES
          WHERE AGENCY_INCIDENT_ID =:P_AGENCY_INCIDENT_ID
}
GET_NEXT_REPAIR_SEQ{
SELECT COALESCE ( MAX ( air.repair_seq ), 0 ) + 1
           FROM agency_incident_repairs air
          WHERE air.agency_incident_id = :P_AGENCY_INCIDENT_ID
          }
          
          
TAG_ADJUDICATION_GET_OFFENCE_DETAILS{
   SELECT OMS_MISCELLANEOUS_GETDESCCODE ( 'OIC_OFN_TYPE',OIC_OFFENCE_TYPE ) as OFFENCE_TYPE_DESC,     DESCRIPTION, OIC_OFFENCE_CODE FROM OIC_OFFENCES WHERE OIC_OFFENCE_ID = :P_OFFENCE_ID
}

TAG_ADJUDICATION_GET_HEARING_TYPE{
 select  tag_adjudication_gethearingtype(:p_hearing_id) 
}