
OCDVTEAM_FIND_RGFUNCTION {
 	SELECT REF_CODE.DESCRIPTION  DESCRIPTION, REF_CODE.CODE  CODE,LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'FUNCTION'  AND (ACTIVE_FLAG = 'Y') ORDER BY LIST_SEQ ,DESCRIPTION ,CODE
}

OCDVTEAM_OFFTEAMASSIGN_FIND_OFFENDER_TEAM_ASSIGNMENTS {
 	SELECT OFFENDER_BOOK_ID ,FUNCTION_TYPE ,TEAM_ID ,ASSIGNMENT_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_TEAM_ASSIGNMENTS  where offender_book_id=:offenderBookId order by oms_miscellaneous_getdesccode ('FUNCTION',OFFENDER_TEAM_ASSIGNMENTS.function_type)
}
OCDVTEAM_OFFTEAMASSIGN_INSERT_OFFENDER_TEAM_ASSIGNMENTS {
	INSERT INTO OFFENDER_TEAM_ASSIGNMENTS(OFFENDER_BOOK_ID ,FUNCTION_TYPE ,TEAM_ID ,ASSIGNMENT_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ) VALUES(:offenderBookId ,:functionType ,:teamId ,:assignmentDate ,CURRENT_TIMESTAMP ,:createUserId ,null ,null ,:sealFlag )
}

OCDVTEAM_OFFENDER_TEAM_ASSIGNMENTS_HISTORY {
	INSERT INTO offender_team_assign_hty(OFFENDER_BOOK_ID ,FUNCTION_TYPE ,TEAM_ID ,ASSIGNMENT_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ) VALUES(:offenderBookId ,:functionType ,:teamId ,:assignmentDate ,CURRENT_TIMESTAMP ,:createUserId ,CURRENT_TIMESTAMP,:modifyUserId ,:sealFlag )
}

OCDVTEAM_OFFTEAMASSIGN_UPDATE_OFFENDER_TEAM_ASSIGNMENTS {
	UPDATE OFFENDER_TEAM_ASSIGNMENTS set OFFENDER_BOOK_ID  = :offenderBookId ,FUNCTION_TYPE  = :functionType ,TEAM_ID  = :teamId ,ASSIGNMENT_DATE  = :assignmentDate ,MODIFY_DATETIME  =CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag /* where */
}
S

OCDVTEAM_OFF_BKG_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM OFFENDER_TEAM_ASSIGNMENTS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}
OCDVTEAM_GET_TEAM_DESCRIPTION{
select TEAM_CODE,DESCRIPTION from automation_teams where  TEAM_ID=:teamId
}
OIMVDTSL_CONSTRAINT_VALIDATIONS_TIMES{
SELECT AC1.TABLE_NAME FROM ALL_CONSTRAINTS AC1, ALL_CONSTRAINTS AC2 WHERE AC1.CONSTRAINT_NAME = :CONSTRAINTNAME AND AC2.TABLE_NAME = 'OFFENDER_TEAM_ASSIGNMENTS' AND AC1.CONSTRAINT_TYPE = 'R' AND AC2.CONSTRAINT_NAME = AC1.R_CONSTRAINT_NAME AND AC2.OWNER = AC1.R_OWNER AND AC2.CONSTRAINT_TYPE IN ('P', 'U')
}
