
OCITTASK_FIND_RGSTAFF {
SELECT DISTINCT st.last_name || ', ' || st.first_name officer_name, st.staff_id code, st.staff_id FROM staff_members st, team_staff_members tm WHERE st.staff_id = tm.staff_id AND tm.team_id = :teamid ORDER BY officer_name
}
OCITTASK_FIND_RGCOMPLETESTATUS {
 	SELECT  DESCRIPTION , CODE FROM REFERENCE_CODES WHERE DOMAIN = 'COMPLETE_STS' ORDER BY LIST_SEQ
}

OCITTASK_FIND_RGTASKSUBTYPE {
 	SELECT DESCRIPTION ,CODE FROM   REFERENCE_CODES WHERE   DOMAIN = 'TASK_SUBTYPE' AND PARENT_CODE = :taskType ORDER BY DESCRIPTION
}
OCITTASK_FIND_TEAMID {
 	SELECT DISTINCT
    t.team_id
FROM
    automation_teams           t,
    team_staff_members    tm,
    staff_members   sm
WHERE
    tm.team_id = t.team_id
    AND tm.staff_id = sm.staff_id
    AND sm.user_id = :createUserId
    AND tm.active_flag = 'Y'
    AND t.team_code = :TEAMCODE
 	
 	}
OCITTASK_FIND_RGTASKTYPE {
 	SELECT DISTINCT REFS.DESCRIPTION DESCRIPTION , WS.WORK_TYPE CODE FROM WORKS WS , REFERENCE_CODES REFS WHERE WS.WORKFLOW_TYPE = 'TASK' AND WS.WORK_TYPE = REFS.CODE AND REFS.DOMAIN = 'TASK_TYPE' ORDER BY DESCRIPTION
}

OCITTASK_FIND_RGTEAM {
 	SELECT DISTINCT
    t.team_code code,
    t.description
FROM
    automation_teams           t,
    team_staff_members    tm,
    staff_members   sm
WHERE
    tm.team_id = t.team_id
    AND tm.staff_id = sm.staff_id
    AND sm.user_id = :createUserId
    AND tm.active_flag = 'Y'
 	
 	}
OCITTASK_FIND_OFFENDER_BOOKID {
 	SELECT O.LAST_NAME, O.FIRST_NAME, OB.OFFENDER_BOOK_ID ,OB.ACTIVE_FLAG,OB.COMMUNITY_ACTIVE_FLAG,O.OFFENDER_ID_DISPLAY FROM OFFENDERS O, OFFENDER_BOOKINGS OB WHERE OB.ROOT_OFFENDER_ID = O.ROOT_OFFENDER_ID AND OB.OFFENDER_ID = O.OFFENDER_ID AND ((OB.ACTIVE_FLAG = 'Y' AND EXISTS (SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :caseloadId AND AGY_LOC_ID = OB.AGY_LOC_ID)) OR (OB.COMMUNITY_ACTIVE_FLAG = 'Y' AND EXISTS (SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :caseloadId AND AGY_LOC_ID = OB.COMMUNITY_AGY_LOC_ID)) ) AND LTRIM(O.OFFENDER_ID_DISPLAY::text,'0') like  LTRIM(:offenderIdDisplay::text,'0')
}
OCITTASK_TASKS_INSERT_TAG_WORKFLOW_ADM.QUERY_TEAM_TASKS {
	INSERT INTO TAG_WORKFLOW_ADM.QUERY_TEAM_TASKS() VALUES(:)
}

OCITTASK_TASKS_UPDATE_TAG_WORKFLOW_ADM.QUERY_TEAM_TASKS {
	UPDATE TAG_WORKFLOW_ADM.QUERY_TEAM_TASKS set /* where */
}

OCITTASK_TASKS_DELETE_TAG_WORKFLOW_ADM.QUERY_TEAM_TASKS { 
	DELETE FROM TAG_WORKFLOW_ADM.QUERY_TEAM_TASKS/* where */
}

OCITTASK_FIND_RGTASKTYPE_DESCRIPTION {
 	SELECT DISTINCT REFS.DESCRIPTION DESCRIPTION FROM WORKS WS , REFERENCE_CODES REFS WHERE WS.WORKFLOW_TYPE = 'TASK' AND WS.WORK_TYPE = REFS.CODE AND REFS.DOMAIN = 'TASK_TYPE' AND WS.WORK_TYPE = :workType ORDER BY DESCRIPTION
}
