
OCUHVTEA_FIND_RGFUNCTION {
 	SELECT DESCRIPTION,CODE,LIST_SEQ FROM REFERENCE_CODES WHERE DOMAIN = 'FUNCTION' AND (ACTIVE_FLAG = 'Y') ORDER BY LIST_SEQ ,DESCRIPTION ,CODE
}

OCUHVTEA_OFFVTEAMHTY_FIND_V_OFFENDER_TEAM_ASSIGN_HTY {
 	 SELECT OFFENDER_BOOK_ID ,FUNCTION_TYPE ,FUNCTION_TYPE_DESC ,TEAM_ID ,TEAM_CODE ,TEAM_DESCRIPTION ,EXPIRY_DATE ,ASSIGN_DATE ,OFFENDER_TEAM_ASSIGN_HTY_ID   FROM V_OFFENDER_TEAM_ASSIGN_HTY  
}

OCUHVTEA_OFF_BKG_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM V_OFFENDER_TEAM_ASSIGN_HTY V WHERE V.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}
