GET_L_DAYS{
   /*   SELECT DAYS
	  FROM WORK_TRIGGERS
	  WHERE TRIGGER_NAME = :P_TRIGGER_NAME
	  AND DAYS IS NOT NULL
	  AND ROWNUM < 2
	  ORDER BY CREATE_DATETIME  */
select
	DAYS
from
	WORK_TRIGGERS
where
	TRIGGER_NAME = :P_TRIGGER_NAME
	and DAYS is not null
order by
	CREATE_DATETIME
limit 1


}


GET_COUNT_IWP_DOCS_CUR{
  SELECT COUNT(*)
            FROM IWP_DOCUMENTS
            WHERE TEMPLATE_ID = :P_TEMPLATE_ID
 }
 GET_COUNT_OFF_CASENOTE_CUR{
	SELECT COUNT(*)
			FROM OFFENDER_CASE_NOTES
			WHERE CASE_NOTE_TYPE = :P_CASE_NOTE_TYPE
			AND CASE_NOTE_SUB_TYPE = :P_CASE_NOTE_SUB_TYPE
}			