OCMPFACC_GET_FEE_ACCOUNTS {
SELECT
    fa.*,
    (
        SELECT
            account_name
        FROM
            account_codes
        WHERE
            sub_account_type IS NOT NULL
            AND account_code = fa.account_code
    ) AS account_code_desc,
    (SELECT DEDUCTION_DESC   FROM DEDUCTION_TYPES WHERE DEDUCTION_CATEGORY = 'FEE' and DEDUCTION_TYPE = fa.fee_code) as fee_Code_Desc
    FROM
    fee_accounts fa
ORDER BY
    list_seq
}

OCMPFACC_INSERT_FEE_ACCOUNTS {
insert
	into
	FEE_ACCOUNTS(ACCOUNT_CODE,
	FEE_CODE,
	LIST_SEQ,
	RECORD_DATETIME,
	EXPIRY_DATETIME,
	CREATE_USER_ID,
	MODIFY_DATETIME,
	MODIFY_USER_ID,
	SEAL_FLAG)
values(:accountCode,
:feeCode,
:listSeq,
:recordDatetime,
:expiryDatetime,
:createUserId,
null,
null,
:sealFlag);

}

OCMPFACC_UPDATE_FEE_ACCOUNTS {
UPDATE FEE_ACCOUNTS SET EXPIRY_DATETIME = :expiryDatetime, LIST_SEQ= :listSeq WHERE ACCOUNT_CODE=:accountCode AND FEE_CODE=:feeCode
}
OCMPFACC_PRE_INSERT{
SELECT COUNT(*) FROM FEE_ACCOUNTS WHERE ACCOUNT_CODE=:accountCode AND FEE_CODE=:feeCode
}

OCMPFACC_GET_ACCOUNT_CODES {
SELECT to_char(ACCOUNT_CODE) CODE , to_char(ACCOUNT_CODE) DESCRIPTION ,ACCOUNT_NAME , SUB_ACCOUNT_TYPE FROM ACCOUNT_CODES WHERE SUB_ACCOUNT_TYPE IS NOT NULL
}

OCMPFACC_GET_FEE_CODES {
SELECT DEDUCTION_TYPE CODE, DEDUCTION_TYPE DESCRIPTION,DEDUCTION_DESC   FROM DEDUCTION_TYPES WHERE DEDUCTION_CATEGORY = 'FEE'

}
OCMPFACC_PRE_INSERT_LISTSEQ{
SELECT COUNT(*) FROM FEE_ACCOUNTS WHERE list_seq = :listSeq
}
OCMPFACC_PRE_UPDATE_LISTSEQ{
SELECT COUNT(*) FROM FEE_ACCOUNTS WHERE list_seq = :listSeq and ACCOUNT_CODE !=:ACCOUNT_CODE and FEE_CODE != :FEE_CODE
}
