
OIMISSUE_GRIEVANCETYPES_FIND_GRIEVANCE_TYPES {
 	SELECT MODIFY_USER_ID,MODIFIED_USER_ID,CREATE_USER_ID,DESCRIPTION,GRIEV_TYPE,ACTIVE_FLAG,SEAL_FLAG,STAFF_INVOLVED_FLAG,MODIFY_DATETIME,CREATE_DATETIME,LIST_SEQ,EXPIRY_DATE,MODIFIED_DATETIME  FROM GRIEVANCE_TYPES
}
OIMISSUE_GRIEVANCETYPES_INSERT_GRIEVANCE_TYPES {
insert into GRIEVANCE_TYPES( MODIFIED_USER_ID, CREATE_USER_ID, DESCRIPTION, GRIEV_TYPE, ACTIVE_FLAG, SEAL_FLAG, STAFF_INVOLVED_FLAG, MODIFY_DATETIME, CREATE_DATETIME, LIST_SEQ, EXPIRY_DATE, MODIFIED_DATETIME) values( :modifiedUserId, :createUserId, :description, :grievType, :activeFlag, :sealFlag, :staffInvolvedFlag, null , CURRENT_TIMESTAMP, :listSeq, :expiryDate, CURRENT_TIMESTAMP)
}
OIMISSUE_GRIEVANCETYPES_UPDATE_GRIEVANCE_TYPES {
update GRIEVANCE_TYPES set MODIFY_USER_ID = :modifyUserId, MODIFIED_USER_ID = :modifyUserId, DESCRIPTION =:description, GRIEV_TYPE =:grievType, ACTIVE_FLAG =:activeFlag, SEAL_FLAG =:sealFlag, STAFF_INVOLVED_FLAG =:staffInvolvedFlag, MODIFY_DATETIME = CURRENT_TIMESTAMP, LIST_SEQ =:listSeq, EXPIRY_DATE =:expiryDate, MODIFIED_DATETIME = CURRENT_TIMESTAMP where GRIEV_TYPE =:grievType
}

OIMISSUE_GRIEVANCEREASONS_FIND_GRIEVANCE_REASONS {
 	SELECT MODIFY_USER_ID,MODIFIED_USER_ID,CREATE_USER_ID,DESCRIPTION,GRIEV_TYPE,ACTIVE_FLAG,ACTIVE_FLAG CHECKFLAG,SEAL_FLAG,GRIEV_REASON_CODE,MODIFY_DATETIME,CREATE_DATETIME,LIST_SEQ,EXPIRY_DATE,MODIFIED_DATETIME  FROM GRIEVANCE_REASONS  where GRIEV_TYPE=:grievType order by LIST_SEQ 
}
OIMISSUE_GRIEVANCEREASONS_INSERT_GRIEVANCE_REASONS {
insert into GRIEVANCE_REASONS( MODIFIED_USER_ID, CREATE_USER_ID, DESCRIPTION, GRIEV_TYPE, ACTIVE_FLAG, SEAL_FLAG, GRIEV_REASON_CODE, MODIFY_DATETIME, CREATE_DATETIME, LIST_SEQ, EXPIRY_DATE, MODIFIED_DATETIME) values( :modifiedUserId, :createUserId, :description, :grievType, :activeFlag, :sealFlag, :grievReasonCode, null , CURRENT_TIMESTAMP, :listSeq, :expiryDate, CURRENT_TIMESTAMP)
}

OIMISSUE_GRIEVANCEREASONS_UPDATE_GRIEVANCE_REASONS {
	 update GRIEVANCE_REASONS set MODIFY_USER_ID = :modifyUserId, MODIFIED_USER_ID = :modifyUserId, DESCRIPTION =:description, GRIEV_TYPE =:grievType, ACTIVE_FLAG =:activeFlag, SEAL_FLAG =:sealFlag, GRIEV_REASON_CODE =:grievReasonCode, MODIFY_DATETIME = CURRENT_TIMESTAMP, LIST_SEQ =:listSeq, EXPIRY_DATE =:expiryDate, MODIFIED_DATETIME = CURRENT_TIMESTAMP where GRIEV_TYPE =:grievType and GRIEV_REASON_CODE =:grievReasonCode
}

OIMISSUE_GRIEVANCEREASONS_DELETE_GRIEVANCE_REASONS { 
	DELETE FROM GRIEVANCE_REASONS where GRIEV_TYPE=:grievType AND GRIEV_REASON_CODE=:grievReasonCode
}
OIMISSUE_GRIEVANCETXNS_FIND_GRIEVANCE_TXNS {
 	SELECT GRIEV_TYPE, TXN_TYPE, DESCRIPTION, DAYS_RESPOND, DOC_RSP_FLAG,DOC_RSP_FLAG AGYFLAG, OFF_RSP_FLAG, OFF_RSP_FLAG OFFFLAG, IG_RSP_FLAG,IG_RSP_FLAG SUPFLAG, ACTIVE_FLAG,ACTIVE_FLAG CHECKFLAG, EXPIRY_DATE, LIST_SEQ, MODIFY_USER_ID, MODIFY_DATETIME, CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG  FROM GRIEVANCE_TXNS   where  GRIEV_TYPE=:grievType order by LIST_SEQ
}
OIMISSUE_GRIEVANCETXNS_INSERT_GRIEVANCE_TXNS {
insert into GRIEVANCE_TXNS(GRIEV_TYPE, TXN_TYPE, DESCRIPTION, DAYS_RESPOND, DOC_RSP_FLAG, OFF_RSP_FLAG, IG_RSP_FLAG, ACTIVE_FLAG, EXPIRY_DATE, LIST_SEQ, MODIFY_USER_ID, MODIFY_DATETIME, CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG) values(:grievType, :txnType, :description, :daysRespond, :docRspFlag, :offRspFlag, :igRspFlag, :activeFlag, :expiryDate, :listSeq, null , null , CURRENT_TIMESTAMP, :createUserId, :sealFlag)
}

OIMISSUE_GRIEVANCETXNS_UPDATE_GRIEVANCE_TXNS {
 update GRIEVANCE_TXNS set GRIEV_TYPE =:grievType, TXN_TYPE =:txnType, DESCRIPTION =:description, DAYS_RESPOND =:daysRespond, DOC_RSP_FLAG =:docRspFlag, OFF_RSP_FLAG =:offRspFlag, IG_RSP_FLAG =:igRspFlag, ACTIVE_FLAG =:activeFlag, EXPIRY_DATE =:expiryDate, LIST_SEQ =:listSeq, MODIFY_USER_ID = :modifyUserId, MODIFY_DATETIME = CURRENT_TIMESTAMP, SEAL_FLAG =:sealFlag where GRIEV_TYPE =:grievType and TXN_TYPE =:txnType
}

OIMISSUE_GRIEVANCETXNS_DELETE_GRIEVANCE_TXNS { 
	DELETE FROM GRIEVANCE_TXNS where GRIEV_TYPE=:grievType AND TXN_TYPE=:txnType
}


OIMISSUE_GRIEVANCE_TYPES_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM GRIEVANCE_REASONS G WHERE G.GRIEV_TYPE = :GRIEVTYPE
}

OIMISSUE_GRIEVANCE_TYPES_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM GRIEVANCE_TXNS G WHERE G.GRIEV_TYPE = :GRIEVTYPE
}

OIMISSUE_GRIEVANCE_TXNS_KEYDELREC {
	SELECT count(*) FROM OMS_OWNER.OFFENDER_GRIEVANCE_TXNS where GRIEV_TYPE=:grievType AND TXN_TYPE=:txnType
}
OIMISSUE_GRIEVANCE_REASONS_KEYDELREC {
	SELECT count(*) FROM OMS_OWNER.OFFENDER_GRIEVANCES where GRIEV_TYPE=:grievType AND GRIEV_REASON_CODE=:grievReasonCode
}

OIMISSUE_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
