update json_spec set modify_user_id = 'OMS_OWNER' ,
          modify_datetime = current_timestamp ,
		  json_specs = '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.activePrisonerDetails[#2].imprisonmentDetails.dcsId", "first_name": "body.activePrisonerDetails[#2].demographics.firstName", "middle_name": "body.activePrisonerDetails[#2].demographics.middleName", "last_name": "body.activePrisonerDetails[#2].demographics.surName", "sex_code": "body.activePrisonerDetails[#2].demographics.gender", "birth_date": "body.activePrisonerDetails[#2].demographics.dob" } }, "offenderBookingDetails": { "*": { "booking_no": "body.activePrisonerDetails[#2].imprisonmentDetails.pin", "booking_begin_date": "body.activePrisonerDetails[#2].imprisonmentDetails.intakeDatetime", "booking_status": "body.activePrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.activePrisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.activePrisonerDetails[#2].housing.unit" } }, "offenderReleaseDetails": { "*": { "movement_date": "body.activePrisonerDetails[#2].imprisonmentDetails.releaseDateTime" } } } }, { "operation": "default", "spec": { "header": { "intId": "CurrentPrisoners" } } } ]' where spec_key = 'ACTIVE_PRISONER_FORMATTER';

update json_spec set modify_user_id = 'OMS_OWNER' ,
          modify_datetime = current_timestamp ,
		  json_specs = '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.escapedPrisonerDetails[#2].imprisonmentDetails.dcsId", "first_name": "body.escapedPrisonerDetails[#2].demographics.firstName", "middle_name": "body.escapedPrisonerDetails[#2].demographics.middleName", "last_name": "body.escapedPrisonerDetails[#2].demographics.surName", "sex_code": "body.escapedPrisonerDetails[#2].demographics.gender", "birth_date": "body.escapedPrisonerDetails[#2].demographics.dob" } }, "offenderBookingDetails": { "*": { "booking_no": "body.escapedPrisonerDetails[#2].imprisonmentDetails.pin", "booking_begin_date": "body.escapedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime", "booking_status": "body.escapedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.escapedPrisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.escapedPrisonerDetails[#2].housing.unit" } }, "offenderReleaseDetails": { "*": { "movement_date": "body.escapedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime" } } } }, { "operation": "default", "spec": { "header": { "intId": "CurrentPrisoners" } } } ]' where spec_key = 'ESCAPED_PRISONER_FORMATTER';

update json_spec set modify_user_id = 'OMS_OWNER' ,
          modify_datetime = current_timestamp ,
		  json_specs = '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.releasedPrisonerDetails[#2].imprisonmentDetails.dcsId", "first_name": "body.releasedPrisonerDetails[#2].demographics.firstName", "middle_name": "body.releasedPrisonerDetails[#2].demographics.middleName", "last_name": "body.releasedPrisonerDetails[#2].demographics.surName", "sex_code": "body.releasedPrisonerDetails[#2].demographics.gender", "birth_date": "body.releasedPrisonerDetails[#2].demographics.dob" } }, "offenderBookingDetails": { "*": { "booking_no": "body.releasedPrisonerDetails[#2].imprisonmentDetails.pin", "booking_begin_date": "body.releasedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime", "booking_status": "body.releasedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.releasedPrisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.releasedPrisonerDetails[#2].housing.unit" } }, "offenderReleaseDetails": { "*": { "movement_date": "body.releasedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime" } } } }, { "operation": "default", "spec": { "header": { "intId": "CurrentPrisoners" } } }]' where spec_key = 'RELEASED_PRISONER_FORMATTER';

update json_spec set modify_user_id = 'OMS_OWNER' ,
          modify_datetime = current_timestamp ,
		  json_specs = '[{ "operation": "shift", "spec": { "staffDetails": { "*": { "user_id": "header.intUser.intUserId", "first_name": "header.intUser.intUserName", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.prisonerDetails[#2].imprisonmentDetails.pin" } }, "offenderBookingDetails": { "*": { "booking_no": "body.prisonerDetails[#2].imprisonmentDetails.offenderNumber", "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.prisonerDetails[#2].housing.pod", "housing_lev_2_code": "body.prisonerDetails[#2].housing.unit", "housing_lev_3_code": "body.prisonerDetails[#2].housing.cell" } } } }, { "operation": "default", "spec": { "header": { "intId": "Unilink-LOCA" } } } ]' where spec_key = 'PRISONER_MOVEMENTS_FORMATTER';

update json_spec set modify_user_id = 'OMS_OWNER' ,
          modify_datetime = current_timestamp ,
		  json_specs = '[{ "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "first_name": "body.prisonerDetails[#2].demographics.firstName", "last_name": "body.prisonerDetails[#2].demographics.surName" } }, "offenderBookingDetails": { "*": { "booking_no": "body.prisonerDetails[#2].imprisonmentDetails.offenderNumber", "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } } } }, { "operation": "default", "spec": { "header": { "intId": "LearningSystem" } } } ]' where spec_key = 'LEARNING_SYSTEM_FORMATTER';

update json_spec set modify_user_id = 'OMS_OWNER' ,
          modify_datetime = current_timestamp ,
		  json_specs = '[{ "operation": "shift", "spec": { "staffDetails": { "*": { "user_id": "header.intUser.intUserId", "first_name": "header.intUser.intUserName", "date_time": "header.intDatetime" } }, "seriousOffenders": { "*": { "booking_no": "body.prisonerDetails[#2].imprisonmentDetails.pin", "offender_id_display": "body.prisonerDetails[#2].imprisonmentDetails.dcsId", "first_name": "body.prisonerDetails[#2].demographics.firstName", "middle_name": "body.prisonerDetails[#2].demographics.middleName", "last_name": "body.prisonerDetails[#2].demographics.surName", "birth_date": "body.prisonerDetails[#2].demographics.dob" } } } }, { "operation": "default", "spec": { "header": { "intId": "SeriousOffenders" } } } ]' where spec_key = 'SERIOUS_OFFENDER_FORMATTER';