OCUFOVDT_OVERRIDE_TYPE_RG {
	SELECT REF_CODE.CODE  CODE       ,REF_CODE.DESCRIPTION  DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'CF_FOV_TYP'  AND ACTIVE_FLAG = 'Y'  AND EXPIRED_DATE  IS NULL ORDER BY REF_CODE.LIST_SEQ ,REF_CODE.CODE ,REF_CODE.DESCRIPTION
}

OCUFOVDT_FIND_FEE_OVERRIDE_DET {
	SELECT * FROM OFF_FEE_ACCOUNT_OVERRIDES where OFFENDER_FEE_ID = :offenderFeeId
}

OCUFOVDT_INSERT_OFF_FEE_ACCOUNT_OVERRIDES {
	insert into OFF_FEE_ACCOUNT_OVERRIDES(ADDED_BY_STAFF_ID,
ADDED_DATE,
COMMENT_TEXT,
OFFENDER_FEE_ID,
OFF_FEE_OVERRIDE_ID,
OVERRIDE_AMOUNT,
OVERRIDE_END_DATE,
OVERRIDE_START_DATE,
OVERRIDE_TYPE,
PRIORITY_INDICATOR,
CREATE_DATETIME,
CREATE_USER_ID,
SEAL_FLAG) values(:addedByStaffId,:addedDate,:commentText,:offenderFeeId,:offFeeOverrideId,:overrideAmount,:overrideEndDate,:overrideStartDate,:overrideType,:priorityIndicator,current_timestamp,:createUserId,:sealFlag)
}

OCUFOVDT_UPDATE_OFF_FEE_ACCOUNT_OVERRIDES {
	UPDATE OFF_FEE_ACCOUNT_OVERRIDES SET ADDED_BY_STAFF_ID=:addedByStaffId,
ADDED_DATE=:addedDate,
COMMENT_TEXT=:commentText,
OVERRIDE_AMOUNT=:overrideAmount,
OVERRIDE_END_DATE=:overrideEndDate,
OVERRIDE_START_DATE=:overrideStartDate,
OVERRIDE_TYPE=:overrideType,
PRIORITY_INDICATOR=:priorityIndicator,
SEAL_FLAG=:sealFlag, 
MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId where OFF_FEE_OVERRIDE_ID=:offFeeOverrideId
}

OCUFOVDT_DELETE_OFF_FEE_ACCOUNT_OVERRIDES {
	DELETE FROM OFF_FEE_ACCOUNT_OVERRIDES  where OFF_FEE_OVERRIDE_ID=:offFeeOverrideId
}
OCUFOVDT_GET_DEDUCTION_DESC {
    select DEDUCTION_DESC from DEDUCTION_TYPES where deduction_type = :deductionType
}

OCUFOVDT_GET_FREQUENCY {
    select description from reference_codes where code = :code and  domain = 'RECUR_FREQ'
}

OCUFOVDT_GET_LOCATION {
    SELECT description FROM CASELOADS where CASELOAD_ID = :location
}
OCUFOVDT_USERNAME {
    select last_name || ', ' || first_name from staff_members where user_id = USER
}


OCUFOVDT_SYSPFL_FIND_SYSTEM_PROFILES {
SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES where PROFILE_CODE = 'CF_FEE_OVRD'
}
OCUFOVDT_GET_ROLE_ID_LIST_USER {
SELECT
to_char(B.ROLE_ID) role_Id
FROM
STAFF_MEMBERS A, STAFF_MEMBER_ROLES B
WHERE
A.STAFF_ID=B.STAFF_ID AND
A.USER_ID=:userName
}

OCUFOVDT_FEEOVERRIDE_DETAILS_PREINSERT{
	SELECT  NEXTVAL('OFF_FEE_OVERRIDE_ID') FROM  DUAL
}

OCUFOVDT_GET_ADDED_BY_NAME {
select last_name || ', ' || first_name as FULL_NAME
from staff_members
where
  user_id=user
  }
OCUFOVDT_FIND_FEE_OVERRIDE_DET_COUNTY_START_DATE {
select * from OFF_FEE_ACCOUNT_OVERRIDES where OFFENDER_FEE_ID=:offenderFeeId AND OVERRIDE_TYPE=:overrideType
}

OCUFOVDT_GET_ADDED_BY_STAFF_ID {
select staff_id from staff_members where user_Id=:userId
}

OCUFOVDT_GET_USER_ID{
SELECT last_name || ', ' || first_name as FULL_NAME FROM STAFF_MEMBERS WHERE STAFF_ID = :staffId
}