APIMAIN_EXECUTE_QUERY {
	SELECT A.API_ID, A.API_DESCRIPTION, A.QUERY_KEY, A.REQUEST_TYPE, URL, A.CREATE_DATETIME, A.CREATE_USER_ID,aaq.category ,A.MODIFY_DATETIME, A.MODIFY_USER_ID, A.ROW_ID
FROM ACTION_API A,automation_api_query aaq where A.query_key =aaq.query_key ORDER BY MODIFY_DATETIME DESC
}

APIMAIN_INSERT_ACTION_API {
	INSERT INTO ACTION_API(API_ID, API_DESCRIPTION, QUERY_KEY, REQUEST_TYPE, URL, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID) VALUES(:apiId, :apiDescription, :queryKey, :requestType, :url, :createDatetime, :createUserId, null, null)
}

APIMAIN_UPDATE_ACTION_API {
	UPDATE ACTION_API SET API_ID = :apiId, API_DESCRIPTION = :apiDescription, QUERY_KEY = :queryKey, REQUEST_TYPE = :requestType, URL = :url, MODIFY_DATETIME = :modifyDatetime, MODIFY_USER_ID = :modifyUserId WHERE QUERY_KEY = :queryKey
}

APIMAIN_DELETE_ACTION_API {
	DELETE FROM ACTION_API WHERE API_ID = :apiId
}

APIMAIN_FIND_QUERY_KEY {
	SELECT QUERY_KEY CODE, QUERY_DESC DESCRIPTION FROM AUTOMATION_API_QUERY
}
APIMAIN_GET_QUICK_ACTIONS {
SELECT 
  AP.API_ID, API_DESCRIPTION, AP.QUERY_KEY, REQUEST_TYPE, URL, APQ.QUERY_ID, 
  QUERY_TEXT, QUERY_DESC, ACTIVE_FLAG, VERIFIED_BY, VERIFIED_DATE
FROM 
  ACTION_API AP, AUTOMATION_API_QUERY APQ
WHERE
  AP.QUERY_KEY=APQ.QUERY_KEY 
}