
OUMBADMI_FIND_CGFKOFFCONTACTSBOOKINGSTAT {
 	SELECT REF_CODE.CODE ,REF_CODE.DESCRIPTION    FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'BOOK_STS'  AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' )
}

OUMBADMI_VBOOKADM_FIND_V_BOOK_ADMIN {
 	SELECT FIRST_NAME,LAST_NAME,ROOT_OFFENDER_ID, OFFENDER_ID, OFFENDER_ID_DISPLAY, BIRTH_DATE, SUFFIX ,MIDDLE_NAME,SEAL_FLAG FROM V_BOOK_ADMIN 
}
OUMBADMI_OFFCONTACTS_FIND_OFFENDER_BOOKINGS {
 	select
	OFFENDER_BOOK_ID,
	BOOKING_BEGIN_DATE,
	BOOKING_END_DATE,
	BOOKING_NO,
	OFFENDER_ID,
	AGY_LOC_ID,
	LIVING_UNIT_ID,
	DISCLOSURE_FLAG,
	IN_OUT_STATUS,
	ACTIVE_FLAG,
	BOOKING_STATUS,
	YOUTH_ADULT_CODE,
	FINGER_PRINTED_STAFF_ID,
	SEARCH_STAFF_ID,
	PHOTO_TAKING_STAFF_ID,
	ASSIGNED_STAFF_ID,
	CREATE_AGY_LOC_ID,
	BOOKING_TYPE,
	BOOKING_CREATED_DATE,
	ROOT_OFFENDER_ID,
	AGENCY_IML_ID,
	SERVICE_FEE_FLAG,
	EARNED_CREDIT_LEVEL,
	EKSTRAND_CREDIT_LEVEL,
	INTAKE_AGY_LOC_ID,
	ACTIVITY_DATE,
	INTAKE_CASELOAD_ID,
	INTAKE_USER_ID,
	CASE_OFFICER_ID,
	CASE_DATE,
	CASE_TIME,
	COMMUNITY_ACTIVE_FLAG,
	CREATE_INTAKE_AGY_LOC_ID,
	COMM_STAFF_ID,
	COMM_STATUS,
	COMMUNITY_AGY_LOC_ID,
	NO_COMM_AGY_LOC_ID,
	COMM_STAFF_ROLE,
	AGY_LOC_ID_LIST,
	STATUS_REASON,
	TOTAL_UNEXCUSED_ABSENCES,
	REQUEST_NAME,
	RECORD_USER_ID,
	INTAKE_AGY_LOC_ASSIGN_DATE,
	CREATE_DATETIME,
	CREATE_USER_ID,
	MODIFY_DATETIME,
	MODIFY_USER_ID,
	COALESCE(SEAL_FLAG, 'N'::character varying) AS SEAL_FLAG
from
	OFFENDER_BOOKINGS
where
	ROOT_OFFENDER_ID = :ROOTOFFENDERID
order by
	case
		when coalesce(ACTIVE_FLAG, 'N')= 'N' then coalesce(COMMUNITY_ACTIVE_FLAG, 'N')
		else ACTIVE_FLAG
	end desc,
	BOOKING_NO desc

}
OUMBADMI_OFFCONTACTS_UPDATE_OFFENDER_BOOKINGS {
	UPDATE OFFENDER_BOOKINGS set BOOKING_STATUS=:bookingStatus,MODIFY_USER_ID=:modifyUserId,MODIFY_DATETIME=CURRENT_TIMESTAMP where OFFENDER_BOOK_ID= :offenderBookId
}


OUMBADMI_CGFKCHK_OFF_CONTACTS_OFF_BKG{
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :BOOKINGSTATUS AND     DOMAIN = 'BOOK_STS' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OUMBADMI_CGFKCHK_OFF_CONTACTS_OFF_B2 {
	SELECT AGY_LOC.ABBREVIATION ,AGY_LOC.AGENCY_LOCATION_TYPE FROM   AGENCY_LOCATIONS AGY_LOC WHERE  AGY_LOC.AGY_LOC_ID = :AGYLOCID
}


OUMBADMI_OFFENDER_BOOKINGS_BOOKING_STATUS {
select
	COUNT(*)
from
	OFFENDER_BOOKINGS OFB
where
	OFB.OFFENDER_ID = :offenderId
	and OFB.BOOKING_STATUS = 'O'
}
