
OUMEEMOV_FIND_CGFKOFFEMFROMCITY {
 --	SELECT REF_CODE2.CODE  FROM_CITY  /* CG$FK */        ,REF_CODE2.DESCRIPTION  DSP_DESCRIPTION        ,REF_CODE2.LIST_SEQ  DSP_LIST_SEQ FROM   REFERENCE_CODES REF_CODE2 WHERE   DOMAIN='CITY' AND ((ACTIVE_FLAG = 'Y' AND    EXPIRED_DATE IS NULL ) OR   ::MODE = 'QUERY' ) ORDER BY  REF_CODE2.LIST_SEQ        ,REF_CODE2.DESCRIPTION
select REF_CODE2.CODE FROM_CITY , REF_CODE2.DESCRIPTION DSP_DESCRIPTION , REF_CODE2.LIST_SEQ DSP_LIST_SEQ from REFERENCE_CODES REF_CODE2 where domain = 'CITY' and (ACTIVE_FLAG = 'Y' and EXPIRED_DATE is null ) order by REF_CODE2.LIST_SEQ , REF_CODE2.DESCRIPTION
}

OUMEEMOV_FIND_CGFKOFFEMFROMAGYLOCID {
 	SELECT AGY_LOC.AGY_LOC_ID  code , AGY_LOC.DESCRIPTION  description FROM   AGENCY_LOCATIONS AGY_LOC
}

OUMEEMOV_FIND_CGFKOFFEMTOAGYLOCID {
 	SELECT AGY_LOC1.AGY_LOC_ID  code , AGY_LOC1.DESCRIPTION  description FROM   AGENCY_LOCATIONS AGY_LOC1
}

OUMEEMOV_FIND_CGFKOFFEMMOVEMENTTYPE {
 	SELECT REF_CODE.CODE  MOVEMENT_TYPE  ,REF_CODE.LIST_SEQ  DSP_LIST_SEQ4        ,REF_CODE.DESCRIPTION  DSP_DESCRIPTION5 FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN='MOVE_TYPE' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.LIST_SEQ
}

OUMEEMOV_FIND_CGFKOFFEMDIRECTIONCODE {
 	SELECT REF_CODE1.CODE  DIRECTION_CODE ,REF_CODE1.LIST_SEQ  DSP_LIST_SEQ3        ,REF_CODE1.DESCRIPTION  DSP_DESCRIPTION4 FROM   REFERENCE_CODES REF_CODE1 WHERE   DOMAIN='MOVE_DIRECT' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE1.LIST_SEQ
}

OUMEEMOV_FIND_CGFKOFFEMMOVEMENTREASONCO {
 	SELECT  MOVEMENT_REASON_CODE  CODE ,  DESCRIPTION     DESCRIPTION       FROM   MOVEMENT_REASONS WHERE   MOVEMENT_TYPE = :MOVEMENT_TYPE ORDER BY MOVEMENT_REASON_CODE
}

OUMEEMOV_FIND_CGFKOFFEMTOCITY {
 --	SELECT REF_CODE3.CODE  TO_CITY  /* CG$FK */        ,REF_CODE3.DESCRIPTION  DSP_DESCRIPTION2        ,REF_CODE3.LIST_SEQ  DSP_LIST_SEQ2 FROM   REFERENCE_CODES REF_CODE3 WHERE   DOMAIN='CITY' AND ((ACTIVE_FLAG = 'Y' AND    EXPIRED_DATE IS NULL ) OR   ::MODE = 'QUERY' ) ORDER BY  REF_CODE3.LIST_SEQ        ,REF_CODE3.DESCRIPTION
select REF_CODE3.CODE TO_CITY , REF_CODE3.DESCRIPTION DSP_DESCRIPTION2 , REF_CODE3.LIST_SEQ DSP_LIST_SEQ2 from REFERENCE_CODES REF_CODE3 where domain = 'CITY' and (ACTIVE_FLAG = 'Y' and EXPIRED_DATE is null ) order by REF_CODE3.LIST_SEQ , REF_CODE3.DESCRIPTION 
}

OUMEEMOV_OFFEM_FIND_OFFENDER_EXTERNAL_MOVEMENTS {
 	SELECT
    OFFENDER_BOOK_ID,
MOVEMENT_SEQ,
MOVEMENT_DATE,
MOVEMENT_TIME,
INTERNAL_SCHEDULE_TYPE,
INTERNAL_SCHEDULE_REASON_CODE,
MOVEMENT_TYPE,
MOVEMENT_REASON_CODE,
DIRECTION_CODE,
ARREST_AGENCY_LOC_ID,
TO_PROV_STAT_CODE,
ESCORT_CODE,
FROM_AGY_LOC_ID,
TO_AGY_LOC_ID,
ACTIVE_FLAG,
ESCORT_TEXT,
COMMENT_TEXT,
REPORTING_DATE,
TO_CITY,
FROM_CITY,
REPORTING_TIME,
EVENT_ID,
PARENT_EVENT_ID,
TO_COUNTRY_CODE,
OJ_LOCATION_CODE,
APPLICATION_DATE,
APPLICATION_TIME,
TO_ADDRESS_ID,
FROM_ADDRESS_ID,
SEAL_FLAG,
CREATE_DATETIME,
CREATE_USER_ID,
MODIFY_DATETIME,
MODIFY_USER_ID
FROM
    OFFENDER_EXTERNAL_MOVEMENTS
WHERE
    OFFENDER_BOOK_ID = :offenderBookId
ORDER BY
    MOVEMENT_DATE DESC,
    MOVEMENT_TIME DESC,
    ACTIVE_FLAG DESC
}
OUMEEMOV_OFFEM_INSERT_OFFENDER_EXTERNAL_MOVEMENTS {
	    INSERT INTO offender_external_movements (
        offender_book_id,
        movement_seq,
        movement_date,
        movement_time,
        movement_type,
        movement_reason_code,
        direction_code,
        from_agy_loc_id,
        to_agy_loc_id,
        active_flag,
        comment_text,
        to_city,
        from_city,
        create_datetime,
        create_user_id
    ) VALUES (
        :offenderBookId,
        (SELECT COALESCE(MAX(MOVEMENT_SEQ),0)+1 FROM OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID = :offenderBookId),
        :movementDate,
        :movementTime,
        :movementType,
        :movementReasonCode,
        :directionCode,
        :fromAgyLocId,
        :toAgyLocId,
        :activeFlag,
        :commentText,
        :toCity,
        :fromCity,
        current_timestamp,
        :createUserId
    )
}

OUMEEMOV_OFFEM_UPDATE_OFFENDER_EXTERNAL_MOVEMENTS {
	UPDATE OFFENDER_EXTERNAL_MOVEMENTS set MOVEMENT_DATE  = :movementDate ,MOVEMENT_TIME  = :movementTime ,MOVEMENT_TYPE  = :movementType ,MOVEMENT_REASON_CODE  = :movementReasonCode ,DIRECTION_CODE  = :directionCode ,FROM_AGY_LOC_ID  = :fromAgyLocId ,TO_AGY_LOC_ID  = :toAgyLocId ,ACTIVE_FLAG  = :activeFlag,COMMENT_TEXT  = :commentText ,TO_CITY  = :toCity ,FROM_CITY  = :fromCity  ,MODIFY_DATETIME  = current_timestamp ,MODIFY_USER_ID  = :modifyUserId
	WHERE OFFENDER_BOOK_ID= :offenderBookId AND MOVEMENT_SEQ = :movementSeq
}

OUMEEMOV_OFFEM_DELETE_OFFENDER_EXTERNAL_MOVEMENTS { 
	DELETE FROM OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID= :offenderBookId AND MOVEMENT_SEQ = :movementSeq
}


OUMEEMOV_OFF_BKG_PREDELETEPRE-DELETE {
	DELETE FROM OFFENDER_EXTERNAL_MOVEMENTS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OUMEEMOV_OFF_EM_PREINSERT {
	SELECT NVL(MAX(MOVEMENT_SEQ),0)+1 FROM OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID = :offenderBookId
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_REF_FRO_ {
	SELECT REF_CODE2.DESCRIPTION ,REF_CODE2.LIST_SEQ FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.CODE = :FROMCITY AND     DOMAIN='CITY' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR :MODE = 'QUERY')
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_REF_TO__ {
	SELECT REF_CODE3.DESCRIPTION ,REF_CODE3.LIST_SEQ FROM   REFERENCE_CODES REF_CODE3 WHERE  REF_CODE3.CODE = :TOCITY AND     DOMAIN='CITY' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR :MODE = 'QUERY')
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_REF_MOV_ {
	SELECT  '1' FROM   REFERENCE_CODES WHERE  CODE = :MOVEMENTREASONCODE
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_MOVE_RS_ {
	SELECT MOVE_RSN.DESCRIPTION FROM   MOVEMENT_REASONS MOVE_RSN WHERE  MOVE_RSN.MOVEMENT_REASON_CODE = :MOVEMENTREASONCODE AND     MOVEMENT_TYPE = :MOVEMENTTYPE
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_DIRECTI_ {
	SELECT REF_CODE1.LIST_SEQ ,REF_CODE1.DESCRIPTION FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :DIRECTIONCODE AND     DOMAIN='MOVE_DIRECT' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_MOVE_RE_ {
	SELECT REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :MOVEMENTTYPE AND     DOMAIN='MOVE_TYPE' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_AGY_LOC_ {
	SELECT AGY_LOC1.DESCRIPTION FROM   AGENCY_LOCATIONS AGY_LOC1 WHERE  AGY_LOC1.AGY_LOC_ID = :TOAGYLOCID
}

OUMEEMOV_CGFKCHK_OFF_EM_OFF_EM_AGY_2_ {
	SELECT AGY_LOC.DESCRIPTION FROM   AGENCY_LOCATIONS AGY_LOC WHERE  AGY_LOC.AGY_LOC_ID = :FROMAGYLOCID
}

OUMEEMOV_VALIDATE_MOVEMENT_DATETIME_ {
	SELECT MAX(MOVEMENT_DATE) FROM   OFFENDER_EXTERNAL_MOVEMENTS WHERE  OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OUMEEMOV_VALIDATE_MOVEMENT_DATETIME_ {
	SELECT MAX(MOVEMENT_TIME) FROM   OFFENDER_EXTERNAL_MOVEMENTS WHERE  OFFENDER_BOOK_ID = :OFFENDERBOOKID AND    TRUNC(MOVEMENT_DATE) = TRUNC(LV_MAX_DATE)
}

OUMEEMOV_VALIDATE_MOVEMENT_DATE_ {
	SELECT MAX(MOVEMENT_DATE) FROM   OFFENDER_EXTERNAL_MOVEMENTS WHERE  OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OUMEEMOV_VALIDATE_SEQ_NUM_ {
	SELECT 'Y' FROM  OFFENDER_EXTERNAL_MOVEMENTS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND   MOVEMENT_SEQ = :MOVEMENTSEQ
}
OUMEEMOV_GET_MOVEMENT_TYPE {
SELECT * FROM OFFENDER_EXTERNAL_MOVEMENTS OEM WHERE OFFENDER_BOOK_ID = :offenderBookId AND MOVEMENT_SEQ =:movementSeq
}
