GET_LIVING_UNIT_DESCP{
 SELECT DESCRIPTION FROM LIVING_UNITS WHERE LIVING_UNIT_ID = :P_LIV_UNIT_ID
}

TABLE_CUR{
SELECT AC1.TABLE_NAME TABLE_NAME, UC1.COLUMN_NAME COLUMN_NAME FROM ALL_CONSTRAINTS AC1 ,ALL_CONSTRAINTS AC2 ,ALL_CONS_COLUMNS UC1 WHERE AC1.CONSTRAINT_TYPE = 'R' AND AC2.OWNER = UPPER(coalesce(:P_OWNER, 'OMS_OWNER')) AND AC2.CONSTRAINT_NAME = AC1.R_CONSTRAINT_NAME AND AC2.OWNER = AC1.R_OWNER AND AC2.CONSTRAINT_TYPE IN ('P', 'U') AND AC2.TABLE_NAME = UPPER(:P_TABLE_NAME) AND UC1.OWNER = AC1.OWNER AND AC1.TABLE_NAME = UC1.TABLE_NAME AND UC1.CONSTRAINT_NAME = AC1.CONSTRAINT_NAME 
}            

TABLE_CUR_ONE{
SELECT TABLE_NAME FROM ALL_CONS_COLUMNS WHERE CONSTRAINT_NAME = :P_CONSTRAINT_NAME
}

  
TABLE_CUR {
      SELECT AC1.TABLE_NAME TABLE_NAME, UC1.COLUMN_NAME COLUMN_NAME
        FROM ALL_CONSTRAINTS  AC1,
             ALL_CONSTRAINTS  AC2,
             ALL_CONS_COLUMNS UC1,
             ALL_CONS_COLUMNS UC2
       WHERE AC1.CONSTRAINT_TYPE = 'r'
         AND AC2.OWNER = (coalesce(:P_OWNER, 'oms_owner'))
         AND AC2.CONSTRAINT_NAME = AC1.R_CONSTRAINT_NAME
         AND AC2.OWNER = AC1.R_OWNER
         AND AC2.CONSTRAINT_TYPE IN ('p', 'u')
         AND AC2.TABLE_NAME = (:P_TABLE_NAME)
         AND UC1.OWNER = AC1.OWNER
         AND AC1.TABLE_NAME = UC1.TABLE_NAME
         AND UC1.CONSTRAINT_NAME = AC1.CONSTRAINT_NAME
         AND UC2.OWNER = AC2.OWNER
         AND AC2.TABLE_NAME = UC2.TABLE_NAME
         AND UC2.CONSTRAINT_NAME = AC2.CONSTRAINT_NAME
         AND UC2.COLUMN_NAME =(:P_COLUMN_NAME)
}



OFFENDER_CASE_NOTES_SELECT{
 SELECT 1  FROM  OFFENDER_CASE_NOTES   WHERE  CASE_NOTE_ID = :P_KEY_ID  limit 1
 }
 
SUBSTR_FUNCTION{ 
 select SUBSTR(:L_KEY_STRING,
INSTR(:L_KEY_STRING, '=>') + 2,
INSTR(:L_KEY_STRING, '>/') -
INSTR(:L_KEY_STRING, '=>') - 2) from dual
}
SUBSTR_FUNCTION1{
select SUBSTR(:L_KEY_STRING, 2, INSTR(:L_KEY_STRING, '=>') - 2)  from dual
}
SUBSTR_FUNCTION2{
select SUBSTR(:L_KEY_STRING, 2, INSTR(:L_KEY_STRING, '>/') + 2)  from dual
}
SYS_PROFILE_CUR{ 
SELECT PROFILE_VALUE FROM SYSTEM_PROFILES  WHERE PROFILE_TYPE = :P_PTYPE  AND PROFILE_CODE = :P_PCODE
}

GET_STAFF_CUR{
SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID = :P_USER_ID
}