INSERT INTO dynamic_grid_config (MODULE_NAME, GRID_NAME, DB_TABLE_NAME, CONFIG_JSON, CREATE_USER_ID) 
  VALUES ('OCDLEGLS', 'custOrders', 'OCDLEGLO_DATA', '[{"field":"displayNo","fieldName":"custorder.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"type","fieldName":"custorder.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=CUST","sourceType":"OIMSREQS","editable":false},{"field":"termTypeAndLength","fieldName":"custorder.termtypeandlength","dataType":"text","editable":false},{"field":"commenceType","fieldName":"custorder.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","editable":false},{"field":"relatedTo","fieldName":"custorder.linkto","dataType":"text","editable":false},{"field":"commenceDate","fieldName":"custorder.commencedate","dataType":"date","editable":false},{"field":"erd","fieldName":"custorder.erd","dataType":"date","editable":false},{"field":"ped","fieldName":"custorder.ped","dataType":"date","editable":false},{"field":"lrd","fieldName":"custorder.lrd","dataType":"date","editable":false},{"field":"status","fieldName":"custorder.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"orderType","hide":true,"dataType":"text","editable":false}]', 'OMS_OWNER');

INSERT INTO dynamic_grid_config (MODULE_NAME, GRID_NAME, DB_TABLE_NAME, CONFIG_JSON, CREATE_USER_ID) 
  VALUES ('OCDLEGLS', 'nCustOrders', 'OCDLEGLO_DATA', '[{"field":"displayNo","fieldName":"ncustorder.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"type","fieldName":"ncustorder.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=NCUS","sourceType":"OIMSREQS","editable":false},{"field":"termTypeAndLength","fieldName":"ncustorder.termtypeandlength","dataType":"text","editable":false},{"field":"commenceType","fieldName":"ncustorder.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","editable":false},{"field":"relatedTo","fieldName":"ncustorder.linkto","dataType":"text","editable":false},{"field":"commenceDate","fieldName":"ncustorder.commencedate","dataType":"date","editable":false},{"field":"expiryDate","fieldName":"ncustorder.expiryDate","dataType":"date","editable":true},{"field":"status","fieldName":"ncustorder.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"orderType","hide":true,"dataType":"text","editable":false}]', 'OMS_OWNER');

INSERT INTO dynamic_grid_config (MODULE_NAME, GRID_NAME, DB_TABLE_NAME, CONFIG_JSON, CREATE_USER_ID) 
   VALUES ('OCDLEGLS', 'hwd', 'OCDLEGLO_DATA', '[{"field":"receivedDate","fieldName":"hwd.receiveddate","dataType":"date","editable":false},{"field":"issuingAgyLocId","fieldName":"hwd.agency","source":"domain","url":"HWD_AGENCY","dataType":"lov","editable":false},{"field":"holdWarrentDetainerType","fieldName":"hwd.type","source":"domain","url":"HWD_TYPE","dataType":"lov","editable":false},{"field":"warrentNumber","fieldName":"hwd.refnumber","dataType":"text","editable":false},{"field":"startDate","fieldName":"hwd.commencedate","dataType":"date","editable":false},{"field":"expiryDate","fieldName":"hwd.expirydate","dataType":"date","editable":false},{"field":"holdWarrentDetainerTypeInfoIdStatus","fieldName":"hwd.status","dataType":"lov","source":"domain","url":"HWD_STATUS","editable":false}]', 'OMS_OWNER');

--
INSERT INTO dynamic_grid_config (MODULE_NAME, GRID_NAME, DB_TABLE_NAME, CONFIG_JSON, CREATE_USER_ID) 
   VALUES ('OCDENFOR', 'crtOrders', 'OCDLEGLO_DATA', '[{"field":"displayNo","fieldName":"ocdenfor.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"ocdenfor.ordereddate","dataType":"date","required":true,"editable":false},{"field":"matter","fieldName":"ocdenfor.matter","dataType":"text","editable":false},{"field":"court","fieldName":"ocdenfor.court","dataType":"lov","source":"link","url":"ocdccase/populateCourtData","sourceType":"OUMAGLOC","required":true,"editable":false},{"field":"type","fieldName":"ocdenfor.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=NCUS","sourceType":"OIMSREQS","required":true,"editable":false},{"field":"commenceType","fieldName":"ocdenfor.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","required":true,"editable":false},{"field":"relatedTo","fieldName":"ocdenfor.linkto","dataType":"text","editable":false},{"field":"commenceDate","fieldName":"ocdenfor.commencedate","dataType":"date","editable":false},{"field":"termTypeAndLength","fieldName":"ocdenfor.duration","dataType":"text","required":true,"editable":false},{"field":"expiryDate","fieldName":"ocdenfor.expiryDate","dataType":"date","editable":false},{"field":"status","fieldName":"ocdenfor.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"orderType","hide":true,"dataType":"text"}]', 'OMS_OWNER');

--
UPDATE dynamic_grid_config SET CONFIG_JSON ='[{"field":"chargeId","dataType":"number","editable":false,"hide":true},{"field":"select","dataType":"checkbox","fieldName":"ocdchgsu.select","editable":true},{"field":"matter","fieldName":"ocdchgsu.matter","dataType":"text","required":true,"editable":true},{"field":"act","fieldName":"ocdchgsu.act","dataType":"lov","source":"link","url":"ocmpconf/populateStatutes","sourceType":"OIMSTATU","editable":true},{"field":"code","fieldName":"ocdchgsu.code","dataType":"text","required":false,"editable":false},{"field":"description","fieldName":"ocdchgsu.description","required":true,"dataType":"text","editable":false},{"field":"descriptionLaunch","dataType":"hyperlink","displayFields":["code","description","act","legislativeBody"],"parentField":["code","description","act"],"lovUrl":"ocmpconf/getOffencesOnStatute?statuteCode=:act","link":"/multiLov"},{"field":"type","fieldName":"ocdchgsu.type","dataType":"lov","source":"link","sourceType":"OIMOFFEN","parentFields":["code","act"],"url":"ocmpconf/getAllowableOffenceType?offenceCode=:code&statuteCode=:act","editable":true},{"field":"incidentDate","fieldName":"ocdchgsu.incidentdate","dataType":"date","editable":true},{"field":"Range","fieldName":"ocdchgsu.range","dataType":"date","editable":true},{"field":"plea","fieldName":"ocdchgsu.plea","dataType":"lov","source":"domain","url":"PLEA_STATUS","editable":true},{"field":"currentStatus","fieldName":"ocdchgsu.currentstatus","dataType":"text","editable":false},{"field":"details","fieldName":"ocdchgsu.details","dataType":"text","editable":false}]' WHERE MODULE_NAME = 'OCDCHGSU' AND GRID_NAME = 'chargesDlg';

UPDATE dynamic_grid_config SET CONFIG_JSON ='[{"field":"chargeId","dataType":"number","editable":false,"hide":true},{"field":"select","fieldName":"ocdchgsu.select","dataType":"checkbox","editable":false},{"field":"matter","fieldName":"ocdchgsu.matter","dataType":"text","required":true,"editable":true},{"field":"act","fieldName":"ocdchgsu.act","dataType":"lov","source":"link","url":"ocmpconf/populateStatutes","sourceType":"OIMSTATU","editable":true},{"field":"code","fieldName":"ocdchgsu.code","dataType":"text","required":false,"editable":false},{"field":"description","fieldName":"ocdchgsu.description","dataType":"text","required":true,"editable":false},{"field":"descriptionLaunch","dataType":"hyperlink","displayFields":["code","description","act","legislativeBody"],"parentField":["code","description","act"],"lovUrl":"ocmpconf/getOffencesOnStatute?statuteCode=:act","link":"/multiLov"},{"field":"type","fieldName":"ocdchgsu.type","dataType":"lov","source":"link","sourceType":"OIMOFFEN","parentFields":["code","act"],"url":"ocmpconf/getAllowableOffenceType?offenceCode=:code&statuteCode=:act","editable":true},{"field":"incidentDate","fieldName":"ocdchgsu.incidentdate","dataType":"date","editable":true},{"field":"Range","fieldName":"ocdchgsu.range","dataType":"date","editable":true},{"field":"plea","fieldName":"ocdchgsu.plea","dataType":"lov","source":"domain","url":"PLEA_STATUS","editable":true},{"field":"currentStatus","fieldName":"ocdchgsu.currentstatus","dataType":"text","editable":false},{"field":"details","fieldName":"ocdchgsu.details","dataType":"text","editable":false}]' WHERE MODULE_NAME = 'OCDCHGSU' AND GRID_NAME = 'charges';
