delete from MODULE_PRIVILEGES where MODULE_NAME in ('OCDLEGLS', 'OCDLEGLO', 'OCDCHGSU', 'OIDCRTEV', 'OCDNCODE');

delete from OMS_MODULES where MODULE_NAME in ('OCDLEGLS', 'OCDLEGLO', 'OCDCHGSU', 'OIDCRTEV', 'OCDNCODE');


INSERT INTO OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, DYNAMIC_FORM, APPLN_CODE ) VALUES('OCDLEGLS', 'Legal Summary', 'SCREEN', 'Y', 'INST');

INSERT INTO OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, DYNAMIC_FORM, APPLN_CODE ) VALUES('OCDLEGLO', 'Legal Orders', 'SCREEN', 'Y', 'INST');

INSERT INTO OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, DYNAMIC_FORM, APPLN_CODE ) VALUES('OCDCHGSU', 'Charge Summary', 'SCREEN', 'Y', 'INST');

INSERT INTO OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, DYNAMIC_FORM, APPLN_CODE ) VALUES('OIDCRTEV', 'Court Events', 'SCREEN', 'Y', 'INST');

INSERT INTO OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, DYNAMIC_FORM, APPLN_CODE ) VALUES('OCDNCODE', 'Non Custodial Orders', 'SCREEN', 'Y', 'INST');

---

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCDLEGLS', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCDLEGLO', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCDCHGSU', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OIDCRTEV', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCDNCODE', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, NULL, NULL);

--

INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE) 
    VALUES('OIEXPQAC', 'Export Quick Action and API', 'SCREEN', NULL, NULL, 0, 'OMS4', NULL, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL, NULL);
 
--
 
INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
    VALUES('OIEXPQAC', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);
	
INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE) 
    VALUES('OIIMPQAC', 'Import Quick Action API', 'SCREEN', NULL, NULL, 0, 'OMS4', NULL, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL, NULL);
    
--
INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
    VALUES('OIIMPQAC', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);
	
INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE) 
    VALUES('OIEXPPRO', 'Export process', 'SCREEN', NULL, NULL, 0, 'OMS4', NULL, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL, NULL);
 
 --
   
INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
    VALUES('OIEXPPRO', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);
	
INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE) 
    VALUES('OIIMPPRO', 'Import Process', 'SCREEN', NULL, NULL, 0, 'OMS4', '', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL, NULL);
    
--
INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
    VALUES('OIIMPPRO', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

--
 

INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE) 
    VALUES('OWEACPLN', 'Weekly Activity Plan', 'SCREEN', NULL, NULL, 0, 'COM', NULL, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL, NULL);
   
--
INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE)
VALUES('OCUNAWRN', 'Non-Association Conflict Warning', 'SCREEN', NULL, NULL, 0, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCUNAWRN', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

--
 
 INSERT INTO OMS_OWNER.OMS_MODULES(MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE) 
    VALUES('CMNPROSS', 'Common Process', 'SCREEN', NULL, NULL, 0, 'OMS4', NULL, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL, NULL);
    
 
INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
    VALUES('CMNPROSS', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

---