INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) 
  VALUES('KEY_DATES' ,'BOOKING_PED' ,'PED',99,'Y' ,'N' ,'OMS_OWNER',null ,null,null ,null,CURRENT_TIMESTAMP,'OMS_OWNER' ,CURRENT_TIMESTAMP ,null );
--
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME) 
VALUES('PROCEEDING', 'CANCEL', 'Cancel' ,3 ,'Y' ,'Y' ,CURRENT_TIMESTAMP,'OMS_OWNER' ,CURRENT_TIMESTAMP);

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME) 
VALUES('PROCEEDING', 'VARY', 'Vary' ,3 ,'Y' ,'Y' ,CURRENT_TIMESTAMP,'OMS_OWNER' ,CURRENT_TIMESTAMP);

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME) 
VALUES('PROCEEDING', 'SUSPEND', 'Suspend' ,3 ,'Y' ,'Y' ,CURRENT_TIMESTAMP,'OMS_OWNER' ,CURRENT_TIMESTAMP);

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME) 
VALUES('PROCEED_STS', 'ALLOCATED', 'Allocated', 5 ,'Y' ,'Y' ,CURRENT_TIMESTAMP,'OMS_OWNER' ,CURRENT_TIMESTAMP);
	
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME) 
VALUES('PROCEED_STS', 'UNALLOCATED', 'Unallocated' ,6 ,'Y' ,'Y' ,CURRENT_TIMESTAMP,'OMS_OWNER' ,CURRENT_TIMESTAMP);

--

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'UNALLOC' ,'Allocated' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'PROG' ,'In Progress' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'REV' ,'In Review' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'COMP' ,'Completed' ,5,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'SUBM' ,'Submitted' ,6,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );


INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'CLOSED' ,'Closed' ,7,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'NR' ,'Not Required' ,8,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN, CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, SYSTEM_DATA_FLAG, MODIFY_USER_ID, EXPIRED_DATE, NEW_CODE, PARENT_CODE, PARENT_DOMAIN, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG)
VALUES('COM_CON_CAT', 'CRT_REP', 'Court Report', 3, 'Y', 'N', 'OMS_OWNER', NULL, NULL, NULL, NULL, current_timestamp, 'OMS_OWNER', current_timestamp, NULL);

--
delete from REFERENCE_CODES where domain='REP_REQ_STS' and CODE = 'UNALLOC' and DESCRIPTION = 'Allocated';