
OIINTLOC_FIND_RGUSAGES {
 	SELECT DESCRIPTION , CODE, ACTIVE_FLAG FROM REFERENCE_CODES WHERE DOMAIN = 'ILOC_USG' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) AND PARENT_CODE = 'INT_MOV_USG' ORDER BY LIST_SEQ ,DESCRIPTION
}

OIINTLOC_INTLOC_FIND_V_INT_LOC_USAGE_LOCATIONS {
 	SELECT AGY_LOC_ID ,INTERNAL_LOCATION_USAGE ,EVENT_SUB_TYPE ,INTERNAL_LOCATION_USAGE_ID ,INTERNAL_LOCATION_ID , DESCRIPTION ,INTERNAL_LOCATION_CODE ,CAPACITY ,USAGE_LOCATION_TYPE ,LIST_SEQ ,USAGE_LOCATION_ID ,PARENT_USAGE_LOCATION_ID , USER_DESC ,INT_LOC_DEACTIVATE_DATE ,LOWEST_LEVEL_FLAG FROM V_INT_LOC_USAGE_LOCATIONS where lowest_level_flag = 'Y' and internal_location_usage = :usageCode and agy_loc_id = :agyLocId and int_loc_deactivate_date is null order by list_seq,description
}
OIINTLOC_INTLOC_UPDATE_V_INT_LOC_USAGE_LOCATIONS {
	UPDATE V_INT_LOC_USAGE_LOCATIONS set AGY_LOC_ID  = :agyLocId ,INTERNAL_LOCATION_USAGE  = :internalLocationUsage ,EVENT_SUB_TYPE  = :eventSubType ,INTERNAL_LOCATION_USAGE_ID  = :internalLocationUsageId ,INTERNAL_LOCATION_ID  = :internalLocationId ,DESCRIPTION  = :description ,INTERNAL_LOCATION_CODE  = :internalLocationCode ,CAPACITY  = :capacity ,USAGE_LOCATION_TYPE  = :usageLocationType ,LIST_SEQ  = :listSeq ,USAGE_LOCATION_ID  = :usageLocationId ,PARENT_USAGE_LOCATION_ID  = :parentUsageLocationId ,USER_DESC  = :userDesc ,INT_LOC_DEACTIVATE_DATE  = :intLocDeactivateDate ,LOWEST_LEVEL_FLAG  = :lowestLevelFlag 
}

