 
OCMCTOFF_FIND_RGPSSEX {
 	SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'PS_SEX' AND
  ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, DESCRIPTION, CODE

}

OCMCTOFF_FIND_RGETHNICITY {
 	SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'ETHNICITY' AND
  ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, DESCRIPTION, CODE

}

OCMCTOFF_FIND_RGPSNEEDS {
 	SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'PS_FACILITY' AND
  ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, DESCRIPTION, CODE

}

OCMCTOFF_FIND_RGPSAGERANGE {
 	SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'PS_AGE_RANGE' AND
  ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, DESCRIPTION, CODE

}

OCMCTOFF_FIND_RGPSOFFGRPS {
 	SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'PS_OFF_GRPS' AND
  ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, DESCRIPTION, CODE

}

OCMCTOFF_CRPRFGD_FIND_COURSE_ACTIVITY_PROFILES {
 	SELECT
  CRS_ACTY_ID, PROGRAM_PROFILE_TYPE, PROGRAM_PROFILE_CODE, CREATE_DATETIME,
  CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG
FROM COURSE_ACTIVITY_PROFILES

}
OCMCTOFF_CRPRFGD_INSERT_COURSE_ACTIVITY_PROFILES {
	INSERT INTO COURSE_ACTIVITY_PROFILES(CRS_ACTY_ID, PROGRAM_PROFILE_TYPE, PROGRAM_PROFILE_CODE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, 
	 SEAL_FLAG) VALUES(:crsActyId, :programProfileType, :programProfileCode, CURRENT_TIMESTAMP, :createUserId, null, 
	 :sealFlag)
} 

OCMCTOFF_CRPRFGD_UPDATE_COURSE_ACTIVITY_PROFILES {
	UPDATE COURSE_ACTIVITY_PROFILES set CRS_ACTY_ID = :crsActyId, PROGRAM_PROFILE_TYPE = :programProfileType, PROGRAM_PROFILE_CODE = :programProfileCode, 
	 MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID = :modifyUserId, 
	SEAL_FLAG = :sealFlag where CRS_ACTY_ID = :crsActyId
} 

OCMCTOFF_CRPRFGD_DELETE_COURSE_ACTIVITY_PROFILES { 
	DELETE FROM COURSE_ACTIVITY_PROFILES where CRS_ACTY_ID = :crsActyId AND PROGRAM_PROFILE_TYPE = :programProfileType AND PROGRAM_PROFILE_CODE = :programProfileCode
} 

OCMCTOFF_GET_PROGRAM_PROFILE_TYPE { 
	SELECT DESCRIPTION
FROM REFERENCE_CODES
where
  DOMAIN=:domainName and
  code=:programProfileCode

}
