
OFFENDER_TRUST_ACCOUNTS_TEMP{
DELETE FROM Offender_Trust_Accounts_Temp WHERE session_id = :p_session_id AND caseload_id = :p_caseload_id
}
All_C{
SELECT OTA.OFFENDER_ID, OTA.ACCOUNT_CLOSED_FLAG, OTA.HOLD_BALANCE, OTA.CURRENT_BALANCE, OTA.NOTIFY_DATE, OFF.OFFENDER_ID_DISPLAY, OFF.LAST_NAME, OFF.FIRST_NAME FROM OFFENDER_TRUST_ACCOUNTS OTA, OFFENDERS OFF WHERE OTA.CASELOAD_ID = :P_CASELOAD_ID AND OTA.OFFENDER_ID = OFF.OFFENDER_ID AND OTA.ACCOUNT_CLOSED_FLAG = 'N' AND OTA.CURRENT_BALANCE > 0 
}
Max_Movement_C{
SELECT OEM.OFFENDER_BOOK_ID, OEM.TO_AGY_LOC_ID, OEM.MOVEMENT_DATE, OB.ACTIVE_FLAG, OB.IN_OUT_STATUS, OB.BOOKING_STATUS FROM OFFENDER_EXTERNAL_MOVEMENTS OEM, OFFENDER_BOOKINGS OB WHERE OEM.OFFENDER_BOOK_ID = OB.OFFENDER_BOOK_ID AND OB.OFFENDER_BOOK_ID = (SELECT MAX(OFFENDER_BOOK_ID) FROM OFFENDER_BOOKINGS OB2 WHERE OB.ROOT_OFFENDER_ID = OB2.ROOT_OFFENDER_ID AND OB2.BOOKING_TYPE = 'INST') AND OEM.MOVEMENT_SEQ = (SELECT MAX (MOVEMENT_SEQ) FROM OFFENDER_EXTERNAL_MOVEMENTS OEM2 WHERE OEM2.OFFENDER_BOOK_ID = OEM.OFFENDER_BOOK_ID) AND ( OEM.TO_AGY_LOC_ID = 'OUT' OR OEM.TO_AGY_LOC_ID NOT IN (SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :P_CASELOAD_ID AND AGY_LOC_ID <> 'TRN')) AND OB.ROOT_OFFENDER_ID = :P_OFFENDER_ID AND OEM.MOVEMENT_DATE BETWEEN :P_FROM_DATE AND :P_TO_DATE
}
OFFENDER_TRUST_ACCOUNTS_TEMP1{
insert into Offender_Trust_Accounts_Temp (caseload_id, offender_id, session_id, account_closed_flag, hold_balance, current_balance, modify_date, notify_date, offender_book_id, last_name, first_name, movement_date, agy_loc_id, Offender_Id_Display, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME ) values (:caseloadId, :offenderId, :sessionId, :accountClosedFlag, :holdBalance, :currentBalance, CURRENT_TIMESTAMP, :notifyDate, :offenderBookId, :lastName, :firstName, :movementDate, :agyLocId, :offenderIdDisplay, :createUserId, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP )
}
ZERO_C{
select OTA.OFFENDER_ID, OTA.ACCOUNT_CLOSED_FLAG, OTA.HOLD_BALANCE, OTA.CURRENT_BALANCE, OTA.NOTIFY_DATE, OFF.OFFENDER_ID_DISPLAY, OFF.LAST_NAME, OFF.FIRST_NAME FROM OFFENDER_TRUST_ACCOUNTS OTA, OFFENDERS OFF WHERE OTA.CASELOAD_ID = :P_CASELOAD_ID AND OTA.OFFENDER_ID = OFF.OFFENDER_ID AND OTA.ACCOUNT_CLOSED_FLAG = 'N' AND OTA.CURRENT_BALANCE = 0
}
NOTIFY_C{
SELECT OTA.Offender_Id, OTA.Account_closed_flag, OTA.Hold_Balance, OTA.Current_Balance, OTA.Notify_Date, OFF.Offender_Id_Display, OFF.last_name, OFF.first_name FROM Offender_Trust_Accounts OTA, Offenders OFF WHERE ota.caseload_id = :p_caseload_id AND ota.offender_id = off.offender_id AND ota.account_closed_flag = 'N' AND ota.Notify_Date IS NOT NULL 
}
AGY_LOC_ID_EXISTS_C{
SELECT MIN('X') FROM Caseload_Agency_Locations CAL WHERE Caseload_Id = :p_caseload_id AND Agy_loc_Id = :p_agy_loc_id     
}