update
    json_spec
set
    json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"user_id":"header.intUser.intUserId","first_name":"header.intUser.intUserName","date_time":"header.intDatetime"}},"pFromBookingNo":"body.prisonerDetails.imprisonmentId","pToOffIdDisplay":"body.prisonerDetails.oldDcsId","pFromOffIdDisplay":"body.prisonerDetails.newDcsId"}},{"operation":"default","spec":{"header":{"intId":"UnilinkRECO"}}}]',
    modify_datetime = current_timestamp,
    modify_user_id = 'OMS_OWNER'
where
    spec_key = 'TRANSFORM_PRISONER_RECONCILATION';

update
	json_spec
set
	json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":["header.intDatetime","body.trailer.responseDatetime"]}},"correlationId":"header.intCorrelationId","pin":"body.prisonerDetails[#2].imprisonmentDetails.pin","paroleDateDetails":{"*":{"parolecommencedate":"body.prisonerDetails[#4].release.releasestartDate","paroleexpirydate":"body.prisonerDetails[#4].release.releasedueEndDate"}},"paroleOrderDetails":{"*":{"number":"body.prisonerDetails[#4].release.order[#2].number","typecode":"body.prisonerDetails[#4].release.order[#2].type","origincode":"body.prisonerDetails[#4].release.order[#2].origin","issueddate":"body.prisonerDetails[#4].release.order[#2].issuedDate","orderstartdate":"body.prisonerDetails[#4].release.order[#2].orderedStartDate","orderenddate":"body.prisonerDetails[#4].release.order[#2].orderedEndDate"}},"paroleConditionDetails":{"*":{"conditions":{"value":{"*":"body.prisonerDetails[#6].release.order[#4].condition[]"}}}}}},{"operation":"modify-default-beta","spec":{"body":{"prisonerDetails":{"*":{"release":{"orderCourtFileNumber":"TBD"}}}}}},{"operation":"default","spec":{"header":{"intId":"ParoleConditions"},"body":{"trailer":{"respCode":"TBD","errMsg":""}}}}]',
	modify_datetime = current_timestamp,
	modify_user_id = 'OMS_OWNER'
where
	spec_key = 'PAROLE_COND_RESPONSE_FORMATTER';
	
	
update
	json_spec
set
	json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"first_name":"body.prisonerDetails.demographics.firstName","last_name":"body.prisonerDetails.demographics.surName","middle_name":"body.prisonerDetails.demographics.middleName","second_middle_name":"body.prisonerDetails.demographics.secondMiddleName","sex_code":"body.prisonerDetails.demographics.gender","birth_date":"body.prisonerDetails.demographics.dob","offender_id_display":"body.prisonerDetails.imprisonmentDetails.dcsId"}},"offenderBookingDetails":{"*":{"booking_no":"body.prisonerDetails.imprisonmentDetails.imprisonmentId","booking_begin_date":"body.prisonerDetails.imprisonmentDetails.intakeDate","booking_status":"body.prisonerDetails.imprisonmentDetails.imprisonmentStatus","agy_loc_id":"body.prisonerDetails.housing.facility"}},"offenderHousingDetails":{"*":{"housing_lev_1_code":"body.prisonerDetails.housing.pod","housing_lev_2_code":"body.prisonerDetails.housing.unit","housing_lev_3_code":"body.prisonerDetails.housing.cell","iep_level":"body.prisonerDetails.housing.regime"}},"warnings":{"*":{"code":"body.prisonerDetails.alerts[#2].alertCode","createdate":"body.prisonerDetails.alerts[#2].alertStartDate","expirydate":"body.prisonerDetails.alerts[#2].alertEndDate","comment_text":"body.prisonerDetails.alerts[#2].alertComment"}},"offenderFinancialDetails":{"*":{"current_balance":"body.prisonerDetails.financials.accountBalance","balance":"body.prisonerDetails.financials.resettlementAccountBalance","apply_spending_limit_amount":"body.prisonerDetails.financials.transactionSpendLimit"}},"offenderProfileDetails":{"*":{"nationality":"body.prisonerDetails.demographics.nationality","ethnicity":"body.prisonerDetails.demographics.ethnicity","religion":"body.prisonerDetails.demographics.religion"}}}},{"operation":"modify-default-beta","spec":{"body":{"prisonerDetails":{"imprisonmentDetails":{"releaseDateTime":"","releaseReason":""},"alerts":[]}}}},{"operation":"default","spec":{"header":{"intId":"UnilinkIMPR"}}}]',
	modify_datetime = current_timestamp,
	modify_user_id = 'OMS_OWNER'
where
	spec_key = 'TRANSFORM_PRISONER_SENT_STATUS';

update
    json_spec
set
    json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"user_id":"header.intUser.intUserId","first_name":"header.intUser.intUserName","date_time":"header.intDatetime"}},"pFirstName":"body.demographics.firstName","pLastName":"body.demographics.surName","pMiddleName":"body.demographics.middleName","secondMiddleName":"body.demographics.secondMiddleName","dob":"body.demographics.dob","intCorrelationId":"header.intCorrelationId","SearchTypeRes":{"*":{"searchtype":"body.searchType"}}}},{"operation":"default","spec":{"header":{"intId":"JTSNameSearch","intCorrelationId":""}}}]',
    modify_datetime = current_timestamp,
    modify_user_id = 'OMS_OWNER'
where
    spec_key = 'TRANSFRM_OFFDETLS_REQ_WITH_NAMES';

update
    json_spec
set
    json_specs = '[{"operation":"shift","spec":{"correlationId":"header.intCorrelationId","identifier":"body.personDetails.imprisonmentDetails.pin","nameDetails":{"*":{"first_name":"body.personDetails.demographics.firstName","last_name":"body.personDetails.demographics.surName","middle_name":"body.personDetails.demographics.middleName","second_middle_name":"body.personDetails.demographics.secondMiddleName","sex_code":"body.personDetails.demographics.gender","birth_date":"body.personDetails.demographics.dob"}},"deathDetails":{"*":{"death_date":"body.personDetails.demographics.dod"}},"aliasDetails":{"*":{"givenname":"body.personDetails.alias[#2].firstName","othergivennames":"body.personDetails.alias[#2].middleName","second_middle_name":"body.personDetails.alias[#2].secondMiddleName","familyname":"body.personDetails.alias[#2].surName","dateofbirth":"body.personDetails.alias[#2].dob"}},"warningDetails":{"*":{"description":"body.personDetails.alerts[#2].alertCode","alert_type":"body.personDetails.alerts[#2].alertType","createdate":"body.personDetails.alerts[#2].alertStartDate","expirydate":"body.personDetails.alerts[#2].alertEndDate","comment_text":"body.personDetails.alerts[#2].alertComment"}},"residenceDetails":{"*":{"address_line1":"body.personDetails.address.address_line","street":"body.personDetails.address.street","street_number":"body.personDetails.address.street_number","street_direction":"body.personDetails.address.street_direction","suite_number":"body.personDetails.address.suite_number","city_name":"body.personDetails.address.city_name","city_code":"body.personDetails.address.city_code","state_code":"body.personDetails.address.state_code","country_code":"body.personDetails.address.country_code","postal":"body.personDetails.address.postal_code","address":"body.personDetails.address.unstructured_address_line","no_fixed_address_flag":"body.personDetails.address.no_address_flag"}},"occupation":{"*":{"occupation":"body.personDetails.demographics.occupation"}},"userDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":["header.intDatetime","body.trailer.responseDatetime"]}},"wantedDetails":{"*":{"wanted_type":"body.personDetails.wanted.wantedType","escape_date_time":"body.personDetails.wanted.wantedDateTime","escape_comment_text":"body.personDetails.wanted.wantedComment"}}}},{"operation":"modify-default-beta","spec":{"body":{}}},{"operation":"default","spec":{"header":{"intId":"SAPOLOffenderDetail"},"body":{"trailer":{"respCode":"Success","errMsg":""},"personDetails":{"imprisonmentDetails":[],"demographics":[],"address":[],"alerts":[],"alias":[],"wanted":[]}}}}]',
    modify_datetime = current_timestamp,
    modify_user_id = 'OMS_OWNER'
where
    spec_key = 'TRANSFORM_EXTERNAL';

update
    json_spec
set
    json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"first_name":"body.prisonerDetails.demographics.firstName","middle_name":"body.prisonerDetails.demographics.middleName","second_middle_name":"body.prisonerDetails.demographics.secondMiddleName","last_name":"body.prisonerDetails.demographics.surName","sex_code":"body.prisonerDetails.demographics.gender","birth_date":"body.prisonerDetails.demographics.dob","offender_id_display":"body.prisonerDetails.imprisonmentDetails.dcsId"}},"offenderBookingDetails":{"*":{"booking_no":"body.prisonerDetails.imprisonmentDetails.imprisonmentId","booking_begin_date":"body.prisonerDetails.imprisonmentDetails.intakeDate","booking_status":"body.prisonerDetails.imprisonmentDetails.imprisonmentStatus","agy_loc_id":"body.prisonerDetails.housing.facility"}},"offenderHousingDetails":{"*":{"housing_lev_1_code":"body.prisonerDetails.housing.pod","housing_lev_2_code":"body.prisonerDetails.housing.unit","housing_lev_3_code":"body.prisonerDetails.housing.cell","iep_level":"body.prisonerDetails.housing.regime"}},"warnings":{"*":{"description":"body.prisonerDetails.alerts[#2].alertCode","createdate":"body.prisonerDetails.alerts[#2].alertStartDate","expirydate":"body.prisonerDetails.alerts[#2].alertEndDate","comment_text":"body.prisonerDetails.alerts[#2].alertComment"}},"offenderFinancialDetails":{"*":{"current_balance":"body.prisonerDetails.financials.accountBalance","balance":"body.prisonerDetails.financials.resettlementAccountBalance"}},"offenderReleaseDetails":{"*":{"movement_date":"body.prisonerDetails.imprisonmentDetails.releaseDateTime","movement_reason_code":"body.prisonerDetails.imprisonmentDetails.releaseReason"}},"offenderProfileDetails":{"*":{"nationality":"body.prisonerDetails.demographics.nationality","ethnicity":"body.prisonerDetails.demographics.ethnicity","religion":"body.prisonerDetails.demographics.religion"}}}},{"operation":"modify-default-beta","spec":{"body":{"prisonerDetails":{"financials":{"transactionSpendLimit":"TBD"},"imprisonmentDetails":{"releaseDateTime":"","releaseReason":""},"alerts":[]}}}},{"operation":"default","spec":{"header":{"intId":"UnilinkADMI"}}}]',
    modify_datetime = current_timestamp,
    modify_user_id = 'OMS_OWNER'
where
    spec_key = 'PRISONER_ADMISSION_FORMATTER';

update	
	json_spec
set
	json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.releasedPrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.releasedPrisonerDetails[#2].demographics.firstName","middle_name":"body.releasedPrisonerDetails[#2].demographics.middleName","second_middle_name":"body.releasedPrisonerDetails[#2].demographics.secondMiddleName","last_name":"body.releasedPrisonerDetails[#2].demographics.surName","sex_code":"body.releasedPrisonerDetails[#2].demographics.gender","birth_date":"body.releasedPrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_begin_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime"}},"offenderAddresses":{"*":{"address_line1":"body.releasedPrisonerDetails[#2].address.address_line","street":"body.releasedPrisonerDetails[#2].address.street","street_number":"body.releasedPrisonerDetails[#2].address.street_number","street_direction":"body.releasedPrisonerDetails[#2].address.street_direction","suite_number":"body.releasedPrisonerDetails[#2].address.suite_number","city":"body.releasedPrisonerDetails[#2].address.city_name","city_code":"body.releasedPrisonerDetails[#2].address.city_code","state_code":"body.releasedPrisonerDetails[#2].address.state_code","country_code":"body.releasedPrisonerDetails[#2].address.country_code","postal":"body.releasedPrisonerDetails[#2].address.postal_code","address":"body.releasedPrisonerDetails[#2].address.unstructured_address_line","no_fixed_address_flag":"body.releasedPrisonerDetails[#2].address.no_address_flag"}},"offNextCourtDate":{"*":{"event_date":"body.releasedPrisonerDetails[#2].appearance.nextCourtDate"}},"section68Details":{"*":{"section68":"body.releasedPrisonerDetails[#2].sentence.section68Flag"}},"homeDestinationDetails":{"*":{"homedestination":"body.releasedPrisonerDetails[#2].sentence.homeDetentionFlag"}},"releaseDates":{"*":{"expected_release_date":"body.releasedPrisonerDetails[#2].sentence.expectedReleaseDate"}},"releaseDetails":{"*":{"release_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.release_date"}}}},{"operation":"default","spec":{"header":{"intId":"UpdatedOffenderDetails"}}},{"operation":"modify-default-beta","spec":{"body":{"releasedPrisonerDetails":{"*":{"demographics":{"otherName":"TBD","aboriginalIndicator":"TBD"},"sentence":{"courtFileNumber":"TBD","lifeImprisonmentFlag":"TBD","fineAmount":"TBD"}}}}}}]',
	modify_datetime = current_timestamp,
	modify_user_id = 'OMS_OWNER'
where
	spec_key = 'UPDATED_RELEASE_OFF_FORMATTER';


update	
	json_spec
set
	json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.activePrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.activePrisonerDetails[#2].demographics.firstName","middle_name":"body.activePrisonerDetails[#2].demographics.middleName","second_middle_name":"body.activePrisonerDetails[#2].demographics.secondMiddleName","last_name":"body.activePrisonerDetails[#2].demographics.surName","sex_code":"body.activePrisonerDetails[#2].demographics.gender","birth_date":"body.activePrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_begin_date":"body.activePrisonerDetails[#2].imprisonmentDetails.intakeDatetime"}},"offenderAddresses":{"*":{"address_line1":"body.activePrisonerDetails[#2].address.address_line","street":"body.activePrisonerDetails[#2].address.street","street_number":"body.activePrisonerDetails[#2].address.street_number","street_direction":"body.activePrisonerDetails[#2].address.street_direction","suite_number":"body.activePrisonerDetails[#2].address.suite_number","city":"body.activePrisonerDetails[#2].address.city_name","city_code":"body.activePrisonerDetails[#2].address.city_code","state_code":"body.activePrisonerDetails[#2].address.state_code","country_code":"body.activePrisonerDetails[#2].address.country_code","postal":"body.activePrisonerDetails[#2].address.postal_code","address":"body.activePrisonerDetails[#2].address.unstructured_address_line","no_fixed_address_flag":"body.activePrisonerDetails[#2].address.no_address_flag"}},"offNextCourtDate":{"*":{"event_date":"body.activePrisonerDetails[#2].appearance.nextCourtDate"}},"section68Details":{"*":{"section68":"body.activePrisonerDetails[#2].sentence.section68Flag"}},"homeDestinationDetails":{"*":{"homedestination":"body.activePrisonerDetails[#2].sentence.homeDetentionFlag"}},"releaseDates":{"*":{"expected_release_date":"body.activePrisonerDetails[#2].sentence.expectedReleaseDate"}}}},{"operation":"default","spec":{"header":{"intId":"UpdatedOffenderDetails"}}},{"operation":"modify-default-beta","spec":{"body":{"activePrisonerDetails":{"*":{"demographics":{"otherName":"TBD","aboriginalIndicator":"TBD"},"sentence":{"courtFileNumber":"TBD","lifeImprisonmentFlag":"TBD","fineAmount":"TBD"}}}}}}]',
	modify_datetime = current_timestamp,
	modify_user_id = 'OMS_OWNER'
where
	spec_key = 'UPDATED_ACTIVE_OFF_FORMATTER';
	
update
    json_spec
set
    json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"first_name":"body.prisonerDetails[#2].demographics.firstName","last_name":"body.prisonerDetails[#2].demographics.surName","middle_name":"body.prisonerDetails[#2].demographics.middleName","second_middle_name":"body.prisonerDetails[#2].demographics.secondMiddleName","sex_code":"body.prisonerDetails[#2].demographics.gender","birth_date":"body.prisonerDetails[#2].demographics.dob","offender_id_display":"body.prisonerDetails[#2].imprisonmentDetails.dcsId"}},"offenderBookingDetails":{"*":{"booking_no":"body.prisonerDetails[#2].imprisonmentDetails.imprisonmentId","booking_begin_date":"body.prisonerDetails[#2].imprisonmentDetails.intakeDate","booking_status":"body.prisonerDetails[#2].imprisonmentDetails.imprisonmentStatus","agy_loc_id":"body.prisonerDetails[#2].housing.facility"}},"offenderHousingDetails":{"*":{"housing_lev_1_code":"body.prisonerDetails[#2].housing.pod","housing_lev_2_code":"body.prisonerDetails[#2].housing.unit","housing_lev_3_code":"body.prisonerDetails[#2].housing.cell","iep_level":"body.prisonerDetails[#2].housing.regime"}},"warnings":{"*":{"description":"body.prisonerDetails[#4].alerts[#2].alertCode","createdate":"body.prisonerDetails[#4].alerts[#2].alertStartDate","expirydate":"body.prisonerDetails[#4].alerts[#2].alertEndDate","comment_text":"body.prisonerDetails[#4].alerts[#2].alertComment"}},"offenderFinancialDetails":{"*":{"current_balance":"body.prisonerDetails[#2].financials.accountBalance","balance":"body.prisonerDetails[#2].financials.resettlementAccountBalance","apply_spending_limit_amount":"body.prisonerDetails[#2].financials.transactionSpendLimit"}},"offenderReleaseDetails":{"*":{"movement_date":"body.prisonerDetails[#2].imprisonmentDetails.releaseDateTime","movement_reason_code":"body.prisonerDetails[#2].imprisonmentDetails.releaseReason"}},"offenderProfileDetails":{"*":{"nationality":"body.prisonerDetails[#2].demographics.nationality","ethnicity":"body.prisonerDetails[#2].demographics.ethnicity","religion":"body.prisonerDetails[#2].demographics.religion"}}}},{"operation":"modify-default-beta","spec":{"body":{"prisonerDetails":{"*":{"housing":{"regime":" "},"imprisonmentDetails":{"releaseDateTime":"","releaseReason":""},"alerts":[],"demographics":{"nationality":[""],"ethnicity":[""],"religion":[""]}}}}}},{"operation":"default","spec":{"header":{"intId":"UnilinkPRDE"},"body":{"prisonerDetails":{"*":{"demographics":{"nationality":[],"ethnicity":[],"religion":[]}}}}}}]',
    modify_datetime = current_timestamp,
    modify_user_id = 'OMS_OWNER'
where
    spec_key = 'PRISONER_DETAILS_FORMATTER';	