
OTDCLINA_FIND_SELECTMETHODRG {
 	SELECT DESCRIPTION , CODE FROM REFERENCE_CODES WHERE DOMAIN = 'SELECT_METH' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OTDCLINA_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}
OTDCLINA_SYSPFL_INSERT_SYSTEM_PROFILES {
	INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:profileType ,:profileCode ,:description ,:profileValue ,:profileValue2 ,:modifyUserId ,:oldTableName ,CURRENT_TIMESTAMP ,:createUserId ,CURRENT_TIMESTAMP ,:sealFlag )
}

OTDCLINA_SYSPFL_UPDATE_SYSTEM_PROFILES {
	UPDATE SYSTEM_PROFILES set PROFILE_TYPE  = :profileType ,PROFILE_CODE  = :profileCode ,DESCRIPTION  = :description ,PROFILE_VALUE  = :profileValue ,PROFILE_VALUE_2  = :profileValue2 ,MODIFY_USER_ID  = :modifyUserId ,OLD_TABLE_NAME  = :oldTableName ,CREATE_DATETIME  = CURRENT_TIMESTAMP ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,SEAL_FLAG  = :sealFlag /* where */
}

OTDCLINA_SYSPFL_DELETE_SYSTEM_PROFILES { 
	DELETE FROM SYSTEM_PROFILES/* where */
}

OTDCLINA_OFFTRAC_FIND_OFFENDER_TRUST_ACCOUNTS_TEMP {
 	SELECT CASELOAD_ID ,OFFENDER_ID ,SESSION_ID ,ACCOUNT_CLOSED_FLAG ,HOLD_BALANCE ,CURRENT_BALANCE ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,NOTIFY_DATE ,OFFENDER_BOOK_ID ,LAST_NAME ,FIRST_NAME ,MOVEMENT_DATE ,AGY_LOC_ID ,OFFENDER_ID_DISPLAY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM OFFENDER_TRUST_ACCOUNTS_TEMP   where  SESSION_ID = :sessionId  order by MOVEMENT_DATE, LAST_NAME
}
OTDCLINA_OFFTRAC_INSERT_OFFENDER_TRUST_ACCOUNTS_TEMP {
	INSERT INTO OFFENDER_TRUST_ACCOUNTS_TEMP(CASELOAD_ID ,OFFENDER_ID ,SESSION_ID ,ACCOUNT_CLOSED_FLAG ,HOLD_BALANCE ,CURRENT_BALANCE ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,NOTIFY_DATE ,OFFENDER_BOOK_ID ,LAST_NAME ,FIRST_NAME ,MOVEMENT_DATE ,AGY_LOC_ID ,OFFENDER_ID_DISPLAY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:caseloadId ,:offenderId ,:sessionId ,:accountClosedFlag ,:holdBalance ,:currentBalance ,:modifyDate ,:modifyUserId ,:listSeq ,:notifyDate ,:offenderBookId ,:lastName ,:firstName ,:movementDate ,:agyLocId ,:offenderIdDisplay ,CURRENT_TIMESTAMP ,:createUserId ,CURRENT_TIMESTAMP ,:sealFlag )
}

OTDCLINA_OFFTRAC_UPDATE_OFFENDER_TRUST_ACCOUNTS_TEMP {
	UPDATE OFFENDER_TRUST_ACCOUNTS_TEMP set CASELOAD_ID  = :caseloadId ,OFFENDER_ID  = :offenderId ,SESSION_ID  = :sessionId ,ACCOUNT_CLOSED_FLAG  = :accountClosedFlag ,HOLD_BALANCE  = :holdBalance ,CURRENT_BALANCE  = :currentBalance ,MODIFY_DATE  = :modifyDate ,MODIFY_USER_ID  = :modifyUserId ,LIST_SEQ  = :listSeq ,NOTIFY_DATE  = :notifyDate ,OFFENDER_BOOK_ID  = :offenderBookId ,LAST_NAME  = :lastName ,FIRST_NAME  = :firstName ,MOVEMENT_DATE  = :movementDate ,AGY_LOC_ID  = :agyLocId ,OFFENDER_ID_DISPLAY  = :offenderIdDisplay ,CREATE_DATETIME  = CURRENT_TIMESTAMP ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,SEAL_FLAG  = :sealFlag  where CASELOAD_ID  = :caseloadId AND OFFENDER_ID  = :offenderId AND SESSION_ID  = :sessionId 
}


OTDCLINA_OFF_TRAC_KEYEXEQRYKEY-EXEQRY {
	SELECT COUNT(*) FROM OFFENDER_TRUST_ACCOUNTS_TEMP WHERE SESSION_ID = :SESSIONID
}

OTDCLINA_OFF_TRAC_KEYENTQRY {
	SELECT COUNT(*) FROM OFFENDER_TRUST_ACCOUNTS_TEMP WHERE SESSION_ID = :SESSIONID
}

OTDCLINA_OTDCLINA_KEYEXIT {
	DELETE OFFENDER_TRUST_ACCOUNTS_TEMP WHERE SESSION_ID  = LV_SESSION_ID AND CASELOAD_ID = :CASELOADID
}

OTDCLINA_OTDCLINA_WHENNEWFORMINSTANCE_ {
	SELECT USERENV('SESSIONID') FROM DUAL
}

OTDCLINA_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO   V_FORM_DESC FROM   OMS_MODULES WHERE  MODULE_NAME = V_FORM_NAME
}

OTDCLINA_CGRICHK_OFFENDER_TRUST_ACCOUN_ {
	SELECT  '1' FROM    OFFENDER_WORKS OFF_WRK WHERE   OFF_WRK.TRUST_CASELOAD_ID = P_CASELOAD_ID AND     OFF_WRK.OFFENDER_ID = P_OFFENDER_ID
}

OTDCLINA_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OTDCLINA_CLEAR_ZERO_BALANCE_ACCOUNTS_ {
	SELECT ROOT_OFFENDER_ID FROM OFFENDERS WHERE OFFENDER_ID = P_OFF_ID
}

OTDCLINA_CLEAR_ZERO_BALANCE_ACCOUNTS_ {
	SELECT SUBSTR ((FIRST_NAME || '  ' || LAST_NAME), 1, 45) FROM OFFENDERS OFF, OFFENDER_BOOKINGS OFF_BK WHERE OFF.ROOT_OFFENDER_ID = LV_ROOT_OFFENDER_ID AND OFF.ROOT_OFFENDER_ID = OFF_BK.ROOT_OFFENDER_ID AND OFF.OFFENDER_ID = OFF_BK.OFFENDER_ID AND OFF_BK.OFFENDER_BOOK_ID = (SELECT MAX (OFFENDER_BOOK_ID) FROM OFFENDER_BOOKINGS OFF_BK1 WHERE ROOT_OFFENDER_ID = LV_ROOT_OFFENDER_ID AND BOOKING_TYPE = CSLD_TYPE) AND BOOKING_TYPE = CSLD_TYPE
}

OTDCLINA_CLEAR_ZERO_BALANCE_ACCOUNTS_ {
	SELECT DESCRIPTION FROM TRANSACTION_TYPES WHERE TXN_TYPE =T_TXN
}

OTDCLINA_CLOSE_ACCOUNT {
	SELECT ROOT_OFFENDER_ID FROM OFFENDERS WHERE OFFENDER_ID = :POFFID
}

OTDCLINA_CLOSE_ACCOUNT_ROOT_OFFENDER_ID_C {
	SELECT MAX(TXN_ID) FROM GL_TRANSACTIONS
}

OTDCLINA_ZERO_AMOUNTZERO_AMOUNT {
	SELECT ACCOUNT_CODE INTO P_TRUST_ACCOUNT_CODE FROM ACCOUNT_CODES WHERE SUB_ACCOUNT_TYPE = P_SUB_AC_TYPE AND CASELOAD_TYPE = CSLD_TYPE  --@@@ PETER 05-SEP-1999
}

OTDCLINA_CLEAR_INACTIVE_ACCOUNTSCLEAR_INACTIVE_ACCOUNTS {
	SELECT MIN('X') FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B WHERE A.OFFENDER_ID = P_OFFENDER_ID AND A.CASELOAD_ID = :GLOBAL.CASELOAD_ID AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE AND A.TRUST_ACCOUNT_CODE IN ( SELECT DR_ACCOUNT_CODE FROM TRANSACTION_OPERATIONS WHERE CASELOAD_ID = :GLOBAL.CASELOAD_ID AND MODULE_NAME = 'OTDCLINA') AND B.CASELOAD_TYPE = LV_CSLD_TYPE AND A.BALANCE < 0
}

OTDCLINA_CHECK_BALANCE_TALLY_ {
	SELECT SUM(BALANCE) FROM OFFENDER_SUB_ACCOUNTS WHERE OFFENDER_ID = P_OFFENDER_ID AND CASELOAD_ID = :CASELOADID AND TRUST_ACCOUNT_CODE IN ( SELECT DR_ACCOUNT_CODE FROM TRANSACTION_OPERATIONS WHERE CASELOAD_ID = :CASELOADID AND MODULE_NAME = 'OTDCLINA')
}

OTDCLINA_CHECK_SETUP_BEFORE_TRANSFER {
	SELECT COUNT(TXN_TYPE) FROM TRANSACTION_OPERATIONS WHERE MODULE_NAME = 'OTDCLINA' AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
}

OTDCLINA_CHECK_LOCK {
	SELECT 'Y' FROM LOCKED_MODULES WHERE MODULE_NAME = 'OTDCLINA' AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
}

OTDCLINA_TRANSFER_FUNDS_TO_PRO_PER_ {
	SELECT ROOT_OFFENDER_ID FROM OFFENDERS WHERE OFFENDER_ID = P_OFF_ID
}

OTDCLINA_TRANSFER_FUNDS_TO_PRO_PER_ {
	SELECT SUBSTR ((FIRST_NAME || '  ' || LAST_NAME), 1, 45) FROM OFFENDERS OFF, OFFENDER_BOOKINGS OFF_BK WHERE OFF.ROOT_OFFENDER_ID = LV_ROOT_OFFENDER_ID AND OFF.ROOT_OFFENDER_ID = OFF_BK.ROOT_OFFENDER_ID AND OFF.OFFENDER_ID = OFF_BK.OFFENDER_ID AND OFF_BK.OFFENDER_BOOK_ID = (SELECT MAX (OFFENDER_BOOK_ID) FROM OFFENDER_BOOKINGS OFF_BK1 WHERE ROOT_OFFENDER_ID = LV_ROOT_OFFENDER_ID AND BOOKING_TYPE = CSLD_TYPE) AND BOOKING_TYPE = CSLD_TYPE
}

OTDCLINA_TRANSFER_FUNDS_TO_PRO_PER_ {
	SELECT A.TRUST_ACCOUNT_CODE, A.BALANCE, B.SUB_ACCOUNT_TYPE FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B WHERE OFFENDER_ID = LV_ROOT_OFFENDER_ID AND CASELOAD_ID = P_CSLD_ID AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE AND B.SUB_ACCOUNT_TYPE <> 'REG' AND A.TRUST_ACCOUNT_CODE IN (SELECT DR_ACCOUNT_CODE FROM TRANSACTION_OPERATIONS WHERE CASELOAD_ID = P_CSLD_ID AND MODULE_NAME = 'OTDCLINA' AND TXN_TYPE = 'PROP') AND B.CASELOAD_TYPE = CSLD_TYPE
}
OTDCLINA_OFFENDER_TRUST_ACCOUNTS {
UPDATE Offender_Trust_Accounts
         SET Notify_Date = :NOTIFYDATE,
         modify_user_id = :modifyUserId,
	     modify_datetime = current_timestamp
       WHERE Offender_Id = :OFFENDERID
         AND Caseload_Id = :CASELOADID
}
OTDCLINA_OFFENDER_SUB_ACCOUNTS_MAX {
SELECT MIN('X')
        FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B
       WHERE A.OFFENDER_ID = :OFFENDERID
         AND A.CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
         AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE
         AND A.TRUST_ACCOUNT_CODE IN ( SELECT DR_ACCOUNT_CODE
                                         FROM TRANSACTION_OPERATIONS
                                        WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
                                          AND MODULE_NAME = 'OTDCLINA') 
         AND B.CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))
         AND a.balance < 0
}
OTDCLINA_SUM_BALANCE {
SELECT SUM(BALANCE)
        FROM OFFENDER_SUB_ACCOUNTS
       WHERE OFFENDER_ID = :OFFENDERID
         AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
         AND TRUST_ACCOUNT_CODE IN ( SELECT DR_ACCOUNT_CODE
                                       FROM TRANSACTION_OPERATIONS
                                      WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
                                        AND MODULE_NAME = 'OTDCLINA')
}
OTDCLINA_ROOT_OFFENDER_ID {
SELECT ROOT_OFFENDER_ID
        FROM OFFENDERS
       WHERE OFFENDER_ID = :OFFID
}
OTDCLINA_FIRST_NAME_LAST_NAME {
SELECT SUBSTR ((FIRST_NAME || '  ' || LAST_NAME), 1, 45)
        FROM OFFENDERS OFF, OFFENDER_BOOKINGS OFF_BK
       WHERE OFF.ROOT_OFFENDER_ID = :ROOTOFFENDERID
         AND OFF.ROOT_OFFENDER_ID = OFF_BK.ROOT_OFFENDER_ID
         AND OFF.OFFENDER_ID = OFF_BK.OFFENDER_ID
         AND OFF_BK.OFFENDER_BOOK_ID =
                (SELECT MAX (OFFENDER_BOOK_ID)
                   FROM OFFENDER_BOOKINGS OFF_BK1
                  WHERE ROOT_OFFENDER_ID = :ROOTOFFENDERID
                    AND BOOKING_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)))
         AND BOOKING_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))
}
OTDCLINA_DESCRIPTION_TXNTYPE {
SELECT DESCRIPTION    
		 FROM TRANSACTION_TYPES
    WHERE TXN_TYPE = :TXNTYPE
}
OTDCLINA_TXN_ID {
	SELECT NEXTVAL('TXN_ID') FROM DUAL
}
OTDCLINA_UPDATE_OFFENDER_TRANSACTIONS {
UPDATE OFFENDER_TRANSACTIONS
         SET TXN_ADJUSTED_FLAG = 'N',
             HOLD_CLEAR_FLAG = 'N',
             MODIFY_DATE =  CURRENT_TIMESTAMP,
             MODIFY_USER_ID = :MODIFYUSERID,
             PAYEE_CODE = :PPAYEECODE,
             PAYEE_NAME_TEXT = :LVPAYEENAME,
             MODIFY_DATETIME = CURRENT_TIMESTAMP
       WHERE TXN_ID = :PTXNNUM
         AND TXN_ENTRY_SEQ = :PTXNENTRYSEQ
}
OTDCLINA_TRUST_ACCOUNT_CODE {
SELECT ACCOUNT_CODE
     FROM ACCOUNT_CODES
    WHERE SUB_ACCOUNT_TYPE = :PSUBACTYPE
      AND CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))
}
OTDCLINA_OFFENDER_SUB_ACCOUNTS_BALANCE {
UPDATE OFFENDER_SUB_ACCOUNTS 
      SET BALANCE        = 0 ,
          LAST_TXN_ID    = :PTXNNUM,
          LIST_SEQ       = :PTXNENTRYSEQ,
		   	  MODIFY_DATE    = CURRENT_TIMESTAMP,
	        MODIFY_USER_ID = :MODIFYUSERID
    WHERE CASELOAD_ID = :PCSLDID 
      AND OFFENDER_ID = :POFFID	
      AND TRUST_ACCOUNT_CODE = :PTRUSTACCOUNTCODE
}
OTDCLINA_OFFENDER_TRUST_ACCOUNTS_Y {
UPDATE OFFENDER_TRUST_ACCOUNTS
      SET ACCOUNT_CLOSED_FLAG = 'Y',
      MODIFY_USER_ID = :USERID,
      MODIFY_DATETIME = CURRENT_TIMESTAMP 
    WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USERID)
      AND OFFENDER_ID = :LVROOTOFFENDERID
}
OTDCLINA_SESSIONID_COUNT {
SELECT COUNT(*)
     FROM OFFENDER_TRUST_ACCOUNTS_TEMP
    WHERE SESSION_ID = (SELECT USERENV('SESSIONID') FROM DUAL)
}
OTDCLINA_TRUST_ACCOUNT_CODE_BALANCE {
SELECT A.TRUST_ACCOUNT_CODE, A.BALANCE, B.SUB_ACCOUNT_TYPE MODIFY_USER_ID
          FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B
         WHERE OFFENDER_ID = :ROOTOFFENDERID
           AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
           AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE
           AND B.SUB_ACCOUNT_TYPE  <> 'REG'   
           AND A.TRUST_ACCOUNT_CODE IN ( SELECT DR_ACCOUNT_CODE
                                           FROM TRANSACTION_OPERATIONS
                                          WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
                                            AND MODULE_NAME = 'OTDCLINA'
                                            AND TXN_TYPE = 'OT' )
           AND B.CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))
}
OTDCLINA_UPDATE_OFFENDER_TRANSACTIONS_TRANSFER {
UPDATE OFFENDER_TRANSACTIONS
        	  SET TXN_ADJUSTED_FLAG = 'N',
	              HOLD_CLEAR_FLAG   = 'N',
        	      MODIFY_DATE       = current_timestamp,
	              MODIFY_USER_ID    = :USERID,
	              PAYEE_NAME_TEXT   = :LVPAYEENAME 
	        WHERE TXN_ID 	   = :PTXNNUM
                  AND TXN_ENTRY_SEQ     = :PTXNENTRYSEQ
}
OTDCLINA_TRUST_ACCOUNT_CODE_BALANCE_PROP {
SELECT A.TRUST_ACCOUNT_CODE, A.BALANCE, B.SUB_ACCOUNT_TYPE MODIFY_USER_ID
           FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B
          WHERE OFFENDER_ID = :ROOTOFFENDERID
            AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
            AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE
            AND B.SUB_ACCOUNT_TYPE <> 'REG'
            AND A.TRUST_ACCOUNT_CODE IN (SELECT DR_ACCOUNT_CODE
                                           FROM TRANSACTION_OPERATIONS
                                          WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
                                            AND MODULE_NAME = 'OTDCLINA'
                                            AND TXN_TYPE = 'PROP')
            AND B.CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))
}
OTDCLINA_TRUST_ACCOUNT_CODE_BALANCE_REG {
SELECT A.TRUST_ACCOUNT_CODE, A.BALANCE, B.SUB_ACCOUNT_TYPE
          FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B
         WHERE OFFENDER_ID = :ROOTOFFENDERID
           AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)
           AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE
           AND B.SUB_ACCOUNT_TYPE   = 'REG'
           AND B.CASELOAD_TYPE      = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))
}
OTDCLINA_SUM_BALANCE_TEMP {
SELECT SUM(BALANCE)
          FROM OFFENDER_SUB_ACCOUNTS
         WHERE OFFENDER_ID = :ROOTOFFENDERID
           AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USERID)
}
OTDCLINA_OFFENDER_TRUST_ACCOUNTS_BALANCE {
UPDATE OFFENDER_TRUST_ACCOUNTS
            SET CURRENT_BALANCE = :LVBALANCE,
            MODIFY_USER_ID = :USERID,
            MODIFY_DATETIME = CURRENT_TIMESTAMP
          WHERE OFFENDER_ID = :ROOTOFFENDERID
            AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USERID)
}
GET_OLD_RECORDS_SYSTEMPROFILES {
select * from system_profiles where profile_type=:profile_type and profile_code=:profile_code
}