
OTDCLOSE_FIND_CGFKOFFTXNPAYEECODE {
 	SELECT REF_CODE.CODE /* CG$FK */  ,REF_CODE.DOMAIN  ,REF_CODE.DESCRIPTION FROM REFERENCE_CODES REF_CODE WHERE DOMAIN= 'PAYEE_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OTDCLOSE_OFFSUBA_FIND_OFFENDER_SUB_ACCOUNTS {
 	SELECT CASELOAD_ID ,OFFENDER_ID ,TRUST_ACCOUNT_CODE ,BALANCE ,MINIMUM_BALANCE ,HOLD_BALANCE ,LAST_TXN_ID ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,IND_DATE ,IND_DAYS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM OFFENDER_SUB_ACCOUNTS  /* where  */
}
OTDCLOSE_OFFSUBA_INSERT_OFFENDER_SUB_ACCOUNTS {
	INSERT INTO OFFENDER_SUB_ACCOUNTS(CASELOAD_ID ,OFFENDER_ID ,TRUST_ACCOUNT_CODE ,BALANCE ,MINIMUM_BALANCE ,HOLD_BALANCE ,LAST_TXN_ID ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,IND_DATE ,IND_DAYS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:caseloadId ,:offenderId ,:trustAccountCode ,:balance ,:minimumBalance ,:holdBalance ,:lastTxnId ,:modifyDate ,:modifyUserId ,:listSeq ,:indDate ,:indDays ,current_timestamp ,:createUserId ,:modifyDatetime ,:sealFlag )
}

OTDCLOSE_OFFSUBA_UPDATE_OFFENDER_SUB_ACCOUNTS {
	UPDATE OFFENDER_SUB_ACCOUNTS set CASELOAD_ID  = :caseloadId ,OFFENDER_ID  = :offenderId ,TRUST_ACCOUNT_CODE  = :trustAccountCode ,BALANCE  = :balance ,MINIMUM_BALANCE  = :minimumBalance ,HOLD_BALANCE  = :holdBalance ,LAST_TXN_ID  = :lastTxnId ,MODIFY_DATE  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId ,LIST_SEQ  = :listSeq ,IND_DATE  = :indDate ,IND_DAYS  = :indDays ,CREATE_DATETIME  = :createDatetime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,SEAL_FLAG  = :sealFlag /* where */
}

OTDCLOSE_OFFSUBA_DELETE_OFFENDER_SUB_ACCOUNTS { 
	DELETE FROM OFFENDER_SUB_ACCOUNTS/* where */
}

OTDCLOSE_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 	SELECT TXN_ID ,TXN_ENTRY_SEQ ,CASELOAD_ID ,OFFENDER_ID ,OFFENDER_BOOK_ID ,TXN_POSTING_TYPE ,TXN_TYPE ,TXN_ENTRY_DESC ,TXN_ENTRY_AMOUNT ,TXN_ENTRY_DATE ,SUB_ACCOUNT_TYPE ,TXN_REFERENCE_NUMBER ,MODIFY_DATE ,RECEIPT_NUMBER ,SLIP_PRINTED_FLAG ,TRANSFER_CASELOAD_ID ,RECEIPT_PRINTED_FLAG ,PRE_WITHHOLD_AMOUNT ,DEDUCTION_FLAG ,CLOSING_CHEQUE_NUMBER ,REMITTER_NAME ,PAYEE_CODE ,PAYEE_NAME_TEXT ,PAYEE_CORPORATE_ID ,PAYEE_PERSON_ID ,ADJUST_TXN_ID ,ADJUST_TXN_ENTRY_ID ,ADJUST_OFFENDER_ID ,ADJUST_ACCOUNT_CODE ,TXN_ADJUSTED_FLAG ,DEDUCTION_TYPE ,INFO_NUMBER ,HOLD_CLEAR_FLAG ,HOLD_UNTIL_DATE ,HOLD_NUMBER ,GROSS_AMOUNT ,GROSS_NET_FLAG ,REMITTER_ID ,APPLY_SPENDING_LIMIT_AMOUNT ,RECEIPT_PENDING_PRINT_FLAG ,SEAL_FLAG ,ORG_TXN_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_TRANSACTIONS  /* where  */
}
OTDCLOSE_OFFTXN_INSERT_OFFENDER_TRANSACTIONS {
	INSERT INTO OFFENDER_TRANSACTIONS(TXN_ID ,TXN_ENTRY_SEQ ,CASELOAD_ID ,OFFENDER_ID ,OFFENDER_BOOK_ID ,TXN_POSTING_TYPE ,TXN_TYPE ,TXN_ENTRY_DESC ,TXN_ENTRY_AMOUNT ,TXN_ENTRY_DATE ,SUB_ACCOUNT_TYPE ,TXN_REFERENCE_NUMBER ,MODIFY_DATE ,RECEIPT_NUMBER ,SLIP_PRINTED_FLAG ,TRANSFER_CASELOAD_ID ,RECEIPT_PRINTED_FLAG ,PRE_WITHHOLD_AMOUNT ,DEDUCTION_FLAG ,CLOSING_CHEQUE_NUMBER ,REMITTER_NAME ,PAYEE_CODE ,PAYEE_NAME_TEXT ,PAYEE_CORPORATE_ID ,PAYEE_PERSON_ID ,ADJUST_TXN_ID ,ADJUST_TXN_ENTRY_ID ,ADJUST_OFFENDER_ID ,ADJUST_ACCOUNT_CODE ,TXN_ADJUSTED_FLAG ,DEDUCTION_TYPE ,INFO_NUMBER ,HOLD_CLEAR_FLAG ,HOLD_UNTIL_DATE ,HOLD_NUMBER ,GROSS_AMOUNT ,GROSS_NET_FLAG ,REMITTER_ID ,APPLY_SPENDING_LIMIT_AMOUNT ,RECEIPT_PENDING_PRINT_FLAG ,SEAL_FLAG ,ORG_TXN_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ) VALUES(:txnId ,:txnEntrySeq ,:caseloadId ,:offenderId ,:offenderBookId ,:txnPostingType ,:txnType ,:txnEntryDesc ,:txnEntryAmount ,:txnEntryDate ,:subAccountType ,:txnReferenceNumber ,:modifyDate ,:receiptNumber ,:slipPrintedFlag ,:transferCaseloadId ,:receiptPrintedFlag ,:preWithholdAmount ,:deductionFlag ,:closingChequeNumber ,:remitterName ,:payeeCode ,:payeeNameText ,:payeeCorporateId ,:payeePersonId ,:adjustTxnId ,:adjustTxnEntryId ,:adjustOffenderId ,:adjustAccountCode ,:txnAdjustedFlag ,:deductionType ,:infoNumber ,:holdClearFlag ,:holdUntilDate ,:holdNumber ,:grossAmount ,:grossNetFlag ,:remitterId ,:applySpendingLimitAmount ,:receiptPendingPrintFlag ,:sealFlag ,:orgTxnType ,current_timestamp ,:createUserId ,current_timestamp ,:modifyUserId )
}

OTDCLOSE_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OTDCLOSE_CGFKCHK_OFF_TXN_OFF_TXN_REF_C_ {
	SELECT REF_CODE.DOMAIN ,REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :PAYEECODE AND     DOMAIN= 'PAYEE_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}
OTDCLOSE_GET_REG_BAL {
 SELECT SUM ( coalesce ( balance, 0 ) ) FROM offender_sub_accounts WHERE offender_id = :offenderId
      AND caseload_id = :caseloadId  AND trust_account_code IN ( SELECT dr_account_code
                                    FROM transaction_operations
                                   WHERE caseload_id = :caseloadId
                                     AND module_name = 'OTDCLOSE' 
                                     AND txn_type != 'PROP')
}
OTDCLOSE_ACCOUNT_NAME_FOR_VALIDATION {
SELECT ACCOUNT_NAME
        FROM ACCOUNT_CODES 
       WHERE SUB_ACCOUNT_TYPE = 'REG'
}
OTDCLOSE_P_CACH {
	SELECT DISTINCT 'Y' FROM TRANSACTION_OPERATIONS
                      WHERE MODULE_NAME = 'OTDCLOSE'
                        AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_ID)
                        AND TXN_OPERATION_TYPE = 'CASH'
}
OTDCLOSE_P_CHECK {
	SELECT DISTINCT 'Y' FROM TRANSACTION_OPERATIONS
                      WHERE MODULE_NAME = 'OTDCLOSE'
                        AND CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_ID)
                        AND TXN_OPERATION_TYPE = 'CHECK'
}
OTDCLOSE_ACCOUNT_CLOSED_FLAG {
SELECT ACCOUNT_CLOSED_FLAG
        FROM OFFENDER_TRUST_ACCOUNTS
       WHERE CASELOAD_ID = :PCSLD
         AND OFFENDER_ID = :POFFID
         AND ACCOUNT_CLOSED_FLAG = 'Y'
}
OTDCLOSE_OFFENDER_FOREIGN_CURRENCIES {
SELECT count(*)
    FROM OFFENDER_FOREIGN_CURRENCIES
   WHERE CASELOAD_ID = :PCSLD 
     AND OFFENDER_ID = :POFFID
     AND CURRENCY_CONVERTED_FLAG = 'N'
}
OTDCLOSE_HOLD_DATA_COUNT {
SELECT coalesce(HOLD_BALANCE,0)
  FROM OFFENDER_TRUST_ACCOUNTS
  WHERE CASELOAD_ID =:PCSLD 
  AND   OFFENDER_ID =:POFFID
}
OTDCLOSE_TRUST_ACCOUNT_CODE_BALANCE {
SELECT A.TRUST_ACCOUNT_CODE, A.BALANCE, B.SUB_ACCOUNT_TYPE 
         FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B
        WHERE OFFENDER_ID = :POFFID
          AND CASELOAD_ID = :PCSLDID
          AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE
          AND A.TRUST_ACCOUNT_CODE IN ( SELECT DR_ACCOUNT_CODE
                                          FROM TRANSACTION_OPERATIONS
                                         WHERE CASELOAD_ID = :PCSLDID
                                           AND MODULE_NAME = 'OTDCLOSE'
                                           AND TXN_TYPE = 'OT' )
}
OTDCLOSE_TXN_ID {
	SELECT NEXTVAL('TXN_ID') FROM DUAL
}
OTDCLOSE_INSERT_INTO_OFFENDER_TRANSACTIONS {
INSERT INTO OFFENDER_TRANSACTIONS   (TXN_ID, 
				        TXN_ENTRY_SEQ, 
					CASELOAD_ID, 
					OFFENDER_ID, 
					OFFENDER_BOOK_ID, 
					TXN_POSTING_TYPE, 
					TXN_TYPE, 
					TXN_ENTRY_DESC, 
					TXN_ENTRY_AMOUNT,
					TXN_ENTRY_DATE,
					SUB_ACCOUNT_TYPE, 
					MODIFY_DATE, 
					MODIFY_USER_ID, 
					SLIP_PRINTED_FLAG, 
					TXN_ADJUSTED_FLAG, 
					HOLD_CLEAR_FLAG,
					PAYEE_CODE,
					PAYEE_CORPORATE_ID,
					PAYEE_PERSON_ID,
					CREATE_USER_ID,
					CREATE_DATETIME,
					MODIFY_DATETIME)
    VALUES     (:PTRANSNUMBER,
	        :PTXNENTRYSEQ,  
		:PCSLDID, 
		:ROOTOFFID,
		:POFFBOOKID, 
		:PTXNPTGTYPE, 
		:PTXNTYPE, 	 			    		  	
		:PTXNDESC, 
 		:PTXNAMOUNT, 
		date_TRUNC('day', CURRENT_TIMESTAMP),
		:PSUBACTYPE, 
		date_TRUNC('day',CURRENT_TIMESTAMP),
		:PMODFYUSERID,
		:PSLIPPRFLAG, 
		:PTXNADJFLAG,
		:PHOLDCLFLAG,
		:PPAYEECODE,
		:PCORPORATEID,
		:PPERSONID,
		:createUserId,
		current_timestamp,
		current_timestamp)
}
OTDCLOSE_P_TRUST_ACCOUNT_CODE {
SELECT ACCOUNT_CODE 
    FROM ACCOUNT_CODES
    WHERE SUB_ACCOUNT_TYPE = :PSUBACTYPE
    AND   CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN 
    (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_ID))
}

OTDCLOSE_FIRST_NAME_LAST_NAME {
SELECT SUBSTR ((FIRST_NAME || '  ' || LAST_NAME), 1, 45)
        FROM OFFENDERS OFF, OFFENDER_BOOKINGS OFF_BK
       WHERE OFF.ROOT_OFFENDER_ID = :ROOTOFFENDERID
         AND OFF.ROOT_OFFENDER_ID = OFF_BK.ROOT_OFFENDER_ID
         AND OFF.OFFENDER_ID = OFF_BK.OFFENDER_ID
         AND OFF_BK.OFFENDER_BOOK_ID =
                (SELECT MAX (OFFENDER_BOOK_ID)
                   FROM OFFENDER_BOOKINGS OFF_BK1
                  WHERE ROOT_OFFENDER_ID = :ROOTOFFENDERID
                    AND BOOKING_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN
                    (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_ID)))
         AND BOOKING_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN 
         (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_ID))
}
OTDCLOSE_TRUST_ACCOUNT_CODE_BALANCE_PROP {
SELECT A.TRUST_ACCOUNT_CODE, A.BALANCE, B.SUB_ACCOUNT_TYPE MODIFY_USER_ID
           FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B
          WHERE OFFENDER_ID = :ROOTOFFENDERID
            AND CASELOAD_ID = :PCSLDID
            AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE
            AND B.SUB_ACCOUNT_TYPE <> 'REG'
            AND A.TRUST_ACCOUNT_CODE IN (SELECT DR_ACCOUNT_CODE
                                           FROM TRANSACTION_OPERATIONS
                                          WHERE CASELOAD_ID = :PCSLDID
                                            AND MODULE_NAME = 'OTDCLOSE'
                                            AND TXN_TYPE = 'PROP')
            AND B.CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN
            (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_ID))
}
OTDCLOSE_UPDATE_OFFENDER_TRANSACTIONS_TRANSFER {
UPDATE OFFENDER_TRANSACTIONS
        	  SET TXN_ADJUSTED_FLAG = 'N',
	              HOLD_CLEAR_FLAG   = 'N',
        	      MODIFY_DATE       = TRUNC(SYSDATE),
	              MODIFY_USER_ID    = :modifyUserId,
	              PAYEE_NAME_TEXT   = :LVPAYEENAME 
	        WHERE TXN_ID 	   = :PTXNNUM
                  AND TXN_ENTRY_SEQ     = :PTXNENTRYSEQ
}
OTDCLOSE_P_PERSON_ID {
SELECT FIRST_NAME||'  '||LAST_NAME
       FROM PERSONS
      WHERE PERSON_ID = :PPERSONID
}
OTDCLOSE_P_CORPORATE_ID {
SELECT CORPORATE_NAME
       FROM CORPORATES
      WHERE CORPORATE_ID = :PCORPORATEID
}
OTDCLOSE_OFFENDER_TRUST_ACCOUNTS_Y {
UPDATE OFFENDER_TRUST_ACCOUNTS
      SET ACCOUNT_CLOSED_FLAG = 'Y' 
    WHERE CASELOAD_ID = :CASELOADID
      AND OFFENDER_ID = :LVROOTOFFENDERID
}
OTDCLOSE_CHK_CLOSED_ACCOUNT {
SELECT SUM(coalesce(balance,0)) 
        FROM offender_sub_accounts
       WHERE offender_id = :POFFID
         AND caseload_id = :PCSLD
         AND trust_account_code IN
           ( SELECT account_code 
               FROM account_codes
          WHERE caseload_type =
          (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_ID))
          AND   sub_account_type IN
                  ( SELECT code 
                      FROM reference_codes
                     WHERE domain = 'SUB_AC_TYPE'
                       AND parent_code IN('B','S')))
}
OTDCLOSE_CHK_SUB_ACCOUNT {
SELECT coalesce ( SUM(
coalesce(A.BALANCE, 0)),0 )
       FROM OFFENDER_SUB_ACCOUNTS A, ACCOUNT_CODES B
      WHERE OFFENDER_ID = :POFFID
        AND CASELOAD_ID = :PCSLD
        AND A.TRUST_ACCOUNT_CODE = B.ACCOUNT_CODE
        AND B.SUB_ACCOUNT_TYPE !='REG'
        AND A.TRUST_ACCOUNT_CODE  NOT IN 
          ( SELECT DR_ACCOUNT_CODE
              FROM TRANSACTION_OPERATIONS
             WHERE CASELOAD_ID = :PCSLD
               AND MODULE_NAME = 'OTDCLOSE'
               AND TXN_TYPE    = 'OT' )
}

OTDCLOSE_OFFENDER_SUB_ACCOUNTS_BALANCE {
UPDATE OFFENDER_SUB_ACCOUNTS 
      SET BALANCE        = 0 ,
          LAST_TXN_ID    = :PTXNNUM,
          LIST_SEQ       = :PTXNENTRYSEQ,
		   	  MODIFY_DATE    = current_date,
	        MODIFY_USER_ID = :modifyUserId
    WHERE CASELOAD_ID = :PCSLDID 
      AND OFFENDER_ID = :POFFID	
      AND TRUST_ACCOUNT_CODE = :PTRUSTACCOUNTCODE
}
