
OTDOFREZ_FIND_CGFKOFFFDFREEZEREASONCODE {
 	SELECT REF_CODE.CODE   ,REF_CODE.DESCRIPTION  FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'FREEZE_RSN'  AND
 (ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) 
}

OTDOFREZ_OFFFD_FIND_OFFENDER_FREEZE_DISBURSEMENTS {
 	SELECT OFFENDER_FREEZE_ID ,CASELOAD_ID ,OFFENDER_ID ,FROM_DATE ,TO_DATE ,FREEZE_REASON_CODE ,COMMENT_TEXT ,SEAL_FLAG ,REMOVED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_FREEZE_DISBURSEMENTS  WHERE CASELOAD_ID =:caseloadId  and OFFENDER_ID=:offenderId
ORDER BY to_date desc, CASE WHEN removed_flag = 'N' AND to_date >= SYSDATE() THEN 0 WHEN removed_flag = 'N' AND to_date < SYSDATE() THEN 1 WHEN removed_flag = 'Y' THEN 2 END
}
OTDOFREZ_OFFFD_INSERT_OFFENDER_FREEZE_DISBURSEMENTS {
	INSERT INTO OFFENDER_FREEZE_DISBURSEMENTS(OFFENDER_FREEZE_ID ,CASELOAD_ID ,OFFENDER_ID ,FROM_DATE ,TO_DATE ,FREEZE_REASON_CODE ,COMMENT_TEXT ,SEAL_FLAG ,REMOVED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME  ) VALUES(NEXTVAL('OFFENDER_FREEZE_ID') ,:caseloadId ,:offenderId ,:fromDate ,:toDate ,:freezeReasonCode ,:commentText ,:sealFlag ,:removedFlag ,current_timestamp ,:createUserId ,current_timestamp  )
}

OTDOFREZ_OFFFD_UPDATE_OFFENDER_FREEZE_DISBURSEMENTS {
	UPDATE  OFFENDER_FREEZE_DISBURSEMENTS set REMOVED_FLAG=:removedFlag,MODIFY_DATETIME=current_timestamp,modify_user_id =:modifyUserId where  OFFENDER_FREEZE_ID=:offenderFreezeId and CASELOAD_ID=:caseloadId
}
OTDOFREZ_OFF_BKG_DELETE_OFFENDER_FREEZE_DISBURSEMENTS {
	DELETE FROM OFFENDER_FREEZE_DISBURSEMENTS  WHERE OFFENDER_FREEZE_ID  = :offenderFreezeId AND  CASELOAD_ID = :caseloadId
}

OTDOFREZ_OFF_FD_PREINSERT_ {
--	SELECT  OFFENDER_FREEZE_ID.NEXTVAL FROM    SYS.DUAL
select nextval('OFFENDER_FREEZE_ID') 
}

OTDOFREZ_CGFKCHK_OFF_FD_OFF_FD_REF_COD_ {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :FREEZEREASONCODE AND     DOMAIN = 'FREEZE_RSN' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR :MODE != 'QUERY')
}

OTDOFREZ_OFFENDER_FREEZE_DISBURSEMENTS_PRE_INSERT {
SELECT COUNT(*) FROM OFFENDER_FREEZE_DISBURSEMENTS WHERE FROM_DATE=:FROM_DATE AND TO_DATE=:TO_DATE AND FREEZE_REASON_CODE=:FREEZE_REASON_CODE and CASELOAD_ID =:CASELOADID  and OFFENDER_ID=:OFFENDERID and REMOVED_FLAG = 'N'
}