
OTDOPCTA_OFFTA_FIND_OFFENDER_TRUST_ACCOUNTS {
 	SELECT CASELOAD_ID ,OFFENDER_ID ,ACCOUNT_CLOSED_FLAG ,HOLD_BALANCE ,CURRENT_BALANCE ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,NOTIFY_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM OFFENDER_TRUST_ACCOUNTS  /* where  */
}
OTDOPCTA_OFFTA_UPDATE_OFFENDER_TRUST_ACCOUNTS {
	UPDATE OFFENDER_TRUST_ACCOUNTS set ACCOUNT_CLOSED_FLAG  = :accountClosedFlag ,HOLD_BALANCE  = :holdBalance ,CURRENT_BALANCE  = :currentBalance ,MODIFY_DATE  = :modifyDate ,MODIFY_USER_ID  = :modifyUserId ,LIST_SEQ  = :listSeq ,NOTIFY_DATE  = :notifyDate ,CREATE_DATETIME  = :createDatetime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = :modifyDatetime ,SEAL_FLAG  = :sealFlag WHERE CASELOAD_ID  = :caseloadId and OFFENDER_ID  = :offenderId
}

OTDOPCTA_OFFTA_DELETE_OFFENDER_TRUST_ACCOUNTS { 
	DELETE FROM OFFENDER_TRUST_ACCOUNTS  where CASELOAD_ID  = :caseloadId  and OFFENDER_ID  = :offenderId
}

OTDOPCTA_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OTDOPCTA_CGWHEN_NEW_FORM_INSTANCE_ {
SELECT  current_timestamp, USER FROM dual;
}

OTDOPCTA_CGRICHK_OFFENDER_TRUST_ACCOUN {
	SELECT  '1' FROM    OFFENDER_SUB_ACCOUNTS OFF_SUB WHERE   OFF_SUB.CASELOAD_ID = :P_CASELOAD_ID AND     OFF_SUB.OFFENDER_ID = :P_OFFENDER_ID
}

OTDOPCTA_OFFENDER_TRUST_ACCOUNT_TXN_TYPE {
  SELECT TXN_TYPE    FROM TRANSACTION_OPERATIONS WHERE MODULE_NAME = :MODULENAME AND CASELOAD_ID = :CASELOADID
}

OTDOPCTA_ACCOUNT_CODES_TYPE {
SELECT sub_account_type,txn_posting_type
  FROM   account_codes
      WHERE  account_code = (SELECT cr_account_code
                               FROM transaction_operations
                              WHERE module_name =:MODULENAME
                                AND txn_type = :TXNTYPE
				AND caseload_id = :CASELOADID) 
      AND CASELOAD_TYPE = :CASELOADTYPE --('Error: unable to get the offender sub account type to credit.');
  }
  
OTDOPCTA_TXN_ID_SEQUENCE {
 SELECT NEXTVAL('TXN_ID') next_seq from dual
}

OTDOPCTA_UPDATE_OFFENDER_SUB_ACCOUNTS {
update offender_sub_accounts set ind_date = null, ind_days = null where offender_id = :OFFENDERID and caseload_id = :CASELOADID
}