
OTIDTACC_FIND_CALCACCOUNTBALANCES {
  SELECT  COALESCE ( SUM ( CASE  OFF_TXN.TXN_TYPE  WHEN 'HOA'  THEN  OFF_TXN.TXN_ENTRY_AMOUNT  WHEN 'HOR'  THEN  OFF_TXN.TXN_ENTRY_AMOUNT  ELSE 0  END * CASE  OFF_TXN.TXN_POSTING_TYPE  WHEN 'CR'  THEN  -1  ELSE 1  END  ) , 0  )  HOLD_BAL FROM OFFENDER_TRANSACTIONS OFF_TXN WHERE OFF_TXN.OFFENDER_ID = :offenderId::bigint AND OFF_TXN.CASELOAD_ID = :caseloadId

}

OTIDTACC_OFFTA_FIND_OFFENDER_TRUST_ACCOUNTS {
 	SELECT CASELOAD_ID ,OFFENDER_ID ,ACCOUNT_CLOSED_FLAG ,HOLD_BALANCE ,CURRENT_BALANCE ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,NOTIFY_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM OFFENDER_TRUST_ACCOUNTS  /* where  */
}
OTIDTACC_OFFSUBA_FIND_OFFENDER_SUB_ACCOUNTS {
 	SELECT CASELOAD_ID ,OFFENDER_ID ,TRUST_ACCOUNT_CODE ,BALANCE ,MINIMUM_BALANCE ,HOLD_BALANCE ,LAST_TXN_ID ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,IND_DATE ,IND_DAYS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM OFFENDER_SUB_ACCOUNTS  /* where  */
}
OTIDTACC_OFFDED_FIND_OFFENDER_DEDUCTIONS {
 	SELECT OFFENDER_DEDUCTION_ID ,CASELOAD_ID ,OFFENDER_ID ,CREDIT_LIMIT ,DEDUCTION_TYPE ,DEDUCTION_STATUS ,DEDUCTION_PRIORITY ,INFORMATION_NUMBER ,DEDUCTION_PERCENTAGE ,PROCESS_PRIORITY_NUMBER ,EFFECTIVE_DATE ,COMMENT_TEXT ,FIFO_FLAG ,PAYEE_PERSON_ID ,PAYEE_CORPORATE_ID ,MAX_MONTHLY_AMOUNT ,MAX_TOTAL_AMOUNT ,DEDUCTION_AMOUNT ,ADJUSTMENT_REASON_CODE ,ADJUSTMENT_AMOUNT ,ADJUSTMENT_USER_ID ,ADJUSTMENT_TXN_ID ,ADJUSTMENT_TEXT ,MODIFY_DATE ,PAY_DEDUCTION_FLAG ,MAX_RECURSIVE_AMOUNT ,GROUP_ID ,CASE_ID ,PARENT_DEDUCTION_ID ,JS_STATUS ,COLLECT_AGENCY_AMOUNT ,COLLECT_AGENCY_FLAG ,COLLECT_SENT_DATE ,OFFENDER_PAYMENT_PROFILE_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_DEDUCTIONS
}
OTIDTACC_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 	SELECT TXN_ID ,TXN_ENTRY_SEQ ,CASELOAD_ID ,OFFENDER_ID ,OFFENDER_BOOK_ID ,TXN_POSTING_TYPE ,TXN_TYPE ,TXN_ENTRY_DESC ,TXN_ENTRY_AMOUNT ,TXN_ENTRY_DATE ,SUB_ACCOUNT_TYPE ,TXN_REFERENCE_NUMBER ,MODIFY_DATE ,RECEIPT_NUMBER ,SLIP_PRINTED_FLAG ,TRANSFER_CASELOAD_ID ,RECEIPT_PRINTED_FLAG ,PRE_WITHHOLD_AMOUNT ,DEDUCTION_FLAG ,CLOSING_CHEQUE_NUMBER ,REMITTER_NAME ,PAYEE_CODE ,PAYEE_NAME_TEXT ,PAYEE_CORPORATE_ID ,PAYEE_PERSON_ID ,ADJUST_TXN_ID ,ADJUST_TXN_ENTRY_ID ,ADJUST_OFFENDER_ID ,ADJUST_ACCOUNT_CODE ,TXN_ADJUSTED_FLAG ,DEDUCTION_TYPE ,INFO_NUMBER ,HOLD_CLEAR_FLAG ,HOLD_UNTIL_DATE ,HOLD_NUMBER ,GROSS_AMOUNT ,GROSS_NET_FLAG ,REMITTER_ID ,APPLY_SPENDING_LIMIT_AMOUNT ,RECEIPT_PENDING_PRINT_FLAG ,SEAL_FLAG ,ORG_TXN_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_TRANSACTIONS  /* where  */
}
OTIDTACC_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}
OTIDTACC_SYSPFL_INSERT_SYSTEM_PROFILES {
	INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG ) VALUES(:profileType ,:profileCode ,:description ,:profileValue ,:profileValue2 ,:oldTableName ,:sysdate(),:createUserId  ,:sealFlag )
}

OTIDTACC_SYSPFL_DELETE_SYSTEM_PROFILES { 
	DELETE FROM SYSTEM_PROFILES/* where */
}


OTIDTACC_OFF_BKG_PREDELETEPRE-DELETE {
	DELETE FROM OFFENDER_TRUST_ACCOUNTS O WHERE O.CASELOAD_ID = :CASELOADID AND O.OFFENDER_ID = :ROOTOFFENDERID
}

OTIDTACC_OFF_BKG_PREDELETEPRE-DELETE {
	DELETE FROM OFFENDER_DEDUCTIONS O WHERE O.OFFENDER_ID = :ROOTOFFENDERID
}

OTIDTACC_OFF_TXN_WHENNEWRECORDINSTANCE {
	SELECT PAYROLL_BATCH_ID FROM OFFENDER_WORKS WHERE     TXN_ID = :TXNID AND TXN_ENTRY_SEQ = :TXNENTRYSEQ AND OFFENDER_ID = :OFFENDERID
}

OTIDTACC_CGFKCHK_OFF_SUBA_OFF_SUBA_AC {
select AC_CODE.SUB_ACCOUNT_TYPE CODE , REF_CODE.DESCRIPTION from account_codes ac_code left outer join reference_codes ref_code on (AC_CODE.SUB_ACCOUNT_TYPE = REF_CODE.CODE) where AC_CODE.ACCOUNT_CODE = :TRUSTACCOUNTCODE and domain = 'SUB_AC_TYPE' and CODE = AC_CODE.SUB_ACCOUNT_TYPE
}

OTIDTACC_CGFKCHK_OFF_DED_OFF_DED_DED_T {
	SELECT DED_TYPE.DEDUCTION_DESC ,DED_TYPE.LIST_SEQ FROM   DEDUCTION_TYPES DED_TYPE WHERE  DED_TYPE.DEDUCTION_TYPE = :DEDUCTIONTYPE
}

OTIDTACC_CGFDGET_OFF_TXN_DRV_TXN_ENTRY {
	SELECT DECODE(P_TXN_ENTRY_AMOUNT,0,NULL,NULL) FROM   SYS.DUAL
}

OTIDTACC_CGFDGET_OFF_TXN_DRV_TXN_EN2_ {
	SELECT DECODE(P_TXN_ENTRY_AMOUNT,0,NULL,NULL) FROM   SYS.DUAL
}

OTIDTACC_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OTIDTACC_POPULATE_CREDIT_OBLIGATION {
	SELECT COALESCE(SUM(OD.MAX_TOTAL_AMOUNT),0) TOTAL_CREDIT, COALESCE(SUM(OD.DEDUCTION_AMOUNT),0) PAID_CREDIT, COALESCE(SUM(OD.ADJUSTMENT_AMOUNT),0) WRITE_OFF_CREDIT FROM OFFENDER_DEDUCTIONS OD WHERE OD.OFFENDER_ID = :ROOTOFFENDERID AND OD.DEDUCTION_STATUS ='A' AND OD.DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE FROM DEDUCTION_TYPES DT WHERE DT.ACTIVE_FLAG = 'Y' AND DT.EXPIRY_DATE IS NULL AND DT.DEDUCTION_CATEGORY = 'CROB')

}

OTIDTACC_POPULATE_FIXED_OBLIGATION {
	SELECT COALESCE(SUM(OD.MAX_TOTAL_AMOUNT),0) TOTAL_FIXED, COALESCE(SUM(OD.DEDUCTION_AMOUNT),0) PAID_FIXED FROM OFFENDER_DEDUCTIONS OD WHERE OD.OFFENDER_ID = :ROOTOFFENDERID AND OD.DEDUCTION_STATUS ='A' AND OD.DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE FROM DEDUCTION_TYPES DT WHERE DT.ACTIVE_FLAG = 'Y' AND DT.EXPIRY_DATE IS NULL AND DT.DEDUCTION_CATEGORY = 'FXOB') AND NOT EXISTS ( SELECT 1 FROM  OFFENDER_MON_DEDUCTIONS OMD WHERE OMD.OFFENDER_DEDUCTION_ID = OD.OFFENDER_DEDUCTION_ID ) AND  OD.MAX_TOTAL_AMOUNT IS NOT NULL

}

OTIDTACC_CHECK_FIX_MTH_ACT {
	SELECT OD.MAX_TOTAL_AMOUNT , OD.MAX_MONTHLY_AMOUNT, OD.DEDUCTION_STATUS FROM OFFENDER_DEDUCTIONS OD WHERE OD.OFFENDER_ID = :ROOTOFFENDERID AND OD.OFFENDER_DEDUCTION_ID = :OFFENDERDEDUCTIONID AND OD.DEDUCTION_TYPE = :DEDUCTIONTYPE
}

OTIDTACC_POPULATE_CHECK_CLEAR_ {
	SELECT BCR.CHEQUE_NUMBER, GT.RECON_CLEAR_FLAG FROM BANK_CHEQUE_REGISTERS BCR , GL_TRANSACTIONS GT WHERE GT.TXN_ID = BCR.TXN_ID AND GT.ACCOUNT_CODE = BCR.ACCOUNT_CODE AND BCR.TXN_ID = :TXNID
}

OTIDTACC_POPULATE_PAYEE_REMITTER_NAME {
	SELECT R.LAST_NAME ||', '||R.FIRST_NAME REMITTER_NAME FROM REMITTERS R WHERE R.REMITTER_ID = :REMITTERID
}

OTIDTACC_POPULATE_PAYEE_REMITTER_NAME_ {
	SELECT OB.BOOKING_NO FROM OFFENDER_BOOKINGS OB WHERE OB.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OTIDTACC_GET_PAYEE_REMITTER_NAME {
	SELECT T1.TXN_ID , T2.PAYEE_PERSON_ID , T2.PAYEE_CORPORATE_ID , T2.PAYEE_NAME_TEXT FROM OFFENDER_TRANSACTIONS T1 , GL_TRANSACTIONS T2 WHERE T1.OFFENDER_ID   = :OFFENDERID AND T1.TXN_ID        = :TXNID AND T1.TXN_ENTRY_SEQ = :TXNENTRYSEQ AND T1.TXN_ID        = T2.TXN_ID AND T1.TXN_ENTRY_SEQ = T2.TXN_ENTRY_SEQ AND T2.GL_ENTRY_SEQ  = 1
}

OTIDTACC_GET_PERSON_CURSOR {
	SELECT P.LAST_NAME ||', '|| P.FIRST_NAME  AS PERSON_NAME FROM PERSONS P WHERE P.PERSON_ID  = :P_PERSON_ID
}

OTIDTACC_GET_CORPORATE_CURSOR {
	SELECT C.CORPORATE_NAME FROM CORPORATES C WHERE C.CORPORATE_ID = :P_CORPORATE_ID
}
OTIDTACC_GET_AGY_LOC_ID {
SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :CASELOADID AND AGY_LOC_ID = :AGYLOCID
}
OTIDTACC_GET_DAYS_REMAINING {
  select
	coalesce(SA.IND_DAYS,
        coalesce(MB.IND_DAYS,
        0))
from
	offender_sub_accounts sa
left outer join institution_mini_balances mb on
	(SA.TRUST_ACCOUNT_CODE = MB.ACCOUNT_CODE
		and SA.CASELOAD_ID = MB.CASELOAD_ID
		and :AGYLOCID = MB.AGY_LOC_ID)
where
	SA.CASELOAD_ID = :CASELOADID
	and SA.TRUST_ACCOUNT_CODE = :ACCCODE
	and SA.OFFENDER_ID = :OFFID;
}
OTIDTACC_GET_NBT_ACCOUNT_CLOSED_FLAG {
select
	'Y'
from
	OFFENDER_FREEZE_DISBURSEMENTS
where
	OFFENDER_ID = :OFFID
	and CASELOAD_ID = :CSLD_ID
	and date_trunc('D',SYSDATE()) between FROM_DATE and TO_DATE
	and coalesce (REMOVED_FLAG,
	'N')= 'N'
}
OTIDTACC_CALCULATE_DAYS_REMAIN {
	select
	:INDDAYS - (SYSDATE()::date - :INDDATE) result
from
	DUAL;
}
OTIDTACC_GET_CHEQUE_CLEAR_DATA {
SELECT BCR.CHEQUE_NUMBER PRE_WITHHOLD_AMOUNT, 
          GT.RECON_CLEAR_FLAG RECEIPT_PRINTED_FLAG
		 FROM BANK_CHEQUE_REGISTERS BCR
    		, GL_TRANSACTIONS GT
		WHERE GT.TXN_ID = BCR.TXN_ID
  		AND GT.ACCOUNT_CODE = BCR.ACCOUNT_CODE
  		AND BCR.TXN_ID = :TXNID limit 1
}
OTIDTACC_GET_PAYROLL_ID {
SELECT PAYROLL_BATCH_ID FROM OFFENDER_WORKS WHERE     TXN_ID =:TXN_ID AND TXN_ENTRY_SEQ = :TXN_ENTRY_SEQ AND OFFENDER_ID =:OFFENDER_ID limit 1
}
OTIDTACC_GET_BOOKING_NO {
SELECT OB.BOOKING_NO FROM OFFENDER_BOOKINGS OB  WHERE OB.OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID
}
OTIDTACC_GET_REMITTER_NAME {
SELECT R.LAST_NAME ||', '||R.FIRST_NAME REMITTER_NAME
       FROM REMITTERS R                    
      WHERE R.REMITTER_ID = :REMITTER_ID
}
OTIDTACC_GET_CUREENT_BALANCE {
SELECT SUM(CURRENT_BALANCE)
        FROM OFFENDER_TRUST_ACCOUNTS
       WHERE OFFENDER_ID = :OFFENDER_ID
       }
OTIDTACC_GET_CUREENT_BALANCE_WITH_CASELOAD {
SELECT CURRENT_BALANCE FROM OFFENDER_TRUST_ACCOUNTS WHERE OFFENDER_ID = :OFFENDER_ID AND CASELOAD_ID = :CASELOAD_ID
       }
            
OTIDTACC_CHK_DED_CAT {
SELECT DEDUCTION_CATEGORY FROM DEDUCTION_TYPES WHERE DEDUCTION_TYPE = :DEDUCTIONTYPE
    }
OTIDTACC_GET_DEDUCTION_AMOUNT {
 select
	coalesce (DEDUCTION_AMOUNT,
	0)
from
	OFFENDER_MON_DEDUCTIONS
where
	OFFENDER_DEDUCTION_ID = :DEDID
	and MONTHLY_DEDUCTION_DATE = date_trunc('day',current_timestamp)
}
OTIDTACC_CASE_DED_PFL {
SELECT dt.deduction_category, dt.deduction_type FROM deduction_types dt WHERE dt.deduction_type IN (SELECT DISTINCT deduction_type
 FROM offender_deductions WHERE caseload_id = :caseLoad AND offender_id = :offenderId) AND dt.caseload_code IN ('INST', 'BOTH')
             ORDER BY dt.deduction_category, dt.deduction_type
}
OTIDTACC_GET_ACCOUNT_CLOSED_FLAG {
SELECT ACCOUNT_CLOSED_FLAG FROM OFFENDER_TRUST_ACCOUNTS where OFFENDER_ID=:offenderId and CASELOAD_ID=:caseloadId
}