
OTMREMIT_FIND_CGFKREM1DSPDESCRIPTION {
 	SELECT REF_CODE2.DESCRIPTION  DSP_DESCRIPTION  /* CG$FK */        ,REF_CODE2.DOMAIN  DSP_DOMAIN        ,REF_CODE2.LIST_SEQ  DSP_LIST_SEQ        ,REF_CODE2.ACTIVE_FLAG  DSP_ACTIVE_FLAG        ,REF_CODE2.MODIFY_USER_ID  DSP_MODIFY_USER_ID        ,REF_CODE2.EXPIRED_DATE  DSP_EXPIRED_DATE        ,REF_CODE2.NEW_CODE  DSP_NEW_CODE        ,REF_CODE2.PARENT_CODE  DSP_PARENT_CODE        ,REF_CODE2.CODE  COUNTRY_CODE FROM   REFERENCE_CODES REF_CODE2 WHERE   ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL AND DOMAIN='COUNTRY' ORDER BY  REF_CODE2.LIST_SEQ
}

OTMREMIT_FIND_CGFKREM1DSPDESCRIPTION3 {
 	SELECT REF_CODE1.DESCRIPTION  DSP_DESCRIPTION3  /* CG$FK */        ,REF_CODE1.DOMAIN  DSP_DOMAIN2        ,REF_CODE1.LIST_SEQ  DSP_LIST_SEQ2        ,REF_CODE1.ACTIVE_FLAG  DSP_ACTIVE_FLAG2        ,REF_CODE1.MODIFY_USER_ID  DSP_MODIFY_USER_ID2        ,REF_CODE1.EXPIRED_DATE  DSP_EXPIRED_DATE2        ,REF_CODE1.NEW_CODE  DSP_NEW_CODE2        ,REF_CODE1.PARENT_CODE  DSP_PARENT_CODE2        ,REF_CODE1.CODE  PROV_STATE_CODE FROM   REFERENCE_CODES REF_CODE1 WHERE   ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL AND DOMAIN='PROV_STATE' ORDER BY  REF_CODE1.LIST_SEQ
}

OTMREMIT_REM_FIND_REMITTERS {
 	SELECT REMITTER_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,ADDRESS ,CITY ,COUNTRY_CODE ,PROV_STATE_CODE ,ZIP_STATE_CODE ,HOME_PHONE ,HOME_PHONE_AREA ,HOME_PHONE_EXT ,BUS_PHONE ,BUS_PHONE_AREA ,BUS_PHONE_EXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG 
 	FROM REMITTERS 
}
OTMREMIT_REM_INSERT_REMITTERS {
	/*INSERT INTO REMITTERS(REMITTER_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,ADDRESS ,CITY ,COUNTRY_CODE ,PROV_STATE_CODE ,ZIP_STATE_CODE ,HOME_PHONE ,HOME_PHONE_AREA ,HOME_PHONE_EXT ,BUS_PHONE ,BUS_PHONE_AREA ,BUS_PHONE_EXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ) 
	  VALUES(remitter_id.nextval ,:lastName ,:firstName ,:middleName ,:address ,:city ,:countryCode ,:provStateCode ,:zipStateCode ,:homePhone ,:homePhoneArea ,:homePhoneExt ,:busPhone ,:busPhoneArea ,:busPhoneExt ,:createDateTime ,:createUserId ,:modifyDateTime ,:modifyUserId ,:sealFlag )*/
	  INSERT INTO REMITTERS(REMITTER_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,ADDRESS ,CITY ,COUNTRY_CODE ,PROV_STATE_CODE ,ZIP_STATE_CODE ,HOME_PHONE ,HOME_PHONE_AREA ,HOME_PHONE_EXT ,BUS_PHONE ,BUS_PHONE_AREA ,BUS_PHONE_EXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) 
	  VALUES(nextval('remitter_id') ,:lastName ,:firstName ,:middleName ,:address ,:city ,:countryCode ,:provStateCode ,:zipStateCode ,:homePhone ,:homePhoneArea ,:homePhoneExt ,:busPhone ,:busPhoneArea ,:busPhoneExt ,current_timestamp ,:createUserId ,current_timestamp ,:sealFlag )
}

OTMREMIT_REM_UPDATE_REMITTERS {
	UPDATE REMITTERS set LAST_NAME  = :lastName ,FIRST_NAME  = :firstName ,MIDDLE_NAME  = :middleName ,ADDRESS  = :address ,CITY  = :city ,COUNTRY_CODE  = :countryCode ,PROV_STATE_CODE  = :provStateCode ,ZIP_STATE_CODE  = :zipStateCode ,HOME_PHONE  = :homePhone ,HOME_PHONE_AREA  = :homePhoneArea ,HOME_PHONE_EXT  = :homePhoneExt ,BUS_PHONE  = :busPhone ,BUS_PHONE_AREA  = :busPhoneArea ,BUS_PHONE_EXT  = :busPhoneExt ,MODIFY_DATETIME  = current_timestamp ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag 
	 WHERE REMITTER_ID  = :remitterId 
}

OTMREMIT_REM_DELETE_REMITTERS { 
	DELETE FROM REMITTERS  WHERE REMITTER_ID  = :remitterId
}

OTMREMIT_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}
OTMREMIT_SYSPFL_INSERT_SYSTEM_PROFILES {
	--INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:profileType ,:profileCode ,:description ,:profileValue ,:profileValue2 ,:modifyUserId ,:oldTableName ,:createDatetime ,:createUserId ,:modifyDatetime ,:sealFlag )
	INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:profileType ,:profileCode ,:description ,:profileValue ,:profileValue2 ,:oldTableName ,current_timestamp ,:createUserId ,current_timestamp ,:sealFlag )
}

OTMREMIT_SYSPFL_DELETE_SYSTEM_PROFILES { 
	DELETE FROM SYSTEM_PROFILES/* where */
}


OTMREMIT_CGFKCHK_REM1_REM_REF_CODE_F3_ {
	SELECT REF_CODE2.DOMAIN ,REF_CODE2.DESCRIPTION ,REF_CODE2.LIST_SEQ ,REF_CODE2.ACTIVE_FLAG ,REF_CODE2.MODIFY_USER_ID ,REF_CODE2.EXPIRED_DATE ,REF_CODE2.NEW_CODE ,REF_CODE2.PARENT_CODE FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.CODE = :COUNTRYCODE --AND     ACTIVE_FLAG='Y' --AND EXPIRED_DATE IS NULL AND DOMAIN='COUNTRY'
}

OTMREMIT_CGFKLKP_REM1_REM_REF_CODE_F3_ {
	SELECT REF_CODE2.CODE ,REF_CODE2.DOMAIN ,REF_CODE2.LIST_SEQ ,REF_CODE2.ACTIVE_FLAG ,REF_CODE2.MODIFY_USER_ID ,REF_CODE2.EXPIRED_DATE ,REF_CODE2.NEW_CODE ,REF_CODE2.PARENT_CODE FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.DESCRIPTION = :DSPDESCRIPTION AND     ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL AND DOMAIN='COUNTRY'
}

OTMREMIT_CGFKCHK_REM1_REM_REF_CODE_F2_ {
	SELECT REF_CODE1.DOMAIN ,REF_CODE1.DESCRIPTION ,REF_CODE1.LIST_SEQ ,REF_CODE1.ACTIVE_FLAG ,REF_CODE1.MODIFY_USER_ID ,REF_CODE1.EXPIRED_DATE ,REF_CODE1.NEW_CODE ,REF_CODE1.PARENT_CODE FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :PROVSTATECODE AND     ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL AND DOMAIN='PROV_STATE'
}

OTMREMIT_CGFKLKP_REM1_REM_REF_CODE_F2_ {
	SELECT REF_CODE1.CODE ,REF_CODE1.DOMAIN ,REF_CODE1.LIST_SEQ ,REF_CODE1.ACTIVE_FLAG ,REF_CODE1.MODIFY_USER_ID ,REF_CODE1.EXPIRED_DATE ,REF_CODE1.NEW_CODE ,REF_CODE1.PARENT_CODE FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.DESCRIPTION = :DSPDESCRIPTION3 AND     ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL AND DOMAIN='PROV_STATE'
}

OTMREMIT_CGRICHK_REMITTERS_ {
	SELECT  '1' FROM    REMITTERS REM1 WHERE   REM1.REMITTER_ID = P_REMITTER_ID
}
OTMREMIT_FIND_GET_PROV_COUNTRY_CODES {
/*SELECT 
(SELECT  CODE FROM REFERENCE_CODES WHERE  DOMAIN = 'PROV_STATE' AND LIST_SEQ = (SELECT MIN(LIST_SEQ) FROM REFERENCE_CODES WHERE DOMAIN = 'PROV_STATE')) CODE,
(SELECT CODE FROM REFERENCE_CODES WHERE  DOMAIN = 'COUNTRY' AND LIST_SEQ = (SELECT MIN(LIST_SEQ) FROM REFERENCE_CODES WHERE DOMAIN = 'COUNTRY')) DESCRIPTION
FROM REFERENCE_CODES WHERE ROWNUM  = 1*/
select
	(select CODE from REFERENCE_CODES where domain = 'PROV_STATE' and LIST_SEQ = (select MIN(LIST_SEQ) from REFERENCE_CODES where domain = 'PROV_STATE')) CODE,
	(select CODE from REFERENCE_CODES where domain = 'COUNTRY' and LIST_SEQ = (select MIN(LIST_SEQ) from REFERENCE_CODES where domain = 'COUNTRY')) DESCRIPTION
    from REFERENCE_CODES limit 1

}
