
OTUCPAYE_CORP_FIND_CORPORATES {
 	SELECT CORPORATE_ID ,CORPORATE_NAME ,CASELOAD_ID ,CONTACT_PERSON_NAME ,CREATED_DATE ,UPDATED_DATE ,USER_ID ,COMMENT_TEXT ,START_DATE ,ACCOUNT_TERM_CODE ,SHIPPING_TERM_CODE ,MINIMUM_PURCHASE_AMOUNT ,MAXIMUM_PURCHASE_AMOUNT ,MEMO_TEXT ,SUSPENDED_FLAG ,SUSPENDED_DATE ,FEI_NUMBER ,ACTIVE_FLAG ,EXPIRY_DATE ,TAX_NO ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM CORPORATES  /* where  */
}

OTUCPAYE_CORP_POST_QUERY{
   SELECT phone_no,ext_no FROM phones p1 WHERE owner_class = 'CORP' AND phone_type = 'BUS' AND owner_id = :CORPORATE_ID AND 
     p1.phone_id = (SELECT MIN(phone_id) FROM phones p2 WHERE p2.owner_id = :CORPORATE_ID  AND p2.owner_class = 'CORP' AND p2.phone_type = 'BUS')
 }