
OTUGLTRD_GLTXN_FIND_GL_TRANSACTIONS {
 	SELECT TXN_ID ,TXN_ENTRY_SEQ ,GL_ENTRY_SEQ ,ACCOUNT_PERIOD_ID ,ACCOUNT_CODE ,TXN_ENTRY_DATE ,TXN_TYPE ,TXN_POST_USAGE ,CASELOAD_ID ,OFFENDER_ID ,OFFENDER_BOOK_ID ,TXN_ENTRY_AMOUNT ,TXN_ENTRY_DESC ,TXN_REFERENCE_NUMBER ,BANK_STATEMENT_DATE ,RECON_CLEAR_FLAG ,TXN_REVERSED_FLAG ,REVERSED_TXN_ID ,PAYEE_PERSON_ID ,REVERSED_TXN_ENTRY_SEQ ,REVERSED_GL_ENTRY_SEQ ,PAYEE_CORPORATE_ID ,PAYEE_NAME_TEXT ,TXN_OBJECT_CODE ,LIST_SEQ ,TXN_OBJECT_ID ,CREATE_USER_ID ,CREATE_DATE ,INFO_NUMBER ,DEDUCTION_ID ,TXN_ENTRY_TIME ,RECEIPT_NUMBER ,REVERSAL_REASON_CODE ,TXN_LOC_ID ,PAYEE_CLEAR_FLAG ,CREATE_DATETIME ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM GL_TRANSACTIONS
}
OTUGLTRD_C_ALCN {
  SELECT count(0) RESULT FROM  OFFENDER_TRANSACTIONS OT, DEDUCTION_TYPES DT
         	  	    WHERE TXN_ID = :TXNID 
         	  	    AND TXN_ENTRY_SEQ = :TXNSEQ 
         	  	    AND DT.DEDUCTION_TYPE = OT.DEDUCTION_TYPE
         	  	    AND DT.DEDUCTION_CATEGORY = 'ALCN' 
         	  	    }
OTUGLTRD_C_GL {      	  	    
SELECT COUNT(0) FROM GL_TRANSACTIONS GL WHERE TXN_ID = :TXNID AND TXN_ENTRY_SEQ = :TXNSEQ 
}