
OTUHOLDR_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 	SELECT   FROM OFFENDER_TRANSACTIONS  /* where  */
}
OTUHOLDR_OFFTXN_INSERT_OFFENDER_TRANSACTIONS {
	INSERT INTO OFFENDER_TRANSACTIONS() VALUES(:)
}

OTUHOLDR_OFFTXN_UPDATE_OFFENDER_TRANSACTIONS {
	UPDATE OFFENDER_TRANSACTIONS set /* where */
}

OTUHOLDR_OFFTXN_DELETE_OFFENDER_TRANSACTIONS { 
	DELETE FROM OFFENDER_TRANSACTIONS/* where */
}


OTUHOLDR_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OTUHOLDR_GET_V_HOLD_CLEAR_FLAG {
	SELECT HOLD_CLEAR_FLAG FROM   OFFENDER_TRANSACTIONS WHERE  TXN_ID = :txnId AND TXN_ENTRY_SEQ = :txnEntrySeq AND  OFFENDER_ID = :offenderId AND    TXN_TYPE = 'HOA'
}

OTUHOLDR_GEN_TRUST_TRANS {
-- SELECT #SEQ.NEXTVAL NEXT_SEQ FROM DUAL
  SELECT NEXTVAL('#SEQ')
 }

OTUHOLDR_GET_MAX_OFFENDER_BOOK_ID {
	SELECT MAX(OFFENDER_BOOK_ID) FROM OFFENDER_BOOKINGS WHERE OFFENDER_ID = :offenderId
}
OTUHOLDR_TRUST_PROCESS_GL_TRANS_NEW {
CALL OMS_OWNER.TRUST.PROCESS_GL_TRANS_NEW(:P_CSLD_ID, :P_TRANS_TYPE, :P_OPERATION_TYPE, :P_TRANS_AMOUNT, :P_TRANS_NUMBER, :P_TRANS_DATE, :P_TRANS_DESC, :P_TRANS_SEQ, :P_MODULE_NAME, :P_OFF_ID, :P_OFF_BOOK_ID, :P_SUB_ACT_TYPE_DR, :P_SUB_ACT_TYPE_CR, :P_PAYEE_PERS_ID, :P_PAYEE_CORP_ID, :P_PAYEE_NAME_TEXT, :P_GL_SQNC, :P_OFF_DED_ID)
}
OTUHOLDR_UPDATE_OFFENDER_TRUST_ACCOUNTS {
	UPDATE OFFENDER_TRUST_ACCOUNTS SET	HOLD_BALANCE = HOLD_BALANCE - :txnEntryAmount, modify_user_id =:modifyUserId, modify_datetime = current_timestamp WHERE	OFFENDER_ID = :offenderId AND CASELOAD_ID = :caseloadId
}
OTUHOLDR_UPDATE_OFFENDER_SUB_ACCOUNT {
	UPDATE OFFENDER_SUB_ACCOUNTS SET	HOLD_BALANCE = HOLD_BALANCE - :txnEntryAmount,balance = balance + :txnEntryAmount, modify_user_id =:modifyUserId, modify_datetime = current_timestamp WHERE 	OFFENDER_ID = :offenderId AND	CASELOAD_ID = :caseloadId AND 
		TRUST_ACCOUNT_CODE IN 	(SELECT ACCOUNT_CODE FROM ACCOUNT_CODES	WHERE SUB_ACCOUNT_TYPE = :subAccountType)
}
OTUHOLDR_SUB_INSERT_OFF_TXN_INSERT {
	INSERT INTO OFFENDER_TRANSACTIONS (TXN_ID,TXN_ENTRY_SEQ, CASELOAD_ID, OFFENDER_ID, OFFENDER_BOOK_ID, TXN_POSTING_TYPE, TXN_TYPE, TXN_ENTRY_DESC, TXN_ENTRY_AMOUNT,TXN_ENTRY_DATE,SUB_ACCOUNT_TYPE, MODIFY_DATE, SLIP_PRINTED_FLAG, TXN_ADJUSTED_FLAG, HOLD_CLEAR_FLAG,HOLD_NUMBER,CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME) VALUES
 (:txnId, :txnEntrySeq, :caseloadId, :offenderId, :offenderBookId, :txnPostingType, :txnType, :txnEntryDesc, :txnEntryAmount, :txnEntryDate, :subAccountType, :modifyDate, :slipPrintedFlag, :txnAdjustedFlag, :holdClearFlag, :holdNumber,current_timestamp , :createUserId , current_timestamp)
}
OTUHOLDR_UPDATE_OFFENDER_BALANCE {
CALL OMS_OWNER.TRUST.UPDATE_OFFENDER_BALANCE(:P_CSLD_ID, :P_OFF_ID, :P_TRANS_POST_TYPE, :P_TRANS_DATE, :P_TRANS_NUMBER, :P_TRANS_TYPE, :P_TRANS_AMOUNT, :P_SUB_ACT_TYPE, :P_ALLOW_OVERDRAWN)
}
OTUHOLDR_UPDATE_HOLD_RECORD {
	UPDATE OFFENDER_TRANSACTIONS SET	HOLD_CLEAR_FLAG = 'Y' , modify_user_id =:modifyUserId, modify_datetime = current_timestamp WHERE TXN_ID = :txnId AND HOLD_NUMBER = :holdNumber AND OFFENDER_ID = :offenderId
}
OTUHOLDR_GET_ORG_TXN_TYPE {
	SELECT ORG_TXN_TYPE FROM OFFENDER_TRANSACTIONS WHERE TXN_ID = :txnId AND TXN_ENTRY_SEQ = :txnEntrySeq AND OFFENDER_ID = :offenderId
}
OTUHOLDR_OMS_OWNER_FINANCIAL_DO_DEDUCTIONS_FINANCIAL {
	CALL OMS_OWNER.FINANCIAL.DO_DEDUCTIONS_FINANCIAL(:P_CSLD_ID, :P_OFF_ID, :P_OFF_BOOK_ID, :P_TRANS_TYPE, :P_TRANS_NUMBER, :P_TRANS_DATE, :P_SUB_ACT_TYPE, :P_DED_FLAG, :P_RECEIPT_AMOUNT, :P_SHADOW_ID, :P_DED_AMOUNT, :TXN_SEQUENCE, :P_INFO_NUMBER)
}
OTUHOLDR_DEDUCTION_GET_AC_AND_SET_IND_DATE {
	CALL OMS_OWNER.DEDUCTIONS.GET_AC_AND_SET_IND_DATE(:P_OFF_ID, :P_CSLD_ID)
}