
OTUPAYIN_OFFDED_FIND_OFFENDER_DEDUCTIONS {
 	SELECT OFFENDER_DEDUCTION_ID ,CASELOAD_ID ,OFFENDER_ID ,CREDIT_LIMIT ,DEDUCTION_TYPE ,DEDUCTION_STATUS ,DEDUCTION_PRIORITY ,INFORMATION_NUMBER ,DEDUCTION_PERCENTAGE ,PROCESS_PRIORITY_NUMBER ,EFFECTIVE_DATE ,COMMENT_TEXT ,FIFO_FLAG ,PAYEE_PERSON_ID ,PAYEE_CORPORATE_ID ,MAX_MONTHLY_AMOUNT ,MAX_TOTAL_AMOUNT ,DEDUCTION_AMOUNT ,ADJUSTMENT_REASON_CODE ,ADJUSTMENT_AMOUNT ,ADJUSTMENT_USER_ID ,ADJUSTMENT_TXN_ID ,ADJUSTMENT_TEXT ,MODIFY_DATE ,PAY_DEDUCTION_FLAG ,MAX_RECURSIVE_AMOUNT ,GROUP_ID ,CASE_ID ,PARENT_DEDUCTION_ID ,JS_STATUS ,COLLECT_AGENCY_AMOUNT ,COLLECT_AGENCY_FLAG ,COLLECT_SENT_DATE ,OFFENDER_PAYMENT_PROFILE_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_DEDUCTIONS  WHERE OFFENDER_DEDUCTION_ID = :OFFENDERDEDUCTIONID
}
OTUPAYIN_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 	SELECT TXN_ID ,TXN_ENTRY_SEQ ,CASELOAD_ID ,OFFENDER_ID ,OFFENDER_BOOK_ID ,TXN_POSTING_TYPE ,TXN_TYPE ,TXN_ENTRY_DESC ,TXN_ENTRY_AMOUNT ,TXN_ENTRY_DATE ,SUB_ACCOUNT_TYPE ,TXN_REFERENCE_NUMBER ,MODIFY_DATE ,RECEIPT_NUMBER ,SLIP_PRINTED_FLAG ,TRANSFER_CASELOAD_ID ,RECEIPT_PRINTED_FLAG ,PRE_WITHHOLD_AMOUNT ,DEDUCTION_FLAG ,CLOSING_CHEQUE_NUMBER ,REMITTER_NAME ,PAYEE_CODE ,PAYEE_NAME_TEXT ,PAYEE_CORPORATE_ID ,PAYEE_PERSON_ID ,ADJUST_TXN_ID ,ADJUST_TXN_ENTRY_ID ,ADJUST_OFFENDER_ID ,ADJUST_ACCOUNT_CODE ,TXN_ADJUSTED_FLAG ,DEDUCTION_TYPE ,INFO_NUMBER ,HOLD_CLEAR_FLAG ,HOLD_UNTIL_DATE ,HOLD_NUMBER ,GROSS_AMOUNT ,GROSS_NET_FLAG ,REMITTER_ID ,APPLY_SPENDING_LIMIT_AMOUNT ,RECEIPT_PENDING_PRINT_FLAG ,SEAL_FLAG ,ORG_TXN_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM OFFENDER_TRANSACTIONS 
}

OTUPAYIN_OFF_DED_POSTQUERY {
	SELECT DED_TYPE.DEDUCTION_DESC FROM   DEDUCTION_TYPES DED_TYPE WHERE  DED_TYPE.DEDUCTION_TYPE =:DEDUCTION_TYPE
}
