
OTUSUBAC_OFFNAME_FIND_OFFENDERS {
 	SELECT OFFENDER_ID ,OFFENDER_NAME_SEQ ,ID_SOURCE_CODE ,LAST_NAME ,NAME_TYPE ,FIRST_NAME ,MIDDLE_NAME ,BIRTH_DATE ,SEX_CODE ,SUFFIX ,LAST_NAME_SOUNDEX ,BIRTH_PLACE ,BIRTH_COUNTRY_CODE ,CREATE_DATE ,LAST_NAME_KEY ,ALIAS_OFFENDER_ID ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,OFFENDER_ID_DISPLAY ,ROOT_OFFENDER_ID ,CASELOAD_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,ALIAS_NAME_TYPE ,PARENT_OFFENDER_ID ,UNIQUE_OBLIGATION_FLAG ,SUSPENDED_FLAG ,SUSPENDED_DATE ,RACE_CODE ,REMARK_CODE ,ADD_INFO_CODE ,BIRTH_COUNTY ,BIRTH_STATE ,MIDDLE_NAME_2 ,TITLE ,AGE ,CREATE_USER_ID ,LAST_NAME_ALPHA_KEY ,CREATE_DATETIME ,NAME_SEQUENCE ,SEAL_FLAG   FROM OFFENDERS WHERE ROOT_OFFENDER_ID = :offenderId
}
OTUSUBAC_OFFSUBA_FIND_OFFENDER_SUB_ACCOUNTS {
 	SELECT CASELOAD_ID ,OFFENDER_ID ,TRUST_ACCOUNT_CODE ,BALANCE ,MINIMUM_BALANCE ,HOLD_BALANCE ,LAST_TXN_ID ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,IND_DATE ,IND_DAYS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM OFFENDER_SUB_ACCOUNTS  WHERE  
}
OTUSUBAC_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OTUSUBAC_OFF_SUBA_PREQUERY {
	SELECT 'Y' ACTIVE_FLAG FROM CASELOADS WHERE CASELOAD_ID = :caseloadId AND TRUST_ACCOUNTS_FLAG = 'N' AND COMMISSARY_FLAG = 'Y' AND TRUST_COMMISSARY_CASELOAD IS NULL
}

OTUSUBAC_CGFKCHK_OFF_SUBA_OFF_SUBA_AC_CODE {
	SELECT SUB_ACCOUNT_TYPE FROM ACCOUNT_CODES WHERE ACCOUNT_CODE = :accountCode
}

OTUSUBAC_CGFKCHK_OFF_SUBA_OFF_SUBA_AC {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE = :code AND DOMAIN = 'SUB_AC_TYPE'
}
