 
OCMOHSTA_COMHDRST_FIND_COMMUNITY_HEADER_STATUSES {
	SELECT STATUS_CODE, DESCRIPTION, HIERARCHY_SEQUENCE, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EXPIRY_DATE, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG , ROW_ID
FROM  COMMUNITY_HEADER_STATUSES WHERE
}
OCMOHSTA_COMHDRST_INSERT_COMMUNITY_HEADER_STATUSES {
INSERT INTO OMS_OWNER.COMMUNITY_HEADER_STATUSES(STATUS_CODE, DESCRIPTION, HIERARCHY_SEQUENCE, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EXPIRY_DATE, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME, SEAL_FLAG) 
    VALUES(:statusCode, :description, :hierarchySequence, :listSeq, :activeFlag, :updateAllowedFlag, :expiryDate, :createUserId, current_timestamp, NULL, :sealFlag)
}  

OCMOHSTA_COMHDRST_UPDATE_COMMUNITY_HEADER_STATUSES {
	UPDATE OMS_OWNER.COMMUNITY_HEADER_STATUSES 
    SET DESCRIPTION=:description, HIERARCHY_SEQUENCE=:hierarchySequence, LIST_SEQ=:listSeq, ACTIVE_FLAG=:activeFlag, UPDATE_ALLOWED_FLAG=:updateAllowedFlag
    , EXPIRY_DATE=:expiryDate, MODIFY_DATETIME=current_timestamp, MODIFY_USER_ID=:modifyUserId
    WHERE STATUS_CODE = :statusCode
}  

OCMOHSTA_COMHDRST_DELETE_COMMUNITY_HEADER_STATUSES { 
	DELETE FROM COMMUNITY_HEADER_STATUSES  WHERE STATUS_CODE = :statusCode
}


OCMOHSTA_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO   V_FORM_DESC FROM   OMS_MODULES WHERE  MODULE_NAME = V_FORM_NAME
}
OCMOHSTA_STATUS_CUR {
SELECT count(*)  FROM community_header_statuses  WHERE status_code in (:lv_status_code)
       }
 OCMOHSTA_HIERARCHY_CUR {
  SELECT count(*)
        FROM community_header_statuses 
       WHERE hierarchy_sequence in (:lv_hierarchy)
   }
   OCMOHSTA_HIERARCHY_CUR_UPDATE {
  SELECT count(*)
        FROM community_header_statuses 
       WHERE hierarchy_sequence in( :lv_hierarchy ) and row_id  NOT iN (:rowId  )  
   }  