
OCUAVISN_FIND_RGCONTACTTYPE {
 	SELECT DESCRIPTION ,CODE, ACTIVE_FLAG  FROM REFERENCE_CODES  WHERE DOMAIN = 'CONTACTS'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ ,DESCRIPTION ,CODE
}

OCUAVISN_FIND_RGRELATIONSHIPTYPE {
 	SELECT DESCRIPTION        ,CODE, ACTIVE_FLAG   FROM REFERENCE_CODES  WHERE DOMAIN = 'RELATIONSHIP' AND CODE IN
 	(SELECT RELATIONSHIP_TYPE CODE              FROM CONTACT_PERSON_TYPES  WHERE CONTACT_TYPE = :CONTACTTYPE ) 
 	AND ACTIVE_FLAG = 'Y' ORDER BY LIST_SEQ ,DESCRIPTION ,CODE
}
OCUAVISN_FIND_TOTAL_RELATIONSHIP {
SELECT DESCRIPTION        ,CODE   FROM REFERENCE_CODES  WHERE DOMAIN = 'RELATIONSHIP' 
 	AND ACTIVE_FLAG = 'Y' ORDER BY LIST_SEQ ,DESCRIPTION ,CODE
}


OCUAVISN_VOFFAUTHVIS_FIND_V_OFF_CONTACT_PERSONS {
 	SELECT OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,CONTACT_TYPE ,CONTACT_TYPE_DESCRIPTION ,RELATIONSHIP_TYPE ,
 	RELATIONSHIP_TYPE_DESCRIPTION ,PERSON_ID ,OFFENDER_BOOK_ID ,OFFENDER_ID ,APPROVED_VISITOR_FLAG ,CONTACT_ROOT_OFFENDER_ID ,
 	COMMENT_TEXT ,OFFENDER_CONTACT_PERSON_ID ,PERSON_LAST_NAME ,PERSON_FIRST_NAME ,CASELOAD_TYPE ,MODIFY_DATETIME ,MODIFY_USER_ID ,
 	CHECK_SUM ,ACTIVE_FLAG   FROM V_OFF_CONTACT_PERSONS 
}
OCUAVISN_VOFFAUTHVIS_INSERT_V_OFF_CONTACT_PERSONS {
insert into OFFENDER_CONTACT_PERSONS(CONTACT_TYPE , RELATIONSHIP_TYPE , PERSON_ID , OFFENDER_BOOK_ID , APPROVED_VISITOR_FLAG , CONTACT_ROOT_OFFENDER_ID , COMMENT_TEXT , OFFENDER_CONTACT_PERSON_ID , CASELOAD_TYPE , MODIFY_DATETIME , ACTIVE_FLAG , create_datetime, create_user_id)
values(:contactType , :relationshipType, :personId, :offenderBookId, :approvedVisitorFlag, :contactRootOffenderId, :commentText, nextval('OFFENDER_CONTACT_PERSON_ID'), :caseloadType, null, :activeFlag , current_timestamp, :createUserId)
}

OCUAVISN_VOFFAUTHVIS_UPDATE_V_OFF_CONTACT_PERSONS {
update OFFENDER_CONTACT_PERSONS set CONTACT_TYPE = :contactType , RELATIONSHIP_TYPE = :relationshipType , PERSON_ID = :personId , OFFENDER_BOOK_ID = :offenderBookId , APPROVED_VISITOR_FLAG = :approvedVisitorFlag , CONTACT_ROOT_OFFENDER_ID = :contactRootOffenderId , COMMENT_TEXT = :commentText , CASELOAD_TYPE = :caseloadType , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , ACTIVE_FLAG = :activeFlag where OFFENDER_BOOK_ID =:offenderBookId and OFFENDER_CONTACT_PERSON_ID = :offenderContactPersonId
}
OCUAVISN_GET_OFFENDER_CONTACT_PERSON_ID {
SELECT nextval('offender_contact_person_id')
           FROM dual
}
OCUAVISN_GET_CONTACT_TYPE_DESCRIPTION {
select tag_reference_codes_getdesccode('CONTACTS', :contactType) from dual
}
OCUAVISN_GET_RELATIONTYPE_DESCRIPTION {
select tag_reference_codes_getdesccode('RELATIONSHIP', :relationType) from dual
}