
OCUCLOFF_FIND_RGRELATIONSHIPTYPE {

 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'RELATIONSHIP' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  DESCRIPTION, LIST_SEQ

}

OCUCLOFF_FIND_RGCONTACTTYPE {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'CONTACTS' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  DESCRIPTION, LIST_SEQ

}

OCUCLOFF_CONTACTS_FIND_V_DISTINCT_LINKED_OFFENDERS {
 	SELECT
  OFFENDER_ID_DISPLAY, LAST_NAME, FIRST_NAME, MIDDLE_NAME, CONTACT_TYPE,
  CONTACT_TYPE_DESCRIPTION, RELATIONSHIP_TYPE, RELATIONSHIP_TYPE_DESCRIPTION,
  PERSON_ID, ROOT_OFFENDER_ID
FROM V_DISTINCT_LINKED_OFFENDERS
WHERE
  PERSON_ID = :personId

}
