
OCUCNPER_FIND_RGSEXCODE {
 	SELECT DESCRIPTION DESCRIPTION ,        CODE    FROM REFERENCE_CODES  WHERE DOMAIN = 'SEX'     AND ACTIVE_FLAG = 'Y'     AND EXPIRED_DATE IS NULL
}

OCUCNPER_PERSONS_FIND_PERSONS {
 	SELECT PERSON_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,BIRTHDATE ,OCCUPATION_CODE ,CRIMINAL_HISTORY_TEXT ,NAME_TYPE ,ALIAS_PERSON_ID ,ROOT_PERSON_ID ,LANGUAGE_CODE ,COMPREHEND_ENGLISH_FLAG ,SEX ,BIRTH_PLACE ,EMPLOYER ,PROFILE_CODE ,INTERPRETER_REQUIRED ,PRIMARY_LANGUAGE_CODE ,MEMO_TEXT ,SUSPENDED_FLAG ,MARITAL_STATUS ,CITIZENSHIP ,DECEASED_DATE ,CORONER_NUMBER ,ATTENTION ,CARE_OF ,SUSPENDED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,STAFF_FLAG ,REMITTER_FLAG ,LAST_NAME_SOUNDEX ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,LAST_NAME_KEY ,SEAL_FLAG   FROM PERSONS  /* where  */
}

OCUCNPER_PERSONS_INSERT_PERSONS {
 insert into PERSONS(PERSON_ID , LAST_NAME , FIRST_NAME , MIDDLE_NAME , BIRTHDATE , OCCUPATION_CODE , CRIMINAL_HISTORY_TEXT , NAME_TYPE , ALIAS_PERSON_ID , LANGUAGE_CODE , COMPREHEND_ENGLISH_FLAG , SEX , BIRTH_PLACE , EMPLOYER , PROFILE_CODE , INTERPRETER_REQUIRED , PRIMARY_LANGUAGE_CODE , MEMO_TEXT , SUSPENDED_FLAG , MARITAL_STATUS , CITIZENSHIP , DECEASED_DATE , CORONER_NUMBER , ATTENTION , CARE_OF , SUSPENDED_DATE , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , STAFF_FLAG , REMITTER_FLAG , LAST_NAME_SOUNDEX , FIRST_NAME_KEY , MIDDLE_NAME_KEY , LAST_NAME_KEY , SEAL_FLAG, SECOND_MIDDLE_NAME ) values(:personId , :lastName , :firstName , :middleName , :birthdate , :occupationCode , :criminalHistoryText , :nameType , :aliasPersonId , :languageCode , :comprehendEnglishFlag , :sex , :birthPlace , :employer , :profileCode , :interpreterRequired , :primaryLanguageCode , :memoText , :suspendedFlag , :maritalStatus , :citizenship , :deceasedDate , :coronerNumber , :attention , :careOf , :suspendedDate , CURRENT_TIMESTAMP , :createUserId , NULL , :staffFlag , :remitterFlag , :lastNameSoundex , :firstNameKey , :middleNameKey , :lastNameKey , :sealFlag , :secondMiddleName ) 
}

OCUCNPER_PERSONS_PREINSERT {
select Max(person_id) + 1 from persons
}
