
OCUPREST_FIND_RGAUTHORISEDBY {
 	SELECT LAST_NAME||', '|| FIRST_NAME  DESCRIPTION, STAFF_ID  CODE  FROM STAFF_MEMBERS  WHERE UPPER(STATUS ) = 'ACTIVE'    AND TERMINATION_DATE IS NULL    AND SUSPENDED_FLAG = 'N' ORDER BY LAST_NAME||', '|| FIRST_NAME
}

OCUPREST_FIND_RGRESTRICTIONTYPE {
 	SELECT   REF_CODE.DESCRIPTION ,          REF_CODE.CODE ,                   PARENT_CODE     FROM REFERENCE_CODES REF_CODE    WHERE DOMAIN = 'VST_RST_TYPE'      AND ((ACTIVE_FLAG = 'Y' ) OR ::MODE = 'ENTER-QUERY' )      AND PARENT_CODE IN ('BAN' , 'RESTRICTION' ) ORDER BY REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION ,REF_CODE.CODE
}

OCUPREST_OFF_FIND_V_HEADER_BLOCK {
 	SELECT OFFENDER_ID ,ALIAS_OFFENDER_ID ,OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,SUFFIX ,BIRTH_DATE ,OFFENDER_BOOK_ID ,BOOKING_NO ,BOOKING_BEGIN_DATE ,BOOKING_END_DATE ,AGY_LOC_ID ,AGENCY_IML_ID ,LIVING_UNIT_ID ,DISCLOSURE_FLAG ,ACTIVE_FLAG ,BOOKING_STATUS ,LIVING_UNIT_DESCRIPTION ,IN_OUT_STATUS ,STATUS_DISPLAY ,ROOT_OFFENDER_ID ,ASSIGNED_STAFF_ID ,AGY_LOC_TYPE ,CREATE_AGY_LOC_ID ,BOOKING_TYPE ,BOOKING_CREATED_DATE ,LOCATION_CODE ,LIV_UNIT_DESC ,INTAKE_AGY_LOC_ID ,COMMUNITY_ACTIVE_FLAG ,CREATE_INTAKE_AGY_LOC_ID ,COMMUNITY_STATUS ,STATUS_REASON ,HEADER_STATUS ,AGE ,GENDER ,OFFICER ,PRISON_LOCATION ,OFF_ALERTS ,STATUS_1 ,STATUS_2 ,STATUS_3 ,ETHNICITY ,MOVEMENT_REASON ,OFF_SUP_LEVEL  
 	FROM V_HEADER_BLOCK_FN(:USERID) V_HEADER_BLOCK  WHERE OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID
 	
}
OCUPREST_VOFFREST_FIND_V_OFFENDER_RESTRICTIONS {
 	SELECT OFFENDER_BOOK_ID ,OFFENDER_RESTRICTION_ID ,EFFECTIVE_DATE ,EXPIRY_DATE ,RESTRICTION_TYPE ,RESTRICTION_DESC ,ENTERED_STAFF_ID ,ENTERED_STAFF_NAME ,AUTHORISED_STAFF_ID ,AUTHROISED_STAFF_NAME ,COMMENT_TEXT   FROM V_OFFENDER_RESTRICTIONS  
 	 WHERE  OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID
}

OCUPREST_OFF_ONCHECKDELETEMASTER {
	SELECT 1 FROM OFFENDER_RESTRICTIONS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}
