
OIUOVRES_FIND_RGOFFRESTRICTIONTYPE {
select REF_CODE.CODE DESCRIPTION, REF_CODE.CODE CODE , REF_CODE.DESCRIPTION as domain , PARENT_CODE from REFERENCE_CODES REF_CODE where domain = 'VST_RST_TYPE' and ((ACTIVE_FLAG = 'Y' and EXPIRED_DATE is null ) or '' = 'ENTER-QUERY' ) and PARENT_CODE in ('RESTRICTION') order by REF_CODE.LIST_SEQ , REF_CODE.CODE
}
OIUOVRES_FIND_RGSTAFFID {
select (coalesce(LAST_NAME, '') ||', '||  coalesce(FIRST_NAME, '')) as DESCRIPTION, STAFF_ID CODE FROM STAFF_MEMBERS
}

OIUOVRES_PER_FIND_PERSONS {
 	SELECT PERSON_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,BIRTHDATE ,OCCUPATION_CODE ,CRIMINAL_HISTORY_TEXT ,NAME_TYPE ,ALIAS_PERSON_ID ,ROOT_PERSON_ID ,LANGUAGE_CODE ,COMPREHEND_ENGLISH_FLAG ,SEX ,BIRTH_PLACE ,EMPLOYER ,PROFILE_CODE ,INTERPRETER_REQUIRED ,PRIMARY_LANGUAGE_CODE ,MEMO_TEXT ,SUSPENDED_FLAG ,MARITAL_STATUS ,CITIZENSHIP ,DECEASED_DATE ,CORONER_NUMBER ,ATTENTION ,CARE_OF ,SUSPENDED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,STAFF_FLAG ,REMITTER_FLAG ,LAST_NAME_SOUNDEX ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,LAST_NAME_KEY ,SEAL_FLAG   FROM PERSONS where PERSON_ID = :personId
}
OIUOVRES_PER_INSERT_PERSONS {
	INSERT INTO PERSONS(PERSON_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,BIRTHDATE ,OCCUPATION_CODE ,CRIMINAL_HISTORY_TEXT ,NAME_TYPE ,ALIAS_PERSON_ID ,ROOT_PERSON_ID ,LANGUAGE_CODE ,COMPREHEND_ENGLISH_FLAG ,SEX ,BIRTH_PLACE ,EMPLOYER ,PROFILE_CODE ,INTERPRETER_REQUIRED ,PRIMARY_LANGUAGE_CODE ,MEMO_TEXT ,SUSPENDED_FLAG ,MARITAL_STATUS ,CITIZENSHIP ,DECEASED_DATE ,CORONER_NUMBER ,ATTENTION ,CARE_OF ,SUSPENDED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,STAFF_FLAG ,REMITTER_FLAG ,LAST_NAME_SOUNDEX ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,LAST_NAME_KEY ,SEAL_FLAG ) VALUES(:personId ,:lastName ,:firstName ,:middleName ,:birthdate ,:occupationCode ,:criminalHistoryText ,:nameType ,:aliasPersonId ,:rootPersonId ,:languageCode ,:comprehendEnglishFlag ,:sex ,:birthPlace ,:employer ,:profileCode ,:interpreterRequired ,:primaryLanguageCode ,:memoText ,:suspendedFlag ,:maritalStatus ,:citizenship ,:deceasedDate ,:coronerNumber ,:attention ,:careOf ,:suspendedDate ,:createDatetime ,:createUserId ,:modifyDatetime ,:modifyUserId ,:staffFlag ,:remitterFlag ,:lastNameSoundex ,:firstNameKey ,:middleNameKey ,:lastNameKey ,:sealFlag )
}

OIUOVRES_PER_UPDATE_PERSONS {
	UPDATE PERSONS set PERSON_ID  = :personId ,LAST_NAME  = :lastName ,FIRST_NAME  = :firstName ,MIDDLE_NAME  = :middleName ,BIRTHDATE  = :birthdate ,OCCUPATION_CODE  = :occupationCode ,CRIMINAL_HISTORY_TEXT  = :criminalHistoryText ,NAME_TYPE  = :nameType ,ALIAS_PERSON_ID  = :aliasPersonId ,ROOT_PERSON_ID  = :rootPersonId ,LANGUAGE_CODE  = :languageCode ,COMPREHEND_ENGLISH_FLAG  = :comprehendEnglishFlag ,SEX  = :sex ,BIRTH_PLACE  = :birthPlace ,EMPLOYER  = :employer ,PROFILE_CODE  = :profileCode ,INTERPRETER_REQUIRED  = :interpreterRequired ,PRIMARY_LANGUAGE_CODE  = :primaryLanguageCode ,MEMO_TEXT  = :memoText ,SUSPENDED_FLAG  = :suspendedFlag ,MARITAL_STATUS  = :maritalStatus ,CITIZENSHIP  = :citizenship ,DECEASED_DATE  = :deceasedDate ,CORONER_NUMBER  = :coronerNumber ,ATTENTION  = :attention ,CARE_OF  = :careOf ,SUSPENDED_DATE  = :suspendedDate ,CREATE_DATETIME  = :createDatetime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = :modifyDatetime ,MODIFY_USER_ID  = :modifyUserId ,STAFF_FLAG  = :staffFlag ,REMITTER_FLAG  = :remitterFlag ,LAST_NAME_SOUNDEX  = :lastNameSoundex ,FIRST_NAME_KEY  = :firstNameKey ,MIDDLE_NAME_KEY  = :middleNameKey ,LAST_NAME_KEY  = :lastNameKey ,SEAL_FLAG  = :sealFlag /* where */
}

OIUOVRES_OFFCONREST_FIND_OFFENDER_PERSON_RESTRICTS { 
select OFFENDER_CONTACT_PERSON_ID , OFFENDER_PERSON_RESTRICT_ID , RESTRICTION_TYPE , RESTRICTION_EFFECTIVE_DATE , RESTRICTION_EXPIRY_DATE , AUTHORIZED_STAFF_ID , COMMENT_TEXT , ENTERED_STAFF_ID , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID , SEAL_FLAG, case when RESTRICTION_TYPE is not null then ( select DESCRIPTION from REFERENCE_CODES where domain = 'VST_RST_TYPE' and PARENT_CODE = 'RESTRICTION' and CODE = RESTRICTION_TYPE) else null end DESCRIPTION from OFFENDER_PERSON_RESTRICTS where OFFENDER_CONTACT_PERSON_ID = tag_visits_get_offender_cont_person_id(:offenderBookId, :personId) order by RESTRICTION_EFFECTIVE_DATE desc, RESTRICTION_EXPIRY_DATE desc
}
OIUOVRES_OFFCONREST_INSERT_OFFENDER_PERSON_RESTRICTS {
insert into OFFENDER_PERSON_RESTRICTS (OFFENDER_CONTACT_PERSON_ID, OFFENDER_PERSON_RESTRICT_ID, RESTRICTION_TYPE, RESTRICTION_EFFECTIVE_DATE, RESTRICTION_EXPIRY_DATE, COMMENT_TEXT, ENTERED_STAFF_ID, create_datetime, modify_datetime, create_user_id) values ( tag_visits_get_offender_cont_person_id(:offenderBookId, :personId), NEXTVAL('OFFENDER_PERSON_RESTRICT_ID'), :restrictionType, :restrictionEffectiveDate, :restrictionExpiryDate, :commentText,:enteredStaffId, current_timestamp, current_timestamp, :createUserId)
}

OIUOVRES_OFFCONREST_UPDATE_OFFENDER_PERSON_RESTRICTS {
update OFFENDER_PERSON_RESTRICTS set RESTRICTION_TYPE = :restrictionType, RESTRICTION_EFFECTIVE_DATE = :restrictionEffectiveDate, RESTRICTION_EXPIRY_DATE = :restrictionExpiryDate, COMMENT_TEXT = :commentText, modify_datetime = current_timestamp , modify_user_id = :modifyUserId where OFFENDER_CONTACT_PERSON_ID = :offenderContactPersonId and OFFENDER_PERSON_RESTRICT_ID = :offenderPersonRestrictId
}

GET_STAFF_NAME_FOR_ENTERED_STAFF_ID{
SELECT   (coalesce(LAST_NAME , '') ||', '||  coalesce(FIRST_NAME, '')) FROM staff_members WHERE staff_id = :staffId
}

OIUOVRES_OFFCONREST_GET_STAFF_ID{
SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID =:userId
}
