
OMUAPRIS_VOFFAUTHVIS_FIND_V_OFFENDER_AUTHORISED_VISITORS {
 SELECT OFFENDER_BOOK_ID ,VISITOR_OFFENDER_ID_DISPLAY ,CONTACT_TYPE ,RELATIONSHIP_TYPE ,CONTACT_PERSON_TYPE ,AGE ,CONTACT_ROOT_OFFENDER_ID ,CONTACT_PERSON_ID ,VISITOR_LAST_NAME ,VISITOR_FIRST_NAME ,OFFENDER_CONTACT_PERSON_ID   FROM V_OFFENDER_AUTHORISED_VISITORS
}
OMUAPRIS_VOFFAUTHVIS_UPDATE_V_OFFENDER_AUTHORISED_VISITORS {
	UPDATE V_OFFENDER_AUTHORISED_VISITORS set OFFENDER_BOOK_ID  = :offenderBookId ,VISITOR_OFFENDER_ID_DISPLAY  = :visitorOffenderIdDisplay ,CONTACT_TYPE  = :contactType ,RELATIONSHIP_TYPE  = :relationshipType ,CONTACT_PERSON_TYPE  = :contactPersonType ,AGE  = :age ,CONTACT_ROOT_OFFENDER_ID  = :contactRootOffenderId ,CONTACT_PERSON_ID  = :contactPersonId ,VISITOR_LAST_NAME  = :visitorLastName ,VISITOR_FIRST_NAME  = :visitorFirstName ,OFFENDER_CONTACT_PERSON_ID  = :offenderContactPersonId /* where */
}


OMUAPRIS_GET_OFFENDER_NAMES {
	SELECT LAST_NAME, FIRST_NAME, OFFENDER_ID_DISPLAY FROM V_HEADER_BLOCK_FN(:USERID) V_HEADER_BLOCK WHERE OFFENDER_BOOK_ID = :P_OFF_BOOK_ID
}
OMUAPRIS_GET_OFFENDER_RESTRICTIONS {
select
	ORS.EFFECTIVE_DATE,
	ORS.RESTRICTION_TYPE
from
	OFFENDER_RESTRICTIONS ORS
where
	ORS.OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID
	and date_TRUNC('D',ORS.EFFECTIVE_DATE) <= date_TRUNC('D',:P_VISIT_DATE::timestamp)
	and (ORS.EXPIRY_DATE is null
		or
                ORS.EXPIRY_DATE > date_TRUNC('D',:P_VISIT_DATE::timestamp))
}
