
OMUVREST_FIND_RGVISRRESTVISITRESTRICTI {
SELECT REF_CODE.CODE , REF_CODE.DOMAIN , REF_CODE.DESCRIPTION DESCRIPTION , REF_CODE.LIST_SEQ , REF_CODE.ACTIVE_FLAG , REF_CODE.MODIFY_USER_ID , REF_CODE.EXPIRED_DATE , REF_CODE.NEW_CODE , REF_CODE.PARENT_CODE FROM REFERENCE_CODES REF_CODE WHERE DOMAIN = 'VST_RST_TYPE' AND PARENT_CODE IN ('BAN') ORDER BY REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION
}
OMUVREST_PER_FIND_PERSONS {
 	SELECT PERSON_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,BIRTHDATE ,OCCUPATION_CODE ,CRIMINAL_HISTORY_TEXT ,NAME_TYPE ,ALIAS_PERSON_ID ,ROOT_PERSON_ID ,LANGUAGE_CODE ,COMPREHEND_ENGLISH_FLAG ,SEX ,BIRTH_PLACE ,EMPLOYER ,PROFILE_CODE ,INTERPRETER_REQUIRED ,PRIMARY_LANGUAGE_CODE ,MEMO_TEXT ,SUSPENDED_FLAG ,MARITAL_STATUS ,CITIZENSHIP ,DECEASED_DATE ,CORONER_NUMBER ,ATTENTION ,CARE_OF ,SUSPENDED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,STAFF_FLAG ,REMITTER_FLAG ,LAST_NAME_SOUNDEX ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,LAST_NAME_KEY ,SEAL_FLAG   FROM PERSONS /*WHERE PERSON_ID=:PERSONID*/
}
OMUVREST_VISRREST_FIND_VISITOR_RESTRICTIONS {
 	SELECT PERSON_ID ,VISIT_RESTRICTION_TYPE ,EFFECTIVE_DATE ,EXPIRY_DATE ,COMMENT_TXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,VISITOR_RESTRICTION_ID ,ENTERED_STAFF_ID ,OFFENDER_ID ,SEAL_FLAG   FROM VISITOR_RESTRICTIONS WHERE PERSON_ID=:PERSONID ORDER BY EFFECTIVE_DATE DESC, EXPIRY_DATE DESC
}
OMUVREST_VISRREST_INSERT_VISITOR_RESTRICTIONS {
 insert into VISITOR_RESTRICTIONS(PERSON_ID , VISIT_RESTRICTION_TYPE , EFFECTIVE_DATE , EXPIRY_DATE , COMMENT_TXT , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID , VISITOR_RESTRICTION_ID , ENTERED_STAFF_ID , OFFENDER_ID , SEAL_FLAG ) values(:personId , :visitRestrictionType , :effectiveDate , :expiryDate , :commentTxt , current_timestamp , :createUserId , NULL , NULL , :visitorRestrictionId , :enteredStaffId , :offenderId , :sealFlag ) 
}
OMUVREST_VISRREST_UPDATE_VISITOR_RESTRICTIONS {
 update VISITOR_RESTRICTIONS set PERSON_ID = :personId , VISIT_RESTRICTION_TYPE = :visitRestrictionType , EFFECTIVE_DATE = :effectiveDate , EXPIRY_DATE = :expiryDate , COMMENT_TXT = :commentTxt , MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID = :modifyUserId , VISITOR_RESTRICTION_ID = :visitorRestrictionId , ENTERED_STAFF_ID = :enteredStaffId , OFFENDER_ID = :offenderId , SEAL_FLAG = :sealFlag where PERSON_ID = :personId and VISITOR_RESTRICTION_ID = :visitorRestrictionId 
}
OMUVREST_PER_PREDELETEPRE-DELETE {
	DELETE FROM VISITOR_RESTRICTIONS V WHERE V.PERSON_ID = :PERSONID
}
OMUVREST_VISITOR_RESTRICTION_ID {
	SELECT NEXTVAL('VISITOR_RESTRICTION_ID') FROM DUAL
}
OMUVREST_ENTERED_STAFF_ID {
select
	STAFF_ID
from
	STAFF_MEMBERS
where
	USER_ID = :userId;
}
OMUVREST_DESRIPTION_POST_INSERT {
	SELECT LAST_NAME||', '||FIRST_NAME DESCRIPTION
         FROM STAFF_MEMBERS
        WHERE STAFF_ID = :STAFFID
}
