
OSIPSEAR_FIND_RGLANGUAGECODE {
 	SELECT
  DESCRIPTION, CODE, ACTIVE_FLAG
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'LANG'
ORDER BY
  DESCRIPTION, LIST_SEQ

}

OSIPSEAR_FIND_RGMARITALSTATUS {
 	select
	DESCRIPTION,
	CODE,
	ACTIVE_FLAG
from
	REFERENCE_CODES
where
	domain = 'MARITAL_STAT'
	or ('' = 'ENTER-QUERY' )
order by
	DESCRIPTION ,
	LIST_SEQ
}

OSIPSEAR_FIND_RGSEXCODE {
 	select
	DESCRIPTION NBT_SEX_CODE ,
	CODE SEX_CODE
from
	REFERENCE_CODES
where
	domain = 'SEX'
	and ((ACTIVE_FLAG = 'Y'
	and EXPIRED_DATE is null )
	)
order by
	LIST_SEQ asc ,
	DESCRIPTION asc
}

OSIPSEAR_FIND_RGSEARCHTYPE {
 	select
	DESCRIPTION ,
	CODE,
	ACTIVE_FLAG
from
	REFERENCE_CODES
where
	domain = 'SEARCH_TYPE'
	and ((ACTIVE_FLAG = 'Y'
	and EXPIRED_DATE is null )
	or ('' = 'ENTER-QUERY' ) )
order by
	DESCRIPTION ,
	LIST_SEQ
}

OSIPSEAR_FIND_RGIDENTIFIERTYPE {
 	select
	DESCRIPTION,
	CODE,
	ACTIVE_FLAG
from
	REFERENCE_CODES
where
	domain = 'ID_TYPE'
	or ('' = 'ENTER-QUERY' )
order by
	DESCRIPTION ,
	LIST_SEQ
}

OSIPSEAR_PERADDR_FIND_V_PERSON_ADDRESSES {
 	select
	*
from
	V_PERSON_ADDRESSES
where
	PERSON_ID = :personId
order by
	primary_flag desc,
	mail_flag desc,
	active_flag desc,
	coalesce ( start_date,
	'01-JAN-1900' ) desc
}
OSIPSEAR_PERIDENT_FIND_PERSON_IDENTIFIERS {
 	SELECT PERSON_ID ,ID_SEQ ,IDENTIFIER_TYPE ,IDENTIFIER ,ISSUED_AUTHORITY_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,ISSUED_DATE ,SEAL_FLAG   FROM PERSON_IDENTIFIERS  WHERE PERSON_ID = :personId
}
OSIPSEAR_PERIDENT_INSERT_PERSON_IDENTIFIERS {
	insert into PERSON_IDENTIFIERS(PERSON_ID, ID_SEQ, IDENTIFIER_TYPE, IDENTIFIER, ISSUED_AUTHORITY_TEXT , CREATE_USER_ID, create_datetime, modify_datetime ) values(:personId, ( select coalesce (MAX(ID_SEQ) + 1, 0) from PERSON_IDENTIFIERS where PERSON_ID = :personId), :identifierType, :identifier, :issuedAuthorityText, :createUserId, current_timestamp, NULL)
} 

OSIPSEAR_PERIDENT_UPDATE_PERSON_IDENTIFIERS {
 update PERSON_IDENTIFIERS set IDENTIFIER_TYPE = :identifierType , IDENTIFIER = :identifier , ISSUED_AUTHORITY_TEXT = :issuedAuthorityText , MODIFY_USER_ID = :modifyUserId, modify_datetime = current_timestamp where PERSON_ID = :personId and ID_SEQ = :idSeq 
} 

OSIPSEAR_PERIDENT_DELETE_PERSON_IDENTIFIERS { 
	DELETE FROM PERSON_IDENTIFIERS WHERE PERSON_ID  = :personId AND ID_SEQ  = :idSeq
} 

OSIPSEAR_IMAGE_FIND_IMAGES {
 	SELECT IMAGE_ID ,CAPTURE_DATE ,IMAGE_OBJECT_TYPE ,IMAGE_OBJECT_ID ,IMAGE_OBJECT_SEQ ,IMAGE_VIEW_TYPE ,IMAGE_THUMBNAIL ,ACTIVE_FLAG ,ORIENTATION_TYPE ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM IMAGES WHERE  IMAGE_OBJECT_TYPE = 'PERSON' AND IMAGE_OBJECT_ID = :personId AND IMAGE_THUMBNAIL IS NOT NULL AND ACTIVE_FLAG='Y'
}
OSIPSEAR_PERINFO_FIND_PERSONS {
 	SELECT PERSON_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,BIRTHDATE ,OCCUPATION_CODE ,CRIMINAL_HISTORY_TEXT ,NAME_TYPE ,ALIAS_PERSON_ID ,ROOT_PERSON_ID ,LANGUAGE_CODE ,COMPREHEND_ENGLISH_FLAG ,SEX ,BIRTH_PLACE ,EMPLOYER ,PROFILE_CODE ,INTERPRETER_REQUIRED ,PRIMARY_LANGUAGE_CODE ,MEMO_TEXT ,SUSPENDED_FLAG ,MARITAL_STATUS ,CITIZENSHIP ,DECEASED_DATE ,CORONER_NUMBER ,ATTENTION ,CARE_OF ,SUSPENDED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,STAFF_FLAG ,REMITTER_FLAG ,LAST_NAME_SOUNDEX ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,LAST_NAME_KEY ,SEAL_FLAG, SECOND_MIDDLE_NAME, TITLE, NOTES, GENDER, (select description  from  reference_codes rc where domain='GENDER' and code=GENDER) as SEX_DESCRIPTION   FROM PERSONS  WHERE PERSON_ID = :personId
}
OSIPSEAR_PERINFO_UPDATE_PERSONS {
update PERSONS set LAST_NAME = :lastName, FIRST_NAME = :firstName, MIDDLE_NAME = :middleName, SEX = :sex, BIRTHDATE = :birthdate, MARITAL_STATUS = :maritalStatus, LANGUAGE_CODE = :languageCode, INTERPRETER_REQUIRED = :interpreterRequired, DECEASED_DATE = :deceasedDate, STAFF_FLAG = :staffFlag , MODIFY_USER_ID = :modifyUserId, SECOND_MIDDLE_NAME = :secondMiddleName, TITLE = :title, NOTES = :notes, GENDER = :gender, modify_datetime = current_timestamp where PERSON_ID = :personId
} 

OSIPSEAR_PEREMP_FIND_PERSON_EMPLOYMENTS {
 	SELECT PERSON_ID ,EMPLOYMENT_SEQ ,OCCUPATION_CODE ,EMPLOYER_NAME ,HOURS_WEEK ,SCHEDULE_TYPE ,WAGE ,WAGE_PERIOD_CODE ,SUPERVISOR_NAME ,ADDRESS_1 ,ADDRESS_2 ,CITY ,PROV_STATE_CODE ,CONTACT_NUMBER ,CONTACT_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,EMPLOYMENT_DATE ,COMMENT_TEXT ,TERMINATION_DATE ,PHONE_AREA ,PHONE_EXT ,CREATE_DATETIME ,CREATE_USER_ID ,ACTIVE_FLAG ,ADDRESS ,SEAL_FLAG,FORMAT   FROM PERSON_EMPLOYMENTS  WHERE PERSON_ID = :personId ORDER BY EMPLOYMENT_SEQ DESC
}
OSIPSEAR_PEREMP_INSERT_PERSON_EMPLOYMENTS {
insert into PERSON_EMPLOYMENTS(PERSON_ID, EMPLOYMENT_SEQ, EMPLOYER_NAME, CONTACT_NUMBER, PHONE_EXT, ACTIVE_FLAG, ADDRESS, CREATE_USER_ID, FORMAT, create_datetime, modify_datetime) values (:personId, ( select coalesce(max(EMPLOYMENT_SEQ)+ 1, 0) from PERSON_EMPLOYMENTS where PERSON_ID = :personId), :employerName, :contactNumber, :phoneExt, :activeFlag, :address, :createUserId, :format, current_timestamp, NULL)
} 


OSIPSEAR_PEREMP_UPDATE_PERSON_EMPLOYMENTS {
 update PERSON_EMPLOYMENTS set EMPLOYER_NAME = :employerName , PHONE_EXT = :phoneExt , ACTIVE_FLAG = :activeFlag , ADDRESS = :address, CONTACT_NUMBER = :contactNumber, MODIFY_USER_ID = :modifyUserId, FORMAT =:format, modify_datetime = current_timestamp where PERSON_ID = :personId and EMPLOYMENT_SEQ = :employmentSeq 
} 

OSIPSEAR_PEREMP_DELETE_PERSON_EMPLOYMENTS { 
	DELETE FROM PERSON_EMPLOYMENTS where PERSON_ID  = :personId and EMPLOYMENT_SEQ  = :employmentSeq
} 

OSIPSEAR_PSPERSONNAME_DELETE_TAG_PERSON_SEARCH.GET_PARTIAL_SOUNDEX_PERSONS { 
	DELETE FROM TAG_PERSON_SEARCH.GET_PARTIAL_SOUNDEX_PERSONS/* where */
} 


OSIPSEAR_PERSONS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM V_PERSON_ADDRESSES V WHERE V.PERSON_ID = :PERSONID
}

OSIPSEAR_PERSONS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM PERSON_IDENTIFIERS P WHERE P.PERSON_ID = :PERSONID
}

OSIPSEAR_PERSONS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM PERSONS P WHERE P.PERSON_ID = :PERSONID
}

OSIPSEAR_PERSONS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM PERSON_EMPLOYMENTS P WHERE P.PERSON_ID = :PERSONID
}

OSIPSEAR_PERSONS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM IMAGES I WHERE I.IMAGE_OBJECT_ID = :PERSONID
}

OSIPSEAR_GET_ADDITIONAL_NAMES{
select person_id ,last_name,first_name ,middle_name,second_middle_name,pers_add_name_id,name_type from person_additional_names where person_id =:personId order by pers_add_name_id asc
}

OSIPSEAR_INSERT_ADDITIONAL_NAMES{
insert into person_additional_names(person_id ,last_name,first_name ,middle_name,second_middle_name,name_type,create_datetime ,create_user_id) 
values(:personId,:lastName,:firstName,:middleName,:middleName2,:nameType,current_timestamp,:createUserId )
}

OSIPSEAR_UPDATE_ADDITIONAL_NAMES{
UPDATE person_additional_names SET  last_name=:lastName, first_name=:firstName, middle_name=:middleName,name_type =:nameType, second_middle_name=:middleName2 ,modify_user_id =:modifyUserId,modify_datetime = current_timestamp  WHERE pers_add_name_id =:persAddNameId 
}

OSIPSEAR_DELETE_ADDITIONAL_NAMES{
delete from person_additional_names where pers_add_name_id =:persAddNameId
}

OSIPSEAR_GET_DATA_FROM_JIS_COMMON_SYSTEM{
select response_payload responseData ,int_correlation_id from external_system_response where int_correlation_id = :intCorrelationId
}

OSIPSEAR_GET_IDENTIFIER_DATA{
select identifier from person_identifiers where person_id =:personId and identifier_type = 'PIN' limit 1
}

OSIPSEAR_GET_ADDITIONAL_NAMES_AS_PARENT{
select person_id,last_name,first_name,middle_name,second_middle_name from person_additional_names 
}

OSIPSEAR_GET_ADDITIONAL_NAME_DETAILS{
SELECT P.BIRTHDATE,PI.IDENTIFIER pin FROM PERSONS P, PERSON_IDENTIFIERS PI WHERE P.PERSON_ID = PI.PERSON_ID AND  P.PERSON_ID =:personId AND PI.IDENTIFIER_TYPE = 'PIN'
}