
OCISCATA_FIND_RGAREAS {
select DESCRIPTION , AREA_CODE CODE , PARENT_AREA_CODE from ( select C.AREA_CLASS , C.AREA_CODE , C.DESCRIPTION , C.LIST_SEQ , C.AREA_TYPE , P.PARENT_AREA_CLASS , P.PARENT_AREA_CODE , P.PARENT_DESCRIPTION , P.PARENT_LIST_SEQ from ( select AREA_TYPE , AREA_CLASS , AREA_CODE , DESCRIPTION , PARENT_AREA_CODE , LIST_SEQ from AREAS where PARENT_AREA_CODE is not null ) C , ( select AREA_CLASS PARENT_AREA_CLASS , AREA_CODE PARENT_AREA_CODE , DESCRIPTION PARENT_DESCRIPTION , LIST_SEQ PARENT_LIST_SEQ from AREAS a where PARENT_AREA_CODE is null and AREA_CLASS = 'REGION' ) P where P.PARENT_AREA_CODE = C.PARENT_AREA_CODE union all select C.AREA_CLASS , C.AREA_CODE , C.DESCRIPTION , C.LIST_SEQ , C.AREA_TYPE , null , null , null , null from AREAS C where AREA_CLASS = 'REGION' and PARENT_AREA_CODE is null ) a where AREA_TYPE = :NBTENVIRONMENTCODE and ( coalesce(:NBTREGIONCODE::text,'')='' or ( :NBTREGIONCODE = PARENT_AREA_CODE and PARENT_AREA_CLASS = 'REGION' ) ) order by DESCRIPTION
}

OCISCATA_FIND_RGPSAGERANGE {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'PS_AGE_RANGE'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCISCATA_FIND_RGPSAVAIL {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'PS_AVAIL'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCISCATA_FIND_RGPSCATEGORY {
 	SELECT REF_CODE.DESCRIPTION , REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'PS_CATEGORY'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION , CODE
}

OCISCATA_FIND_RGPSNEEDS {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'PS_FACILITY'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCISCATA_FIND_RGPSOFFGRPS {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'PS_OFF_GRPS'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCISCATA_FIND_RGPSPROVTYPE {
 	SELECT REF_CODE.DESCRIPTION , REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'PS_PROV_TYPE'    AND ACTIVE_FLAG = 'Y'  ORDER BY ACTIVE_FLAG DESC , LIST_SEQ , DESCRIPTION , CODE
}

OCISCATA_FIND_RGPSSEX {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'PS_SEX'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCISCATA_FIND_RGETHNICITY {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE, REF_CODE.LIST_SEQ   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'ETHNICITY'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCISCATA_FIND_RGREGION {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.AREA_CODE CODE, LIST_SEQ   FROM AREAS REF_CODE  WHERE AREA_CLASS = 'REGION'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCISCATA_FIND_RGSERVICES {
 	SELECT DESCRIPTION , PROGRAM_ID ,PROGRAM_CODE CODE, LIST_SEQ  FROM PROGRAM_SERVICES  WHERE PROGRAM_CLASS = 'PRG'    AND ACTIVE_FLAG = 'Y'     AND PROGRAM_CATEGORY = :PROGRAMCATEGORY ORDER BY LIST_SEQ , DESCRIPTION
}

OCISCATA_FIND_RGCSLDCODE {
 	SELECT DESCRIPTION , CODE, LIST_SEQ   FROM REFERENCE_CODES  WHERE DOMAIN = 'CSLD_CODE'    AND ACTIVE_FLAG = 'Y'     AND CODE IN ('INST' ,'COMM' ) ORDER BY LIST_SEQ , DESCRIPTION
}

OCISCATA_FIND_RGTEAMAGYLOCS {
select a.description, a.team_id, a.team_code from automation_teams a where a.active_flag = 'Y' and exists ( select 1 from agency_locations agl where agl.agy_loc_id in (select tal.agy_loc_id from team_agency_loc tal where a.team_id = tal.team_id ) and agency_location_type = 'COMM' ) order by a.description
}

OCISCATA_FIND_RGCORPLOCS {
 	SELECT C.CORPORATE_ID  ,C.CORPORATE_NAME    FROM CORPORATES C ,CORPORATE_TYPES CT  WHERE C.CORPORATE_ID = CT.CORPORATE_ID AND CT.CORPORATE_TYPE = :NBTPROGRAMCATEGORY    AND C.ACTIVE_FLAG = 'Y' ORDER BY CORPORATE_NAME
}

OCISCATA_FIND_RGAGYLOCS {
 	SELECT AGY_LOC_ID CODE , DESCRIPTION, LIST_SEQ  FROM AGENCY_LOCATIONS  WHERE AGENCY_LOCATION_TYPE = 'INST'    AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ ,DESCRIPTION
}

OCISCATA_FIND_RGAGYLOCCL {
 	SELECT AL.DESCRIPTION ,CAL.AGY_LOC_ID   FROM CASELOAD_AGENCY_LOCATIONS CAL , AGENCY_LOCATIONS AL  WHERE CAL.AGY_LOC_ID = AL.AGY_LOC_ID    AND CAL.CASELOAD_ID = :CASELOADID    AND CAL.AGY_LOC_ID NOT IN ( 'OUT' , 'TRN'  )
}

OCISCATA_FIND_RGTEAMUNPAIDWK {
 	SELECT t.description description, to_char(tm.team_id) code, t.team_code team_code FROM team_staff_members tm, automation_teams t WHERE tm.active_flag = 'Y' AND t.active_flag = 'Y' AND t.team_id = tm.team_id AND tm.staff_id IN ( SELECT staff_id FROM staff_members WHERE user_id = :userName ) AND t.team_id IN ( SELECT team_id FROM team_functions WHERE function_type = 'UNPAID_WORK' ) ORDER BY t.description, t.team_code
}

OCISCATA_FIND_RGPROVIDERDTTO {
 	select
	CORPORATE_NAME PROVIDER_NAME ,
	CORPORATE_ID PROVIDER_ID
from
	CORPORATES
where
	CORPORATE_ID in (
	select
		CORPORATE_ID
	from
		CORPORATE_TYPES
	where
		CORPORATE_TYPE = 'PROG' )
	and ACTIVE_FLAG = 'Y'
order by
	CORPORATE_NAME
}

OCISCATA_FIND_RGTEAMACP {
 	SELECT t.description description, tm.team_id code, t.team_code team_code FROM team_staff_members tm, automation_teams t WHERE tm.active_flag = 'Y' AND t.active_flag = 'Y' AND t.team_id = tm.team_id AND tm.staff_id IN ( SELECT staff_id FROM staff_members WHERE user_id = :userName ) AND t.team_id IN ( SELECT team_id FROM team_functions WHERE function_type = 'PROGRAMMES' ) ORDER BY t.description, t.team_code;
}

OCISCATA_FIND_RGACPPROVIDERINST {
 	select
	AGY_LOC.DESCRIPTION ,
	AGY_LOC.AGY_LOC_ID AGY_LOC_ID,
	LIST_SEQ
from
	AGENCY_LOCATIONS AGY_LOC
where
	AGENCY_LOCATION_TYPE = 'INST'
	and AGY_LOC_ID in (
	select
		AGY_LOC_ID
	from
		CASELOAD_AGENCY_LOCATIONS
	where
		CASELOAD_ID = :CASELOADID )
	and AGY_LOC_ID not in ('OUT' , 'TRN' )
	and ACTIVE_FLAG = 'Y'
order by
	LIST_SEQ ,
	DESCRIPTION ,
	AGY_LOC_ID
}

OCISCATA_VCRSACT_FIND_V_COURSE_ACTIVITIES {
 	SELECT COURSE_CLASS, CRS_ACTY_ID, COURSE_ACTIVITY_CODE, COURSE_PHASE_ID, PROGRAM_CATEGORY, PROGRAM_CATEGORY_DESC, PROGRAM_ID, PROGRAM_SERVICES_DESC, PHASE_DESC, COURSE_ACTIVITY_DESC, ENVIRONMENT, ENVIRONMENT_DESC, ACTIVE_FLAG, PROVIDER_CLASS, PROVIDER_ID, PROVIDER_CODE, PROVIDER_NAME, PLACEMENT_CORPORATE_ID, AGENCY_CONTACT, SCHEDULE_START_DATE, SCHEDULE_END_DATE, CAPACITY, VACANCY, PQS_NUMBER, COMMENT_TEXT, SERVICES_ADDRESS_ID, SUITE_NUMBER, STREET_INFORMATION, CITY, STATE, POSTAL_CODE, COUNTRY, COUNTRY_DESC, AGY_LOC_ID, AGY_LOC_DESC, AREA_CODE, NOMS_REGION_CODE, INTERNAL_LOCATION_ID, INTERNAL_LOCATION_DESC FROM V_COURSE_ACTIVITIES
}
OCISCATA_VCRSACT_UPDATE_V_COURSE_ACTIVITIES {
	UPDATE V_COURSE_ACTIVITIES set 
}


OCISCATA_V_CRS_ACT_PREQUERY {
	SELECT C.AREA_CODE,NULL FROM AREAS C WHERE AREA_CLASS = ''REGION'' AND PARENT_AREA_CODE IS NULL ) WHERE PARENT_AREA_CODE = '''||:NBTREGIONCODE||''')))
}

OCISCATA_V_CRS_ACT_WHENNEWRECORDINSTANCE {
	SELECT COUNT(*) FROM COURSE_ACTIVITY_PARTIES WHERE CRS_ACTY_ID = :CRSACTYID
}

OCISCATA_OCISCATA_WHENNEWFORMINSTANCE_ {
	select
	distinct ROOT_OFFENDER_ID,
	OFFENDER_ID
from
	OFFENDER_BOOKINGS
where
	OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID
}

OCISCATA_OCISCATA_WHENNEWFORMINSTANCE_ {
	SELECT DESCRIPTION, PROGRAM_ID FROM PROGRAM_SERVICES WHERE PROGRAM_ID = :PPROGRAMID
}

OCISCATA_SETUP_DEFAULTS {
	select
	REF_CODE.CODE
from
	REFERENCE_CODES REF_CODE
where
	domain = 'PS_PROV_TYPE'
	and ACTIVE_FLAG = 'Y'
	and LIST_SEQ = :LIST_SEQ
}
OCISCATA_PROGRAMS_NON_ASSOC_TMP {
SELECT
      LINE,
      OFFENDER_ID,
      OFFENDER_BOOK_ID
    FROM
      PROGRAMS_NON_ASSOC_TMP
    ORDER BY LINE
}
OCISCATA_PROGRAMS_NON_ASSOC_TMP_COUNT {
SELECT COUNT (0) FROM programs_non_assoc_tmp
  }
  
  OCISCATA_CHK_NON_ASS_CONFLICT{
  SELECT
    COUNT(*)
FROM
    OFFENDER_NON_ASSOCIATIONS ONA,
    OFFENDER_NA_DETAILS       OND
WHERE
    ( ( ONA.OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID
        AND ONA.NS_OFFENDER_BOOK_ID = :P_VIS_OFFENDER_BOOK_ID )
      OR ( ONA.OFFENDER_BOOK_ID = :P_VIS_OFFENDER_BOOK_ID
           AND ONA.NS_OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID ) )
    AND OND.OFFENDER_BOOK_ID = ONA.OFFENDER_BOOK_ID
    AND OND.NS_OFFENDER_BOOK_ID = ONA.NS_OFFENDER_BOOK_ID
    AND SYSDATE() >= OND.NS_EFFECTIVE_DATE
    AND (current_date < coalesce(OND.NS_EXPIRY_DATE, current_date +1) 
    OR SYSDATE() <= OND.NS_EFFECTIVE_DATE )
  }
  
  
   OCISCATA_CHK_NONASSOCIATIONS {
	SELECT vbh.last_name || ' ' || vbh.first_name OFFENDER_NAME,vbh.offender_id_display,ona.*  FROM OFFENDER_NON_ASSOCIATIONS ona , V_HEADER_BLOCK_FN(:USERID) vbh
	where ona.offender_book_id=:offenderBookId and ona.NS_OFFENDER_ID in 
	(SELECT  nad.NS_OFFENDER_ID FROM OFFENDER_NA_DETAILS nad 
	where  nad.offender_book_id=:offenderBookId and 
	current_date < coalesce (nad.ns_expiry_date, current_date +1)) and vbh.offender_book_id = ona.ns_offender_book_id

 }
			 OCISCATA_OFFENDER_DETAILS{
 select * from Offenders where offender_id in(
select offender_id  from offender_bookings ob where offender_book_id=:offenderBookId)
 }
 OCISCATA_OFFENDER_DETAILS_EXTERNAL_INDIVIDUAL
 {
select
	*
from
	Offenders
where
	offender_id in(
			(SELECT ns_offender_id  FROM OFFENDER_NON_ASSOCIATIONS ona
	where ona.offender_book_id=:offenderBookId and ona.NS_OFFENDER_ID in 
	(SELECT  nad.NS_OFFENDER_ID FROM OFFENDER_NA_DETAILS nad 
	where  nad.offender_book_id=:offenderBookId and 
	current_date < coalesce(nad.ns_expiry_date, current_date +1)  and current_date >= nad.ns_effective_date)	
		and
ns_offender_book_id in
(select
	offender_book_id 
from
	V_OFFENDER_PROGRAM_PROFILES
where
	CRS_ACTY_ID =:crsActyId
	and OFFENDER_PROGRAM_STATUS = 'ALLOC'
	and ((CRS_ACTY_ID = :crsActyId
		and OFFENDER_PROGRAM_STATUS = 'ALLOC'
		and ((SUSPENDED_FLAG = 'N'
			and OFFENDER_END_DATE is null)
		or ((OFFENDER_END_DATE) > (current_timestamp))))
		and (CRS_ACTY_ID = :crsActyId
			and OFFENDER_PROGRAM_STATUS = 'ALLOC'
			and (SUSPENDED_FLAG = 'N'
				or (OFFENDER_END_DATE) > (current_timestamp)))))))
 }
 OCISCATA_OFFENDER_DETAILS_EXTERNAL_GANG{
select
	*
from
	Offenders
where
	offender_id in(
	select
		offender_id
	from
		offender_bookings ob
	where
		offender_book_id in (
		select
			distinct offender_book_id
		from
			OFFENDER_STG_AFFILIATIONS osa
		where
			( osa.active_flag = 'Y'
				and osa.offender_book_id <> :offenderBookId
				and osa.stg_id in (
				select
					sr.related_stg_id
				from
					STG_RELATIONSHIPS sr
				where
					active_flag = 'Y'
					and sr.stg_id in (
					select
						osa1.stg_id
					from
						OFFENDER_STG_AFFILIATIONS osa1
					where
						osa1.offender_book_id = :offenderBookId
						and active_flag = 'Y')))
			and osa.offender_book_id in
	(
			select
				offender_book_id
			from
				V_OFFENDER_PROGRAM_PROFILES
			where
				CRS_ACTY_ID =:crsActyId
				and OFFENDER_PROGRAM_STATUS = 'ALLOC'
				and ((CRS_ACTY_ID = :crsActyId
					and OFFENDER_PROGRAM_STATUS = 'ALLOC'
					and ((SUSPENDED_FLAG = 'N'
						and OFFENDER_END_DATE is null)
					or ((OFFENDER_END_DATE) > (current_timestamp))))
					and (CRS_ACTY_ID = :crsActyId
						and OFFENDER_PROGRAM_STATUS = 'ALLOC'
						and (SUSPENDED_FLAG = 'N'
							or (OFFENDER_END_DATE) > (current_timestamp)))) )
 ))
 }
 OCISCATA_OFFENDER_NAME_BY_ID
 {
 select  concat(last_name || ',' || first_name)  from offenders where offender_id =:offenderId
 }