OCUPAOFF_VOFFPRGPROFILES_FIND_V_OFFENDER_PROGRAM_PROFILES {
 SELECT OFF_PRGREF_ID, OFFENDER_BOOK_ID, OFFENDER_ID, OFFENDER_ID_DISPLAY, AGE, FIRST_NAME, LAST_NAME, OFFENDER_NAME, SEX_CODE, RACE_CODE, OFFENDER_ALERT, OFFENCE_TYPES, OFFENDER_PROGRAM_STATUS, PROGRAM_ID, OFFENDER_START_DATE, OFFENDER_END_DATE, CRS_ACTY_ID, SUSPENDED_FLAG FROM V_OFFENDER_PROGRAM_PROFILES  
}
