
OIDACSEL_SCHEDULEDACTIVITIES_FIND_V_PRISON_ACTIVITIES {
 	SELECT CRS_ACTY_ID ,SERVICE ,PROGRAM_ID ,ACTIVITY ,AGY_LOC_ID ,AGY_LOC_DESC ,SCHEDULE_START_DATE ,SCHEDULE_END_DATE ,INTERNAL_LOCATION_ID ,INTERNAL_LOCATION_DESC ,ACTIVE_FLAG ,LIST_SEQ ,PROGRAM_CODE   FROM V_PRISON_ACTIVITIES 
 	where program_id = :programId and agy_loc_id = :agyLocId 
}
