
OIDSCHAC_SCHACT_FIND_V_SCHD_PRISON_ACTIVITIES {
SELECT CRS_ACTY_ID, CRS_SCH_ID, SERVICE, PROGRAM_ID, ACTIVITY,  START_TIME,  END_TIME, SCHEDULE_DATE, AGY_LOC_ID, AGY_LOC_DESC,
 	SCHEDULE_START_DATE, SCHEDULE_END_DATE, INTERNAL_LOCATION_ID, INTERNAL_LOCATION_DESC  FROM V_SCHD_PRISON_ACTIVITIES
 	where program_id = :programId and  agy_loc_id = :agyLocId 
 	and SCHEDULE_DATE =  :scheduleDate
}
