GET_OFF_DETAILS{
SELECT o.offender_id_display offender_id_display, o.last_name last_name, o.first_name first_name FROM offenders o WHERE o.offender_id = :p_offender_id
}

TAG_CORE_REMOVE_STRING_INSTR{
select INSTR(:P_MAIN_STRING, :P_SUB_STRING) from DUAL
}

TAG_CORE_REMOVE_STRING_SUBSTR{
SELECT  SUBSTR(:P_MAIN_STRING, 1, :V_POS - 1) FROM DUAL
}

TAG_CORE_REMOVE_STRING_SUBSTRING_ONE{
SELECT   SUBSTR(:P_MAIN_STRING,:V_POS+:V_LENGTH, LENGTH(:P_MAIN_STRING)) FROM DUAL
}

TAG_CORE_REMOVE_STRING_SUBSTR_ONE{
SELECT   SUBSTR(:P_MAIN_STRING,:V_POS+:V_LENGTH, LENGTH(:P_MAIN_STRING)) FROM DUAL
}