
OIICMOCI_FIND_RGAGYLOCID {
 	SELECT AGY_LOC.DESCRIPTION , AGY_LOC.AGY_LOC_ID CODE, AGY_LOC.ACTIVE_FLAG   FROM AGENCY_LOCATIONS AGY_LOC  WHERE AGENCY_LOCATION_TYPE = 'INST'    AND AGY_LOC.AGY_LOC_ID NOT IN ('OUT' , 'TRN' )    AND EXISTS (           SELECT 'X'             FROM CASELOAD_AGENCY_LOCATIONS CAL            WHERE CAL.AGY_LOC_ID = AGY_LOC.AGY_LOC_ID              AND CAL.CASELOAD_ID = :CASELOADID )
}

OIICMOCI_FIND_RGLU1 {
   	SELECT LU.LIVING_UNIT_CODE , LU.LIVING_UNIT_ID , LU.ACTIVE_FLAG  FROM LIVING_UNITS LU  WHERE AGY_LOC_ID = :AGYLOCID    AND ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID IS NULL
}

OIICMOCI_FIND_RGLU2 {
 	SELECT LU.LIVING_UNIT_CODE , LU.LIVING_UNIT_ID , LU.ACTIVE_FLAG   FROM LIVING_UNITS LU  WHERE AGY_LOC_ID = :AGYLOCID    AND ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID = :NBTLIVINGUNITID1
}

OIICMOCI_FIND_RGLU3 {
 	SELECT LU.LIVING_UNIT_CODE , LU.LIVING_UNIT_ID , LU.ACTIVE_FLAG   FROM LIVING_UNITS LU  WHERE AGY_LOC_ID = :AGYLOCID    AND ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID = :NBTLIVINGUNITID2
}

OIICMOCI_OFFSCH_FIND_V_COURT_EVENTS {
 	SELECT EVENT_ID ,EVENT_CLASS ,EVENT_TYPE ,CASE_ID ,CASE_INFO_PREFIX ,CASE_INFO_NUMBER ,OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,BIRTH_DATE ,OFFENDER_BOOK_ID ,BOOKING_ACTIVE_FLAG ,LIVING_UNIT_ID ,LEVEL_1_CODE ,LEVEL_2_CODE ,LEVEL_3_CODE ,LEVEL_4_CODE ,OFFENDER_AGY_LOC_ID ,OFFENDER_AGY_LOC_DESC ,EVENT_DATE ,START_TIME ,END_TIME ,COURT_EVENT_TYPE ,COURT_EVENT_TYPE_DESC ,MOVEMENT_REASON_CODE ,MOVEMENT_REASON_DESC ,JUDGE_NAME ,EVENT_STATUS ,RESULT_CODE ,PARENT_EVENT_ID ,AGY_LOC_ID ,AGY_LOC_ID_NAME ,COMMENT_TEXT ,EVENT_OUTCOME ,CHECK_SUM, APPEARANCE_TYPE, APPEARANCE_LOCATION,OUTCOME_REASON_CODE   FROM V_COURT_EVENTS 
}
