
OIIDMOVE_FIND_CGFKOFFEMMOVEMENTREASONCO {
 	SELECT REF_CODE.CODE   ,REF_CODE.DOMAIN,REF_CODE.DESCRIPTION ,REF_CODE.EXPIRED_DATE,REF_CODE.ACTIVE_FLAG ,REF_CODE.LIST_SEQ  FROM REFERENCE_CODES REF_CODE 
	WHERE DOMAIN = 'MOVE_RSN' ORDER BY  REF_CODE.LIST_SEQ
}

OIIDMOVE_FIND_CGFKOFFEMMOVEMENTTYPE {
 	SELECT REF_CODE.CODE   ,REF_CODE.DOMAIN,REF_CODE.DESCRIPTION ,REF_CODE.EXPIRED_DATE,REF_CODE.ACTIVE_FLAG ,REF_CODE.LIST_SEQ  FROM REFERENCE_CODES REF_CODE 
	WHERE DOMAIN = 'MOVE_TYPE' ORDER BY  REF_CODE.LIST_SEQ
}

OIIDMOVE_OFFEM_FIND_V_OFF_EXT_MOVEMENTS {
 	SELECT OFFENDER_BOOK_ID ,OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,MOVEMENT_SEQ ,MOVEMENT_DATE ,MOVEMENT_TIME ,INTERNAL_SCHEDULE_TYPE ,INTERNAL_SCHEDULE_REASON_CODE ,MOVEMENT_TYPE ,MOVEMENT_REASON_CODE ,DIRECTION_CODE ,ARREST_AGENCY_LOC_ID ,TO_PROV_STAT_CODE ,ESCORT_CODE ,FROM_AGY_LOC_ID ,FROM_AGY_LOC_DESC ,TO_AGY_LOC_ID ,TO_AGY_LOC_DESC ,ACTIVE_FLAG ,ESCORT_TEXT ,COMMENT_TEXT ,REPORTING_DATE ,TO_CITY ,TO_CITY_DESC ,FROM_CITY ,FROM_CITY_DESC ,REPORTING_TIME ,TO_ADDRESS_ID ,TO_ADDRESS_DESC ,FROM_ADDRESS_ID ,FROM_ADDRESS_DESC,SEAL_FLAG   FROM V_OFF_EXT_MOVEMENTS  
}
OIIDMOVE_OFFEM_INSERT_V_OFF_EXT_MOVEMENTS {
	INSERT INTO V_OFF_EXT_MOVEMENTS(OFFENDER_BOOK_ID ,OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,MOVEMENT_SEQ ,MOVEMENT_DATE ,MOVEMENT_TIME ,INTERNAL_SCHEDULE_TYPE ,INTERNAL_SCHEDULE_REASON_CODE ,MOVEMENT_TYPE ,MOVEMENT_REASON_CODE ,DIRECTION_CODE ,ARREST_AGENCY_LOC_ID ,TO_PROV_STAT_CODE ,ESCORT_CODE ,FROM_AGY_LOC_ID ,FROM_AGY_LOC_DESC ,TO_AGY_LOC_ID ,TO_AGY_LOC_DESC ,ACTIVE_FLAG ,ESCORT_TEXT ,COMMENT_TEXT ,REPORTING_DATE ,TO_CITY ,TO_CITY_DESC ,FROM_CITY ,FROM_CITY_DESC ,REPORTING_TIME ,TO_ADDRESS_ID ,TO_ADDRESS_DESC ,FROM_ADDRESS_ID ,FROM_ADDRESS_DESC ) VALUES(:offenderBookId ,:offenderIdDisplay ,:lastName ,:firstName ,:movementSeq ,:movementDate ,:movementTime ,:internalScheduleType ,:internalScheduleReasonCode ,:movementType ,:movementReasonCode ,:directionCode ,:arrestAgencyLocId ,:toProvStatCode ,:escortCode ,:fromAgyLocId ,:fromAgyLocDesc ,:toAgyLocId ,:toAgyLocDesc ,:activeFlag ,:escortText ,:commentText ,:reportingDate ,:toCity ,:toCityDesc ,:fromCity ,:fromCityDesc ,:reportingTime ,:toAddressId ,:toAddressDesc ,:fromAddressId ,:fromAddressDesc )
}


OIIDMOVE_CGFKCHK_OFF_EM_OFF_EM_REF_MOV_ {
	SELECT REF_CODE1.DOMAIN ,REF_CODE1.DESCRIPTION ,REF_CODE1.EXPIRED_DATE ,REF_CODE1.ACTIVE_FLAG ,REF_CODE1.LIST_SEQ FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :MOVEMENTREASONCODE AND     DOMAIN = 'MOVE_RSN'
}

OIIDMOVE_CGFKCHK_OFF_EM_OFF_EM_MOVE_RS_ {
	SELECT  '1' FROM   MOVEMENT_REASONS WHERE  MOVEMENT_REASON_CODE = :MOVEMENTREASONCODE
}

OIIDMOVE_CGFKCHK_OFF_EM_OFF_EM_DIRECTI_ {
	SELECT  '1' FROM   REFERENCE_CODES WHERE  CODE = :DIRECTIONCODE
}

OIIDMOVE_CGFKCHK_OFF_EM_OFF_EM_MOVE_RE_ {
	SELECT REF_CODE.DOMAIN ,REF_CODE.DESCRIPTION ,REF_CODE.EXPIRED_DATE ,REF_CODE.ACTIVE_FLAG ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :MOVEMENTTYPE AND     DOMAIN = 'MOVE_TYPE'
}

OIIDMOVE_CGFKCHK_OFF_EM_OFF_EM_V_HEADE_ {
	SELECT B.ACTIVE_FLAG ,O.OFFENDER_ID FROM   OFFENDERS O,OFFENDER_BOOKINGS B WHERE O.OFFENDER_ID = B.OFFENDER_ID AND   B.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIIDMOVE_CGFKLKP_OFF_EM_OFF_EM_V_HEADE_ {
	SELECT V_OFF_BKG.OFFENDER_BOOK_ID ,V_OFF_BKG.ACTIVE_FLAG ,V_OFF_BKG.OFFENDER_ID FROM   V_HEADER_BLOCK_FN(:USERID) V_OFF_BKG WHERE  V_OFF_BKG.OFFENDER_ID_DISPLAY = :OFFENDERIDDISPLAY AND    V_OFF_BKG.LAST_NAME = :LASTNAME
}
