
OUMRCODE_REFDMN_FIND_REFERENCE_DOMAINS {
 	SELECT DOMAIN ,DESCRIPTION ,DOMAIN_STATUS ,OWNER_CODE ,APPLN_CODE ,OLD_CODE_TABLE ,PARENT_DOMAIN ,CODE_LENGTH ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SUPER_SET_DOMAIN ,SEAL_FLAG   FROM REFERENCE_DOMAINS 
} 
OUMRCODE_REFDMN_INSERT_REFERENCE_DOMAINS {
insert into REFERENCE_DOMAINS(domain , DESCRIPTION , DOMAIN_STATUS , OWNER_CODE , APPLN_CODE , OLD_CODE_TABLE , PARENT_DOMAIN , CODE_LENGTH , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID , SUPER_SET_DOMAIN , SEAL_FLAG ) values(:domain , :description , :domainStatus , :ownerCode , :applnCode , :oldCodeTable , :parentDomain , :codeLength , CURRENT_TIMESTAMP , :createUserId , NULL , NULL , :superSetDomain , :sealFlag ) 
}

OUMRCODE_REFDMN_UPDATE_REFERENCE_DOMAINS {
UPDATE REFERENCE_DOMAINS set DOMAIN  = :domain ,DESCRIPTION  = :description ,DOMAIN_STATUS  = :domainStatus ,OWNER_CODE  = :ownerCode ,APPLN_CODE  = :applnCode ,OLD_CODE_TABLE  = :oldCodeTable ,PARENT_DOMAIN  = :parentDomain ,CODE_LENGTH  = :codeLength ,
		MODIFY_DATETIME  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  =:modifyUserId ,SUPER_SET_DOMAIN  = :superSetDomain ,SEAL_FLAG  = :sealFlag  where DOMAIN  = :domain
}

OUMRCODE_REFCODE_FIND_REFERENCE_CODES {
 	SELECT DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM REFERENCE_CODES WHERE DOMAIN = :domain order by LIST_SEQ, DESCRIPTION
}
OUMRCODE_REFCODE_INSERT_REFERENCE_CODES {
 insert into REFERENCE_CODES(domain , CODE , DESCRIPTION , LIST_SEQ , ACTIVE_FLAG , SYSTEM_DATA_FLAG , MODIFY_USER_ID , EXPIRED_DATE , NEW_CODE , PARENT_CODE , PARENT_DOMAIN , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:domain , :code , :description , :listSeq , :activeFlag , :systemDataFlag , null, :expiredDate , :newCode , :parentCode , :parentDomain , CURRENT_TIMESTAMP, :createUserId , null , :sealFlag ) 
}

OUMRCODE_REFCODE_UPDATE_REFERENCE_CODES {
	UPDATE REFERENCE_CODES set DOMAIN  = :domain ,CODE  = :code ,DESCRIPTION  = :description ,LIST_SEQ  = :listSeq ,ACTIVE_FLAG  = :activeFlag ,SYSTEM_DATA_FLAG  = :systemDataFlag ,MODIFY_USER_ID  = :modifyUserId ,EXPIRED_DATE  = :expiredDate ,NEW_CODE  = :newCode ,PARENT_CODE  = :parentCode ,PARENT_DOMAIN  = :parentDomain ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,SEAL_FLAG  = :sealFlag  where DOMAIN  = :domain and CODE  = :code
}


OUMRCODE_CGFKCHK_REF_DMN_RFE_DMN_REF_D {
	SELECT  '1' FROM   REFERENCE_DOMAINS WHERE  DOMAIN = :PARENTDOMAIN
}

OUMRCODE_CGUVCHK_REFERENCE_DOMAINS_PK_ {
	SELECT  '1' FROM    REFERENCE_DOMAINS WHERE   ( P_ROWID IS NULL OR ROWID <> P_ROWID ) AND     DOMAIN = P_DOMAIN
} 

OUMRCODE_CGUVCHK_REFERENCE_CODES_PK {
	SELECT  '1' FROM    REFERENCE_CODES WHERE   DOMAIN = :P_DOMAIN AND     CODE = :P_CODE
}

OUMRCODE_CGRICHK_REFERENCE_DOMAINS_ {
	SELECT '1' FROM REFERENCE_DOMAINS REF_DMN WHERE REF_DMN.PARENT_DOMAIN = :P_DOMAIN
}
