CHECK_USER_EXIST {
select count(*) from oms_users_list where user_id = :userName
}
SAVE_ENCRYPT_PWD {
	insert into AD_USER (USER_ID, PWD) values(:userId, :pwd)
}
CHECK_EMAIL_EXIST {
select count(*) from staff_members where UPPER(MAIL_ID)=UPPER(:emailId)
}
STAFF_FIND_STAFF_MEMBERS {
 	SELECT STAFF_ID ,ASSIGNED_CASELOAD_ID ,WORKING_STOCK_LOC_ID ,WORKING_CASELOAD_ID ,USER_ID,USER_ID USERIDVAL ,BADGE_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,ABBREVIATION ,POSITION ,BIRTHDATE ,TERMINATION_DATE ,UPDATE_ALLOWED_FLAG ,DEFAULT_PRINTER_ID ,SUSPENDED_FLAG ,SUPERVISOR_STAFF_ID ,COMM_RECEIPT_PRINTER_ID ,PERSONNEL_TYPE ,AS_OF_DATE ,EMERGENCY_CONTACT ,ROLE ,SEX_CODE ,STATUS ,SUSPENSION_DATE ,SUSPENSION_REASON ,FORCE_PASSWORD_CHANGE_FLAG ,LAST_PASSWORD_CHANGE_DATE ,LICENSE_CODE ,LICENSE_EXPIRY_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,TITLE ,NAME_SEQUENCE ,QUEUE_CLUSTER_ID ,FIRST_LOGON_FLAG ,SUFFIX ,SEAL_FLAG ,MAIL_ID  FROM STAFF_MEMBERS where UPPER(MAIL_ID)=UPPER(:emailId) 
}

OUMUCREAT_INSERT_OMS_USERS_LIST {
insert into OMS_USERS_LIST(USER_ID, password, CREATE_DATETIME, FAILED_LOGIN_ATTEMPTS, CREATE_USER_ID) values(:userId, :password, CURRENT_TIMESTAMP, :failedLoginAttempts, :createUserId)
}

OUMUCREAT_GET_PWD {
	SELECT PASSWORD  FROM OMS_USERS_LIST WHERE USER_ID = (SELECT USER_ID FROM STAFF_MEMBERS WHERE MAIL_ID = :mailId)

}
OUMUCREAT_UPDATE_OMS_USERS_LIST {
  UPDATE OMS_USERS_LIST SET PASSWORD = :password, MODIFY_USER_ID=:modifyUserId, MODIFY_DATETIME=current_timestamp where USER_ID = :userId
}

AD_USER_DETAILS {
 select user_id from staff_members where ad_user = 'Y'
}
