INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
 SELECT 'OCDIPLANDIALOG', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL  
  WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OCDIPLANDIALOG' AND role_id = 444);
  
INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
 SELECT 'OIPASINF', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL  
  WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OIPASINF' AND role_id = 444);