OMS_INTAKE_REF_CUR{
SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = :lvDomain AND CODE = :pSupLevel           
}

OMS_INTAKE_SYS_CUR{
select
	PROFILE_VALUE profileValue,
	PROFILE_VALUE_2 profileValue2
from
	SYSTEM_PROFILES
where
	PROFILE_TYPE = 'CLIENT'
	and PROFILE_CODE = 'PENDING_STAT'
}