
OIDREMCS_FIND_CGFKHOUSINGLEVEL1 {
 	select
	distinct LIV_UNIT.internal_location_code LIVING_UNIT_CODE ,
	LIV_UNIT.internal_location_id LIVING_UNIT_ID1,
	DESCRIPTION
from
	(
	select
		internal_location_code,
		internal_location_id,
		DESCRIPTION,
		ACTIVE_FLAG,
		parent_internal_location_id
	from
		agency_internal_locations ail
	where
		ail.unit_type is not null
		and ail.unit_type::text <> ''::text) LIV_UNIT ,
	AGENCY_REPORTING_LOCS ARL
where
	ARL.COUNT_TYPE_ID = :COUNTTYPEID
	and LIV_UNIT.ACTIVE_FLAG = 'Y'
	and ARL.ACTIVE_FLAG = 'Y'
	and LIV_UNIT.internal_location_id = ARL.LOCATION1_ID
	and parent_internal_location_id is null
	and ARL.LOCATION_TYPE = 'HOUS'
	and exists (
	select
		ALC.COUNT_TYPE_ID
	from
		AGENCY_LOCATION_COUNTS ALC ,
		AGENCY_COUNTS AC ,
		TEMP_OIDCOUNT OI
	where
		ALC.REPORTING_LOC_ID = AC.REPORTING_LOC_ID
		and ALC.REPORTING_LOC_ID = OI.REPORTING_LOC_ID
		and ALC.COUNT_TYPE_ID = OI.COUNT_TYPE_ID
		and ALC.AGY_SEQ = OI.AGY_SEQ
		and ALC.COUNT_TYPE_ID = ARL.COUNT_TYPE_ID
		and ALC.AGY_SEQ = ARL.AGY_SEQ
		and OUTCOME is null )
order by
	LIVING_UNIT_CODE
}

OIDREMCS_FIND_CGFKHOUSINGLEVEL2 {
 	SELECT DISTINCT LIV_UNIT.LIVING_UNIT_CODE LIVING_UNIT_CODE2 ,
 	LIV_UNIT.LIVING_UNIT_ID LIVING_UNIT_ID2 ,
                DESCRIPTION   FROM LIVING_UNITS LIV_UNIT ,
                AGENCY_REPORTING_LOCS ARL  WHERE ARL.COUNT_TYPE_ID = :COUNTTYPEID    AND LIV_UNIT.ACTIVE_FLAG = 'Y'
 	AND ARL.ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID = :NBTLIVUNITID1    
 	AND LIV_UNIT.LIVING_UNIT_ID = ARL.LOCATION2_ID    AND ARL.LOCATION_TYPE = 'HOUS'    
 	AND EXISTS (SELECT ALC.COUNT_TYPE_ID FROM AGENCY_LOCATION_COUNTS ALC , AGENCY_COUNTS AC , TEMP_OIDCOUNT OI
 	WHERE ALC.REPORTING_LOC_ID = AC.REPORTING_LOC_ID  AND ALC.REPORTING_LOC_ID = OI.REPORTING_LOC_ID
 	AND ALC.COUNT_TYPE_ID = OI.COUNT_TYPE_ID  AND ALC.AGY_SEQ = OI.AGY_SEQ
 	AND ALC.COUNT_TYPE_ID  = ARL.COUNT_TYPE_ID                
 	AND ALC.AGY_SEQ = ARL.AGY_SEQ
 	AND OUTCOME IS NULL )    ORDER BY LIVING_UNIT_CODE
}

OIDREMCS_FIND_CGFKHOUSINGLEVEL3 {
	SELECT LIV_UNIT.LIVING_UNIT_CODE, LIV_UNIT.LIVING_UNIT_ID, DESCRIPTION FROM LIVING_UNITS LIV_UNIT, AGENCY_REPORTING_LOCS ARL WHERE 
	ARL.COUNT_TYPE_ID = :COUNTTYPEID AND PARENT_LIVING_UNIT_ID = :NBTLIVUNITID2 AND LIV_UNIT.LIVING_UNIT_ID = ARL.LOCATION3_ID AND ARL.ACTIVE_FLAG = 'Y' 
	AND LIV_UNIT.ACTIVE_FLAG = 'Y' AND ARL.LOCATION_TYPE = 'HOUS' AND EXISTS (SELECT ALC.COUNT_TYPE_ID FROM AGENCY_LOCATION_COUNTS ALC, AGENCY_COUNTS AC, TEMP_OIDCOUNT OI WHERE 
	ALC.REPORTING_LOC_ID = AC.REPORTING_LOC_ID AND ALC.REPORTING_LOC_ID = OI.REPORTING_LOC_ID AND ALC.COUNT_TYPE_ID = OI.COUNT_TYPE_ID AND ALC.AGY_SEQ = OI.AGY_SEQ AND 
	ALC.COUNT_TYPE_ID = ARL.COUNT_TYPE_ID AND ALC.AGY_SEQ = ARL.AGY_SEQ AND OUTCOME IS NULL ) ORDER BY LIVING_UNIT_CODE
}

OIDREMCS_FIND_CGFKINITLOCCODE {
 	SELECT VIL.INTERNAL_LOCATION_CODE LOCATION_CODE ,        VIL.INTERNAL_LOCATION_ID AGENCY_IML_ID ,
 	VIL.INTERNAL_LOCATION_DESC DESCRIPTION   FROM  V_INT_LOC_SUMMARIES VIL ,
 	AGENCY_REPORTING_LOCS ARL  WHERE ARL.COUNT_TYPE_ID = :COUNTTYPEID
 	AND VIL.ACTIVE_FLAG = 'Y'    AND ARL.ACTIVE_FLAG = 'Y'    
 	AND VIL.INTERNAL_LOCATION_ID = ARL.LOCATION1_ID    
 	AND ARL.LOCATION_TYPE = 'INIT'    AND EXISTS (SELECT ALC.COUNT_TYPE_ID    FROM AGENCY_LOCATION_COUNTS ALC , AGENCY_COUNTS AC ,
 	TEMP_OIDCOUNT OI                 WHERE ALC.REPORTING_LOC_ID = AC.REPORTING_LOC_ID
 	AND ALC.REPORTING_LOC_ID = OI.REPORTING_LOC_ID                   AND ALC.COUNT_TYPE_ID = OI.COUNT_TYPE_ID
 	AND ALC.AGY_SEQ = OI.AGY_SEQ                   AND ALC.COUNT_TYPE_ID  = ARL.COUNT_TYPE_ID
 	AND ALC.AGY_SEQ = ARL.AGY_SEQ                   AND OUTCOME IS NULL )      ORDER BY LOCATION_CODE
 	
}

OIDREMCS_FIND_CGFKCONDUCTEDBY {
 	SELECT USER_ID, FIRST_NAME, LAST_NAME, STAFF_ID  FROM STAFF_MEMBERS WHERE STATUS = 'ACTIVE'  ORDER BY 1
}

OIDREMCS_SUBREMCNT_FIND_AGENCY_LOCATION_COUNTS {
 	SELECT REPORTING_LOC_ID ,COUNT_TYPE_ID ,AGY_SEQ ,DATE_SUBMITTED ,ACTUAL_COUNT ,REPORTED_COUNT ,CONDUCTED_BY_USERID ,ENTERED_BY_USERID ,CONDUCTED_DATETIME ,RECOUNT_RSN_CODE ,DISCREP_RSN_CODE ,RSN_CODE_USERID ,RSN_CODE_DATETIME ,RCNT_CONDUCTED_BY ,RCNT_DATETIME ,RCNT_IN_PROGRESS_FLAG ,RECOUNT_TOTAL ,COMMENT_TEXT ,VERIFIED_USER_ID ,VERIFIED_DATETIME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM AGENCY_LOCATION_COUNTS  /* where  */
}
OIDREMCS_SUBREMCNT_INSERT_AGENCY_LOCATION_COUNTS {
	insert
	into
	AGENCY_LOCATION_COUNTS(REPORTING_LOC_ID ,
	COUNT_TYPE_ID ,
	AGY_SEQ ,
	DATE_SUBMITTED ,
	ACTUAL_COUNT ,
	REPORTED_COUNT ,
	CONDUCTED_BY_USERID ,
	ENTERED_BY_USERID ,
	CONDUCTED_DATETIME ,
	RECOUNT_RSN_CODE ,
	DISCREP_RSN_CODE ,
	RSN_CODE_USERID ,
	RSN_CODE_DATETIME ,
	RCNT_CONDUCTED_BY ,
	RCNT_DATETIME ,
	RCNT_IN_PROGRESS_FLAG ,
	RECOUNT_TOTAL ,
	COMMENT_TEXT ,
	VERIFIED_USER_ID ,
	VERIFIED_DATETIME ,
	CREATE_DATETIME ,
	CREATE_USER_ID ,
	SEAL_FLAG )
values(:reportingLocId ,
:countTypeId ,
:agySeq ,
:dateSubmitted ,
:actualCount ,
:reportedCount ,
:conductedByUserid ,
:enteredByUserid ,
:conductedDatetime ,
:recountRsnCode ,
:discrepRsnCode ,
:rsnCodeUserid ,
:rsnCodeDatetime ,
:rcntConductedBy ,
:rcntDatetime ,
:rcntInProgressFlag ,
:recountTotal ,
:commentText ,
:verifiedUserId ,
:verifiedDatetime ,
CURRENT_TIMESTAMP ,
:createUserId ,
:sealFlag )

}

OIDREMCS_SUBREMCNT_UPDATE_AGENCY_LOCATION_COUNTS {
	update
	agency_location_counts
set
	DATE_SUBMITTED = :dateSubmitted ,
	ACTUAL_COUNT = :actualCount,
	REPORTED_COUNT = :reportedCount ,
	CONDUCTED_BY_USERID = :conductedByUserid,
	ENTERED_BY_USERID = :modifyUserId,
	MODIFY_USER_ID = :modifyUserId,
	MODIFY_DATETIME = current_timestamp
	where
	COUNT_TYPE_ID =:countTypeId
	and AGY_SEQ = :agySeq
	and REPORTING_LOC_ID = :reportingLocId
}

OIDREMCS_UPDATE_COUNT_RECORDUPDATE_COUNT_RECORD {
	SELECT AGY_SEQ  FROM AGENCY_REPORTING_LOCS WHERE LOCATION1_ID = :LIV_UNIT_ID
	AND COALESCE(LOCATION2_ID,0) = COALESCE(:LIV_UNIT_ID2,0) 
	AND COALESCE(LOCATION3_ID,0) = COALESCE(:LIV_UNIT_ID3,0)
	AND LOCATION_TYPE = 'HOUS' AND COUNT_TYPE_ID = :COUNT_TYPE_ID
}
OIDREMCS_GET_LIVING_UNIT3{
 SELECT MAX(LOCATION3_ID)  LOCATION3_ID	         
	         FROM AGENCY_REPORTING_LOCS
	        WHERE LOCATION1_ID = :NBT_LIV_UNIT_ID1
	          AND LOCATION2_ID = :NBT_LIV_UNIT_ID2
}

OIDREMCS_GET_HOUSING_LOCATION_LOV_NAMES {
	SELECT INITCAP(HOUSING_LEV_1_CODE) HOUSINGLEVONELABLENAME,INITCAP(HOUSING_LEV_2_CODE) HOUSINGLEVTWOLABLENAME , CASE when INITCAP(HOUSING_LEV_3_CODE) is null then '' else INITCAP(HOUSING_LEV_3_CODE) end  HOUSINGLEVTHREELABLENAME FROM AGENCY_LOCATIONS WHERE AGY_LOC_ID IN (SELECT AGY_LOC_ID FROM AGENCY_COUNT_TYPES WHERE COUNT_TYPE_ID = :COUNTTYPEID)
}

OIDREMCS_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OIDREMCS_UPDATE_COUNT_RECORDUPDATE_COUNT_VALUE{
	SELECT AGY_SEQ  FROM AGENCY_REPORTING_LOCS 
	WHERE LOCATION1_ID = :INTERNAL_LOCATION_ID AND LOCATION_TYPE = 'INIT' AND COUNT_TYPE_ID = :COUNT_TYPE_ID
}
OIDREMCS_LCHECK1{
SELECT 'Y'  CHECK_FLAG    
           FROM AGENCY_REPORTING_LOCS
          WHERE LOCATION1_ID =:LIVINGUNITID1
            AND LOCATION2_ID = :LIVINGUNITID2
            AND LOCATION3_ID IS NULL
            }

OIDREMCS_UPDATE_COUNT_RECORDUPDATE_COUNT_RECORD_L_CHK {
	SELECT 'Y'  FROM AGENCY_LOCATION_COUNTS
	WHERE COUNT_TYPE_ID = :COUNT_TYPE_ID AND AGY_SEQ = :AGY_SEQ AND REPORTING_LOC_ID = :REPORTING_LOC_ID AND REPORTED_COUNT IS NOT NULL
}

OIDREMCS_HOUSING_LEV_1_VALHOUSING_LEV_1_VAL {
	SELECT 'Y' INTO L_CHK FROM AGENCY_REPORTING_LOCS WHERE LOCATION1_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID1 AND LOCATION2_ID IS NULL AND LOCATION3_ID IS NULL
}

OIDREMCS_HOUSING_LEV_1_VALHOUSING_LEV_1_VAL {
	SELECT 'Y' INTO L_CHK1 FROM AGENCY_REPORTING_LOCS WHERE LOCATION1_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID1 AND NVL(LOCATION2_ID,0) = NVL(:SUB_REM_CNT.NBT_LIV_UNIT_ID2,0) AND NVL(LOCATION3_ID,0) = NVL(:SUB_REM_CNT.NBT_LIV_UNIT_ID3,0)
}

OIDREMCS_HOUSING_LEV_1_VALHOUSING_LEV_1_VAL {
	SELECT MAX(LOCATION2_ID) INTO L_LOC2_ID FROM AGENCY_REPORTING_LOCS WHERE LOCATION1_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID1
}

OIDREMCS_HOUSING_LEV_2_VALHOUSING_LEV_2_VAL {
	SELECT 'Y' INTO L_CHK FROM AGENCY_REPORTING_LOCS WHERE LOCATION1_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID1 AND NVL(LOCATION2_ID,0) = NVL(:SUB_REM_CNT.NBT_LIV_UNIT_ID2,0) AND NVL(LOCATION3_ID,0) = NVL(:SUB_REM_CNT.NBT_LIV_UNIT_ID3,0)
}

OIDREMCS_HOUSING_LEV_2_VALHOUSING_LEV_2_VAL {
	SELECT 'Y' INTO L_CHK1 FROM AGENCY_REPORTING_LOCS WHERE LOCATION1_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID1 AND LOCATION2_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID2 AND LOCATION3_ID IS NULL
}

OIDREMCS_HOUSING_LEV_2_VALHOUSING_LEV_2_VAL {
	SELECT MAX(LOCATION3_ID) INTO L_LOC3_ID FROM AGENCY_REPORTING_LOCS WHERE LOCATION1_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID1 AND LOCATION2_ID = :SUB_REM_CNT.NBT_LIV_UNIT_ID2
}

OIDREMCS_CALCULATE_ACTUAL_COUNTCALCULATE_ACTUAL_COUNT {
	SELECT COUNT(*) INTO :SUB_REM_CNT.ACTUAL_COUNT FROM OFFENDER_BOOKINGS OB WHERE OB.LIVING_UNIT_ID IN (SELECT LIVING_UNIT_ID FROM LIVING_UNITS START WITH LIVING_UNIT_ID = L_LIV_UNIT_ID CONNECT BY PARENT_LIVING_UNIT_ID = PRIOR LIVING_UNIT_ID) AND OB.ACTIVE_FLAG = 'Y' AND OB.AGENCY_IML_ID  IS NULL AND IN_OUT_STATUS = 'IN'
}

OIDREMCS_CALCULATE_ACTUAL_COUNTCALCULATE_ACTUAL_COUNT {
	SELECT COUNT(*) INTO :SUB_REM_CNT.ACTUAL_COUNT FROM OFFENDER_BOOKINGS OB WHERE OB.AGENCY_IML_ID = :SUB_REM_CNT.NBT_INTERNAL_LOCATION --AND OB.AGENCY_IML_ID IN (SELECT INTERNAL_LOCATION_ID FROM AGENCY_INTERNAL_LOCATIONS CONNECT BY PRIOR INTERNAL_LOCATION_ID = PARENT_INTERNAL_LOCATION_ID START WITH INTERNAL_LOCATION_ID = :SUB_REM_CNT.NBT_INTERNAL_LOCATION) AND OB.ACTIVE_FLAG = 'Y' AND IN_OUT_STATUS = 'IN'
}
OIDREMCS_GET_ACTUAL_COUNT{
select
	COUNT(*)

from
	OFFENDER_BOOKINGS OB
where
	OB.LIVING_UNIT_ID in (with recursive cte as (
	select
		LIVING_UNIT_ID
	from
		LIVING_UNITS
	where
		LIVING_UNIT_ID = :L_LIV_UNIT_ID
union all
	select
		lu.LIVING_UNIT_ID
	from
		LIVING_UNITS lu
	join cte c on
		(c.LIVING_UNIT_ID = PARENT_LIVING_UNIT_ID)

)
	select
		*
	from
		cte

)
	and
 OB.ACTIVE_FLAG = 'Y'
	and coalesce(OB.AGENCY_IML_ID::text, '') = ''
	and IN_OUT_STATUS = 'IN';
}
OIDREMCS_GET_INTERNAL_LOCATION_COUNT{
select
	COUNT(*)
from
	OFFENDER_BOOKINGS OB
where
	OB.AGENCY_IML_ID in (with recursive cte as (
	select
		INTERNAL_LOCATION_ID
	from
		AGENCY_INTERNAL_LOCATIONS
	where
		INTERNAL_LOCATION_ID = :L_LIV_UNIT_ID
union all
	select
		ail.INTERNAL_LOCATION_ID
	from
		AGENCY_INTERNAL_LOCATIONS ail
	join cte c on
		(c.INTERNAL_LOCATION_ID = PARENT_INTERNAL_LOCATION_ID )

)
	select
		*
	from
		cte

)
	and OB.ACTIVE_FLAG = 'Y'
	and IN_OUT_STATUS = 'IN';
}

GET_AGENCY_REPORTING_LOCS_ONE {
	SELECT count(*) FROM agency_reporting_locs WHERE location1_id = :livUnitId AND location2_id IS NULL AND location3_id IS NULL
}

GET_AGENCY_REPORTING_LOCS_TWO {
	SELECT MAX(location2_id) FROM agency_reporting_locs WHERE location1_id = :livUnitId
}

GET_AGENCY_REPORTING_LOCS_THREE {
	SELECT count(*) FROM agency_reporting_locs WHERE location1_id = :livUnitId1 AND location2_id = :livUnitId2 AND location3_id IS NULL
}

GET_AGENCY_REPORTING_LOCS_FOUR {
	SELECT MAX(location3_id) FROM agency_reporting_locs WHERE location1_id = :livUnitId1 AND location2_id = :livUnitId2
}
OIDREMCS_RESUBMITCOUNT_DELETE_QUERY {
update
	AGENCY_LOCATION_COUNTS
set
	REPORTED_COUNT = null ,
	CONDUCTED_BY_USERID = null ,
	ENTERED_BY_USERID = null ,
	RCNT_IN_PROGRESS_FLAG = 'N',
	MODIFY_DATETIME = current_timestamp,
	MODIFY_USER_ID = :modifyUserId 
where
	COUNT_TYPE_ID = :countTypeId
	and AGY_SEQ = :agySeq
	and REPORTING_LOC_ID = :reportingLocId
}
OIDREMCS_COUNT_RECORDUPDATE_COUNT_RECORD {
	SELECT 'Y'  FROM AGENCY_LOCATION_COUNTS 
	WHERE COUNT_TYPE_ID = :COUNT_TYPE_ID AND AGY_SEQ = :AGY_SEQ AND REPORTING_LOC_ID = :REPORTING_LOC_ID 
	    AND REPORTED_COUNT IS NOT NULL AND RCNT_IN_PROGRESS_FLAG = 'Y'
}
OIDREMCS_GET_LABEL_DESCRIPTION {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'LIVING_UNIT' AND CODE = :CODE
}
