
OIDRECOR_FIND_CGFKRECOUNTRSN {
 	SELECT CODE ,DESCRIPTION  FROM REFERENCE_CODES  WHERE DOMAIN = 'RECOUNT_RSN'  AND ACTIVE_FLAG = 'Y'  ORDER BY LIST_SEQ
}

OIDRECOR_AGENCYCOUNTS_FIND_AGENCY_COUNTS {
 	SELECT REPORTING_LOC_ID ,COUNT_TYPE_ID ,INITIATED_DATE ,COMPLETION_DATE ,TOTAL_ACTUAL ,TOTAL_REPORTED ,CONDUCTED_BY_USERID ,OUTCOME ,RECOUNT_RSN_CODE ,DISCREP_RSN_CODE ,RSN_CODE_USERID ,RSN_CODE_DATETIME ,COMMENT_TEXT ,PARENT_REPORTING_LOC_ID ,COUNT_IN_PROGRESS ,OUT_TOTAL ,TOTAL_MALE ,TOTAL_FEMALE ,TOTAL_OTHER ,TOTAL_MALE_OUT ,TOTAL_FEMALE_OUT ,TOTAL_OTHER_OUT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM AGENCY_COUNTS  /* where  */
}
OIDRECOR_AGENCYCOUNTS_INSERT_AGENCY_COUNTS {
insert
	into
	agency_counts (reporting_loc_id,
	count_type_id,
	initiated_date,
	parent_reporting_loc_id,
	conducted_by_userid,
	count_in_progress,
	comment_text,
	create_datetime,
	create_user_id )
	values ( :reportingLocId,
	:countTypeId,
	current_timestamp,
	:parentReportingLocId,
	:createUserId,
	'Y',
	:commentText,
	current_timestamp,
	:createUserId )
}

OIDRECOR_AGENCYCOUNTS_UPDATE_AGENCY_COUNTS {
	 UPDATE AGENCY_COUNTS SET TOTAL_ACTUAL = :totalActual, TOTAL_MALE = :totalMale, TOTAL_FEMALE = :totalFemale, TOTAL_OTHER = :totalOther, TOTAL_REPORTED = :totalReported, OUT_TOTAL = :outTotal, TOTAL_MALE_OUT = :totalMaleOut, TOTAL_FEMALE_OUT = :totalFemaleOut, TOTAL_OTHER_OUT = :totalOtherOut, COMPLETION_DATE = current_timestamp, COUNT_IN_PROGRESS = 'N', OUTCOME = 'RE COUNT', COMMENT_TEXT = :commentText, RECOUNT_RSN_CODE = :recountRsnCode, RSN_CODE_USERID = :rsnCodeUserid, RSN_CODE_DATETIME = :rsnCodeDatetime, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID =:modifyUserId WHERE REPORTING_LOC_ID = :reportingLocId AND COUNT_TYPE_ID = :countTypeId AND INITIATED_DATE = (SELECT LOCKED_DATE FROM LOCKED_MODULES WHERE MODULE_NAME = 'OIDCOUNT' AND SESSION_ID = :sessionId AND USER_ID = :createUserId)
}

OIDRECOR_AGENCYCOUNTS_DELETE_AGENCY_COUNTS { 
	 update locked_modules set locked_date = current_timestamp, modify_datetime = current_timestamp, modify_user_id =:modifyUserId where session_id = :reCountSessionId and module_name = 'OIDCOUNT' and user_id = :createUserId and session_id = :sessionId
}


OIDRECOR_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION  FROM OMS_MODULES WHERE MODULE_NAME = :V_FORM_NAME
}

OIDRECOR_PRINT_LIST_ {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'ROLE_BASE'
}

OIDRECOR_PRINT_LIST_ {
	SELECT * FROM SALES_MAINTENANCES WHERE CASELOAD_ID = :P_CASELOAD_ID AND STOCK_LOC_ID = :P_STOCK_ID
}

OIDRECOR_PRINT_LIST_ {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'SYS' AND PROFILE_CODE = 'ROLE_PSWD'
}

OIDRECOR_DEFAULT_AGY_LOCDEFAULT_AGY_LOC {
	select ALAL.AGY_LOC_ID, ALAL.DESCRIPTION DSP_DESCRIPTION2

from AGENCY_LOCATIONS ALAL where ALAL.AGENCY_LOCATION_TYPE = 'INST' and ALAL.AGY_LOC_ID in ( select CA.AGY_LOC_ID from CASELOAD_AGENCY_LOCATIONS CA where CA.CASELOAD_ID = :P_GLOBAL_CASELOAD_ID ) and ALAL.AGY_LOC_ID not in ( 'TRN', 'OUT' )
}

OIDRECOR_AGENCYLOCATIONCOUNTS_DELETE_AGENCY_COUNTS {
DELETE FROM AGENCY_LOCATION_COUNTS WHERE COUNT_TYPE_ID = :countTypeId
}
