
OIDVERCC_FIND_CGFKAGYLOCID {
 	SELECT   AL.AGY_LOC_ID AGY_LOC_ID ,          AL.DESCRIPTION DESCRIPTION     FROM AGENCY_LOCATIONS AL    WHERE AL.AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID                              FROM CASELOAD_AGENCY_LOCATIONS CAL ,                                   CASELOADS CAS                             WHERE CAS.CASELOAD_ID = CAL.CASELOAD_ID                               AND CAL.CASELOAD_ID =  :CASELOADID                               AND CAL.AGY_LOC_ID NOT IN ('OUT' ,'TRN' ,'CRT' )  )    AND AL.AGY_LOC_ID NOT IN ('OUT' , 'TRN' )    AND AL.DEACTIVATION_DATE IS NULL ORDER BY AL.LIST_SEQ  ,AL.AGY_LOC_ID
}

OIDVERCC_FIND_CGFKCOUNTTYPES {
 	SELECT RC.CODE CODE ,RC.DESCRIPTION DESCRIPTION FROM REFERENCE_CODES RC WHERE DOMAIN = 'COUNT_TYPES'  AND ACTIVE_FLAG = 'Y' AND RC.CODE IN  (SELECT DISTINCT COUNT_TYPE_CODE  FROM AGENCY_COUNT_TYPES WHERE AGY_LOC_ID = :AGYLOCID ) ORDER BY LIST_SEQ 
}

OIDVERCC_FIND_CGFKSCHEDULEDTIME {
 	select
	case
		when SCHEDULED_TIME = 'NA' then null
		else SCHEDULED_TIME
	end SCHEDULED_TIME ,
	AGY_LOC_ID ,
	COUNT_TYPE_CODE,
	COUNT_TYPE_ID
from
	AGENCY_COUNT_TYPES
where
	AGY_LOC_ID = :AGYLOCID
	and COUNT_TYPE_CODE = :COUNTTYPECODE
order by
	SCHEDULED_TIME ,
	AGY_LOC_ID ,
	COUNT_TYPE_CODE
}

OIDVERCC_AGENCYCOUNTTYPES_FIND_AGENCY_COUNT_TYPES {
 	SELECT  * FROM AGENCY_COUNT_TYPES
}
OIDVERCC_AGENCYCOUNTTYPES_INSERT_AGENCY_COUNT_TYPES {
	INSERT INTO AGENCY_COUNT_TYPES() VALUES(:)
}

OIDVERCC_AGENCYCOUNTTYPES_UPDATE_AGENCY_COUNT_TYPES {
	UPDATE AGENCY_COUNT_TYPES set
}

OIDVERCC_AGENCYCOUNTTYPES_DELETE_AGENCY_COUNT_TYPES { 
	DELETE FROM AGENCY_COUNT_TYPES
}

OIDVERCC_REPORTINGLOCATIONS_FIND_V_REPORTING_LOCATIONS {
 	select
	AGY_LOC_ID ,
	COUNT_TYPE_ID ,
	COUNT_TYPE_CODE ,
	case 
		when SCHEDULED_TIME = 'NA'
		then null
		else SCHEDULED_TIME
	end SCHEDULED_TIME ,
	AGY_SEQ ,
	LOCATION_TYPE ,
	LOCATION1_ID ,
	LOCATION2_ID ,
	LOCATION3_ID ,
	LIST_SEQ ,
	REPORTING_LOC_ID ,
	DATE_SUBMITTED ,
	ACTUAL_COUNT ,
	REPORTED_COUNT ,
	CONDUCTED_BY_USERID ,
	ENTERED_BY_USERID ,
	CONDUCTED_DATETIME ,
	RECOUNT_RSN_CODE ,
	DISCREP_RSN_CODE ,
	RSN_CODE_USERID ,
	RSN_CODE_DATETIME ,
	VERIFIED_USER_ID ,
	VERIFIED_DATETIME ,
	RCNT_CONDUCTED_BY ,
	RCNT_DATETIME ,
	RCNT_IN_PROGRESS_FLAG ,
	RECOUNT_TOTAL ,
	REPORTED_TOTAL ,
	LOCATION_DESCRIPTION
from
	V_REPORTING_LOCATIONS
}
OIDVERCC_REPORTINGLOCATIONS_DELETE_V_REPORTING_LOCATIONS { 
	DELETE FROM V_REPORTING_LOCATIONS
}


OIDVERCC_DEFAULT_AGY_LOCDEFAULT_AGY_LOC {
	select
	ALAL.AGY_LOC_ID,
	ALAL.DESCRIPTION DSP_DESCRIPTION2

from
	AGENCY_LOCATIONS ALAL
where
	ALAL.AGENCY_LOCATION_TYPE = 'INST'
	and ALAL.AGY_LOC_ID in (
	select
		CA.AGY_LOC_ID
	from
		CASELOAD_AGENCY_LOCATIONS CA
	where
		CA.CASELOAD_ID = :P_GLOBAL_CASELOAD_ID )
	and ALAL.AGY_LOC_ID not in ( 'TRN', 'OUT' )
}
OIDVERCC_UPDATE_AGENCY_LOCATION_COUNTS {
update
	AGENCY_LOCATION_COUNTS
set
	VERIFIED_USER_ID = :modifyUserId,
	VERIFIED_DATETIME = current_timestamp ,
	MODIFY_DATETIME = current_timestamp,
	MODIFY_USER_ID = :modifyUserId
where
	REPORTING_LOC_ID = :reportingLocId
	and COUNT_TYPE_ID = :countTypeId
	and AGY_SEQ = :agySeq
}
