
OIIHISCO_FIND_CGFKAGYLOCID {
 	SELECT AL.AGY_LOC_ID , AL.DESCRIPTION   FROM AGENCY_LOCATIONS AL  WHERE AL.AGENCY_LOCATION_TYPE IN ('INST' ,'JAIL' ,'HOSP' )    
AND AL.AGY_LOC_ID NOT IN ('OUT' , 'TRN' )    AND coalesce (AL.DEACTIVATION_DATE,'1010-10-10') = '1010-10-10'    AND AL.AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID 
FROM CASELOAD_AGENCY_LOCATIONS CAL  WHERE CAL.CASELOAD_ID = :CASELOAD_ID  ) 
ORDER BY AL.AGY_LOC_ID ,AL.LIST_SEQ
}

OIIHISCO_FIND_CGFKCOUNTTYPES {
 	SELECT DISTINCT CODE ,DESCRIPTION FROM REFERENCE_CODES AC , AGENCY_COUNT_TYPES ACT WHERE AC.DOMAIN = 'COUNT_TYPES'  
 	AND AC.CODE = ACT.COUNT_TYPE_CODE AND AC.ACTIVE_FLAG = 'Y'  AND ACT.AGY_LOC_ID = :LOCATION ORDER BY 1
}

OIIHISCO_FIND_CGFKSCHTIME {
 	SELECT COUNT_TYPE_CODE ,
	case
		when SCHEDULED_TIME = 'NA' then null
		else SCHEDULED_TIME
	end SCHEDULED_TIME  FROM  AGENCY_COUNT_TYPES ACT 
 	WHERE COUNT_TYPE_CODE = :COUNTTYPE AND AGY_LOC_ID = :LOCATION ORDER BY 1
}

OIIHISCO_AGENCYCOUNTS_FIND_AGENCY_COUNTS {
 	SELECT REPORTING_LOC_ID ,COUNT_TYPE_ID ,INITIATED_DATE ,COMPLETION_DATE ,TOTAL_ACTUAL ,TOTAL_REPORTED ,CONDUCTED_BY_USERID ,OUTCOME ,RECOUNT_RSN_CODE ,DISCREP_RSN_CODE ,RSN_CODE_USERID ,RSN_CODE_DATETIME ,COMMENT_TEXT ,PARENT_REPORTING_LOC_ID ,COUNT_IN_PROGRESS ,OUT_TOTAL ,TOTAL_MALE ,TOTAL_FEMALE ,TOTAL_OTHER ,TOTAL_MALE_OUT ,TOTAL_FEMALE_OUT ,TOTAL_OTHER_OUT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM AGENCY_COUNTS  /* where  */
}
OIIHISCO_AGENCYLOCATIONCOUNTS_FIND_AGENCY_LOCATION_COUNTS {
 	SELECT REPORTING_LOC_ID ,COUNT_TYPE_ID ,AGY_SEQ ,DATE_SUBMITTED ,ACTUAL_COUNT ,REPORTED_COUNT ,CONDUCTED_BY_USERID ,ENTERED_BY_USERID ,CONDUCTED_DATETIME ,
 	RECOUNT_RSN_CODE ,DISCREP_RSN_CODE ,RSN_CODE_USERID ,RSN_CODE_DATETIME ,RCNT_CONDUCTED_BY ,RCNT_DATETIME ,RCNT_IN_PROGRESS_FLAG ,RECOUNT_TOTAL ,COMMENT_TEXT ,VERIFIED_USER_ID ,
 	VERIFIED_DATETIME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM AGENCY_LOCATION_COUNTS 
 	where REPORTED_COUNT IS NOT NULL AND REPORTING_LOC_ID =:REPORTING_LOC_ID order by CONDUCTED_DATETIME
}

OIIHISCO_AGENCY_COUNTS_POSTQUERY {
	select
	COUNT_TYPE_CODE,
	case
		when SCHEDULED_TIME = 'NA' then null
		else SCHEDULED_TIME
	end SCHEDULED_TIME
from
	AGENCY_COUNT_TYPES
where
	COUNT_TYPE_ID = :COUNT_TYPE_ID
}

OIIHISCO_AGENCY_COUNTS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM AGENCY_LOCATION_COUNTS A WHERE A.REPORTING_LOC_ID = :REPORTINGLOCID
}

OIIHISCO_AGENCY_LOCATION_COUNTS_POSTQUERY {
	SELECT LOCATION_DESCRIPTION  FROM V_REPORTING_LOCATIONS WHERE REPORTING_LOC_ID = :REPORTING_LOC_ID AND AGY_SEQ = :AGY_SEQ
}

OIIHISCO_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION  FROM OMS_MODULES WHERE MODULE_NAME = :V_FORM_NAME
}

OIIHISCO_DEFAULT_AGY_LOCDEFAULT_AGY_LOC {
	SELECT ALAL.AGY_LOC_ID, ALAL.DESCRIPTION DSP_DESCRIPTION2  FROM AGENCY_LOCATIONS ALAL WHERE ALAL.AGENCY_LOCATION_TYPE = 'INST' AND ALAL.AGY_LOC_ID IN ( SELECT CA.AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS CA WHERE CA.CASELOAD_ID = :P_GLOBAL_CASELOAD_ID ) AND ALAL.AGY_LOC_ID NOT IN ( 'TRN', 'OUT' )
}

OIIHISCO_RUN_REPORT_ {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'ROLE_BASE'
}

OIIHISCO_RUN_REPORT_ {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'SYS' AND PROFILE_CODE = 'ROLE_PSWD'
}

OIIHISCO_RUN_REPORT_ {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'REPORT_ALIAS'
}

OIIHISCO_RUN_REPORT_ {
	SELECT LTRIM(RTRIM(DESCRIPTION)) FROM SYSTEM_PROFILES WHERE PROFILE_CODE = :P_PROFILE_CODE AND PROFILE_TYPE = :P_PROFILE_TYPE
}

OIIHISCO_COMMENT_TEXT {
	select comment_text from agency_counts ac where reporting_loc_id = :reportingLocId; 
}
