
OIIINROL_ROLLLIST_FIND_V_INT_LOC_OFFENDERS {
 	SELECT AGY_LOC_ID ,ROOT_INTERNAL_LOCATION_ID ,OFFENDER_BOOK_ID ,OFFENDER_ID ,LAST_NAME ,FIRST_NAME ,OFFENDER_ID_DISPLAY ,INTERNAL_LOCATION_ID ,INTERNAL_LOCATION_DESC ,PARENT_INTERNAL_LOCATION_ID ,IN_OUT_STATUS ,LIVING_UNIT_ID ,LIVING_UNIT_DESC ,ALERT_FLAG   FROM V_INT_LOC_OFFENDERS 
 	WHERE AGY_LOC_ID = :agyLocId AND ROOT_INTERNAL_LOCATION_ID = :internallocationid AND IN_OUT_STATUS = 'IN' order by living_unit_desc,last_name,first_name
}
