
OIIUNROL_ROLLLIST_FIND_V_LIVING_UNIT_OFFENDERS {
 	SELECT AGY_LOC_ID ,LIVING_UNIT_ID ,LIVING_UNIT_DESC ,PARENT_LIVING_UNIT_ID ,ROOT_LIVING_UNIT_ID ,AGENCY_IML_ID ,AGENCY_IML_DESC ,IN_OUT_STATUS ,ACTIVE_FLAG ,OFFENDER_BOOK_ID ,OFFENDER_ID ,OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,ALERT_FLAG   FROM V_LIVING_UNIT_OFFENDERS
}
