  PROVIDER_NAME_FROM_TEAMS{
   SELECT description
           FROM automation_teams
          WHERE team_id = :P_PROVIDER_ID
 } 
   PROVIDER_NAME_FROM_CORPORATES{
   SELECT corporate_name
           FROM corporates
          WHERE corporate_id = :P_PROVIDER_ID
  } 
  PROVIDER_NAME_FROM_PERSONS{
   SELECT last_name || ', ' first_name
           FROM persons
          WHERE person_id = :P_PROVIDER_ID
  }   
   PROVIDER_NAME_FROM_AGENCY_LOCATIONS{
   SELECT description
           FROM agency_locations
          WHERE agy_loc_id = :P_PROVIDER_CODE
  }
  TAG_PRG_COURSE_ACTIVITY_CAPACITY{
   SELECT capacity FROM course_activities WHERE crs_acty_id = :p_course_activity_id
   }
  TAG_PRG_COUNT{
   SELECT COUNT(*) FROM offender_program_profiles  WHERE crs_acty_id = :p_course_activity_id  AND offender_program_status = 'ALLOC'
   }

GET_REC_FRM_OFF_BKGS{
 SELECT bkg.agy_loc_id, al.agency_location_type, bkg.in_out_status FROM offender_bookings bkg, agency_locations al WHERE bkg.agy_loc_id = al.agy_loc_id AND bkg.offender_book_id = :p_offender_book_id
}   

TAG_PRG_CREDITED_HOURS_WITHOUT_SENT_COND_ID {
SELECT SUM(COALESCE(CREDIT_WORK_HOURS, 0)) CREDIT_WORK_HOURS FROM (( SELECT SUM(COALESCE(CREDIT_WORK_HOURS, 0)) CREDIT_WORK_HOURS FROM OFFENDER_PROGRAM_PROFILES WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND SENTENCE_SEQ = :SEQ UNION ALL SELECT SUM(COALESCE(CASE ADJUSTMENT_TYPE WHEN 'C' THEN ADJUSTMENT_MINUTES::DECIMAL / 60 WHEN 'D' THEN -1 * ADJUSTMENT_MINUTES::DECIMAL / 60 ELSE 0 END, 0)) CREDIT_WORK_HOURS FROM OFFENDER_UNPAID_WORK_ADJ WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND SENTENCE_SEQ = :SEQ)) S
}

TAG_PRG_CREDITED_HOURS_WITH_SENT_COND_ID {
SELECT SUM(COALESCE(CREDIT_WORK_HOURS, 0)) CREDIT_WORK_HOURS FROM (( SELECT SUM(COALESCE(CREDIT_WORK_HOURS, 0)) CREDIT_WORK_HOURS FROM OFFENDER_PROGRAM_PROFILES WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND OFFENDER_SENT_CONDITION_ID = :OFFENDERSENTCONDID AND SENTENCE_SEQ = :SEQ UNION ALL SELECT SUM(COALESCE(CASE ADJUSTMENT_TYPE WHEN 'C' THEN ADJUSTMENT_MINUTES::DECIMAL / 60 WHEN 'D' THEN -1 * ADJUSTMENT_MINUTES::DECIMAL / 60 ELSE 0 END, 0)) CREDIT_WORK_HOURS FROM OFFENDER_UNPAID_WORK_ADJ WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND SENTENCE_SEQ = :SEQ and OFFENDER_SENT_CONDITION_ID = :OFFENDERSENTCONDID)) S

}