 
OCMNOQUE_FIND_RGQUESTIONSASSESSMENTS {
 	SELECT
  ASSESSMENT_ID, ASSESSMENT_CLASS, PARENT_ASSESSMENT_ID, ASSESSMENT_CODE,
  DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EFFECTIVE_DATE,
  EXPIRY_DATE, SCORE, MUTUAL_EXCLUSIVE_FLAG, DETERMINE_SUP_LEVEL_FLAG,
  REQUIRE_EVALUATION_FLAG, REQUIRE_APPROVAL_FLAG, REVIEW_CYCLE_DAYS,
  CASELOAD_TYPE, REVIEW_FLAG, ASSESS_COMMENT, HIGH_VALUE, LOW_VALUE,
  SEARCH_CRITERIA_FLAG, OVERRIDEABLE_FLAG, ASSESSMENT_TYPE,
  CALCULATE_TOTAL_FLAG, MEASURE, CREATE_USER_ID, CREATE_DATE, MODIFY_USER_ID,
  MODIFY_DATETIME, CREATE_DATETIME, CELL_SHARING_ALERT_FLAG, TOTAL_PERCENT,
  SCREEN_CODE, SCHEDULE_COMPLETE_DAYS, SECT_SCORE_INCLUDE_FLAG,
  SECT_SCORE_OVERRIDE_FLAG, MEDICAL_FLAG, SEAL_FLAG, REQUIRED_FLAG
FROM ASSESSMENTS A
WHERE
 PARENT_ASSESSMENT_ID = :ASSESSMENTID AND
 A.ASSESSMENT_CLASS = 'CAT' 
}

OCMNOQUE_FIND_RGSECTIONSASSESSMENTS {
 	SELECT
  ASSESSMENT_CODE, DESCRIPTION, ASSESSMENT_ID, PARENT_ASSESSMENT_ID
FROM ASSESSMENTS
WHERE
  PARENT_ASSESSMENT_ID = :ASSESSMENTID AND
  ASSESSMENT_CLASS = 'SECT' AND
  ACTIVE_FLAG = 'Y'
ORDER BY
  LIST_SEQ ASC, ASSESSMENT_CODE ASC

}

OCMNOQUE_FIND_RGASSESSMENTTYPE {
 	SELECT
  REF_CODE.DESCRIPTION NBT_ASSESSMENT_TYPE, REF_CODE.CODE ASSESSMENT_TYPE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'ASSESS_TYPE' AND
  (ACTIVE_FLAG = 'Y')
ORDER BY
  LIST_SEQ, DESCRIPTION

}

OCMNOQUE_FIND_RGCASELOADTYPE {
SELECT
    ref_code.code caseload_type,
    ref_code.description nbt_caseload_type
FROM
    reference_codes ref_code
WHERE
        domain = 'CLOAD_TYPE'
    AND (
        active_flag = 'Y'
    )
ORDER BY list_seq,code
}

OCMNOQUE_FIND_RGRESULTCODE {
 	SELECT
  CODE CODE, DESCRIPTION
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'SUP_LVL_TYPE' AND
  (ACTIVE_FLAG = 'Y')
ORDER BY
  LIST_SEQ, CODE

}

OCMNOQUE_ASSESS_FIND_ASSESSMENTS {
 	SELECT ASSESSMENT_ID, ASSESSMENT_CLASS, PARENT_ASSESSMENT_ID, ASSESSMENT_CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EFFECTIVE_DATE, EXPIRY_DATE, SCORE, MUTUAL_EXCLUSIVE_FLAG, DETERMINE_SUP_LEVEL_FLAG, REQUIRE_EVALUATION_FLAG, REQUIRE_APPROVAL_FLAG, REVIEW_CYCLE_DAYS, CASELOAD_TYPE, REVIEW_FLAG, ASSESS_COMMENT, HIGH_VALUE, LOW_VALUE, SEARCH_CRITERIA_FLAG, OVERRIDEABLE_FLAG, ASSESSMENT_TYPE, CALCULATE_TOTAL_FLAG, MEASURE, CREATE_USER_ID, CREATE_DATE, MODIFY_USER_ID, MODIFY_DATETIME, CREATE_DATETIME, CELL_SHARING_ALERT_FLAG, TOTAL_PERCENT, SCREEN_CODE, SCHEDULE_COMPLETE_DAYS, SECT_SCORE_INCLUDE_FLAG, SECT_SCORE_OVERRIDE_FLAG, MEDICAL_FLAG, SEAL_FLAG  FROM ASSESSMENTS WHERE ASSESSMENT_CLASS = 'TYPE'
}
OCMNOQUE_ASSESS_INSERT_ASSESSMENTS {
	insert into assessments ( assessment_id, assessment_class, parent_assessment_id, assessment_code, description, list_seq, active_flag, update_allowed_flag, effective_date, expiry_date, score, mutual_exclusive_flag, determine_sup_level_flag, require_evaluation_flag, require_approval_flag, review_cycle_days, caseload_type, review_flag, assess_comment, high_value, low_value, search_criteria_flag, overrideable_flag, assessment_type, calculate_total_flag, measure, create_user_id, create_date, modify_datetime, create_datetime, cell_sharing_alert_flag, total_percent, screen_code, schedule_complete_days, sect_score_include_flag, sect_score_override_flag, medical_flag, seal_flag, required_flag, bookmark_name, bookmark_condition, min_value, max_value) values ( :assessmentId, :assessmentClass, :parentAssessmentId, :assessmentCode, :description, :listSeq, :activeFlag, :updateAllowedFlag, :effectiveDate, :expiryDate, :score, :mutualExclusiveFlag, :determineSupLevelFlag, :requireEvaluationFlag, :requireApprovalFlag, :reviewCycleDays, :caseloadType, :reviewFlag, :assessComment, :highValue, :lowValue, :searchCriteriaFlag, :overrideableFlag, :assessmentType, :calculateTotalFlag, :measure, :createUserId, :createDate, NULL, current_timestamp, :cellSharingAlertFlag, :totalPercent, :screenCode, :scheduleCompleteDays, :sectScoreIncludeFlag, :sectScoreOverrideFlag, :medicalFlag, :sealFlag, :requiredFlag, :ansBookMark, :bookmarkCondition, :minValue, :maxValue)
}  

OCMNOQUE_ASSESS_UPDATE_ASSESSMENTS {
	UPDATE ASSESSMENTS set assessment_id =:assessmentId,assessment_class =:assessmentClass,parent_assessment_id =:parentAssessmentId, assessment_code =:assessmentCode,description =:description,list_seq =:listSeq,active_flag =:activeFlag,update_allowed_flag = :updateAllowedFlag,effective_date =:effectiveDate,expiry_date =:expiryDate,score =:score,mutual_exclusive_flag = :mutualExclusiveFlag,determine_sup_level_flag =:determineSupLevelFlag,require_evaluation_flag =:requireEvaluationFlag, require_approval_flag =:requireApprovalFlag,review_cycle_days =:reviewCycleDays,caseload_type =:caseloadType,review_flag = :reviewFlag,assess_comment =:assessComment,high_value =:highValue,low_value =:lowValue,search_criteria_flag =:searchCriteriaFlag, overrideable_flag =:overrideableFlag,assessment_type =:assessmentType,calculate_total_flag =:calculateTotalFlag,measure =:measure, modify_user_id =:modifyUserId,modify_datetime =current_timestamp, cell_sharing_alert_flag =:cellSharingAlertFlag,total_percent =:totalPercent,screen_code = :screenCode,schedule_complete_days =:scheduleCompleteDays,sect_score_include_flag =:sectScoreIncludeFlag,bookmark_name = :ansBookMark, sect_score_override_flag =:sectScoreOverrideFlag,medical_flag =:medicalFlag,seal_flag =:sealFlag, required_flag = :requiredFlag,bookmark_condition=:bookmarkCondition, min_value = :minValue, max_value = :maxValue where assessment_id =:assessmentId 
} 

OCMNOQUE_ASSESS_DELETE_ASSESSMENTS { 
	DELETE FROM ASSESSMENTS where assessment_id =:assessmentId
}  

OCMNOQUE_ASSSECT_FIND_ASSESSMENTS {
 	 	SELECT ASSESSMENT_ID, ASSESSMENT_CLASS, PARENT_ASSESSMENT_ID, ASSESSMENT_CODE,ASSESSMENT_CODE CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EFFECTIVE_DATE, EXPIRY_DATE, SCORE, MUTUAL_EXCLUSIVE_FLAG, DETERMINE_SUP_LEVEL_FLAG, REQUIRE_EVALUATION_FLAG, REQUIRE_APPROVAL_FLAG, REVIEW_CYCLE_DAYS, CASELOAD_TYPE, REVIEW_FLAG, ASSESS_COMMENT, HIGH_VALUE, LOW_VALUE, SEARCH_CRITERIA_FLAG, OVERRIDEABLE_FLAG, ASSESSMENT_TYPE, CALCULATE_TOTAL_FLAG, MEASURE, CREATE_USER_ID, CREATE_DATE, MODIFY_USER_ID, MODIFY_DATETIME, CREATE_DATETIME, CELL_SHARING_ALERT_FLAG, TOTAL_PERCENT, SCREEN_CODE, SCHEDULE_COMPLETE_DAYS, SECT_SCORE_INCLUDE_FLAG, SECT_SCORE_OVERRIDE_FLAG, MEDICAL_FLAG, SEAL_FLAG  FROM ASSESSMENTS WHERE ASSESSMENT_CLASS = 'SECT'
}

OCMNOQUE_ASSANS_FIND_ASSESSMENTS {
 	 	SELECT ASSESSMENT_ID, ASSESSMENT_CLASS, PARENT_ASSESSMENT_ID, ASSESSMENT_CODE,ASSESSMENT_CODE CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EFFECTIVE_DATE, EXPIRY_DATE, SCORE, MUTUAL_EXCLUSIVE_FLAG, DETERMINE_SUP_LEVEL_FLAG, REQUIRE_EVALUATION_FLAG, REQUIRE_APPROVAL_FLAG, REVIEW_CYCLE_DAYS, CASELOAD_TYPE, REVIEW_FLAG, ASSESS_COMMENT, HIGH_VALUE, LOW_VALUE, SEARCH_CRITERIA_FLAG, OVERRIDEABLE_FLAG, ASSESSMENT_TYPE, CALCULATE_TOTAL_FLAG, MEASURE, CREATE_USER_ID, CREATE_DATE, MODIFY_USER_ID, MODIFY_DATETIME, CREATE_DATETIME, CELL_SHARING_ALERT_FLAG, TOTAL_PERCENT, SCREEN_CODE, SCHEDULE_COMPLETE_DAYS, SECT_SCORE_INCLUDE_FLAG, SECT_SCORE_OVERRIDE_FLAG, MEDICAL_FLAG, SEAL_FLAG,BOOKMARK_NAME,BOOKMARK_CONDITION, MIN_VALUE, MAX_VALUE  FROM ASSESSMENTS WHERE ASSESSMENT_CLASS = 'IND' AND PARENT_ASSESSMENT_ID=:ASSESSMENT_ID ORDER BY LIST_SEQ ASC , ASSESSMENT_CODE ASC

}

OCMNOQUE_FIND_ASSSECTLOV {
SELECT ASSESSMENT_ID, ASSESSMENT_CODE CODE, DESCRIPTION ,LIST_SEQ from  ASSESSMENTS where PARENT_ASSESSMENT_ID=:assessmentId AND ASSESSMENT_CLASS = 'SECT' ORDER BY LIST_SEQ ASC, ASSESSMENT_CODE ASC
}

OCMNOQUE_FIND_ASSQUELOV {
 	SELECT ASSESSMENT_ID, ASSESSMENT_CODE CODE, DESCRIPTION, ASSESSMENT_TYPE,LIST_SEQ FROM ASSESSMENTS WHERE PARENT_ASSESSMENT_ID = :ASSESSMENTID AND ASSESSMENT_CLASS = 'CAT' AND ACTIVE_FLAG = 'Y' ORDER BY LIST_SEQ ASC , ASSESSMENT_CODE ASC
}
OCMNOQUE_ASSSECT_INSERT_ASSESSMENTS {
	INSERT INTO ASSESSMENTS() VALUES(:)
} 

OCMNOQUE_ASSSECT_UPDATE_ASSESSMENTS {
	UPDATE ASSESSMENTS set 
} 

OCMNOQUE_ASSSECT_DELETE_ASSESSMENTS { 
	DELETE FROM ASSESSMENTS
}

OCMNOQUE_ASSRES_FIND_ASSESSMENT_RESULTS {
 	SELECT ASSESSMENT_ID, SUPERVISION_LEVEL_TYPE, LIST_SEQ, EXPIRY_DATE, UPDATE_ALLOWED_FLAG, ACTIVE_FLAG, CELL_SHARING_ALERT_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM ASSESSMENT_RESULTS WHERE ASSESSMENT_ID = :ASSESSMENTID  ORDER BY LIST_SEQ,ACTIVE_FLAG DESC,SUPERVISION_LEVEL_TYPE
}
OCMNOQUE_ASSRES_INSERT_ASSESSMENT_RESULTS {
	INSERT INTO ASSESSMENT_RESULTS(ASSESSMENT_ID, SUPERVISION_LEVEL_TYPE, LIST_SEQ, EXPIRY_DATE, UPDATE_ALLOWED_FLAG, ACTIVE_FLAG, CELL_SHARING_ALERT_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) VALUES(:assessmentId,:supervisionLevelType,:listSeq,:expiryDate,:updateAllowedFlag,:activeFlag,:cellSharingAlertFlag,current_timestamp,:createUserId, NULL,:sealFlag)
} 

OCMNOQUE_ASSRES_UPDATE_ASSESSMENT_RESULTS {
	UPDATE ASSESSMENT_RESULTS set ASSESSMENT_ID =:assessmentId,SUPERVISION_LEVEL_TYPE =:supervisionLevelType,LIST_SEQ =:listSeq,EXPIRY_DATE =
	:expiryDate,UPDATE_ALLOWED_FLAG =:updateAllowedFlag,ACTIVE_FLAG =:activeFlag,CELL_SHARING_ALERT_FLAG =:cellSharingAlertFlag,
	MODIFY_DATETIME =current_timestamp,MODIFY_USER_ID =:modifyUserId,SEAL_FLAG =:sealFlag where 
	ASSESSMENT_ID =:assessmentId and SUPERVISION_LEVEL_TYPE =:supervisionLevelType
}  

OCMNOQUE_ASSRES_DELETE_ASSESSMENT_RESULTS { 
	DELETE FROM ASSESSMENT_RESULTS where ASSESSMENT_ID =:assessmentId and SUPERVISION_LEVEL_TYPE =:supervisionLevelType
}  


OCMNOQUE_ASSESS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM ASSESSMENTS A WHERE A.PARENT_ASSESSMENT_ID = :ASSESSMENTID
}

OCMNOQUE_ASSESS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM ASSESSMENT_RESULTS A WHERE A.ASSESSMENT_ID = :ASSESSMENTID
}

OCMNOQUE_ASS_QUE1_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM ASSESSMENTS A WHERE A.PARENT_ASSESSMENT_ID = :ASSESSMENTID
}

OCMNOQUE_ASS_ANS1_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM ASSESSMENTS A WHERE A.PARENT_ASSESSMENT_ID = :ASSESSMENTID
}

OCMNOQUE_VALIDATE_CASELOAD {
	SELECT COUNT(*) FROM ASSESSMENTS WHERE assessment_id IN ( SELECT DISTINCT assessment_type_id FROM OFFENDER_ASSESSMENTS WHERE assessment_type_id = :ASSESSMENTID )
}

OCMNOQUE_GET_ASSRELCOUNT {
	SELECT COUNT(*) FROM assessments a WHERE a.PARENT_ASSESSMENT_ID = :ASSESSMENTID
}

OCMNOQUE_GET_ASSRESRELCOUNT {
	SELECT COUNT(*) FROM ASSESSMENT_RESULTS A WHERE A.ASSESSMENT_ID = :ASSESSMENTID
}

OCMNOQUE_ASSESSKEYDELLIST {
select
	upper(tc.table_name) TABLE_NAME,
	upper(kcu.column_name) COLUMN_NAME
from
	information_schema.table_constraints as tc
join information_schema.key_column_usage as kcu on
	tc.constraint_name = kcu.constraint_name
	and tc.table_schema = kcu.table_schema
join information_schema.constraint_column_usage as ccu on
	ccu.constraint_name = tc.constraint_name
	and ccu.table_schema = tc.table_schema
where
	tc.constraint_type = 'FOREIGN KEY'
	and upper(ccu.table_name)= 'ASSESSMENTS'
	and UPPER(CCU.COLUMN_NAME)= UPPER('ASSESSMENT_ID')
}

OCMNOQUE_ASSESSKEYDELETERECROWCOUNT {
	SELECT 1 from ASSESSMENTS where ASSESSMENT_ID=:ASSESSMENTID limit 1
}

OCMNOQUE_GETASSESSMENTSUPCOUNT{
	SELECT COUNT ( 0 ) FROM ASSESSMENT_SUPERVISIONS WHERE assessment_id = :ASSESSMENTID AND supervision_level_type = :SUPERVISIONLEVELTYPE
}

OCMNOQUE_GETOFFENDERASSCOUNT{
	SELECT COUNT ( 0 ) FROM OFFENDER_ASSESSMENTS WHERE assessment_type_id = :ASSESSMENTID AND (calc_sup_level_type = :SUPERVISIONLEVELTYPE 
	OR overrided_sup_level_type = :SUPERVISIONLEVELTYPE OR review_sup_level_type = :SUPERVISIONLEVELTYPE )
}

OCMNOQUE_GETDEFAULTASSESSMENTTYPE{
	SELECT CODE FROM REFERENCE_CODES WHERE DOMAIN = 'ASSESS_TYPE' AND ACTIVE_FLAG = 'Y' AND LIST_SEQ = 1
}
OCMNOQUE_RG_BOOKMARK_RECORDGROUP{
SELECT BOOKMARK_NAME CODE ,DESCRIPTION DESCRIPTION  FROM IWP_BOOKMARKS WHERE bookmark_type='TEXT' AND EXPIRY_DATE IS NULL
}