GET_UNIT_TYPE_LOV{
SELECT * FROM REFERENCE_CODES RC  WHERE  DOMAIN='HOU_UN_TYPE' AND EXPIRED_DATE IS NULL AND ACTIVE_FLAG ='Y' ORDER BY LIST_SEQ
}

GET_LEVEL1_DATA{
SELECT LIVING_UNIT_ID , AGY_LOC_ID , LIVING_UNIT_TYPE , LIVING_UNIT_CODE , DESCRIPTION , LEVEL_1_CODE , LEVEL_2_CODE , LEVEL_3_CODE , LEVEL_4_CODE , USER_DESC , ACA_CAP_RATING , SECURITY_LEVEL_CODE , LIST_SEQ , PARENT_LIVING_UNIT_ID , HOUSING_UNIT_TYPE , ACTIVE_FLAG , CONTROL_ACTIVE_FLAG , CNA_NO , CAPACITY , OPERATION_CAPACITY , CERTIFIED_FLAG , DEACTIVATE_DATE , REACTIVATE_DATE , DEACTIVATE_REASON_CODE , COMMENT_TEXT , LOWEST_LEVEL_FLAG , REACH_OPER_CAPACITY_FLAG , NO_OF_OCCUPANT FROM LIVING_UNITS WHERE AGY_LOC_ID = :AGYLOCID AND PARENT_LIVING_UNIT_ID IS NULL AND HOUSING_UNIT_TYPE = :HOUSINGUNITTYPE and living_units.active_flag = 'Y' ORDER BY LIST_SEQ
}

GET_LEVEL2_DATA{
select LIVING_UNIT_ID , AGY_LOC_ID , LIVING_UNIT_TYPE , LIVING_UNIT_CODE , DESCRIPTION , LEVEL_1_CODE , LEVEL_2_CODE , LEVEL_3_CODE , LEVEL_4_CODE , USER_DESC , ACA_CAP_RATING , SECURITY_LEVEL_CODE , LIST_SEQ , PARENT_LIVING_UNIT_ID , HOUSING_UNIT_TYPE , ACTIVE_FLAG , CONTROL_ACTIVE_FLAG , CNA_NO , CAPACITY , OPERATION_CAPACITY , CERTIFIED_FLAG , DEACTIVATE_DATE , REACTIVATE_DATE , DEACTIVATE_REASON_CODE , COMMENT_TEXT , LOWEST_LEVEL_FLAG , REACH_OPER_CAPACITY_FLAG , NO_OF_OCCUPANT from LIVING_UNITS where PARENT_LIVING_UNIT_ID = :LIVINGUNITID and living_units.active_flag = 'Y' order by LIST_SEQ
}

GET_LEVEL3_DATA{
select LIVING_UNIT_ID , AGY_LOC_ID , LIVING_UNIT_TYPE , LIVING_UNIT_CODE , DESCRIPTION , LEVEL_1_CODE , LEVEL_2_CODE , LEVEL_3_CODE , LEVEL_4_CODE , USER_DESC , ACA_CAP_RATING , SECURITY_LEVEL_CODE , LIST_SEQ , PARENT_LIVING_UNIT_ID , HOUSING_UNIT_TYPE , ACTIVE_FLAG , CONTROL_ACTIVE_FLAG , CNA_NO , CAPACITY , OPERATION_CAPACITY , CERTIFIED_FLAG , DEACTIVATE_DATE , REACTIVATE_DATE , DEACTIVATE_REASON_CODE , COMMENT_TEXT , LOWEST_LEVEL_FLAG , REACH_OPER_CAPACITY_FLAG , NO_OF_OCCUPANT from LIVING_UNITS where PARENT_LIVING_UNIT_ID = :LIVINGUNITID and living_units.active_flag = 'Y' order by LIST_SEQ
}

GET_LEVEL4_DATA{
select LIVING_UNIT_ID , AGY_LOC_ID , LIVING_UNIT_TYPE , LIVING_UNIT_CODE , DESCRIPTION , LEVEL_1_CODE , LEVEL_2_CODE , LEVEL_3_CODE , LEVEL_4_CODE , USER_DESC , ACA_CAP_RATING , SECURITY_LEVEL_CODE , LIST_SEQ , PARENT_LIVING_UNIT_ID , HOUSING_UNIT_TYPE , ACTIVE_FLAG , CONTROL_ACTIVE_FLAG , CNA_NO , CAPACITY , OPERATION_CAPACITY , CERTIFIED_FLAG , DEACTIVATE_DATE , REACTIVATE_DATE , DEACTIVATE_REASON_CODE , COMMENT_TEXT , LOWEST_LEVEL_FLAG , REACH_OPER_CAPACITY_FLAG , NO_OF_OCCUPANT from LIVING_UNITS where LIVING_UNIT_ID = :LIVINGUNITID and living_units.active_flag = 'Y' order by LIST_SEQ
}
GET_LEVEL_HOUSING_LOCATIONS_DATA_BASED_LOV_CODE {
WITH RECURSIVE rec AS (
    SELECT
        *,
        1 AS level
    FROM
        living_units
    WHERE
        agy_loc_id = :agyLocId
        AND (COALESCE(:livingUnitId, 0) = 0
        OR living_unit_id = :livingUnitId)
        AND active_flag = 'Y'
    UNION ALL
    SELECT
        lu.*,
        rec.level + 1
    FROM
        rec
    JOIN
        living_units lu ON lu.parent_living_unit_id = rec.living_unit_id
    WHERE
        lu.active_flag = 'Y'
)
SELECT
    *
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER (PARTITION BY living_unit_id ORDER BY level) AS rn
        FROM
            rec
    ) AS subquery
WHERE
    rn = 1
ORDER BY
    level, list_seq ,living_unit_id
}

GET_LIVING_UNIT_COUNT{
select * from (with recursive rec as (
	select
		*
	from
		living_units
	where
		living_unit_id = :livingUnitId
union all
	select
		living_units.*
	from
		rec,
		living_units
	where
		living_units.parent_living_unit_id = rec.living_unit_id )
	select
		*
	from
		rec) a LIMIT 1
}

OIUZOHOS_GET_INETRANAL_LOCATION_COUNT {
select count(*) from off_obs_zone_details where internal_location_id =:internalLocationId and active_flag='Y'
}
