
OIMSTATU_FIND_CGFKSTATLEGISLATINGBODYCOD {
 	SELECT REF_CODE.CODE  LEGISLATING_BODY_CODE        ,REF_CODE.DESCRIPTION  DSP_DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'LEGISL_BODY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

  OIMSTATU_STAT_FIND_STATUTES {
SELECT statute_code, description, legislating_body_code, active_flag, list_seq, update_allowed_flag, expiry_date, modify_user_id, create_datetime, create_user_id, modify_datetime, seal_flag, row_id FROM statutes 


}
OIMSTATU_STAT_INSERT_STATUTES {
insert into STATUTES(STATUTE_CODE , DESCRIPTION , LEGISLATING_BODY_CODE , ACTIVE_FLAG , LIST_SEQ , UPDATE_ALLOWED_FLAG , EXPIRY_DATE , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:statuteCode , :description , :legislatingBodyCode , :activeFlag , :listSeq , :updateAllowedFlag , :expiryDate , current_timestamp , :createUserId , NULL , :sealFlag ) 
}

OIMSTATU_STAT_UPDATE_STATUTES {
update statutes set statute_code = :statuteCode, description = :description, legislating_body_code = :legislatingBodyCode, active_flag = :activeFlag, list_seq = :listSeq, update_allowed_flag = :updateAllowedFlag, expiry_date = :expiryDate, modify_user_id =:modifyUserId, modify_datetime = current_timestamp, seal_flag = :sealFlag where ROW_ID = :rowId 
}

OIMSTATU_STAT_DELETE_STATUTES { 
	DELETE FROM STATUTES where  ROW_ID = :rowId
}


OIMSTATU_CGFKCHK_STAT_STATUTES_REF_LEG_ {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :LEGISLATINGBODYCODE AND     DOMAIN = 'LEGISL_BODY'
}

OIMSTATU_CGUVCHK_STATUTES_PK_ {
	SELECT  '1' FROM    STATUTES WHERE   STATUTE_CODE = P_STATUTE_CODE
}
OIMSTATU_CONSTRAINT_VALIDATIONS {
SELECT  AC1.TABLE_NAME
        FROM ALL_CONSTRAINTS AC1, ALL_CONSTRAINTS AC2
       WHERE AC1.CONSTRAINT_NAME = :CONSTRAINTNAME
         AND AC1.CONSTRAINT_TYPE = 'R'
         AND AC2.CONSTRAINT_NAME = AC1.R_CONSTRAINT_NAME
         AND AC2.OWNER = AC1.R_OWNER
         AND AC2.CONSTRAINT_TYPE IN ('P', 'U')
}

OIMSTATU_GET_INACTIVE_STATUTES {
	select ORC.RESULT_CODE , ORC.DESCRIPTION , ORC.DISPOSITION_CODE , ORC.CHARGE_STATUS , ORC.ACTIVE_FLAG , ORC.EXPIRY_DATE , ORC.CREATE_USER_ID , ORC.CREATE_DATETIME , ORC.MODIFY_USER_ID , ORC.MODIFY_DATETIME , ORC.CONVICTION_FLAG , ORC.LIST_SEQ , ORC.SEAL_FLAG from ( select DESCRIPTION , CODE from REFERENCE_CODES where domain = 'OFF_RESULT' and ACTIVE_FLAG = 'Y' and DESCRIPTION = 'Final') OFF_CODE, ( select DESCRIPTION , CODE from REFERENCE_CODES where domain = 'CHARGE_STS' and ACTIVE_FLAG = 'Y' and DESCRIPTION = 'Inactive') ACT_STAT, ( select RESULT_CODE , DESCRIPTION , DISPOSITION_CODE , CHARGE_STATUS , ACTIVE_FLAG , EXPIRY_DATE , CREATE_USER_ID , CREATE_DATETIME , MODIFY_USER_ID , MODIFY_DATETIME , CONVICTION_FLAG , LIST_SEQ , SEAL_FLAG from OFFENCE_RESULT_CODES) ORC
	where DISPOSITION_CODE = OFF_CODE.CODE and CHARGE_STATUS = ACT_STAT.CODE
}