
OIDCAPPR_FIND_CGFKOFFASS1REVIEWCOMMITTE {
 select REF_CODE2.CODE, REF_CODE2.DOMAIN , REF_CODE2.DESCRIPTION , REF_CODE2.NEW_CODE , REF_CODE2.PARENT_CODE, case when (REF_CODE2.PARENT_CODE = case ( select TO_CHAR(CASELOAD_TYPE) LV_LABEL from CASELOADS where CASELOAD_ID = ( select WORKING_CASELOAD_ID from STAFF_MEMBERS where USER_ID = :userName)) when 'COMM' then 'COMM' when 'INST' then 'INST' end ) then 1 else 0 end SEQVALUE from REFERENCE_CODES REF_CODE2 where REF_CODE2.DOMAIN = 'ASSESS_COMM' and REF_CODE2.EXPIRED_DATE is null and (REF_CODE2.ACTIVE_FLAG = 'Y' or '' = 'ENTER-QUERY' ) order by REF_CODE2.LIST_SEQ asc , REF_CODE2.DESCRIPTION asc
}

OIDCAPPR_FIND_CGFKOFFASS1REVIEWPLACEAGY {
  select agy_loc.agy_loc_id CODE , agy_loc.description DESCRIPTION from agency_locations agy_loc where agy_loc.agency_location_type = ( select TO_CHAR(CASELOAD_TYPE) LV_LABEL from CASELOADS where CASELOAD_ID = ( select WORKING_CASELOAD_ID from STAFF_MEMBERS where USER_ID = :userName)) and coalesce (agy_loc.deactivation_date,'1010-10-10') = '1010-10-10' and agy_loc_id not in ('TRN', 'OUT') order by list_seq, agy_loc_id
}

OIDCAPPR_FIND_CGFKOFFASS1REVIEWSUPLEVEL {
    select A.SUPERVISION_LEVEL_TYPE CODE , OMS_MISCELLANEOUS_GETDESCCODE ('SUP_LVL_TYPE' , A.SUPERVISION_LEVEL_TYPE ) DESCRIPTION from ASSESSMENT_RESULTS A where A.ASSESSMENT_ID = :ASSESSMENTTYPEID and coalesce(A.EXPIRY_DATE, '1010-10-10') = '1010-10-10' and A.ACTIVE_FLAG = 'Y' order by A.LIST_SEQ , A.SUPERVISION_LEVEL_TYPE
}

OIDCAPPR_FIND_CGFKOFFASS1EVALUATIONRESUL {
     select REF_CODE1.CODE , REF_CODE1.DOMAIN , REF_CODE1.DESCRIPTION , REF_CODE1.NEW_CODE , REF_CODE1.PARENT_CODE from REFERENCE_CODES REF_CODE1 where (domain = 'ASSESS_RSLT' and (( coalesce(EXPIRED_DATE,'1010-10-10') = '1010-10-10' and ACTIVE_FLAG = 'Y' and CODE != 'PEN' ) or ('' = 'ENTER-QUERY' ) ) ) order by REF_CODE1.LIST_SEQ , REF_CODE1.DESCRIPTION
}

OIDCAPPR_OFFASS_FIND_V_OFFASS_ASS {
    select OFFENDER_BOOK_ID , ASSESSMENT_SEQ , ASSESSMENT_DATE , ASSESSMENT_TYPE_ID , SCORE , ASSESS_STATUS , OMS_MISCELLANEOUS_GETDESCCODE ('SUP_LVL_TYPE' , CALC_SUP_LEVEL_TYPE )CALC_SUP_LEVEL_TYPE , ASSESS_STAFF_ID , ASSESS_COMMENT_TEXT , OVERRIDE_REASON_TEXT , PLACE_AGY_LOC_ID , OMS_MISCELLANEOUS_GETDESCCODE ('SUP_LVL_TYPE' , OVERRIDED_SUP_LEVEL_TYPE )OVERRIDED_SUP_LEVEL_TYPE , OVERRIDE_COMMENT_TEXT , OVERRIDE_STAFF_ID , EVALUATION_DATE , NEXT_REVIEW_DATE , EVALUATION_RESULT_CODE , OMS_MISCELLANEOUS_GETDESCCODE ('SUP_LVL_TYPE' , REVIEW_SUP_LEVEL_TYPE )REVIEW_SUP_LEVEL_TYPE , REVIEW_PLACEMENT_TEXT , OMS_MISCELLANEOUS_GETDESCCODE ('ASSESS_COMM' , REVIEW_COMMITTE_CODE )REVIEW_COMMITTE_CODE , COMMITTE_COMMENT_TEXT , REVIEW_PLACE_AGY_LOC_ID , REVIEW_SUP_LEVEL_TEXT , MODIFY_USER_ID , OMS_MISCELLANEOUS_GETDESCCODE ('ASSESS_COMM' , ASSESS_COMMITTE_CODE )ASSESS_COMMITTE_CODE , CREATION_DATE , CREATION_USER , APPROVED_SUP_LEVEL_TYPE , CASELOAD_TYPE , MEDICAL_FLAG , REQUIRE_APPROVAL_FLAG  from V_OFFASS_ASS where OFFENDER_BOOK_ID = :OFFENDERBOOKID order by CASELOAD_TYPE desc, ASSESSMENT_SEQ desc
}
OIDCAPPR_OFFASS1_FIND_OFFENDER_ASSESSMENTS {
 	SELECT OFFENDER_BOOK_ID ,ASSESSMENT_SEQ ,ASSESSMENT_DATE ,ASSESSMENT_TYPE_ID ,SCORE ,ASSESS_STATUS ,CALC_SUP_LEVEL_TYPE ,ASSESS_STAFF_ID ,ASSESS_COMMENT_TEXT ,OVERRIDE_REASON_TEXT ,PLACE_AGY_LOC_ID ,OVERRIDED_SUP_LEVEL_TYPE ,OVERRIDE_COMMENT_TEXT ,OVERRIDE_STAFF_ID ,EVALUATION_DATE ,NEXT_REVIEW_DATE ,EVALUATION_RESULT_CODE ,REVIEW_SUP_LEVEL_TYPE ,REVIEW_PLACEMENT_TEXT ,REVIEW_COMMITTE_CODE ,COMMITTE_COMMENT_TEXT ,REVIEW_PLACE_AGY_LOC_ID ,REVIEW_SUP_LEVEL_TEXT ,MODIFY_USER_ID ,ASSESS_COMMITTE_CODE ,CREATION_DATE ,CREATION_USER ,APPROVED_SUP_LEVEL_TYPE ,ASSESSMENT_CREATE_LOCATION ,ASSESSOR_STAFF_ID ,MODIFY_DATETIME ,OVERRIDE_USER_ID ,OVERRIDE_REASON ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG   FROM OFFENDER_ASSESSMENTS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND ASSESSMENT_SEQ = :ASSESSMENTSEQ  
}
OIDCAPPR_OFFASS1_UPDATE_OFFENDER_ASSESSMENTS {
	UPDATE OFFENDER_ASSESSMENTS set ASSESSMENT_DATE  = :assessmentDate ,ASSESSMENT_TYPE_ID  = :assessmentTypeId ,SCORE  = :score ,ASSESS_STATUS  = :assessStatus ,CALC_SUP_LEVEL_TYPE  = :calcSupLevelType ,ASSESS_STAFF_ID  = :assessStaffId ,ASSESS_COMMENT_TEXT  = :assessCommentText ,OVERRIDE_REASON_TEXT  = :overrideReasonText ,PLACE_AGY_LOC_ID  = :placeAgyLocId ,OVERRIDED_SUP_LEVEL_TYPE  = :overridedSupLevelType ,OVERRIDE_COMMENT_TEXT  = :overrideCommentText ,OVERRIDE_STAFF_ID  = :overrideStaffId ,EVALUATION_DATE  = :evaluationDate ,NEXT_REVIEW_DATE  = :nextReviewDate ,EVALUATION_RESULT_CODE  = :evaluationResultCode ,REVIEW_SUP_LEVEL_TYPE  = :reviewSupLevelType ,REVIEW_PLACEMENT_TEXT  = :reviewPlacementText ,REVIEW_COMMITTE_CODE  = :reviewCommitteCode ,COMMITTE_COMMENT_TEXT  = :committeCommentText ,REVIEW_PLACE_AGY_LOC_ID  = :reviewPlaceAgyLocId ,REVIEW_SUP_LEVEL_TEXT  = :reviewSupLevelText ,MODIFY_USER_ID  = :modifyUserId ,ASSESS_COMMITTE_CODE  = :assessCommitteCode ,CREATION_DATE  = :creationDate ,CREATION_USER  = :creationUser ,APPROVED_SUP_LEVEL_TYPE  = :approvedSupLevelType ,ASSESSMENT_CREATE_LOCATION  = :assessmentCreateLocation ,ASSESSOR_STAFF_ID  = :assessorStaffId ,MODIFY_DATETIME  = current_timestamp ,OVERRIDE_USER_ID  = :overrideUserId ,OVERRIDE_REASON  = :overrideReason ,SEAL_FLAG  = :sealFlag where OFFENDER_BOOK_ID  = :offenderBookId and ASSESSMENT_SEQ  = :assessmentSeq
}


OIDCAPPR_OFF_BKG_PREDELETEPRE-DELETE {
	DELETE FROM V_OFFASS_ASS V WHERE V.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIDCAPPR_OFF_ASS_PREDELETE {
	DELETE FROM OFFENDER_ASSESSMENTS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND ASSESSMENT_SEQ = :ASSESSMENTSEQ
}

OIDCAPPR_OFF_ASS1_POSTQUERY {
	SELECT DETERMINE_SUP_LEVEL_FLAG, REQUIRE_APPROVAL_FLAG FROM ASSESSMENTS WHERE ASSESSMENT_ID = :ASSESSMENTTYPEID AND ASSESSMENT_CLASS = 'TYPE' AND ACTIVE_FLAG = 'Y'
}

OIDCAPPR_CGFKCHK_OFF_ASS1_OFF_ASS_EVAL {
     select REF_CODE1.DOMAIN, REF_CODE1.DESCRIPTION, REF_CODE1.NEW_CODE, REF_CODE1.PARENT_CODE from REFERENCE_CODES REF_CODE1 where REF_CODE1.CODE = :EVALUATIONRESULTCODE and (domain = 'ASSESS_RSLT' and ((coalesce (EXPIRED_DATE,'1010-10-10') = '1010-10-10' and ACTIVE_FLAG = 'Y' and CODE != 'PEN') or ('' = 'QUERY')))
}

OIDCAPPR_CGFKCHK_OFF_ASS1_OFF_ASS_R2 {
      select REF_CODE.DOMAIN , REF_CODE.DESCRIPTION , REF_CODE.NEW_CODE , REF_CODE.PARENT_CODE from REFERENCE_CODES REF_CODE where REF_CODE.CODE = :REVIEWSUPLEVELTYPE and (domain = 'SUP_LVL_TYPE' and coalesce (EXPIRED_DATE,'1010-10-10') = '1010-10-10' and ACTIVE_FLAG = 'Y') or '' = 'QUERY'
}

OIDCAPPR_CGFKCHK_OFF_ASS1_OFF_ASS_AGY {
      select AGY_LOC.DESCRIPTION from AGENCY_LOCATIONS AGY_LOC where AGY_LOC.AGY_LOC_ID = :REVIEWPLACEAGYLOCID and (AGENCY_LOCATION_TYPE = :CASELOADTYPE and ( coalesce (DEACTIVATION_DATE, '1010-10-10') = '1010-10-10' or '' = 'QUERY')) 
}

OIDCAPPR_POST_QUERY_FOR_OFF_ASS {
	SELECT DETERMINE_SUP_LEVEL_FLAG, REQUIRE_APPROVAL_FLAG FROM ASSESSMENTS WHERE ASSESSMENT_ID = :ASSESSMENTTYPEID
}

OIDCAPPR_GET_COM_SUP_DEF {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN='COM_SUP_LVLS' AND ACTIVE_FLAG='Y' AND CODE = P_CODE
}

OIDCAPPR_GET_INST_SUP_DEF {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN='SUP_LVL_TYPE' AND ACTIVE_FLAG='Y' AND CODE = P_CODE
}

OIDCAPPR_GET_REF_CODE_DESC {
	SELECT RC.DESCRIPTION FROM REFERENCE_CODES RC WHERE RC.DOMAIN= P_DOMAIN 
}

OIDCAPPR_CGFKCHK_OFF_ASS_OFF_ASS_ASS_F {
	SELECT ASSESS1.DESCRIPTION ,ASSESS1.ACTIVE_FLAG ,ASSESS1.LIST_SEQ FROM   ASSESSMENTS ASSESS1 WHERE  ASSESS1.ASSESSMENT_ID = :ASSESSMENTTYPEID AND     (ASSESS1.ACTIVE_FLAG = 'Y' OR '' != 'NORMAL')
}

OIDCAPPR_CGFKCHK_OFF_ASS_OFF_ASS_REF_A {
	SELECT REF_CODE9.DESCRIPTION, REF_CODE9.LIST_SEQ, REF_CODE9.ACTIVE_FLAG FROM REFERENCE_CODES REF_CODE9 WHERE REF_CODE9.CODE = :ASSESSCOMMITTECODE AND REF_CODE9.DOMAIN = 'ASSESS_COMM' AND (REF_CODE9.ACTIVE_FLAG = 'Y' OR '' != 'NORMAL')
}

OIDCAPPR_GET_ASSESSMENTS {
	SELECT * FROM OFFENDER_ASSESSMENT_ITEMS WHERE OFFENDER_BOOK_ID = :offenderBookId AND ASSESSMENT_SEQ = :assessmentSeq
}
