
OIICLASS_FIND_CGFKASSESSMENTTYPE {
SELECT ASSESS.DESCRIPTION AS ASSESSMENT_TYPE, ASSESS.ASSESSMENT_ID AS ASSESSMENT_ID, ASSESS.CASELOAD_TYPE FROM ASSESSMENTS AS ASSESS WHERE ASSESS.ASSESSMENT_CLASS = 'TYPE' AND ASSESS.PARENT_ASSESSMENT_ID IS NULL AND ( ASSESS.CASELOAD_TYPE = ANY ( CASE WHEN ( SELECT caseload_type FROM caseloads WHERE caseload_id = ( SELECT working_caseload_id FROM staff_members WHERE user_id = :userId ) ) = 'INST' THEN ARRAY['INST'] ELSE ARRAY['COMM', 'BOTH'] END ) ) AND ASSESS.ACTIVE_FLAG = 'Y' ORDER BY ASSESS.LIST_SEQ ASC;
}
 	

OIICLASS_FIND_CGFKAGYLOCID {
 	SELECT   AL.AGY_LOC_ID AGY_LOC_ID ,          AL.DESCRIPTION      FROM AGENCY_LOCATIONS AL    WHERE AL.AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID                              FROM CASELOAD_AGENCY_LOCATIONS CAL ,                                   CASELOADS CAS                             WHERE CAS.CASELOAD_ID = CAL.CASELOAD_ID                               AND CAL.CASELOAD_ID = (select working_caseload_id      from staff_members        where user_id = :userId)                              AND CAL.AGY_LOC_ID NOT IN ('OUT' , 'TRN' )                               AND CAS.ACTIVE_FLAG = 'Y'                               AND (   CAL.UPDATE_ALLOWED_FLAG = 'Y'                                    OR '' <> 'NORMAL'                                    ) ) ORDER BY AL.LIST_SEQ ASC
}

OIICLASS_FIND_CGFKHOUSINGLEVEL1 {
 	SELECT LIV_UNIT.LIVING_UNIT_CODE ,LIV_UNIT.LIVING_UNIT_ID FROM   LIVING_UNITS LIV_UNIT WHERE  AGY_LOC_ID = :agyLocId AND    ACTIVE_FLAG = 'Y' AND    PARENT_LIVING_UNIT_ID IS NULL
}

OIICLASS_FIND_CGFKHOUSINGLEVEL2 {
 	SELECT LIV_UNIT1.LIVING_UNIT_CODE  ,LIV_UNIT1.LIVING_UNIT_ID FROM   LIVING_UNITS LIV_UNIT1 WHERE   AGY_LOC_ID = :agyLocId AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID IN (SELECT LIVING_UNIT_ID 
                                              	FROM LIVING_UNITS 
                                              	WHERE LIVING_UNIT_CODE = :livingUnitId)
}

OIICLASS_FIND_CGFKHOUSINGLEVEL3 {
 	SELECT LIV_UNIT1.LIVING_UNIT_CODE  LIVING_UNIT_CODE3        ,LIV_UNIT1.LIVING_UNIT_ID  LIVING_UNIT_ID3 FROM   LIVING_UNITS LIV_UNIT1 WHERE   AGY_LOC_ID = ::AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID = ::NBTLIVUNITID2
}
OIICLASS_SYSPROF_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}
OIICLASS_LIVUNIT_FIND_LIVING_UNITS {
 	SELECT LIVING_UNIT_ID ,AGY_LOC_ID ,LIVING_UNIT_TYPE ,LIVING_UNIT_CODE ,DESCRIPTION ,LEVEL_1_CODE ,LEVEL_2_CODE ,LEVEL_3_CODE ,LEVEL_4_CODE ,USER_DESC ,ACA_CAP_RATING ,SECURITY_LEVEL_CODE ,LIST_SEQ ,PARENT_LIVING_UNIT_ID ,HOUSING_UNIT_TYPE ,ACTIVE_FLAG ,CONTROL_ACTIVE_FLAG ,CNA_NO ,CAPACITY ,OPERATION_CAPACITY ,CERTIFIED_FLAG ,DEACTIVATE_DATE ,REACTIVATE_DATE ,DEACTIVATE_REASON_CODE ,COMMENT_TEXT ,LOWEST_LEVEL_FLAG ,REACH_OPER_CAPACITY_FLAG ,NO_OF_OCCUPANT   FROM LIVING_UNITS  /* where  */
}
OIICLASS_LIVUNIT_INSERT_LIVING_UNITS {
	INSERT INTO LIVING_UNITS(LIVING_UNIT_ID ,AGY_LOC_ID ,LIVING_UNIT_TYPE ,LIVING_UNIT_CODE ,DESCRIPTION ,LEVEL_1_CODE ,LEVEL_2_CODE ,LEVEL_3_CODE ,LEVEL_4_CODE ,USER_DESC ,ACA_CAP_RATING ,SECURITY_LEVEL_CODE ,LIST_SEQ ,PARENT_LIVING_UNIT_ID ,HOUSING_UNIT_TYPE ,ACTIVE_FLAG ,CONTROL_ACTIVE_FLAG ,CNA_NO ,CAPACITY ,OPERATION_CAPACITY ,CERTIFIED_FLAG ,DEACTIVATE_DATE ,REACTIVATE_DATE ,DEACTIVATE_REASON_CODE ,COMMENT_TEXT ,LOWEST_LEVEL_FLAG ,REACH_OPER_CAPACITY_FLAG ,NO_OF_OCCUPANT ) VALUES(:livingUnitId ,:agyLocId ,:livingUnitType ,:livingUnitCode ,:description ,:level1Code ,:level2Code ,:level3Code ,:level4Code ,:userDesc ,:acaCapRating ,:securityLevelCode ,:listSeq ,:parentLivingUnitId ,:housingUnitType ,:activeFlag ,:controlActiveFlag ,:cnaNo ,:capacity ,:operationCapacity ,:certifiedFlag ,:deactivateDate ,:reactivateDate ,:deactivateReasonCode ,:commentText ,:lowestLevelFlag ,:reachOperCapacityFlag ,:noOfOccupant )
}

OIICLASS_LIVUNIT_UPDATE_LIVING_UNITS {
	UPDATE LIVING_UNITS set LIVING_UNIT_ID  = :livingUnitId ,AGY_LOC_ID  = :agyLocId ,LIVING_UNIT_TYPE  = :livingUnitType ,LIVING_UNIT_CODE  = :livingUnitCode ,DESCRIPTION  = :description ,LEVEL_1_CODE  = :level1Code ,LEVEL_2_CODE  = :level2Code ,LEVEL_3_CODE  = :level3Code ,LEVEL_4_CODE  = :level4Code ,USER_DESC  = :userDesc ,ACA_CAP_RATING  = :acaCapRating ,SECURITY_LEVEL_CODE  = :securityLevelCode ,LIST_SEQ  = :listSeq ,PARENT_LIVING_UNIT_ID  = :parentLivingUnitId ,HOUSING_UNIT_TYPE  = :housingUnitType ,ACTIVE_FLAG  = :activeFlag ,CONTROL_ACTIVE_FLAG  = :controlActiveFlag ,CNA_NO  = :cnaNo ,CAPACITY  = :capacity ,OPERATION_CAPACITY  = :operationCapacity ,CERTIFIED_FLAG  = :certifiedFlag ,DEACTIVATE_DATE  = :deactivateDate ,REACTIVATE_DATE  = :reactivateDate ,DEACTIVATE_REASON_CODE  = :deactivateReasonCode ,COMMENT_TEXT  = :commentText ,LOWEST_LEVEL_FLAG  = :lowestLevelFlag ,REACH_OPER_CAPACITY_FLAG  = :reachOperCapacityFlag ,NO_OF_OCCUPANT  = :noOfOccupant /* where */
}

OIICLASS_OIICLASS_FIND_OIICLASS_CLASS_INQUIRY {
 	SELECT   FROM OIICLASS_CLASS_INQUIRY  /* where  */
}
OIICLASS_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OIICLASS_DEFAULT_AGY_LOCDEFAULT_AGY_LOC {
	SELECT ALAL.AGY_LOC_ID, ALAL.DESCRIPTION DSP_DESCRIPTION2 INTO P_AGY_LOC_ID, P_DESCRIPTION FROM AGENCY_LOCATIONS ALAL WHERE ALAL.AGENCY_LOCATION_TYPE = 'INST' AND ALAL.AGY_LOC_ID IN ( SELECT CA.AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS CA WHERE CA.CASELOAD_ID = P_GLOBAL_CASELOAD_ID ) AND ALAL.AGY_LOC_ID NOT IN ( 'TRN', 'OUT' )
}
