OCMXPSTM_REF_CODE_CONDS{
  SELECT CODE , DESCRIPTION , UPDATE_FLAG , UPDATE_REASON_FLAG FROM MAINTAIN_SPECIALIZED_PRG_STS where code = :code
}

OCMXPSTM_REFCODE_UPDATE_REFERENCE_CODES{
UPDATE MAINTAIN_SPECIALIZED_PRG_STS set UPDATE_FLAG  = :updateFlag ,UPDATE_REASON_FLAG  = :updateReasonFlag ,MODIFY_USER_ID  = :modifyUserId, MODIFY_DATETIME  = current_timestamp   where CODE  = :code
}

OCMXPSTM_REFCODE_INSERT_REFERENCE_CODES{
 insert into MAINTAIN_SPECIALIZED_PRG_STS (CODE , DESCRIPTION , UPDATE_FLAG , UPDATE_REASON_FLAG , SEAL_FLAG , CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID, CREATE_DATETIME) values(:code , :description , :updateFlag , :updateReasonFlag , :sealFlag, :createUserId, null , null , CURRENT_TIMESTAMP)
}