
OCUSCUPS_OFFCRSATTEND_FIND_OFFENDER_COURSE_ATTENDANCES_NEW {
 SELECT EVENT_ID, OFFENDER_BOOK_ID, EVENT_DATE, START_TIME, END_TIME, EVENT_SUB_TYPE, EVENT_STATUS, COMMENT_TEXT, HIDDEN_COMMENT_TEXT, TO_INTERNAL_LOCATION_ID, CRS_SCH_ID, OUTCOME_REASON_CODE, PIECE_WORK, ENGAGEMENT_CODE, UNDERSTANDING_CODE, DETAILS, CREDITED_HOURS, AGREED_TRAVEL_HOUR, SUPERVISOR_NAME, BEHAVIOUR_CODE, ACTION_CODE, SICK_NOTE_RECEIVED_DATE, SICK_NOTE_EXPIRY_DATE, OFF_PRGREF_ID, IN_TIME, OUT_TIME, PERFORMANCE_CODE, REFERENCE_ID, TO_ADDRESS_OWNER_CLASS, TO_ADDRESS_ID, OFF_CRS_SCH_REF_ID, SUPERVISOR_STAFF_ID, CRS_APPT_ID, OFFENDER_COURSE_APPT_RULE_ID, CRS_ACTY_ID, EVENT_TYPE, AGY_LOC_ID, EVENT_CLASS, UNEXCUSED_ABSENCE_FLAG, TO_AGY_LOC_ID, SESSION_NO, OFFENDER_PRG_OBLIGATION_ID, PROGRAM_ID, BONUS_PAY, TXN_ID, TXN_ENTRY_SEQ, PAY_FLAG, AUTHORISED_ABSENCE_FLAG, SEAL_FLAG, DIRECTION_CODE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID ,tag_reference_codes_getdesccode('OUTCOMES', attendence.EVENT_OUTCOME) EVENT_OUTCOME FROM OFFENDER_COURSE_ATTENDANCES attendence where CRS_SCH_ID=:crs_sch_id
}
OCUSCUPS_OFFCRSATTEND_UPDATE_OFFENDER_COURSE_ATTENDANCES {
	UPDATE OFFENDER_COURSE_ATTENDANCES set 
}

OCUSCUPS_GET_OFFENDER_DETAILS {
SELECT O.OFFENDER_ID_DISPLAY, O.LAST_NAME, O.FIRST_NAME, OB.AGY_LOC_ID FROM OFFENDER_BOOKINGS OB, OFFENDERS O WHERE OB.OFFENDER_BOOK_ID =:offBookId AND OB.OFFENDER_ID = O.OFFENDER_ID
}