
OCUSMODU_VACPSCH_FIND_V_ACP_SCHEDULES {
select
	CATCH_UP_SESSION_FLAG,
	CRS_SCH_ID,
	END_TIME,
	INTERNAL_LOCATION_DESC,
	MODULE_INSTANCE_DESC,
	MODULE_INSTANCE_ID,
	MODULE_LIST_SEQ,
	PHASE_CODE,
	PHASE_DESCRIPTION,
	PHASE_INSTANCE_CODE,
	PHASE_INSTANCE_DESC,
	PHASE_INSTANCE_ID,
	PHASE_LIST_SEQ,
	PHASE_PROVIDER_NAME,
	PHASE_PROVIDER_PARTY_CLASS,
	PHASE_PROVIDER_PARTY_CODE,
	PHASE_PROVIDER_PARTY_ID,
	PHASE_SESSION_LENGTH,
	PROGRAM_CODE,
	PROGRAM_DESC,
	PROGRAM_ID,
	PROGRAM_INSTANCE_CODE,
	PROGRAM_INSTANCE_DESC,
	PROGRAM_INSTANCE_ID,
	SCHEDULE_DATE,
	SCHEDULE_STATUS,
	SESSION_NO,
	START_TIME
from
	V_ACP_SCHEDULES
where
	phase_instance_id = :crsActId and
	session_no = :sessionNo  
	and schedule_status = 'SCH'
	and catch_up_session_flag = 'N'
order by
	start_time asc
}
OCUSMODU_VACPSCH_UPDATE_V_ACP_SCHEDULES {
	UPDATE V_ACP_SCHEDULES set 
}
OCUSMODU_GET_WEEKDAY {
select TO_CHAR(to_timestamp(:schDate,'YY-MM-DD HH24:MI:SS.FF'), 'Day') from dual
}


