update
	dynamic_grid_config
set
	CONFIG_JSON = '[ { "field": "displayNo", "fieldName": "ocdleglo.no", "dataType": "text", "editable": false }, { "field": "orderNo", "hide": true, "dataType": "text", "editable": false }, { "field": "orderedDate", "fieldName": "ocdleglo.ordereddate", "dataType": "date", "required": true }, { "field": "matter", "fieldName": "ocdleglo.matter", "dataType": "text", "editable": false }, { "field": "court", "fieldName": "ocdleglo.court", "dataType": "lov", "source": "link", "url": "ocdccase/populateCourtData", "sourceType": "OUMAGLOC", "required": true }, { "field": "sentenceCalcType", "fieldName": "ocdleglo.type", "dataType": "lov", "source": "link", "url": "ocmpconf/populateSentType?sentCategory=", "sourceType": "OIMSREQS", "required": true }, { "field": "commenceType", "fieldName": "ocdleglo.commencetype", "dataType": "lov", "source": "link", "url": "ocmpconf/getCommenceType?orderType=", "sourceType": "OUMRCODE", "required": true, "sourceDomain":"LO_REL_TYPE" }, { "field": "relatedTo", "fieldName": "ocdleglo.linkto", "dataType": "text", "editable": false }, { "field": "relatedToLaunch", "dataType": "hyperlink", "link": "/relatedToLine", "parentField": [ "relatedTo" ] }, { "field": "commenceDate", "fieldName": "ocdleglo.commencedate", "dataType": "date" }, { "field": "termTypeAndLength", "fieldName": "ocdleglo.termtypeandlength", "dataType": "text", "required": true, "editable": false }, { "field": "lengthBtn", "dataType": "hyperlink", "link": "/termToLine", "parentField": [ "termTypeAndLength", "terms" ] }, { "field": "status", "fieldName": "ocdleglo.status", "dataType": "lov", "source": "link", "sourceType": "OCMSTATS", "url": "ocmpconf/rgOrderStatus?orderType=", "editable": true, "required": true }, { "field": "intParties", "dataType": "hyperlink", "link": "/OCDINTPA", "fieldName": "ocdleglo.intParties" }, { "field": "terms", "hide": true, "dataType": "text" }, { "field": "charges", "hide": true, "dataType": "text" }, { "field": "orderType", "hide": true, "dataType": "text" }, { "field": "holdExpiryDate", "fieldName": "ocdleglo.holdExpirydate", "dataType": "date" }, { "field": "activeType", "hide": true, "dataType": "text" }, { "field": "iwpButton", "fieldName": "common.documents", "dataType": "hyperlink", "link": "/EOFFENDER", "queryparam": [ "objectId" ] } ]  ',
	modify_datetime = current_timestamp ,
	modify_user_id = 'OMS_OWNER'
where
	MODULE_NAME = 'OCDCORDS'
	and GRID_NAME = 'custOrd'
	and db_table_name = 'OCDLEGLO_DATA';

update
	dynamic_grid_config
set
	CONFIG_JSON = '[ { "field": "displayNo", "fieldName": "ocdncode.no", "dataType": "text", "editable": false }, { "field": "orderNo", "hide": true, "dataType": "text", "editable": false }, { "field": "orderedDate", "fieldName": "ocdncode.ordereddate", "dataType": "date", "required": true }, { "field": "matter", "fieldName": "ocdncode.matter", "dataType": "text", "editable": false }, { "field": "court", "fieldName": "ocdncode.court", "dataType": "lov", "source": "link", "url": "ocdccase/populateCourtData", "sourceType": "OUMAGLOC", "required": true }, { "field": "sentenceCalcType", "fieldName": "ocdncode.type", "dataType": "lov", "source": "link", "url": "ocmpconf/populateSentType?sentCategory=", "sourceType": "OIMSREQS", "required": true }, { "field": "commenceType", "fieldName": "ocdncode.commencetype", "dataType": "lov", "source": "link", "url": "ocmpconf/getCommenceType?orderType=", "sourceType": "OUMRCODE", "required": true, "sourceDomain": "LO_REL_TYPE" }, { "field": "relatedTo", "fieldName": "ocdncode.linkto", "dataType": "text", "editable": false }, { "field": "relatedToLaunch", "dataType": "hyperlink", "link": "/nonCustRelated", "parentField": [ "relatedTo" ] }, { "field": "commenceDate", "fieldName": "ocdncode.commencedate", "dataType": "date" }, { "field": "termTypeAndLength", "fieldName": "ocdncode.termtypeandlength", "dataType": "text", "required": true, "editable": false }, { "field": "lengthBtn", "dataType": "hyperlink", "link": "/nonCustDuration", "parentField": [ "termTypeAndLength", "terms" ] }, { "field": "expiryDate", "fieldName": "ocdncode.expiryDate", "dataType": "date", "editable": true }, { "field": "status", "fieldName": "ocdncode.status", "dataType": "lov", "source": "link", "sourceType": "OCMSTATS", "url": "ocmpconf/rgOrderStatus?orderType=", "editable": true, "required": true }, { "field": "intParties", "dataType": "hyperlink", "link": "/OCDINTPA", "fieldName": "ocdncode.intparties" }, { "field": "terms", "hide": true, "dataType": "text" }, { "field": "orderType", "hide": true, "dataType": "text" }, { "field": "charges", "hide": true, "dataType": "text" }, { "field": "activeType", "hide": true, "dataType": "text" }, { "field": "iwpButton", "fieldName": "ocdleglo.document", "dataType": "hyperlink", "link": "/EOFFENDER", "queryparam": [ "objectId" ] } ]',
	modify_datetime = current_timestamp ,
	modify_user_id = 'OMS_OWNER'
where
	MODULE_NAME = 'OCDNCODE'
	and GRID_NAME = 'nonCustOrd'
	and db_table_name = 'OCDLEGLO_DATA';