
OIDRPITM_FIND_RGCOLOR {
 	SELECT CODE , DESCRIPTION FROM REFERENCE_CODES  WHERE DOMAIN = 'PPTY_COLOR'  AND ( (ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR  'ENTER-QUERY' = 'ENTER-QUERY'  ) ORDER BY LIST_SEQ
}

OIDRPITM_FIND_RGCONDN {
 	SELECT CODE,DESCRIPTION FROM REFERENCE_CODES  WHERE DOMAIN = 'PPTY_CONDIT'  AND ( (ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR 'ENTER-QUERY'= 'ENTER-QUERY'  ) ORDER BY LIST_SEQ
}

OIDRPITM_FIND_CGFKOFFPIRECEIVEDFROM {
 	SELECT CODE,DESCRIPTION   FROM   REFERENCE_CODES WHERE   DOMAIN='PPTY_REC_FRM' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL ORDER BY  LIST_SEQ ,DESCRIPTION
}

OIDRPITM_FIND_CGFKOFFPIPROPERTYTYPE {
 	SELECT CODE,DESCRIPTION   FROM   REFERENCE_CODES WHERE   DOMAIN = 'PPTY_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  LIST_SEQ ,DESCRIPTION
}
OIDRPITM_OFFPI_INSERT_OFFENDER_PPTY_ITEMS {
INSERT INTO OFFENDER_PPTY_ITEMS( 
 PROPERTY_ITEM_SEQ,
 OFFENDER_BOOK_ID,
 PROPERTY_TYPE,
 PROPERTY_DESCRIPTION,
 AGY_LOC_ID,STATUS_CODE,   
 CONDITION_CODE,
 RECEIVED_FROM,   
 PROPERTY_CONTAINER_ID,
 COMMENT_TEXT,
 CONFIRM_FLAG,   
 DISPOSED_TO_CORP_ID,
 DISPOSED_TO_OFFENDER_FLAG,
 DISPOSED_TO_PERSON,
 DISPOSED_TO_PERSON_ID,COLOR,
 MAKE,
 PROPERTY_SIZE,
 PROPERTY_VALUE,
 SERIAL_NO,QUANTITY,   
 CREATE_DATETIME,CREATE_USER_ID,   
 MODIFY_DATETIME,           
 SEAL_FLAG    
 ) 
 VALUES(
 :propertyItemSeq,
 :offenderBookId,
 :propertyType,
 :propertyDescription,
 :agyLocId,
 :statusCode,
 :conditionCode,
 :receivedFrom,
 :propertyContainerId,
 :commentText,
 :confirmFlag,
 :disposedToCorpId,
 :disposedToOffenderFlag,
 :disposedToPerson,
 :disposedToPersonId,
 :color,
 :make,
 :propertySize,
 :propertyValue,
 :serialNo,
 :quantity,
 current_timestamp,
 :createUserId,
 null,
 :sealFlag
) 
}

OIDRPITM_OFFPI_UPDATE_OFFENDER_PPTY_ITEMS {
	UPDATE OFFENDER_PPTY_ITEMS set 
 PROPERTY_ITEM_SEQ=:propertyItemSeq,
 OFFENDER_BOOK_ID=:offenderBookId,
 PROPERTY_TYPE=:propertyType,
 PROPERTY_DESCRIPTION= :propertyDescription,
 AGY_LOC_ID= :agyLocId,
 STATUS_CODE= :statusCode,  
 CONDITION_CODE= :conditionCode,
 RECEIVED_FROM=:receivedFrom,  
 PROPERTY_CONTAINER_ID=:propertyContainerId,
 COMMENT_TEXT=:commentText,
 CONFIRM_FLAG=:confirmFlag,  
 DISPOSED_TO_CORP_ID=:disposedToCorpId,
 DISPOSED_TO_OFFENDER_FLAG=:disposedToOffenderFlag,
 DISPOSED_TO_PERSON=:disposedToPerson,
 DISPOSED_TO_PERSON_ID=:disposedToPersonId,
 COLOR= :color,
 MAKE= :make,  
 PROPERTY_SIZE= :propertySize,
 PROPERTY_VALUE= :propertyValue,
 SERIAL_NO= :serialNo,
 QUANTITY=:quantity,    
 MODIFY_DATETIME= current_timestamp,        
 MODIFY_USER_ID=:modifyUserId,  
 SEAL_FLAG= :sealFlag     WHERE OFFENDER_BOOK_ID=:offenderBookId AND PROPERTY_ITEM_SEQ=:propertyItemSeq
}

OIDRPITM_OFFPI_DELETE_OFFENDER_PPTY_ITEMS { 
	DELETE FROM OFFENDER_PPTY_ITEMS WHERE OFFENDER_BOOK_ID=:offenderBookId AND PROPERTY_ITEM_SEQ=:propertyItemSeq
}

OIDRPITM_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT   FROM SYSTEM_PROFILES  /* where  */
}

OIDRPITM_V_PHEAD_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM OFFENDER_PPTY_ITEMS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIDRPITM_OFF_PI_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'PPTY_COLOR' AND CODE = :COLOR
}

OIDRPITM_OFF_PI_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'PPTY_CONDIT' AND CODE = :CONDITIONCODE
}

OIDRPITM_OFF_PI_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN='PPTY_REC_FRM' AND CODE = :RECEIVEDFROM
}

OIDRPITM_OFF_PI_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES REF_CODE3 WHERE DOMAIN = 'PPTY_TYPE' AND CODE = :PROPERTYTYPE
}

OIDRPITM_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OIDRPITM_CGFKCHK_OFF_PI_OFF_PI_REF_3{
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :COLOR AND     DOMAIN = 'PPTY_COLOR' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}
OIDRPITM_OFF_EM_PREINSERT_C  {
 SELECT COALESCE(MAX(PROPERTY_ITEM_SEQ), 0) + 1 FROM  OFFENDER_PPTY_ITEMS  WHERE OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID  
}

OIDRPITM_OFFPI_FIND {
 SELECT PROPERTY_ITEM_SEQ ,OFFENDER_BOOK_ID ,PROPERTY_TYPE ,PROPERTY_DESCRIPTION ,AGY_LOC_ID ,STATUS_CODE ,CONDITION_CODE ,RECEIVED_FROM ,PROPERTY_CONTAINER_ID ,COMMENT_TEXT ,CONFIRM_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_OFFENDER_FLAG ,DISPOSED_TO_PERSON ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE, PROPERTY_SIZE ,PROPERTY_VALUE, SERIAL_NO ,QUANTITY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_ITEMS  
 WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND  STATUS_CODE=:STATUS_CODE  AND AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID
                                  FROM CASELOAD_AGENCY_LOCATIONS CAL
                                 WHERE CAL.CASELOAD_ID = :CASELOAD_ID
                                   AND CAL.AGY_LOC_ID NOT IN ( 'OUT', 'TRN' )) 
}

OIDRPITM_RECIEVE_FORM {
SELECT CODE, DESCRIPTION
     FROM REFERENCE_CODES
    WHERE DOMAIN = 'PPTY_REC_FRM' 
      AND ACTIVE_FLAG = 'Y' 
      AND EXPIRED_DATE IS NULL
}
OIDRPITM_GET_DESCRIPTION {
SELECT DESCRIPTION FROM REFERENCE_CODES WHERE CODE=:code AND DOMAIN='PPTY_TYPE'
}
MAX_IMAGE_ID {
SELECT MAX(IMAGE_ID) FROM IMAGES
}
INSERT_IMAGE{
INSERT INTO images VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)
}
IS_IMAGE_EXIST{
SELECT IMAGE_ID FROM IMAGES WHERE IMAGE_OBJECT_ID=? AND IMAGE_OBJECT_SEQ=?
}
UPDATE_IMAGE{
UPDATE IMAGES SET IMAGE_THUMBNAIL=? where IMAGE_ID=?
}
GET_PROPERTY_IMAGE{
SELECT IMAGE_THUMBNAIL ,IMAGE_ID FROM IMAGES WHERE IMAGE_OBJECT_ID=:OFFENDER_BOOK_ID AND IMAGE_OBJECT_SEQ=:PROPERTY_ITEM_SEQ AND IMAGE_OBJECT_TYPE = 'PPTY'
}
DELETE_IMAGE_ORIGINALS{
DELETE FROM IMAGE_ORIGINALS WHERE IMAGE_ID=?
}
DELETE_IMAGE{
DELETE FROM IMAGES WHERE IMAGE_ID=?
}
