
OIDRTCON_OFFCON_FIND_OFFENDER_PPTY_CONTAINERS {
select PROPERTY_ONLY_FLAG , PROPERTY_CONTAINER_ID , OFFENDER_BOOK_ID , AGY_LOC_ID , ACTIVE_FLAG , PROPOSED_DISPOSAL_DATE , COMMENT_TEXT , INTERNAL_LOCATION_ID , CONTAINER_CODE , EXPIRY_DATE , SEAL_MARK , TRN_FROM_AGY_LOC_ID , TRN_TO_AGY_LOC_ID ,
CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID , PROPERTY_STORAGE_ID , DISPOSED_TO , DISPOSED_TO_NAME , SEAL_FLAG from OFFENDER_PPTY_CONTAINERS where TRN_TO_AGY_LOC_ID in ( select agy_loc_id from caseload_agency_locations 
where caseload_id = ( select caseload_id from caseloads where caseload_id = ( select working_caseload_id from staff_members where user_id = :USER_id))) order by OFFENDER_BOOK_ID
}
OIDRTCON_OFFCON_UPDATE_OFFENDER_PPTY_CONTAINERS {
UPDATE OFFENDER_PPTY_CONTAINERS set PROPERTY_ONLY_FLAG  = :propertyOnlyFlag ,OFFENDER_BOOK_ID  = :offenderBookId ,AGY_LOC_ID  = :agyLocId ,ACTIVE_FLAG  = :activeFlag ,PROPOSED_DISPOSAL_DATE  = :proposedDisposalDate ,COMMENT_TEXT  = :commentText ,INTERNAL_LOCATION_ID  = :internalLocationId ,CONTAINER_CODE  = :containerCode ,EXPIRY_DATE  = :expiryDate ,SEAL_MARK  = :sealMark ,TRN_FROM_AGY_LOC_ID  = :trnFromAgyLocId ,TRN_TO_AGY_LOC_ID  = :trnToAgyLocId ,MODIFY_DATETIME  =current_timestamp,MODIFY_USER_ID  = :modifyUserId ,PROPERTY_STORAGE_ID  = :propertyStorageId ,DISPOSED_TO  = :disposedTo ,DISPOSED_TO_NAME  = :disposedToName ,SEAL_FLAG  = :sealFlag where PROPERTY_CONTAINER_ID  = :propertyContainerId

}


OIDRTCON_CGFKCHK_OFF_CON_OFF_CON_REF_C_ {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :CONTAINERCODE AND     DOMAIN='PPTY_CNTNR' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR :MODE = 'QUERY')
}

OIDRTCON_CGFKLKP_OFF_CON_OFF_CON_REF_C_ {
	SELECT REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.DESCRIPTION = :DSPDESCRIPTION AND     DOMAIN='PPTY_CNTNR' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR :MODE = 'QUERY')
}

OIDRTCON_CGFKCHK_OFF_CON_OFF_CON_OFF_B {
	SELECT OFF_BKG.OFFENDER_ID ,OFF_NAME.OFFENDER_ID_DISPLAY ,OFF_NAME.LAST_NAME||', '||OFF_NAME.FIRST_NAME OFFENDER_NAME FROM   OFFENDER_BOOKINGS OFF_BKG ,OFFENDERS OFF_NAME WHERE  OFF_BKG.OFFENDER_BOOK_ID = :OFFENDERBOOKID AND    OFF_NAME.OFFENDER_ID = OFF_BKG.OFFENDER_ID
}

OIDRTCON_RECIEVED_FROM_LOV {
	SELECT DESCRIPTION, AGY_LOC_ID, ACTIVE_FLAG FROM AGENCY_LOCATIONS 
}

GETTING_OLD_OFFENDER_PPT_YITE_MSDATA{
 select * from offender_ppty_items where PROPERTY_CONTAINER_ID = :property_container_id LIMIT 1
 }
GET_ACTIVE_PROP_TYPE_INT_LOCTATION{ 
SELECT C.DESCRIPTION ,        C.INTERNAL_LOCATION_CODE CODE  ,        C.INTERNAL_LOCATION_ID,    FROM INT_LOC_USAGE_LOCATIONS A ,  
      INTERNAL_LOCATION_USAGES B ,        AGENCY_INTERNAL_LOCATIONS C  WHERE A.INTERNAL_LOCATION_USAGE_ID = B.INTERNAL_LOCATION_USAGE_ID    AND B.INTERNAL_LOCATION_USAGE    = 'PROP'
  AND  B.AGY_LOC_ID = :AGYLOCID  AND A.INTERNAL_LOCATION_ID = C.INTERNAL_LOCATION_ID    AND (C.ACTIVE_FLAG = 'Y'    AND C.DEACTIVATE_DATE IS NULL )
     ORDER BY  A.LIST_SEQ  ,C.DESCRIPTION
}

GET_TR_LOCATION_ID {
select INTERNAL_LOCATION_ID from AGENCY_INTERNAL_LOCATIONS where INTERNAL_LOCATION_CODE = :internalLocationCode and AGY_LOC_ID = :agyLocId and active_flag='Y'
}