
	OIDTPRIT_FIND_CGFKITMTXFROMSTATUSCODE {
 SELECT DESCRIPTION , REF_CODE.CODE    /* CG$FK */        ,REF_CODE.LIST_SEQ  DSP_LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE   (DOMAIN = 'PPTY_ITM_STS' AND ((ACTIVE_FLAG = 'Y' AND       EXPIRED_DATE IS NULL ) OR   ('QUERY'  = 'QUERY' ) ) AND REF_CODE.CODE != 'TRANSIT' AND REF_CODE.CODE IN    (SELECT DISTINCT ITEM_STATUS_FROM       FROM ITEM_TRANSACTION_STATII      WHERE ITEM_STATUS_TO != 'DISPOSED' ) ) ORDER BY  REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION
}
	OIDTPRIT_FIND_CGFKITMTXTOSTATUSCODE {
 SELECT REF.DESCRIPTION , ITM_STS.ITEM_STATUS_TO  , ITM_STS.LIST_SEQ   FROM   ITEM_TRANSACTION_STATII ITM_STS , REFERENCE_CODES REF 
WHERE ITEM_STATUS_FROM =:FROMSTATUSCODE  AND ITEM_STATUS_FROM != 'TRANSIT'  AND ITM_STS.ITEM_STATUS_TO != 'DISPOSED' AND REF.DOMAIN = 'PPTY_ITM_STS' AND REF.CODE = ITEM_STATUS_TO AND ( (REF.ACTIVE_FLAG = 'Y' AND REF.EXPIRED_DATE IS NULL ) OR ('' = 'QUERY'  )  )
 ORDER BY  ITM_STS.LIST_SEQ ASC
}
	OIDTPRIT_FIND_CGFKITMTXPROPERTYCONTAINER {
 --SELECT TO_CHAR(OFF_CON3.PROPERTY_CONTAINER_ID) CODE         , OFF_CON3.AGY_LOC_ID  DSP_AGY_LOC_ID2        , OFF_CON3.ACTIVE_FLAG  DSP_ACTIVE_FLAG2        , OFF_CON3.OFFENDER_BOOK_ID  DSP_OFFENDER_BOOK_ID2        , OFF_CON3.PROPERTY_STORAGE_ID  DSP_PROPERTY_STORAGE_ID2        , OFF_CON3.CONTAINER_CODE  DSP_CONTAINER_CODE2        , TAG_UTILS.GET_REF_DESCP('PPTY_CNTNR' ,OFF_CON3.CONTAINER_CODE ) CONTAINER_DESCRIPTION        , AGY_INT.DESCRIPTION DSP_DESCRIPTION2 FROM   OFFENDER_PPTY_CONTAINERS OFF_CON3 ,        AGENCY_INTERNAL_LOCATIONS AGY_INT WHERE  OFF_CON3.AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID                                FROM CASELOAD_AGENCY_LOCATIONS CAL                                WHERE CAL.CASELOAD_ID =:CASELOADID                                AND CAL.AGY_LOC_ID NOT IN ( 'OUT' , 'TRN'  ) )  AND OFF_CON3.OFFENDER_BOOK_ID =:OFFENDERBOOKID AND OFF_CON3.ACTIVE_FLAG = 'Y' AND OFF_CON3.INTERNAL_LOCATION_ID = AGY_INT.INTERNAL_LOCATION_ID ORDER BY  OFF_CON3.CONTAINER_CODE , OFF_CON3.PROPERTY_CONTAINER_ID ASC
select
	TO_CHAR(OFF_CON3.PROPERTY_CONTAINER_ID) CODE ,
	OFF_CON3.AGY_LOC_ID DSP_AGY_LOC_ID2 ,
	OFF_CON3.ACTIVE_FLAG DSP_ACTIVE_FLAG2 ,
	OFF_CON3.OFFENDER_BOOK_ID DSP_OFFENDER_BOOK_ID2 ,
	OFF_CON3.PROPERTY_STORAGE_ID DSP_PROPERTY_STORAGE_ID2 ,
	OFF_CON3.CONTAINER_CODE DSP_CONTAINER_CODE2 ,
	TAG_UTILS_GET_REF_DESCP('PPTY_CNTNR' ,
	OFF_CON3.CONTAINER_CODE ) CONTAINER_DESCRIPTION ,
	AGY_INT.DESCRIPTION DSP_DESCRIPTION2
from
	OFFENDER_PPTY_CONTAINERS OFF_CON3 ,
	AGENCY_INTERNAL_LOCATIONS AGY_INT
where
	OFF_CON3.AGY_LOC_ID in (
	select
		CAL.AGY_LOC_ID
	from
		CASELOAD_AGENCY_LOCATIONS CAL
	where
		CAL.CASELOAD_ID =:CASELOADID
		and CAL.AGY_LOC_ID not in ( 'OUT' , 'TRN' ) )
	and OFF_CON3.OFFENDER_BOOK_ID =:OFFENDERBOOKID
	and OFF_CON3.ACTIVE_FLAG = 'Y'
	and OFF_CON3.INTERNAL_LOCATION_ID = AGY_INT.INTERNAL_LOCATION_ID
order by
	OFF_CON3.CONTAINER_CODE ,
	OFF_CON3.PROPERTY_CONTAINER_ID asc

	}
OIDTPRIT_ITMTX_FIND_OFFENDER_PPTY_ITEM_TXNS {
 SELECT PROPERTY_ITEM_TXN_ID ,OFFENDER_BOOK_ID ,PROPERTY_ITEM_SEQ ,EVENT_SEQ ,FROM_STATUS_CODE ,TO_STATUS_CODE ,CREATE_DATE ,CREATE_USER_ID ,COMMENT_TEXT ,AGY_LOC_ID ,DISPOSED_TO_OFFENDER_FLAG ,VERIFICATION_FLAG ,VERIFY_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_PERSON ,PROPERTY_CONTAINER_ID ,PROPERTY_CONTAINER_TXN_ID ,TO_PROPERTY_CONTAINER_ID ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,CREATE_DATETIME ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_ITEM_TXNS  /* where PROPERTY_ITEM_TXN_ID = ?  */
}

OIDTPRIT_ITMTX_INSERT_OFFENDER_PPTY_ITEM_TXNS {
INSERT INTO OFFENDER_PPTY_ITEM_TXNS(PROPERTY_ITEM_TXN_ID ,OFFENDER_BOOK_ID ,PROPERTY_ITEM_SEQ ,EVENT_SEQ ,FROM_STATUS_CODE ,TO_STATUS_CODE ,CREATE_DATE ,CREATE_USER_ID ,COMMENT_TEXT ,AGY_LOC_ID ,DISPOSED_TO_OFFENDER_FLAG ,VERIFICATION_FLAG ,VERIFY_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_PERSON ,PROPERTY_CONTAINER_ID ,PROPERTY_CONTAINER_TXN_ID ,TO_PROPERTY_CONTAINER_ID ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,CREATE_DATETIME ,MODIFY_DATETIME,SEAL_FLAG ) VALUES(:propertyItemTxnId ,:offenderBookId ,:propertyItemSeq ,:eventSeq ,:fromStatusCode ,:toStatusCode ,:createDate ,:createUserId ,:commentText ,:agyLocId ,:disposedToOffenderFlag ,:verificationFlag ,:verifyFlag ,:disposedToCorpId ,:disposedToPerson ,:propertyContainerId ,:propertyContainerTxnId ,:toPropertyContainerId ,:disposedToPersonId ,:color ,:make ,:serialNo ,CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP,:sealFlag )
}

OIDTPRIT_ITMTX_UPDATE_OFFENDER_PPTY_ITEM_TXNS {
UPDATE OFFENDER_PPTY_ITEM_TXNS set OFFENDER_BOOK_ID  = :offenderBookId ,PROPERTY_ITEM_SEQ  = :propertyItemSeq ,EVENT_SEQ  = :eventSeq ,FROM_STATUS_CODE  = :fromStatusCode ,TO_STATUS_CODE  = :toStatusCode ,CREATE_DATE  = :createDate,COMMENT_TEXT  = :commentText ,AGY_LOC_ID  = :agyLocId ,DISPOSED_TO_OFFENDER_FLAG  = :disposedToOffenderFlag ,VERIFICATION_FLAG  = :verificationFlag ,VERIFY_FLAG  = :verifyFlag ,DISPOSED_TO_CORP_ID  = :disposedToCorpId ,DISPOSED_TO_PERSON  = :disposedToPerson ,PROPERTY_CONTAINER_ID  = :propertyContainerId ,PROPERTY_CONTAINER_TXN_ID  = :propertyContainerTxnId ,TO_PROPERTY_CONTAINER_ID  = :toPropertyContainerId ,DISPOSED_TO_PERSON_ID  = :disposedToPersonId ,COLOR  = :color ,MAKE  = :make ,SERIAL_NO  = :serialNo ,CREATE_DATETIME  = :createDatetime ,MODIFY_DATETIME  =CURRENT_TIMESTAMP,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag where PROPERTY_ITEM_TXN_ID  = :propertyItemTxnId /* where PROPERTY_ITEM_TXN_ID = ? */
}

	OIDTPRIT_ITMTX_DELETE_OFFENDER_PPTY_ITEM_TXNS { 
DELETE FROM OFFENDER_PPTY_ITEM_TXNS where PROPERTY_ITEM_TXN_ID = :propertyItemTxnId
}

OIDTPRIT_OFFPI_FIND_OFFENDER_PPTY_ITEMS {
-- SELECT PROPERTY_ITEM_SEQ ,OFFENDER_BOOK_ID ,PROPERTY_TYPE ,PROPERTY_DESCRIPTION ,AGY_LOC_ID ,STATUS_CODE ,CONDITION_CODE ,RECEIVED_FROM ,PROPERTY_CONTAINER_ID ,COMMENT_TEXT ,CONFIRM_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_OFFENDER_FLAG ,DISPOSED_TO_PERSON ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,QUANTITY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_ITEMS
 SELECT PROPERTY_ITEM_SEQ ,OFFENDER_BOOK_ID ,PROPERTY_TYPE ,PROPERTY_DESCRIPTION ,AGY_LOC_ID ,STATUS_CODE ,CONDITION_CODE ,RECEIVED_FROM ,PROPERTY_CONTAINER_ID ,COMMENT_TEXT ,CONFIRM_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_OFFENDER_FLAG ,DISPOSED_TO_PERSON ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,QUANTITY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_ITEMS
where OFFENDER_BOOK_ID = :OFFENDERBOOKID AND  STATUS_CODE=:STATUSCODE  AND AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID
                                  FROM CASELOAD_AGENCY_LOCATIONS CAL
                                 WHERE CAL.CASELOAD_ID = :CASELOADID
                                   AND CAL.AGY_LOC_ID NOT IN ( 'OUT', 'TRN' ))   
}

OIDTPRIT_OFFPI_OFFENDER_PPTY_ITEMS {
 SELECT PROPERTY_ITEM_SEQ ,OFFENDER_BOOK_ID ,PROPERTY_TYPE ,PROPERTY_DESCRIPTION ,AGY_LOC_ID ,STATUS_CODE ,CONDITION_CODE ,RECEIVED_FROM ,PROPERTY_CONTAINER_ID ,COMMENT_TEXT ,CONFIRM_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_OFFENDER_FLAG ,DISPOSED_TO_PERSON ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE, PROPERTY_SIZE, PROPERTY_VALUE ,SERIAL_NO ,QUANTITY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_ITEMS
where (offender_book_id = :OFFENDERBOOKID AND (agy_loc_id IN (SELECT agy_loc_id FROM caseload_agency_locations WHERE agy_loc_id NOT IN ( 'OUT', 'TRN' ) and caseload_id = :CASELOADID ) OR (status_code IN ('OUT') AND agy_loc_id IN ('OUT', 'TRN'))   ) AND status_code = :STATUSCODE AND (:PROPERTYCONATINERID IS NULL OR   property_container_id = :PROPERTYCONATINERID))
}

OIDTPRIT_OFFPI_UPDATE_OFFENDER_PPTY_ITEMS {
UPDATE OFFENDER_PPTY_ITEMS set PROPERTY_TYPE  = :propertyType ,PROPERTY_DESCRIPTION  = :propertyDescription ,AGY_LOC_ID  = :agyLocId ,STATUS_CODE  = :statusCode ,CONDITION_CODE  = :conditionCode ,RECEIVED_FROM  = :receivedFrom ,PROPERTY_CONTAINER_ID  = :propertyContainerId ,COMMENT_TEXT  = :commentText ,CONFIRM_FLAG  = :confirmFlag ,DISPOSED_TO_CORP_ID  = :disposedToCorpId ,DISPOSED_TO_OFFENDER_FLAG  = :disposedToOffenderFlag ,DISPOSED_TO_PERSON  = :disposedToPerson ,DISPOSED_TO_PERSON_ID  = :disposedToPersonId ,COLOR  = :color ,MAKE  = :make ,SERIAL_NO  = :serialNo ,QUANTITY  = :quantity,MODIFY_DATETIME  =CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag where OFFENDER_BOOK_ID  = :offenderBookId and PROPERTY_ITEM_SEQ  = :propertyItemSeq 
}

OIDTPRIT_SYSPFL_FIND_SYSTEM_PROFILES {
 SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  where PROFILE_TYPE = :profileType and PROFILE_CODE = :profileCode 
}


	OIDTPRIT_V_PHEAD_ONCHECKDELETEMASTER_ITM_TX_CUR {
 SELECT 1 FROM OFFENDER_PPTY_ITEM_TXNS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

	OIDTPRIT_ITM_TX_WHENVALIDATERECORD_REG_ITEMS {
 SELECT SEAL_MARK FROM OFFENDER_PPTY_CONTAINERS WHERE PROPERTY_CONTAINER_ID = :PROPERTYCONTAINERID AND AGY_LOC_ID = :DSPAGYLOCID2
}

	OIDTPRIT_ITM_TX_WHENVALIDATERECORD_REG_ITEMS1 {
 SELECT SEAL_MARK FROM OFFENDER_PPTY_CONTAINERS WHERE PROPERTY_CONTAINER_ID = :PROPERTYCONTAINERID AND AGY_LOC_ID IN
(SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :AGYLOCID)
}

	OIDTPRIT_OFF_PI_POSTQUERY_C_PROPERTY_TYPE_DESC {
 SELECT DESCRIPTION FROM REFERENCE_CODES REF_CODE3 WHERE DOMAIN = 'PPTY_TYPE' AND CODE = :CODE
}

	OIDTPRIT_CGFKCHK_ITM_TX_ITM_TX_OFF_CON_C {
 SELECT OFF_CON2.AGY_LOC_ID ,OFF_CON2.OFFENDER_BOOK_ID ,OFF_CON2.ACTIVE_FLAG ,OFF_CON2.PROPERTY_STORAGE_ID ,OFF_CON2.CONTAINER_CODE --            ,PPTY_STG6.DESCRIPTION FROM   OFFENDER_PPTY_CONTAINERS OFF_CON2 ,PROPERTY_STORAGES PPTY_STG6 WHERE  OFF_CON2.PROPERTY_CONTAINER_ID = TOPROPERTYCONTAINERID AND     (OFF_CON2.AGY_LOC_ID = PPTYAGYLOCID AND OFF_CON2.OFFENDER_BOOK_ID = OFFENDERBOOKID AND OFF_CON2.ACTIVE_FLAG = 'Y') AND    PPTY_STG6.PROPERTY_STORAGE_ID = OFF_CON2.PROPERTY_STORAGE_ID
}

	OIDTPRIT_CGFKCHK_ITM_TX_ITM_TX_OFF_2_C {
 SELECT OFF_CON3.AGY_LOC_ID ,OFF_CON3.ACTIVE_FLAG ,OFF_CON3.OFFENDER_BOOK_ID ,OFF_CON3.PROPERTY_STORAGE_ID ,OFF_CON3.CONTAINER_CODE --            ,PPTY_STG3.DESCRIPTION FROM   OFFENDER_PPTY_CONTAINERS OFF_CON3 ,PROPERTY_STORAGES PPTY_STG3 WHERE  OFF_CON3.PROPERTY_CONTAINER_ID = PROPERTYCONTAINERID AND     (OFF_CON3.AGY_LOC_ID = PPTYAGYLOCID AND OFF_CON3.OFFENDER_BOOK_ID = OFFENDERBOOKID AND OFF_CON3.ACTIVE_FLAG = 'Y') AND    PPTY_STG3.PROPERTY_STORAGE_ID = OFF_CON3.PROPERTY_STORAGE_ID
}

	OIDTPRIT_CGFKCHK_ITM_TX_ITM_TX_ITM_TS__C {
 SELECT ITM_STS.LIST_SEQ FROM   ITEM_TRANSACTION_STATII ITM_STS WHERE  ITM_STS.ITEM_STATUS_TO = TOSTATUSCODE AND     FROMSTATUSCODE IS NOT NULL AND ITEM_STATUS_FROM = FROMSTATUSCODE AND ITEM_STATUS_FROM != 'TRANSIT' AND ITM_STS.ITEM_STATUS_TO != 'DISPOSED'
}

	OIDTPRIT_CGFKCHK_ITM_TX_ITM_TX_REF_COD_C {
 SELECT REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :FROMSTATUSCODE AND     (DOMAIN = 'PPTY_ITM_STS' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR   (:MODE = 'QUERY')) AND REF_CODE.CODE != 'TRANSIT' AND REF_CODE.CODE IN (SELECT DISTINCT ITEM_STATUS_FROM FROM ITEM_TRANSACTION_STATII WHERE ITEM_STATUS_TO != 'DISPOSED'))
}

	OIDTPRIT_CGFKCHK_OFF_PI_OFF_PI_OFF_CON_C {
 SELECT OFF_CON4.PROPERTY_STORAGE_ID ,PPTY_STG7.DESCRIPTION FROM   OFFENDER_PPTY_CONTAINERS OFF_CON4 ,PROPERTY_STORAGES PPTY_STG7 WHERE  OFF_CON4.PROPERTY_CONTAINER_ID = PROPERTYCONTAINERID AND    PPTY_STG7.PROPERTY_STORAGE_ID = OFF_CON4.PROPERTY_STORAGE_ID
}

	OIDTPRIT_PRINT_REPORT_OLD_GET_PRINT_FORMAT_CUR {
 SELECT PRINT_FORMAT_CODE FROM OMS_MODULES WHERE MODULE_NAME = :NAME
}

	OIDTPRIT_PRINT_REPORT_OLD_GET_PRINTER_NAME_CUR {
 SELECT PRTS.DESCRIPTION FROM CASELOAD_FORMAT_PRINTERS CFP, PRINTERS PRTS WHERE PRTS.PRINTER_ID = CFP.DEFAULT_PRINTER_ID AND CFP.CASELOAD_ID = :CASELOADID AND (CFP.PRINT_FORMAT_CODE = :PRINTFORMATCODE OR :CASELOADID IS NULL)
}

	OIDTPRIT_RUN_REPORT_ON_THE_WEB_002_ROLE_CUR {
 SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'ROLE_BASE'
}

	OIDTPRIT_RUN_REPORT_ON_THE_WEB_002_GET_PRINT_FORMAT_CUR {
 --SELECT DECODE(PRINT_FORMAT_CODE, 'LAN', 'LANDSCAPE', 'PORTRAIT') FROM OMS_MODULES WHERE MODULE_NAME = :RNAME
 
 SELECT CASE PRINT_FORMAT_CODE  WHEN 'LAN' THEN  'LANDSCAPE'  ELSE 'PORTRAIT' END FROM OMS_MODULES WHERE MODULE_NAME = :RNAME

}

	OIDTPRIT_PRINT_REPORT_GET_PRINT_FORMAT_CUR {
 SELECT PRINT_FORMAT_CODE FROM OMS_MODULES WHERE MODULE_NAME = 'OIRPTRAN'
}

	OIDTPRIT_PRINT_REPORT_GET_PRINTER_NAME_CUR {
 SELECT PRTS.DESCRIPTION FROM CASELOAD_FORMAT_PRINTERS CFP, PRINTERS PRTS WHERE PRTS.PRINTER_ID = CFP.DEFAULT_PRINTER_ID AND CFP.CASELOAD_ID = :CASELOADID AND (CFP.PRINT_FORMAT_CODE = :PRINTFORMATCODE OR :CASELOADID IS NULL)
}

	OIDTPRIT_PRINT_REPORT_ROLE_CUR {
 SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'ROLE_BASE'
}

	OIDTPRIT_PRINT_REPORT_ROLE_PWD {
 SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'SYS' AND PROFILE_CODE = 'ROLE_PSWD'
}

	OIDTPRIT_PRINT_REPORT_L_REPORT_ALIAS {
 SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'REPORT_ALIAS'
}

	OIDTPRIT_PRINT_REPORT_L_SYSTEM_PROFILES_DESC_CUR  {
 SELECT LTRIM(RTRIM(DESCRIPTION)) FROM SYSTEM_PROFILES WHERE PROFILE_CODE = :P_PROFILE_CODE AND PROFILE_TYPE = :P_PROFILE_TYPE
}
OIDTPRIT_PRINT_REPORT {
--SELECT OFF_CON1.PROPERTY_CONTAINER_ID  PROPERTY_CONTAINER_ID          ,OFF_CON1.OFFENDER_BOOK_ID  DSP_OFFENDER_BOOK_ID        ,OFF_CON1.AGY_LOC_ID  DSP_AGY_LOC_ID        ,OFF_CON1.PROPERTY_STORAGE_ID  DSP_PROPERTY_STORAGE_ID        ,AGY_INT.DESCRIPTION DSP_DESCRIPTION        ,OFF_CON1.CONTAINER_CODE        ,TAG_UTILS.GET_REF_DESCP('PPTY_CNTNR' ,OFF_CON1.CONTAINER_CODE ) CONTAINER_DESC FROM   OFFENDER_PPTY_CONTAINERS OFF_CON1 ,        AGENCY_INTERNAL_LOCATIONS AGY_INT WHERE   OFF_CON1.AGY_LOC_ID IN (SELECT AGY_LOC_ID                                  FROM CASELOAD_AGENCY_LOCATIONS                                 WHERE CASELOAD_ID = :CASELOADID                                    AND AGY_LOC_ID NOT IN ( 'OUT' , 'TRN'  ) )  AND OFF_CON1.OFFENDER_BOOK_ID = :OFFENDERBOOKID AND OFF_CON1.ACTIVE_FLAG = 'Y' AND OFF_CON1.INTERNAL_LOCATION_ID = AGY_INT.INTERNAL_LOCATION_ID ORDER BY OFF_CON1.CONTAINER_CODE , OFF_CON1.PROPERTY_CONTAINER_ID ASC
select
	OFF_CON1.PROPERTY_CONTAINER_ID PROPERTY_CONTAINER_ID ,
	OFF_CON1.OFFENDER_BOOK_ID DSP_OFFENDER_BOOK_ID ,
	OFF_CON1.AGY_LOC_ID DSP_AGY_LOC_ID ,
	OFF_CON1.PROPERTY_STORAGE_ID DSP_PROPERTY_STORAGE_ID ,
	AGY_INT.DESCRIPTION DSP_DESCRIPTION ,
	OFF_CON1.CONTAINER_CODE ,
	TAG_UTILS_GET_REF_DESCP('PPTY_CNTNR' ,
	OFF_CON1.CONTAINER_CODE ) CONTAINER_DESC
from
	OFFENDER_PPTY_CONTAINERS OFF_CON1 ,
	AGENCY_INTERNAL_LOCATIONS AGY_INT
where
	OFF_CON1.AGY_LOC_ID in (
	select
		AGY_LOC_ID
	from
		CASELOAD_AGENCY_LOCATIONS
	where
		CASELOAD_ID = :CASELOADID
		and AGY_LOC_ID not in ( 'OUT' , 'TRN' ) )
	and OFF_CON1.OFFENDER_BOOK_ID = :OFFENDERBOOKID
	and OFF_CON1.ACTIVE_FLAG = 'Y'
	and OFF_CON1.INTERNAL_LOCATION_ID = AGY_INT.INTERNAL_LOCATION_ID
order by
	OFF_CON1.CONTAINER_CODE ,
	OFF_CON1.PROPERTY_CONTAINER_ID asc

}

OIDTPRIT_ITM_TX_POSTQUERY {
	SELECT DESCRIPTION FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_COLOR' AND    UPPER(CODE)   = UPPER(:color)
}

OIDTPRIT_ITM_TX_CONDITION_POSTQUERY {
	SELECT DESCRIPTION FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_CONDIT' AND    UPPER(CODE) = UPPER(:conditionCode)
}

OIDTPRIT_PRINT_PROPERTY_TYPE_DESCRIPTION {
SELECT DESCRIPTION FROM   REFERENCE_CODES WHERE   domain='PPTY_TYPE' AND CODE  = :propertyType
}

OIDTPRIT_ITM_TX_POSTQUERY_CODE {
	SELECT CODE FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_COLOR' AND    DESCRIPTION   = :color
}

OIDTPRIT_ITM_TX_CONDITION_POSTQUERY_CODE {
	SELECT CODE FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_CONDIT' AND    UPPER(DESCRIPTION) = UPPER(:conditionCode)
}

OIDTPRIT_PRINT_PROPERTY_TYPE_DESCRIPTION_CODE {
SELECT CODE FROM   REFERENCE_CODES WHERE   domain='PPTY_TYPE' AND CODE  = :propertyType
}
OIDTPRIT_OFFPI_UPDATE_OFFENDER_PPTY_ITEMS_OLD_DATA{
SELECT * FROM OFFENDER_PPTY_ITEMS WHERE PROPERTY_ITEM_SEQ=:PRIORITY_SEQ AND OFFENDER_BOOK_ID =:OFFENDER_BOOK_ID
}
