
OIDVCONT_FIND_CGFKCONTXACTIONCODE {
--   SELECT REF_CODE1.CODE  CODE ,REF_CODE1.DESCRIPTION  DESCRIPTION FROM REFERENCE_CODES REF_CODE1 WHERE (DOMAIN = 'PPTY_VER' AND REF_CODE1.CODE != DECODE((SELECT SEAL_MARK from OFFENDER_PPTY_CONTAINERS where PROPERTY_CONTAINER_ID = :PROPERTYCONTAINERID) , NULL , 'VS' , 'X' ) AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR ( '' = 'QUERY'  ) ) )
select case when ((REF_CODE1.CODE = 'VS') and coalesce (( select SEAL_MARK from oms_owner.OFFENDER_PPTY_CONTAINERS where PROPERTY_CONTAINER_ID = 1574), '')= '') 
	then 0 else 1 end SEQVALUE , REF_CODE1.CODE CODE , REF_CODE1.DESCRIPTION DESCRIPTION, REF_CODE1.ACTIVE_FLAG from oms_owner.REFERENCE_CODES REF_CODE1
	where domain = 'PPTY_VER' or ( '' = 'QUERY' )
}

OIDVCONT_OFFCON_FIND_OFFENDER_PPTY_CONTAINERS {
 	select
OPC.PROPERTY_ONLY_FLAG ,OPC.PROPERTY_CONTAINER_ID ,OPC.OFFENDER_BOOK_ID ,OPC.AGY_LOC_ID ,OPC.ACTIVE_FLAG ,OPC.PROPOSED_DISPOSAL_DATE ,OPC.COMMENT_TEXT ,OPC.INTERNAL_LOCATION_ID ,OPC.CONTAINER_CODE ,OPC.EXPIRY_DATE ,OPC.SEAL_MARK ,OPC.TRN_FROM_AGY_LOC_ID ,OPC.TRN_TO_AGY_LOC_ID ,OPC.CREATE_DATETIME ,OPC.CREATE_USER_ID ,OPC.MODIFY_DATETIME ,OPC.MODIFY_USER_ID ,OPC.PROPERTY_STORAGE_ID ,OPC.DISPOSED_TO ,OPC.DISPOSED_TO_NAME ,OPC.SEAL_FLAG
from
OFFENDER_PPTY_CONTAINERS OPC,
(select A.* from offender_ppty_items A,(select max(property_item_seq) max_prp_itm_seq,property_container_id from offender_ppty_items group by property_container_id)B
where A.property_item_seq=B.max_prp_itm_seq and A.property_container_id=B.property_container_id) OPI
where
OPC.OFFENDER_BOOK_ID = :offenderBookId
and OPC.AGY_LOC_ID not in ('OUT')
and OPC.ACTIVE_FLAG = 'Y'
and OPC.property_container_id = OPI.property_container_id
and
OPC.AGY_LOC_ID in(
select
AGY_LOC_ID
from
CASELOAD_AGENCY_LOCATIONS
where
CASELOAD_ID = :agyLocId)
order by
PROPERTY_CONTAINER_ID
 	
 }
OIDVCONT_CONTX_FIND_OFFENDER_PPTY_CON_TXNS {
 	SELECT PROPERTY_CONTAINER_TXN_ID ,PROPERTY_CONTAINER_ID ,CREATE_DATE ,CREATE_USER_ID ,AGY_LOC_ID ,ACTION_CODE ,COMMENT_TEXT ,SEAL_MARK ,INTERNAL_LOCATION_ID ,TRN_TO_AGY_LOC_ID ,TRN_FROM_AGY_LOC_ID ,CREATE_DATETIME ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_CON_TXNS
}
OIDVCONT_CONTX_INSERT_OFFENDER_PPTY_CON_TXNS {
	insert into OFFENDER_PPTY_CON_TXNS(PROPERTY_CONTAINER_TXN_ID , PROPERTY_CONTAINER_ID , CREATE_DATE , CREATE_USER_ID , AGY_LOC_ID , ACTION_CODE , COMMENT_TEXT , SEAL_MARK , INTERNAL_LOCATION_ID , TRN_TO_AGY_LOC_ID , TRN_FROM_AGY_LOC_ID , CREATE_DATETIME , MODIFY_DATETIME, SEAL_FLAG ) values(:propertyContainerTxnId , :propertyContainerId , :createDate , :createUserId , :agyLocId , :actionCode , :commentText , :sealMark , :internalLocationId , :trnToAgyLocId , :trnFromAgyLocId , current_timestamp , null , :sealFlag )
}

OIDVCONT_ITMTX_FIND_OFFENDER_PPTY_ITEM_TXNS {
 	SELECT PROPERTY_ITEM_TXN_ID ,OFFENDER_BOOK_ID ,PROPERTY_ITEM_SEQ ,EVENT_SEQ ,FROM_STATUS_CODE ,TO_STATUS_CODE ,CREATE_DATE ,CREATE_USER_ID ,COMMENT_TEXT ,AGY_LOC_ID ,DISPOSED_TO_OFFENDER_FLAG ,VERIFICATION_FLAG ,VERIFY_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_PERSON ,PROPERTY_CONTAINER_ID ,PROPERTY_CONTAINER_TXN_ID ,TO_PROPERTY_CONTAINER_ID ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,CREATE_DATETIME ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_ITEM_TXNS
}
OIDVCONT_ITMTX_INSERT_OFFENDER_PPTY_ITEM_TXNS {
	INSERT INTO OFFENDER_PPTY_ITEM_TXNS(PROPERTY_ITEM_TXN_ID ,OFFENDER_BOOK_ID ,PROPERTY_ITEM_SEQ ,EVENT_SEQ ,FROM_STATUS_CODE ,TO_STATUS_CODE ,CREATE_DATE ,CREATE_USER_ID ,COMMENT_TEXT ,AGY_LOC_ID ,DISPOSED_TO_OFFENDER_FLAG ,VERIFICATION_FLAG ,VERIFY_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_PERSON ,PROPERTY_CONTAINER_ID ,PROPERTY_CONTAINER_TXN_ID ,TO_PROPERTY_CONTAINER_ID ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,CREATE_DATETIME ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(nextval('PROPERTY_ITEM_TXN_ID') ,:offenderBookId ,:propertyItemSeq ,:eventSeq ,:fromStatusCode ,:toStatusCode ,:createDate ,:createUserId ,:commentText ,:agyLocId ,:disposedToOffenderFlag ,:verificationFlag ,:verifyFlag ,:disposedToCorpId ,:disposedToPerson ,:propertyContainerId ,:propertyContainerTxnId ,:toPropertyContainerId ,:disposedToPersonId ,:color ,:make ,:serialNo ,current_timestamp ,current_timestamp,:sealFlag )
}

OIDVCONT_ITMTX_UPDATE_OFFENDER_PPTY_ITEM_TXNS {
	UPDATE OFFENDER_PPTY_ITEM_TXNS set PROPERTY_ITEM_TXN_ID  = :propertyItemTxnId ,OFFENDER_BOOK_ID  = :offenderBookId ,PROPERTY_ITEM_SEQ  = :propertyItemSeq ,EVENT_SEQ  = :eventSeq ,FROM_STATUS_CODE  = :fromStatusCode ,TO_STATUS_CODE  = :toStatusCode ,CREATE_DATE  = :createDate ,COMMENT_TEXT  = :commentText ,AGY_LOC_ID  = :agyLocId ,DISPOSED_TO_OFFENDER_FLAG  = :disposedToOffenderFlag ,VERIFICATION_FLAG  = :verificationFlag ,VERIFY_FLAG  = :verifyFlag ,DISPOSED_TO_CORP_ID  = :disposedToCorpId ,DISPOSED_TO_PERSON  = :disposedToPerson ,PROPERTY_CONTAINER_ID  = :propertyContainerId ,PROPERTY_CONTAINER_TXN_ID  = :propertyContainerTxnId ,TO_PROPERTY_CONTAINER_ID  = :toPropertyContainerId ,DISPOSED_TO_PERSON_ID  = :disposedToPersonId ,COLOR  = :color ,MAKE  = :make ,SERIAL_NO  = :serialNo,MODIFY_DATETIME  =current_timestamp ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag  /*where PROPERTY_CONTAINER_TXN_ID = :propertyContainerTxnId*/
}

OIDRPITM_OFFPI_FIND_OFFENDER_PPTY_ITEMS {
 	SELECT PROPERTY_ITEM_SEQ ,OFFENDER_BOOK_ID ,PROPERTY_TYPE ,PROPERTY_DESCRIPTION ,AGY_LOC_ID ,STATUS_CODE ,CONDITION_CODE ,RECEIVED_FROM ,PROPERTY_CONTAINER_ID ,COMMENT_TEXT ,CONFIRM_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_OFFENDER_FLAG ,DISPOSED_TO_PERSON ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,QUANTITY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG FROM OFFENDER_PPTY_ITEMS  WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND PROPERTY_ITEM_SEQ =:propertyItemSeq
}

OIDVCONT_V_PHEAD_ONCHECKDELETEMASTER {
	SELECT 1 FROM OFFENDER_PPTY_CONTAINERS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIDVCONT_ITM_TX_POSTQUERY {
	SELECT DESCRIPTION FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_COLOR' AND    CODE   = :COLOR
}

OIDVCONT_ITM_TX_POSTQUERY_COLOR {
   SELECT CODE FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_COLOR' AND    DESCRIPTION   = :COLOR
}

OIDVCONT_ITM_TX_CONDITION_POSTQUERY {
	SELECT DESCRIPTION FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_CONDIT' AND    CODE = :DSPCONDITIONCODE
}

OIDVCONT_CGFKCHK_OFF_CON_OFF_CON_PPTY {
	SELECT DESCRIPTION FROM   AGENCY_INTERNAL_LOCATIONS WHERE INTERNAL_LOCATION_ID = :INTERNALLOCATIONID
}

OIDVCONT_CGFKCHK_OFF_CON_OFF_CON_REF_C {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :CONTAINERCODE AND     (DOMAIN = 'PPTY_CNTNR' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR ( '' = 'QUERY' )))
}

OIDVCONT_CGFKCHK_CON_TX_CON_TXN_REF_CO_ {
--SELECT REF_CODE1.DESCRIPTION FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :ACTIONCODE AND     (DOMAIN = 'PPTY_VER' AND REF_CODE1.CODE != DECODE(:SEALMARK, NULL, 'VS', 'X') AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR ( :MODE = 'QUERY' )))
	SELECT REF_CODE1.DESCRIPTION FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :ACTIONCODE AND     (DOMAIN = 'PPTY_VER' AND REF_CODE1.CODE != CASE   WHEN :SEALMARK IS NULL THEN  'VS'  ELSE 'X' END AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL) OR ( :MODE = 'QUERY' )))

}

OIDVCONT_CGFKCHK_ITM_TX_ITM_TX_OFF_PI__ {
	SELECT OFF_PI.PROPERTY_TYPE ,OFF_PI.PROPERTY_DESCRIPTION ,OFF_PI.CONDITION_CODE ,OFF_PI.QUANTITY FROM   OFFENDER_PPTY_ITEMS OFF_PI WHERE  OFF_PI.OFFENDER_BOOK_ID = :OFFENDERBOOKID AND    (OFF_PI.PROPERTY_ITEM_SEQ = :PROPERTYITEMSEQ OR (OFF_PI.PROPERTY_ITEM_SEQ IS NULL AND :PROPERTYITEMSEQ IS NULL ))
}

OIDVCONT_CGFKCHK_ITM_TX_ITM_TX_OFF_PI__ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'PPTY_TYPE' AND CODE   = :DSPPROPERTYTYPE
}

OIDVCONT_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OIDVCONT_PROPERTY_CONTAINER_TXN_ID {
--SELECT NVL(MAX(PROPERTY_CONTAINER_TXN_ID), 0) + 1 FROM  OFFENDER_PPTY_CON_TXNS
SELECT NEXTVAL('PROPERTY_CONTAINER_TXN_ID') FROM DUAL
}

OIDRPITM_OFFPI_GET_OFFENDER_PPTY_ITEMS {
 	SELECT PROPERTY_ITEM_SEQ ,OFFENDER_BOOK_ID ,PROPERTY_TYPE ,PROPERTY_DESCRIPTION ,AGY_LOC_ID ,STATUS_CODE ,CONDITION_CODE ,RECEIVED_FROM ,PROPERTY_CONTAINER_ID ,COMMENT_TEXT ,CONFIRM_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_OFFENDER_FLAG ,DISPOSED_TO_PERSON ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE ,SERIAL_NO ,QUANTITY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG FROM OFFENDER_PPTY_ITEMS  WHERE STATUS_CODE != 'DISPOSED' AND PROPERTY_CONTAINER_ID = :propertyContainerId order by PROPERTY_ITEM_SEQ
}

OIDVCONT_PROPERTY_ITEM_TXN_ID {
--SELECT NVL(MAX(PROPERTY_ITEM_TXN_ID), 0) + 1 FROM  OFFENDER_PPTY_ITEM_TXNS
SELECT NEXTVAL('PROPERTY_ITEM_TXN_ID') FROM DUAL
}

OIDVCONT_PRINT_PROPERTY_TYPE_DESCRIPTION {
SELECT  REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   domain='PPTY_TYPE' AND REF_CODE.CODE  = :propertyType and active_flag='Y' and expired_date is null ORDER BY REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION
}

OIDVCONT_UPDATE_OFFENDER_PPTY_CONTAINERS {
UPDATE OFFENDER_PPTY_CONTAINERS SET SEAL_MARK = NULL, modify_user_id =:modifyUserId, modify_datetime = current_timestamp  WHERE  PROPERTY_CONTAINER_ID = :propertyContainerId
}

 OIDVCONT_GET_USER_NAME{
 select last_name || ',' || ' '  || first_name  from staff_members sm  where user_id =:userId
 }
