
OIIPTRAN_OFFPI_FIND_OFFENDER_PPTY_ITEMS {
 	SELECT PROPERTY_ITEM_SEQ ,OFFENDER_BOOK_ID ,PROPERTY_TYPE ,PROPERTY_DESCRIPTION ,AGY_LOC_ID ,STATUS_CODE ,CONDITION_CODE ,RECEIVED_FROM ,PROPERTY_CONTAINER_ID ,COMMENT_TEXT ,CONFIRM_FLAG ,DISPOSED_TO_CORP_ID ,DISPOSED_TO_OFFENDER_FLAG ,DISPOSED_TO_PERSON ,DISPOSED_TO_PERSON_ID ,COLOR ,MAKE, PROPERTY_SIZE, PROPERTY_VALUE ,SERIAL_NO ,QUANTITY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PPTY_ITEMS
}
OIIPTRAN_ITMTX_FIND_OFFENDER_PPTY_ITEM_TXNS {
 	select
	PROPERTY_ITEM_TXN_ID,
	OFFENDER_BOOK_ID,
	PROPERTY_ITEM_SEQ,
	EVENT_SEQ,
	FROM_STATUS_CODE,
	TO_STATUS_CODE,
	CREATE_DATE,
	CREATE_USER_ID,
	COMMENT_TEXT,
	AGY_LOC_ID,
	DISPOSED_TO_OFFENDER_FLAG,
	VERIFICATION_FLAG,
	VERIFY_FLAG,
	DISPOSED_TO_CORP_ID,
	DISPOSED_TO_PERSON,
	PROPERTY_CONTAINER_ID,
	PROPERTY_CONTAINER_TXN_ID,
	TO_PROPERTY_CONTAINER_ID,
	DISPOSED_TO_PERSON_ID,
	COLOR,
	MAKE,
	SERIAL_NO,
	CREATE_DATETIME,
	MODIFY_DATETIME,
	MODIFY_USER_ID,
	SEAL_FLAG,
	CORP.description as DISPOSED_TO_CORP_NAME,
	ACTION_CODE,
	ACTION_REASON
from
	OFFENDER_PPTY_ITEM_TXNS OFF_PITO
left outer join (
	select
		TO_CHAR(v.CORPORATE_ID) code,
		v.CORPORATE_NAME description
	from
		CORPORATE_TYPES CT
	inner join CORPORATES v on
		v.corporate_id = CT.corporate_id
	where
		ct.corporate_type = 'DISP')CORP on
	OFF_PITO.DISPOSED_TO_CORP_ID::text = CORP.CODE
}

OIIPTRAN_V_PHEAD_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM OFFENDER_PPTY_ITEMS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIIPTRAN_CGFKCHK_ITM_TX_ITM_TX_CORP_F1_ {
	SELECT CORPORATE_NAME FROM   CORPORATE_ADDRESS_V WHERE  CORPORATE_ID = :DISPOSEDTOCORPID
}

OIIPTRAN_CGFKCHK_OFF_PI_OFF_PI_OFF_CON {
	SELECT OPC.INTERNAL_LOCATION_ID FROM OFFENDER_PPTY_CONTAINERS OPC, OFFENDER_PPTY_ITEMS OPI WHERE OPI.OFFENDER_BOOK_ID = OPC.OFFENDER_BOOK_ID AND   OPC.PROPERTY_CONTAINER_ID = OPI.PROPERTY_CONTAINER_ID AND   OPI.OFFENDER_BOOK_ID = :OFFENDERBOOKID AND   OPI.PROPERTY_CONTAINER_ID = :PROPERTYCONTAINERID AND   OPI.PROPERTY_ITEM_SEQ = :PROPERTYITEMSEQ
}

OIIPTRAN_PRINT_TO_STATUS_DESCRIPTION {
SELECT  REF_CODE.DESCRIPTION FROM REFERENCE_CODES REF_CODE WHERE   domain='PPTY_ITM_STS' AND REF_CODE.CODE  = :toStatusCode and active_flag='Y' and expired_date is null ORDER BY REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION
}

OIIPTRAN_PRINT_RECEIVED_FORM_DESCRIPTION {
SELECT  REF_CODE.DESCRIPTION FROM REFERENCE_CODES REF_CODE WHERE   domain='PPTY_REC_FRM' AND REF_CODE.CODE  = :receivedFrom and active_flag='Y' and expired_date is null ORDER BY REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION
}

OIIPTRAN_PRINT_PROPERTY_TYPE_DESCRIPTION {
SELECT  REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   domain='PPTY_TYPE' AND REF_CODE.CODE  = :propertyType and active_flag='Y' and expired_date is null ORDER BY REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION
}

OIIPTRAN_PRINT_COLOR_DESCRIPTION {
SELECT  REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   domain='PPTY_COLOR' AND REF_CODE.CODE  = :color and active_flag='Y' and expired_date is null ORDER BY REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION
}

OIIPTRAN_PRINT_CONDITION_CODE_DESCRIPTION {
SELECT  REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   domain='PPTY_CONDIT' AND REF_CODE.CODE  = :conditionCode and active_flag='Y' and expired_date is null ORDER BY REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION
}

OIIPTRAN_PRINT_AGY_LOC_ID_DESCRIPTION {
SELECT DESCRIPTION FROM AGENCY_LOCATIONS WHERE AGY_LOC_ID = :agyLocId
}

OIIPTRAN_CGFKCHK_OFF_CON_OFF_CON_PPTY {
	SELECT DESCRIPTION FROM   AGENCY_INTERNAL_LOCATIONS WHERE INTERNAL_LOCATION_ID = :INTERNALLOCATIONID
}

OIIPTRAN_PPTY_REC_FRM_LIST {
SELECT DESCRIPTION   FROM   REFERENCE_CODES WHERE   DOMAIN='PPTY_REC_FRM' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL ORDER BY  LIST_SEQ ,DESCRIPTION
}

OIIPTRAN_PPTY_TYPE_LIST {
SELECT DESCRIPTION   FROM   REFERENCE_CODES WHERE   DOMAIN = 'PPTY_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  LIST_SEQ ,DESCRIPTION
}

OIIPTRAN_PPTY_COLOR_LIST {
SELECT DESCRIPTION FROM   REFERENCE_CODES WHERE  DOMAIN = 'PPTY_COLOR' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OIIPTRAN_PPTY_CONDIT_LIST {
SELECT DESCRIPTION FROM REFERENCE_CODES  WHERE DOMAIN = 'PPTY_CONDIT'  AND ( (ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR 'ENTER-QUERY'= 'ENTER-QUERY'  ) ORDER BY LIST_SEQ
}

OIIPTRAN_FACILITY_LIST {
SELECT  DISTINCT AGY_LOC.DESCRIPTION FROM AGENCY_LOCATIONS AGY_LOC, CASELOAD_AGENCY_LOCATIONS CAL
}

OIIPTRAN_AGY_LOCATION_LIST {
SELECT C.DESCRIPTION FROM INT_LOC_USAGE_LOCATIONS A ,        INTERNAL_LOCATION_USAGES B ,        AGENCY_INTERNAL_LOCATIONS C
WHERE A.INTERNAL_LOCATION_USAGE_ID = B.INTERNAL_LOCATION_USAGE_ID    AND B.INTERNAL_LOCATION_USAGE = 'PROP'
 AND B.AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID  FROM CASELOAD_AGENCY_LOCATIONS CAL WHERE CAL.CASELOAD_ID = :caseLoadId
 AND CAL.AGY_LOC_ID NOT IN ( 'OUT' , 'TRN'  ) )     AND A.INTERNAL_LOCATION_ID = C.INTERNAL_LOCATION_ID
AND ((C.ACTIVE_FLAG = 'Y'    AND C.DEACTIVATE_DATE IS NULL )
 OR ('' = 'ENTER-QUERY' ) )   ORDER BY  C.AGY_LOC_ID ,A.LIST_SEQ  ,C.DESCRIPTION
 }
 OIIPTRAN_IMAGES {
 SELECT * FROM IMAGES  WHERE IMAGE_OBJECT_ID =:offenderBookId and  IMAGE_OBJECT_TYPE =:imageObjectType 
 }
 OIIPTRAN_GET_IMAGE_FLAG{
   SELECT 'Y'
       FROM images
      WHERE image_object_id = :offenderBookId
        AND image_object_seq = :pptySeq
        AND image_object_type = 'PPTY'
        AND IMAGE_THUMBNAIL IS NOT NULL
 }