OUMBUNDL_GET_PROPERTY_BUNDLES {
	SELECT GROUP_ID, GROUP_NAME, PROPERTY_SEQ, CASELOAD_ID, ACTIVE_FLAG, EXPIRY_DATE FROM PROPERTY_GROUPS
}

OUMBUNDL_GET_PROPERTY_BUNDLES_ITEMS {
	SELECT PROPERTY_ITEM_ID, PROPERTY_TYPE_CODE, GROUP_ID, PROPERTY_DESCRIPTION, QUANTITY, CONDITION_CODE, SEQUENCE FROM PROPERTY_GROUP_ITEMS WHERE GROUP_ID = :groupId
}

OUMBUNDL_INSERT_PROPERTY_BUNDLES {
	INSERT INTO PROPERTY_GROUPS(GROUP_ID, GROUP_NAME, PROPERTY_SEQ, CASELOAD_ID, ACTIVE_FLAG, EXPIRY_DATE, CREATE_DATETIME ,CREATE_USER_ID)
	VALUES(:groupId, :groupName, :propertySeq, :caseloadId, :activeFlag, :expiryDate, current_timestamp, :createUserId)
}

OUMBUNDL_UPDATE_PROPERTY_BUNDLES {
	UPDATE PROPERTY_GROUPS set GROUP_NAME = :groupName, PROPERTY_SEQ = :propertySeq, CASELOAD_ID = :caseloadId, ACTIVE_FLAG = :activeFlag, EXPIRY_DATE = :expiryDate,
	 MODIFY_DATETIME=current_timestamp, MODIFY_USER_ID = :modifyUserId WHERE GROUP_ID = :groupId
}

OUMBUNDL_DELETE_PROPERTY_BUNDLES {
	DELETE FROM PROPERTY_GROUPS WHERE GROUP_ID = :groupId
}

OUMBUNDL_INSERT_PROPERTY_ITEMS {
	INSERT INTO PROPERTY_GROUP_ITEMS(PROPERTY_ITEM_ID, GROUP_ID, PROPERTY_DESCRIPTION, PROPERTY_TYPE_CODE, SEQUENCE, RECEIVED_FROM, CONDITION_CODE, QUANTITY, CREATE_DATETIME ,CREATE_USER_ID)
	VALUES(nextval('property_item_id_seq'), :groupId, :propertyDescription, :propertyTypeCode, :sequence, :receivedFrom, :conditionCode, :quantity, current_timestamp, :createUserId)
}

OUMBUNDL_UPDATE_PROPERTY_ITEMS {
	UPDATE PROPERTY_GROUP_ITEMS set GROUP_ID = :groupId, PROPERTY_DESCRIPTION = :propertyDescription,PROPERTY_TYPE_CODE = :propertyTypeCode, SEQUENCE = :sequence, RECEIVED_FROM = :receivedFrom, CONDITION_CODE = :conditionCode,
	 MODIFY_DATETIME=current_timestamp, MODIFY_USER_ID = :modifyUserId WHERE PROPERTY_ITEM_ID = :propertyItemId and GROUP_ID = :groupId
}

OUMBUNDL_DELETE_PROPERTY_ITEMS {
	DELETE FROM PROPERTY_GROUP_ITEMS WHERE PROPERTY_ITEM_ID = :propertyItemId
}

OUMBUNDL_FIND_CASELOAD {
	 SELECT CSLD.CASELOAD_ID CODE,CSLD.DESCRIPTION DESCRIPTION FROM CASELOADS CSLD  WHERE CSLD.ACTIVE_FLAG = 'Y' AND CSLD.CASELOAD_ID IN ( SELECT STAFF_AC.CASELOAD_ID FROM STAFF_ACCESSIBLE_CASELOADS STAFF_AC WHERE STAFF_AC.STAFF_ID = ( SELECT STAFF.STAFF_ID FROM STAFF_MEMBERS STAFF WHERE :userId = STAFF.USER_ID  )  ) ORDER BY CSLD.LIST_SEQ ASC

}