CHK_IND_AC_C{
 SELECT TRUST_ACCOUNT_CODE FROM OFFENDER_SUB_ACCOUNTS WHERE OFFENDER_ID = :P_OFF_ID AND CASELOAD_ID = :P_CSLD_ID AND TRUST_ACCOUNT_CODE IN (SELECT ACCOUNT_CODE FROM INSTITUTION_MINI_BALANCES WHERE CASELOAD_ID = :P_CSLD_ID) AND TRUST_ACCOUNT_CODE IN (SELECT ACCOUNT_CODE FROM ACCOUNT_CODES WHERE CASELOAD_TYPE = :CSLD_TYPE) UNION SELECT TRUST_ACCOUNT_CODE FROM OFFENDER_SUB_ACCOUNTS WHERE OFFENDER_ID = :P_OFF_ID AND CASELOAD_ID = :P_CSLD_ID AND MINIMUM_BALANCE IS NOT NULL AND TRUST_ACCOUNT_CODE IN (SELECT ACCOUNT_CODE FROM ACCOUNT_CODES WHERE CASELOAD_TYPE = :CSLD_TYPE)   
   
}

CHK_CASELOAD_C{
SELECT MIN('X') FROM INSTITUTION_MINI_BALANCES WHERE CASELOAD_ID = :P_CSLD_ID
}

CUR_CHK_IND{
SELECT IND_DATE ,NVL(OSA.IND_DAYS, NVL(IMB.IND_DAYS, 0))IND_DAYS FROM OFFENDER_SUB_ACCOUNTS OSA ,INSTITUTION_MINI_BALANCES IMB WHERE OSA.CASELOAD_ID = :P_CSLD_ID AND OSA.OFFENDER_ID = :P_OFF_ID AND OSA.TRUST_ACCOUNT_CODE = :P_TRUST_ACCT_CODE AND IMB.ACCOUNT_CODE(+) = OSA.TRUST_ACCOUNT_CODE AND IMB.CASELOAD_ID(+) = OSA.CASELOAD_ID AND IMB.AGY_LOC_ID(+) = DECODE(:P_AGYLOC_ID, 'TRN', 'OUT', :P_AGYLOC_ID)
}
GET_DIFFERENCE{
SELECT (:INDDAYS - (TRUNC(SYSDATE) - TRUNC(TO_DATE(:INDDATE,'DD-MM-YYYY')))) DIFF FROM DUAL;
}
SYSTEM_PROFILE_C{
SELECT PROFILE_VALUE ,PROFILE_VALUE_2 FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'IND_CON'
}

GET_TRUST_ACCOUNT_CODE_C{
SELECT ACCOUNT_CODE FROM ACCOUNT_CODES WHERE SUB_ACCOUNT_TYPE = 'REG'
}

SUM_OFF_SUB_ACT_BAL_C{
SELECT SUM(OSA.BALANCE) FROM OFFENDER_SUB_ACCOUNTS OSA WHERE OFFENDER_ID = :P_OFF_ID AND TRUST_ACCOUNT_CODE = :LV_TRUST_ACCOUNT_CODE AND NOT EXISTS (SELECT DISTINCT CASELOAD_ID FROM INSTITUTION_MINI_BALANCES IMB WHERE IMB.CASELOAD_ID = OSA.CASELOAD_ID)
}

MAX_IND_DATE_C{
SELECT MAX(IND_DATE) FROM OFFENDER_SUB_ACCOUNTS OSA WHERE OFFENDER_ID = :P_OFF_ID AND TRUST_ACCOUNT_CODE = :LV_TRUST_ACCOUNT_CODE AND NOT EXISTS (SELECT DISTINCT CASELOAD_ID FROM INSTITUTION_MINI_BALANCES IMB WHERE IMB.CASELOAD_ID = OSA.CASELOAD_ID)
}

GET_MAX_IND_DAYS{
SELECT MAX(OSA.IND_DAYS) FROM OFFENDER_SUB_ACCOUNTS OSA WHERE OFFENDER_ID = :P_OFF_ID AND TRUST_ACCOUNT_CODE = :LV_TRUST_ACCOUNT_CODE AND IND_DATE = :LV_INDIGENT_DATE AND NOT EXISTS (SELECT DISTINCT CASELOAD_ID FROM INSTITUTION_MINI_BALANCES IMB WHERE IMB.CASELOAD_ID = OSA.CASELOAD_ID)
}

GET_NO_FM_DATE_SUBTRATION{
SELECT (TRUNC(SYSDATE) - TO_DATE(:INDDATE,'DD-MM-YYYY')) FROM DUAL
}