
OCMDEFTM_FIND_RGAGYLOC {
 	--SELECT  AL.AGY_LOC_ID CODE, AL.DESCRIPTION   FROM   AGENCY_LOCATIONS AL WHERE   ( ( ACTIVE_FLAG = 'Y' AND DEACTIVATION_DATE IS NULL  )  ) AND AL.AGY_LOC_ID IN ( SELECT CA.AGY_LOC_ID   FROM CASELOAD_AGENCY_LOCATIONS CA   WHERE CA.CASELOAD_ID = :CASELOADID   ) AND AL.AGY_LOC_ID NOT IN ('TRN' , 'OUT' ) AND AL.AGENCY_LOCATION_TYPE=:AGENCYLOCTYPE ORDER BY LIST_SEQ ,DESCRIPTION ,AGY_LOC_ID
select
	AL.AGY_LOC_ID CODE,
	AL.DESCRIPTION
from
	AGENCY_LOCATIONS AL
where
	( ( ACTIVE_FLAG = 'Y'
		and DEACTIVATION_DATE is null ) )
	and AL.AGY_LOC_ID in (
	select
		CA.AGY_LOC_ID
	from
		CASELOAD_AGENCY_LOCATIONS CA
	where
		CA.CASELOAD_ID = :CASELOADID )
	and AL.AGY_LOC_ID not in ('TRN' , 'OUT' )
	and AL.AGENCY_LOCATION_TYPE =:AGENCYLOCTYPE
order by
	LIST_SEQ ,
	DESCRIPTION ,
	AGY_LOC_ID;
}
OCMDEFTM_FIND_RGAGYLOCTYPE {
 	--SELECT REF_CODE.DESCRIPTION DESCRIPTION ,  REF_CODE.CODE CODE   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'AGY_LOC_TYPE'   AND ((ACTIVE_FLAG = 'Y' ) OR ('' = 'ENTER-QUERY' ) ) AND CODE IN ('INST' , 'COMM' ) AND CODE IN (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = USER))  ORDER BY REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION ,REF_CODE.CODE
SELECT REF_CODE.DESCRIPTION DESCRIPTION ,  REF_CODE.CODE CODE   FROM REFERENCE_CODES REF_CODE 
 	WHERE DOMAIN = 'AGY_LOC_TYPE'   AND ((ACTIVE_FLAG = 'Y' ) OR ('' = 'ENTER-QUERY' ) ) AND CODE IN ('INST' , 'COMM' ) 
 	AND CODE IN (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID =:USER_NAME)) 
 	ORDER BY REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION ,REF_CODE.CODE
}

OCMDEFTM_FIND_RGFUNCTION {
 	SELECT REF_CODE.DESCRIPTION , REF_CODE.CODE  FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'FUNCTION'  AND (   (ACTIVE_FLAG = 'Y' )           OR ('' = 'ENTER-QUERY' )           )  ORDER BY REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION ,REF_CODE.CODE
}

OCMDEFTM_AGYTMFN_FIND_AGY_LOC_TEAM_FUNCTIONS {
 	--SELECT AGY_LOC_TEAM_FUNCTION_ID,AGY_LOC_ID,FUNCTION_TYPE,TEAM_ID,OVERWRITTEN_FLAG,EFFECTIVE_DATE,EXPIRY_DATE,ACTIVE_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG  FROM AGY_LOC_TEAM_FUNCTIONS  
 	SELECT AGY_LOC_TEAM_FUNCTION_ID,AGY_LOC_ID,FUNCTION_TYPE,TEAM_ID,OVERWRITTEN_FLAG,EFFECTIVE_DATE,EXPIRY_DATE,ACTIVE_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG  FROM AGY_LOC_TEAM_FUNCTIONS  
}
OCMDEFTM_INSERT_AGY_LOC_TEAM_FUNCTIONS {
--	INSERT INTO AGY_LOC_TEAM_FUNCTIONS(AGY_LOC_TEAM_FUNCTION_ID,AGY_LOC_ID,FUNCTION_TYPE,TEAM_ID,OVERWRITTEN_FLAG,EFFECTIVE_DATE,EXPIRY_DATE,ACTIVE_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG) VALUES(:agyLocTeamFunctionId,:agyLocId,:functionType,:teamId,:overwrittenFlag,:effectiveDate,:expiryDate,:activeFlag,:createDatetime,:createUserId,:modifyDatetime,:modifyUserId,:sealFlag)
	insert into AGY_LOC_TEAM_FUNCTIONS(AGY_LOC_TEAM_FUNCTION_ID, AGY_LOC_ID, FUNCTION_TYPE, TEAM_ID, OVERWRITTEN_FLAG, EFFECTIVE_DATE, EXPIRY_DATE, ACTIVE_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) values(:agyLocTeamFunctionId, :agyLocId, :functionType, :teamId, :overwrittenFlag, :effectiveDate, :expiryDate, :activeFlag,CURRENT_TIMESTAMP, :createUserId,CURRENT_TIMESTAMP, :sealFlag)
}
OCMDEFTM_GET_TEAM_DESCRIPTION{
select DESCRIPTION from automation_teams where TEAM_ID=:teamId
}
OCMDEFTM_UPDATE_AGY_LOC_TEAM_FUNCTIONS {
--	UPDATE AGY_LOC_TEAM_FUNCTIONS set OVERWRITTEN_FLAG=:overwrittenFlag ,EFFECTIVE_DATE=:effectiveDate ,EXPIRY_DATE=:expiryDate ,ACTIVE_FLAG=:activeFlag ,CREATE_DATETIME=:createDatetime ,CREATE_USER_ID=:createUserId ,MODIFY_DATETIME=:modifyDatetime where  AGY_LOC_TEAM_FUNCTION_ID=:agyLocTeamFunctionId
	 update AGY_LOC_TEAM_FUNCTIONS set OVERWRITTEN_FLAG =:overwrittenFlag , EFFECTIVE_DATE =:effectiveDate , EXPIRY_DATE =:expiryDate , ACTIVE_FLAG =:activeFlag , MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME =CURRENT_TIMESTAMP where AGY_LOC_TEAM_FUNCTION_ID =:agyLocTeamFunctionId
}
OCMDEFTM_CHECK_TEAM_EXIST{
SELECT 'Y' FROM agy_loc_team_functions WHERE agy_loc_id = :agyLocId AND function_type = :functionType AND active_flag = 'Y'
}
OCMDEFTM_GET_LOC_ID{
--SELECT agy_loc_team_function_id.NEXTVAL FROM DUAL
SELECT NEXTVAL('AGY_LOC_TEAM_FUNCTION_ID')
}
