GET_CASE_LOAD_LIST {
 SELECT CSLD.CASELOAD_ID CODE ,CSLD.DESCRIPTION DESCRIPTION , CSLD.CASELOAD_TYPE CASELOAD_TYPE   FROM CASELOADS CSLD  WHERE CSLD.ACTIVE_FLAG = 'Y' AND CSLD.CASELOAD_ID IN ( SELECT STAFF_AC.CASELOAD_ID FROM STAFF_ACCESSIBLE_CASELOADS STAFF_AC WHERE STAFF_AC.STAFF_ID = ( SELECT STAFF.STAFF_ID FROM STAFF_MEMBERS STAFF WHERE USER = STAFF.USER_ID  )  ) ORDER BY CSLD.LIST_SEQ ASC
}

GET_TEAMS_DATA { 
SELECT TEAM_ID,TEAM_CODE ,DESCRIPTION ,TEAM_EMAIL, ACTIVE_FLAG ,EXPIRY_DATE ,CREATE_USER_ID ,MODIFY_USER_ID ,MODIFY_DATETIME ,CREATE_DATETIME    FROM automation_teams 
  order by active_flag desc,team_code,description

}

INSERT_TEAMS_DATA { 

INSERT INTO automation_teams(TEAM_ID,TEAM_CODE ,DESCRIPTION , TEAM_EMAIL,ACTIVE_FLAG ,EXPIRY_DATE ,CREATE_USER_ID ,MODIFY_USER_ID ,MODIFY_DATETIME ,CREATE_DATETIME) 
VALUES(:teamId,:teamCode ,:description , :teamEmail,:activeFlag ,:expiryDate ,:createUserId ,null ,null ,:createDatetime)

}

UPDATE_TEAMS_DATA {
	UPDATE automation_teams set ACTIVE_FLAG  = :activeFlag , TEAM_EMAIL = :teamEmail, EXPIRY_DATE  = :expiryDate ,MODIFY_USER_ID  = :modifyUserId ,MODIFY_DATETIME  = :modifyDatetime   where TEAM_ID  = :teamId
}

DELETE_TEAMS_DATA{ 
DELETE FROM automation_teams   where TEAM_ID  = :teamId
}

OCMTEAMMAIN_FIND_AGYLOC {
 	SELECT agy_loc.description description, agy_loc.agy_loc_id code 
 FROM agency_locations agy_loc WHERE ACTIVE_FLAG='Y'
}

GET_TEAM_ID { 
SELECT nextval('AUTOMATION_TEAMS_team_id')  FROM DUAL;
}

INSERT_TEAM_FUNCTIONS {
	INSERT INTO TEAM_FUNCTIONS(TEAM_ID ,FUNCTION_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG ) VALUES(:teamId ,:functionType ,:createDatetime ,:createUserId  ,:sealFlag )
}

INSERT_TEAM_AGENCY {
	INSERT INTO TEAM_AGENCY_LOC(TEAM_ID ,AGY_LOC_ID ,CREATE_DATETIME ,CREATE_USER_ID ,ACTIVE_FLAG ) VALUES(:teamId ,:agyLocId ,:createDatetime ,:createUserId ,:activeFlag )
}

DELETE_TEAM_FUNCTIONS{ 
DELETE FROM TEAM_FUNCTIONS   where TEAM_ID  = :teamId
}

DELETE_TEAM_AGENCY{ 
DELETE FROM TEAM_AGENCY_LOC   where TEAM_ID  = :teamId
}

GET_TEAM_AGENCY_DATA{ 
SELECT TEAM_ID,AGY_LOC_ID,CREATE_DATETIME,CREATE_USER_ID,ACTIVE_FLAG FROM TEAM_AGENCY_LOC where TEAM_ID  = :teamId
}

GET_TEAM_FUNCTION_DATA{ 
SELECT TEAM_ID,FUNCTION_TYPE,CREATE_DATETIME,CREATE_USER_ID,SEAL_FLAG FROM TEAM_FUNCTIONS where TEAM_ID  = :teamId
}
GET_STAFF_DETAILS {
 	SELECT DISTINCT SM.LAST_NAME LAST_NAME , SM.FIRST_NAME FIRST_NAME , SM.STAFF_ID, SM.STAFF_ID CODE ,SM.USER_ID    
 	FROM STAFF_MEMBERS SM  where STATUS='ACTIVE' ORDER BY 1 , 2
}
GET_TEAM_MEMBERS_DATA {
 	SELECT TM.TEAM_ID ,TM.STAFF_ID ,SM.last_name,SM.USER_ID,SM.first_name,TM.TEAM_MEMBER_ID ,TM.ACTIVE_FLAG,TM.EXPIRY_DATE ,TM.CREATE_DATETIME ,TM.CREATE_USER_ID ,TM.MODIFY_DATETIME ,TM.MODIFY_USER_ID 
 	 FROM TEAM_STAFF_MEMBERS TM ,staff_members SM  where  TM.staff_id=SM.staff_id AND TM.TEAM_ID =:teamId order by SM.staff_id
}
INSERT_TEAM_MEMBERS_DATA {
	INSERT INTO TEAM_STAFF_MEMBERS(TEAM_ID ,STAFF_ID ,TEAM_MEMBER_ID ,ACTIVE_FLAG ,EXPIRY_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ) VALUES(:teamId ,:staffId ,:teamMemberId  ,:activeFlag ,:expiryDate ,:createDateTime ,:createUserId ,null ,null )
}

UPDATE_TEAM_MEMBERS_DATA {
	UPDATE TEAM_STAFF_MEMBERS set TEAM_ID  = :teamId ,STAFF_ID  = :staffId ,ACTIVE_FLAG  = :activeFlag ,EXPIRY_DATE  = :expiryDate,MODIFY_DATETIME  = :modifyDateTime ,MODIFY_USER_ID  = :modifyUserId  where TEAM_MEMBER_ID  = :teamMemberId 
}
GET_TEAM_MEMBER_ID { 
SELECT nextval('TEAM_STAFF_MEMBERS_TEAM_ID_SEQ') FROM DUAL
}

DELETE_TEAM_MEMBERS_DATA { 
DELETE FROM TEAM_STAFF_MEMBERS WHERE TEAM_MEMBER_ID = :teamMemberId 
}
