KEY_CUR{
SELECT USER_ID , OFFENDER_BOOK_ID , OFFENDER_ID_DISPLAY , OBJECT_TYPE , OBJECT_ID , MODULE_NAME , OS_USER , PRISON_LOCATION , OFF_SUP_LEVEL , TRIM_USER , STATUS_DISPLAY FROM EOFFENDER_KEY_LOGINS WHERE KEY_LOGIN = :P_KEY
}