INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OIRREPORT', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OIIMPJRP', 444, 'Q', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OIEXPJRP', 444, 'Q', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES('OIRMREPOR', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCDCHGDT', 444, 'A', 'Y', current_timestamp,'OMS_OWNER', current_timestamp,NULL, NULL); 