--echo everything (this eliminates the need to use -a)
\set ECHO all

--set the message level sent to client
SET client_min_messages = warning;

--print connection information
\echo 'Database Information:'
\conninfo

--set client session behaviour
\set AUTOCOMMIT on
\timing on
\set footer on
\x auto
\pset null <NULL>
\set VERBOSITY verbose
\pset pager off

show search_path;

select current_timestamp;

--record scripts version
call log_db_version_control('5', 'initial PostgreSql Elite db version ');
call log_db_version_control_patches('5', 'v5_0_0_9_3_audit', 'ddl audit columns set 1_0 of patch v5_0_0_9_3_audit', '1_0_batch_oms_owner_ddl_v5_0_0_9_3_audit.run');

--execute sql scripts

---------------------------------------------------------------------
--ddl and dml to support ddl for missing audit columns and seal flag 
---------------------------------------------------------------------

\i 1_fix_tables_missing_all_audit_columns.sql 
\i 2_fix_tables_missing_create_datetime_column.sql 
\i 3_fix_tables_missing_create_user_id_column.sql 
\i 4_fix_tables_missing_modify_datetime_column.sql 
\i 5_fix_tables_missing_modify_user_id_column.sql 
\i 6_fix_tables_missing_seal_flag_column.sql 


select current_timestamp;

show search_path;

 
 





