
OIUPRRES_PRRES_FIND_OFFENDER_GRIEVANCE_TXNS {
 SELECT GRIEVANCE_ID ,TXN_SEQ ,START_DATE ,END_DATE ,GRIEV_TYPE ,TXN_TYPE ,FINDING ,ASSIGNED_STAFF_ID ,GRIEV_LEVEL ,CREATE_USER_ID ,CREATE_DATETIME ,STATUS ,PROPOSED_RESPONSE ,OFFICIAL_RESPONSE , MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG FROM OFFENDER_GRIEVANCE_TXNS WHERE GRIEVANCE_ID = :grievanceId AND TXN_SEQ = :txnSeq 
}

OIUPRRES_PRRES_INSERT_OFFENDER_GRIEVANCE_TXNS {
insert into OFFENDER_GRIEVANCE_TXNS(GRIEVANCE_ID , TXN_SEQ , START_DATE , END_DATE , GRIEV_TYPE , TXN_TYPE , FINDING , ASSIGNED_STAFF_ID , GRIEV_LEVEL , CREATE_USER_ID , CREATE_DATETIME , STATUS , PROPOSED_RESPONSE , OFFICIAL_RESPONSE , MODIFY_DATETIME , SEAL_FLAG ) values(:grievanceId , :txnSeq , :startDate , :endDate , :grievType , :txnType , :finding , :assignedStaffId , :grievLevel , :createUserId , current_timestamp, :status , :proposedResponse , :officialResponse , null , :sealFlag )
}

OIUPRRES_PRRES_UPDATE_OFFENDER_GRIEVANCE_TXNS {	
 update OFFENDER_GRIEVANCE_TXNS set PROPOSED_RESPONSE =:proposedResponse, modify_user_id =:modifyUserId, modify_datetime = current_timestamp where GRIEVANCE_ID =:grievanceId and TXN_SEQ =:txnSeq
 }

OIUPRRES_GET_PROPOSED_RESPONSE {
	SELECT PROPOSED_RESPONSE FROM OFFENDER_GRIEVANCE_TXNS WHERE GRIEVANCE_ID = :GRIEVANCEID AND TXN_SEQ = :TXNSEQ
}
