
OIUSTINV_FIND_RGSTAFF {
	SELECT SM.LAST_NAME , SM.USER_ID, SM.STAFF_ID, to_char(SM.STAFF_ID) CODE, SM.user_id description FROM STAFF_MEMBERS SM , CASELOADS C 
  	WHERE SM.STATUS = 'ACTIVE'  AND SM.USER_ID IS NOT NULL AND C.CASELOAD_ID = SM.WORKING_CASELOAD_ID AND C.CASELOAD_TYPE = 'INST' ORDER BY USER_ID
  	}

OIUSTINV_OFFENDERGRIEVSTAFFS_FIND_OFFENDER_GRIEV_STAFFS {
 	SELECT GRIEVANCE_ID,STAFF_ID,MODIFY_USER_ID,MODIFY_DATETIME,CREATE_DATETIME,CREATE_USER_ID,SEAL_FLAG, ROW_ID  FROM OFFENDER_GRIEV_STAFFS WHERE GRIEVANCE_ID = :GRIEVANCE_ID
}
OIUSTINV_OFFENDERGRIEVSTAFFS_INSERT_OFFENDER_GRIEV_STAFFS {
	insert into OFFENDER_GRIEV_STAFFS(GRIEVANCE_ID, STAFF_ID, MODIFY_DATETIME, CREATE_DATETIME, CREATE_USER_ID, MODIFY_USER_ID, SEAL_FLAG) values(:grievanceId, :staffId, null , current_timestamp, :createUserId, null, :sealFlag)
	}  

OIUSTINV_OFFENDERGRIEVSTAFFS_UPDATE_OFFENDER_GRIEV_STAFFS {
	UPDATE OFFENDER_GRIEV_STAFFS set GRIEVANCE_ID=:grievanceId,STAFF_ID=:staffId,MODIFY_USER_ID=:modifyUserId,MODIFY_DATETIME=current_timestamp,SEAL_FLAG=:sealFlag WHERE GRIEVANCE_ID = :grievanceId AND ROW_ID = :rowId
}

OIUSTINV_OFFENDERGRIEVSTAFFS_DELETE_OFFENDER_GRIEV_STAFFS { 
	DELETE FROM OFFENDER_GRIEV_STAFFS WHERE GRIEVANCE_ID = :grievanceId AND STAFF_ID = :staffId
}


OIUSTINV_OFFENDER_GRIEV_STAFFS_POSTQUERY {
	SELECT LAST_NAME, FIRST_NAME, MIDDLE_NAME FROM STAFF_MEMBERS WHERE STAFF_ID = :STAFFID
}

OIUSTINV_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
