update dynamic_grid_config 
  set   modify_datetime = current_timestamp
       ,modify_user_id = 'OMS_OWNER' 
       ,config_json = '[{"field":"displayNo","fieldName":"ocdleglo.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"ocdleglo.ordereddate","dataType":"date","required":true},{"field":"matter","fieldName":"ocdleglo.matter","dataType":"text","editable":false},{"field":"court","fieldName":"ocdleglo.court","dataType":"lov","source":"link","url":"ocdccase/populateCourtData","sourceType":"OUMAGLOC","required":true},{"field":"type","fieldName":"ocdleglo.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=","sourceType":"OIMSREQS","required":true},{"field":"commenceType","fieldName":"ocdleglo.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","required":true},{"field":"relatedTo","fieldName":"ocdleglo.linkto","dataType":"text","editable":false},{"field":"relatedToLaunch","dataType":"hyperlink","link":"/relatedToLine","parentField":["relatedTo"]},{"field":"commenceDate","fieldName":"ocdleglo.commencedate","dataType":"date"},{"field":"termTypeAndLength","fieldName":"ocdleglo.termtypeandlength","dataType":"text","required":true,"editable":false},{"field":"lengthBtn","dataType":"hyperlink","link":"/termToLine","parentField":["termTypeAndLength","terms"]},{"field":"pel","fieldName":"ocdleglo.pel","dataType":"checkbox"},{"field":"status","fieldName":"ocdleglo.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"terms","hide":true,"dataType":"text"},{"field":"charges","hide":true,"dataType":"text"},{"field":"orderType","hide":true,"dataType":"text"},{"field":"holdExpiryDate","fieldName":"ocdleglo.holdExpirydate","dataType":"date"}]' 
  where module_name = 'OCDLEGLO' and grid_name = 'custOrd';

update dynamic_grid_config 
   set modify_datetime = current_timestamp
       ,modify_user_id = 'OMS_OWNER' 
       ,config_json  = '[{"field":"displayNo","fieldName":"custorder.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"type","fieldName":"custorder.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=CUST","sourceType":"OIMSREQS","editable":false},{"field":"termTypeAndLength","fieldName":"custorder.termtypeandlength","dataType":"text","editable":false},{"field":"commenceType","fieldName":"custorder.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","editable":false},{"field":"relatedTo","fieldName":"custorder.linkto","dataType":"text","editable":false},{"field":"commenceDate","fieldName":"custorder.commencedate","dataType":"date","editable":false},{"field":"erd","fieldName":"custorder.erd","dataType":"text","editable":false},{"field":"ped","fieldName":"custorder.ped","dataType":"date","editable":false},{"field":"lrd","fieldName":"custorder.lrd","dataType":"text","editable":false},{"field":"holdExpiryDate","fieldName":"ocdleglo.holdExpirydate","dataType":"text","editable": false},{"field":"status","fieldName":"custorder.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"orderType","hide":true,"dataType":"text","editable":false}]' 
   where module_name = 'OCDLEGLS' and grid_name = 'custOrders';

UPDATE DYNAMIC_GRID_CONFIG 
   SET modify_datetime = current_timestamp
       ,modify_user_id = 'OMS_OWNER' 
       ,CONFIG_JSON ='[{"field":"displayNo","fieldName":"ocdleglo.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"ocdleglo.ordereddate","dataType":"date","required":true},{"field":"matter","fieldName":"ocdleglo.matter","dataType":"text","editable":false},{"field":"court","fieldName":"ocdleglo.court","dataType":"lov","source":"link","url":"ocdccase/populateCourtData","sourceType":"OUMAGLOC","required":true},{"field":"type","fieldName":"ocdleglo.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=","sourceType":"OIMSREQS","required":true},{"field":"commenceType","fieldName":"ocdleglo.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","required":true},{"field":"relatedTo","fieldName":"ocdleglo.linkto","dataType":"text","editable":false},{"field":"relatedToLaunch","dataType":"hyperlink","link":"/relatedToLine","parentField":["relatedTo"]},{"field":"commenceDate","fieldName":"ocdleglo.commencedate","dataType":"date"},{"field":"termTypeAndLength","fieldName":"ocdleglo.termtypeandlength","dataType":"text","required":true,"editable":false},{"field":"lengthBtn","dataType":"hyperlink","link":"/termToLine","parentField":["termTypeAndLength","terms"]},{"field":"pel","fieldName":"ocdleglo.pel","dataType":"checkbox"},{"field":"status","fieldName":"ocdleglo.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"intParties","dataType":"hyperlink","link":"/OCDINTPA","fieldName":"ocdleglo.intParties"},{"field":"terms","hide":true,"dataType":"text"},{"field":"charges","hide":true,"dataType":"text"},{"field":"orderType","hide":true,"dataType":"text"},{"field":"holdExpiryDate","fieldName":"ocdleglo.holdExpirydate","dataType":"date"}]' 
   WHERE MODULE_NAME = 'OCDLEGLO' AND GRID_NAME = 'custOrd';

UPDATE DYNAMIC_GRID_CONFIG 
   SET modify_datetime = current_timestamp
       ,modify_user_id = 'OMS_OWNER' 
       ,CONFIG_JSON ='[{"field":"displayNo","fieldName":"ocdncode.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"ocdncode.ordereddate","dataType":"date","required":true},{"field":"matter","fieldName":"ocdncode.matter","dataType":"text","editable":false},{"field":"court","fieldName":"ocdncode.court","dataType":"lov","source":"link","url":"ocdccase/populateCourtData","sourceType":"OUMAGLOC","required":true},{"field":"type","fieldName":"ocdncode.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=","sourceType":"OIMSREQS","required":true},{"field":"commenceType","fieldName":"ocdncode.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","required":true},{"field":"relatedTo","fieldName":"ocdncode.linkto","dataType":"text","editable":false},{"field":"relatedToLaunch","dataType":"hyperlink","link":"/nonCustRelated","parentField":["relatedTo"]},{"field":"commenceDate","fieldName":"ocdncode.commencedate","dataType":"date"},{"field":"termTypeAndLength","fieldName":"ocdncode.termtypeandlength","dataType":"text","required":true,"editable":false},{"field":"lengthBtn","dataType":"hyperlink","link":"/nonCustDuration","parentField":["termTypeAndLength","terms"]},{"field":"expiryDate","fieldName":"ocdncode.expiryDate","dataType":"date","editable":true},{"field":"status","fieldName":"ocdncode.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"intParties","dataType":"hyperlink","link":"/OCDINTPA","fieldName":"ocdncode.intparties"},{"field":"terms","hide":true,"dataType":"text"},{"field":"orderType","hide":true,"dataType":"text"},{"field":"charges","hide":true,"dataType":"text"}]' 
  WHERE MODULE_NAME = 'OCDNCODE' AND GRID_NAME = 'nonCustOrd';