DELETE FROM IWP_TEMPLATE_ROLES WHERE  ROLE_CODE ='CNOTE_AMEND';
DELETE FROM IWP_TEMPLATE_ROLES WHERE  ROLE_CODE ='CNOTE_DELETE';
DELETE FROM IWP_TEMPLATE_ROLES WHERE  ROLE_CODE ='CNOTE_UPDATE';
DELETE FROM IWP_TEMPLATE_ROLES WHERE  ROLE_CODE ='CLOGS_UPDATE';
DELETE FROM IWP_TEMPLATE_ROLES WHERE  ROLE_CODE ='CLOGS_AMEND';
DELETE FROM IWP_TEMPLATE_ROLES WHERE  ROLE_CODE ='CLOGS_DELETE';