DELETE FROM MODULE_PRIVILEGES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_AMEND');
DELETE FROM MODULE_PRIVILEGES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_DELETE');
DELETE FROM MODULE_PRIVILEGES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_UPDATE');
DELETE FROM MODULE_PRIVILEGES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_UPDATE');
DELETE FROM MODULE_PRIVILEGES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_AMEND');
DELETE FROM MODULE_PRIVILEGES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_DELETE');

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES('OCDINTPA', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

Insert into MODULE_PRIVILEGES (MODULE_NAME,ROLE_ID,ACCESS_PRIVILEGE,VERIFICATION_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG) 
values ('OIMSRLUC',444,'A','Y',CURRENT_TIMESTAMP,USER,NULL,NULL,null);

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OIDOWREL', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OIDOWREL', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCICNSRC', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO MODULE_PRIVILEGES (MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES('OCMCNPER', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL, NULL);