DELETE FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_AMEND';
DELETE FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_DELETE';
DELETE FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_UPDATE';
DELETE FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_UPDATE';
DELETE FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_AMEND';
DELETE FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_DELETE';

INSERT INTO oms_owner.oms_roles (role_id, role_name, role_seq, create_datetime, create_user_id, modify_datetime, modify_user_id, role_code, parent_role_code, seal_flag)
VALUES(nextval('role_id'), 'Enhanced Staff Report User', 1, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, 'STAFF_ENHAN', NULL, NULL);