DELETE FROM STAFF_MEMBER_ROLES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_AMEND');
DELETE FROM STAFF_MEMBER_ROLES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_DELETE');
DELETE FROM STAFF_MEMBER_ROLES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CNOTE_UPDATE');
DELETE FROM STAFF_MEMBER_ROLES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_UPDATE');
DELETE FROM STAFF_MEMBER_ROLES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_AMEND');
DELETE FROM STAFF_MEMBER_ROLES WHERE ROLE_ID = (SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE ='CLOGS_DELETE');