
OSIHRSUM_FIND_CGFKFAFDESTINATIONFORM {
 	SELECT OMS_MOD.MODULE_NAME code  ,OMS_MOD.DESCRIPTION DESCRIPTION FROM OMS_MODULES OMS_MOD , FORM_ACCESSIBLE_FORMS FAF WHERE OMS_MOD.MODULE_TYPE = 'SCREEN' AND FAF.ORIGINATING_FORM = 'OSIHRSUM' AND FAF.DESTINATION_FORM = OMS_MOD.MODULE_NAME
}

OSIHRSUM_OFFBKGS_FIND_V_HEADER_BLOCK {
 	SELECT OFFENDER_ID ,ALIAS_OFFENDER_ID ,OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,SUFFIX ,BIRTH_DATE ,OFFENDER_BOOK_ID ,BOOKING_NO ,BOOKING_BEGIN_DATE ,BOOKING_END_DATE ,AGY_LOC_ID ,AGENCY_IML_ID ,LIVING_UNIT_ID ,DISCLOSURE_FLAG ,ACTIVE_FLAG ,BOOKING_STATUS ,LIVING_UNIT_DESCRIPTION ,IN_OUT_STATUS ,STATUS_DISPLAY ,ROOT_OFFENDER_ID ,ASSIGNED_STAFF_ID ,AGY_LOC_TYPE ,CREATE_AGY_LOC_ID ,BOOKING_TYPE ,BOOKING_CREATED_DATE ,LOCATION_CODE ,LIV_UNIT_DESC ,INTAKE_AGY_LOC_ID ,COMMUNITY_ACTIVE_FLAG ,CREATE_INTAKE_AGY_LOC_ID ,COMMUNITY_STATUS ,STATUS_REASON ,HEADER_STATUS ,AGE ,GENDER ,OFFICER ,PRISON_LOCATION ,OFF_ALERTS ,STATUS_1 ,STATUS_2 ,STATUS_3 ,ETHNICITY ,MOVEMENT_REASON ,OFF_SUP_LEVEL   FROM V_HEADER_BLOCK_FN(:USERID)  V_HEADER_BLOCK  /* where  */
}
OSIHRSUM_VHISBOO_FIND_V_HISTORICAL_BOOKINGS {
	SELECT AGY_LOC.AGY_LOC_ID, AGY_LOC.DESCRIPTION LOCATOIN_DESCRIPTION, AGY_LOC.AGENCY_LOCATION_TYPE AGY_LOC_TYPE, vhb.ROOT_OFFENDER_ID , vhb.OFFENDER_BOOK_ID , vhb.IN_MOVEMENT_SEQ , vhb.IN_DATE , vhb.IN_TIME , vhb.IN_MOVEMENT_TYPE , vhb.IN_MOVEMENT_REASON_CODE , vhb.OUT_DATE , vhb.OUT_TIME , vhb.OUT_MOVEMENT_SEQ , vhb.OUT_MOVEMENT_TYPE , vhb.OUT_MOVEMENT_REASON_CODE , vhb.BOOKING_NO FROM AGENCY_LOCATIONS AGY_LOC, (SELECT ROOT_OFFENDER_ID , OFFENDER_BOOK_ID , IN_MOVEMENT_SEQ , IN_DATE , IN_TIME , IN_MOVEMENT_TYPE , IN_MOVEMENT_REASON_CODE , AGY_LOC_ID , OUT_DATE , OUT_TIME , OUT_MOVEMENT_SEQ , OUT_MOVEMENT_TYPE , OUT_MOVEMENT_REASON_CODE , BOOKING_NO FROM V_HISTORICAL_BOOKINGS WHERE ROOT_OFFENDER_ID=:rootOffenderId ) vhb WHERE vhb.AGY_LOC_ID = AGY_LOC.AGY_LOC_ID ORDER BY IN_DATE DESC, IN_TIME DESC
}
OSIHRSUM_FAF_FIND_FORM_ACCESSIBLE_FORMS {
	SELECT ORIGINATING_FORM , DESTINATION_FORM , LIST_SEQ , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID , SEAL_FLAG FROM FORM_ACCESSIBLE_FORMS WHERE ORIGINATING_FORM = 'OSIHRSUM' AND DESTINATION_FORM IN (SELECT MODULE_NAME FROM MODULE_PRIVILEGES WHERE ROLE_ID IN (SELECT ROLE_ID FROM STAFF_MEMBER_ROLES WHERE STAFF_ID = (SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID = upper(:userName) ) ) ) order by LIST_SEQ ASC
}
OSIHRSUM_FAF_INSERT_FORM_ACCESSIBLE_FORMS {
	insert
	into
	FORM_ACCESSIBLE_FORMS(ORIGINATING_FORM ,
	DESTINATION_FORM ,
	CREATE_DATETIME ,
	CREATE_USER_ID ,
	MODIFY_DATETIME,
	SEAL_FLAG )
values('OSIHRSUM' ,
:destinationForm ,
CURRENT_TIMESTAMP ,
:createUserId,
NULL ,
:sealFlag)
}

OSIHRSUM_FAF_DELETE_FORM_ACCESSIBLE_FORMS { 
	DELETE FROM FORM_ACCESSIBLE_FORMS where ORIGINATING_FORM = :originatingForm and DESTINATION_FORM = :destinationForm
}

OSIHRSUM_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OSIHRSUM_OFF_BKGS_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM V_HISTORICAL_BOOKINGS WHERE ROOT_OFFENDER_ID = :ROOTOFFENDERID
}

OSIHRSUM_CGFKCHK_V_HIS_BOO_V_HIS_BOO_A_ {
	SELECT AGY_LOC.DESCRIPTION FROM   AGENCY_LOCATIONS AGY_LOC WHERE  AGY_LOC.AGY_LOC_ID = :AGYLOCID
}

OSIHRSUM_CGFKCHK_FAF_FAF_OMS_MOD_F2_ {
	SELECT OMS_MOD.DESCRIPTION FROM   OMS_MODULES OMS_MOD WHERE  OMS_MOD.MODULE_NAME = :DESTINATIONFORM
}

OSIHRSUM_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

GET_IMAGE_DATA {
	SELECT IMAGE_ID, CAPTURE_DATE, IMAGE_OBJECT_TYPE, IMAGE_OBJECT_ID, IMAGE_OBJECT_SEQ, IMAGE_VIEW_TYPE, IMAGE_THUMBNAIL, ACTIVE_FLAG, ORIENTATION_TYPE, SEAL_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID FROM IMAGES WHERE image_object_id = :offenderBookId AND active_flag = 'Y' AND image_object_type = 'OFF_BKG' AND image_view_type = 'FACE'
}

GET_COMMENT_CUR {
	SELECT comment_text FROM offender_external_movements WHERE offender_book_id = :offenderBookId and movement_seq = :movementSeq
}

GET_COMM_COMMENT_CUR {
	SELECT obs.addition_comment FROM offender_booking_agy_locs obs WHERE obs.offender_book_id = :offenderBookId AND obs.agy_loc_id = 
	:agyLocId AND TO_CHAR(obs.ADDITION_DATE, 'DD-MM-YYYY') = :inDate AND TO_CHAR(obs.ADDITION_TIME, 'HH24:MI:SS') = :inTime
}

GET_COMM_CLOSE_COMMENT_CUR {
	SELECT COMMENT_TEXT FROM OFFENDER_BOOKING_EVENTS WHERE OFFENDER_BOOK_ID = :offenderBookId AND TO_CHAR(EVENT_DATE, 'DD-MM-YYYY') = :outDate and TO_CHAR(EVENT_TIME, 'HH24:MI:SS') = :outTime
}
GET_OFFENDER_COMMENT_TEXT_OFFENDER_RELEASE_DETAILS
{
select coalesce (( select comment_text from OFFENDER_RELEASE_DETAILS where offender_book_id = :offenderBookId), ( select comment_text from offender_external_movements where offender_book_id = :offenderBookId and movement_seq =:movementSeq))}