INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME) 
 select 'HOUSE_ADM', 444, 'A', 'Y', 'OMS_OWNER', current_timestamp, current_timestamp 
 where NOT EXISTS (select 1 from OMS_OWNER.MODULE_PRIVILEGES where module_name = 'HOUSE_ADM' and role_id = 444);

INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME) 
 select 'OIDOICAP', 444, 'A', 'Y', 'OMS_OWNER', current_timestamp, current_timestamp 
where NOT EXISTS (select 1 from OMS_OWNER.MODULE_PRIVILEGES where module_name = 'OIDOICAP' and role_id = 444);


