ADDRESES_T1_OFFENDERS_RECORD{
SELECT COUNT(*)  FROM   OFFENDERS WHERE  OFFENDER_ID = :ownerId
}

ADDRESES_T1_PERSON_RECORD{
SELECT COUNT(*) FROM   PERSONS WHERE  PERSON_ID = :ownerId
}
ADDRESES_T1_CORPORATE_RECORD{
SELECT COUNT(*)  FROM   CORPORATES WHERE  CORPORATE_ID = :ownerId
}

ADDRESES_T1_STAFF_RECORD{
SELECT COUNT(*)   FROM   STAFF_MEMBERS WHERE  STAFF_ID = :ownerId

}
ADDRESES_T1_LOCATION_RECORD{
SELECT COUNT(*)  FROM   AGENCY_LOCATIONS WHERE  AGY_LOC_ID = :ownerCode
}
ADDRESES_T1_OFFENDER_EDUCATION_RECORD{
SELECT COUNT(*)  FROM   OFFENDER_EDUCATIONS WHERE  OFFENDER_BOOK_ID = :ownerId   AND    EDUCATION_SEQ    = :ownerSeq

}
ADDRESES_T1_OFFENDER_EMPLOYMENT_RECORD{
SELECT COUNT(*)  FROM   OFFENDER_EMPLOYMENTS WHERE  OFFENDER_BOOK_ID = :ownerId AND    EMPLOY_SEQ   = :ownerSeq

}
ADDRESES_T1_PERSON_EMPLOYMENT_RECORD{
SELECT COUNT(*)  FROM   PERSON_EMPLOYMENTS WHERE  PERSON_ID  = :ownerId AND    EMPLOYMENT_SEQ = :ownerSeq

}
	