ADDRESEST2_PHONE_RECORDS_EXISTS {
-- SELECT COUNT(*) INTO V_NUMROWS FROM   PHONES WHERE  OWNER_CLASS = 'ADDR' AND    OWNER_ID = :addressId
 SELECT COUNT(*)  FROM   PHONES WHERE  OWNER_CLASS = 'ADDR' AND    OWNER_ID = :addressId

 }
 ADDRESEST2_INTERNET_ADDRESSES_RECORDS_EXISTS {
 SELECT COUNT(*) FROM   INTERNET_ADDRESSES WHERE  OWNER_CLASS = 'ADDR' AND    OWNER_ID = :addressId
 }