GET_AGY_LOC_ESTABLISHMENTS {
 SELECT AGY_LOC_ID,
ESTABLISHMENT_TYPE,
CREATE_DATETIME,
CREATE_USER_ID,
MODIFY_DATETIME,
MODIFY_USER_ID,
SEAL_FLAG
 FROM AGY_LOC_ESTABLISHMENTS WHERE AGY_LOC_ID = :AGY_LOC_ID and establishment_type=:ESTABLISHMENT_TYPE 
 }
 