INSERT_CASELOAD_TRANSACTION_TYPES_JN{
INSERT INTO CASELOAD_TRANSACTION_TYPES_JN (JN_OPERATION,
    JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN,
    JN_SESSION, CASELOAD_ID, ACCOUNT_CODE, LIST_SEQ
    , MODIFY_DATE, MODIFY_USER_ID, CREATE_USER_ID
    , CREATE_DATETIME, MODIFY_DATETIME
    )
    VALUES ('INS', :USERNAME, current_timestamp, NULL, NULL,
    0, :CASELOAD_ID, :ACCOUNT_CODE
    , :LIST_SEQ, :MODIFY_DATE
    , :MODIFY_USER_ID, :CREATE_USER_ID
    , :CREATE_DATETIME, :MODIFY_DATETIME
     )
}

