COM_CSLD_CURRENT_ACCTS_BASE_T1_GET{
SELECT CASELOAD_ID,ACCOUNT_CODE,ACCOUNT_PERIOD_ID,CURRENT_BALANCE,BANK_ACCOUNT_TYPE,BANK_ACCOUNT_NUMBER,ACCOUNT_PARTY_TYPE,PAYEE_PERSON_ID,PAYEE_CORPORATE_ID,MODIFY_USER_ID,MODIFY_DATE,LIST_SEQ,ROUTING_NUMBER,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG FROM COM_CSLD_CURRENT_ACCOUNTS_BASE WHERE CASELOAD_ID=:caseloadId AND ACCOUNT_CODE=:accountCode
}
COM_CSLD_CURRENT_ACCTS_BASE_T1_L_BANK_CHQ_BOOKS_EXISTS_CUR{
SELECT 'Y'  FROM COMM_BANK_CHEQUE_BOOKS WHERE caseload_id =  :caseloadId AND account_code = :accountCode
}
COM_CSLD_CURRENT_ACCTS_BASE_T1_UPDATE{
UPDATE comm_bank_cheque_books SET account_number = :bankAccountNumber WHERE caseload_id =  :caseloadId  AND account_code = :accountCode
}