COMM_GL_TRANSACTIONS_T1_COMM_GL_TRANSACTIONS{
SELECT TXN_ID,TXN_ENTRY_SEQ,GL_ENTRY_SEQ,ACCOUNT_PERIOD_ID,ACCOUNT_CODE,TXN_ENTRY_DATE,TXN_TYPE,TXN_POST_USAGE,CASELOAD_ID,OFFENDER_ID,TXN_ENTRY_AMOUNT,TXN_ENTRY_DESC,TXN_REFERENCE_NUMBER,BANK_STATEMENT_DATE,RECON_CLEAR_FLAG,TXN_REVERSED_FLAG,REVERSED_TXN_ID,REVERSED_TXN_ENTRY_SEQ,REVERSED_GL_ENTRY_SEQ,PAYEE_NAME_TEXT,PAYEE_CORPORATE_ID,PAYEE_PERSON_ID,STOCK_ITEM_ID,SALES_ORDER_ID,SHIPMENT_PAYMENT_ID,MODIFY_USER_ID,MODIFY_DATETIME,RETURN_ID,TXN_LOC_ID,OFF_TXN_ID,CREATE_DATETIME,CREATE_USER_ID,SEAL_FLAG FROM COMM_GL_TRANSACTIONS WHERE TXN_ID=:txnId AND TXN_ENTRY_SEQ=:txnEntrySeq AND GL_ENTRY_SEQ=:glEntrySeq
}
COMM_GL_TRANSACTIONS_T1_V_PROFILE_VALUE{
SELECT profile_value FROM system_profiles WHERE profileType = 'CLIENT' AND profileCode = 'TRUST_AUDITS'
}
COMM_GL_TRANSACTIONS_T1_V_MODULE_NAME{
SELECT module_name FROM   TRUST_AUDITS_TMP  WHERE  sid = :sid
}
COMM_GL_TRANSACTIONS_T1_COMMISSARY_AUDITS{
INSERT INTO COMMISSARY_AUDITS(module_name, txn_id, sid,create_datetime,modify_datetime,create_user_id) VALUES (:moduleName, :txnId, :sid,:createDatetime,:modifyDatetime,:createUserId)
}