C_AL{
SELECT AL.AREA_CODE, AL.NOMS_REGION_CODE, AL.AGENCY_LOCATION_TYPE FROM AGENCY_LOCATIONS AL WHERE AL.AGY_LOC_ID = :PROVIDER_PARTY_CODE
}

C_T{
SELECT T.AREA_CODE FROM TEAMS T WHERE T.TEAM_ID = :PROVIDER_PARTY_ID
}

 INSERT_INTO_COURSE_ACTIVITY_AREAS{
 insert into COURSE_ACTIVITY_AREAS (CRS_ACTY_ID, AREA_CODE , CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME) values (:CRS_ACTY_ID, :LV_AREA_CODE, :createUserId, CURRENT_TIMESTAMP, null)
 }
 