GET_PROG_SERV_PROF{
SELECT PROGRAM_PROFILE_TYPE, PROGRAM_PROFILE_CODE FROM PROGRAM_SERVICES_PROFILES WHERE PROGRAM_ID = :LV_PROGRAM_ID
}

INSERT_INTO_COURSE_ACTIVITY_PROFILES{
insert into COURSE_ACTIVITY_PROFILES ( CRS_ACTY_ID, PROGRAM_PROFILE_TYPE, PROGRAM_PROFILE_CODE, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME ) select :CRS_ACTY_ID, PROGRAM_PROFILE_TYPE, PROGRAM_PROFILE_CODE, :createUserId , CURRENT_TIMESTAMP, null from PROGRAM_SERVICES_PROFILES where PROGRAM_ID = :PROGRAM_ID
}
