GET_MODULE_NAME{
SELECT MODULE_NAME FROM TRUST_AUDITS WHERE TXN_ID = :TXN_ID
}

INSERT_INTO_FAR_CSLD_CURRENT_ACCTS_TXNS{
INSERT INTO FAR_CSLD_CURRENT_ACCTS_TXNS (CASELOAD_CURRENT_ACCOUNT_ID, CASELOAD_ID, ACCOUNT_CODE, ACCOUNT_PERIOD_ID, CURRENT_BALANCE, MODIFY_DATE, TXN_ID, TXN_ENTRY_SEQ, GL_ENTRY_SEQ, MODULE_NAME, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME) VALUES (:CASELOAD_CURRENT_ACCOUNT_ID, :CASELOAD_ID, :ACCOUNT_CODE, :ACCOUNT_PERIOD_ID, :CURRENT_BALANCE, :MODIFY_DATE, :TXN_ID, :TXN_ENTRY_SEQ, :GL_ENTRY_SEQ, :V_MODULE_NAME, :CREATEUSERID, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP)
}
