IMAGES_T1_INSERT_IMAGE_ORIGINALS {

INSERT INTO IMAGE_ORIGINALS (IMAGE_ID, CREATE_USER_ID, CREATE_DATETIME)
   SELECT :imageId, :createUserId,CURRENT_TIMESTAMP FROM DUAL
   WHERE NOT EXISTS (SELECT 'X' FROM IMAGE_ORIGINALS WHERE IMAGE_ID = :imageId)
   
}