OFFENDER_UNPAID_WORK_ADJ_TR1_GET{
SELECT OFFENDER_UNPAID_WORK_ADJ_ID,OFFENDER_BOOK_ID,SENTENCE_SEQ,ADJUSTMENT_DATE,ADJUSTMENT_MINUTES,ADJUSTMENT_TYPE,REASON_CODE,COMMENT_TEXT,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG FROM OFFENDER_UNPAID_WORK_ADJ WHERE OFFENDER_UNPAID_WORK_ADJ_ID=:offenderUnpaidWorkAdjId
}
OFFENDER_UNPAID_WORK_ADJ_TR1_V_NUMROWS{
SELECT count(*)  v_numrows FROM   reference_codes r WHERE  r.domain = 'PS_ADJ_REA' and    r.code   = :reasonCode
}