OFFENDER_EXTERNAL_MOVEMENT_T13_CLOSE_BOOKING_CUR{
SELECT COALESCE(CLOSE_CONTACT_FLAG, 'N') CLOSE_CONTACT_FLAG FROM MOVEMENT_REASONS WHERE MOVEMENT_TYPE = :MOVEMENT_TYPE AND MOVEMENT_REASON_CODE = :movementReasonCode
}
OFFENDER_EXTERNAL_MOVEMENT_T13_OFFENDER_BILLING_PROFILES{
update OFFENDER_BILLING_PROFILES set EFFECTIVE_DATE_END = date_trunc('D',:effectiveDateEnd::date), modify_datetime = current_timestamp, modify_user_id =:modifyUserId where OFFENDER_BOOKING_ID = :offenderBookingId and coalesce(EFFECTIVE_DATE_END,:effectiveDateEnd::date + 1) > :effectiveDateEnd
}