OFFENDER_MON_BENEFICIARIES_TJN_INSERT{
insert into OFFENDER_MON_BENEFICIARIES (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, BENEFICIARY_ID, MONTHLY_DEDUCTION_DATE, OFFENDER_DEDUCTION_ID , RECEIVED_AMOUNT, PERSON_ID, CORPORATE_ID , UNKNOWN_BEN_ID, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('INS', createUserId, current_timestamp, null, null, 0, :BENEFICIARYID, :MONTHLYDEDUCTIONDATE, :OFFENDERDEDUCTIONID , :RECEIVEDAMOUNT, :PERSONID, :CORPORATEID , :UNKNOWNBENID, current_timestamp, :createUserId, current_timestamp, :SEALFLAG )
}

OFFENDER_MON_BENEFICIARIES_TJN_UPDATE{
insert into OFFENDER_MON_BENEFICIARIES (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, BENEFICIARY_ID, MONTHLY_DEDUCTION_DATE , OFFENDER_DEDUCTION_ID, RECEIVED_AMOUNT, PERSON_ID , CORPORATE_ID, UNKNOWN_BEN_ID, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('UPD', createUserId, current_timestamp, null, null, 0, :BENEFICIARYID, :MONTHLYDEDUCTIONDATE, :OFFENDERDEDUCTIONID , :RECEIVEDAMOUNT, :PERSONID, :CORPORATEID , :UNKNOWNBENID, current_timestamp, :createUserId, current_timestamp, :SEALFLAG )
}

OFFENDER_MON_BENEFICIARIES_TJN_DELETE{
insert into OFFENDER_MON_BENEFICIARIES (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, BENEFICIARY_ID, MONTHLY_DEDUCTION_DATE , OFFENDER_DEDUCTION_ID, RECEIVED_AMOUNT, PERSON_ID , CORPORATE_ID, UNKNOWN_BEN_ID, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('DEL', createUserId, current_timestamp, null, null, 0, :BENEFICIARYID, :MONTHLYDEDUCTIONDATE, :OFFENDERDEDUCTIONID , :RECEIVEDAMOUNT, :PERSONID, :CORPORATEID , :UNKNOWNBENID, current_timestamp, :createUserId, current_timestamp, :SEALFLAG )
}
