 INSERT_INTO_OFFENDER_TEAM_ASSIGN_HTY{
 INSERT INTO OFFENDER_TEAM_ASSIGN_HTY ( OFFENDER_BOOK_ID, FUNCTION_TYPE, TEAM_ID, EXPIRY_DATE, ASSIGN_DATE, OFFENDER_TEAM_ASSIGN_HTY_ID, CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME ) VALUES ( :OFFENDER_BOOK_ID, :FUNCTION_TYPE, :TEAM_ID, SYSDATE(), :ASSIGNMENT_DATE, NEXTVAL('OFFENDER_TEAM_ASSIGN_HTY_ID'), CURRENT_TIMESTAMP , :CREATEUSERID , null )
 }