OFFENDER_SENT_CONDITIONS_T2_OFFENDER_SENT_CONDITIONS{
SELECT SENTENCE_SEQ,COMM_CONDITION_TYPE,COMM_CONDITION_CODE,START_DATE,CONDITION_STATUS,STATUS_DATE,OFFENDER_BOOK_ID,EXPIRY_DATE,LIST_SEQ,COMMENT_TEXT,CURFEW_START_TIME,CURFEW_END_TIME,CONDITION_RECOMMENDED_FLAG,GOVERNOR_CONDITION_FLAG,LENGTH,LENGTH_UNIT,DETAILS_TEXT,OFFENDER_SENT_CONDITION_ID,CURFEW_PROVIDER,EXCLUSION_CODE,RESIDENCY_ADDRESS_ID,MENTAL_HEALTH_PROVIDER,ALCOHOL_TREATMENT_PROVIDER,ATTENDANCE_CENTRE,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,CONDITION_REQUIRED_FLAG,CONDITION_APPLIED_FLAG,LONG_COMMENT_TEXT,APPOINTMENT_PERSON_NAME,REVIEW_CODE,SUPERVISOR_NAME,REPORT_TIME,REPORT_DATE,PERSONAL_RELATIONSHIP_FLAG,VEHICLE_DETAILS_FLAG,NON_ASSOCIATED_OFFENDERS,DRUG_TESTING,TERMINATION_DATE,STATUS_REASON_CODE,NO_RESIDENT_UNDER_AGE_OF,PROHIBITED_CONTACT,RESTRICTED_CHILD_AGE_OF,RESTRICTED_APPROVAL_PERSON,CURFEW_TAGGING_FLAG,OTHER_PROGRAM,NO_WORK_WITH_UNDER_AGE,NO_WORK_WITH_UNDER_AGE_OF,NO_ACCESS_TO_INTERNET,NO_USER_OF_COMPUTER,STATUS_UPDATE_REASON,STATUS_UPDATE_COMMENT,STATUS_UPDATE_DATE,STATUS_UPDATE_STAFF_ID,WORKFLOW_ID,PROGRAM_ID,ACTIVITY_CODE,COND_ACT_TYPE,ACTIVITY_STATUS,CATEGORY_TYPE,NON_ASSOCIATION_TEXT,FINANCIAL_TOTAL_AMOUNT,SEAL_FLAG,OBJECT_ID,OBJECT_TYPE,BOARD_ORDER_FLAG OFFENDER_SENT_CONDITIONS WHERE OFFENDER_SENT_CONDITION_ID=:offenderSentConditionId
}
OFFENDER_SENT_CONDITIONS_T2_PRG_METHOD_CUR{
SELECT program_methodFROM community_conditions WHERE comm_condition_type = :commConditionType AND comm_condition_code = :commConditionCode AND category_type = :categoryType
}
OFFENDER_SENT_CONDITIONS_T2_OBL_CUR{
 SELECT 'Y' FROM offender_prg_obligations WHERE offender_book_id = :offenderBookId AND offender_sent_condition_id = :offenderSentConditionId FOR UPDATE OF offender_book_id WAIT 1
}
COMMUNITY_CONDITIONS_LV_CNT{
SELECT COUNT ( * )  FROM community_conditions WHERE comm_condition_type = :commConditionType   AND comm_condition_code = :commConditionCode AND program_method IN ( 'DRR', 'SA', 'ACP' )
}
OFFENDER_PRG_OBLIGATIONS_LV_CNT{
SELECT COUNT ( * ) FROM offender_prg_obligations WHERE offender_sent_condition_id = :offenderSentCondition_id AND offender_book_id = :offenderBookId
}
OFFENDER_PRG_OBLIGATIONS_UPDATE{
UPDATE offender_prg_obligations SET LENGTH = :length,  length_unit = :lengthUnit  WHERE CURRENT OF :oblCur
}
OFFENDER_PRG_OBLIGATIONS_INSERT{
INSERT INTO offender_prg_obligations( offender_prg_obligation_id, offender_book_id, offender_sent_condition_id, sentence_seq, LENGTH,
  length_unit, referral_date, end_date, event_type,program_id ) SELECT offender_prg_obligation_id.NEXTVAL, :offenderBookId,:offenderSentConditionId, :sentenceSeq,:length, :lengthUnit, os.start_date, os.end_date, :eventType,:programId FROM offender_sentences os  WHERE os.offender_book_id = :offenderBookId  AND os.sentence_seq = :sentenceSeq 
}
