OFFENDER_BENEFICIARIES_TJN_INSERT{
insert into OFFENDER_BENEFICIARIES_JN (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, BENEFICIARY_ID, OFFENDER_DEDUCTION_ID, OFFENDER_ID , PERSON_ID, CORPORATE_ID, PRIORITY , AMOUNT, percent, OVERRIDE_AMOUNT , RECEIVED_AMOUNT, UNKNOWN_BEN_ID , COMMENT_TEXT, MONTHLY_AMOUNT, RECURSIVE_AMOUNT , TBD_FLAG, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('INS', :createUserId, current_timestamp, null, null, 0, :BENEFICIARYID, :OFFENDERDEDUCTIONID, :OFFENDERID , :PERSONID, :CORPORATEID, :PRIORITY , :AMOUNT, :PERCENT, :OVERRIDEAMOUNT , :RECEIVEDAMOUNT, :UNKNOWNBENID , :COMMENTTEXT, :MONTHLYAMOUNT, :RECURSIVEAMOUNT , :TBDFLAG, current_timestamp, :createUserId, current_timestamp, :SEALFLAG )
}

OFFENDER_BENEFICIARIES_TJN_UPDATE{
insert into OFFENDER_BENEFICIARIES_JN (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, BENEFICIARY_ID, OFFENDER_DEDUCTION_ID, OFFENDER_ID , PERSON_ID, CORPORATE_ID, PRIORITY , AMOUNT, percent, OVERRIDE_AMOUNT , RECEIVED_AMOUNT, MODIFY_USER_ID, UNKNOWN_BEN_ID , COMMENT_TEXT, MONTHLY_AMOUNT, RECURSIVE_AMOUNT , TBD_FLAG, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('UPD', :createUserId, current_timestamp, null, null, 0, :BENEFICIARYID, :OFFENDERDEDUCTIONID, :OFFENDERID , :PERSONID, :CORPORATEID, :PRIORITY , :AMOUNT, :PERCENT, :OVERRIDEAMOUNT , :RECEIVEDAMOUNT, :MODIFYUSERID, :UNKNOWNBENID , :COMMENTTEXT, :MONTHLYAMOUNT, :RECURSIVEAMOUNT , :TBDFLAG, current_timestamp, :createUserId, current_timestamp, :SEALFLAG )
}

OFFENDER_BENEFICIARIES_TJN_DELETE{
insert into OFFENDER_BENEFICIARIES_JN (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, BENEFICIARY_ID, OFFENDER_DEDUCTION_ID, OFFENDER_ID , PERSON_ID, CORPORATE_ID, PRIORITY , AMOUNT, percent, OVERRIDE_AMOUNT , RECEIVED_AMOUNT, MODIFY_USER_ID, UNKNOWN_BEN_ID , COMMENT_TEXT, MONTHLY_AMOUNT, RECURSIVE_AMOUNT , TBD_FLAG, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('DEL', :createUserId, current_timestamp, null, null, 0, :BENEFICIARYID, :OFFENDERDEDUCTIONID, :OFFENDERID , :PERSONID, :CORPORATEID, :PRIORITY , :AMOUNT, :PERCENT, :OVERRIDEAMOUNT , :RECEIVEDAMOUNT, :MODIFYUSERID, :UNKNOWNBENID , :COMMENTTEXT, :MONTHLYAMOUNT, :RECURSIVEAMOUNT , :TBDFLAG, current_timestamp, :createUserId, current_timestamp, :SEALFLAG )
}