OFFENDER_IND_SCHEDULES{
SELECT * FROM OFFENDER_IND_SCHEDULES WHERE EVENT_ID=:eventId
}
OFFENDER_IND_SCHEDULES_T2_EVENT_TYPE{
SELECT count(*)  FROM   Reference_codes WHERE  code =:eventType AND    DOMAIN IN ('MOVE_TYPE', 'INT_SCH_TYPE', 'EVENTS')
}
OFFENDER_IND_SCHEDULES_T2_EVENT_STATUS{
SELECT count(*) FROM   Reference_codes WHERE  code =:eventStatus AND    DOMAIN IN ('EVENT_STS' )
}