OFFENDER_CASE_IDENTIFIERS_T1_V_NUMROWS{
SELECT count(*) v_numrows FROM   offender_case_Identifiers  WHERE  Identifier_type = 'PNC' AND    identifier_No   = :IdentifierNo
}
OFFENDER_CASE_IDENTIFIERS_T1_GET{
SELECT IDENTIFIER_TYPE,CASE_ID,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,IDENTIFIER_NO,SEAL_FLAG FROM OFFENDER_CASE_IDENTIFIERS WHERE CASE_ID=:caseId
}