GET_OFFENDER_CASES_CASE_ID {
select CASE_ID,
OFFENDER_BOOK_ID,
CASE_INFO_NUMBER,
CASE_TYPE,
CASE_STATUS,
COMBINED_CASE_ID,
MODIFY_DATETIME,
MODIFY_USER_ID,
BEGIN_DATE,
AGY_LOC_ID,
CREATE_USER_ID,
CREATE_DATETIME,
CASE_INFO_PREFIX,
VICTIM_LIAISON_UNIT,
STATUS_UPDATE_REASON,
STATUS_UPDATE_COMMENT,
STATUS_UPDATE_DATE,
STATUS_UPDATE_STAFF_ID,
LIDS_CASE_NUMBER,
CASE_SEQ,
SEAL_FLAG from OFFENDER_CASES where CASE_ID=:CASE_ID
}

GET_PROFILE_VALUE_CASE_OBLIGN {
SELECT PROFILE_VALUE
     FROM SYSTEM_PROFILES
    WHERE PROFILE_TYPE = 'CLIENT'
      AND PROFILE_CODE = 'CASE_OBLIGN'
}

UPDATE_OFFENDER_DEDUCTIONS {
UPDATE OFFENDER_DEDUCTIONS
            SET INFORMATION_NUMBER = :CASE_INFO_NUMBER
          WHERE CASE_ID = :CASE_ID;
}

UPDATE_OFFENDER_PAYMENT_PLANS {
         UPDATE OFFENDER_PAYMENT_PLANS
            SET INFORMATION_NUMBER = :CASE_INFO_NUMBER
          WHERE CASE_ID = :CASE_ID
}