OFF_FEE_ACCOUNT_PROFILE_T2_INSERT_A{
insert into OFF_FEE_ACCOUNT_PROFILE_HTY (OFFENDER_FEE_ID, RECORD_DATETIME, AMOUNT, DAY_OF_MONTH, START_DATE, EFFECTIVE_DATE, EXPIRY_DATE, FEE_ACT_STATUS, STATUS_EFFECTIVE_DATE, COMMENT_TEXT, create_datetime, modify_datetime, create_user_id) 
values (:OFFENDER_FEE_ID, current_date, :AMOUNT, :DAY_OF_MONTH, :START_DATE, :EFFECTIVE_DATE, :EXPIRY_DATE, :FEE_ACT_STATUS, :STATUS_EFFECTIVE_DATE, :COMMENT_TEXT, current_timestamp, current_timestamp, :createUserId)
}

OFF_FEE_ACCOUNT_PROFILE_T2_INSERT_P{
insert into OFF_FEE_ACCOUNT_PROFILE_HTY (OFFENDER_FEE_ID, RECORD_DATETIME, AMOUNT, DAY_OF_MONTH, START_DATE, EFFECTIVE_DATE, EXPIRY_DATE, FEE_ACT_STATUS, STATUS_EFFECTIVE_DATE, create_datetime, modify_datetime, create_user_id) 
values (:OFFENDER_FEE_ID, current_date, :AMOUNT, :DAY_OF_MONTH, :START_DATE, :EFFECTIVE_DATE, :EXPIRY_DATE, :FEE_ACT_STATUS, :STATUS_EFFECTIVE_DATE, current_timestamp, current_timestamp, :createUserId)
}

OFF_FEE_ACCOUNT_PROFILE_T2_OLD_FEE_ACT_STATUS{
select fee_act_status from OFF_FEE_ACCOUNT_PROFILE where offender_fee_id = :offenderFeeId 
}