OFF_OBSERVATION_PERIODS_T1_OFF_OBSERVATION_PERIODS_OLD{
SELECT OFFENDER_BOOK_ID,OBS_PERIOD_ID,OBSERVATION_TYPE,START_DATE,END_REASON_CODE,END_DATE,STATUS_CODE,FREQUENCY,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG FROM OFF_OBSERVATION_PERIODS WHERE OFFENDER_BOOK_ID=:offenderBookId AND OBS_PERIOD_ID=:obsPeriodId
}
OFF_OBSERVATION_PERIODS_T1_AUTHCHECKCUR{
SELECT profile_value FROM system_profiles WHERE profile_type = 'CLIENT' AND profile_code = 'OO_USE_MOB'
}
