ORDERS_TJN_INSERT{
insert
	into
	ORDERS_JN (JN_OPERATION,
	JN_ORACLE_USER,
	JN_DATETIME,
	JN_NOTES,
	JN_APPLN,
	JN_SESSION,
	ORDER_ID,
	OFFENDER_BOOK_ID,
	CASE_ID ,
	COURT_DATE,
	ORDER_TYPE,
	ISSUING_AGY_LOC_ID ,
	COURT_INFO_ID,
	ORDER_STATUS,
	CREATE_USER_ID ,
	DUE_DATE,
	COURT_SERIOUSNESS_LEVEL ,
	ORDER_SERIOUSNESS_LEVEL,
	REQUEST_DATE,
	STAFF_WORK_ID ,
	EVENT_ID,
	COMPLETE_DATE,
	COMPLETE_STAFF_ID ,
	INTERVENTION_TIER_CODE,
	NON_REPORT_FLAG,
	CPS_RECEIVED_DATE ,
	COMMENT_TEXT,
	ISSUE_DATE,
	MESSAGE_ID ,
	WORKFLOW_ID,
	OFFENDER_PROCEEDING_ID,
	SEAL_FLAG )
values ('INS',
:createUserId ,
current_timestamp,
null,
null,
0,
:orderId,
:offenderBookId,
:caseId ,
:courtDate,
:orderType,
:issuingAgyLocId ,
:courtInfoId,
:orderStatus,
:createUserId ,
:dueDate,
:courtSeriousnessLevel ,
:orderSeriousnessLevel,
:requestDate,
:staffWorkId ,
:eventId,
:completeDate,
:completeStaffId ,
:interventionTierCode,
:nonReportFlag,
:cpsReceivedDate ,
:commentText,
:issueDate,
:messageId ,
:workflowId,
:offenderProceedingId,
:sealFlag )
}

ORDERS_TJN_UPDATE{
insert
	into
	ORDERS_JN (JN_OPERATION,
	JN_ORACLE_USER,
	JN_DATETIME,
	JN_NOTES,
	JN_APPLN,
	JN_SESSION,
	ORDER_ID,
	OFFENDER_BOOK_ID,
	CASE_ID ,
	COURT_DATE,
	ORDER_TYPE,
	ISSUING_AGY_LOC_ID ,
	COURT_INFO_ID,
	ORDER_STATUS,
	CREATE_USER_ID ,
	DUE_DATE,
	COURT_SERIOUSNESS_LEVEL ,
	ORDER_SERIOUSNESS_LEVEL,
	REQUEST_DATE,
	STAFF_WORK_ID ,
	EVENT_ID,
	COMPLETE_DATE,
	COMPLETE_STAFF_ID ,
	INTERVENTION_TIER_CODE,
	NON_REPORT_FLAG,
	CPS_RECEIVED_DATE ,
	COMMENT_TEXT,
	ISSUE_DATE,
	MESSAGE_ID ,
	WORKFLOW_ID,
	OFFENDER_PROCEEDING_ID,
	SEAL_FLAG )
values ('UPD',
:createUserId ,
current_timestamp,
null,
null,
0,
:orderId,
:offenderBookId,
:caseId ,
:courtDate,
:orderType,
:issuingAgyLocId ,
:courtInfoId,
:orderStatus,
:createUserId ,
:dueDate,
:courtSeriousnessLevel ,
:orderSeriousnessLevel,
:requestDate,
:staffWorkId ,
:eventId,
:completeDate,
:completeStaffId ,
:interventionTierCode,
:nonReportFlag,
:cpsReceivedDate ,
:commentText,
:issueDate,
:messageId ,
:workflowId,
:offenderProceedingId,
:sealFlag )

}

ORDERS_TJN_DELETE{
insert
	into
	ORDERS_JN (JN_OPERATION,
	JN_ORACLE_USER,
	JN_DATETIME,
	JN_NOTES,
	JN_APPLN,
	JN_SESSION,
	ORDER_ID,
	OFFENDER_BOOK_ID,
	CASE_ID ,
	COURT_DATE,
	ORDER_TYPE,
	ISSUING_AGY_LOC_ID ,
	COURT_INFO_ID,
	ORDER_STATUS,
	CREATE_USER_ID ,
	DUE_DATE,
	COURT_SERIOUSNESS_LEVEL ,
	ORDER_SERIOUSNESS_LEVEL,
	REQUEST_DATE,
	STAFF_WORK_ID ,
	EVENT_ID,
	COMPLETE_DATE,
	COMPLETE_STAFF_ID ,
	INTERVENTION_TIER_CODE,
	NON_REPORT_FLAG,
	CPS_RECEIVED_DATE ,
	COMMENT_TEXT,
	ISSUE_DATE,
	MESSAGE_ID ,
	WORKFLOW_ID,
	OFFENDER_PROCEEDING_ID,
	SEAL_FLAG )
values ('DEL',
:createUserId ,
current_timestamp,
null,
null,
0,
:orderId,
:offenderBookId,
:caseId ,
:courtDate,
:orderType,
:issuingAgyLocId ,
:courtInfoId,
:orderStatus,
:createUserId ,
:dueDate,
:courtSeriousnessLevel ,
:orderSeriousnessLevel,
:requestDate,
:staffWorkId ,
:eventId,
:completeDate,
:completeStaffId ,
:interventionTierCode,
:nonReportFlag,
:cpsReceivedDate ,
:commentText,
:issueDate,
:messageId ,
:workflowId,
:offenderProceedingId,
:sealFlag )
}









