PRINT_RECEIPTS_TMP_TJN_INSERT{
insert into PRINT_RECEIPTS_TMP_JN (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, MODULE_NAME, TXN_ID, OFFENDER_ID , RECEIPT_NUMBER, SESSION_ID, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('INS', :createUserId, current_timestamp, null, null, 0, :MODULENAME, :TXNID, :OFFENDERID , :RECEIPTNUMBER, :SESSIONID, current_timestamp, :createUserId, current_timestamp, :SEALFLAG)
}

PRINT_RECEIPTS_TMP_TJN_UPDATE{
insert into PRINT_RECEIPTS_TMP_JN (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, MODULE_NAME , TXN_ID, OFFENDER_ID, RECEIPT_NUMBER , SESSION_ID, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('UPD', :createUserId, current_timestamp, null, null, 0, :MODULENAME, :TXNID, :OFFENDERID , :RECEIPTNUMBER, :SESSIONID, current_timestamp, :createUserId, current_timestamp, :SEALFLAG)
}

PRINT_RECEIPTS_TMP_TJN_DELETE{
insert into PRINT_RECEIPTS_TMP_JN (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, MODULE_NAME , TXN_ID, OFFENDER_ID, RECEIPT_NUMBER , SESSION_ID, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) 
values ('DEL', createUserId, current_timestamp, null, null, 0, :MODULENAME, :TXNID, :OFFENDERID , :RECEIPTNUMBER, :SESSIONID, current_timestamp, :createUserId, current_timestamp, :SEALFLAG)
}