GET_PROFILE_VALUE_FROM_SYSTEM_PROFILES {
SELECT PROFILE_VALUE FROM SYSTEM_PROFILES  WHERE PROFILE_TYPE = 'SYS' AND PROFILE_CODE = 'Q_CLUSTER_ID'
}

GET_STAFF_ID_LV_PROFILE_VALUE_MOD {
SELECT  MOD(:STAFF_ID::NUMERIC ,:LV_PROFILE_VALUE::NUMERIC) + 1  FROM DUAL
}
