GET_COUNT_ADDRESSES {
SELECT COUNT(*) FROM   ADDRESSES  WHERE  OWNER_CLASS = 'STF' AND    OWNER_ID = :STAFF_ID
}
GET_COUNT_PHONES {
SELECT COUNT(*)  FROM   PHONES WHERE  OWNER_CLASS = 'STF' AND    OWNER_ID = :STAFF_ID
}
    
GET_COUNT_INTERNET_ADDRESSES {
SELECT COUNT(*) FROM   INTERNET_ADDRESSES WHERE  OWNER_CLASS = 'STF' AND    OWNER_ID = :STAFF_ID
}