STOCK_LOCATIONS_TJN_STOCK_LOCATIONS{
SELECT CASELOAD_ID,STOCK_LOC_ID,DESCRIPTION,LIST_SEQ,UPDATE_ALLOWED_FLAG,EXPIRY_DATE,ACTIVE_FLAG,MODIFIED_USER_ID,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG FROM STOCK_LOCATIONS WHERE CASELOAD_ID =:caseloadId AND STOCK_LOC_ID=:stockLocId
}
STOCK_LOCATIONS_TJN_INS{
INSERT INTO STOCK_LOCATIONS_JN ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, CASELOAD_ID, STOCK_LOC_ID, DESCRIPTION, LIST_SEQ, UPDATE_ALLOWED_FLAG, EXPIRY_DATE, ACTIVE_FLAG, MODIFIED_USER_ID, CREATE_USER_ID , MODIFY_USER_ID, SEAL_FLAG ) VALUES ('INS', :createUserId, :createDatetime, NULL, NULL, 0, :caseloadId, :stockLocId, :description, :listSeq, :updateAllowedFlag, :expiryDate, :activeFlag, :modifiedUserId, :createUserId, :modifyUserId, :sealFlag )
}
STOCK_LOCATIONS_TJN_UPD{
INSERT INTO STOCK_LOCATIONS_JN (JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, CASELOAD_ID, STOCK_LOC_ID , DESCRIPTION, LIST_SEQ, UPDATE_ALLOWED_FLAG, EXPIRY_DATE, ACTIVE_FLAG, MODIFIED_USER_ID, CREATE_USER_ID , MODIFY_USER_ID, SEAL_FLAG ) VALUES ('UPD', :createUserId, :createDatetime, NULL, NULL, 0, :caseloadId, :stockLocId, :description, :listSeq, :updateAllowedFlag, :expiryDate, :activeFlag, :modifiedUserId, :createUserId, :modifyUserId, :sealFlag )
}
STOCK_LOCATIONS_TJN_DEL{
 INSERT INTO STOCK_LOCATIONS_JN ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION, CASELOAD_ID, STOCK_LOC_ID , DESCRIPTION, LIST_SEQ, UPDATE_ALLOWED_FLAG, EXPIRY_DATE, ACTIVE_FLAG, MODIFIED_USER_ID, CREATE_USER_ID , MODIFY_USER_ID, SEAL_FLAG )VALUES ('UPD', :createUserId, :createDatetime, NULL, NULL, 0  , :caseloadId, :stockLocId, :description, :listSeq, :updateAllowedFlag , :expiryDate, :activeFlag, :modifiedUserId, :createUserId, :modifyUserId, :sealFlag )
}
