SUBSTANCE_TESTS_TIEQ_SUBSTANCE_TESTS{
SELECT  OFFENDER_BOOK_ID,SAMPLE_SEQ,TEST_SEQ,DATE_TESTED,TESTED_BY,WITNESS,RESULTS,DISPOSITION,COMMENT_TEXT,TIME_TESTED,SUBTANCE_TEST_TYPE,TEST_NUMBER,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG FROM SUBSTANCE_TESTS WHERE OFFENDER_BOOK_ID=:offenderBookId AND SAMPLE_SEQ=:sampleSeq AND TEST_SEQ=:testSeq
}
SUBSTANCE_TESTS_TIEQ_V_SUB_CUR{
SELECT substance FROM substance_samples WHERE offender_book_id = :offenderBookId AND sample_seq = :sampleSeq
}