V_COURSE_PHASE_OFFERINGS_TU_L_CRS_ACTY_ID{
SELECT NEXTVAL('CRS_ACTY_ID')
}
V_COURSE_PHASE_OFFERINGS_TU_COURSE_ACTIVITIES_INSERT{
insert into COURSE_ACTIVITIES(CRS_ACTY_ID, COURSE_CLASS, PARENT_CRS_ACTY_ID, PROGRAM_ID, LIST_SEQ, DESCRIPTION, ACTIVE_FLAG, PROVIDER_PARTY_CLASS, PROVIDER_PARTY_ID, PROVIDER_PARTY_CODE, CAPACITY, NO_OF_SESSIONS, SESSION_LENGTH, SERVICES_ADDRESS_ID, INTERNAL_LOCATION_ID, COURSE_ACTIVITY_TYPE, CASELOAD_TYPE, CREATE_DATETIME, MODIFY_DATETIME, CREATE_USER_ID, modify_user_id) values(:crsActyId, 'CRS_PH', :parentCrsActyId, :programId, :listSeq, :description, 'Y', :providerPartyClass, :providerPartyId, :providerPartyCode, :capacity, :noOfSessions, :sessionLength, :servicesAddressId, :internalLocationId, :courseActivityType, :caseloadType, CURRENT_TIMESTAMP, null, :createUserId, null )
}
V_COURSE_PHASE_OFFERINGS_TU_COURSE_ACTIVITIES_UPDATE{
UPDATE COURSE_ACTIVITIES SET  SCHEDULE_START_DATE  = :scheduleStartDate, SCHEDULE_END_DATE = :scheduleEndDate,COMMENT_TEXT  = :commentText, CAPACITY = :capacity,NO_OF_SESSIONS  = :noOfSessions,SESSION_LENGTH = :sessionLength,SERVICES_ADDRESS_ID  = :servicesAddressId, PLACEMENT_CORPORATE_ID  = :placementCorporateId,CASELOAD_TYPE  = :caseloadType,INTERNAL_LOCATION_ID = :internalLocationId,MODIFY_DATETIME=CURRENT_TIMESTAMP,MODIFY_USER_ID=:modifyUserId WHERE  CRS_ACTY_ID = :crsActyId
}
V_COURSE_PHASE_OFFERINGS_TU_COURSE_ACTIVITY_AREAS_DELETE{
DELETE FROM COURSE_ACTIVITY_AREAS WHERE  CRS_ACTY_ID = :crsActyId
}
V_COURSE_PHASE_OFFERINGS_TU_COURSE_ACTIVITIES_DELETE{
DELETE FROM COURSE_ACTIVITIES WHERE  CRS_ACTY_ID = :crsActyId
}
V_COURSE_PHASE_OFFERINGS_TU_COURSE_ACTIVITIES_UPDATE3{
UPDATE COURSE_ACTIVITIES SET    SCHEDULE_START_DATE  = :scheduleStartDate, SCHEDULE_END_DATE    = :scheduleEndDate, COMMENT_TEXT   = :commentText, Capacity   = :capacity, No_Of_Sessions  = :noOfSessions,   Session_Length = :sessionLength, services_Address_id  = :servicesAddressId,  placement_corporate_ID  = :placementCorporateId, caseload_type  = :caseloadType, Internal_location_ID = :internalLocationId,modify_datetime=:modifyDatetime,modify_user_id=:modifyUserId WHERE  CRS_ACTY_ID   = :coursePhaseId
}
V_COURSE_PHASE_OFFERINGS_TU_COURSE_ACTIVITIES_UPDATE2{
UPDATE COURSE_ACTIVITIES SET  SERVICES_ADDRESS_ID  = :servicesAddressId, INTERNAL_LOCATION_ID = :internalLocationId,MODIFY_DATETIME=CURRENT_TIMESTAMP,MODIFY_USER_ID=:modifyUserId WHERE PARENT_CRS_ACTY_ID = :parentCrsActyId
}
DELETE_COURSE_PHASE_MODULES{
DELETE FROM v_course_modules WHERE COURSE_PHASE_ID = :coursePhaseId
}
GET_OLD_VALUES_V_COURSE_PHASE_OFFERINGS{
SELECT * FROM V_COURSE_PHASE_OFFERINGS  WHERE COURSE_ID = :courseId AND PROGRAM_PHASE_ID = :programPhaseId
}
OCMSVACP_CONSTRAINT_VALIDATIONS{
select distinct AC1.TABLE_NAME CHILD_TABLE
from 
  ALL_CONSTRAINTS AC1,ALL_CONSTRAINTS AC2
where
  upper(AC1.CONSTRAINT_NAME) =upper(:CONSTRAINTNAME) and
  upper(AC1.TABLE_NAME) = 'COURSE_ACTIVITY_PARTIES' and
  AC1.CONSTRAINT_TYPE = 'f' and
  AC2.CONSTRAINT_NAME = AC1.R_CONSTRAINT_NAME and
  AC2.OWNER = AC1.R_OWNER and
  upper(AC2.CONSTRAINT_TYPE) in ('P', 'U')
  }
