V_OFFENDER_COURSE_EVENTS_TU_INSERT{
insert into OFFENDER_COURSE_ATTENDANCES(EVENT_ID, event_class, offender_book_id, event_date, off_prgref_id, event_status, Reference_id, crs_sch_id, crs_appt_id, crs_acty_id, event_sub_type, event_type, Start_Time, End_Time, in_time, out_time, event_outcome, agy_loc_ID, comment_text, piece_work, performance_code, outcome_reason_code, to_agy_loc_id, to_internal_location_id, to_address_id, engagement_code, understanding_code, credited_hours, agreed_travel_hour, behaviour_code, supervisor_staff_id, unexcused_absence_flag, direction_code, create_datetime, modify_datetime, create_user_id, modify_user_id, session_no) values (:eventId, :eventClass, :offenderBookId, :eventDate, :offPrgrefId, :eventStatus, :referenceId, :crsSchId, :crsApptId, :crsActyId, :eventSubType, :eventType, :startTime, :endTime, :inTime, :outTime, :eventOutcome, :agyLocId, :commentText, :pieceWork, :performanceCode, :outcomeReasonCode, :toAgyLocId, :toInternalLocationId, :toAddressId, :engagementCode, :understandingCode, :creditedHours, :agreedTravelHour, :behaviourCode, :supervisorStaffId, :unexcusedAbsenceFlag, :directionCode, current_timestamp, null , :createUserId, null , :sessionNo)
}
V_OFFENDER_COURSE_EVENTS_TU_UPDATE{
update OFFENDER_COURSE_ATTENDANCES set Event_Status =:eventStatus, Event_date =:eventDate, Start_Time =:startTime, End_Time =:endTime, in_Time =:inTime, Out_Time =:outTime, crs_acty_id =:crsActyId, comment_text =:commentText, Piece_work =:pieceWork, performance_code =:performanceCode, event_outcome =:eventOutcome, off_prgref_id =:offPrgrefId, crs_sch_id =:crsSchId, unexcused_absence_flag =:unexcusedAbsenceFlag, outcome_reason_code =:outcomeReasonCode, supervisor_staff_id =:supervisorStaffId, to_agy_loc_id =:toAgyLocId, to_address_id =:toAddressId, to_internal_location_id =:toInternalLocationId, engagement_code =:engagementCode, understanding_code =:understandingCode, credited_hours =:creditedHours, agreed_travel_hour =:agreedTravelHour, behaviour_code =:behaviourCode, direction_code =:directionCode, crs_appt_id =:crsApptId, modify_datetime =current_timestamp, modify_user_id =:modifyUserId ,sms_schedule_hours_before=:smsScheduleHoursBefore, email_schedule_hours_before=:emailScheduleHoursBefore, email_flag=:emailFlag, sms_flag=:smsFlag where event_id =:eventId
}

V_OFFENDER_COURSE_EVENTS_GET_EVENT_ID {
SELECT nextval('Event_ID') FROM DUAL;
}
