
OUMBMARK_AIWPBOOKMARKS_FIND_IWP_BOOKMARKS {
 	SELECT BOOKMARK_NAME, ACTIVE_FLAG,BOOKMARK_TYPE ,DESCRIPTION, SQL_TEXT, DATE_CREATED ,USER_CREATED ,CREATE_DATETIME, CREATE_USER_ID ,MODIFY_DATETIME, MODIFY_USER_ID, EXPIRY_DATE,SQL_VERIFIED_FLAG, SEAL_FLAG  FROM IWP_BOOKMARKS  ORDER BY  ACTIVE_FLAG DESC, BOOKMARK_NAME ASC
}
OUMBMARK_AIWPBOOKMARKS_INSERT_IWP_BOOKMARKS {
insert into IWP_BOOKMARKS(BOOKMARK_NAME, ACTIVE_FLAG, BOOKMARK_TYPE , DESCRIPTION, SQL_TEXT, DATE_CREATED , USER_CREATED , CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME, EXPIRY_DATE, SQL_VERIFIED_FLAG ) values(:bookmarkName, :activeFlag, :bookmarkType , :description, :sqlText, :dateCreated , :userCreated , current_timestamp, :createUserId , NULL, :expiryDate, :sqlVerifiedFlag)
}

OUMBMARK_AIWPBOOKMARKS_UPDATE_IWP_BOOKMARKS {
update IWP_BOOKMARKS set BOOKMARK_NAME =:bookmarkName, ACTIVE_FLAG =:activeFlag, BOOKMARK_TYPE =:bookmarkType , DESCRIPTION =:description, SQL_TEXT =:sqlText, DATE_CREATED =:dateCreated , USER_CREATED =:userCreated, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID =:modifyUserId, EXPIRY_DATE =:expiryDate, SQL_VERIFIED_FLAG =:sqlVerifiedFlag where BOOKMARK_NAME =:bookmarkName 
}

OUMBMARK_AIWPPARAMETERS_FIND_IWP_BOOKMARK_PARAMETERS {
 	SELECT  PARAMETER_NAME, PARAMETER_TYPE, DESCRIPTION ,BOOKMARK_NAME, DATE_CREATED, USER_CREATED, PARAMETER_DATA_TYPE, CREATE_DATETIME ,CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, ACTIVE_FLAG, SEAL_FLAG,MODULE_BLOCK_CODE,FIELD  FROM IWP_BOOKMARK_PARAMETERS where BOOKMARK_NAME=:BOOKMARKNAME ORDER BY BOOKMARK_NAME ASC
}
OUMBMARK_AIWPPARAMETERS_INSERT_IWP_BOOKMARK_PARAMETERS {
 insert into IWP_BOOKMARK_PARAMETERS(USER_CREATED,PARAMETER_NAME, PARAMETER_TYPE, DESCRIPTION , BOOKMARK_NAME, PARAMETER_DATA_TYPE, CREATE_DATETIME , CREATE_USER_ID, MODIFY_DATETIME,MODULE_BLOCK_CODE,FIELD) values(:userCreated,:parameterName, :parameterType, :description , :bookmarkName, :parameterDataType, current_timestamp , :createUserId, NULL,:moduleBlockCode,:field) 
}

OUMBMARK_AIWPPARAMETERS_UPDATE_IWP_BOOKMARK_PARAMETERS {
 update IWP_BOOKMARK_PARAMETERS set PARAMETER_TYPE =:parameterType, DESCRIPTION =:description, DATE_CREATED =:dateCreated, USER_CREATED =:userCreated, PARAMETER_DATA_TYPE =:parameterDataType, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID =:modifyUserId, ACTIVE_FLAG =:activeFlag, SEAL_FLAG = :sealFlag,MODULE_BLOCK_CODE=:moduleBlockCode,FIELD=:field  where BOOKMARK_NAME =:bookmarkName and PARAMETER_NAME =:parameterName 
}


OUMBMARK_A_IWP_BOOKMARKS_ONCHECKDELETEMASTER {
	SELECT * FROM IWP_BOOKMARKS WHERE BOOKMARK_NAME = :BOOKMARKNAME
}

OUMBMARK_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OUMBMARK_CHECK_FOR_MAPPING_ {
	SELECT 1 FROM IWP_PARAMETER_MAPPINGS A WHERE A.BOOKMARK_NAME = :BOOKMARKNAME
}

OUMBMARK_DUPLICATE_BOOKMARK_NAME {
	 IS SELECT 'Y' FROM IWP_BOOKMARKS WHERE IWP_BOOKMARKS.BOOKMARK_NAME = P_BOOKMARK_NAME
}
OUMBMARK_OMS_MISCELLANEOUS_STAFF_NAME{

SELECT  Last_Name||', '||First_Name
        
        FROM  STAFF_MEMBERS
        WHERE User_ID  = :P_USER_ID
}
OUMBMARK_IWP_BOOKMARKS_SQL_TEXT{
SELECT 1 FROM IWP_BOOKMARKS WHERE SQL_TEXT =:SQLTEXT
}
OUMBMARK_GET_USER_NAME {
SELECT USER_ID FROM STAFF_MEMBERS WHERE USER_ID=:USER_Id
}
OUMBMARK_INSERT_IWP_OUTPARAMS {
INSERT INTO IWP_BOOKMARK_OUT_PARAMETERS(PARAMETER_NAME, PARAMETER_DESC, BOOKMARK_NAME, CREATE_DATETIME , CREATE_USER_ID) values(:parameterName, :parameterDesc, :bookmarkName, current_timestamp , :createUserId)
}
OUMBMARK_GET_IWP_BOOKMARK_OUT_PARAMETERS {
select PARAMETER_NAME, PARAMETER_DESC, BOOKMARK_NAME, CREATE_DATETIME , CREATE_USER_ID from IWP_BOOKMARK_OUT_PARAMETERS WHERE BOOKMARK_NAME = :bookmarkName 
}
OUMBMARK_DELETE_IWP_BOOKMARK_OUT_PARAMETERS {
DELETE FROM IWP_BOOKMARK_OUT_PARAMETERS WHERE BOOKMARK_NAME = :bookmarkName
}

OUMBMARK_UPDATE_IWP_COMPOSITE_BOOKMARKS {
UPDATE IWP_BOOKMARK_OUT_PARAMETERS set  PARAMETER_DESC =:parameterDesc, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID =:modifyUserId where BOOKMARK_NAME =:bookmarkName and PARAMETER_NAME =:parameterName
}

OUMBMARK_GET_IWP_COMPOSITE_BOOKMARKS{ 
select * from IWP_COMPOSITE_BOOKMARKS WHERE BOOKMARK_NAME = :bookmarkName 
}

OUMBMARK_GET_IWP_BOOKMARK{ 
SELECT SQL_TEXT FROM IWP_BOOKMARKS WHERE BOOKMARK_NAME=:bookmarkName 
}

OUMBMARK_DELETE_IWP_COMPOSITE_BOOKMARK{ 
DELETE FROM IWP_COMPOSITE_BOOKMARKS WHERE BOOKMARK_NAME =:bookmarkName
}