
OCUSREPS_OMSMODULES_FIND_OMS_MODULES {
 	SELECT MODULE_NAME ,DESCRIPTION ,MODULE_TYPE ,PRINT_FORMAT_CODE ,PREVIEW_FLAG ,DEFAULT_COPY ,APPLN_CODE ,HELP_DIRECTORY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ,OUTPUT_TYPE   FROM OMS_MODULES
}
OCUSREPS_OMSMODULES_INSERT_OMS_MODULES {
	INSERT INTO OMS_MODULES(MODULE_NAME ,DESCRIPTION ,MODULE_TYPE ,PRINT_FORMAT_CODE ,PREVIEW_FLAG ,DEFAULT_COPY ,APPLN_CODE ,HELP_DIRECTORY ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ,OUTPUT_TYPE ) VALUES(:moduleName ,:description ,:moduleType ,:printFormatCode ,:previewFlag ,:defaultCopy ,:applnCode ,:helpDirectory ,:createDatetime ,:createUserId ,:modifyDatetime ,:modifyUserId ,:sealFlag ,:outputType )
}

OCUSREPS_OMSMODULES_UPDATE_OMS_MODULES {
	UPDATE OMS_MODULES set MODULE_NAME  = :moduleName ,DESCRIPTION  = :description ,MODULE_TYPE  = :moduleType ,PRINT_FORMAT_CODE  = :printFormatCode ,PREVIEW_FLAG  = :previewFlag ,DEFAULT_COPY  = :defaultCopy ,APPLN_CODE  = :applnCode ,HELP_DIRECTORY  = :helpDirectory ,CREATE_DATETIME  = :createDatetime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = :modifyDatetime ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag ,OUTPUT_TYPE  = :outputType /* where */
}

OCUSREPS_OMSMODULES_DELETE_OMS_MODULES { 
	DELETE FROM OMS_MODULES/* where */
}


OCUSREPS_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
