
OTUACODE_ACCODE_FIND_ACCOUNT_CODES {
 	SELECT  REC_ACCOUNT_CODE, ACCOUNT_CODE, ACCOUNT_NAME, POSTING_STATUS_FLAG, ACCOUNT_TYPE, SUB_ACCOUNT_TYPE, TXN_POSTING_TYPE, ALL_CASELOAD_FLAG, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, CASELOAD_TYPE, PARENT_ACCOUNT_CODE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG FROM ACCOUNT_CODES 
}

OTUACODE_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
