
OCICBENE_VCORP_FIND_CORPORATE_ADDRESS_V {
 	-- SELECT CORPORATE_ID ,CORPORATE_NAME ,CASELOAD_ID ,CONTACT_PERSON_NAME ,SUSPENDED_DATE ,SUSPENDED_FLAG ,ADDRESS_ID ,ADDRESS_TYPE ,OWNER_CLASS ,OWNER_ID ,OWNER_CODE ,OWNER_SEQ ,SUITE_NUMBER ,STREET_NUMBER ,STREET ,STREET_DIRECTION ,ZIP_POSTAL_CODE ,CITY_CODE ,PROV_STATE_CODE ,COUNTRY_CODE ,CITY_DESC ,PROV_STATE_DESC ,COUNTRY_DESC ,MAIL_CARE_OF ,PRIMARY_FLAG ,MAIL_FLAG  
 	   --FROM CORPORATE_ADDRESS_V  CORPORATE_ADDRESS_V
  	 SELECT CORPORATE_ID ,CORPORATE_NAME ,CASELOAD_ID ,CONTACT_PERSON_NAME ,SUSPENDED_DATE ,SUSPENDED_FLAG ,ADDRESS_ID ,ADDRESS_TYPE ,OWNER_CLASS ,OWNER_ID ,OWNER_CODE ,OWNER_SEQ ,SUITE_NUMBER ,STREET_NUMBER ,STREET ,STREET_DIRECTION ,ZIP_POSTAL_CODE ,CITY_CODE ,PROV_STATE_CODE ,COUNTRY_CODE ,CITY_DESC ,PROV_STATE_DESC ,COUNTRY_DESC ,MAIL_CARE_OF ,PRIMARY_FLAG ,MAIL_FLAG  
 	FROM CORPORATE_ADDRESS_V  
}
OCICBENE_OFFBNC_FIND_OFFENDER_BENEFICIARIES {
 	 SELECT BENEFICIARY_ID ,OFFENDER_DEDUCTION_ID ,OFFENDER_ID ,PERSON_ID ,CORPORATE_ID ,PRIORITY ,AMOUNT ,PERCENT ,OVERRIDE_AMOUNT ,RECEIVED_AMOUNT ,MODIFY_USER_ID ,MODIFY_DATETIME ,UNKNOWN_BEN_ID ,COMMENT_TEXT ,MONTHLY_AMOUNT ,RECURSIVE_AMOUNT ,TBD_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG   
 	  FROM OFFENDER_BENEFICIARIES   WHERE   CORPORATE_ID = :CORPORATE_ID ORDER BY OFFENDER_DEDUCTION_ID DESC
 	
}
OCICBENE_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OCICBENE_CGFKCHK_OFF_BNC_OFF_BNC_OFF_D_ {
	SELECT OFF_DED.OFFENDER_ID ,OFF_DED.DEDUCTION_TYPE ,OFF_DED.INFORMATION_NUMBER ,OFF_DED.CASELOAD_ID ,OFF_DED.DEDUCTION_PERCENTAGE ,OFF_DED.PROCESS_PRIORITY_NUMBER ,OFF_DED.EFFECTIVE_DATE ,OFF_DED.MODIFY_DATE ,OFF_DED.MODIFY_USER_ID ,OFF_DED.FIFO_FLAG ,OFF_DED.PAYEE_PERSON_ID ,OFF_DED.PAYEE_CORPORATE_ID ,OFF_DED.MAX_MONTHLY_AMOUNT ,OFF_DED.MAX_TOTAL_AMOUNT ,OFF_DED.DEDUCTION_AMOUNT ,OFF_DED.ADJUSTMENT_REASON_CODE ,OFF_DED.ADJUSTMENT_AMOUNT ,OFF_DED.ADJUSTMENT_TXN_ID ,OFF_DED.ADJUSTMENT_TEXT ,OFF_DED.COMMENT_TEXT ,OFF_DED.ADJUSTMENT_USER_ID ,OFF_DED.DEDUCTION_PRIORITY ,OFF_DED.DEDUCTION_STATUS ,OFF_DED.CREDIT_LIMIT ,OFF_DED.PAY_DEDUCTION_FLAG ,OFF_DED.MAX_RECURSIVE_AMOUNT FROM   OFFENDER_DEDUCTIONS OFF_DED WHERE  OFF_DED.OFFENDER_DEDUCTION_ID = :OFFENDERDEDUCTIONID
}

OCICBENE_OFF_BNC_POSTQUERY {
SELECT OFF.OFFENDER_ID_DISPLAY OFFENDER_ID_DISPLAY, OFF.LAST_NAME || ', ' || OFF.FIRST_NAME LAST_NAME
           FROM OFFENDERS OFF, OFFENDER_BOOKINGS OFF_BKG
          WHERE OFF.ROOT_OFFENDER_ID = :OFFENDER_ID
            AND OFF.ROOT_OFFENDER_ID = OFF_BKG.ROOT_OFFENDER_ID
            AND OFF.OFFENDER_ID = OFF_BKG.OFFENDER_ID
            AND OFF_BKG.OFFENDER_BOOK_ID = (SELECT MAX (OFFENDER_BOOK_ID)
                                              FROM OFFENDER_BOOKINGS OFF_BKG1
                                             WHERE OFF_BKG1.ROOT_OFFENDER_ID = OFF_BKG.ROOT_OFFENDER_ID)
  }
OCICBENE_OFF_BNC_POPULATE_WRITE_OFF {
     --SELECT DEDUCTION_TYPE, ADJUSTMENT_REASON_CODE, NVL(ADJUSTMENT_AMOUNT, 0) ADJUSTMENT_AMOUNT
     --FROM OFFENDER_DEDUCTIONS
     --WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
       SELECT DEDUCTION_TYPE, ADJUSTMENT_REASON_CODE, coalesce(ADJUSTMENT_AMOUNT, 0) ADJUSTMENT_AMOUNT
        FROM OFFENDER_DEDUCTIONS
       WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
}
OCICBENE_OFF_BNC_CHK_DED_CAT {
SELECT deduction_category
     FROM deduction_types
    WHERE deduction_type = :deduction_type
    }
    
OCICBENE_OFF_BNC_GET_MON_AMT {
--SELECT NVL (SUM (DECODE (TXN_POST_USAGE, 'CR', TXN_ENTRY_AMOUNT, 'DR', TXN_ENTRY_AMOUNT *-1, 0)), 0) 
  --     		  FROM BENEFICIARY_TRANSACTIONS
    --   		 WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
      -- 		   AND CORPORATE_ID = :CORPORATE_ID
       	--	   AND TRUNC (TXN_ENTRY_DATE, 'MM') = TRUNC (SYSDATE, 'MM')
       	SELECT COALESCE (SUM (CASE  TXN_POST_USAGE  WHEN 'CR' THEN  TXN_ENTRY_AMOUNT  WHEN 'DR' THEN  TXN_ENTRY_AMOUNT *-1  else 0 END), 0) 
       		  FROM BENEFICIARY_TRANSACTIONS
       		 WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
       		   AND CORPORATE_ID = :CORPORATE_ID
       		   AND date_trunc ('Month',txn_entry_date)  = date_trunc('Month',CURRENT_TIMESTAMP)
  }
  
 OCICBENE_OFF_BNC_REC_MONTH {
     --  SELECT MONTHS_BETWEEN (TRUNC (SYSDATE, 'MM'), TRUNC (EFFECTIVE_DATE, 'MM')) + 1
	   --           FROM OFFENDER_DEDUCTIONS
	     --        WHERE OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID
	     select date_part ('month',age(CURRENT_TIMESTAMP,:effective_date)) + 1 as months
       from	 OFFENDER_DEDUCTIONS
      where	OFFENDER_DEDUCTION_ID = :OFFENDER_DEDUCTION_ID

}
OCICBENE_GET_CHEQUE_SUM {
select	coalesce (SUM(CHK_AMT),	0)
			from
			(
				select
				distinct CHEQUE_TXN_ID CHK_TXN_ID,
				CHEQUE_AMOUNT CHK_AMT
				from	BANK_CHEQUE_BENEFICIARIES BCB,
						BANK_CHEQUE_REGISTERS BCR
				where
					BCB.CORPORATE_ID = :CORP_ID
					and BCR.CHEQUE_STATUS = 'PRINTED'
					and BCB.CHEQUE_TXN_ID = BCR.TXN_ID) a
}
OCICBENE_GET_PAYMENT_AMOUNT {
--SELECT NVL (SUM (OCPP.PAYMENT_AMOUNT), 0)
  --            FROM OFFENDER_CREDIT_PRIOR_PAYMENTS OCPP, BENEFICIARY_TRANSACTIONS BEN
    --         WHERE BEN.CORPORATE_ID = :CORP_ID
      --         AND NVL (BEN.REV_TXN_FLAG, 'N') = 'N'
        --       AND BEN.TXN_TYPE NOT IN ('GBEN', 'BBEN')
          --     AND OCPP.TXN_ID = BEN.TXN_ID
            --   AND OCPP.TXN_ENTRY_SEQ = BEN.TXN_ENTRY_SEQ
              SELECT COALESCE(SUM (OCPP.PAYMENT_AMOUNT), 0)
              FROM OFFENDER_CREDIT_PRIOR_PAYMENTS OCPP, BENEFICIARY_TRANSACTIONS BEN
             WHERE BEN.CORPORATE_ID = :CORP_ID
               AND COALESCE (BEN.REV_TXN_FLAG, 'N') = 'N'
               AND BEN.TXN_TYPE NOT IN ('GBEN', 'BBEN')
               AND OCPP.TXN_ID = BEN.TXN_ID
               AND OCPP.TXN_ENTRY_SEQ = BEN.TXN_ENTRY_SEQ
}

OCICBENE_CORP_UPADTE_QUERY {
 UPDATE CORPORATES SET    SUSPENDED_FLAG = :suspendedFlag, SUSPENDED_DATE =:suspendedDate , MODIFY_DATETIME = CURRENT_TIMESTAMP,
  MODIFY_USER_ID = :modifyUserId WHERE  CORPORATE_ID = :corporateId
    }
OCICBENE_PROFILE_VALUE {
 SELECT PROFILE_VALUE
      FROM SYSTEM_PROFILES
     WHERE PROFILE_TYPE = :PPROFTYPE
       AND PROFILE_CODE = :PPROFCODE
}