
OCUTRAHI_BENTXN_FIND_BENEFICIARY_TRANSACTIONS {
select TXN_ID , TXN_ENTRY_SEQ , GL_ENTRY_SEQ , BEN_ENTRY_SEQ , OFFENDER_DEDUCTION_ID , ACCOUNT_CODE , PERSON_ID , CORPORATE_ID , TXN_POST_USAGE , TXN_ENTRY_DATE , TXN_ENTRY_TIME , TXN_ENTRY_AMOUNT , CASELOAD_ID , TXN_TYPE , TXN_ENTRY_DESC , CHECK_CLEARED_DATE , REV_TXN_FLAG , REV_TXN_ID , REV_TXN_ENTRY_SEQ , REV_GL_ENTRY_SEQ , REV_BEN_ENTRY_SEQ , MODIFY_USER_ID , MODIFY_DATE , UNKNOWN_BEN_ID , BENEFICIARY_CLEARED_FLAG , RECEIPT_TXN_TYPE , BENEFICIARY_ID , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG from BENEFICIARY_TRANSACTIONS where (BENEFICIARY_TRANSACTIONS.OFFENDER_DEDUCTION_ID = :offenderDeductionId or coalesce (:offenderDeductionId::text ,'')= '') and (person_id = :personId or coalesce (:personId::text ,'')='') and (corporate_id = :corporateId or coalesce (:corporateId::text,'')='') order by txn_entry_date desc, txn_entry_time desc
}
 
OCUTRAHI_VBCBEN_FIND_V_BANK_CHEQUE_BENEFICIARIES {
 select CREATE_DATE , CHEQUE_NUMBER , CHEQUE_STATUS , CHEQUE_PAID_DATE , CHEQUE_TXN_ID , TXN_ENTRY_DATE , TXN_ENTRY_TIME , TXN_ENTRY_DESC , TXN_POST_USAGE , CHEQUE_AMOUNT , PERSON_ID , CORPORATE_ID from V_BANK_CHEQUE_BENEFICIARIES where (person_id = :personId or coalesce (:personId::text,'')='') and (corporate_id = :corporateId or coalesce (:corporateId::text ,'')='') and txn_post_usage = 'CR' order by create_date desc, txn_entry_time desc
 }

OCUTRAHI_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES  /* where  */
}

OCUTRAHI_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO   V_FORM_DESC FROM   OMS_MODULES WHERE  MODULE_NAME = V_FORM_NAME
}
