
OCMCOACT_FIND_CGFKACCODERECACCOUNTCODE {
 	SELECT AC_CODE1.ACCOUNT_CODE  REC_ACCOUNT_CODE  /* CG$FK */        ,AC_CODE1.ACCOUNT_NAME  DESCRIPTION FROM   ACCOUNT_CODES AC_CODE1 ORDER BY  AC_CODE1.ACCOUNT_CODE ASC         ,AC_CODE1.ACCOUNT_NAME ASC
}

OCMCOACT_FIND_CGFKACCODEPARENTCODE {
 	SELECT AC_CODE1.ACCOUNT_CODE PARENT_ACCOUNT_CODE /* CG$FK */  ,AC_CODE1.ACCOUNT_NAME DESCRIPTION FROM ACCOUNT_CODES AC_CODE1 ORDER BY AC_CODE1.ACCOUNT_CODE ASC  ,AC_CODE1.ACCOUNT_NAME ASC
}

OCMCOACT_FIND_CGFKCSLDACDCASELOADID {
 	SELECT CSLD.CASELOAD_ID  CASELOAD_ID  /* CG$FK */        ,CSLD.DESCRIPTION  DSP_DESCRIPTION FROM   CASELOADS CSLD
}

OCMCOACT_FIND_CGFKACCODEACCOUNTTYPE {
 	SELECT REF_CODE.CODE  ACCOUNT_TYPE  /* CG$FK */        ,REF_CODE.DESCRIPTION  DSP_DESCRIPTION3        ,REF_CODE.LIST_SEQ  DSP_LIST_SEQ3 FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'ACCOUNT_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.LIST_SEQ ASC         ,REF_CODE.DESCRIPTION ASC
}

OCMCOACT_FIND_CGFKACCODETXNPOSTINGTYPE {
 	SELECT REF_CODE3.CODE  TXN_POSTING_TYPE  /* CG$FK */        ,REF_CODE3.DESCRIPTION  DSP_DESCRIPTION2        ,REF_CODE3.LIST_SEQ  DSP_LIST_SEQ2 FROM   REFERENCE_CODES REF_CODE3 WHERE   DOMAIN = 'AC_TXN_POST' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE3.LIST_SEQ ASC         ,REF_CODE3.CODE ASC
}

OCMCOACT_FIND_CGFKACCODESUBACCOUNTTYPE {
 	SELECT REF_CODE2.CODE  SUB_ACCOUNT_TYPE  /* CG$FK */        ,REF_CODE2.DESCRIPTION  DSP_DESCRIPTION        ,REF_CODE2.LIST_SEQ  DSP_LIST_SEQ FROM   REFERENCE_CODES REF_CODE2 WHERE   DOMAIN = 'SUB_AC_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE2.LIST_SEQ ASC         ,REF_CODE2.DESCRIPTION ASC
}

OCMCOACT_ACCODE_FIND_ACCOUNT_CODES {
 	SELECT  REC_ACCOUNT_CODE, ACCOUNT_CODE, ACCOUNT_NAME, POSTING_STATUS_FLAG, ACCOUNT_TYPE, SUB_ACCOUNT_TYPE, TXN_POSTING_TYPE, ALL_CASELOAD_FLAG, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, CASELOAD_TYPE, PARENT_ACCOUNT_CODE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG FROM ACCOUNT_CODES 
}
OCMCOACT_ACCODE_INSERT_ACCOUNT_CODES {
	insert into ACCOUNT_CODES(REC_ACCOUNT_CODE, ACCOUNT_CODE, ACCOUNT_NAME, POSTING_STATUS_FLAG, ACCOUNT_TYPE, SUB_ACCOUNT_TYPE, TXN_POSTING_TYPE, ALL_CASELOAD_FLAG, MODIFY_DATE, LIST_SEQ, CASELOAD_TYPE, PARENT_ACCOUNT_CODE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) values(:recAccountCode, :accountCode, :accountName, :postingStatusFlag, :accountType, :subAccountType, :txnPostingType, :allCaseloadFlag, current_timestamp, :listSeq, :caseloadType, :parentAccountCode, current_timestamp, :createUserId, current_timestamp, :sealFlag)
}

OCMCOACT_ACCODE_UPDATE_ACCOUNT_CODES {
--	UPDATE ACCOUNT_CODES set REC_ACCOUNT_CODE =:recAccountCode, ACCOUNT_NAME=:accountName, POSTING_STATUS_FLAG=:postingStatusFlag, ACCOUNT_TYPE=:accountType, SUB_ACCOUNT_TYPE=:subAccountType, TXN_POSTING_TYPE=:txnPostingType, ALL_CASELOAD_FLAG=:allCaseloadFlag, MODIFY_USER_ID=:modifyUserId, MODIFY_DATE=:modifyDate, LIST_SEQ=:listSeq, CASELOAD_TYPE=:caseloadType, PARENT_ACCOUNT_CODE=:parentAccountCode, CREATE_DATETIME=:createDatetime, CREATE_USER_ID=:createUserId, MODIFY_DATETIME=:modifyDatetime, SEAL_FLAG=:sealFlag WHERE ACCOUNT_CODE=:accountCode
	-- update ACCOUNT_CODES set REC_ACCOUNT_CODE =:recAccountCode, ACCOUNT_NAME =:accountName, POSTING_STATUS_FLAG =:postingStatusFlag, ACCOUNT_TYPE =:accountType, SUB_ACCOUNT_TYPE =:subAccountType, TXN_POSTING_TYPE =:txnPostingType, ALL_CASELOAD_FLAG =:allCaseloadFlag, MODIFY_USER_ID =:modifyUserId, MODIFY_DATE =:modifyDate, LIST_SEQ =:listSeq, CASELOAD_TYPE =:caseloadType, PARENT_ACCOUNT_CODE =:parentAccountCode, MODIFY_DATETIME =:modifyDatetime, SEAL_FLAG =:sealFlag where ACCOUNT_CODE =:accountCode
update ACCOUNT_CODES set REC_ACCOUNT_CODE =:recAccountCode, ACCOUNT_NAME =:accountName, POSTING_STATUS_FLAG =:postingStatusFlag, ACCOUNT_TYPE =:accountType, SUB_ACCOUNT_TYPE =:subAccountType, TXN_POSTING_TYPE =:txnPostingType, ALL_CASELOAD_FLAG =:allCaseloadFlag, MODIFY_USER_ID =:modifyUserId, MODIFY_DATE =:modifyDate, LIST_SEQ =:listSeq, CASELOAD_TYPE =:caseloadType, PARENT_ACCOUNT_CODE =:parentAccountCode, MODIFY_DATETIME = CURRENT_TIMESTAMP, SEAL_FLAG =:sealFlag where ACCOUNT_CODE =:accountCode
}

OCMCOACT_ACCODE_DELETE_ACCOUNT_CODES { 
	DELETE FROM ACCOUNT_CODES WHERE ACCOUNT_CODE=:accountCode
}

OCMCOACT_CSLDACD1_FIND_CASELOAD_ACCOUNT_CODES {
 	SELECT   FROM CASELOAD_ACCOUNT_CODES  /* where  */
}

OCMCOACT_CGFKCHK_AC_CODE_AC_CODE_AC_CO_ {
	SELECT AC_CODE1.ACCOUNT_NAME FROM   ACCOUNT_CODES AC_CODE1 WHERE  AC_CODE1.ACCOUNT_CODE = :RECACCOUNTCODE
}

OCMCOACT_CGFKCHK_AC_CODE_AC_SUB_ACCT_T_ {
	SELECT REF_CODE2.DESCRIPTION ,REF_CODE2.LIST_SEQ FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.CODE = :SUBACCOUNTTYPE AND     DOMAIN = 'SUB_AC_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OCMCOACT_CGFKCHK_AC_CODE_AC_POST_TYPE__ {
	SELECT REF_CODE3.DESCRIPTION ,REF_CODE3.LIST_SEQ FROM   REFERENCE_CODES REF_CODE3 WHERE  REF_CODE3.CODE = :TXNPOSTINGTYPE AND     DOMAIN = 'AC_TXN_POST' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OCMCOACT_CGFKCHK_AC_CODE_AC_ACCT_TYPE__ {
	SELECT REF_CODE.DESCRIPTION ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :ACCOUNTTYPE AND     DOMAIN = 'ACCOUNT_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OCMCOACT_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OCMCOACT_CGFKCHK_CSLD_ACD_CSLD_ACD_CSL_ {
	SELECT CSLD.DESCRIPTION FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID
}

OCMCOACT_CGRICHK_ACCOUNT_CODES_DR {
	SELECT  COUNT(*) FROM    TRANSACTION_OPERATIONS TXN_OPE WHERE   TXN_OPE.DR_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_CGRICHK_ACCOUNT_CODES_CR {
	SELECT  COUNT(*) FROM    TRANSACTION_OPERATIONS TXN_OPE WHERE   TXN_OPE.CR_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_CGRICHK_ACCOUNT_CODES_BANK_DR {
	SELECT  COUNT(*) FROM    TRANSACTION_OPERATIONS TXN_OPE WHERE   TXN_OPE.BANK_DR_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_CGRICHK_ACCOUNT_CODES_BANK_CR {
	SELECT  COUNT(*) FROM    TRANSACTION_OPERATIONS TXN_OPE WHERE   TXN_OPE.BANK_CR_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_CGRICHK_ACCOUNT_CODES_TXN_INV {
	SELECT  COUNT(*) FROM    TXN_OPS_INVALID_ACCOUNTS TXN_INV WHERE   TXN_INV.INVALID_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_SUB_ACCOUNT_VIEWS_S_AV {
	SELECT  COUNT(*)  FROM    SUB_ACCOUNT_VIEWS S_AV WHERE   S_AV.ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_PAYEE_ACCOUNT_BALANCES {
	SELECT  COUNT(*)  FROM    PAYEE_ACCOUNT_BALANCES PAYEE_A WHERE   PAYEE_A.ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_INTEREST_TRANSACTION_TYPES {
	SELECT  COUNT(*)  FROM    INTEREST_TRANSACTION_TYPES INT_TT WHERE   INT_TT.TRUST_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_GL_TRANSACTIONS {
	SELECT  COUNT(*)  FROM    GL_TRANSACTIONS GL_TXN WHERE   GL_TXN.ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_OFFENDER_SUB_ACCOUNTS {
	SELECT  COUNT(*)  FROM    OFFENDER_SUB_ACCOUNTS OFF_SUB WHERE   OFF_SUB.TRUST_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_CASELOAD_DEDUCTION_PROFILES {
    SELECT  COUNT(*)  FROM    CASELOAD_DEDUCTION_PROFILES CSLD_DP WHERE   CSLD_DP.ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_ACCOUNT_CODES_AC_CODE {
    SELECT  COUNT(*)  FROM    ACCOUNT_CODES AC_CODE WHERE   AC_CODE.REC_ACCOUNT_CODE = :PACCOUNTCODE
}
OCMCOACT_CASELAOD_ACCOUNT_CODES {
	SELECT 'X' FROM   CASELOAD_ACCOUNT_CODES WHERE  CASELOAD_ID = :CSLDID AND    ACCOUNT_CODE = :ACODE
}
OCMCOACT_CHK_SUB_AC_TYPE_TXN_CUR {
SELECT DISTINCT SUB_ACCOUNT_TYPE FROM OFFENDER_TRANSACTIONS
                WHERE SUB_ACCOUNT_TYPE =(SELECT AC.SUB_ACCOUNT_TYPE
                                           FROM ACCOUNT_CODES AC
                                          WHERE AC.ACCOUNT_CODE = :ACODE
                                            AND AC.CASELOAD_TYPE =(SELECT CASELOAD_TYPE
                                                                     FROM CASELOADS
                                                                    WHERE CASELOAD_ID = :CSLDID)
                                            LIMIT 1)
}
OCMCOACT_CHK_DUP_SUB_AC_TYPE_CUR {                                
SELECT AC.ACCOUNT_CODE FROM ACCOUNT_CODES AC
                WHERE AC.CASELOAD_TYPE =(SELECT CASELOAD_TYPE
                                           FROM CASELOADS
                                          WHERE CASELOAD_ID = :CSLDID)
                  AND AC.SUB_ACCOUNT_TYPE = :NEWSUBACTYPE                                      
}
OCMCOACT_ACCOUNT_CODE_VALIDATION {
	SELECT 'Y' FROM ACCOUNT_CODES WHERE ACCOUNT_CODE = :ACCOUNTCODE AND CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_NAME))
}

OCMCOACT_CASELOAD_ACCOUNT_CODE_VALIDATION {
	SELECT 'Y' FROM CASELOAD_ACCOUNT_CODES WHERE ACCOUNT_CODE = :ACCOUNTCODE AND CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_NAME)
}
OCMCOACT_TRANSACTION_OPERATIONS_CANNOT_DELETE {
SELECT COUNT(*)
        FROM transaction_operations top
       WHERE top.caseload_id IN
                (SELECT caseload_id
                   FROM caseloads
                  WHERE caseload_type =
                           (SELECT caseload_type
                              FROM caseloads
                             WHERE caseload_id = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_NAME)
                            )
                 )
         AND (  top.cr_account_code = :PACCOUNTCODE
             OR top.dr_account_code = :PACCOUNTCODE)
}
OCMCOACT_GL_EXISTS_CANNOT_DELETE {
SELECT COUNT(*)
        FROM gl_transactions gl
       WHERE gl.caseload_id  IN
                (SELECT caseload_id
                   FROM caseloads
                  WHERE caseload_type =
                           (SELECT caseload_type
                              FROM caseloads
                             WHERE caseload_id = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_NAME)
                            )
                 )
         AND gl.account_code = :PACCOUNTCODE
}
OCMCOACT_DELETE_CASELOAD_ACCOUNT_SUMMARIES {
DELETE
     FROM CASELOAD_ACCOUNT_SUMMARIES
    WHERE CASELOAD_ID IN
                (SELECT CASELOAD_ID
                   FROM CASELOADS
                  WHERE CASELOAD_TYPE =
                           (SELECT CASELOAD_TYPE
                              FROM CASELOADS
                             WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID =:createUserId)
                            )
                 )
      AND ACCOUNT_CODE = :accountCode
}
OCMCOACT_DELETE_CASELOAD_CURRENT_ACCOUNTS_TXNS {
DELETE
     FROM CASELOAD_CURRENT_ACCOUNTS_TXNS
    WHERE CASELOAD_ID IN
                (SELECT CASELOAD_ID
                   FROM CASELOADS
                  WHERE CASELOAD_TYPE =
                           (SELECT CASELOAD_TYPE
                              FROM CASELOADS
                             WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :createUserId)
                            )
                 )
      AND ACCOUNT_CODE = :accountCode
}
OCMCOACT_DELETE_CASELOAD_CURRENT_ACCOUNTS_BASE {
DELETE
     FROM CASELOAD_CURRENT_ACCOUNTS_BASE
    WHERE CASELOAD_ID IN
                (SELECT CASELOAD_ID
                   FROM CASELOADS
                  WHERE CASELOAD_TYPE =
                           (SELECT CASELOAD_TYPE
                              FROM CASELOADS
                             WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :createUserId)
                            )
                 )
      AND ACCOUNT_CODE = :accountCode
}
