
OCMTROPS_FIND_CGFKTXNOPERCASELOADID {
-- 	SELECT CSLD.CASELOAD_ID  CODE  /* CG$FK */        ,CSLD.DESCRIPTION  DESCRIPTION        ,CSLD.CASELOAD_TYPE  CASELOAD_TYPE        ,CSLD.LIST_SEQ  LIST_SEQ FROM   CASELOADS CSLD WHERE   CSLD.CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = USER))
 	SELECT CSLD.CASELOAD_ID  CODE  /* CG$FK */        ,CSLD.DESCRIPTION  DESCRIPTION,CSLD.CASELOAD_TYPE  CASELOAD_TYPE,
 	CSLD.LIST_SEQ  LIST_SEQ FROM   CASELOADS CSLD WHERE   CSLD.CASELOAD_TYPE = 
 	(SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))

}

OCMTROPS_FIND_CGFKTXNOPERTXNTYPE {
-- 	SELECT TXN_TYPE.TXN_TYPE  CODE  /* CG$FK */        ,TXN_TYPE.DESCRIPTION  DESCRIPTION      ,TXN_TYPE.LIST_SEQ        ,TXN_TYPE.CASELOAD_TYPE, 
--CASE
--WHEN ( (ACTIVE_FLAG = 'Y' AND EXPIRY_DATE  IS NULL ) OR (''='ENTER-QUERY' ) ) AND TXN_TYPE.CASELOAD_TYPE=(SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = USER)) THEN 'Y'
--ELSE 'N' END SEAL_FLAG
-- FROM   TRANSACTION_TYPES TXN_TYPE  ORDER BY  TXN_TYPE.LIST_SEQ ASC         ,TXN_TYPE.DESCRIPTION ASC         ,TXN_TYPE.TXN_TYPE ASC
--SELECT TXN_TYPE.TXN_TYPE  CODE  /* CG$FK */        ,TXN_TYPE.DESCRIPTION  DESCRIPTION      ,TXN_TYPE.LIST_SEQ        ,TXN_TYPE.CASELOAD_TYPE
-- FROM   TRANSACTION_TYPES TXN_TYPE  ORDER BY  TXN_TYPE.LIST_SEQ ASC         ,TXN_TYPE.DESCRIPTION ASC         ,TXN_TYPE.TXN_TYPE ASC
select
	TXN_TYPE.TXN_TYPE CODE /* CG$FK */
	,
	TXN_TYPE.DESCRIPTION DESCRIPTION ,
	TXN_TYPE.LIST_SEQ ,
	TXN_TYPE.CASELOAD_TYPE,
	case
		when ( (ACTIVE_FLAG = 'Y'
		and EXPIRY_DATE is null )
		or ('' = 'ENTER-QUERY' ) )
		and TXN_TYPE.CASELOAD_TYPE =(
		select
			CASELOAD_TYPE
		from
			CASELOADS
		where
			CASELOAD_ID in (
			select
				WORKING_CASELOAD_ID
			from
				STAFF_MEMBERS
			where
				USER_ID =:userId)) then 'Y'
		else 'N'
	end SEAL_FLAG
from
	TRANSACTION_TYPES TXN_TYPE
order by
	TXN_TYPE.LIST_SEQ asc ,
	TXN_TYPE.DESCRIPTION asc ,
	TXN_TYPE.TXN_TYPE asc

}

OCMTROPS_FIND_CGFKTXNOPERDRACCOUNTCODE {
-- 	SELECT AC_CODE.ACCOUNT_CODE  ACCOUNT_CODE  /* CG$FK */        ,AC_CODE.ACCOUNT_NAME  DESCRIPTION        ,AC_CODE.CASELOAD_TYPE  FROM   ACCOUNT_CODES AC_CODE WHERE   POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE.CASELOAD_TYPE=(SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = USER)) AND AC_CODE.ACCOUNT_CODE IN (SELECT CAS.ACCOUNT_CODE FROM CASELOAD_ACCOUNT_SUMMARIES CAS WHERE CAS.CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = USER) ) ORDER BY  AC_CODE.ACCOUNT_CODE ASC
SELECT AC_CODE.ACCOUNT_CODE  ACCOUNT_CODE  /* CG$FK */        ,AC_CODE.ACCOUNT_NAME  DESCRIPTION        ,
 	AC_CODE.CASELOAD_TYPE  FROM   ACCOUNT_CODES AC_CODE WHERE   POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y'
 	AND AC_CODE.CASELOAD_TYPE=(SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId))
 	AND AC_CODE.ACCOUNT_CODE IN (SELECT CAS.ACCOUNT_CODE FROM CASELOAD_ACCOUNT_SUMMARIES CAS WHERE CAS.CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS 
 	WHERE USER_ID = :userId) ) ORDER BY  AC_CODE.ACCOUNT_CODE ASC
}

OCMTROPS_FIND_CGFKTXNOPERCRACCOUNTCODE {
 	SELECT AC_CODE1.ACCOUNT_CODE  ACCOUNT_CODE  /* CG$FK */        ,AC_CODE1.ACCOUNT_NAME  DESCRIPTION        ,AC_CODE1.CASELOAD_TYPE  FROM   ACCOUNT_CODES AC_CODE1 WHERE   POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE1.CASELOAD_TYPE=(SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)) AND AC_CODE1.ACCOUNT_CODE IN (SELECT CAS1.ACCOUNT_CODE FROM CASELOAD_ACCOUNT_SUMMARIES CAS1 WHERE CAS1.CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId) ) ORDER BY  AC_CODE1.ACCOUNT_CODE ASC
}

OCMTROPS_FIND_CGFKTXNOPERBANKDRACCOUNT {
 	SELECT AC_CODE2.ACCOUNT_CODE   /* CG$FK */        ,AC_CODE2.ACCOUNT_NAME  DESCRIPTION        ,AC_CODE2.CASELOAD_TYPE  FROM   ACCOUNT_CODES AC_CODE2 WHERE   POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE2.CASELOAD_TYPE=(SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)) AND AC_CODE2.ACCOUNT_CODE IN (SELECT CAS2.ACCOUNT_CODE FROM CASELOAD_ACCOUNT_SUMMARIES CAS2 WHERE CAS2.CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId) ) ORDER BY  AC_CODE2.ACCOUNT_CODE ASC
}

OCMTROPS_FIND_CGFKTXNOPERBANKCRACCOUNT {
 	SELECT AC_CODE3.ACCOUNT_CODE  /* CG$FK */        ,AC_CODE3.ACCOUNT_NAME  DESCRIPTION        ,AC_CODE3.CASELOAD_TYPE FROM   ACCOUNT_CODES AC_CODE3 WHERE   POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE3.CASELOAD_TYPE=(SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId)) AND AC_CODE3.ACCOUNT_CODE IN (SELECT CAS3.ACCOUNT_CODE FROM CASELOAD_ACCOUNT_SUMMARIES CAS3 WHERE CAS3.CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :userId) ) ORDER BY  AC_CODE3.ACCOUNT_CODE ASC
}

OCMTROPS_FIND_CGFKTXNOPERTXNOPERATIONTY {
 	SELECT REF_CODE.CODE   /* CG$FK */        ,REF_CODE.DESCRIPTION         ,REF_CODE.LIST_SEQ  FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'TXN_OPER' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.LIST_SEQ ASC         ,REF_CODE.DESCRIPTION ASC
}

OCMTROPS_FIND_CGFKTXNOPERMODULENAME {
 	SELECT OMS_MOD.MODULE_NAME  CODE  /* CG$FK */        ,OMS_MOD.DESCRIPTION  FROM   OMS_MODULES OMS_MOD WHERE   MODULE_TYPE = 'SCREEN' ORDER BY  OMS_MOD.MODULE_NAME ASC         ,OMS_MOD.DESCRIPTION ASC
}

OCMTROPS_TXNOPER_FIND_TRANSACTION_OPERATIONS {
 	SELECT MODULE_NAME ,TXN_TYPE ,TXN_OPERATION_SEQ ,DR_ACCOUNT_CODE ,CR_ACCOUNT_CODE ,BANK_DR_ACCOUNT_CODE ,BANK_CR_ACCOUNT_CODE ,INVALID_ACCOUNTS_FLAG ,CHEQUE_PRODUCTION_FLAG ,RECEIPT_PRODUCTION_FLAG ,CHEQUE_PAYEE_TYPE ,UPDATE_ALLOWED_FLAG ,TXN_OPERATION_TYPE ,TXN_ITEM_CODE ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,CASELOAD_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM TRANSACTION_OPERATIONS TRANSACTION_OPERATIONS   
}
OCMTROPS_TXNOPER_INSERT_TRANSACTION_OPERATIONS {
--	INSERT INTO TRANSACTION_OPERATIONS(MODULE_NAME ,TXN_TYPE ,TXN_OPERATION_SEQ ,DR_ACCOUNT_CODE ,CR_ACCOUNT_CODE ,BANK_DR_ACCOUNT_CODE ,BANK_CR_ACCOUNT_CODE ,INVALID_ACCOUNTS_FLAG ,CHEQUE_PRODUCTION_FLAG ,RECEIPT_PRODUCTION_FLAG ,CHEQUE_PAYEE_TYPE ,UPDATE_ALLOWED_FLAG ,TXN_OPERATION_TYPE ,TXN_ITEM_CODE ,MODIFY_DATE ,MODIFY_USER_ID ,LIST_SEQ ,CASELOAD_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ) VALUES(:moduleName ,:txnType ,:txnOperationSeq ,:drAccountCode ,:crAccountCode ,:bankDrAccountCode ,:bankCrAccountCode ,:invalidAccountsFlag ,:chequeProductionFlag ,:receiptProductionFlag ,:chequePayeeType ,:updateAllowedFlag ,:txnOperationType ,:txnItemCode ,CURRENT_TIMESTAMP ,:modifyUserId ,:listSeq ,:caseloadId ,CURRENT_TIMESTAMP ,:createUserId ,CURRENT_TIMESTAMP ,:sealFlag )
    insert into TRANSACTION_OPERATIONS(MODULE_NAME , TXN_TYPE , TXN_OPERATION_SEQ , DR_ACCOUNT_CODE , CR_ACCOUNT_CODE , BANK_DR_ACCOUNT_CODE , BANK_CR_ACCOUNT_CODE , INVALID_ACCOUNTS_FLAG , CHEQUE_PRODUCTION_FLAG , RECEIPT_PRODUCTION_FLAG , CHEQUE_PAYEE_TYPE , UPDATE_ALLOWED_FLAG , TXN_OPERATION_TYPE , TXN_ITEM_CODE , MODIFY_DATE , LIST_SEQ , CASELOAD_ID , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:moduleName , :txnType , :txnOperationSeq , :drAccountCode , :crAccountCode , :bankDrAccountCode , :bankCrAccountCode , :invalidAccountsFlag , :chequeProductionFlag , :receiptProductionFlag , :chequePayeeType , :updateAllowedFlag , :txnOperationType , :txnItemCode , CURRENT_TIMESTAMP , :listSeq , :caseloadId , CURRENT_TIMESTAMP , :createUserId , CURRENT_TIMESTAMP , :sealFlag )
}

OCMTROPS_TXNOPER_UPDATE_TRANSACTION_OPERATIONS {
--	UPDATE TRANSACTION_OPERATIONS set DR_ACCOUNT_CODE  = :drAccountCode ,CR_ACCOUNT_CODE  = :crAccountCode ,BANK_DR_ACCOUNT_CODE  = :bankDrAccountCode ,BANK_CR_ACCOUNT_CODE  = :bankCrAccountCode ,INVALID_ACCOUNTS_FLAG  = :invalidAccountsFlag ,CHEQUE_PRODUCTION_FLAG  = :chequeProductionFlag ,RECEIPT_PRODUCTION_FLAG  = :receiptProductionFlag ,CHEQUE_PAYEE_TYPE  = :chequePayeeType ,UPDATE_ALLOWED_FLAG  = :updateAllowedFlag ,TXN_OPERATION_TYPE  = :txnOperationType ,TXN_ITEM_CODE  = :txnItemCode ,MODIFY_DATE  = :modifyDate ,MODIFY_USER_ID  = :modifyUserId ,LIST_SEQ  = :listSeq ,CREATE_DATETIME  = :createDatetime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,SEAL_FLAG  = :sealFlag WHERE MODULE_NAME  = :moduleName AND TXN_TYPE  = :txnType AND TXN_OPERATION_SEQ  = :txnOperationSeq AND CASELOAD_ID  = :caseloadId 
	update TRANSACTION_OPERATIONS set DR_ACCOUNT_CODE = :drAccountCode , CR_ACCOUNT_CODE = :crAccountCode , BANK_DR_ACCOUNT_CODE = :bankDrAccountCode , BANK_CR_ACCOUNT_CODE = :bankCrAccountCode , INVALID_ACCOUNTS_FLAG = :invalidAccountsFlag , CHEQUE_PRODUCTION_FLAG = :chequeProductionFlag , RECEIPT_PRODUCTION_FLAG = :receiptProductionFlag , CHEQUE_PAYEE_TYPE = :chequePayeeType , UPDATE_ALLOWED_FLAG = :updateAllowedFlag , TXN_OPERATION_TYPE = :txnOperationType , TXN_ITEM_CODE = :txnItemCode , MODIFY_DATE = :modifyDate , MODIFY_USER_ID = :modifyUserId , LIST_SEQ = :listSeq , MODIFY_DATETIME = CURRENT_TIMESTAMP , SEAL_FLAG = :sealFlag where MODULE_NAME = :moduleName and TXN_TYPE = :txnType and TXN_OPERATION_SEQ = :txnOperationSeq and CASELOAD_ID = :caseloadId
}

OCMTROPS_TXNOPER_DELETE_TRANSACTION_OPERATIONS { 
	DELETE FROM TRANSACTION_OPERATIONS WHERE MODULE_NAME  = :moduleName AND TXN_TYPE  = :txnType AND TXN_OPERATION_SEQ  = :txnOperationSeq AND CASELOAD_ID  = :caseloadId
}


OCMTROPS_CGFKCHK_TXN_OPER_TXN_OPER_CSL_ {
	SELECT CSLD.DESCRIPTION ,CSLD.CASELOAD_TYPE ,CSLD.LIST_SEQ FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID AND     CSLD.CASELOAD_TYPE=:CASELOADTYPE
}

OCMTROPS_CGFKCHK_TXN_OPER_TXN_OPER_OMS_ {
	SELECT OMS_MOD.DESCRIPTION FROM   OMS_MODULES OMS_MOD WHERE  OMS_MOD.MODULE_NAME = :MODULENAME AND     MODULE_TYPE = 'SCREEN'
}

OCMTROPS_CGFKCHK_TXN_OPER_TXN_OPER_REF_ {
	SELECT REF_CODE.DESCRIPTION ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :TXNOPERATIONTYPE AND     DOMAIN = 'TXN_OPER' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OCMTROPS_CGFKCHK_TXN_OPER_TXN_OPER_BNK_ {
	SELECT AC_CODE3.ACCOUNT_NAME ,AC_CODE3.CASELOAD_TYPE FROM   ACCOUNT_CODES AC_CODE3 WHERE  AC_CODE3.ACCOUNT_CODE = :BANKCRACCOUNTCODE AND     POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE3.CASELOAD_TYPE=:CASELOADTYPE
}

OCMTROPS_CGFKCHK_TXN_OPER_TXN_OPER_2_ {
	SELECT AC_CODE2.ACCOUNT_NAME ,AC_CODE2.CASELOAD_TYPE FROM   ACCOUNT_CODES AC_CODE2 WHERE  AC_CODE2.ACCOUNT_CODE = :BANKDRACCOUNTCODE AND     POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE2.CASELOAD_TYPE=:CASELOADTYPE
}

OCMTROPS_CGFKCHK_TXN_OPER_TXN_OPER_CR__ {
	SELECT AC_CODE1.ACCOUNT_NAME ,AC_CODE1.CASELOAD_TYPE FROM   ACCOUNT_CODES AC_CODE1 WHERE  AC_CODE1.ACCOUNT_CODE = :CRACCOUNTCODE AND     POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE1.CASELOAD_TYPE=:CASELOADTYPE
}

OCMTROPS_CGFKCHK_TXN_OPER_TXN_OPER_DR__ {
	SELECT AC_CODE.ACCOUNT_NAME ,AC_CODE.CASELOAD_TYPE FROM   ACCOUNT_CODES AC_CODE WHERE  AC_CODE.ACCOUNT_CODE = :DRACCOUNTCODE AND     POSTING_STATUS_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND AC_CODE.CASELOAD_TYPE=:CASELOADTYPE
}

OCMTROPS_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
OCMTROPS_TXN_OPREATION_VALIDATION {
SELECT 'Y' FROM TRANSACTION_OPERATIONS WHERE TXN_TYPE = :TXNTYPE AND MODULE_NAME = :MODULENAME AND CASELOAD_ID = :CASELOADID AND TXN_OPERATION_SEQ = :TXNOPERATIONSEQ
}
