
OCMTRANS_FIND_CGFKTXNTYPECREDITOBLIGATIO {
 	SELECT DED_TYPE.DEDUCTION_TYPE  CODE  /* CG$FK */        ,DED_TYPE.DEDUCTION_DESC  DESCRIPTION        ,DED_TYPE.LIST_SEQ  LIST_SEQ FROM   DEDUCTION_TYPES DED_TYPE WHERE   DEDUCTION_CATEGORY = 'CROB' AND ACTIVE_FLAG = 'Y' ORDER BY  DED_TYPE.LIST_SEQ ASC         ,DED_TYPE.DEDUCTION_TYPE ASC
}

OCMTRANS_FIND_CGFKTXNPAYEEPAYEEPERSONID {
 	SELECT PER.PERSON_ID  PERSON_ID  /* CG$FK */        ,PER.LAST_NAME  LAST_NAME        ,PER.FIRST_NAME  FIRST_NAME        ,PER.MIDDLE_NAME  MIDDLE_NAME FROM   PERSONS PER
}

OCMTRANS_FIND_CGFKTXNPAYEEPAYEECORPORATE {
 	SELECT CORP.CORPORATE_ID  CORPORATE_ID  /* CG$FK */        ,CORP.CORPORATE_NAME  CORPORATE_NAME FROM   CORPORATES CORP
}

OCMTRANS_FIND_CGFKCSLDTTCASELOADID {
 	SELECT CSLD.CASELOAD_ID  CASELOAD_ID  /* CG$FK */        ,CSLD.DESCRIPTION  DSP_DESCRIPTION FROM   CASELOADS CSLD WHERE   TRUST_ACCOUNTS_FLAG = 'Y' ORDER BY  CSLD.CASELOAD_ID ASC
}

OCMTRANS_FIND_CGFKTXNTYPETXNUSAGE {
 	SELECT REF_CODE.CODE  CODE   ,REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.LIST_SEQ  LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'AC_TXN_USG' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.LIST_SEQ ASC         ,REF_CODE.DESCRIPTION ASC
}

OCMTRANS_TXNTYPE_FIND_TRANSACTION_TYPES {
 	SELECT TXN_TYPE ,DESCRIPTION ,ACTIVE_FLAG ,TXN_USAGE ,ALL_CASELOAD_FLAG ,EXPIRY_DATE ,UPDATE_ALLOWED_FLAG ,MANUAL_INVOICE_FLAG ,CREDIT_OBLIGATION_TYPE ,MODIFY_DATE ,LIST_SEQ ,GROSS_NET_FLAG ,CASELOAD_TYPE ,SEAL_FLAG ,DAYS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM TRANSACTION_TYPES  /* where  */
}
OCMTRANS_TXNTYPE_INSERT_TRANSACTION_TYPES {
	 insert into TRANSACTION_TYPES(TXN_TYPE , DESCRIPTION , ACTIVE_FLAG , TXN_USAGE , ALL_CASELOAD_FLAG , EXPIRY_DATE , UPDATE_ALLOWED_FLAG , MANUAL_INVOICE_FLAG , CREDIT_OBLIGATION_TYPE , MODIFY_DATE , LIST_SEQ , GROSS_NET_FLAG , CASELOAD_TYPE , SEAL_FLAG , DAYS , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME ) values(:txnType , :description , :activeFlag , :txnUsage , :allCaseloadFlag , :expiryDate , :updateAllowedFlag , :manualInvoiceFlag , :creditObligationType , :modifyDate , :listSeq , :grossNetFlag , :caseloadType , :sealFlag , :days , current_timestamp , :createUserId , current_timestamp )
}

OCMTRANS_TXNTYPE_UPDATE_TRANSACTION_TYPES {
	update TRANSACTION_TYPES set DESCRIPTION = :description , ACTIVE_FLAG = :activeFlag , TXN_USAGE = :txnUsage , ALL_CASELOAD_FLAG = :allCaseloadFlag , EXPIRY_DATE = :expiryDate , UPDATE_ALLOWED_FLAG = :updateAllowedFlag , MANUAL_INVOICE_FLAG = :manualInvoiceFlag , CREDIT_OBLIGATION_TYPE = :creditObligationType , MODIFY_DATE = :modifyDate , LIST_SEQ = :listSeq , GROSS_NET_FLAG = :grossNetFlag , CASELOAD_TYPE = :caseloadType , SEAL_FLAG = :sealFlag , DAYS = :days , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId where TXN_TYPE = :txnType
}

OCMTRANS_TXNTYPE_DELETE_TRANSACTION_TYPES { 
	DELETE FROM TRANSACTION_TYPES WHERE TXN_TYPE  = :txnType
}

OCMTRANS_CSLDTT_FIND_CASELOAD_TRANSACTION_TYPES {
 	SELECT CASELOAD_ID ,TXN_TYPE ,MODIFY_USER_ID ,MODIFY_DATE ,LIST_SEQ ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM CASELOAD_TRANSACTION_TYPES  /* where  */
}
OCMTRANS_CSLDTT_INSERT_CASELOAD_TRANSACTION_TYPES {
	 insert into CASELOAD_TRANSACTION_TYPES(CASELOAD_ID , TXN_TYPE , MODIFY_DATE , LIST_SEQ , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:caseloadId , :txnType , :modifyDate , :listSeq , :createDatetime , :createUserId , :modifyDatetime , :sealFlag )
}

OCMTRANS_CSLDTT_DELETE_CASELOAD_TRANSACTION_TYPES { 
	DELETE FROM CASELOAD_TRANSACTION_TYPES/* where */
}

OCMTRANS_TXNPAYEE_FIND_TRANSACTION_PAYEES {
 	SELECT TXN_TYPE ,PAYEE_SEQ ,PAYEE_PERSON_ID ,PAYEE_CORPORATE_ID ,MODIFY_USER_ID ,MODIFY_DATE ,DEFAULT_PAYEE_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM TRANSACTION_PAYEES WHERE TXN_TYPE = :TXNTYPE
}
OCMTRANS_TXNPAYEE_INSERT_TRANSACTION_PAYEES {
	 insert into TRANSACTION_PAYEES(TXN_TYPE , PAYEE_SEQ , PAYEE_PERSON_ID , PAYEE_CORPORATE_ID , MODIFY_DATE , DEFAULT_PAYEE_FLAG , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:txnType , :payeeSeq , :payeePersonId , :payeeCorporateId , :modifyDate , :defaultPayeeFlag , current_timestamp , :createUserId , current_timestamp , :sealFlag )
}

OCMTRANS_TXNPAYEE_UPDATE_TRANSACTION_PAYEES {
	update TRANSACTION_PAYEES set TXN_TYPE = :txnType , PAYEE_SEQ = :payeeSeq , PAYEE_PERSON_ID = :payeePersonId , PAYEE_CORPORATE_ID = :payeeCorporateId , MODIFY_USER_ID = :modifyUserId , MODIFY_DATE = :modifyDate , DEFAULT_PAYEE_FLAG = :defaultPayeeFlag , MODIFY_DATETIME = current_timestamp , SEAL_FLAG = :sealFlag where TXN_TYPE = :txnType and PAYEE_SEQ = :payeeSeq
}

OCMTRANS_TXNPAYEE_DELETE_TRANSACTION_PAYEES { 
	DELETE FROM TRANSACTION_PAYEES  WHERE TXN_TYPE = :txnType AND PAYEE_SEQ  = :payeeSeq
}


OCMTRANS_TXN_TYPE_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM TRANSACTION_PAYEES T WHERE T.TXN_TYPE = :TXNTYPE
}

OCMTRANS_TXN_TYPE_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM CASELOAD_TRANSACTION_TYPES C WHERE C.TXN_TYPE = :TXNTYPE
}

OCMTRANS_CGFKCHK_TXN_TYPE_TXN_TYPE_DED {
	SELECT DED_TYPE.DEDUCTION_DESC ,DED_TYPE.LIST_SEQ FROM   DEDUCTION_TYPES DED_TYPE WHERE  DED_TYPE.DEDUCTION_TYPE = :CREDITOBLIGATIONTYPE AND     DEDUCTION_CATEGORY = 'CROB' AND ACTIVE_FLAG = 'Y'
}

OCMTRANS_CGFKCHK_TXN_TYPE_TXN_TYPE_REF {
	SELECT REF_CODE.DESCRIPTION ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :TXNUSAGE AND     DOMAIN = 'AC_TXN_USG' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OCMTRANS_CGFKCHK_CSLD_TT_CSLD_TT_CSLD__ {
	SELECT CSLD.DESCRIPTION FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID AND     TRUST_ACCOUNTS_FLAG = 'Y'
}

OCMTRANS_CGFKCHK_TXN_PAYEE_TXN_PAYEE_C {
	SELECT CORP.CORPORATE_NAME FROM   CORPORATES CORP WHERE  CORP.CORPORATE_ID = :PAYEECORPORATEID
}

OCMTRANS_CGFKCHK_TXN_PAYEE_TXN_PAYEE_P {
	SELECT PER.LAST_NAME ,PER.FIRST_NAME ,PER.MIDDLE_NAME FROM   PERSONS PER WHERE  PER.PERSON_ID = :PAYEEPERSONID
}

OCMTRANS_CGFKCHK_TXN_PAYEE_TXN_PAYEE_P_ONE {
	SELECT PER.LAST_NAME FROM   PERSONS PER WHERE  PER.PERSON_ID = :PAYEEPERSONID
}

OCMTRANS_CGRICHK_TRANSACTION_OPERATIONS {
	SELECT  count(*) FROM    TRANSACTION_OPERATIONS TXN_OPE WHERE   TXN_OPE.TXN_TYPE = :TXNTYPE
}

OCMTRANS_CGRICHK_OFFENDER_POST_DATED_TXNS {
	SELECT  count(*) FROM    OFFENDER_POST_DATED_TXNS OFF_PDT WHERE   OFF_PDT.TXN_TYPE = :TXNTYPE
}

OCMTRANS_CGRICHK_INTEREST_TRANSACTION_TYPES {
	SELECT  count(*) FROM    INTEREST_TRANSACTION_TYPES INT_TT WHERE   INT_TT.TXN_TYPE = :TXNTYPE
}

OCMTRANS_CGRICHK_GL_TRANSACTIONS {
	SELECT  count(*) FROM    GL_TRANSACTIONS GL_TXN WHERE   GL_TXN.TXN_TYPE = :TXNTYPE
}

OCMTRANS_CGRICHK_OFFENDER_INTERESTS {
	SELECT  count(*) FROM    OFFENDER_INTERESTS OFF_INT WHERE   OFF_INT.TXN_TYPE = :TXNTYPE
}

OCMTRANS_CGRICHK_DEDUCTION_LIMITS {
	SELECT  count(*) FROM    DEDUCTION_LIMITS DED_LT WHERE   DED_LT.RECEIPT_TYPE = :TXNTYPE
}
OCMTRANS_TXNPAYEE_FIND_TRANSACTION_PAYEES_SEQ {
	SELECT COALESCE(MAX(PAYEE_SEQ), 0) + 1 FROM TRANSACTION_PAYEES WHERE  TXN_TYPE = :txnType

}
OCMTRANS_TXNTYPE_VALIDATION {
	SELECT 'Y' FROM TRANSACTION_TYPES WHERE TXN_TYPE = :TXNTYPE AND CASELOAD_TYPE = (SELECT CASELOAD_TYPE FROM CASELOADS WHERE CASELOAD_ID IN (SELECT WORKING_CASELOAD_ID FROM STAFF_MEMBERS WHERE USER_ID = :USER_NAME))

}