
OTMACPRD_ACPRD_FIND_ACCOUNT_PERIODS {
 	SELECT  * FROM ACCOUNT_PERIODS  
}
OTMACPRD_ACPRD_INSERT_ACCOUNT_PERIODS {
--	INSERT INTO ACCOUNT_PERIODS(ACCOUNT_PERIOD_ID,ACCOUNT_PERIOD_TYPE,START_DATE,END_DATE, PARENT_ACCOUNT_PERIOD_ID,MODIFY_DATE,
--	LIST_SEQ,SEAL_FLAG,CREATE_DATETIME,	CREATE_USER_ID,MODIFY_DATETIME, MODIFY_USER_ID ) 
--	VALUES(:accountPeriodId,:accountPeriodType,:startDate,:endDate,:parentAccountPeriodId,:modifyDate,:listSeq,:sealFlag,current_timestamp,:createUserId,current_timestamp,:modifyUserId)
	 insert into ACCOUNT_PERIODS(ACCOUNT_PERIOD_ID, ACCOUNT_PERIOD_TYPE, START_DATE, END_DATE, PARENT_ACCOUNT_PERIOD_ID, MODIFY_DATE, LIST_SEQ, SEAL_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME ) values(:accountPeriodId, :accountPeriodType, :startDate, :endDate, :parentAccountPeriodId, CURRENT_DATE, :listSeq, :sealFlag, current_timestamp, :createUserId, current_timestamp ) 
}

OTMACPRD_ACPRD_UPDATE_ACCOUNT_PERIODS {
	UPDATE ACCOUNT_PERIODS set ACCOUNT_PERIOD_TYPE=:accountPeriodType ,  START_DATE =:startDate, 
	 END_DATE =:endDate , PARENT_ACCOUNT_PERIOD_ID= :parentAccountPeriodId,MODIFY_DATE= CURRENT_DATE,MODIFY_DATETIME= CURRENT_TIMESTAMP,MODIFY_USER_ID=:modifyUserId  where ACCOUNT_PERIOD_ID =:accountPeriodId
}

OTMACPRD_ACPRD_DELETE_ACCOUNT_PERIODS { 
	DELETE FROM ACCOUNT_PERIODS where ACCOUNT_PERIOD_ID =:accountPeriodId
}


OTMACPRD_CGRICHK_ACCOUNT_PERIODS_ {
	SELECT  '1'  VAL FROM    GL_TRANSACTIONS GL_TXN WHERE   GL_TXN.ACCOUNT_PERIOD_ID = :accountPeriodId
}

OTMACPRD_OVERLAPDATES {
SELECT START_DATE, END_DATE   FROM   ACCOUNT_PERIODS  WHERE  START_DATE IS NOT NULL AND END_DATE IS NOT NULL

}

OTMACPRD_DUPLICATE_VALUE {
SELECT 1 VAL  FROM account_periods  WHERE account_period_id = :accountPeriodId
}
OTMACPRD_DUPLICATEOVERLAPDATE {
SELECT COUNT(1) FROM ACCOUNT_PERIODS WHERE TO_DATE(:overlapDate ::TEXT, 'DD/MM/YYYY') BETWEEN START_DATE AND END_DATE
}
