
OTMONCOA_FIND_CGFKCSLDAPCASELOADID {
 	SELECT CSLD.CASELOAD_ID CODE ,CSLD.DESCRIPTION DESCRIPTION  ,CSLD.LIST_SEQ LIST_SEQ FROM CASELOADS CSLD WHERE TRUST_ACCOUNTS_FLAG = 'Y' AND CASELOAD_TYPE = :caseloadType ORDER BY CSLD.CASELOAD_ID ,CSLD.LIST_SEQ
}

OTMONCOA_CSLDAP_FIND_CASELOAD_ACCOUNT_PERIODS {
select * from ( select CAP.* from ( select CASELOAD_ID, ACCOUNT_PERIOD_ID, ACCOUNT_PERIOD_STATUS, CLOSING_USER_ID, CLOSING_DATE, REOPEN_TXN_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, row_number() over( order by CASELOAD_ID asc) as ROW_NUM from CASELOAD_ACCOUNT_PERIODS) CAP) as a
}
OTMONCOA_CSLDAP_INSERT_CASELOAD_ACCOUNT_PERIODS {
	INSERT INTO CASELOAD_ACCOUNT_PERIODS() VALUES(:)
}

OTMONCOA_CSLDAP_DELETE_CASELOAD_ACCOUNT_PERIODS { 
	DELETE FROM CASELOAD_ACCOUNT_PERIODS  WHERE ACCOUNT_PERIOD_ID = :accountPeriodId
}
OTMONCOA_GET_TOTAL_COUNT {
	SELECT COUNT(1) FROM CASELOAD_ACCOUNT_PERIODS #param
}


OTMONCOA_CGFKCHK_CSLD_AP_CSLD_AP_CSLD__ {
	SELECT CSLD.DESCRIPTION ,CSLD.LIST_SEQ FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID AND     TRUST_ACCOUNTS_FLAG = 'Y'
}

OTMONCOA_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  current_timestamp , USER

}
OTMONCOA_OTMONCOA_GEN_ACCOUNT_CODES {
	CALL OMS_OWNER.OTMONCOA_GEN_ACCOUNT_CODES(:P_CASELOAD_ID, :P_ACCOUNT_CODE)
}