
OTUINVAC_FIND_TXN_OPS_INVALID_ACCOUNTS {
	SELECT MODULE_NAME, TXN_TYPE, INVALID_ACCOUNT_CODE, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG FROM TXN_OPS_INVALID_ACCOUNTS WHERE  MODULE_NAME = :MODULENAME AND TXN_TYPE = :TXNTYPE ORDER BY MODULE_NAME, TXN_TYPE, INVALID_ACCOUNT_CODE
}

OTUINVAC_TXN_INV_INVALID_ACCOUNT_CR {
	SELECT AC_CODE.ACCOUNT_CODE, AC_CODE.ACCOUNT_NAME  DESCRIPTION FROM   ACCOUNT_CODES AC_CODE order by AC_CODE.ACCOUNT_CODE
}

OTUINVAC_TXN_INV_INSERT_TRANSACTION {
	INSERT INTO TXN_OPS_INVALID_ACCOUNTS(MODULE_NAME, TXN_TYPE, INVALID_ACCOUNT_CODE,  MODIFY_DATE, LIST_SEQ, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) VALUES
	(:moduleName ,:txnType , :invalidAccountCode,:modifyDate ,:listSeq ,CURRENT_TIMESTAMP ,:createUserId ,CURRENT_TIMESTAMP ,:sealFlag )
}

OTUINVAC_TXN_INV_UPDATE_TRANSACTION {
	UPDATE TXN_OPS_INVALID_ACCOUNTS set MODIFY_USER_ID = :modifyUserId, MODIFY_DATE = :modifyDate, LIST_SEQ = :listSeq,  MODIFY_DATETIME = CURRENT_TIMESTAMP WHERE MODULE_NAME = :moduleName AND TXN_TYPE = :txnType AND INVALID_ACCOUNT_CODE = :invalidAccountCode
}

OTUINVAC_TXN_INV_DELETE_TRANSACTION { 
	DELETE FROM TXN_OPS_INVALID_ACCOUNTS WHERE MODULE_NAME = :moduleName AND TXN_TYPE = :txnType AND INVALID_ACCOUNT_CODE = :invalidAccountCode
}