
OCDMWORK_FIND_RGREASON {
 	SELECT REF_CODE.CODE  ,            REF_CODE.DESCRIPTION DESCRIPTION   FROM     REFERENCE_CODES REF_CODE WHERE DOMAIN = 'COMPLETE_RSN' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL  ORDER BY LIST_SEQ ,UPPER(DESCRIPTION )
}

OCDMWORK_FIND_RGTYPE {
 	SELECT REF_CODE.DESCRIPTION DESCRIPTION  ,            REF_CODE.CODE   FROM     REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'ALERT_TASK' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ ,UPPER(REF_CODE.DESCRIPTION )
}

OCDMWORK_FIND_RGWORKTYPE {
 	SELECT REF_CODE.DESCRIPTION DESCRIPTION ,            REF_CODE.CODE    FROM     REFERENCE_CODES REF_CODE WHERE DOMAIN = 'TASK_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ ,UPPER(DESCRIPTION )
}

OCDMWORK_FIND_RGSUBTYPE {
 	SELECT REF_CODE.DESCRIPTION DESCRIPTION , REF_CODE.CODE CODE FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'TASK_SUBTYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ ,UPPER(DESCRIPTION )
}

OCDMWORK_FIND_RGCOMPLETED {
 	SELECT  REF_CODE.DESCRIPTION DESCRIPTION  , REF_CODE.CODE   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'WORK_STATUS' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ ,UPPER(DESCRIPTION )
}

OCDMWORK_FIND_RGSEVERITY {
 	SELECT DESCRIPTION SEVERITY_DESC ,        CODE        SEVERITY_CODE    FROM REFERENCE_CODES    WHERE DOMAIN = 'MEMO_SEVTY'    AND  (   (ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL )          OR (::MODE = 'ENTER-QUERY' )          )   ORDER BY LIST_SEQ ,UPPER(DESCRIPTION )
}

OCDMWORK_WORK_UPDATE_TAG_WORKFLOW.BROWSE_QUEUE {
	UPDATE TAG_WORKFLOW.BROWSE_QUEUE set /* where */
}


OCDMWORK_MEMO_POSTQUERY_ {
	SELECT  DESCRIPTION FROM  REFERENCE_CODES WHERE  DOMAIN = 'MEMO_SEVTY' AND  CODE = :SEVERITYCODE
}
OCDMWORK_WORK_EXECUTERY {
	SELECT   QUEUE_NAME, TEAM_ID, STAFF_ID, TEAM_MEMBER_ID, WORK_ID,
              OFFENDER_BOOK_ID, ASSIGNMENT_DATE, DUE_DATE, MSGID,
              MESSAGE_TEXT, WORKFLOW_TYPE, ORIGINAL_MSGID,
              EVENT_DATE,FUNCTION_TYPE,
              SEVERITY_CODE, ACKNOWLEDGEMENT_REQUIRED,
              ACKNOWLEDGEMENT_SUBJECT, SENDER_ID
              FROM TABLE ( TAG_WORKFLOW.SCAN_QUEUE ( 'TAGWFC2.TAG_WF_PERSONAL_T_C2',NULL,NULL ) )
              WHERE STAFF_ID IN (SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID=USER)

}
OCDMWORK_MEMO_EXECUTERY {
	SELECT   QUEUE_NAME, TEAM_ID, STAFF_ID, TEAM_MEMBER_ID, WORK_ID,
                   OFFENDER_BOOK_ID, ASSIGNMENT_DATE, DUE_DATE, MSGID,
                   MESSAGE_TEXT, WORKFLOW_TYPE, ORIGINAL_MSGID,
        		   EVENT_DATE,FUNCTION_TYPE,
                   SEVERITY_CODE, ACKNOWLEDGEMENT_REQUIRED,
                   ACKNOWLEDGEMENT_SUBJECT, SENDER_ID 
              FROM TABLE ( TAG_WORKFLOW.SCAN_QUEUE ( 'TAGWFC2.TAG_WF_PERSONAL_M_C2',NULL,NULL ) )
              WHERE STAFF_ID IN (SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID=USER)
             
}
