
OCDSMEMO_FIND_RGWORKTYPE {
 	SELECT DISTINCT REFERENCE_CODES.DESCRIPTION DESCRIPTION , WORKS.WORK_TYPE  CODE FROM WORKS , REFERENCE_CODES   WHERE WORKS.WORKFLOW_TYPE = 'MEMO'   AND WORKS.ACTIVE_FLAG = 'Y'    AND (WORKS.EXPIRY_DATE IS NULL OR WORKS.EXPIRY_DATE > current_timestamp )   AND (WORKS.CASELOAD_TYPE IN (:caseloadType , 'BOTH' ) )    AND WORKS.WORK_TYPE = REFERENCE_CODES.CODE    AND REFERENCE_CODES.DOMAIN = 'TASK_TYPE'    AND REFERENCE_CODES.CODE <> 'MEMO_REC'  ORDER BY REFERENCE_CODES.DESCRIPTION
}

OCDSMEMO_FIND_RGWORKSUBTYPE {
 	SELECT REFERENCE_CODES.DESCRIPTION DESCRIPTION , WORKS.WORK_SUB_TYPE  CODE , WORKS.WORK_ID  WORK_ID  FROM WORKS , REFERENCE_CODES   WHERE WORKS.WORKFLOW_TYPE = 'MEMO'   AND WORKS.WORK_TYPE = :workType    AND WORKS.ACTIVE_FLAG = 'Y'    AND (WORKS.EXPIRY_DATE IS NULL OR WORKS.EXPIRY_DATE > current_timestamp )   AND WORKS.CASELOAD_TYPE = :caseloadType    AND WORKS.WORK_SUB_TYPE = REFERENCE_CODES.CODE    AND REFERENCE_CODES.DOMAIN = 'TASK_SUBTYPE'  ORDER BY REFERENCE_CODES.DESCRIPTION
}

OCDSMEMO_FIND_RGSEVERITY {
 	SELECT REF_CODE.DESCRIPTION  DESCRIPTION  ,REF_CODE.CODE  SEVERITY_CODE  FROM   REFERENCE_CODES REF_CODE WHERE   REF_CODE.DOMAIN = 'MEMO_SEVTY'    AND   REF_CODE.ACTIVE_FLAG = 'Y'    AND   (REF_CODE.EXPIRED_DATE IS NULL OR REF_CODE.EXPIRED_DATE > current_timestamp ) ORDER BY  REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION
}

OCDSMEMO_FIND_RGSTAFF {
 	SELECT LAST_NAME || ', ' || FIRST_NAME AS STAFF_NAME , STAFF_ID FROM STAFF_MEMBERS   WHERE STATUS = 'ACTIVE'
}


OCDSMEMO_CREATE_FORM_GLOBALS {
--	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
	SELECT DESCRIPTION  FROM OMS_MODULES WHERE MODULE_NAME = :V_FORM_NAME

}

OCDSMEMO_GET_OFF_DETAILSGET_OFF_DETAILS {
--	SELECT V_HEADER_BLOCK.OFFENDER_BOOK_ID, V_HEADER_BLOCK.LAST_NAME, V_HEADER_BLOCK.FIRST_NAME, V_HEADER_BLOCK.PRISON_LOCATION INTO P_OFFENDER_BOOK_ID, P_LAST_NAME, P_FIRST_NAME, P_PRISON_LOCATION FROM V_HEADER_BLOCK WHERE V_HEADER_BLOCK.OFFENDER_ID_DISPLAY  = P_OFFENDER_ID_DISPLAY AND V_HEADER_BLOCK.ACTIVE_FLAG = 'Y' AND (   V_HEADER_BLOCK.BOOKING_END_DATE IS NULL OR V_HEADER_BLOCK.BOOKING_BEGIN_DATE = (SELECT MAX(OB.BOOKING_BEGIN_DATE) FROM OFFENDER_BOOKINGS OB WHERE OB.ROOT_OFFENDER_ID = V_HEADER_BLOCK.ROOT_OFFENDER_ID AND OB.ACTIVE_FLAG = 'Y' ) ) AND EXISTS (SELECT 1 FROM CASELOAD_AGENCY_LOCATIONS CAL WHERE CAL.AGY_LOC_ID = V_HEADER_BLOCK.AGY_LOC_ID AND CAL.CASELOAD_ID = :GLOBAL.CASELOAD_ID )
select
	V_HEADER_BLOCK.OFFENDER_BOOK_ID,
	V_HEADER_BLOCK.LAST_NAME,
	V_HEADER_BLOCK.FIRST_NAME,
	V_HEADER_BLOCK.PRISON_LOCATION
from
	V_HEADER_BLOCK_FN(:USERID) V_HEADER_BLOCK
where
	V_HEADER_BLOCK.OFFENDER_ID_DISPLAY = :P_OFFENDER_ID_DISPLAY
	and V_HEADER_BLOCK.ACTIVE_FLAG = 'Y'
	and ( V_HEADER_BLOCK.BOOKING_END_DATE is null
		or V_HEADER_BLOCK.BOOKING_BEGIN_DATE = (
		select
			MAX(OB.BOOKING_BEGIN_DATE)
		from
			OFFENDER_BOOKINGS OB
		where
			OB.ROOT_OFFENDER_ID = V_HEADER_BLOCK.ROOT_OFFENDER_ID
			and OB.ACTIVE_FLAG = 'Y' ) )
	and exists (
	select
		1
	from
		CASELOAD_AGENCY_LOCATIONS CAL
	where
		CAL.AGY_LOC_ID = V_HEADER_BLOCK.AGY_LOC_ID
		and CAL.CASELOAD_ID = :CASELOAD_ID )
}

OCDSMEMO_GET_OFF_DETAILSGET_OFF_DETAILS {
--	SELECT V_PIMS_NAME_SEARCH.OFFENDER_BOOK_ID, V_PIMS_NAME_SEARCH.LAST_NAME, V_PIMS_NAME_SEARCH.FIRST_NAME, V_PIMS_NAME_SEARCH.PRISON_LOCATION INTO P_OFFENDER_BOOK_ID, P_LAST_NAME, P_FIRST_NAME, P_PRISON_LOCATION FROM V_PIMS_NAME_SEARCH WHERE V_PIMS_NAME_SEARCH.OFFENDER_ID_DISPLAY  = P_OFFENDER_ID_DISPLAY AND EXISTS ( SELECT 1 FROM OFFENDER_BOOKINGS OB WHERE OB.OFFENDER_BOOK_ID = V_PIMS_NAME_SEARCH.OFFENDER_BOOK_ID AND OB.COMMUNITY_ACTIVE_FLAG = 'Y' AND (   OB.BOOKING_END_DATE IS NULL OR OB.BOOKING_BEGIN_DATE = (SELECT MAX(OB1.BOOKING_BEGIN_DATE) FROM OFFENDER_BOOKINGS OB1 WHERE OB1.ROOT_OFFENDER_ID = OB.ROOT_OFFENDER_ID AND OB1.COMMUNITY_ACTIVE_FLAG = 'Y' ) ) )
select
	V_PIMS_NAME_SEARCH.OFFENDER_BOOK_ID,
	V_PIMS_NAME_SEARCH.LAST_NAME,
	V_PIMS_NAME_SEARCH.FIRST_NAME,
	V_PIMS_NAME_SEARCH.PRISON_LOCATION
from
	V_PIMS_NAME_SEARCH
where
	V_PIMS_NAME_SEARCH.OFFENDER_ID_DISPLAY = :P_OFFENDER_ID_DISPLAY
	and exists (
	select
		1
	from
		OFFENDER_BOOKINGS OB
	where
		OB.OFFENDER_BOOK_ID = V_PIMS_NAME_SEARCH.OFFENDER_BOOK_ID
		and OB.COMMUNITY_ACTIVE_FLAG = 'Y'
		and ( OB.BOOKING_END_DATE is null
		or OB.BOOKING_BEGIN_DATE = (
		select
			MAX(OB1.BOOKING_BEGIN_DATE)
		from
			OFFENDER_BOOKINGS OB1
		where
			OB1.ROOT_OFFENDER_ID = :ROOT_OFFENDER_ID
			and OB1.COMMUNITY_ACTIVE_FLAG = 'Y' ) ) )
}
