INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag) 
   VALUES ('OCDLEGLO', 'custOrd', 'OCDLEGLO_DATA', '[{"field":"displayNo","fieldName":"ocdleglo.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"ocdleglo.ordereddate","dataType":"date","required":true},{"field":"matter","fieldName":"ocdleglo.matter","dataType":"text","editable":false},{"field":"court","fieldName":"ocdleglo.court","dataType":"lov","source":"link","url":"ocdccase/populateCourtData","sourceType":"OUMAGLOC","required":true},{"field":"type","fieldName":"ocdleglo.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=","sourceType":"OIMSREQS","required":true},{"field":"commenceType","fieldName":"ocdleglo.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","required":true},{"field":"relatedTo","fieldName":"ocdleglo.linkto","dataType":"text","editable":false},{"field":"relatedToLaunch","dataType":"hyperlink","link":"/relatedToLine","parentField":["relatedTo"]},{"field":"commenceDate","fieldName":"ocdleglo.commencedate","dataType":"date"},{"field":"termTypeAndLength","fieldName":"ocdleglo.termtypeandlength","dataType":"text","required":true,"editable":false},{"field":"lengthBtn","dataType":"hyperlink","link":"/termToLine","parentField":["termTypeAndLength","terms"]},{"field":"pel","fieldName":"ocdleglo.pel","dataType":"checkbox"},{"field":"status","fieldName":"ocdleglo.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"terms","hide":true,"dataType":"text"},{"field":"charges","hide":true,"dataType":"text"},{"field":"orderType","hide":true,"dataType":"text"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDLEGLO', 'terms', 'OCDLEGLO_DATA', '[{"field":"termType","fieldName":"termToLine.termtype","dataType":"lov","source":"link","sourceType":"OIMSREQS","url":"ocmpconf/populateTermType?sentCategory=:orderType&sentType=:sentType","required":true},{"field":"years","fieldName":"termToLine.years","dataType":"number","maxValue":99.5,"format":"1.1-1"},{"field":"months","fieldName":"termToLine.months","dataType":"number","maxValue":99.5,"format":"1.1-1"},{"field":"weeks","fieldName":"termToLine.weeks","dataType":"number","maxValue":99,"format":"0.0-0"},{"field":"days","fieldName":"termToLine.days","dataType":"number","maxValue":99,"format":"0.0-0"},{"field":"indefinite","fieldName":"termToLine.indefinite","dataType":"checkbox"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDLEGLO', 'related', 'OCDLEGLO_DATA', '[{"field":"displayNo","fieldName":"ocdleglo.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"ocdleglo.ordereddate","dataType":"date"},{"field":"matter","fieldName":"ocdleglo.matter","dataType":"text"},{"field":"type","fieldName":"ocdleglo.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=","sourceType":"OIMSREQS"},{"field":"termTypeAndLength","fieldName":"ocdleglo.termtypeandlength","dataType":"text"},{"field":"commenceDate","fieldName":"ocdleglo.commencedate","dataType":"date"},{"field":"status","fieldName":"ocdleglo.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDCHGSU', 'charges', 'OCDCHGSU_DATA', '[{"field":"chargeId","dataType":"number","editable":false,"hide":true},{"field":"select","fieldName":"ocdchgsu.select","dataType":"checkbox","editable":false},{"field":"matter","fieldName":"ocdchgsu.matter","dataType":"text","required":true,"editable":true},{"field":"act","fieldName":"ocdchgsu.act","dataType":"lov","source":"link","url":"ocmpconf/populateStatutes","sourceType":"OIMSTATU","required":true,"editable":true},{"field":"code","fieldName":"ocdchgsu.code","dataType":"text","required":false,"editable":false},{"field":"description","fieldName":"ocdchgsu.description","dataType":"text","required":true,"editable":false},{"field":"descriptionLaunch","dataType":"hyperlink","displayFields":["code","description","act","legislativeBody"],"parentField":["code","description","act"],"lovUrl":"ocmpconf/getOffencesOnStatute?statuteCode=:act","link":"/multiLov"},{"field":"type","fieldName":"ocdchgsu.type","dataType":"lov","source":"link","sourceType":"OIMOFFEN","parentFields":["code","act"],"url":"ocmpconf/getAllowableOffenceType?offenceCode=:code&statuteCode=:act","editable":true},{"field":"incidentDate","fieldName":"ocdchgsu.incidentdate","dataType":"date","editable":true},{"field":"Range","fieldName":"ocdchgsu.range","dataType":"date","editable":true},{"field":"plea","fieldName":"ocdchgsu.plea","dataType":"lov","source":"domain","url":"PLEA_STATUS","editable":true},{"field":"currentStatus","fieldName":"ocdchgsu.currentstatus","dataType":"text","editable":false},{"field":"details","fieldName":"ocdchgsu.details","dataType":"text","editable":false}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDLEGLO', 'chargesChild', 'OCDLEGLO_DATA', '[{"field":"chargeId","dataType":"number","editable":false,"hide":true},{"field":"matter","fieldName":"ocdchgsu.matter","dataType":"text","editable":false},{"field":"description","fieldName":"ocdchgsu.descriptionchild","dataType":"text","editable":false},{"field":"outcome","fieldName":"ocdchgsu.outcome","dataType":"lov","source":"link","url":"ocmpconf/populateOutcome","sourceType":"OCMORCOD","required":true,"editable":true},{"field":"type","fieldName":"ocdchgsu.type","dataType":"lov","source":"domain","url":"OFFENCE_TYPE","editable":false},{"field":"incidentDate","fieldName":"ocdchgsu.incidentdate","dataType":"date","editable":false},{"field":"Range","fieldName":"ocdchgsu.range","dataType":"date","editable":false},{"field":"plea","fieldName":"ocdchgsu.plea","dataType":"lov","source":"domain","url":"PLEA_STATUS","editable":false},{"field":"details","fieldName":"ocdchgsu.details","dataType":"text","editable":false}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDCHGSU', 'chargesDlg', 'OCDCHGSU_DATA', '[{"field":"chargeId","dataType":"number","editable":false,"hide":true},{"field":"select","dataType":"checkbox","fieldName":"ocdchgsu.select","editable":true},{"field":"matter","fieldName":"ocdchgsu.matter","dataType":"text","required":true,"editable":true},{"field":"act","fieldName":"ocdchgsu.act","dataType":"lov","source":"link","url":"ocmpconf/populateStatutes","sourceType":"OIMSTATU","required":true,"editable":true},{"field":"code","fieldName":"ocdchgsu.code","dataType":"text","required":false,"editable":false},{"field":"description","fieldName":"ocdchgsu.description","required":true,"dataType":"text","editable":false},{"field":"descriptionLaunch","dataType":"hyperlink","displayFields":["code","description","act","legislativeBody"],"parentField":["code","description","act"],"lovUrl":"ocmpconf/getOffencesOnStatute?statuteCode=:act","link":"/multiLov"},{"field":"type","fieldName":"ocdchgsu.type","dataType":"lov","source":"link","sourceType":"OIMOFFEN","parentFields":["code","act"],"url":"ocmpconf/getAllowableOffenceType?offenceCode=:code&statuteCode=:act","editable":true},{"field":"incidentDate","fieldName":"ocdchgsu.incidentdate","dataType":"date","editable":true},{"field":"Range","fieldName":"ocdchgsu.range","dataType":"date","editable":true},{"field":"plea","fieldName":"ocdchgsu.plea","dataType":"lov","source":"domain","url":"PLEA_STATUS","editable":true},{"field":"currentStatus","fieldName":"ocdchgsu.currentstatus","dataType":"text","editable":false},{"field":"details","fieldName":"ocdchgsu.details","dataType":"text","editable":false}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDLEGLS', 'keyDateSummary', 'OCDLEGLS_DATA', '[{"field":"date_type","dataType":"text","fieldName":"ocdlegls.datetype","editable":false},{"field":"value","dataType":"date","fieldName":"ocdlegls.value","editable":false}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDNCODE', 'nonCustOrd', 'OCDLEGLO_DATA', '[{"field":"displayNo","fieldName":"ocdncode.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"ocdncode.ordereddate","dataType":"date","required":true},{"field":"matter","fieldName":"ocdncode.matter","dataType":"text","editable":false},{"field":"court","fieldName":"ocdncode.court","dataType":"lov","source":"link","url":"ocdccase/populateCourtData","sourceType":"OUMAGLOC","required":true},{"field":"type","fieldName":"ocdncode.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=","sourceType":"OIMSREQS","required":true},{"field":"commenceType","fieldName":"ocdncode.commencetype","dataType":"lov","source":"domain","url":"LO_REL_TYPE","required":true},{"field":"relatedTo","fieldName":"ocdncode.linkto","dataType":"text","editable":false},{"field":"relatedToLaunch","dataType":"hyperlink","link":"/nonCustRelated","parentField":["relatedTo"]},{"field":"commenceDate","fieldName":"ocdncode.commencedate","dataType":"date"},{"field":"termTypeAndLength","fieldName":"ocdncode.termtypeandlength","dataType":"text","required":true,"editable":false},{"field":"lengthBtn","dataType":"hyperlink","link":"/nonCustDuration","parentField":["termTypeAndLength","terms"]},{"field":"expiryDate","fieldName":"ocdncode.expiryDate","dataType":"date","editable":true},{"field":"status","fieldName":"ocdncode.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE","editable":false},{"field":"terms","hide":true,"dataType":"text"},{"field":"orderType","hide":true,"dataType":"text"},{"field":"charges","hide":true,"dataType":"text"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag) 
   VALUES ('OCDNCODE', 'nonCustTerm', 'OCDLEGLO_DATA', '[{"field":"termType","fieldName":"ncusTerm.termtype","dataType":"lov","source":"link","sourceType":"OIMSREQS","url":"ocmpconf/populateTermType?sentCategory=:orderType&sentType=:sentType","required":true},{"field":"years","fieldName":"ncusTerm.years","dataType":"number","maxValue":99.5,"format":"1.1-1"},{"field":"months","fieldName":"ncusTerm.months","dataType":"number","maxValue":99.5,"format":"1.1-1"},{"field":"weeks","fieldName":"ncusTerm.weeks","dataType":"number","maxValue":99,"format":"0.0-0"},{"field":"days","fieldName":"ncusTerm.days","dataType":"number","maxValue":99,"format":"0.0-0"},{"field":"fixedExpiry","fieldName":"ncusTerm.fixedExpiry","dataType":"checkbox"},{"field":"indefinite","fieldName":"ncusTerm.indefinite","dataType":"checkbox"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OCDNCODE', 'nonCustRelated', 'OCDLEGLO_DATA', '[{"field":"displayNo","fieldName":"nonCustRelated.no","dataType":"text","editable":false},{"field":"no","hide":true,"dataType":"text","editable":false},{"field":"orderedDate","fieldName":"nonCustRelated.ordereddate","dataType":"date"},{"field":"matter","fieldName":"nonCustRelated.matter","dataType":"text"},{"field":"type","fieldName":"nonCustRelated.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=","sourceType":"OIMSREQS"},{"field":"termTypeAndLength","fieldName":"nonCustRelated.termtypeandlength","dataType":"text"},{"field":"commenceDate","fieldName":"nonCustRelated.commencedate","dataType":"date"},{"field":"status","fieldName":"nonCustRelated.status","dataType":"lov","source":"domain","url":"ACTIVE_TYPE"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag)
   VALUES ('OSANVIOS', 'sanctions', 'OCDLEGLO_DATA', '[{"field":"no","fieldName":"ocdleglo.no","dataType":"number","editable":false},{"field":"type","fieldName":"ocdleglo.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=NCUS","sourceType":"OIMSREQS","required":true},{"field":"matter","fieldName":"ocdleglo.matter","dataType":"text","editable":false},{"field":"commenceDate","fieldName":"ocdleglo.commencedate","dataType":"date"},{"field":"expiryDate","fieldName":"Expiry Date","dataType":"date"},{"field":"sanctionCount","fieldName":"Sanction Count","dataType":"number","editable":false},{"field":"adjournedCount","fieldName":"Adjourned Sanctions","dataType":"number","minValue":"0","maxValue":"999999","whole":"true"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

INSERT INTO oms_owner.dynamic_grid_config (module_name, grid_name, db_table_name, config_json, create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag) 
   VALUES ('OSANVIOS', 'sanctions', 'OCDLEGLO_DATA', '[{"field":"no","fieldName":"ocdleglo.no","dataType":"number","editable":false},{"field":"type","fieldName":"ocdleglo.type","dataType":"lov","source":"link","url":"ocmpconf/populateSentType?sentCategory=NCUS","sourceType":"OIMSREQS","required":true},{"field":"matter","fieldName":"ocdleglo.matter","dataType":"text","editable":false},{"field":"commenceDate","fieldName":"ocdleglo.commencedate","dataType":"date"},{"field":"expiryDate","fieldName":"Expiry Date","dataType":"date"},{"field":"sanctionCount","fieldName":"Sanction Count","dataType":"number","editable":false},{"field":"adjournedCount","fieldName":"Adjourned Sanctions","dataType":"number","minValue":"0","maxValue":"999999","whole":"true"}]', CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);
