UPDATE oms_owner.system_settings SET setting_value = '[{"KEY_DESC":"Insights Server Url","KEY_CODE":"INSI_SER_URL","VALUE":" "},{"KEY_DESC":"Get Insight Auth Token","KEY_CODE":"INS_AUTH_TOKEN","VALUE":"https://bi.elitev4.com/bi/api/site/insightstraining/token"},{"KEY_DESC":"Search Insight User","KEY_CODE":"INS_SEARCH_USER","VALUE":"https://bi.elitev4.com/bi/api/site/insightstraining/v2.0/users"},{"KEY_DESC":"Create Insight User","KEY_CODE":"INS_CREATE_USER","VALUE":"https://bi.elitev4.com/bi/api/site/insightstraining/v2.0/users"},{"KEY_DESC":"environment ","KEY_CODE":"INS_ENV","VALUE":"enterprise"},{"KEY_DESC":"siteIdentifier","KEY_CODE":"INS_SITE_IDF","VALUE":"site/elitebisales"},{"KEY_DESC":"authorizationUrl","KEY_CODE":"INS_AUTH_URL","VALUE":"/embeddetail/get"},{"KEY_DESC":"EmbedSecret","KEY_CODE":"INS_EMB_SEC","VALUE":"bIm9Aw0hgfgjyNFmyFQ0LJJ6vZI34UCt"}]' WHERE SETTING_TYPE = 'INSIGHTS' AND SETTING_PROVIDER_CODE = 'INSIGHTS';

--
UPDATE oms_owner.system_settings SET setting_value = '[{"KEY_DESC":"Application Server Url","KEY_CODE":"APP_SER_URL","VALUE":"http://10.60.2.179:4000"},{"KEY_DESC":"Automation Server Url","KEY_CODE":"AUT_SER_URL","VALUE":"http://10.60.2.179:4001"},{"KEY_DESC":"Sentence Calc Url","KEY_CODE":"SCAL_SER_URL","VALUE":" "},{"KEY_DESC":"Jasper Server Url","KEY_CODE":"JASP_SER_URL","VALUE":" "}]' WHERE setting_type = 'serverConfig' AND setting_provider_code = 'PRODUCT';

UPDATE oms_owner.system_settings SET setting_value = '[{"KEY_DESC":"Insights Server Url","KEY_CODE":"INSI_SER_URL","VALUE":" "},{"KEY_DESC":"Get Insight Auth Token","KEY_CODE":"INS_AUTH_TOKEN","VALUE":"https://bi.elitev4.com/bi/api/site/insightstraining/token"},{"KEY_DESC":"Search Insight User","KEY_CODE":"INS_SEARCH_USER","VALUE":"https://bi.elitev4.com/bi/api/site/insightstraining/v2.0/users"},{"KEY_DESC":"Create Insight User","KEY_CODE":"INS_CREATE_USER","VALUE":"https://bi.elitev4.com/bi/api/site/insightstraining/v2.0/users"}]' WHERE setting_type = 'INSIGHTS' AND setting_provider_code = 'INSIGHTS';

--
DELETE FROM oms_owner.system_settings WHERE setting_type = 'AD' AND setting_provider_code = 'INSIGHTS';

INSERT INTO oms_owner.system_settings (setting_type,setting_provider_code,setting_value,create_datetime, create_user_id, modify_datetime, modify_user_id, seal_flag) 
  VALUES ('INSIGHTS','AUTH','[{"KEY_DESC":"Insights User","KEY_CODE":"USERNAME","VALUE":"jowdoe@syscon.com"}, {"KEY_DESC":"Insights Pasword","KEY_CODE":"PASSWORD","VALUE":"passvalue"}, {"KEY_DESC":"Insights Granttype","KEY_CODE":"GRANT_TYPE","VALUE":"password"}]',CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);
