CHK_ACTIVE_LICENCES{
SELECT 'Y' FROM DUAL WHERE EXISTS ( SELECT 'Y' FROM OFFENDER_LICENCE_SENTENCES OLS, OFFENDER_SENTENCES OS WHERE OLS.OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID AND OLS.CASE_ID = :P_CASE_ID AND OLS.OFFENDER_BOOK_ID = OS.OFFENDER_BOOK_ID AND OLS.LICENCE_SENTENCE_SEQ = OS.SENTENCE_SEQ AND OS.SENTENCE_STATUS = 'A' )
}

GET_CASE_ID{
SELECT CASE_ID FROM OFFENDER_CASES WHERE ROW_ID = :P_ROWID
}

CHK_ACTIVE_SENTENCES{
SELECT 'Y' FROM DUAL WHERE EXISTS ( SELECT 'Y' FROM OFFENDER_SENTENCES WHERE SENTENCE_CATEGORY != 'LICENCE' AND CASE_ID = :P_CASE_ID AND SENTENCE_STATUS = 'A' )
}

GET_SENTENCE_SEQ{
SELECT SENTENCE_SEQ FROM OFFENDER_SENTENCES WHERE ROW_ID = :P_ROWID
}

CHK_ACTIVE_CONDITIONS{
SELECT 'Y' FROM DUAL WHERE EXISTS ( SELECT 'Y' FROM OFFENDER_SENT_CONDITIONS WHERE OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID AND SENTENCE_SEQ = :P_SENTENCE_SEQ AND CONDITION_STATUS = 'A' )
}

CHK_ACTIVE_CASES{
SELECT 'Y' FROM DUAL WHERE EXISTS ( SELECT 'Y' FROM OFFENDER_CASES WHERE OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID AND CASE_STATUS = 'A' )
}


