update	
	json_spec
set
	json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.activePrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.activePrisonerDetails[#2].demographics.firstName","middle_name":"body.activePrisonerDetails[#2].demographics.middleName","second_middle_name":"body.activePrisonerDetails[#2].demographics.secondMiddleName","last_name":"body.activePrisonerDetails[#2].demographics.surName","sex_code":"body.activePrisonerDetails[#2].demographics.gender","birth_date":"body.activePrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_begin_date":"body.activePrisonerDetails[#2].imprisonmentDetails.intakeDatetime"}},"offenderAddresses":{"*":{"address_line1":"body.activePrisonerDetails[#2].address.address_line","street":"body.activePrisonerDetails[#2].address.street","street_number":"body.activePrisonerDetails[#2].address.street_number","street_direction":"body.activePrisonerDetails[#2].address.street_direction","suite_number":"body.activePrisonerDetails[#2].address.suite_number","city":"body.activePrisonerDetails[#2].address.city_name","city_code":"body.activePrisonerDetails[#2].address.city_code","state_code":"body.activePrisonerDetails[#2].address.state_code","country_code":"body.activePrisonerDetails[#2].address.country_code","postal":"body.activePrisonerDetails[#2].address.postal_code","address":"body.activePrisonerDetails[#2].address.unstructured_address_line","no_fixed_address_flag":"body.activePrisonerDetails[#2].address.no_address_flag"}},"offNextCourtDate":{"*":{"event_date":"body.activePrisonerDetails[#2].appearance.nextCourtDate"}},"section68Details":{"*":{"section68":"body.activePrisonerDetails[#2].sentence.section68Flag"}},"homeDestinationDetails":{"*":{"homedestination":"body.activePrisonerDetails[#2].sentence.homeDetentionFlag"}},"releaseDates":{"*":{"expected_release_date":"body.activePrisonerDetails[#2].sentence.expectedReleaseDate"}}}},{"operation":"default","spec":{"header":{"intId":"UpdatedOffenderDetails"}}},{"operation":"modify-default-beta","spec":{"body":{"activePrisonerDetails":{"*":{"demographics":{"aboriginalIndicator":"TBD"},"sentence":{"courtFileNumber":"TBD","lifeImprisonmentFlag":"TBD","fineAmount":"TBD"}}}}}}]',
	modify_datetime = current_timestamp,
	modify_user_id = 'OMS_OWNER'
where
	spec_key = 'UPDATED_ACTIVE_OFF_FORMATTER';

update	
	json_spec
set
	json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.releasedPrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.releasedPrisonerDetails[#2].demographics.firstName","middle_name":"body.releasedPrisonerDetails[#2].demographics.middleName","second_middle_name":"body.releasedPrisonerDetails[#2].demographics.secondMiddleName","last_name":"body.releasedPrisonerDetails[#2].demographics.surName","sex_code":"body.releasedPrisonerDetails[#2].demographics.gender","birth_date":"body.releasedPrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_begin_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime"}},"offenderAddresses":{"*":{"address_line1":"body.releasedPrisonerDetails[#2].address.address_line","street":"body.releasedPrisonerDetails[#2].address.street","street_number":"body.releasedPrisonerDetails[#2].address.street_number","street_direction":"body.releasedPrisonerDetails[#2].address.street_direction","suite_number":"body.releasedPrisonerDetails[#2].address.suite_number","city":"body.releasedPrisonerDetails[#2].address.city_name","city_code":"body.releasedPrisonerDetails[#2].address.city_code","state_code":"body.releasedPrisonerDetails[#2].address.state_code","country_code":"body.releasedPrisonerDetails[#2].address.country_code","postal":"body.releasedPrisonerDetails[#2].address.postal_code","address":"body.releasedPrisonerDetails[#2].address.unstructured_address_line","no_fixed_address_flag":"body.releasedPrisonerDetails[#2].address.no_address_flag"}},"offNextCourtDate":{"*":{"event_date":"body.releasedPrisonerDetails[#2].appearance.nextCourtDate"}},"section68Details":{"*":{"section68":"body.releasedPrisonerDetails[#2].sentence.section68Flag"}},"homeDestinationDetails":{"*":{"homedestination":"body.releasedPrisonerDetails[#2].sentence.homeDetentionFlag"}},"releaseDates":{"*":{"expected_release_date":"body.releasedPrisonerDetails[#2].sentence.expectedReleaseDate"}},"releaseDetails":{"*":{"release_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime"}}}},{"operation":"default","spec":{"header":{"intId":"UpdatedOffenderDetails"}}},{"operation":"modify-default-beta","spec":{"body":{"releasedPrisonerDetails":{"*":{"demographics":{"aboriginalIndicator":"TBD"},"sentence":{"courtFileNumber":"TBD","lifeImprisonmentFlag":"TBD","fineAmount":"TBD"}}}}}}]',
	modify_datetime = current_timestamp,
	modify_user_id = 'OMS_OWNER'
where
	spec_key = 'UPDATED_RELEASE_OFF_FORMATTER';
	
update
    json_spec
set
    json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":["header.intDatetime","trailer.responseDatetime"]}},"correlationId":"header.intCorrelationId","pin":"body.prisonerDetails[#2].imprisonmentDetails.pin","paroleDateDetails":{"*":{"parolecommencedate":"body.prisonerDetails[#4].release[#2].releasestartDate","paroleexpirydate":"body.prisonerDetails[#4].release[#2].releasedueEndDate"}},"paroleOrderDetails":{"*":{"number":"body.prisonerDetails[#4].release[#2].order.number","typecode":"body.prisonerDetails[#4].release[#2].order.type","origincode":"body.prisonerDetails[#4].release[#2].order.origin","issueddate":"body.prisonerDetails[#4].release[#2].order.issuedDate","orderstartdate":"body.prisonerDetails[#4].release[#2].order.orderedStartDate","orderenddate":"body.prisonerDetails[#4].release[#2].order.orderedEndDate","par_matter":"body.prisonerDetails[#4].release[#2].orderCourtFileNumber"}},"paroleConditionDetails":{"*":{"conditions":{"value":{"*":"body.prisonerDetails[#4].release[#2].order.condition[]"}}}}}},{"operation":"modify-default-beta","spec":{"body":{"prisonerDetails":{"*":{"release":{"*":{"orderCourtFileNumber":"TBD","order":{"condition":{}}}}}}}}},{"operation":"default","spec":{"header":{"intId":"ParoleConditions"},"trailer":{"respCode":"SUCCESS","errMsg":""}}}]',
    modify_datetime = current_timestamp,
    modify_user_id = 'OMS_OWNER'
where
    spec_key = 'PAROLE_COND_RESPONSE_FORMATTER'; 	