INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE) 
 SELECT 'SIG_INC_TYPE', 'Significant Incident Type', 'ACTIVE', 'ADMIN', 'TAG' 
   FROM dual 
 WHERE NOT EXISTS (SELECT 1 FROM REFERENCE_DOMAINS WHERE domain = 'SIG_INC_TYPE'); 

COMMIT;



