INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2) 
  SELECT 'DB','AD_DF_PWD','AD Default PWD','&password', NULL
    FROM dual 
  WHERE NOT EXISTS (SELECT 'Y' FROM system_profiles WHERE PROFILE_TYPE = 'DB' AND PROFILE_CODE = 'AD_DF_PWD');


UPDATE SYSTEM_PROFILES 
   SET PROFILE_VALUE = '&password'
      ,PROFILE_VALUE_2 = NULL 
 WHERE PROFILE_TYPE = 'DB' 
   AND PROFILE_CODE = 'AD_DF_PWD';


COMMIT;

