INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2) 
  SELECT 'DB','AD_RED_URI','AD Redirect Uril','https%3A%2F%2Fmvp.astriasvc.com%3A8081', NULL
    FROM dual 
  WHERE NOT EXISTS (SELECT 'Y' FROM system_profiles WHERE PROFILE_TYPE = 'DB' AND PROFILE_CODE = 'AD_RED_URI');


UPDATE SYSTEM_PROFILES 
   SET PROFILE_VALUE = 'https%3A%2F%2Fmvp.astriasvc.com%3A8081'
      ,PROFILE_VALUE_2 = NULL 
 WHERE PROFILE_TYPE = 'DB' 
   AND PROFILE_CODE = 'AD_RED_URI';


COMMIT;

