INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE,
 PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID )
VALUES('CELL_CNDITNS','Cell Conditions List Of Config Values', 'ACTIVE', 'OMS_OWNER', 'OMS', NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL);

INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE,
 PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID )
VALUES('ACTIVITY','Off Obs Activity List Of Config Values', 'ACTIVE', 'OMS_OWNER', 'OMS', NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL);

INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE,
 PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID )
VALUES('COM_DET_CAT','Demeanor List Of Configuration Values', 'ACTIVE', 'OMS_OWNER', 'OMS', NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL);

INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE,
 PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID )
VALUES('NOT_IN_CELL','Off Obs NotInCell List Of Config Values', 'ACTIVE', 'OMS_OWNER', 'OMS', NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL);

INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE,
 PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID )
VALUES('OBSRVATN_TYP','Off Obs Type List Of Config Values', 'ACTIVE', 'OMS_OWNER', 'OMS', NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL);

INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE,
 PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID )
VALUES('OBSRVTN_ZONE','Zone Configurations for observations', 'ACTIVE', 'OMS_OWNER', 'OMS', NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL);

INSERT INTO REFERENCE_DOMAINS (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE,
 PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID )
VALUES('END_RSN_CODE','OffObsPer EndRsnCode List of config val', 'ACTIVE', 'OMS_OWNER', 'OMS', NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, NULL);

