--'KEY_DATES'
INSERT INTO oms_owner.reference_codes(domain, code, description, list_seq, active_flag, system_data_flag,  expired_date, new_code, parent_code, parent_domain, create_datetime, create_user_id, modify_datetime, modify_user_id,seal_flag)
VALUES('KEY_DATES', 'indefinite', 'Indefinite', NULL, 'Y', 'N',  NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, 'OMS_OWNER', CURRENT_TIMESTAMP, NULL, NULL);

--'CELL_CNDITNS'
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('CELL_CNDITNS' ,'TRASH' ,'Trashed' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('CELL_CNDITNS' ,'TIDY' ,'Tidy' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('CELL_CNDITNS' ,'EPTY_ITE_RE' ,'Empty_Items Removed for safety' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('CELL_CNDITNS' ,'NO_OUT_ORD' ,'Nothing out of ordinary' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('CELL_CNDITNS' ,'WET' ,'wet floor' ,5,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

--'ACTIVITY'
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('ACTIVITY' ,'TALK_TO_OFFC' ,'Talking to officer' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('ACTIVITY' ,'STAND_STILL' ,'Standing Still' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('ACTIVITY' ,'USE_TOILET' ,'Using Toilet' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('ACTIVITY' ,'NO_CHANGE' ,'No Change' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('ACTIVITY' ,'ROCK' ,'Rocking' ,5,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('ACTIVITY' ,'MUTTER_SELF' ,'Muttering to self' ,6,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

--'COM_DET_CAT'
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('COM_DET_CAT' ,'OPT1' ,'Option1' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('COM_DET_CAT' ,'OPT2' ,'Option2' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('COM_DET_CAT' ,'OPT3' ,'Option3' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('COM_DET_CAT' ,'OPT4' ,'Option4' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

--'NOT_IN_CELL' 
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('NOT_IN_CELL' ,'CRT_APPEAR' ,'Court Appearence' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('NOT_IN_CELL' ,'MEDICAL_APT' ,'Medical Appointment' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('NOT_IN_CELL' ,'SCH_VISIT' ,'Scheduled Visit' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('NOT_IN_CELL' ,'PAROLE_HEAR' ,'Parole Hearing' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

--'OBSRVATN_TYP'
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVATN_TYP' ,'EYE_3X' ,'Eyes On 3X' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVATN_TYP' ,'SUC_CONT' ,'Sucide Continuous' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVATN_TYP' ,'SUC_SEL_HRM1' ,'Sucide Self Harm-Lvl1' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVATN_TYP' ,'SUC_SEL_HRM2' ,'Sucide Self Harm-Lvl2' ,4,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVATN_TYP' ,'CAMERA EYE' ,'Camera eye' ,5,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

--'OBSRVTN_ZONE' 
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVTN_ZONE' ,'ZONE1-A' ,'Zone 1 A' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVTN_ZONE' ,'ZONE1-B' ,'Zone 1 B' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('OBSRVTN_ZONE' ,'ZONE2-A' ,'Zone 2 B' ,3,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

--'END_RSN_CODE'
INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,
EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('END_RSN_CODE' ,'END_RSN1' ,'End Date Reached' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,
'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

