
OCUWARNG_ALLOWED_OVERRIDE {
    SELECT 'Y'
FROM
  STAFF_MEMBER_ROLES SMR, OMS_ROLES R
WHERE
  SMR.ROLE_ID = R.ROLE_ID AND
  UPPER(R.ROLE_CODE) = 'MOVE_ADMIN' AND
  SMR.STAFF_ID IN
    (SELECT STAFF_ID
     FROM STAFF_MEMBERS
     WHERE
       UPPER(USER_ID) = :createUserId AND
       STATUS = 'ACTIVE')



 }