
OIDCHOLO_FIND_CGFKCRTMVTMPMOVEMENTREASO {
 	SELECT REF_CODE2.CODE          ,REF_CODE2.DOMAIN       ,REF_CODE2.DESCRIPTION  FROM   REFERENCE_CODES REF_CODE2 WHERE   REF_CODE2.DOMAIN = 'CHG_HOUS_RSN' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ ,CODE ,DESCRIPTION
}

OIDCHOLO_FIND_CGFKBEDAHDSPDESCRIPTION {
 	SELECT REF_CODE3.CODE DSP_DESCRIPTION         ,REF_CODE3.DOMAIN DSP_DOMAIN       
 	,REF_CODE3.CODE ASSIGNMENT_REASON         ,REF_CODE3.DESCRIPTION CGNBT_DUMMY  
 	FROM REFERENCE_CODES REF_CODE3  WHERE REF_CODE3.DOMAIN = 'CHG_HOUS_RSN'  AND 
 	((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) ) ORDER BY LIST_SEQ ,CODE ,DESCRIPTION

}

OIDCHOLO_FIND_CGFKBEDAHDSPOFFENDERIDDI {
 	SELECT V_OFF_BKG.OFFENDER_ID_DISPLAY DSP_OFFENDER_ID_DISPLAY   ,
 	V_OFF_BKG.LAST_NAME DSP_LAST_NAME  ,V_OFF_BKG.FIRST_NAME DSP_FIRST_NAME  ,
 	V_OFF_BKG.LIVING_UNIT_DESCRIPTION DSP_LIVING_UNIT_DESCRIPTION  ,V_OFF_BKG.OFFENDER_BOOK_ID OFFENDER_BOOK_ID
 	FROM V_HEADER_BLOCK_FN(:USERID) V_OFF_BKG WHERE ACTIVE_FLAG = 'Y' AND AGY_LOC_ID = :AGYLOCID AND 
 	BOOKING_BEGIN_DATE = (SELECT MAX(OB.BOOKING_BEGIN_DATE ) FROM OFFENDER_BOOKINGS OB 
 	WHERE OB.OFFENDER_ID = V_OFF_BKG.OFFENDER_ID ) AND EXISTS 
 	(SELECT 'X' FROM CASELOAD_AGENCY_LOCATIONS CAL WHERE CAL.CASELOAD_ID =:CASELOADID 
 	AND CAL.AGY_LOC_ID = V_OFF_BKG.AGY_LOC_ID AND CAL.AGY_LOC_ID NOT IN ('OUT' , 'TRN' )  ) ORDER BY V_OFF_BKG.LAST_NAME
 	

}

OIDCHOLO_FIND_CGFKCRTMVTMPDSPLIVING4 {
 	SELECT LIV_UNIT.LIVING_UNIT_CODE,LIV_UNIT.CAPACITY ,LIV_UNIT.LIVING_UNIT_ID , LIV_UNIT.LIST_SEQ, LIV_UNIT.ACTIVE_FLAG FROM   LIVING_UNITS LIV_UNIT WHERE   AGY_LOC_ID = :AGYLOCID AND (ACTIVE_FLAG = 'Y' OR '' = 'ENTER-QUERY' ) AND PARENT_LIVING_UNIT_ID IS NULL ORDER BY LIST_SEQ ,LIVING_UNIT_CODE
}

OIDCHOLO_FIND_CGFKCRTMVTMPDSPLIVING3 {
 	SELECT LIV_UNIT1.LIVING_UNIT_CODE,LIV_UNIT1.CAPACITY,LIV_UNIT1.LIVING_UNIT_ID, LIV_UNIT1.ACTIVE_FLAG FROM   LIVING_UNITS LIV_UNIT1 WHERE   AGY_LOC_ID = :AGYLOCID AND (ACTIVE_FLAG = 'Y' OR '' = 'ENTER-QUERY' ) AND PARENT_LIVING_UNIT_ID IN (SELECT LIVING_UNIT_ID 
                                              	FROM LIVING_UNITS 
                                              	WHERE LIVING_UNIT_CODE = :LIVINGUNITID1)  ORDER BY LIST_SEQ ,LIVING_UNIT_CODE
}

OIDCHOLO_FIND_CGFKCRTMVTMPDSPLIVING2 {
 	SELECT LIV_UNIT2.LIVING_UNIT_CODE  DSP_LIVING_UNIT_CODE3          ,LIV_UNIT2.CAPACITY  DSP_CAPACITY2  
 	,LIV_UNIT2.LIVING_UNIT_ID  LIVING_UNIT_ID3 FROM   LIVING_UNITS LIV_UNIT2 WHERE   AGY_LOC_ID =  :AGYLOCID 
 	AND (ACTIVE_FLAG = 'Y' ) AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID2 
 	ORDER BY LIST_SEQ ,LIVING_UNIT_CODE

}

OIDCHOLO_FIND_CGFKCRTMVTMPDSPLIVINGUNI {
 	SELECT LIV_UNIT3.LIVING_UNIT_CODE  DSP_LIVING_UNIT_CODE         ,LIV_UNIT3.CAPACITY  DSP_CAPACITY        ,LIV_UNIT3.LIVING_UNIT_ID  LIVING_UNIT_ID4 FROM   LIVING_UNITS LIV_UNIT3 WHERE  
 	AGY_LOC_ID = :AGYLOCID AND (ACTIVE_FLAG = 'Y'  ) AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID3 
 	ORDER BY LIST_SEQ ,LIVING_UNIT_CODE

}

OIDCHOLO_FIND_CGFKCRTMVTMPAGYLOCID {
 	SELECT AGY_LOC.AGY_LOC_ID  CODE ,AGY_LOC.DESCRIPTION  DESCRIPTION,  AGY_LOC.ACTIVE_FLAG FROM   AGENCY_LOCATIONS AGY_LOC WHERE   AGY_LOC.AGY_LOC_ID  IN (SELECT CA.AGY_LOC_ID    FROM CASELOAD_AGENCY_LOCATIONS CA WHERE CA.CASELOAD_ID  = :CASELOADID AND CA.AGY_LOC_ID NOT IN ('OUT' , 'TRN' ) ) ORDER BY AGY_LOC_ID ,DESCRIPTION
}

OIDCHOLO_CRTMVTMP_FIND_COURT_MOVEMENT_TMP {
select
	vhb.offender_id_display ,
	vhb.last_name ,
	vhb.first_name ,
	vhb.living_unit_id ,
	vhb.BOOKING_BEGIN_DATE ,
	vhb.living_unit_description ,
	vhb.offender_book_id ,
	bah.ASSIGNMENT_DATE ,
	bah.ASSIGNMENT_TIME ,
	vhb.ACTIVE_FLAG
from
	V_HEADER_BLOCK_FN(:USERID) vhb ,
	bed_assignment_histories bah
where
	vhb.agy_loc_id = :agyLocId
	and vhb.OFFENDER_BOOK_ID = bah.OFFENDER_BOOK_ID
	and bah.BED_ASSIGN_SEQ = (
	select
		max(BED_ASSIGN_SEQ)
	from
		bed_assignment_histories
	where
		OFFENDER_BOOK_ID = bah.OFFENDER_BOOK_ID)
	and (coalesce(:level1Code ::text, '') = ''
		or exists (
		select
			1
		from
			living_units lu
		where
			LIVING_UNIT_CODE = :level1Code
			and vhb.living_unit_id in (
			select
				LIVING_UNIT_ID
			from
				LIVING_UNITS
			where
				LEVEL_1_CODE = :level1Code) ))
	and (coalesce(:level2Code ::text, '') = ''
		or exists (
		select
			1
		from
			living_units lu
		where
			LIVING_UNIT_CODE = :level2Code
			and vhb.living_unit_id in (
			select
				LIVING_UNIT_ID
			from
				LIVING_UNITS
			where
				LEVEL_2_CODE = :level2Code) ))
	and (coalesce(:level3Code ::text, '') = ''
		or exists (
		select
			1
		from
			living_units lu
		where
			LIVING_UNIT_CODE = :level3Code
			and vhb.living_unit_id in (
			select
				LIVING_UNIT_ID
			from
				LIVING_UNITS
			where
				LEVEL_3_CODE = :level3Code) ))
	and (coalesce(:level4Code ::text, '') = ''
		or exists (
		select
			1
		from
			living_units lu
		where
			LIVING_UNIT_CODE = :level4Code
			and vhb.living_unit_id in (
			select
				LIVING_UNIT_ID
			from
				LIVING_UNITS
			where
				LEVEL_4_CODE = :level4Code) ))
	and booking_begin_date = (
	select
		max(ob.booking_begin_date)
	from
		offender_bookings ob
	where
		ob.offender_id = vhb.offender_id
		and coalesce(ob.booking_type, 'INST')= 'INST')
	and exists (
	select
		'X'
	from
		caseload_agency_locations cal
	where
		cal.caseload_id = (
		select
			WORKING_CASELOAD_ID
		from
			STAFF_MEMBERS
		where
			USER_ID = :USER_ID)
		and cal.agy_loc_id = vhb.agy_loc_id
		and cal.agy_loc_id not in ('TRN', 'OUT'))
order by
	vhb.last_name

}
OIDCHOLO_CRTMVTMP_INSERT_COURT_MOVEMENT_TMP {
INSERT INTO BED_ASSIGNMENT_HISTORIES(OFFENDER_BOOK_ID,
                                             BED_ASSIGN_SEQ,
                                             LIVING_UNIT_ID,
                                             ASSIGNMENT_DATE,
                                             ASSIGNMENT_TIME,
                                             ASSIGNMENT_REASON,
                                             CREATE_DATETIME ,
                                             CREATE_USER_ID ,
                                             MODIFY_DATETIME)
                                        VALUES(:offenderBookId,
                                              (SELECT (COALESCE(MAX(BED_ASSIGN_SEQ),0) + 1)
       											FROM BED_ASSIGNMENT_HISTORIES
      											WHERE OFFENDER_BOOK_ID = :offenderBookId),
                                              (SELECT LIVING_UNIT_ID 
                                              	FROM LIVING_UNITS 
                                              	WHERE DESCRIPTION = :dspDescription),
                                              :assignmentDate,
                                              :assignmentTime,
                                              :assignmentReason,
                                              current_timestamp ,
                                              :createUserId ,
                                              null)

}

OIDCHOLO_CRTMVTMP_UPDATE_COURT_MOVEMENT_TMP {
update bed_assignment_histories set ASSIGNMENT_END_DATE = date_trunc('D',:assignmentEndDate::timestamp), ASSIGNMENT_END_TIME = :assignmentEndTime, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID =:modifyUserId where offender_book_id = :offenderBookId and bed_assign_seq = ( select coalesce(MAX(BED_ASSIGN_SEQ), 0) from BED_ASSIGNMENT_HISTORIES where OFFENDER_BOOK_ID = :offenderBookId)
}

OIDCHOLO_CRTMVTMP_UPDATE_OFFBKGS {
UPDATE offender_bookings 
      SET agy_loc_id       = :agyLocId,
          living_unit_id   = (SELECT LIVING_UNIT_ID 
                                     FROM LIVING_UNITS 
                                     WHERE DESCRIPTION = :cgnbtBookingStatus),
          MODIFY_DATETIME = current_timestamp,
          MODIFY_USER_ID =:modifyUserId                           
    WHERE offender_book_id = :offenderBookId
}

OIDCHOLO_CRTMVTMP_DELETE_COURT_MOVEMENT_TMP { 
	DELETE FROM COURT_MOVEMENT_TMP
}


OIDCHOLO_CGFKCHK_CRT_MV_TMP_CRT_MV_TMP_ {
	SELECT REF_CODE2.DOMAIN ,REF_CODE2.DESCRIPTION FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.CODE = :MOVEMENTREASON AND     REF_CODE2.DOMAIN = 'CHG_HOUS_RSN' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OIDCHOLO_CGFKCHK_CRT_MV_TMP_CRT_MV_2_ {
	SELECT AGY_LOC.DESCRIPTION FROM   AGENCY_LOCATIONS AGY_LOC WHERE  AGY_LOC.AGY_LOC_ID = :AGYLOCID AND     AGY_LOC.AGY_LOC_ID  IN (SELECT CA.AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS CA WHERE CA.CASELOAD_ID  = :CASELOADID AND CA.AGY_LOC_ID NOT IN ('OUT', 'TRN'))
}

OIDCHOLO_CGFKCHK_CRT_MV_TMP_CRT_MV_3_ {
	SELECT LIV_UNIT3.LIVING_UNIT_CODE ,LIV_UNIT3.CAPACITY FROM   LIVING_UNITS LIV_UNIT3 WHERE  LIV_UNIT3.LIVING_UNIT_ID = :LIVINGUNITID4 AND     AGY_LOC_ID = :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID3
}

OIDCHOLO_CGFKLKP_CRT_MV_TMP_CRT_MV_TMP_ {
	SELECT LIV_UNIT3.LIVING_UNIT_ID ,LIV_UNIT3.CAPACITY FROM   LIVING_UNITS LIV_UNIT3 WHERE  (LIV_UNIT3.LIVING_UNIT_CODE = :DSPLIVINGUNITCODE OR (LIV_UNIT3.LIVING_UNIT_CODE IS NULL AND :DSPLIVINGUNITCODE IS NULL )) AND     AGY_LOC_ID = :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID3
}

OIDCHOLO_CGFKCHK_CRT_MV_TMP_CRT_MV_4_ {
	SELECT LIV_UNIT2.LIVING_UNIT_CODE ,LIV_UNIT2.CAPACITY FROM   LIVING_UNITS LIV_UNIT2 WHERE  LIV_UNIT2.LIVING_UNIT_ID = :LIVINGUNITID3 AND     AGY_LOC_ID =  :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID2
}

OIDCHOLO_CGFKLKP_CRT_MV_TMP_CRT_MV_2_ {
	SELECT LIV_UNIT2.LIVING_UNIT_ID ,LIV_UNIT2.CAPACITY FROM   LIVING_UNITS LIV_UNIT2 WHERE  (LIV_UNIT2.LIVING_UNIT_CODE = :DSPLIVINGUNITCODE3 OR (LIV_UNIT2.LIVING_UNIT_CODE IS NULL AND :DSPLIVINGUNITCODE3 IS NULL )) AND     AGY_LOC_ID =  :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID2
}

OIDCHOLO_CGFKCHK_CRT_MV_TMP_CRT_MV_5_ {
	SELECT LIV_UNIT1.LIVING_UNIT_CODE ,LIV_UNIT1.CAPACITY FROM   LIVING_UNITS LIV_UNIT1 WHERE  LIV_UNIT1.LIVING_UNIT_ID = :LIVINGUNITID2 AND     AGY_LOC_ID = :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID1
}

OIDCHOLO_CGFKLKP_CRT_MV_TMP_CRT_MV_3_ {
	SELECT LIV_UNIT1.LIVING_UNIT_ID ,LIV_UNIT1.CAPACITY FROM   LIVING_UNITS LIV_UNIT1 WHERE  (LIV_UNIT1.LIVING_UNIT_CODE = :DSPLIVINGUNITCODE4 OR (LIV_UNIT1.LIVING_UNIT_CODE IS NULL AND :DSPLIVINGUNITCODE4 IS NULL )) AND     AGY_LOC_ID = :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID1
}

OIDCHOLO_CGFKCHK_CRT_MV_TMP_CRT_MV_6_ {
	SELECT LIV_UNIT.LIVING_UNIT_CODE ,LIV_UNIT.CAPACITY FROM   LIVING_UNITS LIV_UNIT WHERE  LIV_UNIT.LIVING_UNIT_ID = :LIVINGUNITID1 AND     AGY_LOC_ID = :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID IS NULL
}

OIDCHOLO_CGFKLKP_CRT_MV_TMP_CRT_MV_4_ {
	SELECT LIV_UNIT.LIVING_UNIT_ID ,LIV_UNIT.CAPACITY FROM   LIVING_UNITS LIV_UNIT WHERE  (LIV_UNIT.LIVING_UNIT_CODE = :DSPLIVINGUNITCODE5 OR (LIV_UNIT.LIVING_UNIT_CODE IS NULL AND :DSPLIVINGUNITCODE5 IS NULL )) AND     AGY_LOC_ID = :AGYLOCID AND ACTIVE_FLAG = 'Y' AND PARENT_LIVING_UNIT_ID IS NULL
}

OIDCHOLO_CGFKCHK_BED_AH_BED_AH_VHB_F1_ {
	SELECT V_OFF_BKG.ROOT_OFFENDER_ID ,V_OFF_BKG.LAST_NAME ,V_OFF_BKG.FIRST_NAME ,V_OFF_BKG.LIVING_UNIT_DESCRIPTION FROM  V_HEADER_BLOCK_FN(:USERID)  V_OFF_BKG WHERE  V_OFF_BKG.OFFENDER_BOOK_ID = :OFFENDERBOOKID AND     ACTIVE_FLAG = 'Y' AND AGY_LOC_ID = :AGYLOCID AND BOOKING_BEGIN_DATE = (SELECT MAX(OB.BOOKING_BEGIN_DATE) FROM  OFFENDER_BOOKINGS OB WHERE OB.OFFENDER_ID = OFFENDER_ID AND OB.BOOKING_TYPE = 'INST')
}

OIDCHOLO_CGFKLKP_BED_AH_BED_AH_VHB_F1_ {
	SELECT V_OFF_BKG.OFFENDER_BOOK_ID ,V_OFF_BKG.ROOT_OFFENDER_ID ,V_OFF_BKG.LAST_NAME ,V_OFF_BKG.FIRST_NAME ,V_OFF_BKG.LIVING_UNIT_DESCRIPTION FROM   V_HEADER_BLOCK_FN(:USERID) V_OFF_BKG WHERE  (V_OFF_BKG.ROOT_OFFENDER_ID = :DSPOFFENDERIDDISPLAY OR (V_OFF_BKG.ROOT_OFFENDER_ID IS NULL AND :DSPOFFENDERIDDISPLAY IS NULL )) AND    (V_OFF_BKG.LAST_NAME = :DSPLASTNAME OR (V_OFF_BKG.LAST_NAME IS NULL AND :DSPLASTNAME IS NULL )) AND    (V_OFF_BKG.FIRST_NAME = :DSPFIRSTNAME OR (V_OFF_BKG.FIRST_NAME IS NULL AND :DSPFIRSTNAME IS NULL )) AND    (V_OFF_BKG.LIVING_UNIT_DESCRIPTION = :DSPLIVINGUNITDESCRIPTION OR (V_OFF_BKG.LIVING_UNIT_DESCRIPTION IS NULL AND :DSPLIVINGUNITDESCRIPTION IS NULL )) AND     ACTIVE_FLAG = 'Y' AND AGY_LOC_ID = :AGYLOCID AND BOOKING_BEGIN_DATE = (SELECT MAX(OB.BOOKING_BEGIN_DATE) FROM  OFFENDER_BOOKINGS OB WHERE OB.OFFENDER_ID = OFFENDER_ID) AND EXISTS (SELECT 'X' FROM CASELOAD_AGENCY_LOCATIONS CAL WHERE CAL.CASELOAD_ID =:CASELOADID AND CAL.AGY_LOC_ID = AGY_LOC_ID AND CAL.AGY_LOC_ID NOT IN ('OUT', 'TRN') ) ORDER BY V_OFF_BKG.LAST_NAME
}

OIDCHOLO_CGFKCHK_BED_AH_BED_AH_REF_COD_ {
	SELECT REF_CODE3.DOMAIN ,REF_CODE3.CODE ,REF_CODE3.DESCRIPTION FROM   REFERENCE_CODES REF_CODE3 WHERE  REF_CODE3.CODE = :ASSIGNMENTREASON AND     REF_CODE3.DOMAIN = 'CHG_HOUS_RSN' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OIDCHOLO_CGFKLKP_BED_AH_BED_AH_REF_COD_ {
	SELECT REF_CODE3.CODE ,REF_CODE3.CODE ,REF_CODE3.DOMAIN FROM   REFERENCE_CODES REF_CODE3 WHERE  (REF_CODE3.DESCRIPTION = :DSPDESCRIPTION OR (REF_CODE3.DESCRIPTION IS NULL AND :DSPDESCRIPTION IS NULL )) AND     REF_CODE3.DOMAIN = 'CHG_HOUS_RSN' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}
OIDCHOLO_CGFKLKP_BED_AH_BED_DATETIME_PROC {
select LAH.ASSIGNMENT_DATE, LAH.ASSIGNMENT_TIME, BOOKING_BEGIN_DATE from BED_ASSIGNMENT_HISTORIES LAH, OFFENDER_BOOKINGS OB where LAH.LIVING_UNIT_ID = :livingUnitId and LAH.OFFENDER_BOOK_ID = :offenderBookId and OB.OFFENDER_BOOK_ID = LAH.OFFENDER_BOOK_ID order by LAH.BED_ASSIGN_SEQ desc limit 1
}

GET_OLD_REC_OFF_BOOKING {
select * from offender_bookings where offender_book_id = :offender_book_id 
}
