
OIDRHLOC_FIND_CGFKRESBLAGYLOCID {
   select
	CASELOAD_AGENCY_LOCATIONS.AGY_LOC_ID CODE
	,
	CASELOAD_AGENCY_LOCATIONS.CASELOAD_ID CASELOAD_ID ,
	AGENCY_LOCATIONS.DESCRIPTION DESCRIPTION ,
	AGENCY_LOCATIONS.ACTIVE_FLAG,
	CASELOAD_AGENCY_LOCATIONS.UPDATE_ALLOWED_FLAG UPDATE_ALLOWED_FLAG
from
	CASELOAD_AGENCY_LOCATIONS CASELOAD_AGENCY_LOCATIONS ,
	AGENCY_LOCATIONS AGENCY_LOCATIONS
where
	CASELOAD_AGENCY_LOCATIONS.CASELOAD_ID = :CASELOADID
	and CASELOAD_AGENCY_LOCATIONS.AGY_LOC_ID not in ('OUT' , 'TRN' )
	and CASELOAD_AGENCY_LOCATIONS.AGY_LOC_ID = AGENCY_LOCATIONS.AGY_LOC_ID
}

OIDRHLOC_RESBL_FIND_RESERVE_BED_LOCATIONS {
    select
	AGY_LOC_ID ,
	LIVING_UNIT_ID ,
	RESERVE_UNTIL_DATE ,
	REMOVE_REASON ,
	COMMENT_TEXT ,
	OFFENDER_ID ,
	RESERVE_BED_ID ,
	CREATE_DATETIME ,
	CREATE_USER_ID ,
	MODIFY_DATETIME ,
	MODIFY_USER_ID ,
	SEAL_FLAG
from
	RESERVE_BED_LOCATIONS reserve_bed_locations
where
	RESERVE_UNTIL_DATE >= date_trunc('day'::text, LOCALTIMESTAMP)
	and exists 
    (
	select
		1
	from
		caseload_agency_locations CAL
	where
		CAL.caseload_id = :CASELOADID
		and CAL.agy_loc_id = reserve_bed_locations.agy_loc_id )
order by
	LIVING_UNIT_ID,
	RESERVE_UNTIL_DATE
}
OIDRHLOC_RESBL_INSERT_RESERVE_BED_LOCATIONS {
	INSERT INTO RESERVE_BED_LOCATIONS(RESERVE_BED_ID, AGY_LOC_ID ,LIVING_UNIT_ID ,RESERVE_UNTIL_DATE ,REMOVE_REASON ,COMMENT_TEXT ,OFFENDER_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG )
	      VALUES(nextval('RESERVE_BED_ID'), :agyLocId ,:livingUnitId ,:reserveUntilDate ,:removeReason ,:commentText ,:offenderId ,CURRENT_TIMESTAMP,:createUserId ,null,null,:sealFlag )
}

OIDRHLOC_RESBL_UPDATE_RESERVE_BED_LOCATIONS {
	UPDATE RESERVE_BED_LOCATIONS set AGY_LOC_ID  = :agyLocId ,LIVING_UNIT_ID  = :livingUnitId ,RESERVE_UNTIL_DATE  = :reserveUntilDate ,REMOVE_REASON  = :removeReason ,COMMENT_TEXT  = :commentText ,OFFENDER_ID  = :offenderId  ,MODIFY_DATETIME  =CURRENT_TIMESTAMP,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag 
	 where  RESERVE_BED_ID  = :reserveBedId
}

OIDRHLOC_RESBL_DELETE_RESERVE_BED_LOCATIONS { 
	DELETE FROM RESERVE_BED_LOCATIONS  where  RESERVE_BED_ID = :reserveBedId
}


OIDRHLOC_CGFKCHK_RES_BL_RES_BL_CSLD_AL {
select
	CASELOAD_AGENCY_LOCATIONS.CASELOAD_ID ,
	CASELOAD_AGENCY_LOCATIONS.UPDATE_ALLOWED_FLAG
from
	CASELOAD_AGENCY_LOCATIONS CASELOAD_AGENCY_LOCATIONS
where
	CASELOAD_AGENCY_LOCATIONS.AGY_LOC_ID = :AGYLOCID
	and CASELOAD_AGENCY_LOCATIONS.CASELOAD_ID = :CASELOADID
	and CASELOAD_AGENCY_LOCATIONS.AGY_LOC_ID not in ('OUT', 'TRN')
}

OIDRHLOC_GET_LIVING_UNIT_DESC {
  SELECT AGY_LOC_ID,LIVING_UNIT_ID, DESCRIPTION FROM LIVING_UNITS WHERE LIVING_UNIT_ID = :LIVING_UNIT_ID
}
OIDRHLOC_GET_OFFENDER_DETAILS {
 select
	OFF.LAST_NAME,
	OFF.FIRST_NAME,
	OFF.ROOT_OFFENDER_ID,
	OFF.OFFENDER_ID_DISPLAY
from
	OFFENDERS off,
	OFFENDER_BOOKINGS OFF_BKG
where
	OFF.ROOT_OFFENDER_ID in (
	select
		ROOT_OFFENDER_ID
	from
		OFFENDERS
	where
		OFFENDERS.OFFENDER_ID = :OFFENDER_ID)
	and OFF.OFFENDER_ID = OFF_BKG.OFFENDER_ID
	and OFF_BKG.OFFENDER_BOOK_ID = (
	select
		MAX(OFFENDER_BOOK_ID)
	from
		OFFENDER_BOOKINGS OFF_BKG1
	where
		OFF_BKG1.ROOT_OFFENDER_ID = OFF_BKG.ROOT_OFFENDER_ID
		and OFF_BKG1.BOOKING_TYPE = 'INST');
}

OIDRHLOC_VALIDATE_LIV_UNIT_ID {
select
	off_bkg.offender_book_id
from
	offender_bookings off_bkg,
	living_units lu
where
	off_bkg.offender_book_id = :offender_book_id
	and off_bkg.agy_loc_id = lu.agy_loc_id
	and lu.living_unit_id = :living_unit_id
	and lu.active_flag = 'Y'
}

OIDRHLOC_ALLOW_OVERRIDE {
 select
	'Y'
from
	STAFF_MEMBER_ROLES SMR,
	OMS_ROLES R
where
	SMR.ROLE_ID = R.ROLE_ID
	and UPPER(R.ROLE_CODE) = 'MOVE_ADMIN'
	and SMR.STAFF_ID in (
	select
		STAFF_ID
	from
		STAFF_MEMBERS
	where
		UPPER(USER_ID) = 'OMS_OWNER'
			and STATUS = 'ACTIVE')
}
 
 OIDRHLOC_GET_OFFENDER_BOOK_ID {
SELECT OFFENDER_BOOK_ID FROM V_HEADER_BLOCK V WHERE V.OFFENDER_ID = :OFFENDER_ID AND
 AGY_LOC_ID IN (SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :CASELOAD_ID ) 
							 AND OFFENDER_BOOK_ID IN( SELECT OFFENDER_BOOK_ID FROM (SELECT *  FROM OFFENDER_BOOKINGS 
							 ORDER BY BOOKING_END_DATE DESC) WHERE ROOT_OFFENDER_ID = V.ROOT_OFFENDER_ID AND ROWNUM = 1)
							 ORDER BY   LAST_NAME ASC,FIRST_NAME ASC
 }
 OIDRHLOC_GET_CB_FLAG {
select
	AGY_LOC_ID,
	LIVING_UNIT_ID,
	DESCRIPTION
from
	LIVING_UNITS
where
	LIVING_UNIT_ID in (
	select
		OFF_BKG.LIVING_UNIT_ID
	from
		OFFENDER_BOOKINGS OFF_BKG
	where
		OFF_BKG.ROOT_OFFENDER_ID = :ROOT_OFFENDER_ID
		and OFF_BKG.OFFENDER_BOOK_ID = (
		select
			MAX(OFFENDER_BOOK_ID)
			from OFFENDER_BOOKINGS
		where
			BOOKING_TYPE = 'INST'
			and ROOT_OFFENDER_ID = OFF_BKG.ROOT_OFFENDER_ID)
		and OFF_BKG.AGY_LOC_ID in (
		select
			CAL.AGY_LOC_ID
		from
			CASELOAD_AGENCY_LOCATIONS CAL
		where
			CAL.CASELOAD_ID = :CASELOAD_ID))
 }

 OIDRHLOC_GET_V_CAPACITY {
 select
	coalesce (CAPACITY,
	0)
from
	LIVING_UNITS
where
	LIVING_UNIT_ID = :LIVING_UNIT_ID
	and ACTIVE_FLAG = 'Y'
}

OIDRHLOC_GET_OCC_COUNT_CUR{
   SELECT COUNT(1) FROM OFFENDER_BOOKINGS WHERE LIVING_UNIT_ID = :LIVING_UNIT_ID
}

OIDRHLOC_GET_BOOKING_INFO_CUR {
select
	off_bkg.offender_book_id
from
	offender_bookings off_bkg
where
	off_bkg.root_offender_id = :root_offender_id
	and off_bkg.offender_book_id = (
	select
		MAX(offender_book_id)
	from
		offender_bookings
	where
		booking_type = 'INST'
		and root_offender_id = off_bkg.root_offender_id)
	and off_bkg.agy_loc_id in (
	select
		cal.agy_loc_id
	from
		caseload_agency_locations cal
	where
		cal.caseload_id = :caseload_id)
                                                                 }