
OIIEMOVE_FIND_RGOFFEMMOVEMENTREASONCO {
 	select REF_CODE2.DESCRIPTION DESCRIPTION , REF_CODE2.CODE CODE , REF_CODE2.DOMAIN dom , REF_CODE2.EXPIRED_DATE EXPIREDDATE from REFERENCE_CODES REF_CODE2 where domain = 'MOVE_RSN' and ( (ACTIVE_FLAG = 'Y' and coalesce (EXPIRED_DATE::timestamp, '2020-12-12')= '2020-12-12' ) or ( :mode = 'ENTER-QUERY' ) ) order by REF_CODE2.LIST_SEQ , REF_CODE2.DESCRIPTION , REF_CODE2.CODE
}

OIIEMOVE_FIND_RGOFFEMMOVEMENTTYPE {
 	select REF_CODE.DESCRIPTION DESCRIPTION , REF_CODE.CODE CODE , REF_CODE.EXPIRED_DATE EXPIREDDATE from REFERENCE_CODES REF_CODE where domain = 'MOVE_TYPE' and ( (ACTIVE_FLAG = 'Y' and coalesce(expired_date::timestamp,'2020-12-12')='2020-12-12') or ( :mode = 'ENTER-QUERY' ) ) order by REF_CODE.LIST_SEQ , REF_CODE.DESCRIPTION , REF_CODE.CODE
}

OIIEMOVE_FIND_RGOFFEM1DIRECTIONCODE {
 	select REF_CODE5.CODE CODE , REF_CODE5.DESCRIPTION DESCRIPTION , REF_CODE5.EXPIRED_DATE EXPIREDDATE from REFERENCE_CODES REF_CODE5 where domain = 'MOVE_DIRECT' and ( (ACTIVE_FLAG = 'Y' and coalesce (EXPIRED_DATE::timestamp, '2020-12-12')= '2020-12-12' ) or ( :mode = 'ENTER-QUERY' ) ) order by REF_CODE5.LIST_SEQ
}

OIIEMOVE_FIND_RGOFFEM1MOVEMENTTYPE {
 	select REF_CODE3.CODE CODE , REF_CODE3.DESCRIPTION DESCRIPTION , REF_CODE3.EXPIRED_DATE EXPIREDDATE from REFERENCE_CODES REF_CODE3 where domain = 'MOVE_TYPE' and ( (ACTIVE_FLAG = 'Y' and coalesce (EXPIRED_DATE::timestamp, '2020-12-12')= '2020-12-12' ) or ( :mode = 'ENTER-QUERY' ) ) order by REF_CODE3.LIST_SEQ , REF_CODE3.DESCRIPTION
}

OIIEMOVE_FIND_RGOFFEM1MOVEMENTREASONC {
 	SELECT REF_CODE4.DESCRIPTION   DESCRIPTION        ,REF_CODE4.CODE  CODE       ,REF_CODE4.DOMAIN  DOMAIN  ,REF_CODE4.EXPIRED_DATE EXPIREDDATE  FROM   REFERENCE_CODES REF_CODE4 WHERE   DOMAIN='MOVE_RSN' AND ( (ACTIVE_FLAG='Y' AND  EXPIRED_DATE IS NULL ) OR ( :MODE = 'ENTER-QUERY'  )  ) ORDER BY  REF_CODE4.LIST_SEQ        ,REF_CODE4.DESCRIPTION        ,REF_CODE4.CODE
}

OIIEMOVE_FIND_RGOFFEMDIRECTIONCODE {
 	select REF_CODE1.CODE CODE , REF_CODE1.DESCRIPTION DESCRIPTION , REF_CODE1.EXPIRED_DATE EXPIREDDATE from REFERENCE_CODES REF_CODE1 where domain = 'MOVE_DIRECT' and ( (ACTIVE_FLAG = 'Y' and coalesce (EXPIRED_DATE::timestamp, '2020-12-12')= '2020-12-12' ) or ( :mode = 'ENTER-QUERY' ) ) order by REF_CODE1.LIST_SEQ
}

OIIEMOVE_OFFEM_FIND_OFFENDER_EXTERNAL_MOVEMENTS {
 	SELECT OFFENDER_BOOK_ID ,MOVEMENT_SEQ ,MOVEMENT_DATE ,MOVEMENT_TIME ,INTERNAL_SCHEDULE_TYPE ,INTERNAL_SCHEDULE_REASON_CODE ,MOVEMENT_TYPE ,MOVEMENT_REASON_CODE ,DIRECTION_CODE ,ARREST_AGENCY_LOC_ID ,TO_PROV_STAT_CODE ,ESCORT_CODE ,FROM_AGY_LOC_ID ,TO_AGY_LOC_ID ,ACTIVE_FLAG ,ESCORT_TEXT ,COMMENT_TEXT ,REPORTING_DATE ,TO_CITY ,FROM_CITY ,REPORTING_TIME ,EVENT_ID ,PARENT_EVENT_ID ,TO_COUNTRY_CODE ,OJ_LOCATION_CODE ,APPLICATION_DATE ,APPLICATION_TIME ,TO_ADDRESS_ID ,FROM_ADDRESS_ID ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID FROM OFFENDER_EXTERNAL_MOVEMENTS 
}

OIIEMOVE_OFF_BKG_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM OFFENDER_EXTERNAL_MOVEMENTS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIIEMOVE_OFF_EM1_POSTQUERY {
	SELECT BOOKING_NO  FROM OFFENDER_BOOKINGS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIIEMOVE_CGFKCHK_OFF_EM_OFF_EM_REF_MOV_ {
	SELECT REF_CODE2.DESCRIPTION ,REF_CODE2.DOMAIN ,REF_CODE2.ACTIVE_FLAG ,REF_CODE2.EXPIRED_DATE ,REF_CODE2.LIST_SEQ FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.CODE = :MOVEMENTREASONCODE AND  DOMAIN='MOVE_RSN'
}

OIIEMOVE_GET_PROFILE_VALUE_2_ {
	SELECT PROFILE_VALUE_2 FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = :P_PROFILE_TYPE AND PROFILE_CODE = :P_PROFILE_CODE
}

OIIEMOVE_CGFKCHK_OFF_EM_OFF_EM_DIRECTI_ {
	SELECT REF_CODE1.DESCRIPTION ,REF_CODE1.EXPIRED_DATE ,REF_CODE1.ACTIVE_FLAG ,REF_CODE1.LIST_SEQ FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :DIRECTIONCODE AND     DOMAIN='MOVE_DIRECT' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OIIEMOVE_CGFKCHK_OFF_EM_OFF_EM_MOVE_RE_ {
	SELECT REF_CODE.DESCRIPTION ,REF_CODE.EXPIRED_DATE ,REF_CODE.ACTIVE_FLAG ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :MOVEMENTTYPE AND     DOMAIN='MOVE_TYPE' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OIIEMOVE_CGFKCHK_OFF_EM1_OFF_EM_REF_MO_ {
	SELECT REF_CODE4.DESCRIPTION ,REF_CODE4.DOMAIN ,REF_CODE4.ACTIVE_FLAG ,REF_CODE4.EXPIRED_DATE ,REF_CODE4.LIST_SEQ FROM   REFERENCE_CODES REF_CODE4 WHERE  REF_CODE4.CODE = :MOVEMENTREASONCODE AND  DOMAIN='MOVE_RSN'
}

OIIEMOVE_CGFKCHK_OFF_EM1_OFF_EM_DIRECT_ {
	SELECT REF_CODE5.DESCRIPTION ,REF_CODE5.EXPIRED_DATE ,REF_CODE5.ACTIVE_FLAG ,REF_CODE5.LIST_SEQ FROM   REFERENCE_CODES REF_CODE5 WHERE  REF_CODE5.CODE = :DIRECTIONCODE AND     DOMAIN='MOVE_DIRECT' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OIIEMOVE_CGFKCHK_OFF_EM1_OFF_EM_MOV2_ {
	SELECT REF_CODE3.DESCRIPTION ,REF_CODE3.EXPIRED_DATE ,REF_CODE3.ACTIVE_FLAG ,REF_CODE3.LIST_SEQ FROM   REFERENCE_CODES REF_CODE3 WHERE  REF_CODE3.CODE = :MOVEMENTTYPE AND     DOMAIN='MOVE_TYPE' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OIIEMOVE_FIND_ALAGYLOCIDRG {
 	SELECT AGY_LOC.AGY_LOC_ID,AGY_LOC.DESCRIPTION,AGY_LOC.LIST_SEQ   FROM   AGENCY_LOCATIONS AGY_LOC WHERE (ACTIVE_FLAG='Y' OR :MODE='ENTER-QUERY' ) ORDER BY  AGY_LOC.LIST_SEQ ,AGY_LOC_ID ,AGY_LOC.DESCRIPTION
}
OIIEMOVE_FIND_CITY_DESCRIPTION {
SELECT DESCRIPTION     FROM REFERENCE_CODES RC   WHERE RC.DOMAIN = 'CITY' and CODE = :toCity
}
OIIEMOVE_FIND_ADDRESS_DESCRIPTION {
select SUBSTR (FULL_ADDRESS, 1, 40) from V_ADDRESSES where ADDRESS_ID = :addressId
}

