
OCIOCNOT_FIND_RGTYPE {
 	SELECT DISTINCT OMS_MISCELLANEOUS_GETDESCCODE ('TASK_TYPE' , W.WORK_TYPE ) DESCRIPTION ,               WORK_TYPE CODE   FROM WORKS W  WHERE WORKFLOW_TYPE = 'CNOTE' AND (W.ACTIVE_FLAG  = 'Y') ORDER BY  DESCRIPTION  ,CODE
}

OCIOCNOT_FIND_RGSUBTYPE {
 	SELECT DISTINCT OMS_MISCELLANEOUS_GETDESCCODE ('TASK_SUBTYPE' , W.WORK_SUB_TYPE ) DESCRIPTION ,               WORK_SUB_TYPE CODE   FROM WORKS W  WHERE WORKFLOW_TYPE = 'CNOTE' AND (W.ACTIVE_FLAG  = 'Y') ORDER BY  DESCRIPTION  ,CODE
}

OCIOCNOT_FIND_RGSTAFFNAME {
 	SELECT DISTINCT SM.LAST_NAME || ', ' || SM.FIRST_NAME STAFF_NAME      FROM STAFF_MEMBERS SM , OFFENDER_CASE_NOTES OCN  WHERE SM.STAFF_ID = OCN.STAFF_ID
}

OCIOCNOT_FIND_RGLOCATION {
 	SELECT AGY_LOC.DESCRIPTION  ,AGY_LOC.AGY_LOC_ID CODE  FROM AGENCY_LOCATIONS AGY_LOC , CASELOAD_AGENCY_LOCATIONS CAL  WHERE AGY_LOC.AGY_LOC_ID = CAL.AGY_LOC_ID  AND CAL.UPDATE_ALLOWED_FLAG = 'Y'   AND CAL.CASELOAD_ID = :CASELOADID  AND EXISTS ( SELECT 'X' FROM STAFF_ACCESSIBLE_CASELOADS SAC                    WHERE SAC.CASELOAD_ID = CAL.CASELOAD_ID                       AND SAC.UPDATE_ALLOWED_FLAG = 'Y'                        AND EXISTS (SELECT 'X' FROM STAFF_MEMBERS SM                              WHERE SM.STAFF_ID = SAC.STAFF_ID AND SM.USER_ID =:userId ) ) ORDER BY AGY_LOC.DESCRIPTION
}

OCIOCNOT_CASENOTE_FIND_V_OFFENDER_CASE_NOTES {
 	SELECT OFFENDER_BOOK_ID ,CASE_NOTE_ID ,OFFENDER_ID_DISPLAY ,LAST_NAME ,FIRST_NAME ,CONTACT_DATE ,CONTACT_TIME ,CASE_NOTE_TYPE ,CONTACT_TYPE ,CASE_NOTE_SUB_TYPE ,CONTACT_SUB_TYPE ,STAFF_ID ,STAFF_NAME ,AMENDMENT_FLAG ,CHECK_BOX1 ,CHECK_BOX2 ,CHECK_BOX3 ,CHECK_BOX4 ,CHECK_BOX5 ,CASE_NOTE_TEXT ,EVENT_ID ,NOTE_SOURCE_CODE ,NOTE_SOURCE ,IWP_FLAG ,DATE_CREATION ,TIME_CREATION   FROM V_OFFENDER_CASE_NOTES  /* where  */
}
OCIOCNOT_GET_STAFF_ID {
SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID =:userId
}
OCIOCNOT_GET_FIRST_LAST_NAME {
 SELECT LAST_NAME,FIRST_NAME,MIDDLE_NAME FROM STAFF_MEMBERS WHERE STAFF_ID = :PSTAFFID
 }
OCIOCNOT_CHECK_PRIVILEGE_EXISTS {
 SELECT count(*)
           FROM staff_members sm,
                staff_member_roles smr,
                oms_roles om
          WHERE sm.staff_id = smr.staff_id
            AND sm.user_id = :userId
            AND smr.role_id = om.role_id
            AND om.role_code = 'STAFF_CLOG'
            }