
OCUCNAME_OFFCASENOTE_FIND_OFFENDER_CASE_NOTES {
 	SELECT OFFENDER_BOOK_ID ,CONTACT_DATE ,CONTACT_TIME ,CASE_NOTE_TYPE ,CASE_NOTE_SUB_TYPE ,STAFF_ID ,CASE_NOTE_TEXT ,AMENDMENT_FLAG ,IWP_FLAG ,CHECK_BOX1 ,CHECK_BOX2 ,CHECK_BOX3 ,CHECK_BOX4 ,CHECK_BOX5 ,EVENT_ID ,CASE_NOTE_ID ,NOTE_SOURCE_CODE ,DATE_CREATION ,TIME_CREATION ,SEAL_FLAG ,OBJECT_TYPE ,OBJECT_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID 
 	FROM OFFENDER_CASE_NOTES   WHERE  OFFENDER_BOOK_ID = :P_CNOTE_BOOK_ID AND CASE_NOTE_ID = :P_CASE_NOTE_ID
}

OCUCNAME_OCUCNAME_WHENNEWFORMINSTANCEWHEN-NEW-FORM-INSTANCE {
	SELECT        OFFENDER_BOOK_ID, CASE_NOTE_ID INTO LV_BOOK_ID, LV_NOTE_ID FROM OFFENDER_CASE_NOTES WHERE OFFENDER_BOOK_ID = LV_BOOK_ID AND CASE_NOTE_ID = LV_NOTE_ID FOR UPDATE OF OFFENDER_BOOK_ID, CASE_NOTE_ID NOWAIT
}

OCUCNAME_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OCUCNAME_UPDATE_OFFENDER_CASE_NOTES {
 UPDATE OFFENDER_CASE_NOTES SET CASE_NOTE_TEXT = :caseNoteText, AMENDMENT_FLAG = 'Y', CHECK_BOX1 = :checkBox1, CHECK_BOX2 = :checkBox2, CHECK_BOX3 = :checkBox3, CHECK_BOX4 = :checkBox4,
      CHECK_BOX5 = :checkBox5, MODIFY_USER_ID=:modifyUserId,MODIFY_DATETIME=CURRENT_TIMESTAMP WHERE OFFENDER_BOOK_ID = :offenderBookId AND CASE_NOTE_ID = :caseNoteId AND STAFF_ID = :staffId
}
