
OCUNOTCM_FIND_RGSTAFFDTLS {
select SM.LAST_NAME || ', ' || SM.FIRST_NAME STAFF_NAME , RC.DESCRIPTION as position , TM.ROLE as role , LOC_ROLE_FROM_DATE FROM_DATE , TM.TEAM_MEMBER_ID TEAM_MEMBER_ID , TM.STAFF_ID STAFF_ID from TEAM_MEMBERS TM , STAFF_MEMBERS SM , REFERENCE_CODES RC where TM.TEAM_ID = ( select TEAM_ID from Teams where DESCRIPTION = :DESCRIPTION) and TM.ACTIVE_FLAG = 'Y' and SM.STAFF_ID = TM.STAFF_ID and RC.CODE = TM.POSITION and RC.DOMAIN = 'STAFF_POS' and RC.ACTIVE_FLAG = 'Y' order by SM.LAST_NAME , SM.FIRST_NAME
}

OCUNOTCM_OFFCASENR_FIND_OFF_CASE_NOTE_RECIPIENTS {
 	SELECT CASE_NOTE_ID ,TEAM_ID ,STAFF_ID ,OFF_CASE_NOTE_RECIPIENT_ID ,
 	COMMENT_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,
 	MODIFY_USER_ID ,SEAL_FLAG   FROM OFF_CASE_NOTE_RECIPIENTS 
}
OCUNOTCM_OFFCASENR_INSERT_OFF_CASE_NOTE_RECIPIENTS {

insert into OFF_CASE_NOTE_RECIPIENTS(CASE_NOTE_ID , TEAM_ID , STAFF_ID , OFF_CASE_NOTE_RECIPIENT_ID , COMMENT_TEXT , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:caseNoteId , :teamId , :staffId , :offCaseNoteRecipientId , :commentText , current_timestamp , :createUserId , null , :sealFlag )
}

OCUNOTCM_OFFCASENR_UPDATE_OFF_CASE_NOTE_RECIPIENTS {


update OFF_CASE_NOTE_RECIPIENTS set CASE_NOTE_ID = :caseNoteId , TEAM_ID = :teamId , STAFF_ID = :staffId , COMMENT_TEXT = :commentText , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where OFF_CASE_NOTE_RECIPIENT_ID = :offCaseNoteRecipientId
}


OIDCNOTE_GETCASE_NOTE_RECIPIENT__ID {

SELECT NEXTVAL('OFF_CASE_NOTE_RECIPIENT_ID') OFF_CASE_NOTE_RECIPIENT_ID FROM DUAL
}
OIDCNOTE_GET_TEAM_ID_DESC {
SELECT DESCRIPTION FROM automation_teams WHERE TEAM_ID=:TEAM_ID
}
OIDCNOTE_GET_STAFF_NAME_DESC {
SELECT LAST_NAME || ', ' || FIRST_NAME  STAFF_NAME  FROM     STAFF_MEMBERS  WHERE STAFF_ID=:STAFF_ID 
}
OIDCNOTE_GET_TEAM_ID{
SELECT TEAM_ID FROM automation_teams WHERE DESCRIPTION=:DESCRIPTION
}
