
OIIISCOU_FIND_CGFKAGYLOCAGYLOCID {
 	SELECT AGY_LOC1.AGY_LOC_ID AGY_LOC_ID, AGY_LOC1.AGY_LOC_ID CODE  ,AGY_LOC1.DESCRIPTION, AGY_LOC1.AGENCY_LOCATION_TYPE FROM AGENCY_LOCATIONS AGY_LOC1 WHERE AGENCY_LOCATION_TYPE = 'INST'  AND AGY_LOC_ID IN (SELECT CAL.AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS CAL WHERE (CAL.CASELOAD_ID = :caseloadId ) AND (CAL.AGY_LOC_ID != 'OUT' ) AND (CAL.AGY_LOC_ID != 'TRN' ) ) ORDER BY AGY_LOC1.DESCRIPTION
}

OIIISCOU_VPRISNCT_FIND_V_PRISON_STATUS_COUNT {
SELECT TOTAL_COUNT ,MALE_COUNT ,FEMALE_COUNT ,AGY_LOC_ID ,IMPRISONMENT_STATUS,
(TOTAL_COUNT - MALE_COUNT - FEMALE_COUNT) OTHER,
ROUND(((TOTAL_COUNT * 100) / 
(SELECT SUM(MALE_COUNT) + SUM(FEMALE_COUNT) + SUM((TOTAL_COUNT - MALE_COUNT - FEMALE_COUNT)) FROM V_PRISON_STATUS_COUNT where AGY_LOC_ID = :agyLocId)),2) PERCENT
  FROM V_PRISON_STATUS_COUNT V_PRISON_STATUS_COUNT WHERE AGY_LOC_ID = :agyLocId ORDER BY IMPRISONMENT_STATUS
}
OIIISCOU_VPRISNTOT_FIND_V_PRISON_TOTAL {
 	SELECT TOTAL_COUNT ,MALE_COUNT ,FEMALE_COUNT ,AGY_LOC_ID   FROM V_PRISON_TOTAL WHERE AGY_LOC_ID = :agyLocId
}

OIIISCOU_CGFKCHK_AGY_LOC_AGY_LOC_ID_AG_ {
	SELECT AGY_LOC1.DESCRIPTION ,AGY_LOC1.AGENCY_LOCATION_TYPE FROM   AGENCY_LOCATIONS AGY_LOC1 WHERE  AGY_LOC1.AGY_LOC_ID = :AGYLOCID AND     AGENCY_LOCATION_TYPE = 'INST'
}

OIIISCOU_CGFDGET_V_PRISN_CT_DRV_IMPRIS {
	SELECT   CODE, DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'IMP_STS' ORDER BY ACTIVE_FLAG DESC, EXPIRED_DATE DESC
}

OIIISCOU_GET_PROFILE_VALUE_2_ {
	SELECT PROFILE_VALUE_2 FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = P_PROFILE_TYPE AND PROFILE_CODE = P_PROFILE_CODE
}
