
OIUIWPGN_FIND_RGSTATUS {
 	SELECT REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'DOCUMENT_STS'  AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR :MODE = 'ENTER-QUERY' ) ORDER BY LIST_SEQ
}

OIUIWPGN_PARAMS_UPDATE_IWP_10G.GET_PARAMETERS {
	UPDATE IWP_10G.GET_PARAMETERS set /* where */
}


OIUIWPGN_GET_REFERENCE_CODE_ {
	SELECT CODE    FROM REFERENCE_CODES WHERE DOMAIN = P_DOMAIN AND LIST_SEQ = P_LIST_SEQ
}

OIUIWPGN_ASSIGN_CONTEXT_PARAM_ {
	SELECT ITM.TEMPLATE_ID, UPPER(ITM.MODULE_NAME) MODULE_NAME, --02-FEB-2012 ADDED UPPER FOR PROPER MATCHING UPPER(ITM.BLOCK_NAME) BLOCK_NAME, ITM.BLOCK_DESCRIPTION, UPPER(IPM.BOOKMARK_NAME) BOOKMARK_NAME, UPPER(IPM.PARAMETER_NAME) PARAMETER_NAME, UPPER(IPM.FIELD_NAME) FIELD_NAME, UPPER(IPM.DOCUMENT_CONTEXT_FLAG) DOCUMENT_CONTEXT_FLAG, UPPER(IPD.PARAMETER_DATA_TYPE) PARAMETER_DATA_TYPE FROM IWP_TEMPLATE_MODULES ITM, IWP_PARAMETER_MAPPINGS IPM, V_IWP_PARAMETER_DATA IPD WHERE ITM.TEMPLATE_MODULE_ID = IPM.TEMPLATE_MODULE_ID AND IPD.TEMPLATE_ID = ITM.TEMPLATE_ID AND IPD.BOOKMARK_NAME = IPM.BOOKMARK_NAME --02-FEB-2012 JOIN CONDITION WAS MISSING RESULTING IN IMPROPER RESULT SET CONTENT AND IPD.PARAMETER_NAME = IPM.PARAMETER_NAME  --02-FEB-2012 JOIN CONDITION WAS MISSING RESULTING IN IMPROPER RESULT SET CONTENT AND ITM.ACTIVE_FLAG = 'Y' -- AND IPM.DOCUMENT_CONTEXT_FLAG = 'Y' AND ITM.TEMPLATE_ID = P_TEMPLATE_ID AND ITM.MODULE_NAME = P_MODULE_NAME AND UPPER(ITM.BLOCK_NAME) = UPPER(P_BLOCK_NAME)
}
