--delete wrong key name

--1. GET_PRISIONER_DETAILS
delete from automation_api_query where QUERY_KEY='GET_PRISIONER_DETAILS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISIONER_DETAILS';
delete from ACTION_API where API_ID='GET_PRISIONER_DETAILS';

--2. GET_PRISIONER_ALIAS
delete from automation_api_query where QUERY_KEY='GET_PRISIONER_ALIAS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISIONER_ALIAS';
delete from ACTION_API where API_ID='GET_PRISIONER_ALIAS';

--3.  GET_PRISIONER_ADMISSION	
delete from automation_api_query where QUERY_KEY='GET_PRISIONER_ADMISSION';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISIONER_ADMISSION';
delete from ACTION_API where API_ID='GET_PRISIONER_ADMISSION';

--4.  GET_PRISIONER_RELEASE
delete from automation_api_query where QUERY_KEY='GET_PRISIONER_RELEASE';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISIONER_RELEASE';
delete from ACTION_API where API_ID='GET_PRISIONER_RELEASE';

--5. GET_PRISIONER_IDENTFIERS  
delete from automation_api_query where QUERY_KEY='GET_PRISIONER_IDENTFIERS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISIONER_IDENTFIERS';
delete from ACTION_API where API_ID='GET_PRISIONER_IDENTFIERS';

--6. GET_PRISIONER_HOUSING
delete from automation_api_query where QUERY_KEY='GET_PRISIONER_HOUSING';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISIONER_HOUSING';
delete from ACTION_API where API_ID='GET_PRISIONER_HOUSING';

--7.  RESPONE_FORMATTER 
delete from automation_api_query where QUERY_KEY='RESPONE_FORMATTER';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='RESPONE_FORMATTER';
delete from ACTION_API where API_ID='RESPONE_FORMATTER';

--8.  PRISIONER_TRANSFER_DETAILS
delete from automation_api_query where QUERY_KEY='PRISIONER_TRANSFER_DETAILS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='PRISIONER_TRANSFER_DETAILS';
delete from ACTION_API where API_ID='PRISIONER_TRANSFER_DETAILS';	

--delete good key name

--1. GET_PRISONER_DETAILS 
delete from automation_api_query where QUERY_KEY='GET_PRISONER_DETAILS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISONER_DETAILS';
delete from ACTION_API where API_ID='GET_PRISONER_DETAILS';

--2. GET_PRISONER_ALIAS
delete from automation_api_query where QUERY_KEY='GET_PRISONER_ALIAS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISONER_ALIAS';
delete from ACTION_API where API_ID='GET_PRISONER_ALIAS';

--3.  GET_PRISONER_ADMISSION  	
delete from automation_api_query where QUERY_KEY='GET_PRISONER_ADMISSION';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISONER_ADMISSION';
delete from ACTION_API where API_ID='GET_PRISONER_ADMISSION';

--4.  GET_PRISONER_RELEASE
delete from automation_api_query where QUERY_KEY='GET_PRISONER_RELEASE';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISONER_RELEASE';
delete from ACTION_API where API_ID='GET_PRISONER_RELEASE';

--5. GET_PRISONER_IDENTFIERS  
delete from automation_api_query where QUERY_KEY='GET_PRISONER_IDENTFIERS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISONER_IDENTFIERS';
delete from ACTION_API where API_ID='GET_PRISONER_IDENTFIERS';

--6. GET_PRISONER_HOUSING 
delete from automation_api_query where QUERY_KEY='GET_PRISONER_HOUSING';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_PRISONER_HOUSING';
delete from ACTION_API where API_ID='GET_PRISONER_HOUSING';

--7. RESPONSE_FORMATTER
delete from automation_api_query where QUERY_KEY='RESPONSE_FORMATTER';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='RESPONSE_FORMATTER';
delete from ACTION_API where API_ID='RESPONSE_FORMATTER';

--8.  PRISONER_TRANSFER_DETAILS 
delete from automation_api_query where QUERY_KEY='PRISONER_TRANSFER_DETAILS';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='PRISONER_TRANSFER_DETAILS';
delete from ACTION_API where API_ID='PRISONER_TRANSFER_DETAILS';

--9.  GET_MESSAGE_ID 
delete from automation_api_query where QUERY_KEY='GET_MESSAGE_ID';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_MESSAGE_ID';
delete from ACTION_API where API_ID='GET_MESSAGE_ID';	

--10.  GET_ASTRIA_PERSON_ID
delete from automation_api_query where QUERY_KEY='GET_ASTRIA_PERSON_ID';
delete from AUTOMATION_QUERY_PARAMETERS where QUERY_KEY='GET_ASTRIA_PERSON_ID';
delete from ACTION_API where API_ID='GET_ASTRIA_PERSON_ID';	