INSERT INTO oms_owner.system_labels (label_id, module_name,msg_key,msg_value,msg_type,create_user_id,modify_user_id) 
 VALUES ( nextval('lable_id_sequence'), 'OUMASSMU','oumassmu.enteredmodulenamedoesnotexistinomsmodules','Modulename does not exist in  OMS_MODULES Table.','LABEL','OMS_OWNER','OMS_OWNER');

INSERT INTO oms_owner.system_labels (label_id,module_name,msg_key,msg_value,msg_type,create_user_id,modify_user_id) 
 VALUES ( nextval('lable_id_sequence'), 'OCDOFACC', 'ocdofacc.billingdaycannotnullpleaseenterbillingday', 'Billing Day cannot be NULL. Please enter a billing day.', 'LABEL','OMS_OWNER','OMS_OWNER');


insert into SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 values( NEXTVAL('LABLE_ID_SEQUENCE') ,'LOGIN', 'login.userisinactive', 'User is inactive', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

insert into SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
values( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCUUCOND', 'ocuucond.legalTextofCondition', 'Legal Text of Condition', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

insert into SYSTEM_LABELS(LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_USER_ID,MODIFY_USER_ID)
 values(NEXTVAL('LABLE_ID_SEQUENCE'), 'OCMTEAMMAIN', 'ocmteammain.manageteam', 'Manage Team', 'LABEL', 'OMS_OWNER','OMS_OWNER');

insert into SYSTEM_LABELS(LABEL_ID, MODULE_NAME, MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_USER_ID,MODIFY_USER_ID)
 values(NEXTVAL('LABLE_ID_SEQUENCE'),'OCMTEAMMAIN','ocmteammain.teamAgyLocmandatory','Administrative Location must be entered','LABEL','OMS_OWNER','OMS_OWNER');

insert into SYSTEM_LABELS(LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_USER_ID, MODIFY_USER_ID)
 values(NEXTVAL('LABLE_ID_SEQUENCE'),'OCMTEAMMAIN','ocmteammain.teamFuncmandatory','Functions must be entered','LABEL','OMS_OWNER','OMS_OWNER');

INSERT INTO oms_owner.system_labels (label_id,module_name,msg_key,msg_value,msg_type,create_user_id,modify_user_id) 
 VALUES (NEXTVAL('lable_id_sequence'),'OCDCLOGS','ocdclogs.offendderdoesnthaveemailconfiguration','Offender does not have email(s) Configuration','LABEL','OMS_OWNER','OMS_OWNER');

INSERT INTO oms_owner.system_labels (label_id,module_name,msg_key,msg_value,msg_type,create_user_id,modify_user_id) 
 VALUES (NEXTVAL('lable_id_sequence'),'OUMUSERS','oumusers.assignedcaseloadnotinaccesscaselaod','Selected Assigned caseload is not in the list of accessible caseloads for this User.','LABEL','OMS_OWNER','OMS_OWNER');

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.no', 'No.', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.ordereddate', 'Ordered Date', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.matter', 'Matter #', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.court', 'Court', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.type', 'Type', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.commencetype', 'Commence Type', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.linkto', 'Link To', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.commencedate', 'Commence Date', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.termtypeandlength', 'Term Type(s) & Length(s)', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'ocdleglo.pel', 'PEL', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.termtype', 'Term Type', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.years', 'Years', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.months', 'Months', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.weeks', 'Weeks', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.days', 'Days', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.indefinite', 'Indefinite', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID )
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.select', 'Select', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.matter', 'Matter #', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.act', 'Act', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.code', 'Code', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.description', 'Description', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.descriptionchild', 'Charge', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.type', 'Type', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.incidentdate', 'Incident Date', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.range', '/ Range', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.plea', 'Plea', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.outcome', 'Outcome', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.currentstatus', 'Current Status', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.details', 'Details', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDCHGSU', 'ocdchgsu.indefinite', 'Type', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLS', 'ocdlegls.datetype', 'Date Type', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLS', 'ocdlegls.value', 'Value', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.pleaseaddoneimp', 'Please add atleast one Imprisonment term', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.morethanonenpp', 'Cannot add more than one Non-Parole Period term', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.morethanoneimp', 'Cannot add more than one Imprisonment Period term', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO SYSTEM_LABELS( LABEL_ID , MODULE_NAME , MSG_KEY , MSG_VALUE , MSG_TYPE , CREATE_USER_ID , MODIFY_USER_ID ) 
 VALUES( NEXTVAL('LABLE_ID_SEQUENCE') , 'OCDLEGLO', 'termToLine.nppgrtimp', 'Non-Parole Period duration must be less than or equal to Imprisonment duration', 'LABEL', 'OMS_OWNER' , 'OMS_OWNER' );

INSERT INTO system_labels (label_id,module_name,msg_key,msg_value,msg_type,create_user_id,modify_user_id) 
 VALUES (NEXTVAL('lable_id_sequence'),'OUMUSERS','oumusers.thiscaseloadcannotbedeletedbecausestaffalredyhasbeenassigned','This Caseload Cannot Be Deleted Because Staff Alredy Has Been Assigned','LABEL','OMS_OWNER','OMS_OWNER');
 
