----------------Sentence Key Dates Entry in Reference Domain Table---------------------

insert into REFERENCE_DOMAINS (DOMAIN,DESCRIPTION,DOMAIN_STATUS,OWNER_CODE,APPLN_CODE,OLD_CODE_TABLE,PARENT_DOMAIN,CODE_LENGTH
                             ,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SUPER_SET_DOMAIN,SEAL_FLAG) 
   values ('SENT_DT_DISP','Sentence Date Display','ACTIVE','ADMIN','OMS',null,null,null,
          to_timestamp('27-08-18 02:45:20.667040000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:20.667050000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',null,null);


----------------Sentence Key Dates Entry in Reference codes Table---------------------

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','HDCED_DATE','HDCED',1,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.845992000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.845996000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','HDCAD_DATE','HDCAD',2,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.846694000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.846697000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','ETD_DATE','ETD',3,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.847272000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.847275000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','MTD_DATE','MTD',4,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.847862000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.847865000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','LTD_DATE','LTD',5,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.848476000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.848479000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','ARD_DATE','ARD',6,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.849101000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.849104000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','CRD_DATE','CRD',7,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.849649000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.849652000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','PED_DATE','PED',8,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.850190000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.850193000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','APD_DATE','APD',9,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.850804000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.850807000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','NPD_DATE','NPD',10,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.851459000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.851463000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','LED_DATE','LED',11,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.852105000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.852109000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','SED_DATE','SED',12,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.852809000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.852813000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

insert into REFERENCE_CODES (DOMAIN,CODE,DESCRIPTION,LIST_SEQ,ACTIVE_FLAG,SYSTEM_DATA_FLAG,MODIFY_USER_ID,EXPIRED_DATE,NEW_CODE,PARENT_CODE,PARENT_DOMAIN,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) 
values ('SENT_DT_DISP','PRRD_DATE','PRRD',13,'Y','N',null,null,null,null,null,to_timestamp('27-08-18 02:45:27.853514000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'OMS_OWNER',to_timestamp('27-08-18 02:45:27.853518000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);

COMMIT;
