INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_VIEW','Schedule_Default calander view','Day','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_EVT_TIME','Schedule_Calander Event End Time','60','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','COURT_COLOR','Schedule_Court Event Color','#3ce371','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','INT_COLOR','Schedule_Internal Event Color','#ff0000','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','EXT_COLOR','Schedule_External Event Color','#ce82ee','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','TEMP_COLOR','Schedule_Temparory Absence Event Color','#005aff','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','PRG_COLOR','Schedule_Institutional Actives Event Color','#ffa500','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','INT_EVT_TIME','Schedule_Internal Event End time','60','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','EXT_EVT_TIME','Schedule_External Event End time','120','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','DFLT_COLOR','Schedule_Default Colour','#ff0000','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_STR_TIME','Schedule_ calendar start time','07:00','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_END_TIME','Schedule_ calendar end time','18:00','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_MON_AGN','Schedule_month agenda view enable','true','', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_DAY','Schedule_day view enable','true','1', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_WK_VIEW','Schedule_week view enable','true','2', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_WK_WEEK','Schedule_work view enable','true','3', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_MON_VIEW','Schedule_month  view enable','true','4', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_AGN_VIEW','Schedule_ agenda view enable','true','5', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_TLN_DAY','Schedule_TimeLine Day view enable','true','7', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_TLN_WEEK','Schedule_TimeLine Week view enable','true','8', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_TLN_WORK','Schedule_TimeLine Work Week view enable','true','9', USER, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYSTEM_PROFILES(PROFILE_TYPE, PROFILE_CODE, DESCRIPTION, PROFILE_VALUE, PROFILE_VALUE_2, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME)
VALUES('DISPLAY','CAL_TLN_MON','Schedule_TimeLine month view enable','true','10', USER, SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;