---- Clear old data first for the database
DELETE FROM oms_owner.oms_modules_help;

---- Version: sysconjusticesystems/online_help:1.10
---- Insert screens: 220 Rows

INSERT INTO oms_owner.oms_modules_help (module_name, help_type, help_url, help_desc)
VALUES
    ('OCDADDRE', 'H', 'OCDADDRE.htm', 'OCDADDRE HTML Help Topic'),
	('OCDALERT', 'H', 'OCDALERT.htm', 'OCDALERT HTML Help Topic'),
	('OCDALIAS', 'H', 'OCDALIAS.htm', 'OCDALIAS HTML Help Topic'),
	('OCDALTCC', 'H', 'OCDALTCC.htm', 'OCDALTCC HTML Help Topic'),
	('OCDATPOW', 'H', 'OCDATPOW.htm', 'OCDATPOW HTML Help Topic'),
	('OCDBAILO', 'H', 'OCDBAILO.htm', 'OCDBAILO HTML Help Topic'),
	('OCDCGPAY', 'H', 'OCDCGPAY.htm', 'OCDCGPAY HTML Help Topic'),
	('OCDCLIST', 'H', 'OCDCLIST.htm', 'OCDCLIST HTML Help Topic'),
	('OCDCLOGS', 'H', 'OCDCLOGS.htm', 'OCDCLOGS HTML Help Topic'),
	('OCDCLOSE', 'H', 'OCDCLOSE.htm', 'OCDCLOSE HTML Help Topic'),
	('OCDCORDS', 'H', 'OCDCORDS.htm', 'OCDCORDS HTML Help Topic'),
	('OCDEDEMP', 'H', 'OCDEDEMP.htm', 'OCDEDEMP HTML Help Topic'),
	('OCDEXPOW', 'H', 'OCDEXPOW.htm', 'OCDEXPOW HTML Help Topic'),
	('OCDHEALT', 'H', 'OCDHEALT.htm', 'OCDHEALT HTML Help Topic'),
	('OCDINTAK', 'H', 'OCDINTAK.htm', 'OCDINTAK HTML Help Topic'),
	('OCDIPLAN', 'H', 'OCDIPLAN.htm', 'OCDIPLAN HTML Help Topic'),
	('OCDLANGS', 'H', 'OCDLANGS.htm', 'OCDLANGS HTML Help Topic'),
	('OCDLEGLS', 'H', 'OCDLEGLS.htm', 'OCDLEGLS HTML Help Topic'),
	('OCDNCODE', 'H', 'OCDNCODE.htm', 'OCDNCODE HTML Help Topic'),
	('OCDNOQUE', 'H', 'OCDNOQUE.htm', 'OCDNOQUE HTML Help Topic'),
	('OCDORASS', 'H', 'OCDORASS.htm', 'OCDORASS HTML Help Topic'),
	('OCDPAROR', 'H', 'OCDPAROR.htm', 'OCDPAROR HTML Help Topic'),
	('OCDPERSO', 'H', 'OCDPERSO.htm', 'OCDPERSO HTML Help Topic'),
	('OCDPROGR', 'H', 'OCDPROGR.htm', 'OCDPROGR HTML Help Topic'),
	('OCDPSREP', 'H', 'OCDPSREP.htm', 'OCDPSREP HTML Help Topic'),
	('OCDRLFCC', 'H', 'OCDRLFCC.htm', 'OCDRLFCC HTML Help Topic'),
	('OCDSABUS', 'H', 'OCDSABUS.htm', 'OCDSABUS HTML Help Topic'),
	('OCDSENCH', 'H', 'OCDSENCH.htm', 'OCDSENCH HTML Help Topic'),
	('OCDTAPOW', 'H', 'OCDTAPOW.htm', 'OCDTAPOW HTML Help Topic'),
	('OCDXPROG', 'H', 'OCDXPROG.htm', 'OCDXPROG HTML Help Topic'),
	('OCICNSRC', 'H', 'OCICNSRC.htm', 'OCICNSRC HTML Help Topic'),
	('OCIDIARY', 'H', 'OCIDIARY.htm', 'OCIDIARY HTML Help Topic'),
	('OCIIPLAN', 'H', 'OCIIPLAN.htm', 'OCIIPLAN HTML Help Topic'),
	('OCINAMES', 'H', 'OCINAMES.htm', 'OCINAMES HTML Help Topic'),
	('OCIOCNOT', 'H', 'OCIOCNOT.htm', 'OCIOCNOT HTML Help Topic'),
	('OCIPOWLO', 'H', 'OCIPOWLO.htm', 'OCIPOWLO HTML Help Topic'),
	('OCISCATA', 'H', 'OCISCATA.htm', 'OCISCATA HTML Help Topic'),
	('OCITTPOW', 'H', 'OCITTPOW.htm', 'OCITTPOW HTML Help Topic'),
	('OCSPROGR', 'H', 'OCSPROGR.htm', 'OCSPROGR HTML Help Topic'),
	('OCUCOFFE', 'H', 'OCUCOFFE.htm', 'OCUCOFFE HTML Help Topic'),
	('OIDBSIAP', 'H', 'OIDBSIAP.htm', 'OIDBSIAP HTML Help Topic'),
	('OIDBUTAB', 'H', 'OIDBUTAB.htm', 'OIDBUTAB HTML Help Topic'),
	('OIDCAPPR', 'H', 'OIDCAPPR.htm', 'OIDCAPPR HTML Help Topic'),
	('OIDCHOLO', 'H', 'OIDCHOLO.htm', 'OIDCHOLO HTML Help Topic'),
	('OIDCIPON', 'H', 'OIDCIPON.htm', 'OIDCIPON HTML Help Topic'),
	('OIDCNOTE', 'H', 'OIDCNOTE.htm', 'OIDCNOTE HTML Help Topic'),
	('OIDCUSTAD', 'H', 'OIDCUSTAD.htm', 'OIDCUSTAD HTML Help Topic'),
	('OIDDPROP', 'H', 'OIDDPROP.htm', 'OIDDPROP HTML Help Topic'),
	('OIDEHLOC', 'H', 'OIDEHLOC.htm', 'OIDEHLOC HTML Help Topic'),
	('OIDESCAP', 'H', 'OIDESCAP.htm', 'OIDESCAP HTML Help Topic'),
	('OIDIEPLV', 'H', 'OIDIEPLV.htm', 'OIDIEPLV HTML Help Topic'),
	('OIDINTMV', 'H', 'OIDINTMV.htm', 'OIDINTMV HTML Help Topic'),
	('OIDISTAT', 'H', 'OIDISTAT.htm', 'OIDISTAT HTML Help Topic'),
	('OIDITRAN', 'H', 'OIDITRAN.htm', 'OIDITRAN HTML Help Topic'),
	('OIDMHIST', 'H', 'OIDMHIST.htm', 'OIDMHIST HTML Help Topic'),
	('OIDMPITM', 'H', 'OIDMPITM.htm', 'OIDMPITM HTML Help Topic'),
	('OIDONONA', 'H', 'OIDONONA.htm', 'OIDONONA HTML Help Topic'),
	('OIDPAATT', 'H', 'OIDPAATT.htm', 'OIDPAATT HTML Help Topic'),
	('OIDPACTI', 'H', 'OIDPACTI.htm', 'OIDPACTI HTML Help Topic'),
	('OIDPIDEN', 'H', 'OIDPIDEN.htm', 'OIDPIDEN HTML Help Topic'),
	('OIDPINFO', 'H', 'OIDPINFO.htm', 'OIDPINFO HTML Help Topic'),
	('OIDPWAIT', 'H', 'OIDPWAIT.htm', 'OIDPWAIT HTML Help Topic'),
	('OIDRELEA', 'H', 'OIDRELEA.htm', 'OIDRELEA HTML Help Topic'),
	('OIDRHLOC', 'H', 'OIDRHLOC.htm', 'OIDRHLOC HTML Help Topic'),
	('OIDRPLAN', 'H', 'OIDRPLAN.htm', 'OIDRPLAN HTML Help Topic'),
	('OIDRTCON', 'H', 'OIDRTCON.htm', 'OIDRTCON HTML Help Topic'),
	('OIDSCEXM', 'H', 'OIDSCEXM.htm', 'OIDSCEXM HTML Help Topic'),
	('OIDSCMOV', 'H', 'OIDSCMOV.htm', 'OIDSCMOV HTML Help Topic'),
	('OIDSHLOG', 'H', 'OIDSHLOG.htm', 'OIDSHLOG HTML Help Topic'),
	('OIDSIAPP', 'H', 'OIDSIAPP.htm', 'OIDSIAPP HTML Help Topic'),
	('OIDSTABS', 'H', 'OIDSTABS.htm', 'OIDSTABS HTML Help Topic'),
	('OIDSTEST', 'H', 'OIDSTEST.htm', 'OIDSTEST HTML Help Topic'),
	('OIDSTOJU', 'H', 'OIDSTOJU.htm', 'OIDSTOJU HTML Help Topic'),
	('OIDTPCON', 'H', 'OIDTPCON.htm', 'OIDTPCON HTML Help Topic'),
	('OIDTROJU', 'H', 'OIDTROJU.htm', 'OIDTROJU HTML Help Topic'),
	('OIDTRWJU', 'H', 'OIDTRWJU.htm', 'OIDTRWJU HTML Help Topic'),
	('OIDUNCTA', 'H', 'OIDUNCTA.htm', 'OIDUNCTA HTML Help Topic'),
	('OIDVCONT', 'H', 'OIDVCONT.htm', 'OIDVCONT HTML Help Topic'),
	('OIDVIRES', 'H', 'OIDVIRES.htm', 'OIDVIRES HTML Help Topic'),
	('OIDVISIT', 'H', 'OIDVISIT.htm', 'OIDVISIT HTML Help Topic'),
	('OIDVTOUR', 'H', 'OIDVTOUR.htm', 'OIDVTOUR HTML Help Topic'),
	('OIIBOOKS', 'H', 'OIIBOOKS.htm', 'OIIBOOKS HTML Help Topic'),
	('OIICIPON', 'H', 'OIICIPON.htm', 'OIICIPON HTML Help Topic'),
	('OIICLASS', 'H', 'OIICLASS.htm', 'OIICLASS HTML Help Topic'),
	('OIICMOCI', 'H', 'OIICMOCI.htm', 'OIICMOCI HTML Help Topic'),
	('OIIDMOVE', 'H', 'OIIDMOVE.htm', 'OIIDMOVE HTML Help Topic'),
	('OIIEMOVE', 'H', 'OIIEMOVE.htm', 'OIIEMOVE HTML Help Topic'),
	('OIIHLHIS', 'H', 'OIIHLHIS.htm', 'OIIHLHIS HTML Help Topic'),
	('OIINAMES', 'H', 'OIINAMES.htm', 'OIINAMES HTML Help Topic'),
	('OIIOSCED', 'H', 'OIIOSCED.htm', 'OIIOSCED HTML Help Topic'),
	('OIIPCLOC', 'H', 'OIIPCLOC.htm', 'OIIPCLOC HTML Help Topic'),
	('OIIPCTRA', 'H', 'OIIPCTRA.htm', 'OIIPCTRA HTML Help Topic'),
	('OIIPTRAN', 'H', 'OIIPTRAN.htm', 'OIIPTRAN HTML Help Topic'),
	('OIISCHED', 'H', 'OIISCHED.htm', 'OIISCHED HTML Help Topic'),
	('OIISHLOG', 'H', 'OIISHLOG.htm', 'OIISHLOG HTML Help Topic'),
	('OIIVISIT', 'H', 'OIIVISIT.htm', 'OIIVISIT HTML Help Topic'),
	('OIMISREA', 'H', 'OIMISREA.htm', 'OIMISREA HTML Help Topic'),
	('OIVCTMNG', 'H', 'OIVCTMNG.htm', 'OIVCTMNG HTML Help Topic'),
	('OMUVREST', 'H', 'OMUVREST.htm', 'OMUVREST HTML Help Topic'),
	('OSIHRSUM', 'H', 'OSIHRSUM.htm', 'OSIHRSUM HTML Help Topic'),
	('OSINAMES', 'H', 'OSINAMES.htm', 'OSINAMES HTML Help Topic'),
	('OSIOSEAR', 'H', 'OSIOSEAR.htm', 'OSIOSEAR HTML Help Topic'),
	('OSIPSEAR', 'H', 'OSIPSEAR.htm', 'OSIPSEAR HTML Help Topic'),
	('OUMASSMU', 'H', 'OUMASSMU.htm', 'OUMASSMU HTML Help Topic'),
	('OUMCPASS', 'H', 'OUMCPASS.htm', 'OUMCPASS HTML Help Topic'),
	('OUMPERSO', 'H', 'OUMPERSO.htm', 'OUMPERSO HTML Help Topic'),
	('OUMROLES', 'H', 'OUMROLES.htm', 'OUMROLES HTML Help Topic'),
	('OUMSMALA', 'H', 'OUMSMALA.htm', 'OUMSMALA HTML Help Topic'),
	('OUMUCREAT', 'H', 'OUMUCREAT.htm', 'OUMUCREAT HTML Help Topic'),
	('OUMUSERS', 'H', 'OUMUSERS.htm', 'OUMUSERS HTML Help Topic'),
	('OWEACPLN', 'H', 'OWEACPLN.htm', 'OWEACPLN HTML Help Topic'),
	('OCDALIAS', 'E', 'ERD\OCDALIAS.htm', 'OCDALIAS ERD Help Topic'),
	('OCDALTCC', 'E', 'ERD\OCDALTCC.htm', 'OCDALTCC ERD Help Topic'),
	('OCDCLOSE', 'E', 'ERD\OCDCLOSE.htm', 'OCDCLOSE ERD Help Topic'),
	('OCDCSCH', 'E', 'ERD\OCDCSCH.htm', 'OCDCSCH ERD Help Topic'),
	('OCDEDEMP', 'E', 'ERD\OCDEDEMP.htm', 'OCDEDEMP ERD Help Topic'),
	('OCDINTAK', 'E', 'ERD\OCDINTAK.htm', 'OCDINTAK ERD Help Topic'),
	('OCDIPLAN', 'E', 'ERD\OCDIPLAN.htm', 'OCDIPLAN ERD Help Topic'),
	('OCDLANGS', 'E', 'ERD\OCDLANGS.htm', 'OCDLANGS ERD Help Topic'),
	('OCDNOQUE', 'E', 'ERD\OCDNOQUE.htm', 'OCDNOQUE ERD Help Topic'),
	('OCDPROGR', 'E', 'ERD\OCDPROGR.htm', 'OCDPROGR ERD Help Topic'),
	('OCDRLFCC', 'E', 'ERD\OCDRLFCC.htm', 'OCDRLFCC ERD Help Topic'),
	('OCDSABUS', 'E', 'ERD\OCDSABUS.htm', 'OCDSABUS ERD Help Topic'),
	('OCDXPROG', 'E', 'ERD\OCDXPROG.htm', 'OCDXPROG ERD Help Topic'),
	('OCIIPLAN', 'E', 'ERD\OCIIPLAN.htm', 'OCIIPLAN ERD Help Topic'),
	('OCIOCNOT', 'E', 'ERD\OCIOCNOT.htm', 'OCIOCNOT ERD Help Topic'),
	('OCISCATA', 'E', 'ERD\OCISCATA.htm', 'OCISCATA ERD Help Topic'),
	('OCMCNPER', 'E', 'ERD\OCMCNPER.htm', 'OCMCNPER ERD Help Topic'),
	('OCMCPREV', 'E', 'ERD\OCMCPREV.htm', 'OCMCPREV ERD Help Topic'),
	('OCMNOQUE', 'E', 'ERD\OCMNOQUE.htm', 'OCMNOQUE ERD Help Topic'),
	('OCMSERVI', 'E', 'ERD\OCMSERVI.htm', 'OCMSERVI ERD Help Topic'),
	('OCMSPRAC', 'E', 'ERD\OCMSPRAC.htm', 'OCMSPRAC ERD Help Topic'),
	('OCMSVACP', 'E', 'ERD\OCMSVACP.htm', 'OCMSVACP ERD Help Topic'),
	('OCMWORKS', 'E', 'ERD\OCMWORKS.htm', 'OCMWORKS ERD Help Topic'),
	('OCMXPROG', 'E', 'ERD\OCMXPROG.htm', 'OCMXPROG ERD Help Topic'),
	('OIDADMIS', 'E', 'ERD\OIDADMIS.htm', 'OIDADMIS ERD Help Topic'),
	('OIDBSIAP', 'E', 'ERD\OIDBSIAP.htm', 'OIDBSIAP ERD Help Topic'),
	('OIDBSTRN', 'E', 'ERD\OIDBSTRN.htm', 'OIDBSTRN ERD Help Topic'),
	('OIDBUTAB', 'E', 'ERD\OIDBUTAB.htm', 'OIDBUTAB ERD Help Topic'),
	('OIDCAPPR', 'E', 'ERD\OIDCAPPR.htm', 'OIDCAPPR ERD Help Topic'),
	('OIDCHLOC', 'E', 'ERD\OIDCHLOC.htm', 'OIDCHLOC ERD Help Topic'),
	('OIDCHOLO', 'E', 'ERD\OIDCHOLO.htm', 'OIDCHOLO ERD Help Topic'),
	('OIDCIPON', 'E', 'ERD\OIDCIPON.htm', 'OIDCIPON ERD Help Topic'),
	('OIDCNOTE', 'E', 'ERD\OIDCNOTE.htm', 'OIDCNOTE ERD Help Topic'),
	('OIDDPROP', 'E', 'ERD\OIDDPROP.htm', 'OIDDPROP ERD Help Topic'),
	('OIDEHLOC', 'E', 'ERD\OIDEHLOC.htm', 'OIDEHLOC ERD Help Topic'),
	('OIDESCAP', 'E', 'ERD\OIDESCAP.htm', 'OIDESCAP ERD Help Topic'),
	('OIDIEPLV', 'E', 'ERD\OIDIEPLV.htm', 'OIDIEPLV ERD Help Topic'),
	('OIDINCDE', 'E', 'ERD\OIDINCDE.htm', 'OIDINCDE ERD Help Topic'),
	('OIDINTMV', 'E', 'ERD\OIDINTMV.htm', 'OIDINTMV ERD Help Topic'),
	('OIDISSUE', 'E', 'ERD\OIDISSUE.htm', 'OIDISSUE ERD Help Topic'),
	('OIDISTAT', 'E', 'ERD\OIDISTAT.htm', 'OIDISTAT ERD Help Topic'),
	('OIDITRAN', 'E', 'ERD\OIDITRAN.htm', 'OIDITRAN ERD Help Topic'),
	('OIDMBRDT', 'E', 'ERD\OIDMBRDT.htm', 'OIDMBRDT ERD Help Topic'),
	('OIDMHIST', 'E', 'ERD\OIDMHIST.htm', 'OIDMHIST ERD Help Topic'),
	('OIDMPITM', 'E', 'ERD\OIDMPITM.htm', 'OIDMPITM ERD Help Topic'),
	('OIDOICAP', 'E', 'ERD\OIDOICAP.htm', 'OIDOICAP ERD Help Topic'),
	('OIDOICUS', 'E', 'ERD\OIDOICUS.htm', 'OIDOICUS ERD Help Topic'),
	('OIDOMAIL', 'E', 'ERD\OIDOMAIL.htm', 'OIDOMAIL ERD Help Topic'),
	('OIDONONA', 'E', 'ERD\OIDONONA.htm', 'OIDONONA ERD Help Topic'),
	('OIDOWREL', 'E', 'ERD\OIDOWREL.htm', 'OIDOWREL ERD Help Topic'),
	('OIDPACTI', 'E', 'ERD\OIDPACTI.htm', 'OIDPACTI ERD Help Topic'),
	('OIDPAWLI', 'E', 'ERD\OIDPAWLI.htm', 'OIDPAWLI ERD Help Topic'),
	('OIDPIDEN', 'E', 'ERD\OIDPIDEN.htm', 'OIDPIDEN ERD Help Topic'),
	('OIDPINFO', 'E', 'ERD\OIDPINFO.htm', 'OIDPINFO ERD Help Topic'),
	('OIDPWAIT', 'E', 'ERD\OIDPWAIT.htm', 'OIDPWAIT ERD Help Topic'),
	('OIDRHLOC', 'E', 'ERD\OIDRHLOC.htm', 'OIDRHLOC ERD Help Topic'),
	('OIDRTCON', 'E', 'ERD\OIDRTCON.htm', 'OIDRTCON ERD Help Topic'),
	('OIDSCEXM', 'E', 'ERD\OIDSCEXM.htm', 'OIDSCEXM ERD Help Topic'),
	('OIDSCMOV', 'E', 'ERD\OIDSCMOV.htm', 'OIDSCMOV ERD Help Topic'),
	('OIDSHLOG', 'E', 'ERD\OIDSHLOG.htm', 'OIDSHLOG ERD Help Topic'),
	('OIDSIAPP', 'E', 'ERD\OIDSIAPP.htm', 'OIDSIAPP ERD Help Topic'),
	('OIDSTABS', 'E', 'ERD\OIDSTABS.htm', 'OIDSTABS ERD Help Topic'),
	('OIDSTEST', 'E', 'ERD\OIDSTEST.htm', 'OIDSTEST ERD Help Topic'),
	('OIDSTOJU', 'E', 'ERD\OIDSTOJU.htm', 'OIDSTOJU ERD Help Topic'),
	('OIDTPCON', 'E', 'ERD\OIDTPCON.htm', 'OIDTPCON ERD Help Topic'),
	('OIDTROJU', 'E', 'ERD\OIDTROJU.htm', 'OIDTROJU ERD Help Topic'),
	('OIDTRWJU', 'E', 'ERD\OIDTRWJU.htm', 'OIDTRWJU ERD Help Topic'),
	('OIDUNCTA', 'E', 'ERD\OIDUNCTA.htm', 'OIDUNCTA ERD Help Topic'),
	('OIDVCONT', 'E', 'ERD\OIDVCONT.htm', 'OIDVCONT ERD Help Topic'),
	('OIDVIRES', 'E', 'ERD\OIDVIRES.htm', 'OIDVIRES ERD Help Topic'),
	('OIDVISIT', 'E', 'ERD\OIDVISIT.htm', 'OIDVISIT ERD Help Topic'),
	('OIDVTOUR', 'E', 'ERD\OIDVTOUR.htm', 'OIDVTOUR ERD Help Topic'),
	('OIICMOCI', 'E', 'ERD\OIICMOCI.htm', 'OIICMOCI ERD Help Topic'),
	('OIIDMOVE', 'E', 'ERD\OIIDMOVE.htm', 'OIIDMOVE ERD Help Topic'),
	('OIIGRIEV', 'E', 'ERD\OIIGRIEV.htm', 'OIIGRIEV ERD Help Topic'),
	('OIIHISCO', 'E', 'ERD\OIIHISCO.htm', 'OIIHISCO ERD Help Topic'),
	('OIIINLOG', 'E', 'ERD\OIIINLOG.htm', 'OIIINLOG ERD Help Topic'),
	('OIIISCOU', 'E', 'ERD\OIIISCOU.htm', 'OIIISCOU ERD Help Topic'),
	('OIIOICUS', 'E', 'ERD\OIIOICUS.htm', 'OIIOICUS ERD Help Topic'),
	('OIIPCLOC', 'E', 'ERD\OIIPCLOC.htm', 'OIIPCLOC ERD Help Topic'),
	('OIIPCTRA', 'E', 'ERD\OIIPCTRA.htm', 'OIIPCTRA ERD Help Topic'),
	('OIIPTRAN', 'E', 'ERD\OIIPTRAN.htm', 'OIIPTRAN ERD Help Topic'),
	('OIISCHED', 'E', 'ERD\OIISCHED.htm', 'OIISCHED ERD Help Topic'),
	('OIISHLOG', 'E', 'ERD\OIISHLOG.htm', 'OIISHLOG ERD Help Topic'),
	('OIITGDET', 'E', 'ERD\OIITGDET.htm', 'OIITGDET ERD Help Topic'),
	('OIIVISIT', 'E', 'ERD\OIIVISIT.htm', 'OIIVISIT ERD Help Topic'),
	('OIIWLTWJ', 'E', 'ERD\OIIWLTWJ.htm', 'OIIWLTWJ ERD Help Topic'),
	('OIMADMIS', 'E', 'ERD\OIMADMIS.htm', 'OIMADMIS ERD Help Topic'),
	('OIMCOUNT', 'E', 'ERD\OIMCOUNT.htm', 'OIMCOUNT ERD Help Topic'),
	('OIMCTACT', 'E', 'ERD\OIMCTACT.htm', 'OIMCTACT ERD Help Topic'),
	('OIMIEPLV', 'E', 'ERD\OIMIEPLV.htm', 'OIMIEPLV ERD Help Topic'),
	('OIMILOCA', 'E', 'ERD\OIMILOCA.htm', 'OIMILOCA ERD Help Topic'),
	('OIMISREA', 'E', 'ERD\OIMISREA.htm', 'OIMISREA ERD Help Topic'),
	('OIMISSUE', 'E', 'ERD\OIMISSUE.htm', 'OIMISSUE ERD Help Topic'),
	('OIMOICMP', 'E', 'ERD\OIMOICMP.htm', 'OIMOICMP ERD Help Topic'),
	('OIMOICOI', 'E', 'ERD\OIMOICOI.htm', 'OIMOICOI ERD Help Topic'),
	('OIMPLDUR', 'E', 'ERD\OIMPLDUR.htm', 'OIMPLDUR ERD Help Topic'),
	('OIMPRFCA', 'E', 'ERD\OIMPRFCA.htm', 'OIMPRFCA ERD Help Topic'),
	('OIMPRFCO', 'E', 'ERD\OIMPRFCO.htm', 'OIMPRFCO ERD Help Topic'),
	('OIMSLEVL', 'E', 'ERD\OIMSLEVL.htm', 'OIMSLEVL ERD Help Topic'),
	('OIMULOCA', 'E', 'ERD\OIMULOCA.htm', 'OIMULOCA ERD Help Topic'),
	('OIMVDTSL', 'E', 'ERD\OIMVDTSL.htm', 'OIMVDTSL ERD Help Topic'),
	('OIMVLIMT', 'E', 'ERD\OIMVLIMT.htm', 'OIMVLIMT ERD Help Topic'),
	('OIMWORKR', 'E', 'ERD\OIMWORKR.htm', 'OIMWORKR ERD Help Topic'),
	('OMUVREST', 'E', 'ERD\OMUVREST.htm', 'OMUVREST ERD Help Topic'),
	('OSIPSEAR', 'E', 'ERD\OSIPSEAR.htm', 'OSIPSEAR ERD Help Topic'),
	('OSISTGKW', 'E', 'ERD\OSISTGKW.htm', 'OSISTGKW ERD Help Topic'),
	('OUMEMOVE', 'E', 'ERD\OUMEMOVE.htm', 'OUMEMOVE ERD Help Topic'),
	('OUMINOUT', 'E', 'ERD\OUMINOUT.htm', 'OUMINOUT ERD Help Topic'),
	('OCDADDRE', 'E', 'ERD\OCDADDRE.htm', 'OCDADDRE ERD Help Topic'),
	('OCDALERT', 'E', 'ERD\OCDALERT.htm', 'OCDALERT ERD Help Topic');
	
---- version: sysconjusticesystems/online_help:1.11
---- insert screens: 25 Rows (total 247 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url,help_desc) 
VALUES
     ('OIDADMIS', 'H', 'OIDADMIS.htm', 'Reception/Admission HTML Help Topic'),
     ('OIMPRFCO', 'H', 'OIMPRFCO.htm', 'Maintain Profile Codes HTML Help Topic'),
     ('OUMBUNDL', 'H', 'OUMBUNDL.htm', 'Maintain Property Bundles HTML Help Topic'),
     ('OIMSTATU', 'H', 'OIMSTATU.htm', 'Maintain Statutes HTML Help Topic'),
     ('OIDRELSC', 'H', 'OIDRELSC.htm', 'Release Schedules HTML Help Topic'),
     ('OIIWLTWJ', 'H', 'OIIWLTWJ.htm', 'Within Jurisdiction Waiting List HTML Help Topic'),
     ('OIDPAWLI', 'H', 'OIDPAWLI.htm', 'Activity Waiting List HTML Help Topic'),
     ('OIDOFFOB', 'H', 'OIDOFFOB.htm', 'Inmate Observations HTML Help Topic'),
     ('OIIOFFOB', 'H', 'OIIOFFOB.htm', 'Inmate Observations Inquiry HTML Help Topic'),
     ('OCMDSPWD', 'H', 'OCMDSPWD.htm', 'Maintain Default Staff Position Workloads HTML Help Topic'),
     ('OUMSMUGA', 'H', 'OUMSMUGA.htm', 'Staff Member Access HTML Help Topic'),
     ('OUMPERSD', 'H', 'OUMPERSD.htm', 'License Details HTML Help Topic'),
     ('OUISDIRE', 'H', 'OUISDIRE.htm', 'Staff Directory HTML Help Topic'),
     ('OCMPCONF', 'H', 'OCMPCONF.htm', 'Component Behaviour HTML Help Topic'),
     ('OUMWMENU', 'H', 'OUMWMENU.htm', 'Screen Flows HTML Help Topic'),
     ('OUMEEMOV', 'H', 'OUMEEMOV.htm', 'Edit External Moves HTML Help Topic'),
     ('OUMAGYRG', 'H', 'OUMAGYRG.htm', 'Agency Location Regions HTML Help Topic'),
     ('OUMHLHIS', 'H', 'OUMHLHIS.htm', 'Housing Location History HTML Help Topic'),
     ('OUMINSDB', 'H', 'OUMINSDB.htm', 'Module Dashboard Association HTML Help Topic'),
     ('OMSHELP', 'H', 'OMSHELP.htm', 'Help HTML Help Topic'),
     ('OLISET', 'H', 'OLISET.htm', 'Branding HTML Help Topic'),
     ('OUMCDTAB', 'H', 'OUMCDTAB.htm', 'Available Copy Tables HTML Help Topic'),
     ('OUMAGENC', 'H', 'OUMAGENC.htm', 'External Agencies/Corporates HTML Help Topic'),
     ('OUMPURGE', 'H', 'OUMPURGE.htm', 'Purge Offenders HTML Help Topic'),
     ('OUMBADMI', 'H', 'OUMBADMI.htm', 'Bookings Administration HTML Help Topic');

---- version: sysconjusticesystems/online_help:1.12
---- insert screens: 0 Rows (total 247 Rows) --- Comment: Fixed screens

---- version: sysconjusticesystems/online_help:1.13
---- insert screens: 14 Rows (total 261 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url,help_desc) 
VALUES								
     ('OIMADMIS', 'H', 'OIMADMIS.htm', 'Maintain Admissions HTML Help Topic'),
     ('OIMPRFCA', 'H', 'OIMPRFCA.htm', 'Maintain Profile Category/Types HTML Help Topic'),
     ('OIMCTACT', 'H', 'OIMCTACT.htm', 'Maintain Person Contacts HTML Help Topic'),
     ('OUMRCODE', 'H', 'OUMRCODE.htm', 'OMS Reference Codes HTML Help Topic'),
     ('OUMHOCOD', 'H', 'OUMHOCOD.htm', 'Maintain Offense Categories HTML Help Topic'),
     ('OIMOFFEN', 'H', 'OIMOFFEN.htm', 'Maintain Charges HTML Help Topic'),
     ('OCMSTATS', 'H', 'OCMSTATS.htm', 'Maintain Statuses HTML Help Topic'),
     ('OIMCUSTS', 'H', 'OIMCUSTS.htm', 'Maintain Custody Statuses HTML Help Topic'),
     ('OCMLESET', 'H', 'OCMLESET.htm', 'Legals Settings HTML Help Topic'),
     ('OIMSREQS', 'H', 'OIMSREQS.htm', 'Maintain Sentences HTML Help Topic'),
     ('OIMSATYP', 'H', 'OIMSATYP.htm', 'Sentence Adjustment Types HTML Help Topic'),
     ('OIMCRTOR', 'H', 'OIMCRTOR.htm', 'Maintain Court Order Types HTML Help Topic'),
     ('OUMMEROF', 'H', 'OUMMEROF.htm', 'Merge Offenders HTML Help Topic'),
     ('OUIMERGE', 'H', 'OUIMERGE.htm', 'Merge Transaction Inquiry HTML Help Topic');
	 
	 
---- version: sysconjusticesystems/online_help:1.14
---- insert screens: 18 Rows (total 279 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url,help_desc)
VALUES								
     ('OUMSYPFL', 'H', 'OUMSYPFL.htm', 'System Profiles HTML Help Topic'),
     ('OUMMENUS', 'H', 'OUMMENUS.htm', 'Menus HTML Help Topic'),
     ('OUMAGYHT', 'H', 'OUMAGYHT.htm', 'Agency Location History HTML Help Topic'),
     ('OTMLOCKR', 'H', 'OTMLOCKR.htm', 'Module Lock Removal HTML Help Topic'),
     ('OUMAGLOC', 'H', 'OUMAGLOC.htm', 'Agency Locations HTML Help Topic'),
     ('OUMRAREA', 'H', 'OUMRAREA.htm', 'Regions/Areas HTML Help Topic'),
     ('OUMACASE', 'H', 'OUMACASE.htm', 'Caseload HTML Help Topic'),
     ('OUMSYSET', 'H', 'OUMSYSET.htm', 'System Settings HTML Help Topic'),
     ('OUMRELMD', 'H', 'OUMRELMD.htm', 'Related Modules HTML Help Topic'),
     ('OUMSYLAB', 'H', 'OUMSYLAB.htm', 'System Labels HTML Help Topic'),
     ('OUMFORMS', 'H', 'OUMFORMS.htm', 'Form Access HTML Help Topic'),
     ('OMUNVARY', 'H', 'OMUNVARY.htm', 'Name Variations (Name Search) HTML Help Topic'),
     ('OUMRESTA', 'H', 'OUMRESTA.htm', 'Restricted Access HTML Help Topic'),
     ('OYMHOLID', 'H', 'OYMHOLID.htm', 'Holidays HTML Help Topic'),
     ('OCMSERVI', 'H', 'OCMSERVI.htm', 'Services HTML Help Topic'),
     ('UPDOFFID', 'H', 'UPDOFFID.htm', 'Update Offender ID HTML Help Topic'),
     ('OCMSHIER', 'H', 'OCMSHIER.htm', 'Staff Hierarchy HTML Help Topic'),
     ('OCMORCOD', 'H', 'OCMORCOD.htm', 'Offense Result Codes HTML Help Topic');

---- Current version: sysconjusticesystems/online_help:1.15
---- insert screens: 14 Rows (total 293 Rows)

INSERT INTO oms_owner.oms_modules_help(module_name,help_type,help_url,help_desc)
VALUES
     ('OCMCONDI', 'H', 'OCMCONDI.htm', 'Maint. Conditions HTML Help Topic'),					
     ('OIMRELSC', 'H', 'OIMRELSC.htm', 'Release Schedule SettingsHTML Help Topic'),
     ('OIMMHOLO', 'H', 'OIMMHOLO.htm', 'Housing LocationsHTML Help Topic'),
     ('OIMULOCA', 'H', 'OIMULOCA.htm', 'Internal Location UsagesHTML Help Topic'),
     ('OCMCPREV', 'H', 'OCMCPREV.htm', 'Maint. Case Plan Review Periods HTML Help Topic'),
     ('OCMCNPER', 'H', 'OCMCNPER.htm', 'Maintain Case Note PermissionsHTML Help Topic'),
     ('OIMCOUNT', 'H', 'OIMCOUNT.htm', 'Maintain CountsHTML Help Topic'),
     ('OIMVDTSL', 'H', 'OIMVDTSL.htm', 'Maint. Day/Time SlotsHTML Help Topic'),
     ('OIMVLIMT', 'H', 'OIMVLIMT.htm', 'Maint. Visit LimitsHTML Help Topic'),
     ('OIMOICMP', 'H', 'OIMOICMP.htm', 'Maint. OIC Maximum PenaltiesHTML Help Topic'),
     ('OIMIITPS', 'H', 'OIMIITPS.htm', 'Maintain Issues PermissionsHTML Help Topic'),
     ('OCMNOQUE', 'H', 'OCMNOQUE.htm', 'Maintain Assessment Questionnaires'),
     ('OIMSLEVL', 'H', 'OIMSLEVL.htm', 'Maintain Assessment Scores'),
     ('OIMILOCA', 'H', 'OIMILOCA.htm', 'Maintain Internal Locations');
