
OCUWKHTY_VWORKASSIGNMENTHISTORY_FIND_V_WORK_ASSIGNMENT_HISTORY {
 	SELECT  TASK_ASSIGNMENT_HTY_ID, TASK_ASSIGNMENT_ID, WORK_ID, DETAIL, OFFENDER_BOOK_ID, ASSIGNMENT_DATE, ASSIGNMENT_STATUS, TEAM_MEMBER_ID, 
 	STAFF_ID, STAFF_LAST_NAME, STAFF_NAME, STAFF_POSITION, STAFF_ROLE, TEAM_ID, TEAM_CODE, TEAM_DESCRIPTION, WORKFLOW_HISTORY_ID FROM 
 	V_WORK_ASSIGNMENT_HISTORY  where work_id = :workId and offender_book_id = :offenderBookId AND WORKFLOW_HISTORY_ID = 
 	:workflowHistoryId order by assignment_date desc
}

OCUWKHTY_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
