
OIDCOASI_FIND_RGAGYLOCID {
 	SELECT AGY_LOC.AGY_LOC_ID CODE ,        AGY_LOC.DESCRIPTION DESCRIPTION   FROM AGENCY_LOCATIONS AGY_LOC  WHERE AGY_LOC.AGY_LOC_ID IN (           SELECT CA.AGY_LOC_ID             FROM CASELOAD_AGENCY_LOCATIONS CA            WHERE CA.CASELOAD_ID = :CASELOADID              AND CA.AGY_LOC_ID NOT IN ('OUT' , 'TRN' ) )
}

OIDCOASI_FIND_RGLIVINGUNITCODEONE {
 	SELECT LIV_UNIT.LIVING_UNIT_CODE DESCRIPTION ,        TO_CHAR(LIV_UNIT.LIVING_UNIT_ID) CODE   FROM LIVING_UNITS LIV_UNIT  WHERE AGY_LOC_ID = :AGYLOCID    AND ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID IS NULL
}

OIDCOASI_FIND_RGLIVINGUNITCODETWO {
 	SELECT LIV_UNIT1.LIVING_UNIT_CODE DESCRIPTION  ,               TO_CHAR(LIV_UNIT1.LIVING_UNIT_ID) CODE   FROM LIVING_UNITS LIV_UNIT1  WHERE AGY_LOC_ID = :AGYLOCID    AND ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID
}

OIDCOASI_FIND_RGLIVINGUNITCODETHREE {
 	SELECT LIV_UNIT2.LIVING_UNIT_CODE DESCRIPTION ,                   TO_CHAR(LIV_UNIT2.LIVING_UNIT_ID) CODE   FROM LIVING_UNITS LIV_UNIT2  WHERE AGY_LOC_ID = :AGYLOCID    AND ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID
}

OIDCOASI_FIND_RGLIVINGUNITCODEFOUR {
 	SELECT LIV_UNIT3.LIVING_UNIT_CODE DESCRIPTION ,        TO_CHAR(LIV_UNIT3.LIVING_UNIT_ID) CODE   FROM LIVING_UNITS LIV_UNIT3  WHERE AGY_LOC_ID = :AGYLOCID    AND ACTIVE_FLAG = 'Y'    AND PARENT_LIVING_UNIT_ID = :LIVINGUNITID
}

OIDCOASI_FIND_RGSTAFFID {
 	SELECT   DISTINCT SM.LAST_NAME DESCRIPTION ,          SM.FIRST_NAME FIRSTNAME ,     SM.STAFF_ID code     FROM STAFF_MEMBERS SM , STAFF_ACCESSIBLE_CASELOADS SAC    WHERE SM.STAFF_ID = SAC.STAFF_ID      AND SM.STATUS = 'ACTIVE'      AND SAC.CASELOAD_ID IN (             SELECT CASELOAD_ID               FROM CASELOAD_AGENCY_LOCATIONS CAL              WHERE CAL.AGY_LOC_ID = :AGYLOCID ) ORDER BY LAST_NAME , FIRST_NAME
}

OIDCOASI_OFFASGN_UPDATE_OIDCOASI.OFFENDER_ASSIGNMENTS_QUERY {
	UPDATE OIDCOASI.OFFENDER_ASSIGNMENTS_QUERY set /* where */
}


OIDCOASI_GET_PROFILE_VALUE_2_ {
	SELECT PROFILE_VALUE_2 FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = :P_PROFILE_TYPE AND PROFILE_CODE = :P_PROFILE_CODE
}

OIDCOASI_GET_OFFENDER_CASE_OFFICER {
	SELECT count(*) FROM OFFENDER_CASE_OFFICERS WHERE OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID AND CASE_OFFICER_ID = :P_CASE_OFFICER_ID 
	AND CASE_ASSIGNED_TIME = :P_CASE_ASSIGNED_TIME AND CASE_ASSIGNED_DATE = :P_CASE_ASSIGNED_DATE
}

OIDCOASI_DELETE_OFFENDER_CASE_OFFICER {
	DELETE FROM OFFENDER_CASE_OFFICERS WHERE OFFENDER_BOOK_ID = :offenderBookId AND 
	to_date(to_char(CASE_ASSIGNED_DATE, 'YYYY/MM/DD'), 'YYYY/MM/DD')  >= current_date
}

OIDCOASI_INSERT_OFFENDER_CASE_OFFICER {
INSERT INTO OFFENDER_CASE_OFFICERS(CASE_OFFICER_ID, CASE_ASSIGNED_DATE, CASE_ASSIGNED_TIME, CASE_AGY_LOC_ID, OFFENDER_BOOK_ID, USER_ID, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME) VALUES (:CASE_OFFICER_ID, :CASE_ASSIGNED_DATE, OMS_UTILS_COMBINE_DATE_TIME(:CASE_ASSIGNED_DATE, :CASE_ASSIGNED_TIME), :CASE_AGY_LOC_ID, :OFFENDER_BOOK_ID, :USERID, :USERID, CURRENT_TIMESTAMP, null)
}
               
               