
OUMSTAFC_FIND_RGSTAFFSKILL {
 	SELECT REF_CODE.CODE  SKILL_TYPE ,REF_CODE.DESCRIPTION  DSP_DESCRIPTION4 FROM   REFERENCE_CODES REF_CODE WHERE   (DOMAIN ='STAFF_SKILLS' AND ( ACTIVE_FLAG = 'Y' OR '' <> 'NORMAL' ) ) ORDER BY  REF_CODE.LIST_SEQ ASC ,REF_CODE.DESCRIPTION ASC ,REF_CODE.CODE ASC
}

OUMSTAFC_FIND_RGPROGRAM {
 	SELECT PROGRAM_ID	PROG_ID , DESCRIPTION  PROG_DESC , PROGRAM_CODE  PROG_CODE  FROM PROGRAM_SERVICES     WHERE PROGRAM_CATEGORY = 'ACP' AND PROGRAM_CLASS = 'PRG' AND (ACTIVE_FLAG = 'Y' OR '' <> 'NORMAL' ) ORDER BY LIST_SEQ , DESCRIPTION
}

OUMSTAFC_FIND_RGSUBTYPE {
 	SELECT REF_CODE1.CODE  SUB_TYPE ,REF_CODE1.DESCRIPTION  DSP_DESCRIPTION3 FROM   REFERENCE_CODES REF_CODE1 WHERE   (DOMAIN = 'SKL_SUB_TYPE' AND PARENT_CODE = :skillType AND   (ACTIVE_FLAG = 'Y' OR '' <> 'NORMAL' ) ) ORDER BY  REF_CODE1.LIST_SEQ ASC ,REF_CODE1.DESCRIPTION ASC ,REF_CODE1.CODE ASC
}

OUMSTAFC_STSK_FIND_STAFF_SKILLS {
 	SELECT ROW_ID::text,STAFF_ID,SKILL_TYPE,SUB_TYPE,AS_OF_DATE,STSK_COMMENT,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,PROGRAM_ID,STAFF_SKILL_ID,ACTIVE_FLAG,EXPIRY_DATE,SEAL_FLAG  FROM STAFF_SKILLS  
}
OUMSTAFC_STSK_INSERT_STAFF_SKILLS {
	INSERT INTO STAFF_SKILLS(STAFF_ID,SKILL_TYPE,SUB_TYPE,AS_OF_DATE,STSK_COMMENT,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,PROGRAM_ID,STAFF_SKILL_ID,ACTIVE_FLAG,EXPIRY_DATE,SEAL_FLAG) VALUES(:staffId,:skillType,:subType,:asOfDate,:stskComment,CURRENT_TIMESTAMP,:createUserId,null,null,:programId,:staffSkillId,:activeFlag,:expiryDate,:sealFlag)
}

OUMSTAFC_STSK_UPDATE_STAFF_SKILLS {
	UPDATE STAFF_SKILLS set STAFF_ID=:staffId,SKILL_TYPE=:skillType,SUB_TYPE=:subType,AS_OF_DATE=:asOfDate,STSK_COMMENT=:stskComment,MODIFY_DATETIME=CURRENT_TIMESTAMP,MODIFY_USER_ID=:modifyUserId,PROGRAM_ID=:programId,STAFF_SKILL_ID=:staffSkillId,ACTIVE_FLAG=:activeFlag,EXPIRY_DATE=:expiryDate,SEAL_FLAG=:sealFlag
	where ROW_ID=(:rowId)::numeric
}
OUMSTAFC_STAFF_SKILL_ID_NEXT_VAL {
	SELECT nextval('STAFF_SKILL_ID') FROM  dual
}
