truncate table oms_modules_help restart identity;

insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('CALSCH','H','CALSCH.htm','CALSCH html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDADDRE','H','OCDADDRE.htm','OCDADDRE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDALERT ','H','OCDALERT.htm','OCDALERT  html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDALIAS','H','OCDALIAS.htm','OCDALIAS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDALTCC','H','OCDALTCC.htm','OCDALTCC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDATPOW','H','OCDATPOW.htm','OCDATPOW html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDAWORK','H','OCDAWORK.htm','OCDAWORK html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDCCASE','H','OCDCCASE.htm','OCDCCASE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDCLOGS','H','OCDCLOGS.htm','OCDCLOGS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDCLOSE','H','OCDCLOSE.htm','OCDCLOSE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDCREFU','H','OCDCREFU.htm','OCDCREFU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDEDEMP','H','OCDEDEMP.htm','OCDEDEMP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDEXPOW','H','OCDEXPOW.htm','OCDEXPOW html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDINTAK','H','OCDINTAK.htm','OCDINTAK html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDIPLAN','H','OCDIPLAN.htm','OCDIPLAN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDLANGS','H','OCDLANGS.htm','OCDLANGS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDMWORK','H','OCDMWORK.htm','OCDMWORK html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDNOQUE','H','OCDNOQUE.htm','OCDNOQUE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDORASS','H','OCDORASS.htm','OCDORASS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDOTASK','H','OCDOTASK.htm','OCDOTASK html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDPAYOB','H','OCDPAYOB.htm','OCDPAYOB html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDPERSO','H','OCDPERSO.htm','OCDPERSO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDRLFCC','H','OCDRLFCC.htm','OCDRLFCC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDSABUS','H','OCDSABUS.htm','OCDSABUS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDSUPST','H','OCDSUPST.htm','OCDSUPST html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDTAPOW','H','OCDTAPOW.htm','OCDTAPOW html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDTWORK','H','OCDTWORK.htm','OCDTWORK html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDVTEAM','H','OCDVTEAM.htm','OCDVTEAM html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDXPROG','H','OCDXPROG.htm','OCDXPROG html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCIDIARY','H','OCIDIARY.htm','OCIDIARY html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCIDOACC','H','OCIDOACC.htm','OCIDOACC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCIINTRR','H','OCIINTRR.htm','OCIINTRR html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCIIPLAN','H','OCIIPLAN.htm','OCIIPLAN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCIOCNOT','H','OCIOCNOT.htm','OCIOCNOT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCIPOWLO','H','OCIPOWLO.htm','OCIPOWLO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCIPOWOF','H','OCIPOWOF.htm','OCIPOWOF html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCISCATA','H','OCISCATA.htm','OCISCATA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCITTASK','H','OCITTASK.htm','OCITTASK html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCITTPOW','H','OCITTPOW.htm','OCITTPOW html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMSHIER','H','OCMSHIER.htm','OCMSHIER html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMSPRAC','H','OCMSPRAC.htm','OCMSPRAC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCRORREC','H','OCRORREC.htm','OCRORREC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUCOFFE','H','OCUCOFFE.htm','OCUCOFFE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDADMIS','H','OIDADMIS.htm','OIDADMIS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDBSIAP','H','OIDBSIAP.htm','OIDBSIAP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDBSTRN','H','OIDBSTRN.htm','OIDBSTRN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDBUTAB','H','OIDBUTAB.htm','OIDBUTAB html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDCAPPR','H','OIDCAPPR.htm','OIDCAPPR html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDCHLOC','H','OIDCHLOC.htm','OIDCHLOC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDCHOLO','H','OIDCHOLO.htm','OIDCHOLO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDCIPON','H','OIDCIPON.htm','OIDCIPON html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDCNOTE','H','OIDCNOTE.htm','OIDCNOTE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDCOASI','H','OIDCOASI.htm','OIDCOASI html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDCOUNT','H','OIDCOUNT.htm','OIDCOUNT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDDPROP','H','OIDDPROP.htm','OIDDPROP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDEHLOC','H','OIDEHLOC.htm','OIDEHLOC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDESCAP','H','OIDESCAP.htm','OIDESCAP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDINCDE','H','OIDINCDE.htm','OIDINCDE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDINTMV','H','OIDINTMV.htm','OIDINTMV html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDISSUE','H','OIDISSUE.htm','OIDISSUE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDISTAT','H','OIDISTAT.htm','OIDISTAT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDITRAN','H','OIDITRAN.htm','OIDITRAN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDMBRDT','H','OIDMBRDT.htm','OIDMBRDT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDMHIST','H','OIDMHIST.htm','OIDMHIST html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDMPITM','H','OIDMPITM.htm','OIDMPITM html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDOICUS','H','OIDOICUS.htm','OIDOICUS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDONONA','H','OIDONONA.htm','OIDONONA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDPAATT','H','OIDPAATT.htm','OIDPAATT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDPACTI','H','OIDPACTI.htm','OIDPACTI html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDPAWLI','H','OIDPAWLI.htm','OIDPAWLI html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDPIDEN','H','OIDPIDEN.htm','OIDPIDEN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDPINFO','H','OIDPINFO.htm','OIDPINFO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDRELEA','H','OIDRELEA.htm','OIDRELEA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDRELSC','H','OIDRELSC.htm','OIDRELSC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDRHLOC','H','OIDRHLOC.htm','OIDRHLOC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDRPLAN','H','OIDRPLAN.htm','OIDRPLAN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDRTCON','H','OIDRTCON.htm','OIDRTCON html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSCEXM','H','OIDSCEXM.htm','OIDSCEXM html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSCHAC','H','OIDSCHAC.htm','OIDSCHAC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSCMOV','H','OIDSCMOV.htm','OIDSCMOV html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSHLOG','H','OIDSHLOG.htm','OIDSHLOG html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSIAPP','H','OIDSIAPP.htm','OIDSIAPP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSTABS','H','OIDSTABS.htm','OIDSTABS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSTEST','H','OIDSTEST.htm','OIDSTEST html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSTOJU','H','OIDSTOJU.htm','OIDSTOJU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSTWJU','H','OIDSTWJU.htm','OIDSTWJU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSUBLC','H','OIDSUBLC.htm','OIDSUBLC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDTPCON','H','OIDTPCON.htm','OIDTPCON html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDTROJU','H','OIDTROJU.htm','OIDTROJU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDTRWJU','H','OIDTRWJU.htm','OIDTRWJU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDUNCTA','H','OIDUNCTA.htm','OIDUNCTA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDVCONT','H','OIDVCONT.htm','OIDVCONT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDVERCC','H','OIDVERCC.htm','OIDVERCC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDVIRES','H','OIDVIRES.htm','OIDVIRES html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDVISIT','H','OIDVISIT.htm','OIDVISIT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDVTOUR','H','OIDVTOUR.htm','OIDVTOUR html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIICLASS','H','OIICLASS.htm','OIICLASS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIDMOVE','H','OIIDMOVE.htm','OIIDMOVE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIEMOVE','H','OIIEMOVE.htm','OIIEMOVE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIGRIEV','H','OIIGRIEV.htm','OIIGRIEV html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIHISCO','H','OIIHISCO.htm','OIIHISCO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIINLOG','H','OIIINLOG.htm','OIIINLOG html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIISCOU','H','OIIISCOU.htm','OIIISCOU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIINAMES','H','OIINAMES.htm','OIINAMES html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIOICUS','H','OIIOICUS.htm','OIIOICUS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIPCLOC','H','OIIPCLOC.htm','OIIPCLOC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIPCTRA','H','OIIPCTRA.htm','OIIPCTRA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIPROLL','H','OIIPROLL.htm','OIIPROLL html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIPTRAN','H','OIIPTRAN.htm','OIIPTRAN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIISCHED','H','OIISCHED.htm','OIISCHED html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIISHLOG','H','OIISHLOG.htm','OIISHLOG html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIITGDET','H','OIITGDET.htm','OIITGDET html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIVISIT','H','OIIVISIT.htm','OIIVISIT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIIWLTWJ','H','OIIWLTWJ.htm','OIIWLTWJ html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMISSUE','H','OIMISSUE.htm','OIMISSUE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OMUVREST','H','OMUVREST.htm','OMUVREST html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OSIOSEAR','H','OSIOSEAR.htm','OSIOSEAR html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OSIPSEAR','H','OSIPSEAR.htm','OSIPSEAR html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OSISTGKW','H','OSISTGKW.htm','OSISTGKW html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OTDCLOSE','H','OTDCLOSE.htm','OTDCLOSE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OTDCNTAC','H','OTDCNTAC.htm','OTDCNTAC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OTDSUBAT','H','OTDSUBAT.htm','OTDSUBAT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OTINAMES','H','OTINAMES.htm','OTINAMES html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OTIOPINQ','H','OTIOPINQ.htm','OTIOPINQ html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMAUDIT','H','OUMAUDIT.htm','OUMAUDIT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OWHEADER','H','OWHEADER.htm','OWHEADER html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('HOUSE_ADM','H','HOUSE_ADM.htm','HOUSE_ADM html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMCPREV','H','OCMCPREV.htm','OCMCPREV html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMDEDUT','H','OCMDEDUT.htm','OCMDEDUT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMDEFTM','H','OCMDEFTM.htm','OCMDEFTM html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMEVENT','H','OCMEVENT.htm','OCMEVENT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMFAPRO','H','OCMFAPRO.htm','OCMFAPRO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMNOQUE','H','OCMNOQUE.htm','OCMNOQUE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMOHSTA','H','OCMOHSTA.htm','OCMOHSTA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMPCONF','H','OCMPCONF.htm','OCMPCONF html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMSERVI','H','OCMSERVI.htm','OCMSERVI html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMSUWPJ','H','OCMSUWPJ.htm','OCMSUWPJ html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMTEAMS','H','OCMTEAMS.htm','OCMTEAMS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMTNAVI','H','OCMTNAVI.htm','OCMTNAVI html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMWORKS','H','OCMWORKS.htm','OCMWORKS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCMXPROG','H','OCMXPROG.htm','OCMXPROG html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMADMIS','H','OIMADMIS.htm','OIMADMIS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMCOUNT','H','OIMCOUNT.htm','OIMCOUNT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMCTACT','H','OIMCTACT.htm','OIMCTACT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMILOCA','H','OIMILOCA.htm','OIMILOCA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMISREA','H','OIMISREA.htm','OIMISREA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMMHOLO','H','OIMMHOLO.htm','OIMMHOLO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMPLDUR','H','OIMPLDUR.htm','OIMPLDUR html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMPRFCA','H','OIMPRFCA.htm','OIMPRFCA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMPRFCO','H','OIMPRFCO.htm','OIMPRFCO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMSLEVL','H','OIMSLEVL.htm','OIMSLEVL html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMTGNGS','H','OIMTGNGS.htm','OIMTGNGS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMULOCA','H','OIMULOCA.htm','OIMULOCA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMVDTSL','H','OIMVDTSL.htm','OIMVDTSL html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIMVLIMT','H','OIMVLIMT.htm','OIMVLIMT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OLISET','H','OLISET.htm','OLISET html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OMSHELP','H','OMSHELP.htm','OMSHELP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OMUNVARY','H','OMUNVARY.htm','OMUNVARY html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUISDIRE','H','OUISDIRE.htm','OUISDIRE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMACASE','H','OUMACASE.htm','OUMACASE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMAGENC','H','OUMAGENC.htm','OUMAGENC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMAGLOC','H','OUMAGLOC.htm','OUMAGLOC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMAGYRG','H','OUMAGYRG.htm','OUMAGYRG html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMAPASS','H','OUMAPASS.htm','OUMAPASS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMASSMU','H','OUMASSMU.htm','OUMASSMU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMBADMI','H','OUMBADMI.htm','OUMBADMI html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMBMARK','H','OUMBMARK.htm','OUMBMARK html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMCDTAB','H','OUMCDTAB.htm','OUMCDTAB html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMDTEMP','H','OUMDTEMP.htm','OUMDTEMP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMEEMOV','H','OUMEEMOV.htm','OUMEEMOV html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMEMOVE','H','OUMEMOVE.htm','OUMEMOVE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMFORMS','H','OUMFORMS.htm','OUMFORMS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMHLHIS','H','OUMHLHIS.htm','OUMHLHIS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMINOUT','H','OUMINOUT.htm','OUMINOUT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMMENUS','H','OUMMENUS.htm','OUMMENUS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMPERSO','H','OUMPERSO.htm','OUMPERSO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMRAREA','H','OUMRAREA.htm','OUMRAREA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMRCODE','H','OUMRCODE.htm','OUMRCODE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMRESTA','H','OUMRESTA.htm','OUMRESTA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMROLES','H','OUMROLES.htm','OUMROLES html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMSMALA','H','OUMSMALA.htm','OUMSMALA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMSMUGA','H','OUMSMUGA.htm','OUMSMUGA html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMSYLAB','H','OUMSYLAB.htm','OUMSYLAB html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMUCREAT','H','OUMUCREAT.htm','OUMUCREAT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMUSERS','H','OUMUSERS.htm','OUMUSERS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMWMENU','H','OUMWMENU.htm','OUMWMENU html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OYMHOLID','H','OYMHOLID.htm','OYMHOLID html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('UPDOFFID','H','UPDOFFID.htm','UPDOFFID html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('HOUSING','H','HOUSING.htm','HOUSING html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDALTCC','H','OCDALTCC.htm','OCDALTCC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDCCONT','H','OCDCCONT.htm','OCDCCONT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDGNUMB','H','OCDGNUMB.htm','OCDGNUMB html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDOAPOP','H','OCDOAPOP.htm','OCDOAPOP html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDRLFCC','H','OCDRLFCC.htm','OCDRLFCC html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCDSMEMO','H','OCDSMEMO.htm','OCDSMEMO html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUALERT','H','OCUALERT.htm','OCUALERT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUAVISN','H','OCUAVISN.htm','OCUAVISN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUCLOFF','H','OCUCLOFF.htm','OCUCLOFF html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUCNPER','H','OCUCNPER.htm','OCUCNPER html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUCSTAF','H','OCUCSTAF.htm','OCUCSTAF html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUTASAT','H','OCUTASAT.htm','OCUTASAT html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUVERIF','H','OCUVERIF.htm','OCUVERIF html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OCUWKHTY','H','OCUWKHTY.htm','OCUWKHTY html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDOFVER','H','OIDOFVER.htm','OIDOFVER html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIDSTGIN','H','OIDSTGIN.htm','OIDSTGIN html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIUIMAGE','H','OIUIMAGE.htm','OIUIMAGE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIUIWPVE','H','OIUIWPVE.htm','OIUIWPVE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OIUOVRES','H','OIUOVRES.htm','OIUOVRES html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OMUAPRIS','H','OMUAPRIS.htm','OMUAPRIS html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OMUAVBED','H','OMUAVBED.htm','OMUAVBED html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OSINAMES','H','OSINAMES.htm','OSINAMES html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OTUCPAYE','H','OTUCPAYE.htm','OTUCPAYE html file');
insert into oms_modules_help(module_name,help_type,help_url,help_desc) 
 values('OUMSTAFC','H','OUMSTAFC.htm','OUMSTAFC html file');
