GET_REQUIREMENT{
SELECT DESCRIPTION FROM COMMUNITY_CONDITIONS WHERE COMM_CONDITION_CODE = :P_COMM_CONDITION_CODE AND COMM_CONDITION_TYPE = :P_COMM_CONDITION_TYPE AND CATEGORY_TYPE = :P_CATEGORY_TYPE
}