
OIMLEGSU_FIND_RGLEGALCLASS {
 	SELECT DESCRIPTION ,   CODE    FROM REFERENCE_CODES   WHERE DOMAIN = 'LEGAL_BLOCK'    AND (   (ACTIVE_FLAG = 'Y' ) OR '' = 'ENTER-QUERY'  ) ORDER BY LIST_SEQ , DESCRIPTION
}

OIMLEGSU_FIND_RGUPDATEREASONCODE {
 	select DESCRIPTION , UPDATE_REASON_CODE CODE , OMS_MISCELLANEOUS_GETDESCCODE('LGL_RSN_CAT' , REASON_CATEGORY ) RC_DESC , OMS_MISCELLANEOUS_GETDESCCODE('ACTIVE_TYPE' , ACTIVE_TYPE ) AT_DESC from LEGAL_UPDATE_REASONS where ( (ACTIVE_FLAG = 'Y' ) ) order by LIST_SEQ , DESCRIPTION
}

OIMLEGSU_LGLUPDUSAGES_FIND_LEGAL_UPDATE_USAGES {
 	SELECT LEGAL_CLASS ,UPDATE_REASON_CODE ,ACTIVE_FLAG ,EXPIRY_DATE ,LIST_SEQ ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM LEGAL_UPDATE_USAGES 
}
OIMLEGSU_LGLUPDUSAGES_INSERT_LEGAL_UPDATE_USAGES {
	insert into LEGAL_UPDATE_USAGES(LEGAL_CLASS , UPDATE_REASON_CODE , ACTIVE_FLAG , EXPIRY_DATE , LIST_SEQ , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:legalClass , :updateReasonCode , :activeFlag , :expiryDate , :listSeq , CURRENT_TIMESTAMP , :createUserId , NULL, :sealFlag )
}

OIMLEGSU_LGLUPDUSAGES_UPDATE_LEGAL_UPDATE_USAGES {
	update LEGAL_UPDATE_USAGES set LEGAL_CLASS = :legalClass , UPDATE_REASON_CODE = :updateReasonCode , ACTIVE_FLAG = :activeFlag , EXPIRY_DATE = :expiryDate , LIST_SEQ = :listSeq , MODIFY_DATETIME =CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where LEGAL_CLASS = :legalClass and UPDATE_REASON_CODE = :updateReasonCode
}

OIMLEGSU_LGLUPDUSAGES_DELETE_LEGAL_UPDATE_USAGES { 
	DELETE FROM LEGAL_UPDATE_USAGES WHERE LEGAL_CLASS  = :legalClass AND UPDATE_REASON_CODE  = :updateReasonCode
}

OIMLEGSU_PROCEDURE_DATA {
 SELECT description, oms_miscellaneous_getdesccode ( 'LGL_RSN_CAT', reason_category ) reason_category, oms_miscellaneous_getdesccode ( 'ACTIVE_TYPE', active_type ) active_type
 FROM legal_update_reasons WHERE update_reason_code = :PUPDATEREASONCODE
}

OIMLEGSU_KEY_DEL_REC {
SELECT COUNT(*)
           FROM sentence_update_reasons
          WHERE update_reason_code = :PREASONCODE
            AND legal_class = :PLEGALCLASS
}