
OUMHOCOD_HOCODES_FIND_HO_CODES {
 	SELECT HO_CODE ,DESCRIPTION ,ACTIVE_FLAG ,EXPIRY_DATE ,CREATE_USER_ID ,CREATE_DATE ,MODIFY_USER_ID ,MODIFY_DATETIME ,CREATE_DATETIME ,SEAL_FLAG   FROM HO_CODES
}
OUMHOCOD_HOCODES_INSERT_HO_CODES {
 insert into HO_CODES(HO_CODE , DESCRIPTION , ACTIVE_FLAG , EXPIRY_DATE , CREATE_USER_ID , CREATE_DATE , MODIFY_DATETIME , CREATE_DATETIME , SEAL_FLAG ) values(:hoCode , :description , :activeFlag , :expiryDate , :createUserId , :createDate , NULL , CURRENT_TIMESTAMP , :sealFlag ) 
}

OUMHOCOD_HOCODES_UPDATE_HO_CODES {
	 update HO_CODES set HO_CODE = :hoCode , DESCRIPTION = :description , ACTIVE_FLAG = :activeFlag , EXPIRY_DATE = :expiryDate, MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP , SEAL_FLAG = :sealFlag where HO_CODE = :hoCode
}

OUMHOCOD_HOCODES_DELETE_HO_CODES { 
	DELETE FROM HO_CODES where HO_CODE  = :hoCode
}


OUMHOCOD_HO_CODES_KEYDELREC {
	SELECT COUNT (*) FROM OFFENCES WHERE HO_CODE = :HOCODE
}
