
OIMISREA_FIND_RGINTSCHRSN {
 	SELECT DESCRIPTION ,        CODE ,         LIST_SEQ     FROM REFERENCE_CODES   WHERE DOMAIN = 'INT_SCH_RSN'    AND ACTIVE_FLAG = 'Y' ORDER BY 3 , 1
}

OIMISREA_FIND_RGINTSCHTYPE {
 	SELECT DESCRIPTION ,        CODE ,         LIST_SEQ     FROM REFERENCE_CODES   WHERE DOMAIN = 'INT_SCH_TYPE'    AND ACTIVE_FLAG = 'Y' ORDER BY  3 , 1
}

OIMISREA_INTSR_FIND_INTERNAL_SCHEDULE_REASONS {
 	SELECT INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_RSN_CODE, DESCRIPTION, ACTIVE_FLAG, LIST_SEQ, EXPIRY_DATE, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM INTERNAL_SCHEDULE_REASONS
}
OIMISREA_INTSR_INSERT_INTERNAL_SCHEDULE_REASONS {
     insert into INTERNAL_SCHEDULE_REASONS(INTERNAL_SCHEDULE_TYPE, INTERNAL_SCHEDULE_RSN_CODE, DESCRIPTION, ACTIVE_FLAG, LIST_SEQ, EXPIRY_DATE, CREATE_USER_ID, CREATE_DATETIME, SEAL_FLAG, MODIFY_USER_ID, MODIFY_DATETIME) values(:internalScheduleType, :internalScheduleRsnCode, :description, :activeFlag, :listSeq, :expiryDate, :createUserId, CURRENT_TIMESTAMP, :sealFlag, null, null)
}

OIMISREA_INTSR_UPDATE_INTERNAL_SCHEDULE_REASONS {
	 update INTERNAL_SCHEDULE_REASONS set INTERNAL_SCHEDULE_TYPE =:internalScheduleType, INTERNAL_SCHEDULE_RSN_CODE =:internalScheduleRsnCode, DESCRIPTION =:description, ACTIVE_FLAG =:activeFlag, LIST_SEQ =:listSeq, EXPIRY_DATE =:expiryDate, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID =:modifyUserId, SEAL_FLAG =:sealFlag where INTERNAL_SCHEDULE_TYPE =:internalScheduleType and INTERNAL_SCHEDULE_RSN_CODE =:internalScheduleRsnCode
}

OIMISREA_INTSR_DELETE_INTERNAL_SCHEDULE_REASONS { 
	DELETE FROM INTERNAL_SCHEDULE_REASONS WHERE INTERNAL_SCHEDULE_TYPE=:internalScheduleType AND INTERNAL_SCHEDULE_RSN_CODE=:internalScheduleRsnCode 
}


OIMISREA_INT_SR_KEYDELREC {
	SELECT COUNT(*) FROM OFFENDER_IND_SCHEDULES WHERE EVENT_TYPE = :EVENTTYPE AND EVENT_SUB_TYPE = :EVENTSUBTYPE
}
