GET_OFF_DETAILS_BY_BOOK_ID_OFF_DET_CUR {

	SELECT O.OFFENDER_ID_DISPLAY, O.LAST_NAME, O.FIRST_NAME, OB.AGY_LOC_ID FROM OFFENDER_BOOKINGS OB, OFFENDERS O WHERE OB.OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID AND OB.OFFENDER_ID = O.OFFENDER_ID

}

GET_OFF_BOOK_ID{
select offender_book_id from v_name_search2_fn(:userId) where offender_id_display = :p_off_id_disp
}
GET_OFFENDER_DETAILS_NEW{
 exists ( select 1 from CASELOAD_AGENCY_LOCATIONS B where B.CASELOAD_ID = :P_CASELOAD_ID and B.AGY_LOC_ID = OB.AGY_LOC_ID and ( coalesce (:P_AGY_LOC_ID,'') = '' or B.AGY_LOC_ID = :P_AGY_LOC_ID ))
}                                
--SELECT DISTINCT OB.OFFENDER_BOOK_ID, O.LAST_NAME, O.FIRST_NAME, OB.AGY_LOC_ID FROM OFFENDERS O, OFFENDER_BOOKINGS OB WHERE O.OFFENDER_ID_DISPLAY = :P_OFFENDER_ID_DISPLAY AND O.OFFENDER_ID = OB.OFFENDER_ID AND OB.ACTIVE_FLAG = 'Y' AND EXISTS ( SELECT 1 FROM CASELOAD_AGENCY_LOCATIONS B WHERE B.CASELOAD_ID = :P_CASELOAD_ID AND B.AGY_LOC_ID = OB.AGY_LOC_ID AND ( :P_AGY_LOC_ID IS NULL OR B.AGY_LOC_ID = :P_AGY_LOC_ID ))

