DELETE FROM REFERENCE_CODES where domain = 'REP_REQ_STS' and code = 'UNALLOC';
DELETE FROM REFERENCE_CODES where domain = 'REP_REQ_STS' and code = 'ALLOC';

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'UNALLOC' ,'Unallocated' ,1,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

INSERT INTO REFERENCE_CODES(DOMAIN ,CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,SYSTEM_DATA_FLAG ,MODIFY_USER_ID ,EXPIRED_DATE ,NEW_CODE ,PARENT_CODE ,PARENT_DOMAIN ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG )
VALUES('REP_REQ_STS' ,'ALLOC' ,'Allocated' ,2,'Y' ,'Y' ,'OMS_OWNER' ,NULL ,NULL ,NULL ,NULL ,CURRENT_TIMESTAMP ,'OMS_OWNER' ,CURRENT_TIMESTAMP ,NULL );

