-----------S4-19781
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.panetitle','Care In Placment Inquiry','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.paneltitle','Active Care In Placment Search','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.ciptype','CIP Type','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.cipreason','CIP Reason','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.careinplacement','Care In Placment - Active','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.pid','PID#','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.lastname','Last Name','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.firstname','First Name','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.typeofcip','Type of CIP','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.reason','Reason','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.timeservedhours','Time Served: Hours','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.timeserveddays','Time Served: Days','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.reviewdate','Review Date','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.expirydate','Expiry Date','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (nextval('LABLE_ID_SEQUENCE'), 'OIICIPON','oiicipon.details','Details','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OCONDAWAIT','ocondawait.assignedtosameteam','Retrieved Conditions are in Same Team.Please select another Team to Assign.','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OCONDAWAIT','ocondawait.assignedtosamelocation','Retrieved Conditions are in Same Location.Please select another Location to Assign.','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OCONDTRF','ocondtrf.assignedtosamestaffmember','The selected Conditon is Assigned to same Staff Member.Please select another Staff Member.','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OCONDTRF','ocondtrf.assignedtosameteam','Retrieved Conditions are in Same Team.Please select another Team to Assign.','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OCONDTRF','ocondtrf.assignedtosamelocation','Retrieved Conditions are in Same Location.Please select another Location to Assign.','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OCONDTRF','ocondtrf.pleaseselectanyoneassignee','Please Select Any One of the Assignee','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);
  
INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)  
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.passwordresetwithmailconfigured','Password Reset successfully  and new password has sent to user’s email address. The newly generated password is %password%.','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS(LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)  
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.passwordresetwithoutmailconfigured','Password Reset successfully and email could not be sent to User as there is no email configured. The newly generated password is %password%.','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.passwordsuccess','Password Reset/Updated Successfully','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.insightsuser','Insights User','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.insightsuserid','User Id','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.mailid','Mail Id','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.status','Status','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO OMS_OWNER.SYSTEM_LABELS (LABEL_ID,MODULE_NAME,MSG_KEY,MSG_VALUE,MSG_TYPE,CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
VALUES (NEXTVAL('LABLE_ID_SEQUENCE'), 'OUMUSERS','oumusers.insightsaccess','Insight Access','LABEL',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP,NULL,NULL);  

--
UPDATE SYSTEM_LABELS 
   SET modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER' 
	  ,MSG_VALUE = 'Elite 5.0.0.0.11_HF2' 
 WHERE MODULE_NAME = 'LOGIN' AND MSG_KEY IN ('home.title.header', 'login.header');