
OTMLOCKR_LOCKMOD_FIND_LOCKED_MODULES {
-- 	SELECT MODULE_NAME,CASELOAD_ID,USER_ID,LOCKED_DATE,OFFENDER_ID,SESSION_ID,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,AGY_LOC_ID,SEAL_FLAG,ACCOUNT_CODE, ROWIDTOCHAR(ROWID) ROW_ID FROM LOCKED_MODULES  /* where  */
SELECT MODULE_NAME,CASELOAD_ID,USER_ID,LOCKED_DATE,OFFENDER_ID,SESSION_ID,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,AGY_LOC_ID,SEAL_FLAG,ACCOUNT_CODE,
 	 ROW_ID FROM LOCKED_MODULES 
}
OTMLOCKR_LOCKMOD_INSERT_LOCKED_MODULES {
--	INSERT INTO LOCKED_MODULES(MODULE_NAME,CASELOAD_ID,USER_ID,LOCKED_DATE,OFFENDER_ID,SESSION_ID,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,AGY_LOC_ID,SEAL_FLAG,ACCOUNT_CODE) VALUES(:moduleName,:caseloadId,:userId,:lockedDate,:offenderId,:sessionId,:createDatetime,:createUserId,:modifyDatetime,:modifyUserId,:agyLocId,:sealFlag,:accountCode)
	insert into LOCKED_MODULES(MODULE_NAME, CASELOAD_ID, USER_ID, LOCKED_DATE, OFFENDER_ID, SESSION_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, AGY_LOC_ID, SEAL_FLAG, ACCOUNT_CODE) values(:moduleName, :caseloadId, :userId, :lockedDate, :offenderId, :sessionId, current_timestamp, :createUserId, current_timestamp, :agyLocId, :sealFlag, :accountCode)
}

OTMLOCKR_LOCKMOD_UPDATE_LOCKED_MODULES {
--	UPDATE LOCKED_MODULES set MODULE_NAME=:moduleName,CASELOAD_ID=:caseloadId,USER_ID=:userId,LOCKED_DATE=:lockedDate,OFFENDER_ID=:offenderId,SESSION_ID=:sessionId,CREATE_DATETIME=:createDatetime,CREATE_USER_ID=:createUserId,MODIFY_DATETIME=:modifyDatetime,MODIFY_USER_ID=:modifyUserId,AGY_LOC_ID=:agyLocId,SEAL_FLAG=:sealFlag,ACCOUNT_CODE=:accountCode 
--	where MODULE_NAME=:moduleName AND CASELOAD_ID=:caseloadId AND ROWID=:rowId
	update LOCKED_MODULES set MODULE_NAME =:moduleName, CASELOAD_ID =:caseloadId, USER_ID =:userId, LOCKED_DATE =:lockedDate, OFFENDER_ID =:offenderId, SESSION_ID =:sessionId, MODIFY_DATETIME =current_timestamp, MODIFY_USER_ID =:modifyUserId, AGY_LOC_ID =:agyLocId, SEAL_FLAG =:sealFlag, ACCOUNT_CODE =:accountCode where MODULE_NAME =:moduleName and CASELOAD_ID =:caseloadId and ROW_ID =:rowId
}

OTMLOCKR_LOCKMOD_DELETE_LOCKED_MODULES { 
	DELETE FROM LOCKED_MODULES where MODULE_NAME=:moduleName AND CASELOAD_ID=:caseloadId AND ROW_ID=:rowId
}


OTMLOCKR_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OTMLOCKR_GET_REPOTING_LOC_ID {
	SELECT REPORTING_LOC_ID FROM AGENCY_COUNTS WHERE REPORTING_LOC_ID = (SELECT REPORTING_LOC_ID FROM agency_counts WHERE CREATE_USER_ID = :createUserId AND CREATE_DATETIME = (SELECT MAX(CREATE_DATETIME) FROM AGENCY_COUNTS WHERE CREATE_USER_ID = :createUserId)) AND COUNT_IN_PROGRESS = 'Y'
}

OTMLOCKR_DELETE_AGENCY_LOCATION_COUNTS {
	DELETE FROM AGENCY_LOCATION_COUNTS WHERE REPORTING_LOC_ID = :repotingLocId
}

OTMLOCKR_DELETE_INITIATE_RECORDS {
	DELETE FROM AGENCY_COUNTS WHERE REPORTING_LOC_ID = :repotingLocId
}
