
OUMAGYRG_FIND_AGENCYLOCATIONTYPERG {
 	SELECT REF_CODE.CODE CODE , REF_CODE.DESCRIPTION DESCRIPTION FROM REFERENCE_CODES REF_CODE WHERE DOMAIN = 'AGY_LOC_TYPE' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ , CODE , DESCRIPTION
}

OUMAGYRG_FIND_GEOGRAPHICREGIONRG {
 	SELECT REF_CODE.CODE CODE        ,REF_CODE.DESCRIPTION  DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'GEOGRAPHIC'  AND    ((ACTIVE_FLAG = 'Y'  AND    EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ , CODE , DESCRIPTION
}

OUMAGYRG_FIND_SUBAREARG {
 	SELECT AREA_CODE CODE , DESCRIPTION FROM AREAS WHERE AREA_TYPE = :AGENCYLOCATIONTYPE AND AREA_CLASS = 'SUB_AREA' AND PARENT_AREA_CODE = :AREACODE AND ((ACTIVE_FLAG = 'Y' AND EXPIRY_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ, CODE , DESCRIPTION 
}
OUMAGYRG_FIND_SUBAREARG_TOT {
 	SELECT DISTINCT PARENT_AREA_CODE CODE  FROM AREAS WHERE  AREA_CLASS = 'SUB_AREA'  AND ((ACTIVE_FLAG = 'Y' AND EXPIRY_DATE IS NULL ) OR '' = 'ENTER-QUERY' )}


OUMAGYRG_FIND_AREARG {
 	SELECT  area_code CODE, DESCRIPTION FROM areas WHERE area_type = :AGENCYLOCATIONTYPE AND area_class = 'AREA' AND parent_area_code = :NOMSREGIONCODE
    AND ( ( active_flag = 'Y'  AND expiry_date IS NULL ) OR '' = 'ENTER-QUERY' )  ORDER by  LIST_SEQ, CODE , DESCRIPTION 
}

OUMAGYRG_FIND_AREARG_TOT {
SELECT DISTINCT PARENT_AREA_CODE CODE,AREA_TYPE FROM AREAS WHERE  AREA_CLASS = 'AREA'AND ( ( ACTIVE_FLAG = 'Y'  AND EXPIRY_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) 
 }
OUMAGYRG_FIND_JUSTICEAREARG {
 	SELECT REF_CODE.CODE CODE        ,REF_CODE.DESCRIPTION  DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'LOCAL_AREA'  AND    ((ACTIVE_FLAG = 'Y'  AND    EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ , CODE , DESCRIPTION
}

OUMAGYRG_FIND_NOMSREGIONRG {
 	SELECT AREA_CODE CODE , DESCRIPTION FROM AREAS WHERE AREA_CLASS = 'REGION' AND ((ACTIVE_FLAG = 'Y' AND EXPIRY_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ, CODE , DESCRIPTION  
}
OUMAGYRG_AGYLOC_FIND_AGENCY_LOCATIONS {
 	SELECT AGY_LOC_ID, DESCRIPTION, AGENCY_LOCATION_TYPE, DISTRICT_CODE, ABBREVIATION, DEACTIVATION_DATE, CONTACT_NAME, PRINT_QUEUE, JURISDICTION_CODE, BAIL_OFFICE_FLAG, LIST_SEQ, 
 	HOUSING_LEV_1_CODE, HOUSING_LEV_2_CODE, HOUSING_LEV_3_CODE, HOUSING_LEV_4_CODE, PROPERTY_LEV_1_CODE, PROPERTY_LEV_2_CODE, PROPERTY_LEV_3_CODE, LAST_BOOKING_NO, COMMISSARY_PRIVILEGE, 
 	BUSINESS_HOURS, ADDRESS_TYPE, ACTIVE_FLAG, DISABILITY_ACCESS_CODE, INTAKE_FLAG, SUB_AREA_CODE, AREA_CODE,  NOMS_REGION_CODE ,GEOGRAPHIC_REGION_CODE, JUSTICE_AREA_CODE, CREATE_DATETIME, 
 	CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, LONG_DESCRIPTION, LABCORP_CLIENT_ID, SEAL_FLAG FROM AGENCY_LOCATIONS  WHERE agy_loc_id NOT IN ('OUT', 'TRN')  ORDER BY AGY_LOC_ID
}
OUMAGYRG_AGYLOC_UPDATE_AGENCY_LOCATIONS {
 update AGENCY_LOCATIONS set AGY_LOC_ID =:agyLocId, DESCRIPTION =:description, AGENCY_LOCATION_TYPE =:agencyLocationType, DISTRICT_CODE =:districtCode, ABBREVIATION =:Abbreviation, DEACTIVATION_DATE =:deactivationDate, CONTACT_NAME =:contactName, PRINT_QUEUE =:printQueue, JURISDICTION_CODE =:jurisdictionCode, BAIL_OFFICE_FLAG =:bailOfficeFlag, LIST_SEQ =:listSeq, HOUSING_LEV_1_CODE =:housingLev1Code, HOUSING_LEV_2_CODE =:housingLev1Code, HOUSING_LEV_3_CODE =:housingLev3Code , HOUSING_LEV_4_CODE =:housingLev4Code, PROPERTY_LEV_1_CODE =:propertyLev1Code, PROPERTY_LEV_2_CODE =:propertyLev2Code, PROPERTY_LEV_3_CODE =:propertyLev3Code, LAST_BOOKING_NO =:lastBookingNo, COMMISSARY_PRIVILEGE =:commissaryPrivilege, BUSINESS_HOURS =:businessHours, ADDRESS_TYPE =:addressType, ACTIVE_FLAG =:activeFlag, DISABILITY_ACCESS_CODE =:disabilityAccessCode, INTAKE_FLAG =:intakeFlag, SUB_AREA_CODE =:subAreaCode, AREA_CODE =:areaCode, NOMS_REGION_CODE =:nomsRegionCode, GEOGRAPHIC_REGION_CODE =:geographicRegionCode, JUSTICE_AREA_CODE =:justiceAreaCode, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID =:modifyUserId, LONG_DESCRIPTION =:longDescription, LABCORP_CLIENT_ID =:labcorpClientId, SEAL_FLAG =:sealFlag where agy_loc_id =:agyLocId 
}
