
OUMFORMS_FIND_RGMODULENAME {
SELECT OMS_MOD2.MODULE_NAME CODE ,OMS_MOD2.DESCRIPTION DESCRIPTION FROM OMS_MODULES OMS_MOD2 WHERE MODULE_TYPE = 'SCREEN' 
}

OUMFORMS_FIND_RGTABLENAME {
SELECT DISTINCT upper(TABLE_NAME) CODE, upper(TABLE_NAME) DESCRIPTION FROM ALL_TAB_COLUMNS where
 	Upper(column_name)IN ( 'OFFENDER_BOOK_ID' ,'OFFENDER_ID' ,'OFFENDER_BOOKING_ID' ,'STG_ID' ) ORDER BY 1 
}

OUMFORMS_FIND_RGDESTINATIONFORM { 
 	SELECT OMS_MOD1.MODULE_NAME  CODE, OMS_MOD1.DESCRIPTION  DESCRIPTION FROM   OMS_MODULES OMS_MOD1 WHERE   MODULE_TYPE = 'SCREEN'
}

OUMFORMS_OMSMOD_FIND_OMS_MODULES {
 	SELECT MODULE_NAME, DESCRIPTION, MODULE_TYPE, PRINT_FORMAT_CODE, PREVIEW_FLAG, DEFAULT_COPY, APPLN_CODE, HELP_DIRECTORY, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG, OUTPUT_TYPE FROM OMS_MODULES  WHERE MODULE_TYPE = 'SCREEN'
}
OUMFORMS_FAF_FIND_FORM_ACCESSIBLE_FORMS {
 	SELECT ORIGINATING_FORM, DESTINATION_FORM, LIST_SEQ, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID,SEAL_FLAG FROM FORM_ACCESSIBLE_FORMS
}
OUMFORMS_FAF_INSERT_FORM_ACCESSIBLE_FORMS {
     insert into FORM_ACCESSIBLE_FORMS(ORIGINATING_FORM, DESTINATION_FORM, LIST_SEQ, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) values(:originatingForm, :destinationForm, :listSeq, CURRENT_TIMESTAMP, :createUserId, NULL, :sealFlag)
}

OUMFORMS_FAF_UPDATE_FORM_ACCESSIBLE_FORMS {
update FORM_ACCESSIBLE_FORMS F set ORIGINATING_FORM =:originatingForm, DESTINATION_FORM =:destinationForm, LIST_SEQ =:listSeq, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID = :modifyUserId, SEAL_FLAG =:sealFlag where F.ORIGINATING_FORM = :originatingForm and F.DESTINATION_FORM = :destinationForm 
}

OUMFORMS_FAF_DELETE_FORM_ACCESSIBLE_FORMS { 
	DELETE FROM FORM_ACCESSIBLE_FORMS F WHERE F.ORIGINATING_FORM = :originatingForm and F.DESTINATION_FORM = :destinationForm
}

OUMFORMS_ACCESSTAB_FIND_ACCESSIBLE_FORM_TABLES {
SELECT ORIGINATING_FORM, DESTINATION_FORM, upper(TABLE_NAME) TABLE_NAME, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG  FROM ACCESSIBLE_FORM_TABLES  WHERE ORIGINATING_FORM  =:originatingForm and DESTINATION_FORM  =:destinationForm
}
OUMFORMS_ACCESSTAB_INSERT_ACCESSIBLE_FORM_TABLES {
    insert into ACCESSIBLE_FORM_TABLES( ORIGINATING_FORM, DESTINATION_FORM, TABLE_NAME, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) values( :originatingForm, :destinationForm, :tableName, CURRENT_TIMESTAMP, :createUserId, NULL, :sealFlag)
}
			
OUMFORMS_ACCESSTAB_DELETE_ACCESSIBLE_FORM_TABLES { 
	DELETE FROM ACCESSIBLE_FORM_TABLES A WHERE A.ORIGINATING_FORM = :originatingForm and A.DESTINATION_FORM = :destinationForm 
}

OUMFORMS_CONSTRAINT_VALIDATIONS {
 select
 tc.table_name
from
 information_schema.table_constraints as tc
join information_schema.key_column_usage as kcu on
 tc.constraint_name = kcu.constraint_name
 and tc.table_schema = kcu.table_schema
join information_schema.constraint_column_usage as ccu on
 ccu.constraint_name = tc.constraint_name
 and ccu.table_schema = tc.table_schema
where
 tc.constraint_type = 'FOREIGN KEY'
 and upper(ccu.table_name)= 'ACCESSIBLE_FORM_TABLES'
 and upper(tc.CONSTRAINT_NAME)= :CONSTRAINTNAME
 and upper(tc.constraint_schema)= 'OMS_OWNER'

} 

PRE_DELETE_FROM_FORM_ACCESSIBLE_FORMS {
 DELETE FROM FORM_ACCESSIBLE_FORMS F WHERE F.ORIGINATING_FORM = :OMS_MOD.MODULE_NAME
 }
 OUMFORMS_ACCESSTAB_DELETE_ACCESSIBLE_FORM_TABLES_TWO {
 DELETE FROM ACCESSIBLE_FORM_TABLES A WHERE A.ORIGINATING_FORM = :originatingForm and A.DESTINATION_FORM = :destinationForm and TABLE_NAME=:tableName
}
