
OUMMENUS_FIND_RGMENUSECDESC {
 	SELECT OMS_MOD.MODULE_NAME CODE          ,OMS_MOD.DESCRIPTION DESCRIPTION        ,OMS_MOD.MODULE_TYPE FROM OMS_MODULES OMS_MOD WHERE OMS_MOD.MODULE_TYPE = 'SCREEN' ORDER BY MODULE_NAME
}

OUMMENUS_VMENUSECS_FIND_V_MENU_SECS {
 	SELECT MENU_ID, PARENT_MENU_ID, MENU_ITEM, MODULE_NAME, SORT_ORDER, DESCRIPTION, MODULE_TYPE, APPLN_CODE ,(select count(*) from menu_securities where PARENT_MENU_ID=vm.MENU_ID) as menu_exist_count,DESCRIPTION MODULE_DESCRIPTION
    FROM V_MENU_SECS vm WHERE
}
OUMMENUS_VMENUSECS_INSERT_V_MENU_SECS {
insert into OMS_OWNER.MENU_SECURITIES(MENU_ID, PARENT_MENU_ID, MENU_ITEM, MODULE_NAME, SORT_ORDER, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG, DYNAMIC_FORM) values(NEXTVAL('MENU_ID'), :parentMenuId, :menuItem, :moduleName, :sortOrder, CURRENT_TIMESTAMP, :createUserId, NULL, :sealFlag, :dynamicForm) 
}

OUMMENUS_VMENUSECS_UPDATE_V_MENU_SECS {
	UPDATE OMS_OWNER.MENU_SECURITIES 
    SET  PARENT_MENU_ID=:parentMenuId, MENU_ITEM=:menuItem, MODULE_NAME=:moduleName, SORT_ORDER=:sortOrder,MODIFY_DATETIME=CURRENT_TIMESTAMP, MODIFY_USER_ID=:modifyUserId, SEAL_FLAG=:sealFlag
    WHERE MENU_ID=:menuId
}

OUMMENUS_VMENUSECS_DELETE_V_MENU_SECS { 
	DELETE FROM MENU_SECURITIES WHERE MENU_ID=:menuId
}

OUMMENUS_OMS_MODULES_UPDATE_DESC {
     update OMS_MODULES set DESCRIPTION=:description , MODIFY_DATETIME=CURRENT_TIMESTAMP, MODIFY_USER_ID=:modifyUserId where MODULE_NAME=:moduleName 
   }
OUMMENUS_V_MENU_SECS_PREINSERT_ {
	select NEXTVAL ('MENU_ID')

}

OUMMENUS_PREINSERT_PREUPDATE_PREDELETE_VALID {
	SELECT COUNT(*) FROM V_MENU_SECS where PARENT_MENU_ID = :PARENTMENUID and SORT_ORDER = :SORTORDER
}


OUMMENUS_PREDELETE_CHECKING {
select count(*) from menu_securities where PARENT_MENU_ID=:menuId
}