
OUMPURGE_OFF_FIND_V_HEADER_BLOCK {
SELECT ( SELECT COUNT(OFFENDER_ID) FROM OFFENDER_TRUST_ACCOUNTS WHERE OFFENDER_ID = V_HEADER_BLOCK.OFFENDER_ID AND ACCOUNT_CLOSED_FLAG = 'N') AS TRUST_COUNT, ( SELECT COALESCE(SEAL_FLAG, 'N') FROM OFFENDERS WHERE OFFENDER_ID = V_HEADER_BLOCK.OFFENDER_ID) AS SEAL_FLAG, OFFENDER_ID, ALIAS_OFFENDER_ID, OFFENDER_ID_DISPLAY, LAST_NAME, FIRST_NAME, MIDDLE_NAME, SUFFIX, BIRTH_DATE, OFFENDER_BOOK_ID, BOOKING_NO, BOOKING_BEGIN_DATE, BOOKING_END_DATE, AGY_LOC_ID,
AGENCY_IML_ID, LIVING_UNIT_ID, DISCLOSURE_FLAG, ACTIVE_FLAG, BOOKING_STATUS, LIVING_UNIT_DESCRIPTION, IN_OUT_STATUS, STATUS_DISPLAY, ROOT_OFFENDER_ID, ASSIGNED_STAFF_ID, AGY_LOC_TYPE,
CREATE_AGY_LOC_ID, BOOKING_TYPE, BOOKING_CREATED_DATE, LOCATION_CODE, LIV_UNIT_DESC, INTAKE_AGY_LOC_ID, COMMUNITY_ACTIVE_FLAG, CREATE_INTAKE_AGY_LOC_ID, COMMUNITY_STATUS, STATUS_REASON,
HEADER_STATUS, AGE, GENDER, OFFICER, PRISON_LOCATION, OFF_ALERTS, STATUS_1, STATUS_2, STATUS_3, ETHNICITY, MOVEMENT_REASON, OFF_SUP_LEVEL FROM V_HEADER_BLOCK_FN(:USERID) V_HEADER_BLOCK
}
OUMPURGE_OFF_UPDATE_V_HEADER_BLOCK {
UPDATE V_HEADER_BLOCK set OFFENDER_ID = :offenderId, ALIAS_OFFENDER_ID = :aliasOffenderId, OFFENDER_ID_DISPLAY = :offenderIdDisplay, LAST_NAME = :lastName, FIRST_NAME = :firstName, MIDDLE_NAME = :middleName, SUFFIX = :suffix, BIRTH_DATE = :birthDate, OFFENDER_BOOK_ID = :offenderBookId, BOOKING_NO = :bookingNo, BOOKING_BEGIN_DATE = :bookingBeginDate, BOOKING_END_DATE = :bookingEndDate, AGY_LOC_ID = :agyLocId, AGENCY_IML_ID = :agencyImlId, LIVING_UNIT_ID = :livingUnitId, DISCLOSURE_FLAG = :disclosureFlag, ACTIVE_FLAG = :activeFlag, BOOKING_STATUS = :bookingStatus, LIVING_UNIT_DESCRIPTION = :livingUnitDescription, IN_OUT_STATUS = :inOutStatus, STATUS_DISPLAY = :statusDisplay, ROOT_OFFENDER_ID = :rootOffenderId, ASSIGNED_STAFF_ID = :assignedStaffId, AGY_LOC_TYPE = :agyLocType, CREATE_AGY_LOC_ID = :createAgyLocId, BOOKING_TYPE = :bookingType, BOOKING_CREATED_DATE = :bookingCreatedDate, LOCATION_CODE = :locationCode, LIV_UNIT_DESC = :livUnitDesc, INTAKE_AGY_LOC_ID = :intakeAgyLocId, COMMUNITY_ACTIVE_FLAG = :communityActiveFlag, CREATE_INTAKE_AGY_LOC_ID = :createIntakeAgyLocId, COMMUNITY_STATUS = :communityStatus, STATUS_REASON = :statusReason, HEADER_STATUS = :headerStatus, AGE = :age, GENDER = :gender, OFFICER = :officer, PRISON_LOCATION = :prisonLocation, OFF_ALERTS = :offAlerts, STATUS_1 = :status1, STATUS_2 = :status2, STATUS_3 = :status3, ETHNICITY = :ethnicity, MOVEMENT_REASON = :movementReason, OFF_SUP_LEVEL = :offSupLevel where 
}

OUMPURGE_OFFBKG_FIND_OFFENDER_BOOKINGS {
SELECT OFFENDER_BOOK_ID, BOOKING_BEGIN_DATE, BOOKING_END_DATE, BOOKING_NO, OFFENDER_ID, AGY_LOC_ID, LIVING_UNIT_ID, DISCLOSURE_FLAG, IN_OUT_STATUS, ACTIVE_FLAG, BOOKING_STATUS, YOUTH_ADULT_CODE, FINGER_PRINTED_STAFF_ID, SEARCH_STAFF_ID, PHOTO_TAKING_STAFF_ID, ASSIGNED_STAFF_ID, CREATE_AGY_LOC_ID, BOOKING_TYPE, BOOKING_CREATED_DATE, ROOT_OFFENDER_ID, AGENCY_IML_ID, SERVICE_FEE_FLAG, EARNED_CREDIT_LEVEL, EKSTRAND_CREDIT_LEVEL, INTAKE_AGY_LOC_ID, ACTIVITY_DATE, INTAKE_CASELOAD_ID, INTAKE_USER_ID, CASE_OFFICER_ID, CASE_DATE, CASE_TIME, COMMUNITY_ACTIVE_FLAG, CREATE_INTAKE_AGY_LOC_ID, COMM_STAFF_ID, COMM_STATUS, COMMUNITY_AGY_LOC_ID, NO_COMM_AGY_LOC_ID, COMM_STAFF_ROLE, AGY_LOC_ID_LIST, STATUS_REASON, TOTAL_UNEXCUSED_ABSENCES, REQUEST_NAME, RECORD_USER_ID, INTAKE_AGY_LOC_ASSIGN_DATE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM OFFENDER_BOOKINGS where ROOT_OFFENDER_ID = :rootOffenderId ORDER BY BOOKING_BEGIN_DATE DESC 
}
OUMPURGE_OFFBKG_UPDATE_OFFENDER_BOOKINGS {
update OFFENDER_BOOKINGS set OFFENDER_BOOK_ID = :offenderBookId, BOOKING_BEGIN_DATE = :bookingBeginDate, BOOKING_END_DATE = :bookingEndDate, BOOKING_NO = :bookingNo, OFFENDER_ID = :offenderId, AGY_LOC_ID = :agyLocId, LIVING_UNIT_ID = :livingUnitId, DISCLOSURE_FLAG = :disclosureFlag, IN_OUT_STATUS = :inOutStatus, ACTIVE_FLAG = :activeFlag, BOOKING_STATUS = :bookingStatus, YOUTH_ADULT_CODE = :youthAdultCode, FINGER_PRINTED_STAFF_ID = :fingerPrintedStaffId, SEARCH_STAFF_ID = :searchStaffId, PHOTO_TAKING_STAFF_ID = :photoTakingStaffId, ASSIGNED_STAFF_ID = :assignedStaffId, CREATE_AGY_LOC_ID = :createAgyLocId, BOOKING_TYPE = :bookingType, BOOKING_CREATED_DATE = :bookingCreatedDate, ROOT_OFFENDER_ID = :rootOffenderId, AGENCY_IML_ID = :agencyImlId, SERVICE_FEE_FLAG = :serviceFeeFlag, EARNED_CREDIT_LEVEL = :earnedCreditLevel, EKSTRAND_CREDIT_LEVEL = :ekstrandCreditLevel, INTAKE_AGY_LOC_ID = :intakeAgyLocId, ACTIVITY_DATE = :activityDate, INTAKE_CASELOAD_ID = :intakeCaseloadId, INTAKE_USER_ID = :intakeUserId, CASE_OFFICER_ID = :caseOfficerId, CASE_DATE = :caseDate, CASE_TIME = :caseTime, COMMUNITY_ACTIVE_FLAG = :communityActiveFlag, CREATE_INTAKE_AGY_LOC_ID = :createIntakeAgyLocId, COMM_STAFF_ID = :commStaffId, COMM_STATUS = :commStatus, COMMUNITY_AGY_LOC_ID = :communityAgyLocId, NO_COMM_AGY_LOC_ID = :noCommAgyLocId, COMM_STAFF_ROLE = :commStaffRole, AGY_LOC_ID_LIST = :agyLocIdList, STATUS_REASON = :statusReason, TOTAL_UNEXCUSED_ABSENCES = :totalUnexcusedAbsences, REQUEST_NAME = :requestName, RECORD_USER_ID = :recordUserId, INTAKE_AGY_LOC_ASSIGN_DATE = :intakeAgyLocAssignDate, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID = :modifyUserId, SEAL_FLAG = :sealFlag where OFFENDER_BOOK_ID = :offenderBookId 
}


OUMPURGE_OFF_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM OFFENDER_BOOKINGS O WHERE O.ROOT_OFFENDER_ID = :ROOTOFFENDERID
}

OUMPURGE_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT current_timestamp , upper(user)  FROM DUAL
}

OUMPURGE_CGFKCHK_OFF_CONTACTS_OFF_BKG {
	SELECT DESCRIPTION FROM   REFERENCE_CODES  WHERE CODE = :code AND DOMAIN = 'BOOK_STS'
}
OUMPURGE_LV_COUNT_SEAL_BOOKINGS {
SELECT count(0) FROM offender_bookings WHERE root_offender_id = :lv_root_id AND (coalesce(SEAL_FLAG::text, '') = '' OR SEAL_FLAG ='N') 
}

OUMPURGE_SHOW_CASELOAD_ACCT {
SELECT caseload_id  FROM offender_trust_accounts  WHERE offender_id = :lv_root_off_id  AND account_closed_flag = 'N'
}

OUMPURGE_GET_SEAL_FLAG_CUR {
SELECT COALESCE(SEAL_FLAG,'N')  FROM OFFENDERS WHERE OFFENDER_ID = :lv_root_off_id
}


OUMPURGE_CHECK_ACTIVE_BOOKING {
SELECT COUNT(0) FROM OFFENDER_BOOKINGS OB WHERE OB.ROOT_OFFENDER_ID = :lv_root_off_id AND OB.ACTIVE_FLAG = 'Y' 
}

OUMPURGE_GET_BOOKING_CNT_CUR {
SELECT COUNT(*) FROM offender_bookings WHERE root_offender_id = :lv_root_off_id 
}

OUMPURGE_GET_PROFILE_VALUE{
SELECT OMS_MISCELLANEOUS_GET_PROFILE_VALUE( 'CLIENT', 'CLIENT') PROFILEVALUE FROM DUAL
}
OUMPURGE_GET_BENEFICIARY_ACC_CUR {
SELECT COUNT(*) FROM OFFENDER_BENEFICIARIES OFF_BEN, BENEFICIARY_TRANSACTIONS BEN_TRAN WHERE OFF_BEN.OFFENDER_ID = :P_OFFENDER_ID AND OFF_BEN.OFFENDER_DEDUCTION_ID = BEN_TRAN.OFFENDER_DEDUCTION_ID AND COALESCE(BEN_TRAN.BENEFICIARY_CLEARED_FLAG,'N') = 'N' 
}
OUMPURGE_GET_SUBSTR_VAL {
SELECT SUBSTR(:CASELOADID,2) FROM DUAL
}

OUMPURGE_GET_TRUST_ACCOUNT_CODE {
SELECT COUNT(offender_id) FROM offender_trust_accounts WHERE offender_id = :OFFENDERID AND account_closed_flag = 'N'
}

OUMPURGE_GET_SEALED_FLAG {
SELECT COALESCE(seal_flag,'N') FROM offenders WHERE offender_id = :OFFENDERID
}
OUMPURGE_GET_SUBSTR {
	SELECT substr(:DATA || :STATUSREASON, 1, 240) FROM DUAL
}
OUMPURGE_GET_OLDDATA{
select OFFENDER_BOOK_ID ,BOOKING_BEGIN_DATE ,BOOKING_END_DATE ,BOOKING_NO ,OFFENDER_ID ,AGY_LOC_ID ,LIVING_UNIT_ID ,DISCLOSURE_FLAG ,IN_OUT_STATUS ,ACTIVE_FLAG ,BOOKING_STATUS ,YOUTH_ADULT_CODE ,FINGER_PRINTED_STAFF_ID ,SEARCH_STAFF_ID ,PHOTO_TAKING_STAFF_ID ,ASSIGNED_STAFF_ID ,CREATE_AGY_LOC_ID ,BOOKING_TYPE ,BOOKING_CREATED_DATE ,ROOT_OFFENDER_ID ,AGENCY_IML_ID ,SERVICE_FEE_FLAG ,EARNED_CREDIT_LEVEL ,EKSTRAND_CREDIT_LEVEL ,INTAKE_AGY_LOC_ID ,ACTIVITY_DATE ,INTAKE_CASELOAD_ID ,INTAKE_USER_ID ,CASE_OFFICER_ID ,CASE_DATE ,CASE_TIME ,COMMUNITY_ACTIVE_FLAG ,CREATE_INTAKE_AGY_LOC_ID ,COMM_STAFF_ID ,COMM_STATUS ,COMMUNITY_AGY_LOC_ID ,NO_COMM_AGY_LOC_ID ,COMM_STAFF_ROLE ,AGY_LOC_ID_LIST ,STATUS_REASON ,TOTAL_UNEXCUSED_ABSENCES ,REQUEST_NAME ,RECORD_USER_ID ,INTAKE_AGY_LOC_ASSIGN_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID SEAL_FLAG from offender_bookings where offender_book_id =:offenderBookId
}
OUMPURGE_SEALBUTTON_ACCESS_PERMISSION {
select
	count(*)
from
	staff_member_roles smr
where
	staff_id =(
	select
		staff_id
	from
		staff_members sm
	where
		user_id =:userID) and role_id =:roleIdVal
}
OUMPURGE_SYSPFL_FIND_SYSTEM_PROFILES {
 SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,PROFILE_VALUE ,PROFILE_VALUE_2 ,MODIFY_USER_ID ,OLD_TABLE_NAME ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM SYSTEM_PROFILES   where PROFILE_TYPE = :profileType and PROFILE_CODE = :profileCode  
}

OUMPURGE_GET_LV_SEAL_BOOKING_COUNT {
SELECT count(*) FROM   offender_bookings WHERE  root_offender_id::text = :rootOffenderId::text AND    (SEAL_FLAG IS NULL OR SEAL_FLAG ='N')
}