
OUMSMUGA_FIND_CGFKSTAFFROLEDSPUSERID {
 	SELECT STAFF.USER_ID  CODE, STAFF.USER_ID DESCRIPTION, STAFF.LAST_NAME  LAST_NAME ,STAFF.FIRST_NAME  FIRST_NAME ,STAFF.MIDDLE_NAME  MIDDLE_NAME ,STAFF.STAFF_ID  STAFF_ID FROM   STAFF_MEMBERS STAFF WHERE   USER_ID IS NOT NULL AND TERMINATION_DATE IS NULL ORDER BY  STAFF.USER_ID
}

OUMSMUGA_OMSROLE_FIND_OMS_ROLES {
 	SELECT ROLE_NAME, ROLE_ID, ROLE_CODE, ROLE_SEQ FROM OMS_ROLES  ORDER BY ROLE_SEQ
}
OUMSMUGA_STAFFROLE_FIND_STAFF_MEMBER_ROLES {
 	 	SELECT STAFF_ID, ROLE_ID, ROLE_CODE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG, to_char(ROW_ID) ROW_ID  FROM staff_member_roles where exists (SELECT NULL FROM staff_members WHERE staff_members.staff_id = staff_member_roles.staff_id AND termination_date IS NULL) and role_id = :roleId
}
OUMSMUGA_STAFFROLE_INSERT_STAFF_MEMBER_ROLES {
	INSERT INTO STAFF_MEMBER_ROLES(STAFF_ID, ROLE_ID, ROLE_CODE, SEAL_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME) VALUES(:staffId, :roleId, :roleCode, :sealFlag,current_timestamp,:createUserId,null )
}

OUMSMUGA_STAFFROLE_UPDATE_STAFF_MEMBER_ROLES {
	UPDATE STAFF_MEMBER_ROLES set STAFF_ID = :staffId , MODIFY_DATETIME =current_timestamp , MODIFY_USER_ID =:modifyUserId  where ROLE_ID = :roleId AND ROW_ID = cast(:rowId as integer)   
}

OUMSMUGA_STAFFROLE_DELETE_STAFF_MEMBER_ROLES { 
	DELETE FROM STAFF_MEMBER_ROLES where STAFF_ID = :staffId AND ROLE_ID = :roleId
}


OUMSMUGA_CGFKCHK_STAFF_ROLE_STAFF_ROLE_ {
	SELECT STAFF.USER_ID ,STAFF.LAST_NAME ,STAFF.FIRST_NAME ,STAFF.MIDDLE_NAME FROM   STAFF_MEMBERS STAFF WHERE  STAFF.STAFF_ID = :STAFFID AND    USER_ID IS NOT NULL AND TERMINATION_DATE IS NULL
}

OUMSMUGA_CGFKLKP_STAFF_ROLE_STAFF_ROLE_ {
	SELECT STAFF.STAFF_ID ,STAFF.LAST_NAME ,STAFF.FIRST_NAME ,STAFF.MIDDLE_NAME FROM   STAFF_MEMBERS STAFF WHERE  STAFF.USER_ID = :DSPUSERID AND     USER_ID IS NOT NULL AND TERMINATION_DATE IS NULL
}

OUMSMUGA_CGUVCHK_STAFF_MEMBER_ROLES_PK_ {
	SELECT  '1' FROM    STAFF_MEMBER_ROLES WHERE   ROLE_ID = :P_ROLE_ID AND     STAFF_ID = :P_STAFF_ID
}

OUMSMUGA_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  current_timestamp , upper(user) FROM DUAL
}

OUMSMUGA_GET_STAFF_USER_ID {
	SELECT USER_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME FROM STAFF_MEMBERS where STAFF_ID = :staffId
}

OUMSMUGA_GET_STAFF_ID{

select
	STAFF.STAFF_ID 
	
from
	STAFF_MEMBERS STAFF
where
	STAFF.USER_ID = :DSPUSERID
	}
	


