
OYMHOLID_FIND_CGFKCSLDGHCCOMPENSATIONCOD {
 	SELECT REF_CODE.CODE CODE, REF_CODE.DESCRIPTION  DESCRIPTION, REF_CODE.LIST_SEQ  LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  DOMAIN = 'COMPENSATION' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.LIST_SEQ, REF_CODE.DESCRIPTION
}

OYMHOLID_FIND_CGFKCSLDGHCWORKGROUPID {
 	SELECT CSLD_WRKG.WORK_GROUP_ID CODE, CSLD_WRKG.DESCRIPTION DESCRIPTION, CSLD_WRKG.LIST_SEQ LIST_SEQ, CSLD_WRKG.CASELOAD_ID CASELOAD_ID FROM CASELOAD_WORK_GROUPS CSLD_WRKG WHERE CASELOAD_ID = :caseloadId AND ACTIVE_FLAG='Y' AND EXPIRY_DATE IS NULL
}

OYMHOLID_SYSEVENT_FIND_SYSTEM_EVENTS {
 	SELECT EVENT_TYPE, EVENT_SEQ, DESCRIPTION, EVENT_DATE, MODIFY_DATE, EVENT_END_DATE, SYSTEM_EVENT_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG, MODIFY_USER_ID  from SYSTEM_EVENTS where EVENT_TYPE='HOL'
}
OYMHOLID_SYSEVENT_INSERT_SYSTEM_EVENTS {
     insert into SYSTEM_EVENTS(EVENT_TYPE, EVENT_SEQ, DESCRIPTION, EVENT_DATE, MODIFY_DATE, EVENT_END_DATE, SYSTEM_EVENT_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME,MODIFY_USER_ID ) values(:eventType, :eventSeq, :description, :eventDate, :modifyDate, :eventEndDate, :systemEventId, CURRENT_TIMESTAMP, :createUserId, NULL,NULL ) 
}

OYMHOLID_SYSEVENT_UPDATE_SYSTEM_EVENTS {
	UPDATE SYSTEM_EVENTS set EVENT_TYPE = :eventType, EVENT_SEQ = :eventSeq, DESCRIPTION  = :description, EVENT_DATE = :eventDate, MODIFY_DATE = :modifyDate, EVENT_END_DATE = :eventEndDate, SYSTEM_EVENT_ID = :systemEventId, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID = :modifyUserId where SYSTEM_EVENT_ID = :systemEventId 
}

OYMHOLID_SYSEVENT_DELETE_SYSTEM_EVENTS { 
	DELETE FROM SYSTEM_EVENTS where SYSTEM_EVENT_ID = :systemEventId
}

OYMHOLID_CSLDGHC_FIND_CASELOAD_GRP_HOL_COMPENS {
select
CASELOAD_ID,
COMPENSATION_CODE,
CREATE_DATETIME,
CREATE_USER_ID,
HOLIDAY_EVENT_ID,
MODIFY_DATETIME,
MODIFY_USER_ID,
SEAL_FLAG,
WORK_GROUP_ID,
ROW_ID
from
CASELOAD_GRP_HOL_COMPENS
where
CASELOAD_ID = :caseloadId
and HOLIDAY_EVENT_ID = :holidayEventId
order by row_id

}
OYMHOLID_CSLDGHC_INSERT_CASELOAD_GRP_HOL_COMPENS {
    insert into CASELOAD_GRP_HOL_COMPENS(CASELOAD_ID, COMPENSATION_CODE, HOLIDAY_EVENT_ID, WORK_GROUP_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME) values(:caseloadId, :compensationCode, :holidayEventId, :workGroupId, CURRENT_TIMESTAMP, :createUserId, NULL) 
}

OYMHOLID_CSLDGHC_UPDATE_CASELOAD_GRP_HOL_COMPENS {
	update CASELOAD_GRP_HOL_COMPENS set CASELOAD_ID = :caseloadId, COMPENSATION_CODE = :compensationCode, HOLIDAY_EVENT_ID = :holidayEventId, WORK_GROUP_ID = :workGroupId, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID = :modifyUserId where HOLIDAY_EVENT_ID = :holidayEventId and ROW_ID = :rowId
}

OYMHOLID_CSLDGHC_DELETE_CASELOAD_GRP_HOL_COMPENS { 
	DELETE FROM CASELOAD_GRP_HOL_COMPENS where HOLIDAY_EVENT_ID = :holidayEventId AND WORK_GROUP_ID = :workGroupId
}


OYMHOLID_SYS_EVENT_PREINSERT {
SELECT coalesce (MAX(SYSTEM_EVENT_ID), 0) + 1 FROM System_Events
}

OYMHOLID_SYS_EVENT_EVENT_SEQ {
SELECT coalesce(max(EVENT_SEQ),0) + 1  FROM SYSTEM_EVENTS
}

OYMHOLID_SYS_EVENT_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM CASELOAD_GRP_HOL_COMPENS C WHERE C.HOLIDAY_EVENT_ID = :SYSTEMEVENTID
}

OYMHOLID_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT current_timestamp, 'OMS_OWNER'
}

OYMHOLID_CGFKCHK_CSLD_GHC_CSLD_GHC_REF_ {
	SELECT REF_CODE.DESCRIPTION ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :COMPENSATIONCODE AND     DOMAIN = 'COMPENSATION' AND ACTIVE_FLAG='Y' AND EXPIRED_DATE IS NULL
}

OYMHOLID_CGFKCHK_CSLD_GHC_CSLD_GHC_CSL_ {
	SELECT CSLD_WRKG.DESCRIPTION ,CSLD_WRKG.LIST_SEQ ,CSLD_WRKG.CASELOAD_ID FROM   CASELOAD_WORK_GROUPS CSLD_WRKG WHERE  CSLD_WRKG.WORK_GROUP_ID = :WORKGROUPID
}






