
OCUAUTHR_FIND_RGSTAFFNAME {
SELECT
    sm.last_name,
    sm.first_name,
    sm.staff_id
FROM
    staff_members sm
WHERE
    staff_id IN (
        SELECT
            tm.staff_id
        FROM
            team_members tm
        WHERE
            tm.team_id = :team_id
    )
    AND  sm.status = 'ACTIVE'
         
ORDER BY
    sm.last_name ASC
 	              
}

OCUAUTHR_TSKASSHTY_FIND_TASK_ASSIGNMENT_HTY {
 	SELECT TASK_ASSIGNMENT_HTY_ID, TASK_ASSIGNMENT_ID, OFFENDER_BOOK_ID, WORK_ID, ASSIGNMENT_DATE, 
ASSIGNMENT_STATUS, TEAM_ID, STAFF_ID, TEAM_MEMBER_ID, DUE_DATE, DETAILS, COMPLETION_DATE, COMPLETE_REASON_CODE, 
COMPLETE_COMMENT_TEXT, COMPLETE_USER_ID, MESSAGE_ID, ORIGINAL_MESSAGE_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, 
TRIGGER_NAME, WORKFLOW_HISTORY_ID, EVENT_DATE, FUNCTION_TYPE, SEAL_FLAG FROM TASK_ASSIGNMENT_HTY  where WORKFLOW_HISTORY_ID=:WORKFLOW_HISTORY_ID order by TASK_ASSIGNMENT_HTY_ID desc
}

OCUAUTHR_TSKASSHTY_FIND_TASK_ASSIGNMENT_HTY_EMPTY {
 	SELECT TASK_ASSIGNMENT_HTY_ID, TASK_ASSIGNMENT_ID, OFFENDER_BOOK_ID, WORK_ID, ASSIGNMENT_DATE, 
ASSIGNMENT_STATUS, TEAM_ID, STAFF_ID, TEAM_MEMBER_ID, DUE_DATE, DETAILS, COMPLETION_DATE, COMPLETE_REASON_CODE, 
COMPLETE_COMMENT_TEXT, COMPLETE_USER_ID, MESSAGE_ID, ORIGINAL_MESSAGE_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, 
TRIGGER_NAME, WORKFLOW_HISTORY_ID, EVENT_DATE, FUNCTION_TYPE, SEAL_FLAG FROM TASK_ASSIGNMENT_HTY   order by TASK_ASSIGNMENT_HTY_ID desc
}

OCUAUTHR_TSKASSHTY_FIND_TEAM_DESC_POST_QUERY{
--Below code is modified for jira issues
SELECT TEAM_CODE, DESCRIPTION FROM TEAMS WHERE TEAM_ID = :TEAM_ID
--SELECT TEAM_CODE, DESCRIPTION FROM automation_teams WHERE TEAM_ID = :TEAM_ID

}

OCUAUTHR_TSKASSHTY_FIND_STAFF_NAME_POST_QUERY{
	 SELECT LAST_NAME, FIRST_NAME
             FROM STAFF_MEMBERS
            WHERE STAFF_ID = :STAFF_ID

}


