
OCUWARNI_FIND_RGCONSUBTYPE {
 	SELECT DESCRIPTION , CODE     FROM REFERENCE_CODES    WHERE DOMAIN = 'TASK_SUBTYPE'       AND PARENT_CODE = 'EN'       AND ((ACTIVE_FLAG = 'Y' ) OR ('' = 'ENTER-QUERY' ) ) ORDER BY  LIST_SEQ , DESCRIPTION , CODE ASC
}

OCUWARNI_FIND_RGSTAFFNAME {
select
	distinct A.STAFF_NAME DESCRIPTION ,
	A.SAC_STAFF_ID CODE
from
	V_STAFF_LOCATION_ROLES A ,
	OFFENDER_BOOKINGS B
where
	( B.OFFENDER_BOOK_ID = :OFFENDERBOOKID
		and ( '' = 'ENTER-QUERY'
			and exists (
			select
				'X'
			from
				CASELOAD_AGENCY_LOCATIONS
			where
				AGY_LOC_ID = A.CAL_AGY_LOC_ID
				and CASELOAD_ID = :CASELOADID ) )
		or ( B.ACTIVE_FLAG = 'Y'
			and A.CAL_AGY_LOC_ID = B.AGY_LOC_ID
			and B.AGY_LOC_ID = :PAGYLOCID )
		or ( B.COMMUNITY_ACTIVE_FLAG = 'Y'
			and B.COMMUNITY_AGY_LOC_ID = A.CAL_AGY_LOC_ID )
		or ( COALESCE  (B.ACTIVE_FLAG ,
		'N' ) = 'N'
			and COALESCE  (B.COMMUNITY_ACTIVE_FLAG ,
			'N' ) = 'N'
				and exists (
				select
					'X'
				from
					CASELOAD_AGENCY_LOCATIONS
				where
					AGY_LOC_ID = A.CAL_AGY_LOC_ID
					and CASELOAD_ID = :CASELOADID ) ) )
order by
	A.STAFF_NAME ,
	A.SAC_STAFF_ID
}

OCUWARNI_OFFCASENOTES_FIND_OFFENDER_CASE_NOTES {
 	SELECT OFFENDER_BOOK_ID,CONTACT_DATE,CONTACT_TIME,CASE_NOTE_TYPE,CASE_NOTE_SUB_TYPE,STAFF_ID,CASE_NOTE_TEXT,AMENDMENT_FLAG,IWP_FLAG, CHECK_BOX1, CHECK_BOX2, CHECK_BOX3, CHECK_BOX4, CHECK_BOX5, EVENT_ID ,CASE_NOTE_ID,NOTE_SOURCE_CODE, DATE_CREATION, TIME_CREATION,SEAL_FLAG,  OBJECT_TYPE,OBJECT_ID,   CREATE_DATETIME ,CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID  FROM OFFENDER_CASE_NOTES   WHERE  OFFENDER_BOOK_ID =:offenderBookId AND CASE_NOTE_TYPE='SEC' ORDER BY CONTACT_DATE DESC
}
