insert
	into
	STAFF_MEMBERS(STAFF_ID ,
	ASSIGNED_CASELOAD_ID ,
	WORKING_CASELOAD_ID ,
	USER_ID ,
	LAST_NAME ,
	FIRST_NAME ,
	UPDATE_ALLOWED_FLAG ,
	SUSPENDED_FLAG ,
	PERSONNEL_TYPE ,
	AS_OF_DATE ,
	STATUS ,
	CREATE_DATETIME ,
	CREATE_USER_ID ,
	MODIFY_DATETIME ,
	QUEUE_CLUSTER_ID,
	MAIL_ID )
SELECT (select max(STAFF_ID)+1 from staff_members),
(select caseload_id from caseloads where caseload_type = 'INST' order by caseload_id limit 1),
(select caseload_id from caseloads where caseload_type = 'INST' order by caseload_id limit 1),
'SYSTEM',
'SYSTEM',
'SYSTEM',
'N' ,
'N' ,
'VA' ,
current_timestamp ,
'OMS_OWNER' ,
current_timestamp ,
'OMS_OWNER' ,
null ,
null,
null 
 WHERE NOT EXISTS (SELECT 1 FROM staff_members WHERE user_id = 'SYSTEM');