insert into oms_owner.STAFF_MEMBER_ROLES(STAFF_ID ,ROLE_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME, MODIFY_USER_ID ,ROLE_CODE ) 
 SELECT (select STAFF_ID from STAFF_MEMBERS where USER_ID = 'SYSTEM'),
         (select ROLE_ID from OMS_ROLES where ROLE_NAME = 'All Forms'), CURRENT_TIMESTAMP , 'OMS_OWNER' ,CURRENT_TIMESTAMP , 'OMS_OWNER' , 'ALL_FORMS' 
  WHERE NOT EXISTS (SELECT 1 FROM STAFF_MEMBER_ROLES WHERE staff_id = (select STAFF_ID from STAFF_MEMBERS where USER_ID = 'SYSTEM')); 
  
		 