update json_spec 
  set modify_datetime = current_timestamp
   ,modify_user_id = 'OMS_OWNER'
   ,json_specs = '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "user_id": "header.intUser.intUserId", "first_name": "header.intUser.intUserName", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "offender_id_display": "body.prisonerDetails[#2].imprisonmentDetails.pin" } }, "offenderBookingDetails": { "*": { "booking_no": "body.prisonerDetails[#2].imprisonmentDetails.offenderNumber", "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.prisonerDetails[#2].housing.pod", "housing_lev_2_code": "body.prisonerDetails[#2].housing.unit", "housing_lev_3_code": "body.prisonerDetails[#2].housing.cell" } } } }, { "operation": "modify-default-beta", "spec": { "body": { "prisonerDetails": { "*": { "housing": { "regime": " " }, "financials": { "transactionSpendLimit": " " } } } } } }, { "operation": "default", "spec": { "header": { "intId": "Unilink-LOCA", "intRecSource": "TBD", "intRecAction": "", "intCorrelId": "TBD" } } } ] ' where spec_key = 'PRISONER_MOVEMENTS_FORMATTER';


update json_spec 
  set modify_datetime = current_timestamp
   ,modify_user_id = 'OMS_OWNER'
   ,json_specs = '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "first_name": "body.prisonerDetails[#2].demographics.firstName", "last_name": "body.prisonerDetails[#2].demographics.surName", "sex_code": "body.prisonerDetails[#2].demographics.gender", "birth_date": "body.prisonerDetails[#2].demographics.dob", "offender_id_display": "body.prisonerDetails[#2].imprisonmentDetails.dcsId" } }, "offenderBookingDetails": { "*": { "booking_no": "body.prisonerDetails[#2].imprisonmentDetails.imprisonmentId", "booking_begin_date": "body.prisonerDetails[#2].imprisonmentDetails.intakeDate", "booking_status": "body.prisonerDetails[#2].imprisonmentDetails.imprisonmentStatus", "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } }, "offenderHousingDetails": { "*": { "housing_lev_1_code": "body.prisonerDetails[#2].housing.pod", "housing_lev_2_code": "body.prisonerDetails[#2].housing.unit", "housing_lev_3_code": "body.prisonerDetails[#2].housing.cell" } }, "warnings": { "*": { "description": "body.prisonerDetails[#4].alerts[#2].alertCode", "createdate": "body.prisonerDetails[#4].alerts[#2].alertStartDate", "expirydate": "body.prisonerDetails[#4].alerts[#2].alertEndDate", "comment_text": "body.prisonerDetails[#4].alerts[#2].alertComment" } }, "offenderFinancialDetails": { "*": { "current_balance": "body.prisonerDetails[#2].financials.accountBalance", "balance": "body.prisonerDetails[#2].financials.resettlementAccountBalance" } } } }, { "operation": "modify-default-beta", "spec": { "body": { "prisonerDetails": { "*": { "housing": { "regime": " " }, "financials": { "transactionSpendLimit": " " }, "imprisonmentDetails": { "releaseDateTime": "", "releaseReason": "" } } } } } }, { "operation": "default", "spec": { "header": { "intId": "UnilinkWARN" } } } ] ' where spec_key = 'TRANSFORM_WARNING';

update json_spec 
   set modify_datetime = current_timestamp
   ,modify_user_id = 'OMS_OWNER',
   json_specs = '[ { "operation": "shift", "spec": { "staffDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "offenderDetails": { "*": { "first_name": "body.prisonerDetails[#2].demographics.firstName", "last_name": "body.prisonerDetails[#2].demographics.surName" } }, "offenderBookingDetails": { "*": { "booking_no": "body.prisonerDetails[#2].imprisonmentDetails.offenderNumber", "agy_loc_id": "body.prisonerDetails[#2].housing.facility" } }, "computerAccessFlag": { "*": { "coalesce": "body.prisonerDetails[#2].computerAccess" } } } }, { "operation": "default", "spec": { "header": { "intId": "LearningSystem" } } } ] ' where spec_key = 'LEARNING_SYSTEM_FORMATTER';

update json_spec 
   set modify_datetime = current_timestamp
   ,modify_user_id = 'OMS_OWNER'
   ,json_specs = '[ { "operation": "shift", "spec": { "userDetails": { "*": { "first_name": "header.intUser.intUserName", "user_id": "header.intUser.intUserId", "date_time": "header.intDatetime" } }, "identifierDetails": { "*": { "identifier": "body.personDetails.imprisonmentDetails.pin" } }, "correlationId": "header.intCorrelationId", "nameDetails": { "*": { "first_name": "body.personDetails.demographics.firstName", "last_name": "body.personDetails.demographics.surName", "sex_code": "body.personDetails.demographics.gender", "birth_date": "body.personDetails.demographics.dob" } }, "aliasDetails": { "*": { "familyname": "body.personDetails.alias[#2].firstName", "eliteoffenderid": "body.personDetails.alias[#2].offenderId", "givenname": "body.personDetails.alias[#2].lastname", "dateofbirth": "body.personDetails.alias[#2].dob" } }, "warningDetails": { "*": { "description": "body.personDetails.alerts[#2].alertCode", "alert_type": "body.personDetails.alerts[#2].alertType", "createdate": "body.personDetails.alerts[#2].alertStartDate", "expirydate": "body.personDetails.alerts[#2].alertEndDate", "comment_text": "body.personDetails.alerts[#2].alertComment" } }, "residenceDetails": { "*": { "streetnumber": "body.personDetails.address.road.roadNumber", "streetname": "body.personDetails.address.road.roadName", "city": "body.personDetails.address.localityName", "state": "body.personDetails.address.stateOrTerritoryCode", "country": "body.personDetails.address.countryName", "postal": "body.personDetails.address.postCode", "address": "body.personDetails.address.unstructuredAddressLine", "recordeddate": "body.personDetails.address.recordedDate" } }, "occupation": { "*": { "employment_type": "body.personDetails.demographics.occupation" } } } }, { "operation": "default", "spec": { "header": { "intId": "OffenderDetail" } } } ] ' where spec_key = 'TRANSFORM_EXTERNAL';


update json_spec 
  set modify_datetime = current_timestamp
   ,modify_user_id = 'OMS_OWNER'
   ,json_specs = '[{"operation":"shift","spec":{"ProcessInput":{"header":{"intCorrelationId":"correlationId"},"body":{"prisonerDetails":{"imprisonmentDetails":{"pin":"offenderBookId"},"informationDirective":"RequestType"}}}}}]' where spec_key = 'TRANSFORM_SERVICE';
   
   
---S4-21081 in S4-18183

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.prisonerDetails[#2].imprisonmentDetails.offenderNumber","first_name":"body.prisonerDetails[#2].demographics.firstName","last_name":"body.prisonerDetails[#2].demographics.surName"}},"offenderBookingDetails":{"*":{"agy_loc_id":"body.prisonerDetails[#2].housing.facility"}},"computerAccessFlag":{"*":{"coalesce":"body.prisonerDetails[#2].computerAccess"}}}},{"operation":"default","spec":{"header":{"intId":"LearningSystem"}}}]' 
 where spec_key = 'LEARNING_SYSTEM_FORMATTER';

---S4-21112 in S4-18175

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"first_name":"body.prisonerDetails[#2].demographics.firstName","last_name":"body.prisonerDetails[#2].demographics.surName","sex_code":"body.prisonerDetails[#2].demographics.gender","birth_date":"body.prisonerDetails[#2].demographics.dob","offender_id_display":"body.prisonerDetails[#2].imprisonmentDetails.dcsId"}},"offenderBookingDetails":{"*":{"booking_no":"body.prisonerDetails[#2].imprisonmentDetails.imprisonmentId","booking_begin_date":"body.prisonerDetails[#2].imprisonmentDetails.intakeDate","booking_status":"body.prisonerDetails[#2].imprisonmentDetails.imprisonmentStatus","agy_loc_id":"body.prisonerDetails[#2].housing.facility"}},"offenderHousingDetails":{"*":{"housing_lev_1_code":"body.prisonerDetails[#2].housing.pod","housing_lev_2_code":"body.prisonerDetails[#2].housing.unit","housing_lev_3_code":"body.prisonerDetails[#2].housing.cell"}},"warnings":{"*":{"code":"body.prisonerDetails[#4].alerts[#2].alertCode","createdate":"body.prisonerDetails[#4].alerts[#2].alertStartDate","expirydate":"body.prisonerDetails[#4].alerts[#2].alertEndDate","comment_text":"body.prisonerDetails[#4].alerts[#2].alertComment"}},"offenderFinancialDetails":{"*":{"current_balance":"body.prisonerDetails[#2].financials.accountBalance","balance":"body.prisonerDetails[#2].financials.resettlementAccountBalance"}}}},{"operation":"modify-default-beta","spec":{"body":{"prisonerDetails":{"*":{"housing":{"regime":" "},"financials":{"transactionSpendLimit":" "},"imprisonmentDetails":{"releaseDateTime":"","releaseReason":""}}}}}},{"operation":"default","spec":{"header":{"intId":"UnilinkWARN"}}}]' 
   where spec_key = 'TRANSFORM_WARNING';

---S4-21179, S4-21180 in S4-18179

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"userDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"correlationId":"header.intCorrelationId","nameDetails":{"*":{"offender_id_display":"body.personDetails.imprisonmentDetails.pin","first_name":"body.personDetails.demographics.firstName","last_name":"body.personDetails.demographics.surName","sex_code":"body.personDetails.demographics.gender","birth_date":"body.personDetails.demographics.dob"}},"aliasDetails":{"*":{"givenname":"body.personDetails.alias[#2].firstName","eliteoffenderid":"body.personDetails.alias[#2].offenderId","familyname":"body.personDetails.alias[#2].lastname","dateofbirth":"body.personDetails.alias[#2].dob"}},"warningDetails":{"*":{"description":"body.personDetails.alerts[#2].alertCode","alert_type":"body.personDetails.alerts[#2].alertType","createdate":"body.personDetails.alerts[#2].alertStartDate","expirydate":"body.personDetails.alerts[#2].alertEndDate","comment_text":"body.personDetails.alerts[#2].alertComment"}},"residenceDetails":{"*":{"streetnumber":"body.personDetails.address.road.roadNumber","streetname":"body.personDetails.address.road.roadName","city":"body.personDetails.address.localityName","state":"body.personDetails.address.stateOrTerritoryCode","country":"body.personDetails.address.countryName","postal":"body.personDetails.address.postCode","address":"body.personDetails.address.unstructuredAddressLine","recordeddate":"body.personDetails.address.recordedDate"}},"occupation":{"*":{"occupation":"body.personDetails.demographics.occupation"}}}},{"operation":"default","spec":{"header":{"intId":"SAPOLOffenderDetail"}}}]' 
 where spec_key = 'TRANSFORM_EXTERNAL';

---S4-21233, S4-21251 in S4-18179

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"userDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}}}},{"operation":"default","spec":{"header":{"intId":"SAPOLOffenderDetail"},"body":{"Error":"The prisioner does not Exist in Elite"}}}]' 
 where spec_key = 'TRANSFORM_ERROR';

---S4-21064 in S4-18176

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.activePrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.activePrisonerDetails[#2].demographics.firstName","middle_name":"body.activePrisonerDetails[#2].demographics.middleName","last_name":"body.activePrisonerDetails[#2].demographics.surName","sex_code":"body.activePrisonerDetails[#2].demographics.gender","birth_date":"body.activePrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_no":"body.activePrisonerDetails[#2].imprisonmentDetails.pin","booking_begin_date":"body.activePrisonerDetails[#2].imprisonmentDetails.intakeDatetime","booking_status":"body.activePrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus","agy_loc_id":"body.activePrisonerDetails[#2].housing.facility"}},"offenderHousingDetails":{"*":{"housing_lev_1_code":"body.activePrisonerDetails[#2].housing.unit"}},"offenderReleaseDetails":{"*":{"release_date":"body.activePrisonerDetails[#2].imprisonmentDetails.releaseDateTime"}}}},{"operation":"default","spec":{"header":{"intId":"CurrentPrisoners"}}}]' 
 where spec_key = 'ACTIVE_PRISONER_FORMATTER';

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.releasedPrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.releasedPrisonerDetails[#2].demographics.firstName","middle_name":"body.releasedPrisonerDetails[#2].demographics.middleName","last_name":"body.releasedPrisonerDetails[#2].demographics.surName","sex_code":"body.releasedPrisonerDetails[#2].demographics.gender","birth_date":"body.releasedPrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_no":"body.releasedPrisonerDetails[#2].imprisonmentDetails.pin","booking_begin_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime","booking_status":"body.releasedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus","agy_loc_id":"body.releasedPrisonerDetails[#2].housing.facility"}},"offenderHousingDetails":{"*":{"housing_lev_1_code":"body.releasedPrisonerDetails[#2].housing.unit"}},"offenderReleaseDetails":{"*":{"release_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime"}}}},{"operation":"default","spec":{"header":{"intId":"CurrentPrisoners"}}}]' 
 where spec_key = 'RELEASED_PRISONER_FORMATTER';

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.escapedPrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.escapedPrisonerDetails[#2].demographics.firstName","middle_name":"body.escapedPrisonerDetails[#2].demographics.middleName","last_name":"body.escapedPrisonerDetails[#2].demographics.surName","sex_code":"body.escapedPrisonerDetails[#2].demographics.gender","birth_date":"body.escapedPrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_no":"body.escapedPrisonerDetails[#2].imprisonmentDetails.pin","booking_begin_date":"body.escapedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime","booking_status":"body.escapedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus","agy_loc_id":"body.escapedPrisonerDetails[#2].housing.facility"}},"offenderHousingDetails":{"*":{"housing_lev_1_code":"body.escapedPrisonerDetails[#2].housing.unit"}},"offenderReleaseDetails":{"*":{"release_date":"body.escapedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime"}}}},{"operation":"default","spec":{"header":{"intId":"CurrentPrisoners"}}}]' 
 where spec_key = 'ESCAPED_PRISONER_FORMATTER';
 
 
 update json_spec 
    set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"userDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"correlationId":"header.intCorrelationId","nameDetails":{"*":{"offender_id_display":"body.personDetails.imprisonmentDetails.pin","first_name":"body.personDetails.demographics.firstName","last_name":"body.personDetails.demographics.surName","sex_code":"body.personDetails.demographics.gender","birth_date":"body.personDetails.demographics.dob"}},"aliasDetails":{"*":{"givenname":"body.personDetails.alias[#2].firstName","eliteoffenderid":"body.personDetails.alias[#2].offenderId","familyname":"body.personDetails.alias[#2].lastname","dateofbirth":"body.personDetails.alias[#2].dob"}},"warningDetails":{"*":{"code":"body.personDetails.alerts[#2].alertCode","alert_type":"body.personDetails.alerts[#2].alertType","createdate":"body.personDetails.alerts[#2].alertStartDate","expirydate":"body.personDetails.alerts[#2].alertEndDate","comment_text":"body.personDetails.alerts[#2].alertComment"}},"residenceDetails":{"*":{"streetnumber":"body.personDetails.address.road.roadNumber","streetname":"body.personDetails.address.road.roadName","city":"body.personDetails.address.localityName","state":"body.personDetails.address.stateOrTerritoryCode","country":"body.personDetails.address.countryName","postal":"body.personDetails.address.postCode","address":"body.personDetails.address.unstructuredAddressLine","recordeddate":"body.personDetails.address.recordedDate"}},"occupation":{"*":{"occupation":"body.personDetails.demographics.occupation"}}}},{"operation":"default","spec":{"header":{"intId":"SAPOLOffenderDetail"}}}]' 
  where spec_key = 'TRANSFORM_EXTERNAL';

update json_spec 
    set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"activePrisoners":{"header":{"*":"header.&"},"body":{"activePrisonerDetails":{"*":"body.activePrisonerDetails[]"}}},"releasePrisoners":{"body":{"releasedPrisonerDetails":{"*":"body.releasedPrisonerDetails[]"}}},"escapePrisoners":{"body":{"escapedPrisonerDetails":{"*":"body.escapedPrisonerDetails[]"}}}}}]' 
  where spec_key = 'CURRENT_PRISONER_FORMATTER';

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.activePrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.activePrisonerDetails[#2].demographics.firstName","middle_name":"body.activePrisonerDetails[#2].demographics.middleName","last_name":"body.activePrisonerDetails[#2].demographics.surName","sex_code":"body.activePrisonerDetails[#2].demographics.gender","birth_date":"body.activePrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_no":"body.activePrisonerDetails[#2].imprisonmentDetails.pin","booking_begin_date":"body.activePrisonerDetails[#2].imprisonmentDetails.intakeDatetime","booking_status":"body.activePrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus"}},"offenderHousingDetails":{"*":{"agy_loc_id":"body.activePrisonerDetails[#2].housing.facility","housing_lev_1_code":"body.activePrisonerDetails[#2].housing.unit","assignment_time":"body.activePrisonerDetails[#2].housing.assignDate","assignment_end_time":"body.activePrisonerDetails[#2].housing.endDate"}},"offenderReleaseDetails":{"*":{"release_date":"body.activePrisonerDetails[#2].imprisonmentDetails.releaseDateTime"}}}},{"operation":"default","spec":{"header":{"intId":"CurrentPrisoners"}}}]' 
 where spec_key = 'ACTIVE_PRISONER_FORMATTER';

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.releasedPrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.releasedPrisonerDetails[#2].demographics.firstName","middle_name":"body.releasedPrisonerDetails[#2].demographics.middleName","last_name":"body.releasedPrisonerDetails[#2].demographics.surName","sex_code":"body.releasedPrisonerDetails[#2].demographics.gender","birth_date":"body.releasedPrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_no":"body.releasedPrisonerDetails[#2].imprisonmentDetails.pin","booking_begin_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime","booking_status":"body.releasedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus"}},"offenderHousingDetails":{"*":{"agy_loc_id":"body.releasedPrisonerDetails[#2].housing.facility","housing_lev_1_code":"body.releasedPrisonerDetails[#2].housing.unit","assignment_time":"body.releasedPrisonerDetails[#2].housing.assignDate","assignment_end_time":"body.releasedPrisonerDetails[#2].housing.endDate"}},"offenderReleaseDetails":{"*":{"release_date":"body.releasedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime"}}}},{"operation":"default","spec":{"header":{"intId":"CurrentPrisoners"}}}]' 
 where spec_key = 'RELEASED_PRISONER_FORMATTER';

update json_spec 
   set modify_datetime = current_timestamp
      ,modify_user_id = 'OMS_OWNER'
      ,json_specs = '[{"operation":"shift","spec":{"staffDetails":{"*":{"first_name":"header.intUser.intUserName","user_id":"header.intUser.intUserId","date_time":"header.intDatetime"}},"offenderDetails":{"*":{"offender_id_display":"body.escapedPrisonerDetails[#2].imprisonmentDetails.dcsId","first_name":"body.escapedPrisonerDetails[#2].demographics.firstName","middle_name":"body.escapedPrisonerDetails[#2].demographics.middleName","last_name":"body.escapedPrisonerDetails[#2].demographics.surName","sex_code":"body.escapedPrisonerDetails[#2].demographics.gender","birth_date":"body.escapedPrisonerDetails[#2].demographics.dob"}},"offenderBookingDetails":{"*":{"booking_no":"body.escapedPrisonerDetails[#2].imprisonmentDetails.pin","booking_begin_date":"body.escapedPrisonerDetails[#2].imprisonmentDetails.intakeDatetime","booking_status":"body.escapedPrisonerDetails[#2].imprisonmentDetails.imprisonmentStatus"}},"offenderHousingDetails":{"*":{"agy_loc_id":"body.escapedPrisonerDetails[#2].housing.facility","housing_lev_1_code":"body.escapedPrisonerDetails[#2].housing.unit","assignment_time":"body.escapedPrisonerDetails[#2].housing.assignDate","assignment_end_time":"body.escapedPrisonerDetails[#2].housing.endDate"}},"offenderReleaseDetails":{"*":{"release_date":"body.escapedPrisonerDetails[#2].imprisonmentDetails.releaseDateTime"}}}},{"operation":"default","spec":{"header":{"intId":"CurrentPrisoners"}}}]' 
 where spec_key = 'ESCAPED_PRISONER_FORMATTER';
 
 

