CREATE USER OMS_STAGE
   IDENTIFIED BY oms_stage
   DEFAULT TABLESPACE tag_data
   TEMPORARY TABLESPACE temp
   PROFILE DEFAULT;


GRANT CREATE SESSION TO oms_stage;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TYPE TO oms_stage;
GRANT CREATE ANY INDEX TO oms_stage;
GRANT EXECUTE ANY PROCEDURE TO oms_stage;
GRANT RESOURCE, TAG_USER TO oms_stage;

-- GRANT EXECUTE ON DBMS_STATS TO oms_stage; 

-- GRANT SELECT ON V_$SESSION TO oms_stage; 
-- GRANT SELECT ON V_$INSTANCE TO oms_stage; 
-- GRANT SELECT ON dba_objects TO oms_stage; 
GRANT UNLIMITED TABLESPACE TO oms_stage;
