INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCMTIRLV', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER', NULL);

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCMTIDET', 444, 'A', 'Y', CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER', NULL);

INSERT INTO MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG)
VALUES('OCDOTRLV', 444, 'A', 'Y', CURRENT_TIMESTAMP, 'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER', NULL);	

Insert into MODULE_PRIVILEGES (MODULE_NAME,ROLE_ID,ACCESS_PRIVILEGE,VERIFICATION_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG) 
values ('OCDHEALT', 444,'A','Y',CURRENT_TIMESTAMP,'OMS_OWNER',CURRENT_TIMESTAMP, 'OMS_OWNER', null);