
OTMCOPRO_FIND_CGFKCSLDDPPAYEECORPORATEI {
 	SELECT CORP.CORPORATE_ID  PAYEE_CORPORATE_ID  /* CG$FK */ FROM (SELECT CRP.CORPORATE_ID , CRP.CORPORATE_NAME        FROM CORPORATES CRP , CORPORATE_TYPES CTP       WHERE CRP.CORPORATE_ID = CTP.CORPORATE_ID        AND CTP.CORPORATE_TYPE NOT IN ('VENDOR' ,'PROGRAM' )       UNION       SELECT CORPORATE_ID ,CORPORATE_NAME       FROM CORPORATES CRP2       WHERE NOT EXISTS ( SELECT 1 FROM CORPORATE_TYPES CTP2 WHERE CRP2.CORPORATE_ID = CTP2.CORPORATE_ID  )       ) CORP
}

OTMCOPRO_FIND_CGFKCSLDDDRECEIPTTXNTYPE {
 	SELECT TXN_TYPE.TXN_TYPE CODE /* CG$FK */  ,TXN_TYPE.DESCRIPTION DESCRIPTION FROM TRANSACTION_TYPES TXN_TYPE WHERE TXN_USAGE = 'R' AND ACTIVE_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND CASELOAD_TYPE = :caseloadType ORDER BY TXN_TYPE.TXN_TYPE  ,TXN_TYPE.DESCRIPTION
}

OTMCOPRO_FIND_CGFKCSLDDPDEDUCTIONTYPE {
 	SELECT DED_TYPE.DEDUCTION_TYPE CODE /* CG$FK */  ,DED_TYPE.DEDUCTION_DESC DESCRIPTION FROM DEDUCTION_TYPES DED_TYPE WHERE DEDUCTION_CATEGORY = 'CROB' AND ACTIVE_FLAG = 'Y' AND CASELOAD_CODE IN ('BOTH' ,:CASELOADTYPE ) ORDER BY DED_TYPE.DEDUCTION_TYPE  ,DED_TYPE.DEDUCTION_DESC
}

OTMCOPRO_FIND_CGFKCSLDDPACCOUNTCODE {
 	SELECT AC_CODE.ACCOUNT_CODE /* CG$FK */  ,AC_CODE.ACCOUNT_NAME DESCRIPTION FROM ACCOUNT_CODES AC_CODE WHERE SUB_ACCOUNT_TYPE IS NULL AND POSTING_STATUS_FLAG = 'Y' AND CASELOAD_TYPE = :CASELOADTYPE ORDER BY AC_CODE.ACCOUNT_CODE  ,AC_CODE.ACCOUNT_NAME
}

OTMCOPRO_FIND_CGFKCSLDDPPAYEEPERSONID {
 	SELECT PER.PERSON_ID  PAYEE_PERSON_ID  /* CG$FK */ FROM   PERSONS PER
}

OTMCOPRO_CSLDDP_FIND_CASELOAD_DEDUCTION_PROFILES {
 	SELECT DELAY_RECAPTURE, ACTIVE_FLAG, CASELOAD_ID, DEDUCTION_TYPE, EFFECTIVE_DATE, FIFO_FLAG, FO_AL_ALL_OFFENDER_FLAG, PERCENTAGE, INTERNAL_PRIORITY_NO, EXTERNAL_PRIORITY_NO, ACCOUNT_CODE, CO_LIMIT_AMOUNT, CO_CREDIT_WHEN_INDIGENT_FLAG, MAX_MONTHLY_AMOUNT, MAX_TOTAL_AMOUNT, EXPIRY_DATE, PAYEE_PERSON_ID, PAYEE_CORPORATE_ID, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, FLAT_RATE, MINIMUM_TRUST_BALANCE, INDIGENT_MANDATORY_FLAG, COMM_CONDITION_TYPE, COMM_CONDITION_CODE, MAX_RECURSIVE_AMOUNT, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, CATEGORY_TYPE, SEAL_FLAG FROM CASELOAD_DEDUCTION_PROFILES
}
OTMCOPRO_CSLDDP_INSERT_CASELOAD_DEDUCTION_PROFILES {
--	INSERT INTO CASELOAD_DEDUCTION_PROFILES(DELAY_RECAPTURE,ACTIVE_FLAG,CASELOAD_ID,DEDUCTION_TYPE,EFFECTIVE_DATE,FIFO_FLAG,FO_AL_ALL_OFFENDER_FLAG,PERCENTAGE,INTERNAL_PRIORITY_NO,EXTERNAL_PRIORITY_NO,ACCOUNT_CODE,CO_LIMIT_AMOUNT,CO_CREDIT_WHEN_INDIGENT_FLAG,MAX_MONTHLY_AMOUNT,MAX_TOTAL_AMOUNT,EXPIRY_DATE,PAYEE_PERSON_ID,PAYEE_CORPORATE_ID,MODIFY_USER_ID,MODIFY_DATE,LIST_SEQ,FLAT_RATE,MINIMUM_TRUST_BALANCE,INDIGENT_MANDATORY_FLAG,COMM_CONDITION_TYPE,COMM_CONDITION_CODE,MAX_RECURSIVE_AMOUNT,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,CATEGORY_TYPE,SEAL_FLAG) VALUES(
--	:delayRecapture, :activeFlag, :caseloadId, :deductionType, :effectiveDate, :fifoFlag, 'N', :percentage, :internalPriorityNo, :externalPriorityNo, :accountCode, :coLimitAmount, :coCreditWhenIndigentFlag, :maxMonthlyAmount, :maxTotalAmount, :expiryDate, :payeePersonId, :payeeCorporateId, USER, SYSDATE, :listSeq, :flatRate, :minimumTrustBalance, :indigentMandatoryFlag, :commConditionType, :commConditionCode, :maxRecursiveAmount, SYSDATE, USER, SYSDATE, :categoryType, :sealFlag)
	 insert into CASELOAD_DEDUCTION_PROFILES(DELAY_RECAPTURE, ACTIVE_FLAG, CASELOAD_ID, DEDUCTION_TYPE, EFFECTIVE_DATE, FIFO_FLAG, FO_AL_ALL_OFFENDER_FLAG, PERCENTAGE, INTERNAL_PRIORITY_NO, EXTERNAL_PRIORITY_NO, ACCOUNT_CODE, CO_LIMIT_AMOUNT, CO_CREDIT_WHEN_INDIGENT_FLAG, MAX_MONTHLY_AMOUNT, MAX_TOTAL_AMOUNT, EXPIRY_DATE, PAYEE_PERSON_ID, PAYEE_CORPORATE_ID, MODIFY_DATE, LIST_SEQ, FLAT_RATE, MINIMUM_TRUST_BALANCE, INDIGENT_MANDATORY_FLAG, COMM_CONDITION_TYPE, COMM_CONDITION_CODE, MAX_RECURSIVE_AMOUNT, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, CATEGORY_TYPE, SEAL_FLAG) values( :delayRecapture, :activeFlag, :caseloadId, :deductionType, :effectiveDate, :fifoFlag, 'N', :percentage, :internalPriorityNo, :externalPriorityNo, :accountCode, :coLimitAmount, :coCreditWhenIndigentFlag, :maxMonthlyAmount, :maxTotalAmount, :expiryDate, :payeePersonId, :payeeCorporateId, CURRENT_TIMESTAMP, :listSeq, :flatRate, :minimumTrustBalance, :indigentMandatoryFlag, :commConditionType, :commConditionCode, :maxRecursiveAmount, CURRENT_TIMESTAMP, :createUserId, CURRENT_TIMESTAMP, :categoryType, :sealFlag) 
}

OTMCOPRO_CSLDDP_UPDATE_CASELOAD_DEDUCTION_PROFILES {
--	UPDATE CASELOAD_DEDUCTION_PROFILES set DELAY_RECAPTURE = :delayRecapture , ACTIVE_FLAG = :activeFlag , EFFECTIVE_DATE = :effectiveDate , FIFO_FLAG = :fifoFlag , FO_AL_ALL_OFFENDER_FLAG = :foAlAllOffenderFlag , PERCENTAGE = :percentage , INTERNAL_PRIORITY_NO = :internalPriorityNo , EXTERNAL_PRIORITY_NO = :externalPriorityNo , ACCOUNT_CODE = :accountCode , CO_LIMIT_AMOUNT = :coLimitAmount , CO_CREDIT_WHEN_INDIGENT_FLAG = :coCreditWhenIndigentFlag , MAX_MONTHLY_AMOUNT = :maxMonthlyAmount , MAX_TOTAL_AMOUNT = :maxTotalAmount , EXPIRY_DATE = :expiryDate , PAYEE_PERSON_ID = :payeePersonId , PAYEE_CORPORATE_ID = :payeeCorporateId , LIST_SEQ = :listSeq , FLAT_RATE = :flatRate , MINIMUM_TRUST_BALANCE = :minimumTrustBalance , INDIGENT_MANDATORY_FLAG = :indigentMandatoryFlag , COMM_CONDITION_TYPE = :commConditionType , COMM_CONDITION_CODE = :commConditionCode , MAX_RECURSIVE_AMOUNT = :maxRecursiveAmount , CATEGORY_TYPE = :categoryType , SEAL_FLAG = :sealFlag  
--	 WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType
	 update CASELOAD_DEDUCTION_PROFILES set DELAY_RECAPTURE = :delayRecapture , ACTIVE_FLAG = :activeFlag , EFFECTIVE_DATE = :effectiveDate , FIFO_FLAG = :fifoFlag , FO_AL_ALL_OFFENDER_FLAG = :foAlAllOffenderFlag , PERCENTAGE = :percentage , INTERNAL_PRIORITY_NO = :internalPriorityNo , EXTERNAL_PRIORITY_NO = :externalPriorityNo , ACCOUNT_CODE = :accountCode , CO_LIMIT_AMOUNT = :coLimitAmount , CO_CREDIT_WHEN_INDIGENT_FLAG = :coCreditWhenIndigentFlag , MAX_MONTHLY_AMOUNT = :maxMonthlyAmount , MAX_TOTAL_AMOUNT = :maxTotalAmount , EXPIRY_DATE = :expiryDate , PAYEE_PERSON_ID = :payeePersonId , PAYEE_CORPORATE_ID = :payeeCorporateId , LIST_SEQ = :listSeq , FLAT_RATE = :flatRate , MINIMUM_TRUST_BALANCE = :minimumTrustBalance , INDIGENT_MANDATORY_FLAG = :indigentMandatoryFlag , COMM_CONDITION_TYPE = :commConditionType , COMM_CONDITION_CODE = :commConditionCode , MAX_RECURSIVE_AMOUNT = :maxRecursiveAmount , CATEGORY_TYPE = :categoryType , SEAL_FLAG = :sealFlag, MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where CASELOAD_ID = :caseloadId and DEDUCTION_TYPE = :deductionType 
}

OTMCOPRO_CSLDDP_DELETE_CASELOAD_DEDUCTION_PROFILES { 
	DELETE FROM CASELOAD_DEDUCTION_PROFILES WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType
}

OTMCOPRO_CSLDDD_FIND_CASELOAD_DEDUCTION_DETAILS {
 	SELECT CASELOAD_ID, DEDUCTION_TYPE, RECEIPT_TXN_TYPE, PERCENTAGE, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, FLAT_RATE, MINIMUM_TRUST_BALANCE_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG  FROM CASELOAD_DEDUCTION_DETAILS  WHERE CASELOAD_ID = :CASELOADID AND DEDUCTION_TYPE  = :DEDUCTIONTYPE AND (PERCENTAGE IS NOT NULL OR FLAT_RATE IS NOT NULL) AND MINIMUM_TRUST_BALANCE_FLAG IS NOT NULL
}
OTMCOPRO_CSLDDD_INSERT_CASELOAD_DEDUCTION_DETAILS {
--	INSERT INTO CASELOAD_DEDUCTION_DETAILS(CASELOAD_ID,DEDUCTION_TYPE,RECEIPT_TXN_TYPE,PERCENTAGE,MODIFY_USER_ID,MODIFY_DATE,LIST_SEQ,FLAT_RATE,MINIMUM_TRUST_BALANCE_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG) VALUES(
--	:caseloadId, :deductionType, :receiptTxnType, :percentage, USER, SYSDATE, :listSeq, :flatRate, :minimumTrustBalanceFlag, SYSDATE, USER, SYSDATE, :sealFlag)
	 insert into CASELOAD_DEDUCTION_DETAILS(CASELOAD_ID, DEDUCTION_TYPE, RECEIPT_TXN_TYPE, PERCENTAGE, MODIFY_DATE, LIST_SEQ, FLAT_RATE, MINIMUM_TRUST_BALANCE_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) values( :caseloadId, :deductionType, :receiptTxnType, :percentage, CURRENT_TIMESTAMP, :listSeq, :flatRate, :minimumTrustBalanceFlag, CURRENT_TIMESTAMP, :createUserId, CURRENT_TIMESTAMP, :sealFlag) 
}

OTMCOPRO_CSLDDD_UPDATE_CASELOAD_DEDUCTION_DETAILS {
--	UPDATE CASELOAD_DEDUCTION_DETAILS SET PERCENTAGE = :percentage, FLAT_RATE = :flatRate, MINIMUM_TRUST_BALANCE_FLAG = :minimumTrustBalanceFlag WHERE DEDUCTION_TYPE = :deductionType AND CASELOAD_ID = :caseloadId AND RECEIPT_TXN_TYPE = :receiptTxnType
	update CASELOAD_DEDUCTION_DETAILS set PERCENTAGE = :percentage, FLAT_RATE = :flatRate, MINIMUM_TRUST_BALANCE_FLAG = :minimumTrustBalanceFlag, MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where DEDUCTION_TYPE = :deductionType and CASELOAD_ID = :caseloadId and RECEIPT_TXN_TYPE = :receiptTxnType
}

OTMCOPRO_CSLDDD_DELETE_CASELOAD_DEDUCTION_DETAILS { 
	DELETE FROM CASELOAD_DEDUCTION_DETAILS WHERE DEDUCTION_TYPE = :deductionType AND CASELOAD_ID = :caseloadId AND RECEIPT_TXN_TYPE = :receiptTxnType
}


OTMCOPRO_CGFKCHK_CSLD_DP_DEDPROF_CORP__ {
	SELECT  '1' FROM   CORPORATES CORP WHERE  CORP.CORPORATE_ID = :PAYEECORPORATEID
}

OTMCOPRO_CGFKCHK_CSLD_DP_DEDPROF_PER_F_ {
	SELECT  '1' FROM   PERSONS PER WHERE  PER.PERSON_ID = :PAYEEPERSONID
}

OTMCOPRO_CGFKCHK_CSLD_DP_DEDPROF_AC_CO_ {
	SELECT AC_CODE.ACCOUNT_NAME FROM   ACCOUNT_CODES AC_CODE WHERE  AC_CODE.ACCOUNT_CODE = :ACCOUNTCODE AND     SUB_ACCOUNT_TYPE IS NULL AND POSTING_STATUS_FLAG = 'Y' AND AC_CODE.CASELOAD_TYPE = :CASELOADTYPE
}

OTMCOPRO_CGFKCHK_CSLD_DP_DEDPROF_DEDTY_ {
	SELECT DED_TYPE.DEDUCTION_DESC FROM   DEDUCTION_TYPES DED_TYPE WHERE  DED_TYPE.DEDUCTION_TYPE = :DEDUCTIONTYPE AND     DEDUCTION_CATEGORY = 'CROB' AND ACTIVE_FLAG = 'Y' AND DED_TYPE.CASELOAD_CODE IN('BOTH', :CASELOADTYPE)
}

OTMCOPRO_CGWHEN_NEW_FORM_INSTANCE_ {
	select
	SYSDATE(),
	upper(user)
from
	DUAL
}

OTMCOPRO_CGFKCHK_CSLD_DD_CSLD_DD_TXNTY_ {
	SELECT TXN_TYPE.DESCRIPTION FROM   TRANSACTION_TYPES TXN_TYPE WHERE  TXN_TYPE.TXN_TYPE = :RECEIPTTXNTYPE AND     TXN_USAGE = 'R' AND ACTIVE_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND TXN_TYPE.CASELOAD_TYPE = :CASELOADTYPE
}
OTMCOPRO_GET_PERCENT_AND_ENTERNAL_PRIORITY {
	SELECT percentage "per", external_priority_no "extPrioNo"  FROM caseload_deduction_profiles  WHERE deduction_type = :deductionType  AND caseload_id = :caseloadId
}
OTMCOPRO_GET_MAX_EXTERNAL_PRIORITY_NO {
	select
	coalesce (MAX (external_priority_no),
	0) + 1
from
	caseload_deduction_profiles
where
	caseload_id = :caseloadId
}
OTMCOPRO_GET_MAX_INTERNAL_PRIORITY_NO {
	select
	coalesce (MAX (internal_priority_no),
	0) + 1
from
	caseload_deduction_profiles
where
	caseload_id = :caseloadId
	and external_priority_no = :externalPriorityNo
}

OTMCOPRO_GET_RECEIPT_PERCENTAGE {
	select
	coalesce(MAX (coalesce (percentage,
	0)),
	0)
from
	caseload_deduction_details
where
	caseload_id = :caseloadId
	and deduction_type = :deductionType
}
OTMCOPRO_UPDATE_CASELOAD_DEDUCTION_PROFILES_PERCENTAGE {
--	UPDATE caseload_deduction_profiles  SET percentage = :percentage  WHERE caseload_id = :caseloadId  AND deduction_type = :deductionType
	update caseload_deduction_profiles set percentage = :percentage, MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where caseload_id = :caseloadId and deduction_type = :deductionType
}
OTMCOPRO_GET_CALCULATE_ON_VAL {
	SELECT FROM_BALANCE_TYPE FROM DEDUCTION_TYPES WHERE DEDUCTION_TYPE = :deductionType
}
OTMCOPRO_CHK_DUPLICATE {
SELECT 'X' FROM  CASELOAD_DEDUCTION_PROFILES  WHERE CASELOAD_ID = :caseloadId AND   DEDUCTION_TYPE = :deductionType
}
OTMCOPRO_GET_LIMIT_AND_PERIOD_TYPE {
 SELECT LIMIT_AMOUNT, PERIOD_TYPE   FROM   CASELOAD_LIMITS  WHERE CASELOAD_ID = :caseloadId   AND  LIMIT_TYPE  = :deductionType
}
OTMCOPRO_CGFKCHK_CSLD_DBEN_CSLD_DBEN_C {
	SELECT CORP.CASELOAD_ID ,CORP.CORPORATE_NAME, CORP.CORPORATE_ID FROM   CORPORATES CORP WHERE  CORP.CORPORATE_ID = :corporateId
}