
OTMDPRIO_CSLDDP_FIND_CASELOAD_DEDUCTION_PROFILES {

--SELECT *  FROM CASELOAD_DEDUCTION_PROFILES   where CASELOAD_ID = 'ITAG' ORDER BY EXTERNAL_PRIORITY_NO ,INTERNAL_PRIORITY_NO
 	SELECT *  FROM CASELOAD_DEDUCTION_PROFILES   where 
}
OTMDPRIO_CSLDDP_UPDATE_CASELOAD_DEDUCTION_PROFILES {
--	UPDATE CASELOAD_DEDUCTION_PROFILES    SET EXTERNAL_PRIORITY_NO = :externalPriorityNo ,INTERNAL_PRIORITY_NO =:internalPriorityNo, INDIGENT_MANDATORY_FLAG = :indigentMandatoryFlag ,FIFO_FLAG =:fifoFlag   
--	WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE =:deductionType
UPDATE CASELOAD_DEDUCTION_PROFILES    SET EXTERNAL_PRIORITY_NO = :externalPriorityNo ,INTERNAL_PRIORITY_NO =:internalPriorityNo, INDIGENT_MANDATORY_FLAG = :indigentMandatoryFlag ,FIFO_FLAG =:fifoFlag, MODIFY_DATE = CURRENT_DATE ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId  
	WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE =:deductionType
}


OTMDPRIO_CGWHEN_NEW_FORM_INSTANCE_ {

SELECT current_timestamp, 'OMS_OWNER'

--	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
OTMDPRIO_GETBALTYPEDESC {
SELECT DED_TYPE.DEDUCTION_DESC,DED_TYPE.FROM_BALANCE_TYPE    FROM   DEDUCTION_TYPES DED_TYPE   WHERE  DED_TYPE.DEDUCTION_TYPE = :deductionType 
}