
OTMTFPRO_FIND_CGFKCSLDDPPAYEECORPORATEI {
 	SELECT TO_CHAR(CORP.CORPORATE_ID)  CODE  /* CG$FK */        ,CORP.CORPORATE_NAME  DESCRIPTION FROM  (SELECT CRP.CORPORATE_ID  , CRP.CORPORATE_NAME , CRP.CASELOAD_ID         FROM CORPORATES CRP , CORPORATE_TYPES CTP        WHERE CRP.CORPORATE_ID = CTP.CORPORATE_ID         AND CTP.CORPORATE_TYPE NOT IN ('VENDOR' ,'PROGRAM' )        UNION        SELECT CRP2.CORPORATE_ID  , CRP2.CORPORATE_NAME , CRP2.CASELOAD_ID        FROM CORPORATES CRP2        WHERE NOT EXISTS ( SELECT 1 FROM CORPORATE_TYPES CTP2 WHERE CRP2.CORPORATE_ID = CTP2.CORPORATE_ID  )                ) CORP ORDER BY  CORP.CORPORATE_ID
}

OTMTFPRO_FIND_CGFKCSLDDDRECEIPTTXNTYPE {
 	SELECT TXN_TYPE.TXN_TYPE CODE /* CG$FK */  ,TXN_TYPE.DESCRIPTION DESCRIPTION FROM TRANSACTION_TYPES TXN_TYPE WHERE TXN_USAGE = 'D' AND ACTIVE_FLAG = 'Y' AND ALL_CASELOAD_FLAG = 'Y' AND CREDIT_OBLIGATION_TYPE IS NULL AND TXN_TYPE.CASELOAD_TYPE = :caseloadType ORDER BY TXN_TYPE.TXN_TYPE  ,TXN_TYPE.DESCRIPTION
}

OTMTFPRO_FIND_CGFKCSLDDPDEDUCTIONTYPE {
 	SELECT DED_TYPE.DEDUCTION_TYPE CODE/* CG$FK */  ,DED_TYPE.DEDUCTION_DESC DESCRIPTION FROM DEDUCTION_TYPES DED_TYPE WHERE DEDUCTION_CATEGORY = 'DTF' AND ACTIVE_FLAG = 'Y' AND DED_TYPE.CASELOAD_CODE IN ( 'BOTH' , :caseloadType  ) ORDER BY DED_TYPE.DEDUCTION_TYPE  ,DED_TYPE.DEDUCTION_DESC
}

OTMTFPRO_FIND_CGFKCSLDDPACCOUNTCODE {
 	SELECT TO_CHAR(AC_CODE.ACCOUNT_CODE) CODE /* CG$FK */  ,AC_CODE.ACCOUNT_NAME DESCRIPTION FROM ACCOUNT_CODES AC_CODE WHERE POSTING_STATUS_FLAG = 'Y' AND SUB_ACCOUNT_TYPE IS NULL AND AC_CODE.CASELOAD_TYPE = :caseloadType ORDER BY AC_CODE.ACCOUNT_CODE
}

OTMTFPRO_CSLDDP_FIND_CASELOAD_DEDUCTION_PROFILES {
-- 	SELECT DELAY_RECAPTURE, ACTIVE_FLAG, CASELOAD_ID, DEDUCTION_TYPE, EFFECTIVE_DATE, FIFO_FLAG, FO_AL_ALL_OFFENDER_FLAG, PERCENTAGE, INTERNAL_PRIORITY_NO, EXTERNAL_PRIORITY_NO, ACCOUNT_CODE, CO_LIMIT_AMOUNT, CO_CREDIT_WHEN_INDIGENT_FLAG, MAX_MONTHLY_AMOUNT, MAX_TOTAL_AMOUNT, EXPIRY_DATE, PAYEE_PERSON_ID, PAYEE_CORPORATE_ID, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, FLAT_RATE, MINIMUM_TRUST_BALANCE, INDIGENT_MANDATORY_FLAG, COMM_CONDITION_TYPE, COMM_CONDITION_CODE, MAX_RECURSIVE_AMOUNT, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, CATEGORY_TYPE, SEAL_FLAG FROM CASELOAD_DEDUCTION_PROFILES   WHERE #paramQuery  CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE FROM DEDUCTION_TYPES WHERE DEDUCTION_CATEGORY = 'DTF')
 	SELECT DELAY_RECAPTURE, ACTIVE_FLAG, CASELOAD_ID, DEDUCTION_TYPE, EFFECTIVE_DATE, FIFO_FLAG, FO_AL_ALL_OFFENDER_FLAG,
 	PERCENTAGE, INTERNAL_PRIORITY_NO, EXTERNAL_PRIORITY_NO, ACCOUNT_CODE, CO_LIMIT_AMOUNT, CO_CREDIT_WHEN_INDIGENT_FLAG, 
 	MAX_MONTHLY_AMOUNT, MAX_TOTAL_AMOUNT, EXPIRY_DATE, PAYEE_PERSON_ID, PAYEE_CORPORATE_ID, MODIFY_USER_ID, MODIFY_DATE,
 	LIST_SEQ, FLAT_RATE, MINIMUM_TRUST_BALANCE, INDIGENT_MANDATORY_FLAG, COMM_CONDITION_TYPE, COMM_CONDITION_CODE,
 	MAX_RECURSIVE_AMOUNT, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, CATEGORY_TYPE, SEAL_FLAG FROM CASELOAD_DEDUCTION_PROFILES   WHERE   CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE IN (SELECT DEDUCTION_TYPE FROM DEDUCTION_TYPES WHERE DEDUCTION_CATEGORY = 'DTF')

}
OTMTFPRO_CSLDDP_INSERT_CASELOAD_DEDUCTION_PROFILES {
	--INSERT INTO CASELOAD_DEDUCTION_PROFILES(ACTIVE_FLAG, CASELOAD_ID, DEDUCTION_TYPE, EFFECTIVE_DATE, FIFO_FLAG,
	--FO_AL_ALL_OFFENDER_FLAG, PERCENTAGE, INTERNAL_PRIORITY_NO, EXTERNAL_PRIORITY_NO, ACCOUNT_CODE, EXPIRY_DATE,
	--PAYEE_CORPORATE_ID, MODIFY_DATE,CREATE_USER_ID)
	--VALUES(:activeFlag, :caseloadId, :deductionType, :effectiveDate, :fifoFlag, :foAlAllOffenderFlag, :percentage,
	--:internalPriorityNo, :externalPriorityNo, :accountCode, :expiryDate, :payeeCorporateId, current_timestamp,:createUserId)
INSERT INTO CASELOAD_DEDUCTION_PROFILES(ACTIVE_FLAG, CASELOAD_ID, DEDUCTION_TYPE, EFFECTIVE_DATE, FIFO_FLAG,
	FO_AL_ALL_OFFENDER_FLAG, PERCENTAGE, INTERNAL_PRIORITY_NO, EXTERNAL_PRIORITY_NO, ACCOUNT_CODE, EXPIRY_DATE,
	PAYEE_CORPORATE_ID, MODIFY_DATE,CREATE_USER_ID,MODIFY_DATETIME,CREATE_DATETIME  )
	VALUES(:activeFlag, :caseloadId, :deductionType, :effectiveDate, :fifoFlag, :foAlAllOffenderFlag, :percentage,
	:internalPriorityNo, :externalPriorityNo, :accountCode, :expiryDate, :payeeCorporateId, current_timestamp,:createUserId,current_timestamp,current_timestamp)
}

OTMTFPRO_CSLDDP_UPDATE_CASELOAD_DEDUCTION_PROFILES {
	UPDATE CASELOAD_DEDUCTION_PROFILES SET ACCOUNT_CODE = :accountCode, EFFECTIVE_DATE = :effectiveDate, 
	ACTIVE_FLAG = :activeFlag, EXPIRY_DATE = :expiryDate, FO_AL_ALL_OFFENDER_FLAG = :foAlAllOffenderFlag, 
	PAYEE_CORPORATE_ID = :payeeCorporateId,MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId
	WHERE DEDUCTION_TYPE = :deductionType AND CASELOAD_ID = :caseloadId
	}

OTMTFPRO_CSLDDP_DELETE_CASELOAD_DEDUCTION_PROFILES {
--	DELETE FROM CASELOAD_DEDUCTION_PROFILES WHERE DEDUCTION_TYPE = :deductionType AND CASELOAD_ID = :caseloadId
    DELETE FROM CASELOAD_DEDUCTION_PROFILES WHERE  CASELOAD_ID = :caseloadId  AND DEDUCTION_TYPE = :deductionType

}

OTMTFPRO_CSLDDD_FIND_CASELOAD_DEDUCTION_DETAILS {
 	SELECT CASELOAD_ID, DEDUCTION_TYPE, RECEIPT_TXN_TYPE, PERCENTAGE, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, FLAT_RATE, MINIMUM_TRUST_BALANCE_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG  FROM CASELOAD_DEDUCTION_DETAILS  WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType
}
OTMTFPRO_CSLDDD_INSERT_CASELOAD_DEDUCTION_DETAILS {
    --INSERT INTO CASELOAD_DEDUCTION_DETAILS(CASELOAD_ID, DEDUCTION_TYPE, RECEIPT_TXN_TYPE,
	--PERCENTAGE, FLAT_RATE, MODIFY_DATE,CREATE_USER_ID) VALUES(:caseloadId, :deductionType, :receiptTxnType,
	--:percentage, :flatRate, current_timestamp,:createUserId)
	INSERT INTO CASELOAD_DEDUCTION_DETAILS(CASELOAD_ID, DEDUCTION_TYPE, RECEIPT_TXN_TYPE,
	PERCENTAGE, FLAT_RATE, MODIFY_DATE,CREATE_USER_ID,MODIFY_DATETIME,CREATE_DATETIME ) VALUES(:caseloadId, :deductionType, :receiptTxnType,
	:percentage, :flatRate, current_timestamp,:createUserId,current_timestamp,current_timestamp)
}

OTMTFPRO_CSLDDD_UPDATE_CASELOAD_DEDUCTION_DETAILS {
	UPDATE CASELOAD_DEDUCTION_DETAILS SET PERCENTAGE = :percentage, FLAT_RATE = :flatRate,
	MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId
	WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType AND RECEIPT_TXN_TYPE = :receiptTxnType
}

OTMTFPRO_CSLDDD_DELETE_CASELOAD_DEDUCTION_DETAILS {
	DELETE FROM CASELOAD_DEDUCTION_DETAILS WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType AND RECEIPT_TXN_TYPE = :receiptTxnType
}

OTMTFPRO_SYSPFL_FIND_SYSTEM_PROFILES {
-- 	SELECT   FROM SYSTEM_PROFILES  /* where  */
	SELECT *  FROM SYSTEM_PROFILES  /* where  */
}

OTMTFPRO_CGFKCHK_CSLD_DP_DEDPROF_CORP {
	SELECT CORP.CORPORATE_NAME FROM   CORPORATES CORP WHERE  CORP.CORPORATE_ID = :corporateId
}

OTMTFPRO_CGFKCHK_CSLD_DP_DEDPROF_AC_CO_ {


	SELECT AC_CODE.ACCOUNT_NAME FROM   ACCOUNT_CODES AC_CODE WHERE  AC_CODE.ACCOUNT_CODE = :ACCOUNTCODE AND  POSTING_STATUS_FLAG = 'Y' AND  SUB_ACCOUNT_TYPE IS NULL AND  AC_CODE.CASELOAD_TYPE = CSLD_TYPE
}

OTMTFPRO_CGFKCHK_CSLD_DP_DEDPROF_DEDTY_ {
	SELECT DED_TYPE.DEDUCTION_DESC FROM   DEDUCTION_TYPES DED_TYPE WHERE  DED_TYPE.DEDUCTION_TYPE = :DEDUCTIONTYPE AND  DEDUCTION_CATEGORY = 'DTF' AND  ACTIVE_FLAG = 'Y' AND  DED_TYPE.CASELOAD_CODE IN ( 'BOTH', CSLD_TYPE )
}

OTMTFPRO_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OTMTFPRO_CGFKCHK_CSLD_DD_CSLD_DD_TXNTY_ {
	SELECT TXN_TYPE.DESCRIPTION FROM   TRANSACTION_TYPES TXN_TYPE WHERE  TXN_TYPE.TXN_TYPE = :RECEIPTTXNTYPE AND  TXN_USAGE = 'D' AND ACTIVE_FLAG = 'Y' AND  ALL_CASELOAD_FLAG = 'Y' AND  CREDIT_OBLIGATION_TYPE IS NULL AND  TXN_TYPE.CASELOAD_TYPE = CSLD_TYPE
}
OTMTFPRO_OMS_UTILS.DISPLAY_USER_MESSAGE {
	SELECT sys_msg.appln_code || ' ' ||  sys_msg.message_number || ' ' || sys_msg.message_type || ' ' || sys_msg.message_text MESSAGE FROM system_messages sys_msg WHERE sys_msg.message_number = :msgNo  AND sys_msg.appln_code = :applnCode
}
OTMTFPRO_CHK_DUPLICATE_DED_TYPE {
	SELECT CASELOAD_ID, DEDUCTION_TYPE FROM CASELOAD_DEDUCTION_PROFILES WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType
}
GET_EXTERNAL_PRIORITY_NO {
--SELECT NVL(MAX(EXTERNAL_PRIORITY_NO),0) + 1 FROM   CASELOAD_DEDUCTION_PROFILES  WHERE  CASELOAD_ID = :caseloadId
SELECT COALESCE(MAX(EXTERNAL_PRIORITY_NO),0) + 1 FROM   CASELOAD_DEDUCTION_PROFILES  WHERE  CASELOAD_ID = :caseloadId

}
GET_CSLDDD_MAX_PERCENTAGE {
--	SELECT NVL(MAX(NVL(PERCENTAGE,0)),0) FROM CASELOAD_DEDUCTION_DETAILS WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType 
	SELECT COALESCE(MAX(COALESCE(PERCENTAGE,0)),0) FROM CASELOAD_DEDUCTION_DETAILS WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType 

}
UPDATE_CSLD_DD_CASELOAD_DEDUCTION_PROFILES {
	--UPDATE CASELOAD_DEDUCTION_PROFILES SET PERCENTAGE = :percentage WHERE CASELOAD_ID = :caseloadId AND DEDUCTION_TYPE = :deductionType
UPDATE CASELOAD_DEDUCTION_PROFILES SET PERCENTAGE = :percentage,MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId WHERE CASELOAD_ID = :caseloadId  AND DEDUCTION_TYPE = :deductionType
}