
OCMPHBLK_PRGSRV_FIND_PROGRAM_SERVICES {
 	SELECT PROGRAM_ID,PROGRAM_CATEGORY,PROGRAM_CODE,DESCRIPTION,ACTIVE_FLAG,EXPIRY_DATE,COMMENT_TEXT,PROGRAM_CLASS,PARENT_PROGRAM_ID,CONTACT_METHOD,NO_OF_SESSIONS,NO_OF_ALLOWABLE_RESTARTS,NO_OF_ALLOWABLE_ABSENCES,CAPACITY,SESSION_LENGTH,COMPLETION_FLAG,MODULE_FLAG,MODULE_TYPE,BREAK_ALLOWED_FLAG,START_FLAG,NO_OF_WEEKLY_SESSIONS,PROGRAM_STATUS,LIST_SEQ,PHASE_TYPE,START_DATE,END_DATE,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,MODIFY_USER_ID,FUNCTION_TYPE,SEAL_FLAG  FROM PROGRAM_SERVICES  WHERE  PARENT_PROGRAM_ID=:programId AND PROGRAM_CLASS = 'PRG_BLK' ORDER BY LIST_SEQ,DESCRIPTION
}
OCMPHBLK_PRGSRV_INSERT_PROGRAM_SERVICES {
insert into PROGRAM_SERVICES(PROGRAM_ID, PROGRAM_CATEGORY, PROGRAM_CODE, DESCRIPTION, ACTIVE_FLAG, EXPIRY_DATE, COMMENT_TEXT, PROGRAM_CLASS, PARENT_PROGRAM_ID, CONTACT_METHOD, NO_OF_SESSIONS, NO_OF_ALLOWABLE_RESTARTS, NO_OF_ALLOWABLE_ABSENCES, CAPACITY, SESSION_LENGTH, COMPLETION_FLAG, MODULE_FLAG, MODULE_TYPE, BREAK_ALLOWED_FLAG, START_FLAG, NO_OF_WEEKLY_SESSIONS, PROGRAM_STATUS, LIST_SEQ, PHASE_TYPE, START_DATE, END_DATE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, FUNCTION_TYPE, SEAL_FLAG) values(:programId, :programCategory, :programCode, :description, :activeFlag, :expiryDate, :commentText, :programClass, :parentProgramId, :contactMethod, :noOfSessions, :noOfAllowableRestarts, :noOfAllowableAbsences, :capacity, :sessionLength, :completionFlag, :moduleFlag, :moduleType, :breakAllowedFlag, :startFlag, :noOfWeeklySessions, :programStatus, :listSeq, :phaseType, :startDate, :endDate, CURRENT_TIMESTAMP, :createUserId, null , :functionType, :sealFlag)
}

OCMPHBLK_PRGSRV_UPDATE_PROGRAM_SERVICES {
update PROGRAM_SERVICES set PROGRAM_ID =:programId, PROGRAM_CATEGORY =:programCategory, PROGRAM_CODE =:programCode, DESCRIPTION =:description, ACTIVE_FLAG =:activeFlag, EXPIRY_DATE =:expiryDate, COMMENT_TEXT =:commentText, PROGRAM_CLASS =:programClass, PARENT_PROGRAM_ID =:parentProgramId, CONTACT_METHOD =:contactMethod, NO_OF_SESSIONS =:noOfSessions, NO_OF_ALLOWABLE_RESTARTS =:noOfAllowableRestarts, NO_OF_ALLOWABLE_ABSENCES =:noOfAllowableAbsences, CAPACITY =:capacity, SESSION_LENGTH =:sessionLength, COMPLETION_FLAG =:completionFlag, MODULE_FLAG =:moduleFlag, MODULE_TYPE =:moduleType, BREAK_ALLOWED_FLAG =:breakAllowedFlag, START_FLAG =:startFlag, NO_OF_WEEKLY_SESSIONS =:noOfWeeklySessions, PROGRAM_STATUS =:programStatus, LIST_SEQ =:listSeq, PHASE_TYPE =:phaseType, START_DATE =:startDate, END_DATE =:endDate, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID =:modifyUserId, FUNCTION_TYPE =:functionType, SEAL_FLAG =:sealFlag where PROGRAM_ID =:programId
}

OCMPHBLK_PRGSRV_DELETE_PROGRAM_SERVICES { 
	DELETE FROM PROGRAM_SERVICES WHERE PROGRAM_ID=:programId 
}
OCMPHBLK_CHECK_NEXT_PRG_SRV_SEQ_UNIQUE { 
	SELECT 1  FROM PROGRAM_SERVICES WHERE parent_program_id = :pParentProgId  AND list_seq = :pListSeq AND program_class = 'PRG_BLK'
}



