
OCMSCHRC_CRSACT_UPDATE_COURSE_ACTIVITIES {
update COURSE_ACTIVITIES set HOLIDAY_FLAG = :holidayFlag, modify_datetime = current_timestamp , modify_user_id = :modifyUserId where CRS_ACTY_ID = :crsActyId
}

OCMSCHRC_CRSSCHEDULERUL_FIND_COURSE_SCHEDULE_RULES {
 	SELECT *  FROM COURSE_SCHEDULE_RULES where CRS_ACTY_ID = :crsActyId
}
OCMSCHRC_CRSSCHEDULERUL_INSERT_COURSE_SCHEDULE_RULES {
insert into COURSE_SCHEDULE_RULES(COURSE_SCHEDULE_RULE_ID, CRS_ACTY_ID, WEEK_NO, MONDAY_FLAG, TUESDAY_FLAG, WEDNESDAY_FLAG, THURSDAY_FLAG, FRIDAY_FLAG, SATURDAY_FLAG, SUNDAY_FLAG, START_TIME, END_TIME, SEAL_FLAG, CAPACITY, CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME) values(:courseScheduleRuleId, :crsActyId, :weekNo, :mondayFlag, :tuesdayFlag, :wednesdayFlag, :thursdayFlag, :fridayFlag, :saturdayFlag, :sundayFlag, :startTime, :endTime, :sealFlag, :capacity, CURRENT_TIMESTAMP , :createUserId , null )
}

OCMSCHRC_CRSSCHEDULERUL_UPDATE_COURSE_SCHEDULE_RULES {
update COURSE_SCHEDULE_RULES set MONDAY_FLAG = :mondayFlag, TUESDAY_FLAG = :tuesdayFlag, WEDNESDAY_FLAG = :wednesdayFlag, THURSDAY_FLAG = :thursdayFlag, FRIDAY_FLAG = :fridayFlag, SATURDAY_FLAG = :saturdayFlag, SUNDAY_FLAG = :sundayFlag, START_TIME = :startTime, END_TIME = :endTime, MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where COURSE_SCHEDULE_RULE_ID = :courseScheduleRuleId
}

OCMSCHRC_CRSSCHEDULERUL_DELETE_COURSE_SCHEDULE_RULES { 
	DELETE FROM COURSE_SCHEDULE_RULES where COURSE_SCHEDULE_RULE_ID = :courseScheduleRuleId
}

OCMSCHRC_PROGRAM_SERVICES_FIND_DESCRIPTION{
SELECT * FROM PROGRAM_SERVICES WHERE program_id = :programId
}

OCMSCHRC_GET_FLAG{
	SELECT HOLIDAY_FLAG FROM COURSE_ACTIVITIES WHERE CRS_ACTY_ID = :crsActyId
}

