
OCMSOSCH_CRSACT_FIND_COURSE_ACTIVITIES {
 	SELECT  * FROM COURSE_ACTIVITIES  

}
OCMSOSCH_CRSACT_DELETE_COURSE_ACTIVITIES { 
	DELETE FROM COURSE_ACTIVITIES
}

OCMSOSCH_COURSESCHED_FIND_COURSE_SCHEDULES {
 	SELECT CRS_SCH_ID, CRS_ACTY_ID, to_char(schedule_date, 'Day') WEEKDAY, SCHEDULE_DATE, START_TIME, END_TIME, SESSION_NO, DETAILS, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SCHEDULE_STATUS, CATCH_UP_CRS_SCH_ID, VIDEO_REFERENCE_ID, SEAL_FLAG, CANCELLED_FLAG FROM COURSE_SCHEDULES  where crs_acty_id = :p_crs_acty_id
}
OCMSOSCH_COURSESCHED_INSERT_COURSE_SCHEDULES {
insert into COURSE_SCHEDULES(CRS_SCH_ID, CRS_ACTY_ID, SCHEDULE_DATE, START_TIME, END_TIME, SCHEDULE_STATUS, CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME) values(:crsSchId, :crsActyId, :scheduleDate, :startTime, :endTime, :scheduleStatus, CURRENT_TIMESTAMP , :createUserId , null )
}

OCMSOSCH_COURSESCHED_UPDATE_COURSE_SCHEDULES {
update COURSE_SCHEDULES set SCHEDULE_DATE =:scheduleDate, START_TIME =:startTime, END_TIME =:endTime, MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where CRS_SCH_ID = :crsSchId
}

OCMSOSCH_COURSESCHED_DELETE_COURSE_SCHEDULES { 
	DELETE FROM COURSE_SCHEDULES where CRS_SCH_ID = :crsSchId
}


OCMSOSCH_CRS_ACT_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM COURSE_SCHEDULES C WHERE C.CRS_ACTY_ID = :CRSACTYID
}

OCMSOSCH_GET_DAY {
select
to_char(to_date(:scheduleDate, 'dd-MM-yyyy')::timestamp,'Day')
from
dual
}

OCMSOSCH_DIFF_BETWEEN_DATES {
SELECT 
CASE WHEN (INST_ACT_MAX_SCHEDULED_HOURS IS NULL) or (INST_ACT_MAX_SCHEDULED_HOURS = 0)
OR (INST_ACT_MAX_SCHEDULED_HOURS IS NOT NULL
AND INST_ACT_MAX_SCHEDULED_HOURS >= ABS((EXTRACT(EPOCH FROM TO_TIMESTAMP(:START_TIME,'DD/MM/YYYY HH24:MI') - TO_TIMESTAMP(:END_TIME,'DD/MM/YYYY HH24:MI'))/3600))) THEN 'Y'ELSE 'N' END FLAG
FROM PROGRAMS_PAY_SETTINGS
}