
OCMSTOFF_FIND_RGPSSEX {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'PS_SEX' AND ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL  ) OR ( '' = 'ENTER-QUERY' )  ) ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCMSTOFF_FIND_RGETHNICITY {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'ETHNICITY' AND ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL  ) OR ( '' = 'ENTER-QUERY' )  ) ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCMSTOFF_FIND_RGPSNEEDS {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'PS_FACILITY' AND ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL  ) OR ( '' = 'ENTER-QUERY' )  ) ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCMSTOFF_FIND_RGPSAGERANGE {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'PS_AGE_RANGE' AND ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL  ) OR ( '' = 'ENTER-QUERY' )  ) ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCMSTOFF_FIND_RGPSOFFGRPS {
 	SELECT REF_CODE.DESCRIPTION  ,REF_CODE.CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'PS_OFF_GRPS' AND ( ( ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL  ) OR ( '' = 'ENTER-QUERY' )  ) ORDER BY LIST_SEQ , DESCRIPTION ,CODE
}

OCMSTOFF_PRGPRFGD_FIND_PROGRAM_SERVICES_PROFILES {
 SELECT PROGRAM_ID ,PROGRAM_PROFILE_TYPE ,PROGRAM_PROFILE_CODE,PROGRAM_PROFILE_CODE PROFILE_GENDER_CODE,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM PROGRAM_SERVICES_PROFILES   where PROGRAM_ID=:programId AND PROGRAM_PROFILE_TYPE =:programProfileType
order by PROGRAM_PROFILE_CODE in (SELECT  PROGRAM_PROFILE_CODE FROM REFERENCE_CODES WHERE  domain = 'PS_SEX') 
}
OCMSTOFF_PRGPRFGD_INSERT_PROGRAM_SERVICES_PROFILES {
insert into PROGRAM_SERVICES_PROFILES(PROGRAM_ID , PROGRAM_PROFILE_TYPE , PROGRAM_PROFILE_CODE , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:programId , :programProfileType , :programProfileCode , CURRENT_TIMESTAMP , :createUserId , null , :sealFlag )
}

OCMSTOFF_PRGPRFGD_UPDATE_PROGRAM_SERVICES_PROFILES {
update PROGRAM_SERVICES_PROFILES set PROGRAM_ID = :programId , PROGRAM_PROFILE_TYPE = :programProfileType , PROGRAM_PROFILE_CODE = :programProfileCode , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag 
}

OCMSTOFF_PRGPRFGD_DELETE_PROGRAM_SERVICES_PROFILES { 
	DELETE FROM PROGRAM_SERVICES_PROFILES where PROGRAM_ID  = :programId AND PROGRAM_PROFILE_TYPE  = :programProfileType AND PROGRAM_PROFILE_CODE  = :programProfileCode
}
OCMSTOFF_PRGPRFFR_FIND_PROGRAM_SERVICES_PROFILES {
SELECT PROGRAM_ID ,PROGRAM_PROFILE_TYPE ,PROGRAM_PROFILE_CODE,PROGRAM_PROFILE_CODE PROFILE_ETI_CITY_CODE,CREATE_DATETIME ,
 	 	 	CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM PROGRAM_SERVICES_PROFILES   where PROGRAM_ID=:programId
 	 	 	AND PROGRAM_PROFILE_TYPE =:programProfileType
 	 	 	order by PROGRAM_PROFILE_CODE in (SELECT  PROGRAM_PROFILE_CODE FROM REFERENCE_CODES WHERE  domain = 'ETHNICITY')  
}
OCMSTOFF_PRGPRFAG_FIND_PROGRAM_SERVICES_PROFILES {
SELECT PROGRAM_ID ,PROGRAM_PROFILE_TYPE ,PROGRAM_PROFILE_CODE,PROGRAM_PROFILE_CODE PROFILE_AGE_RANGE_CODE,CREATE_DATETIME ,
 	 	CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM PROGRAM_SERVICES_PROFILES   where PROGRAM_ID=:programId
 	 	AND PROGRAM_PROFILE_TYPE =:programProfileType
 	 	order by PROGRAM_PROFILE_CODE in (SELECT  PROGRAM_PROFILE_CODE FROM REFERENCE_CODES WHERE  domain = 'PS_AGE_RANGE')  
}
OCMSTOFF_PRGPRFFA_FIND_PROGRAM_SERVICES_PROFILES {
SELECT PROGRAM_ID ,PROGRAM_PROFILE_TYPE ,PROGRAM_PROFILE_CODE,PROGRAM_PROFILE_CODE PROFILE_FACILITY_CODE,CREATE_DATETIME ,CREATE_USER_ID ,
 	MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM PROGRAM_SERVICES_PROFILES   where PROGRAM_ID=:programId AND PROGRAM_PROFILE_TYPE =:programProfileType
 	order by PROGRAM_PROFILE_CODE in (SELECT  PROGRAM_PROFILE_CODE FROM REFERENCE_CODES WHERE  domain = 'PS_NEEDS')  
}
OCMSTOFF_PRGPRFIG_FIND_PROGRAM_SERVICES_PROFILES {
SELECT PROGRAM_ID ,PROGRAM_PROFILE_TYPE ,PROGRAM_PROFILE_CODE,PROGRAM_PROFILE_CODE PROFILE_IN_GROUP_CODE,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM PROGRAM_SERVICES_PROFILES   where PROGRAM_ID=:programId AND PROGRAM_PROFILE_TYPE =:programProfileType
order by PROGRAM_PROFILE_CODE in (SELECT  PROGRAM_PROFILE_CODE FROM REFERENCE_CODES WHERE  domain = 'PS_OFF_GRPS')  
}
OCMSTOFF_PRGPRFXG_FIND_PROGRAM_SERVICES_PROFILES {
SELECT PROGRAM_ID ,PROGRAM_PROFILE_TYPE ,PROGRAM_PROFILE_CODE,PROGRAM_PROFILE_CODE PROFILE_EX_GROUP_CODE,CREATE_DATETIME ,CREATE_USER_ID ,
 	MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM PROGRAM_SERVICES_PROFILES   where PROGRAM_ID=:programId AND PROGRAM_PROFILE_TYPE =:programProfileType
 	order by PROGRAM_PROFILE_CODE in (SELECT  PROGRAM_PROFILE_CODE FROM REFERENCE_CODES WHERE  domain = 'PS_OFF_GRPS') 
}
OCMSTOFF_PROFILES_EXIST_COUNT{
SELECT count(*) FROM PROGRAM_SERVICES_PROFILES WHERE program_profile_code = :p_code AND program_profile_type = :p_type AND program_id = :p_program_id
}
OCMSTOFF_CONSTRAINT_VALIDATIONS{
SELECT AC1.TABLE_NAME FROM ALL_CONSTRAINTS AC1, ALL_CONSTRAINTS AC2 WHERE AC1.CONSTRAINT_NAME = :CONSTRAINTNAME AND AC2.TABLE_NAME = 'PROGRAM_SERVICES_PROFILES' AND AC1.CONSTRAINT_TYPE = 'R' AND AC2.CONSTRAINT_NAME = AC1.R_CONSTRAINT_NAME AND AC2.OWNER = AC1.R_OWNER AND AC2.CONSTRAINT_TYPE IN ('P', 'U')
}
