
OCMSVASS_FIND_RGASSESSMENTS {
 	SELECT  ASSESSMENT_CODE CODE , DESCRIPTION      FROM ASSESSMENTS    WHERE ((ACTIVE_FLAG = 'Y'            AND EXPIRY_DATE IS NULL  )            OR ( '' = 'ENTER-QUERY'  ) )      AND ASSESSMENT_CLASS = 'TYPE'      AND SCREEN_CODE IN('EVAL','BOTH')  ORDER BY LIST_SEQ , DESCRIPTION , ASSESSMENT_CODE
}

OCMSVASS_PRGQST_FIND_PROGRAM_ASSESSMENTS {
select PROGRAM_ID, ACTIVE_FLAG, EXPIRY_DATE, ASSESSMENT_ID, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG from PROGRAM_ASSESSMENTS where PROGRAM_ID =:PROGRAMID order by ACTIVE_FLAG desc 
}

OCMSVASS_PRGQST_INSERT_PROGRAM_ASSESSMENTS {
insert into PROGRAM_ASSESSMENTS(PROGRAM_ID , ACTIVE_FLAG , EXPIRY_DATE, ASSESSMENT_ID, CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME, SEAL_FLAG ) values(:programId, :activeFlag , :expiryDate, :assessmentId, current_timestamp , :createUserId , null , :sealFlag )
}

OCMSVASS_PRGQST_UPDATE_PROGRAM_ASSESSMENTS {
update PROGRAM_ASSESSMENTS set ACTIVE_FLAG =:activeFlag , EXPIRY_DATE =:expiryDate, MODIFY_DATETIME =current_timestamp , MODIFY_USER_ID =:modifyUserId, SEAL_FLAG =:sealFlag where PROGRAM_ID =:programId and ASSESSMENT_ID =:assessmentId
}

OCMSVASS_PRGQST_DELETE_PROGRAM_ASSESSMENTS { 
	DELETE FROM PROGRAM_ASSESSMENTS  where PROGRAM_ID =:programId and  ASSESSMENT_ID=:assessmentId 
}

OCMSVASS_GET_ASSESSMENT_CODE {
SELECT DISTINCT ASSESSMENT_CODE FROM ASSESSMENTS WHERE ASSESSMENT_ID = :ASSESSMENTID
}

OCMSVASS_GET_ASSESSMENT_ID {
SELECT DISTINCT ASSESSMENT_ID FROM ASSESSMENTS WHERE ASSESSMENT_CODE = :ASSESSMENTCODE
}
