
OIDMBRAS_FIND_RGREASONCODE {
 select
	DESCRIPTION ,
	CODE
from
	REFERENCE_CODES
where
	domain = 'MBR_AFF_RSN'
	and  (ACTIVE_FLAG = 'Y'
		and EXPIRED_DATE is null  )
}

OIDMBRAS_OFFENDERSTGASSOCIATIONS_FIND_OFFENDER_STG_ASSOCIATIONS {
 	SELECT OFFENDER_BOOK_ID, STG_SEQ, EFFECTIVE_DATE, GROUP_CODE, REASON_CODE, CREATE_USER_ID, CREATE_DATETIME, ACTIVE_FLAG, EXPIRY_DATE, EXPIRED_BY, COMMENT_TEXT, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM OFFENDER_STG_ASSOCIATIONS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID ORDER BY EFFECTIVE_DATE DESC
}
OIDMBRAS_OFFENDERSTGASSOCIATIONS_INSERT_OFFENDER_STG_ASSOCIATIONS {
insert into OFFENDER_STG_ASSOCIATIONS(OFFENDER_BOOK_ID, STG_SEQ, EFFECTIVE_DATE, GROUP_CODE, REASON_CODE, CREATE_USER_ID, CREATE_DATETIME, ACTIVE_FLAG, EXPIRY_DATE, EXPIRED_BY, COMMENT_TEXT, MODIFY_DATETIME, SEAL_FLAG) values(:offenderBookId, :stgSeq, :effectiveDate, :groupCode, :reasonCode, :createUserId, CURRENT_TIMESTAMP, :activeFlag, :expiryDate, :expiredBy, :commentText, null , :sealFlag)
}

OIDMBRAS_OFFENDERSTGASSOCIATIONS_UPDATE_OFFENDER_STG_ASSOCIATIONS {
	UPDATE OFFENDER_STG_ASSOCIATIONS set OFFENDER_BOOK_ID=:offenderBookId, STG_SEQ=:stgSeq, EFFECTIVE_DATE=:effectiveDate, GROUP_CODE=:groupCode, REASON_CODE=:reasonCode , ACTIVE_FLAG=:activeFlag, EXPIRY_DATE=:expiryDate, EXPIRED_BY=:expiredBy, COMMENT_TEXT=:commentText, MODIFY_DATETIME=CURRENT_TIMESTAMP, MODIFY_USER_ID=:modifyUserId, SEAL_FLAG=:sealFlag WHERE OFFENDER_BOOK_ID=:offenderBookId AND STG_SEQ=:stgSeq 
}

OIDMBRAS_OFFENDERSTGASSOCIATIONS_DELETE_OFFENDER_STG_ASSOCIATIONS { 
	DELETE FROM OFFENDER_STG_ASSOCIATIONS WHERE OFFENDER_BOOK_ID=:offenderBookId AND STG_SEQ=:stgSeq
}


OIDMBRAS_OFFENDER_STG_ASSOCIATIONS_PREINSERT {
	select
	coalesce(MAX(STG_SEQ),
	0) + 1
from
	OFFENDER_STG_ASSOCIATIONS
where
	OFFENDER_BOOK_ID = :PBOOKID
order by
	1
}

OIDMBRAS_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
