
OIDMBRVL_FIND_RGACTION {
 	select
	DESCRIPTION NBT_ACTION_CODE ,
	CODE ACTION_CODE
from
	REFERENCE_CODES
where
	domain = 'STG_VAL_ACT'
	and ACTIVE_FLAG = 'Y'
order by
	LIST_SEQ
}

OIDMBRVL_FIND_RGREASON {
 	select
	DESCRIPTION NBT_REASON_CODE ,
	CODE REASON_CODE
from
	REFERENCE_CODES
where
	domain = 'MBR_VAL_RSN'
	and ACTIVE_FLAG = 'Y'
order by
	LIST_SEQ
}

OIDMBRVL_OFFENDERSTGDETAILS_FIND_OFFENDER_STG_DETAILS {
 	SELECT OFFENDER_BOOK_ID ,STG_SEQ ,DETAIL_SEQ ,VAL_DATE ,ACTION_CODE ,CREATE_USER_ID ,CREATE_DATETIME ,REASON_CODE ,COMMENT_TEXT ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_STG_DETAILS  WHERE OFFENDER_BOOK_ID = :offenderBookId AND STG_SEQ = :stgSeq 
}
OIDMBRVL_OFFENDERSTGDETAILS_INSERT_OFFENDER_STG_DETAILS {
insert into OFFENDER_STG_DETAILS(OFFENDER_BOOK_ID , STG_SEQ , DETAIL_SEQ , VAL_DATE , ACTION_CODE , CREATE_USER_ID , CREATE_DATETIME , REASON_CODE , COMMENT_TEXT , MODIFY_DATETIME , modify_user_id , SEAL_FLAG ) values(:offenderBookId , :stgSeq , :detailSeq , :valDate , :actionCode , :createUserId , current_timestamp , :reasonCode , :commentText , null , null , :sealFlag )
}


OIDMBRVL_OFFENDER_STG_DETAILS_PREINSERTPRE_INSERT {
		select
		coalesce(MAX(DETAIL_SEQ),
		0) + 1
	from
		OFFENDER_STG_DETAILS
	where
		OFFENDER_BOOK_ID = :offenderBookId
		and STG_SEQ = :stgSeq
}

OIDMBRVL_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OIDMBRVL_VALIDATE_VAL_DATE {
	SELECT MAX(VAL_DATE) FROM OFFENDER_STG_DETAILS WHERE OFFENDER_BOOK_ID = :offenderBookId AND STG_SEQ = :stgSeq
}

OIDMBRVL_UPDATE_OFFENDER_STG_AFFILIATIONS_APPEAL_DATE {
update OFFENDER_STG_AFFILIATIONS set APPEAL_DATE = :valDate::date + oms_miscellaneous_get_profile_value('CLIENT', 'MBR_APP_DATE')::int, modify_datetime = current_timestamp , modify_user_id = :modifyUserId where OFFENDER_BOOK_ID = :offenderBookId and STG_SEQ = :stgSeq;
}