
OIDSTGCN_FIND_RGNOTETYPE {
 	select
	DESCRIPTION ,
	CODE
from
	REFERENCE_CODES
where
	domain = 'STG_NOTE_TYP'
	and ACTIVE_FLAG = 'Y'
}

OIDSTGCN_FIND_RGNOTEREASON {
select
	DESCRIPTION ,
	CODE
from
	REFERENCE_CODES,
	STG_CASE_NOTES
where
	domain = 'STG_NOTE_RSN'
	and PARENT_CODE = :NOTETYPE
	and ACTIVE_FLAG = 'Y'
}

OIDSTGCN_STGCASENOTES_FIND_STG_CASE_NOTES {
 	SELECT STG_ID,NOTE_SEQ,NOTE_DATE,NOTE_TIME,NOTE_TYPE,NOTE_SUBTYPE,CREATE_USER_ID,TEXT,CREATE_DATETIME,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG FROM STG_CASE_NOTES 
 	where STG_ID = :STG_ID ORDER BY  NOTE_DATE DESC,NOTE_TIME DESC 
}
OIDSTGCN_STGCASENOTES_INSERT_STG_CASE_NOTES {
	insert into STG_CASE_NOTES(STG_ID, NOTE_SEQ, NOTE_DATE, NOTE_TIME, NOTE_TYPE, NOTE_SUBTYPE, CREATE_USER_ID, text, CREATE_DATETIME, MODIFY_DATETIME, SEAL_FLAG) values(:stgId, :noteSeq, :noteDate, :noteTime, :noteType, :noteSubtype, :createUserId, :text, current_timestamp, null , :sealFlag)
}

OIDSTGCN_STGCASENOTES_UPDATE_STG_CASE_NOTES {
update STG_CASE_NOTES set STG_ID = :stgId, NOTE_SEQ = :noteSeq, NOTE_DATE = :noteDate, NOTE_TIME = :noteTime, NOTE_TYPE = :noteType, NOTE_SUBTYPE = :noteSubtype, text = :text, MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId, SEAL_FLAG = :sealFlag where STG_ID =:stgId
}

OIDSTGCN_STGCASENOTES_DELETE_STG_CASE_NOTES { 
	DELETE FROM STG_CASE_NOTES WHERE STG_ID =:stgId AND NOTE_SEQ =:noteSeq
}


OIDSTGCN_STG_CASE_NOTES_PREINSERT_PREINSERT {
	select
	coalesce(MAX(NOTE_SEQ),
	0) + 1
from
	STG_CASE_NOTES
where
	STG_ID =:STGID
order by
	1
}

OIDSTGCN_STG_CASE_NOTES_POSTQUERY_POSTQUERY {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'STG_NOTE_TYP' AND CODE = :note_type
}

OIDSTGCN_STG_CASE_NOTES_POSTQUERY_POSTQUERY {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'STG_NOTE_RSN' AND CODE = :NOTE_SUBTYPE
}

OIDSTGCN_CREATE_FORM_GLOBALS { --Below query is not used in this screen
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
OIDSTGCN_GET_PARENT_CODE {
	SELECT DISTINCT PARENT_CODE  FROM REFERENCE_CODES WHERE DOMAIN = 'STG_NOTE_RSN'
}
