
OIDSTGVL_FIND_RGACTION {
 	SELECT DESCRIPTION , CODE FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_ACT' AND ( ACTIVE_FLAG = 'Y' ) ORDER BY LIST_SEQ
}

OIDSTGVL_FIND_RGDESIGNATION {
 	SELECT DESCRIPTION , CODE FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_DES' AND ( ACTIVE_FLAG = 'Y' ) ORDER BY LIST_SEQ
}

OIDSTGVL_FIND_RGREASON {
 	SELECT DESCRIPTION , CODE FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_RSN' AND ( ACTIVE_FLAG = 'Y' ) ORDER BY LIST_SEQ
}

OIDSTGVL_STGVALIDATIONS_FIND_STG_VALIDATIONS {
 	SELECT STG_ID, VALIDATION_SEQ, VALIDATION_DATE, ACTION, DESIGNATION, REASON, REVIEW_DATE, CREATE_USER_ID, COMMENT_TEXT, CREATE_DATETIME, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM STG_VALIDATIONS WHERE STG_ID = :STGID ORDER BY VALIDATION_DATE DESC
}
OIDSTGVL_STGVALIDATIONS_INSERT_STG_VALIDATIONS {
insert into STG_VALIDATIONS(STG_ID, VALIDATION_SEQ, VALIDATION_DATE, action , DESIGNATION , REASON, REVIEW_DATE, CREATE_USER_ID, COMMENT_TEXT, CREATE_DATETIME, MODIFY_DATETIME, SEAL_FLAG) values(:stgId, :validationSeq, :validationDate, :action, :designation, :reason, :reviewDate, :createUserId, :commentText, CURRENT_TIMESTAMP, null , :sealFlag)	
}


OIDSTGVL_STG_VALIDATIONS_WHENCREATERECORD {
SELECT COALESCE(MAX(VALIDATION_SEQ), 0) + 1 FROM STG_VALIDATIONS WHERE STG_ID = :STGID
}

OIDSTGVL_STG_VALIDATIONS_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_ACT' AND CODE = :ACTION
}

OIDSTGVL_STG_VALIDATIONS_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_DES' AND CODE = :DESIGNATION
}

OIDSTGVL_STG_VALIDATIONS_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_RSN' AND CODE = :REASON
}

OIDSTGVL_OIDSTGVL_KEYCOMMIT {
	SELECT PROFILE_VALUE FROM	SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'STG_VAL_REV'
}

OIDSTGVL_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
OIDSTGVL_MAX_VALIDATION_DATE {
	SELECT MAX(VALIDATION_DATE) FROM STG_VALIDATIONS WHERE STG_ID =  :STGID
}