
OIDSTGIN_AGYINC_FIND_AGENCY_INCIDENTS {
 	SELECT REPORTED_STAFF_ID, AGENCY_INCIDENT_ID, INCIDENT_DATE, INTERNAL_LOCATION_ID, INCIDENT_TIME, INCIDENT_TYPE, INCIDENT_STATUS, CREATE_DATETIME, CREATE_USER_ID, MODIFY_USER_ID, MODIFY_DATETIME, LOCK_FLAG, INCIDENT_DETAILS, REPORT_DATE, REPORT_TIME, AGY_LOC_ID, LEVEL_CODE, LOG_NO, INCIDENT_TEXT, SEAL_FLAG FROM AGENCY_INCIDENTS
}
OIDSTGIN_AGENCYINCIDENTPARTIES_FIND_AGENCY_INCIDENT_PARTIES {
SELECT ai.AGENCY_INCIDENT_ID, ai.PARTY_SEQ, ai.INCIDENT_ROLE, ai.OFFENDER_BOOK_ID, ai.STAFF_ID, ai.PERSON_ID, ai.DISPOSITION_TYPE, ai.DISPOSITION_DATE, ai.OIC_INCIDENT_ID, ai.COMMENT_TEXT, ai.CREATE_DATETIME, ai.CREATE_USER_ID, ai.ACTION_CODE, ai.PARTY_ADDED_DATE, ai.MODIFY_DATETIME, ai.MODIFY_USER_ID, ai.SEAL_FLAG FROM agency_incident_parties ai 
WHERE OFFENDER_BOOK_ID IS NOT NULL AND AGENCY_INCIDENT_ID = :AGENCYINCIDENTID
}

OIDSTGIN_AGENCYINCIDENTPARTIES_FIND_STG_IDS{
select aip.agency_incident_id  from agency_incident_parties aip, offender_stg_affiliations osa  where aip.offender_book_id = :OFFENDERBOOKID  and osa.stg_id = :STGID
   	  OR agency_incident_id in (select agency_incident_id 
   	   from AGENCY_INCIDENT_ASSO_TOSTG  where stg_id =:STGID)
}


OIDSTGIN_AGENCY_INCIDENT_PARTIES_POSTQUERY_OFFENDERS{
	SELECT O.OFFENDER_ID_DISPLAY, O.LAST_NAME||', '||O.FIRST_NAME LAST_NAME FROM OFFENDERS O, OFFENDER_BOOKINGS OFF_BKG WHERE O.OFFENDER_ID = OFF_BKG.OFFENDER_ID AND OFF_BKG.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OIDSTGIN_AGENCY_INCIDENT_PARTIES_POSTQUERY_INCIDENTROLE {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'INC_OFF_PAR' AND CODE = :INCIDENTROLE
}

OIDSTGIN_AGENCY_INCIDENT_PARTIES_POSTQUERY_ACTIONCODE {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'INC_DECISION' AND CODE = :ACTIONCODE
}

OIDSTGIN_AGENCY_INCIDENT_PARTIES_POSTQUERY_DESCRIPTION {
	SELECT DESCRIPTION FROM SECURITY_THREAT_GROUPS WHERE STG_ID = :STGID
}

OIDSTGIN_AGENCY_INCIDENT_PARTIES_POSTQUERY_OFF_CUR {
	SELECT STG_ID FROM OFFENDER_STG_AFFILIATIONS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND ACTIVE_FLAG = 'Y' AND STG_ID = :STGID
}

OIDSTGIN_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OIDSTGIN_POPULATE_INCIDENT_LOCATIONS_POPULATE_INCIDENT_LOCATIONS {
	SELECT INTERNAL_LOCATION_TYPE, DESCRIPTION INTO LV_TYPE, :AGY_INC.NBT_LEVEL-- LV_DESC FROM AGENCY_INTERNAL_LOCATIONS WHERE INTERNAL_LOCATION_ID = :AGY_INC.INTERNAL_LOCATION_ID
}

OIDSTGIN_POPULATE_LOG_NOPOPULATE_LOG_NO {
	SELECT PROFILE_VALUE INTO LV_FORMATE_LOG_NO FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'INC_NUMBER'
}

OIDSTGIN_POPULATE_STG_GROUP_ {
	SELECT STG_DESC FROM V_STG_SET WHERE STG_ID = P_STG_ID
}

OIDSTGIN_POPULATE_STG_GROUP_ {
	SELECT STG_DESC FROM V_STG_GANG_SET WHERE STG_ID = P_STG_ID
}

OIDSTGIN_POPULATE_STG_GROUP_ {
	SELECT STG_DESC FROM V_STG_GROUP WHERE STG_ID = P_STG_ID
}

OIDSTGIN_POPULATE_STG_GROUP_ {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_CODE = 'STG_LOV_LVL' AND   PROFILE_TYPE = 'CLIENT'
}

OIDSTGIN_POPULATE_STAFF_POPULATE_STAFF {
	SELECT STAFF.LAST_NAME||', '||STAFF.FIRST_NAME INTO :AGY_INC.NBT_STAFF FROM   STAFF_MEMBERS STAFF WHERE  STAFF.STAFF_ID = :AGY_INC.STAFF_ID AND SUSPENDED_FLAG ='N' AND TERMINATION_DATE IS NULL
}
OIDSTGIN_TAG_ESTABLISHMENT {
	select
	tag_establishment_get_agy_loc_desc(:AGYLOCID)
from
	DUAL
}
OIDSTGIN_AGENCY_INTERNAL_LOCATIONS {
	SELECT INTERNAL_LOCATION_TYPE, DESCRIPTION FROM AGENCY_INTERNAL_LOCATIONS WHERE INTERNAL_LOCATION_ID = :INTERNALLOCATIONID
}
OIDSTGIN_STAFF_MEMBERS {
	SELECT STAFF.LAST_NAME||', '||STAFF.FIRST_NAME FROM STAFF_MEMBERS STAFF WHERE  STAFF.STAFF_ID = :STAFFID AND SUSPENDED_FLAG ='N'
        AND TERMINATION_DATE IS NULL
}
OIDSTGIN_GET_DESCRIPTION {
	SELECT DESCRIPTION FROM SECURITY_THREAT_GROUPS WHERE STG_ID = :STGID
}
OIDSTGIN_GET_LOCATION {
	SELECT INTERNAL_LOCATION_TYPE, DESCRIPTION FROM AGENCY_INTERNAL_LOCATIONS WHERE INTERNAL_LOCATION_ID = :INTERNALLOCATIONID
}
OIDSTGIN_GET_STG_ID {
	SELECT STG_ID FROM OFFENDER_STG_AFFILIATIONS WHERE OFFENDER_BOOK_ID = :OFFBOOKID AND ACTIVE_FLAG = 'Y' AND STG_ID = :STGID
}
OIDSTGIN_GET_BOOKING_NO {
	SELECT BOOKING_NO FROM V_HEADER_BLOCK_FN(:USERID) V_HEADER_BLOCK  WHERE OFFENDER_BOOK_ID = :ofenderIdDisplay 
}
OIDSTGIN_GET_STG_ID_ELSE_CONDITION {
	SELECT O.STG_ID FROM OFFENDER_STG_AFFILIATIONS O
    WHERE O.STG_SEQ IN (SELECT MAX(A.STG_SEQ)
                        FROM OFFENDER_STG_AFFILIATIONS A
                        WHERE A.OFFENDER_BOOK_ID = :OFFENDERBOOKID
      										AND O.ACTIVE_FLAG = 'Y')
      AND O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}