
OIDSTGHL_FIND_RECCITY {
 SELECT ALL REFERENCE_CODES.CODE ,  REFERENCE_CODES.DESCRIPTION , REFERENCE_CODES.LIST_SEQ FROM REFERENCE_CODES  WHERE REFERENCE_CODES.DOMAIN = 'CITY' AND (REFERENCE_CODES.ACTIVE_FLAG = 'Y' ) ORDER BY REFERENCE_CODES.LIST_SEQ , REFERENCE_CODES.DESCRIPTION
}

OIDSTGHL_FIND_RECSTATE {
select
	all REFERENCE_CODES.CODE ,
	REFERENCE_CODES.DESCRIPTION ,
	REFERENCE_CODES.LIST_SEQ
from
	REFERENCE_CODES
where
	REFERENCE_CODES.DOMAIN = 'PROV_STATE'
	and (REFERENCE_CODES.ACTIVE_FLAG = 'Y')
order by
	REFERENCE_CODES.LIST_SEQ ,
	REFERENCE_CODES.DESCRIPTION

}

OIDSTGHL_FIND_RECCOUNTRY {
select
	all REFERENCE_CODES.CODE ,
	REFERENCE_CODES.DESCRIPTION ,
	REFERENCE_CODES.LIST_SEQ
from
	REFERENCE_CODES
where
	REFERENCE_CODES.DOMAIN = 'COUNTRY'
	and (REFERENCE_CODES.ACTIVE_FLAG = 'Y')
order by
	REFERENCE_CODES.LIST_SEQ ,
	REFERENCE_CODES.DESCRIPTION

}

OIDSTGHL_STG_FIND_SECURITY_THREAT_GROUPS {
 	SELECT STG_ID, STG_LEVEL, STG_CODE, DESCRIPTION, PARENT_STG_ID, LIST_SEQ, EFFECTIVE_DATE, HISTORY_TEXT, ACTIVE_FLAG, CREATE_USER_ID, CREATE_DATETIME, MODIFY_USER_ID, MODIFY_DATETIME, EXPIRY_DATE, SEAL_FLAG FROM SECURITY_THREAT_GROUPS 
}
OIDSTGHL_STG_INSERT_SECURITY_THREAT_GROUPS {
	INSERT INTO SECURITY_THREAT_GROUPS(create_user_id, create_datetime, modify_datetime) VALUES(:createUserId , current_timestamp , null )
}

OIDSTGHL_STG_UPDATE_SECURITY_THREAT_GROUPS {
	UPDATE SECURITY_THREAT_GROUPS set HISTORY_TEXT=:historyText,MODIFY_DATETIME=CURRENT_TIMESTAMP,MODIFY_USER_ID=:modifyUserId WHERE STG_ID=:stgId
}

OIDSTGHL_STG_DELETE_SECURITY_THREAT_GROUPS { 
	DELETE FROM SECURITY_THREAT_GROUPS/* where */
}

OIDSTGHL_STGLOCATIONS_FIND_STG_LOCATIONS {
 	SELECT STG_ID,LOCATION_SEQ,CITY_CODE,PROV_STATE,COUNTRY,COMMENT_TEXT,CREATE_USER_ID,CREATE_DATETIME,MODIFY_DATETIME,MODIFY_USER_ID,SEAL_FLAG   FROM STG_LOCATIONS  WHERE STG_ID=:STGID ORDER BY COUNTRY, PROV_STATE, CITY_CODE
 	}
OIDSTGHL_STGLOCATIONS_INSERT_STG_LOCATIONS {
insert into STG_LOCATIONS(STG_ID, LOCATION_SEQ, CITY_CODE, PROV_STATE, COUNTRY, COMMENT_TEXT, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME, SEAL_FLAG) values(:stgId, :locationSeq, :cityCode, :provState, :country, :commentText, :createUserId, CURRENT_TIMESTAMP, null , :sealFlag)
}

OIDSTGHL_STGLOCATIONS_UPDATE_STG_LOCATIONS {
	UPDATE STG_LOCATIONS set STG_ID=:stgId, LOCATION_SEQ=:locationSeq, CITY_CODE=:cityCode, PROV_STATE=:provState, COUNTRY=:country, COMMENT_TEXT=:commentText,MODIFY_DATETIME=CURRENT_TIMESTAMP, MODIFY_USER_ID=:modifyUserId, SEAL_FLAG=:sealFlag WHERE STG_ID=:stgId AND LOCATION_SEQ=:locationSeq 
}

OIDSTGHL_STGLOCATIONS_DELETE_STG_LOCATIONS { 
	DELETE FROM STG_LOCATIONS WHERE STG_ID=:stgId AND LOCATION_SEQ=:locationSeq
}


OIDSTGHL_STG_ONCHECKDELETEMASTER {
	SELECT * FROM STG_LOCATIONS S WHERE S.STG_ID = :STGID
}

OIDSTGHL_STG_PREINSERT_ {
	SELECT STG_LEVEL,STG_CODE, DESCRIPTION,EFFECTIVE_DATE, ACTIVE_FLAG,CREATE_USER_ID, CREATE_DATETIME FROM  SECURITY_THREAT_GROUPS WHERE STG_ID = :STGID
}

OIDSTGHL_STG_LOCATIONS_PREINSERT {
	SELECT MAX(coalesce (LOCATION_SEQ, 0)) FROM STG_LOCATIONS WHERE STG_ID = :STGID
}

OIDSTGHL_STG_LOCATIONS_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'CITY' AND CODE = :CITYCODE
}

OIDSTGHL_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OIDSTGHL_CGWHEN_NEW_FORM_INSTANCE {
	SELECT ROLE_ID FROM STAFF_MEMBER_ROLES WHERE STAFF_ID IN (SELECT STAFF_ID FROM STAFF_MEMBERS WHERE USER_ID =:USER_NAME)
}
OIDSTGHL_GET_PROFILE_VALUE {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'STG_ADMIN'
}
