
OIDSTGID_FIND_RGPROFILETYPE {
select
	PT.PROFILE_TYPE CODE ,
	PT.DESCRIPTION,
	PT.PROFILE_TYPE
from
	PROFILE_TYPES PT
where
	PT.PROFILE_CATEGORY = 'STG'
	and 
		PT.ACTIVE_FLAG = 'Y'
order by
	LIST_SEQ
}

OIDSTGID_STGIDENTIFIERS_FIND_STG_IDENTIFIERS {
 	SELECT STG_ID, IDENTIFIER_SEQ, PROFILE_TYPE, DETAIL, CREATE_USER_ID, CREATE_DATETIME, IMAGE_DATA, IMAGE_SIZE, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG  FROM STG_IDENTIFIERS WHERE STG_ID = :STGID
}
OIDSTGID_STGIDENTIFIERS_INSERT_STG_IDENTIFIERS {
insert into STG_IDENTIFIERS(STG_ID, IDENTIFIER_SEQ, PROFILE_TYPE, DETAIL, CREATE_USER_ID, CREATE_DATETIME, IMAGE_DATA, IMAGE_SIZE, MODIFY_DATETIME, SEAL_FLAG) values(:stgId, :identifierSeq, :profileType, :detail, :createUserId, current_timestamp, :imageData, :imageSize, null , :sealFlag)
}

OIDSTGID_STGIDENTIFIERS_UPDATE_STG_IDENTIFIERS {
update STG_IDENTIFIERS set STG_ID =:stgId, IDENTIFIER_SEQ =:identifierSeq, PROFILE_TYPE =:profileType, DETAIL =:detail, IMAGE_DATA =:imageData, IMAGE_SIZE =:imageSize, MODIFY_DATETIME = current_timestamp, MODIFY_USER_ID =:modifyUserId, SEAL_FLAG =:sealFlag where STG_ID =:stgId and IDENTIFIER_SEQ =:identifierSeq
}

OIDSTGID_STGIDENTIFIERS_DELETE_STG_IDENTIFIERS { 
	DELETE  FROM STG_IDENTIFIERS where STG_ID= :stgId and IDENTIFIER_SEQ = :identifierSeq
}

OIDSTGID_IMAGE1_FIND_IMAGES {
 	SELECT *  FROM IMAGES WHERE IMAGE_OBJECT_TYPE = 'STG' AND IMAGE_OBJECT_ID  = :STGID AND IMAGE_OBJECT_SEQ = :IDENTIFIERSEQ AND ACTIVE_FLAG  = 'Y'
}
OIDSTGID_IMAGE1_INSERT_IMAGES {
insert into IMAGES(IMAGE_ID, CAPTURE_DATE, IMAGE_OBJECT_TYPE, IMAGE_OBJECT_ID, IMAGE_OBJECT_SEQ, IMAGE_VIEW_TYPE, IMAGE_THUMBNAIL , create_user_id , create_datetime , ) values(:imageId, :captureDate, :imageObjectType, :imageObjectId, :imageObjectSeq, :imageViewType, :imageThumbnail , :createUserId , current_timestamp )
}

OIDSTGID_IMAGE1_DELETE_IMAGES { 
	DELETE FROM IMAGES/* where */
}

OIDSTGID_STGIDENTIFYINGWORDS_FIND_STG_IDENTIFYING_WORDS {
 	SELECT STG_ID, WORD_SEQ, CODE, DESCRIPTION, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM STG_IDENTIFYING_WORDS where STG_ID =:STGID   order by WORD_SEQ
}
OIDSTGID_STGIDENTIFYINGWORDS_INSERT_STG_IDENTIFYING_WORDS {
insert into STG_IDENTIFYING_WORDS(STG_ID, WORD_SEQ, CODE, DESCRIPTION, CREATE_USER_ID, CREATE_DATETIME, MODIFY_DATETIME, SEAL_FLAG) values(:stgId, :wordSeq, :code, :description, :createUserId, current_timestamp, null , :sealFlag)
}

OIDSTGID_STGIDENTIFYINGWORDS_UPDATE_STG_IDENTIFYING_WORDS {
update STG_IDENTIFYING_WORDS set CODE =:code, DESCRIPTION =:description, modify_datetime =current_timestamp, modify_user_id =:modifyUserId where STG_ID =:stgId and WORD_SEQ =:wordSeq
}

OIDSTGID_STGIDENTIFYINGWORDS_DELETE_STG_IDENTIFYING_WORDS { 
	DELETE FROM STG_IDENTIFYING_WORDS where STG_ID=:stgId and WORD_SEQ=:wordSeq
}


OIDSTGID_STG_IDENTIFIERS_PREINSERT {
	select
	coalesce(MAX(IDENTIFIER_SEQ + 1),
	1)
from
	STG_IDENTIFIERS
where
	STG_ID = :STGID
}

OIDSTGID_STG_IDENTIFIERS_POSTQUERY_ {
	SELECT DESCRIPTION FROM PROFILE_TYPES WHERE PROFILE_TYPE = :profileType
}

OIDSTGID_STG_IDENTIFIERS_POSTQUERY_ {
	SELECT COUNT(0) FROM IMAGES WHERE IMAGE_OBJECT_ID = :stgId AND IMAGE_OBJECT_SEQ  = :identifierSeq AND IMAGE_OBJECT_TYPE = 'STG'
}

OIDSTGID_STG_IDENTIFIERS_KEYDELREC_ {
	SELECT COUNT(0) FROM IMAGES WHERE IMAGE_OBJECT_ID = :stgId AND IMAGE_OBJECT_SEQ  = :identifierSeq  AND IMAGE_OBJECT_TYPE = 'STG'
}

OIDSTGID_IMAGE1_PREINSERT_ {
	select
	NEXTVAL('IMAGE_ID')
from
	DUAL;
}

OIDSTGID_STG_IDENTIFYING_WORDS_PREINSERT{
	select
	coalesce(MAX(WORD_SEQ + 1),
	1)
from
	STG_IDENTIFYING_WORDS
where
	STG_ID = :STGID
}

OIDSTGID_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
OIDSTGID_GET_GLOBAL_STG_DESCRIPTION {
	SELECT ST1.DESCRIPTION FROM SECURITY_THREAT_GROUPS ST1  WHERE ST1.STG_ID = :stgId
}

OIDSTGID_FIND_STG_INDENTIFIERS_DATA_ONE{
select
			*
	from
			STG_IDENTIFIERS SI
	where
			SI.PROFILE_TYPE = :PROFILE_TYPE
		and SI.STG_ID = :STGID
}
