
OIISTGMI_VSTGMEMBERSHIPINQUIRY_FIND_V_STG_MEMBERSHIP_INQUIRY {
 	SELECT * FROM V_STG_MEMBERSHIP_INQUIRY V_STG_MEMBERSHIP_INQUIRY 
 	WHERE V_STG_MEMBERSHIP_INQUIRY.STG_AFF_ACTIVE_FLAG = 'Y' AND STG_ID = :STG_ID AND
  V_STG_MEMBERSHIP_INQUIRY.OFFENDER_BOOK_ID = (SELECT MAX(OFFENDER_BOOK_ID)  FROM OFFENDER_BOOKINGS OB  WHERE V_STG_MEMBERSHIP_INQUIRY.ROOT_OFFENDER_ID = OB.ROOT_OFFENDER_ID)
}

OIISTGMI_OIISTGMI_WHENNEWFORMINSTANCE {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_CODE = 'OFF_ID_CODE'
}

OIISTGMI_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}

OIISTGMI_POPULATE_STG_GROUP {
	SELECT STG_DESC FROM V_STG_SET WHERE STG_ID = :STGID
}

OIISTGMI_GET_STG_GROUP_DESCRIPTION {
	select
	case
		when coalesce(STG3.DESCRIPTION::text, '') = '' then null
		else STG3.DESCRIPTION || '-'
	end ||
	case
		when coalesce(STG2.DESCRIPTION::text, '') = '' then null
		else STG2.DESCRIPTION || '-'
	end || STG1.DESCRIPTION DESCRIPTION
from
	SECURITY_THREAT_GROUPS STG1,
	SECURITY_THREAT_GROUPS STG2,
	SECURITY_THREAT_GROUPS STG3
where
	STG1.STG_ID = :STGID
	and STG1.STG_LEVEL = 'SET'
	and STG1.ACTIVE_FLAG = 'Y'
	and STG1.PARENT_STG_ID = STG2.STG_ID
	and STG2.PARENT_STG_ID = STG3.STG_ID
union
 select
	case
		when coalesce(STG2.DESCRIPTION::text, '') = '' then null
		else STG2.DESCRIPTION || '-'
	end || STG1.DESCRIPTION
from
	SECURITY_THREAT_GROUPS STG1,
	SECURITY_THREAT_GROUPS STG2
where
	STG1.STG_ID = :STGID
	and STG1.STG_LEVEL = 'GANG'
	and STG1.ACTIVE_FLAG = 'Y'
	and STG1.PARENT_STG_ID = STG2.STG_ID
union
 select
	DESCRIPTION
from
	SECURITY_THREAT_GROUPS
where
	STG_ID = :STGID
	and STG_LEVEL = 'NATION'
	and ACTIVE_FLAG = 'Y';
}
OIISTGMI_FIND_V_STG_MEMBERSHIP_INQUIRY {
 	SELECT * FROM V_STG_MEMBERSHIP_INQUIRY V_STG_MEMBERSHIP_INQUIRY  
  
}