
OIITGDET_FIND_RGSTG2 {
 	SELECT ST1.DESCRIPTION , ST1.STG_ID STG_ID ,ST1.STG_CODE FROM SECURITY_THREAT_GROUPS ST1 WHERE ST1.STG_LEVEL = 'GANG' AND ST1.ACTIVE_FLAG = 'Y' UNION SELECT ST2.DESCRIPTION||'-'||ST1.DESCRIPTION , ST1.STG_ID STG_ID ,ST1.STG_CODE FROM SECURITY_THREAT_GROUPS ST1 , SECURITY_THREAT_GROUPS ST2  WHERE ST1.STG_LEVEL = 'SET' AND ST1.ACTIVE_FLAG = 'Y' AND ST1.PARENT_STG_ID = ST2.STG_ID
}

OIITGDET_FIND_RGSTG1 {
 	SELECT ST1.DESCRIPTION , ST1.STG_ID STG_ID ,ST1.STG_CODE FROM SECURITY_THREAT_GROUPS ST1  WHERE ST1.STG_LEVEL = 'SET' AND ST1.ACTIVE_FLAG = 'Y'
}

OIITGDET_FIND_RGSTG3 {
 	SELECT DESCRIPTION , STG_ID , STG_CODE FROM SECURITY_THREAT_GROUPS WHERE STG_LEVEL = 'NATION' AND ACTIVE_FLAG = 'Y' UNION SELECT STG2.DESCRIPTION||'-'||STG1.DESCRIPTION DESCRIPTION , STG1.STG_ID STG_ID , STG1.STG_CODE FROM SECURITY_THREAT_GROUPS STG1 , SECURITY_THREAT_GROUPS STG2 WHERE STG1.STG_LEVEL = 'GANG' AND STG1.ACTIVE_FLAG = 'Y' AND STG1.PARENT_STG_ID = STG2.STG_ID UNION SELECT STG3.DESCRIPTION||'-'||STG2.DESCRIPTION||'-'||STG1.DESCRIPTION DESCRIPTION , STG1.STG_ID STG_ID , STG1.STG_CODE FROM SECURITY_THREAT_GROUPS STG1 , SECURITY_THREAT_GROUPS STG2 , SECURITY_THREAT_GROUPS STG3  WHERE STG1.STG_LEVEL = 'SET' AND STG1.ACTIVE_FLAG = 'Y' AND STG1.PARENT_STG_ID = STG2.STG_ID AND STG2.PARENT_STG_ID = STG3.STG_ID  /* SELECT ST1.DESCRIPTION STG_DESC , ST1.STG_ID STG_ID FROM SECURITY_THREAT_GROUPS ST1 WHERE ST1.STG_LEVEL = 'NATION' AND ST1.ACTIVE_FLAG = 'Y' UNION SELECT ST2.DESCRIPTION||'-'||ST1.DESCRIPTION STG_DESC , ST1.STG_ID STG_ID FROM SECURITY_THREAT_GROUPS ST1 , SECURITY_THREAT_GROUPS ST2 WHERE ST1.STG_LEVEL = 'GANG' AND ST1.ACTIVE_FLAG = 'Y' AND ST1.PARENT_STG_ID = ST2.STG_ID UNION SELECT ST3.DESCRIPTION||'-'||ST2.DESCRIPTION||'-'||ST1.DESCRIPTION STG_DESC , ST1.STG_ID STG_ID FROM SECURITY_THREAT_GROUPS ST1 , SECURITY_THREAT_GROUPS ST2 , SECURITY_THREAT_GROUPS ST3  WHERE ST1.STG_LEVEL = 'SET' AND ST1.ACTIVE_FLAG = 'Y' AND ST1.PARENT_STG_ID = ST2.STG_ID AND ST2.PARENT_STG_ID = ST3.STG_ID */
}

OIITGDET_STGVALIDATIONS_FIND_STG_VALIDATIONS {
 	SELECT * FROM STG_VALIDATIONS WHERE stg_id = :stgId AND validation_date = (select max(validation_date) from stg_validations where stg_id = :stgId) ORDER BY VALIDATION_SEQ desc
}
OIITGDET_STGRACEMAKEUP_FIND_V_STG_RACIAL_MAKEUP {
 	SELECT *  FROM V_STG_RACIAL_MAKEUP  WHERE  STG_ID = :stgId ORDER BY RACE_DESCRIPTION
}
OIITGDET_STGLOCATIONPRESENCE_FIND_V_STG_LOCATION_PRESENCE {
 	SELECT SLP.STG_ID, SLP.AGY_LOC_ID, SLP.LOCATION_DESCRIPTION, 
(SELECT COUNT(*) FROM V_STG_LOCATION_MEMBERS WHERE AGY_LOC_ID = SLP.AGY_LOC_ID AND STG_ID = SLP.STG_ID) LOCATION_COUNT 
FROM V_STG_LOCATION_PRESENCE SLP  WHERE  SLP.STG_ID = :stgId ORDER BY SLP.LOCATION_DESCRIPTION  
}
OIITGDET_FAF_FIND_FORM_ACCESSIBLE_FORMS {
 	 	select
	*
from
	FORM_ACCESSIBLE_FORMS
where
	ORIGINATING_FORM = 'OIITGDET'
	and DESTINATION_FORM in (
	select
		MODULE_NAME
	from
		MODULE_PRIVILEGES
	where
		ROLE_ID in (
		select
			ROLE_ID
		from
			STAFF_MEMBER_ROLES
		where
			STAFF_ID = (
			select
				STAFF_ID
			from
				STAFF_MEMBERS
			where
				USER_ID =:USER_NAME)))
order by
	LIST_SEQ asc
}

OIITGDET_STG_DETAIL_KEYEXEQRY_MEMBER {
	SELECT COUNT(*) FROM OFFENDER_BOOKINGS OB, OFFENDER_STG_AFFILIATIONS OSA WHERE OSA.STG_ID = :StgId AND OSA.ACTIVE_FLAG = 'Y' AND OSA.OFFENDER_BOOK_ID = OB.OFFENDER_BOOK_ID AND OB.ACTIVE_FLAG = 'Y'
}

OIITGDET_STG_DETAIL_KEYEXEQRY_VALIDATED {
	SELECT COUNT(*) FROM OFFENDER_BOOKINGS OB, OFFENDER_STG_AFFILIATIONS OSA, OFFENDER_STG_DETAILS OSD WHERE OSA.STG_ID = :StgId AND OSA.ACTIVE_FLAG = 'Y' AND OSA.OFFENDER_BOOK_ID = OB.OFFENDER_BOOK_ID AND OB.ACTIVE_FLAG = 'Y' AND OSD.OFFENDER_BOOK_ID = OSA.OFFENDER_BOOK_ID AND OSD.STG_SEQ = OSA.STG_SEQ AND OSD.DETAIL_SEQ = (SELECT MAX(DETAIL_SEQ) FROM OFFENDER_STG_DETAILS WHERE OFFENDER_BOOK_ID = OSA.OFFENDER_BOOK_ID AND STG_SEQ = OSA.STG_SEQ) AND OSD.ACTION_CODE = 'VALIDATE'
}

OIITGDET_STG_VALIDATIONS_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_ACT' AND CODE = :ACTION
}

OIITGDET_STG_VALIDATIONS_POSTQUERY_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'STG_VAL_DES' AND CODE = :DESIGNATION
}

OIITGDET_FAF_POSTQUERY_DESCRIPTION {
	SELECT OMS_MOD.DESCRIPTION FROM   OMS_MODULES OMS_MOD WHERE  OMS_MOD.MODULE_NAME = :DESTINATIONFORM
}

OIITGDET_FAF_POSTQUERY_VALID_DATA_CUR {
	SELECT count(0) FROM AGENCY_INCIDENTS ai WHERE ai.incident_type = 'STG' AND EXISTS (SELECT aip.agency_incident_id  FROM agency_incident_parties aip, offender_stg_affiliations osa
      WHERE aip.offender_book_id = osa.offender_book_id AND osa.stg_id = :stgId AND aip.agency_incident_id = ai.agency_incident_id)
 }

OIITGDET_FAF_POSTQUERY_VALID_DATA_CUR_TWO {
	SELECT COUNT(*) FROM AGENCY_INCIDENT_ASSO_TOSTG WHERE STG_ID = :stgId
}

OIITGDET_FAF_POSTQUERY_VALID_IWP_CUR {
	select
	COUNT(*)
from
	IWP_TEMPLATES IT,
	IWP_TEMPLATE_MODULES ITM,
	IWP_DOCUMENTS IWPD
where
	IT.TEMPLATE_ID = ITM.TEMPLATE_ID
	and IT.TEMPLATE_ID = IWPD.TEMPLATE_ID
	and ITM.MODULE_NAME = 'OIITGDET'
	and IWPD.OBJECT_TYPE = 'OIITGDET'
	and IWPD.OBJECT_ID=:stgId::text
	}

OIITGDET_OIITGDET_WHENNEWFORMINSTANCE {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_CODE = 'STG_LOV_LVL' AND   PROFILE_TYPE = 'CLIENT'
}

OIITGDET_OIITGDET_WHENNEWFORMINSTANCE_STG_DESCRIPTION_CUR2 {
	select
	case
		when :lvGroup = '1' then 'RG_STG1'
		when :lvGroup = '2' then 'RG_STG2'
		when :lvGroup = '3' then 'RG_STG3'
		else 'RG_STG3'
	end from dual
}

OIITGDET_OIITGDET_WHENNEWFORMINSTANCE_ {
select
	ST1.STG_CODE,
	case
		when coalesce(ST3.DESCRIPTION::text, '') = '' then null
		else ST3.DESCRIPTION || '-'
	end
	|| case
		when coalesce(ST2.DESCRIPTION::text, '') = '' then null
		else ST2.DESCRIPTION || '-'
	end || ST1.DESCRIPTION STG_DESC
from
	security_threat_groups st1
left outer join security_threat_groups st2 on
	(ST1.PARENT_STG_ID = ST2.STG_ID)
left outer join security_threat_groups st3 on
	(ST2.PARENT_STG_ID = ST3.STG_ID)
where
	ST1.STG_ID = :STGID
	and ST1.ACTIVE_FLAG = 'Y'

}

OIITGDET_OIITGDET_WHENNEWFORMINSTANCE_ {
	select
	ST1.STG_CODE,
	case
		when coalesce(ST2.DESCRIPTION::text, '') = '' then null
		else ST2.DESCRIPTION || '-'
	end || ST1.DESCRIPTION STG_DESC
from
	security_threat_groups st1
left outer join security_threat_groups st2 on
	(ST1.PARENT_STG_ID = ST2.STG_ID
		and 'GANG' = ST2.STG_LEVEL)
where
	ST1.STG_ID = :STGID
	and ST1.ACTIVE_FLAG = 'Y'

}

OIITGDET_OIITGDET_WHENNEWFORMINSTANCE_ {
	SELECT ST1.STG_CODE,ST1.DESCRIPTION STG_DESC FROM SECURITY_THREAT_GROUPS ST1 WHERE ST1.STG_ID = :STGID AND ST1.ACTIVE_FLAG = 'Y'
}

OIITGDET_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
OIITGDET_PRIMARY_CUR {
	select 'x' from OMS_OWNER.SECURITY_THREAT_GROUPS where STG_ID = :stgId
}
OIITGDET_GET_PROFILE_VALUE {
	select
	oms_miscellaneous_get_profile_value(:profileType,
	:profileCode) FLAG
from
	dual
}
OIITGDET_GET_GROUP_PRIVILEGE {
	select
	TAG_SECURITY_GET_GROUP_PRIVILEGE_u('OIITGDET',:username)
from
	DUAL
}
