
OIMTGNGS_SECGRP_FIND_SECURITY_THREAT_GROUPS {
 	SELECT *  FROM SECURITY_THREAT_GROUPS
}
OIMTGNGS_SECGRP_INSERT_SECURITY_THREAT_GROUPS {
	 insert into SECURITY_THREAT_GROUPS(STG_ID, STG_LEVEL, STG_CODE, DESCRIPTION, PARENT_STG_ID, LIST_SEQ, EFFECTIVE_DATE, HISTORY_TEXT, ACTIVE_FLAG, CREATE_USER_ID, CREATE_DATETIME, modify_datetime, EXPIRY_DATE, SEAL_FLAG) values(:stgId, :stgLevel, :stgCode, :description, :parentStgId, :listSeq, :effectiveDate, :historyText, :activeFlag, :createUserId, current_timestamp, null, :expiryDate, :sealFlag)
}

OIMTGNGS_SECGRP_UPDATE_SECURITY_THREAT_GROUPS {
	update SECURITY_THREAT_GROUPS set STG_LEVEL =:stgLevel, STG_CODE =:stgCode, DESCRIPTION =:description, LIST_SEQ =:listSeq, EFFECTIVE_DATE =:effectiveDate, HISTORY_TEXT =:historyText, ACTIVE_FLAG =:activeFlag, MODIFY_USER_ID =:modifyUserId, MODIFY_DATETIME = current_timestamp, EXPIRY_DATE =:expiryDate, SEAL_FLAG =:sealFlag where STG_ID =:stgId
}

OIMTGNGS_SECGRP1_FIND_SECURITY_THREAT_GROUPS {
 	SELECT *  FROM SECURITY_THREAT_GROUPS   WHERE PARENT_STG_ID =:parentStgId ORDER BY LIST_SEQ, STG_CODE
}
OIMTGNGS_SECGRP2EXECUTEQUERY {
SELECT *  FROM SECURITY_THREAT_GROUPS   WHERE PARENT_STG_ID =:parentStgId ORDER BY LIST_SEQ, STG_CODE
}
OIMTGNGS_SECGRP1_INSERT_SECURITY_THREAT_GROUPS {
	insert into SECURITY_THREAT_GROUPS(STG_ID, STG_LEVEL, STG_CODE, DESCRIPTION, PARENT_STG_ID, LIST_SEQ, EFFECTIVE_DATE, HISTORY_TEXT, ACTIVE_FLAG, CREATE_USER_ID, CREATE_DATETIME, modify_datetime, EXPIRY_DATE, SEAL_FLAG) values(:stgId, :stgLevel, :stgCode, :description, :parentStgId, :listSeq, :effectiveDate, :historyText, :activeFlag, :createUserId, current_timestamp, null , :expiryDate, :sealFlag)
}

OIMTGNGS_SECGRP1_UPDATE_SECURITY_THREAT_GROUPS {
	UPDATE SECURITY_THREAT_GROUPS set 
}


OIMTGNGS_SEC_GRP_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM SECURITY_THREAT_GROUPS S WHERE S.PARENT_STG_ID = :STGID
}

OIMTGNGS_SEC_GRP_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM SECURITY_THREAT_GROUPS S WHERE S.PARENT_STG_ID = :STGID
}

OIMTGNGS_SEC_GRP_PREINSERT {
	SELECT STG_ID.NEXTVAL INTO LV_STG_ID FROM DUAL
}

OIMTGNGS_SEC_GRP_WHENNEWRECORDINSTANCEWHEN-NEW-RECORD-INSTANCE {
	SELECT COUNT(*) FROM SECURITY_THREAT_GROUPS WHERE PARENT_STG_ID = :STGID
}

OIMTGNGS_SEC_GRP_WHENNEWRECORDINSTANCEWHEN-NEW-RECORD-INSTANCE {
	SELECT COUNT(*) FROM SECURITY_THREAT_GROUPS WHERE PARENT_STG_ID = :STGID
}

OIMTGNGS_SEC_GRP1_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM SECURITY_THREAT_GROUPS S WHERE S.PARENT_STG_ID = :STGID
}

OIMTGNGS_SEC_GRP1_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM SECURITY_THREAT_GROUPS S WHERE S.PARENT_STG_ID = :STGID
}

OIMTGNGS_SEC_GRP1_PREINSERT {
	 SELECT STG_ID.NEXTVAL INTO LV_STG_ID FROM DUAL
}

OIMTGNGS_SEC_GRP1_WHENNEWRECORDINSTANCE {
	 SELECT COUNT(*) FROM SECURITY_THREAT_GROUPS WHERE PARENT_STG_ID = :STGID
}

OIMTGNGS_SEC_GRP2_PREINSERT {
	 select NEXTVAL('STG_ID')

}

OIMTGNGS_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
OIMTGNGS_GETNEXTVALUE {
select  NEXTVAL('STG_ID')

}
OIMTGNGS_GETGANGNEXTVAL {
select  NEXTVAL('STG_ID')

}
OIMTGNGS_GETSETNEXTVAL {
select  NEXTVAL('STG_ID')

}
OIMTGNGS_SECGRP2INSERTSECURITYTHREATGROUPS {
insert into SECURITY_THREAT_GROUPS(STG_ID, STG_LEVEL, STG_CODE, DESCRIPTION, PARENT_STG_ID, LIST_SEQ, EFFECTIVE_DATE, HISTORY_TEXT, ACTIVE_FLAG, CREATE_USER_ID, CREATE_DATETIME, modify_datetime, EXPIRY_DATE, SEAL_FLAG) values(:stgId, :stgLevel, :stgCode, :description, :parentStgId, :listSeq, :effectiveDate, :historyText, :activeFlag, :createUserId, current_timestamp, null, :expiryDate, :sealFlag)
}
OIMTGNGS_GETDUPLICATESTGCODE {
SELECT count(*)
	  FROM SECURITY_THREAT_GROUPS
	 WHERE PARENT_STG_ID IS NULL 
	   AND STG_CODE = :stgCode	   
}
OIMTGNGS_GET_LPVALUE {
	SELECT 	profile_value
  	FROM	SYSTEM_PROFILES
  	WHERE	profile_type = 'CLIENT'
  	AND	profile_code = 'STG_LOV_LVL'
}
OIMTGNGS_GET_LV_GANG {
SELECT COUNT(*)  LV_GANG FROM SECURITY_THREAT_GROUPS WHERE PARENT_STG_ID = :stgId
}
OIMTGNGS_GET_LPSET {
SELECT COUNT(*) LV_SET FROM SECURITY_THREAT_GROUPS WHERE PARENT_STG_ID = :stgId
}
OIMTGNGS_GETDUPLICATEGANGSSTGCODE {
SELECT count(*)	  FROM SECURITY_THREAT_GROUPS 	 WHERE   STG_CODE =:stgCode
}
OIMTGNGS_GETDUPLICATESETSSTGCODE {
SELECT count(*)	  FROM SECURITY_THREAT_GROUPS 	 WHERE   STG_CODE = :stgCode
}
OIMTGNGS_OFF_STG_CUR_SEC_GRP{
SELECT COUNT(*) FROM SECURITY_THREAT_GROUPS  WHERE PARENT_STG_ID = :STG_ID AND ACTIVE_FLAG = 'Y'
}
OIMTGNGS_OFF_STG_CUR_SEC_GRP_ONE {
SELECT COUNT(*) FROM SECURITY_THREAT_GROUPS WHERE PARENT_STG_ID = :STG_ID AND ACTIVE_FLAG = 'Y'
}