
OCDOTASK_FIND_RGCOMPLETERSN {
 	SELECT DESCRIPTION , CODE , LIST_SEQ FROM REFERENCE_CODES WHERE DOMAIN = 'COMPLETE_RSN' ORDER BY LIST_SEQ , DESCRIPTION
}

OCDOTASK_FIND_RGSTAFF {
 SELECT DISTINCT st.last_name || ', ' || st.first_name description, st.staff_id code FROM staff_members st, team_staff_members tm WHERE st.staff_id = tm.staff_id AND ( ( :teamid IS NULL ) OR ( :teamid IS NOT NULL AND tm.team_id = :teamid ) ) ORDER BY description	
}
OCDOTASK_FIND_RGTEAM {
 	SELECT  DESCRIPTION , TEAM_ID CODE  FROM automation_teams
}

OCDOTASK_FIND_RGTASKSUBTYPE {
 	SELECT DESCRIPTION   ,CODE FROM   REFERENCE_CODES WHERE   DOMAIN = 'TASK_SUBTYPE'
}

OCDOTASK_FIND_RGTASKTYPE {
 	SELECT DISTINCT REFS.DESCRIPTION DESCRIPTION , WS.WORK_TYPE CODE FROM WORKS WS , REFERENCE_CODES REFS WHERE WS.WORKFLOW_TYPE = 'TASK' AND WS.WORK_TYPE = REFS.CODE AND REFS.DOMAIN = 'TASK_TYPE' ORDER BY DESCRIPTION
}

OCDOTASK_FIND_RGTASKTYPE_DESCRIPTION {
 	SELECT DISTINCT REFS.DESCRIPTION DESCRIPTION FROM WORKS WS , REFERENCE_CODES REFS WHERE WS.WORKFLOW_TYPE = 'TASK' AND WS.WORK_TYPE = REFS.CODE AND REFS.DOMAIN = 'TASK_TYPE' AND WS.WORK_TYPE = :workType ORDER BY DESCRIPTION
}

