
OCDALIAS_OFFNAME_FIND_OFFENDERS {
 SELECT OFFENDER_ID ,OFFENDER_NAME_SEQ ,ID_SOURCE_CODE ,LAST_NAME ,NAME_TYPE ,FIRST_NAME ,MIDDLE_NAME ,BIRTH_DATE ,SEX_CODE ,SUFFIX ,LAST_NAME_SOUNDEX ,BIRTH_PLACE ,BIRTH_COUNTRY_CODE ,CREATE_DATE ,LAST_NAME_KEY ,ALIAS_OFFENDER_ID ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,OFFENDER_ID_DISPLAY ,ROOT_OFFENDER_ID ,CASELOAD_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,ALIAS_NAME_TYPE ,PARENT_OFFENDER_ID ,UNIQUE_OBLIGATION_FLAG ,SUSPENDED_FLAG ,SUSPENDED_DATE ,RACE_CODE ,REMARK_CODE ,ADD_INFO_CODE ,BIRTH_COUNTY ,BIRTH_STATE ,MIDDLE_NAME_2 ,TITLE ,AGE ,CREATE_USER_ID ,LAST_NAME_ALPHA_KEY ,CREATE_DATETIME ,NAME_SEQUENCE ,SEAL_FLAG ,GENDER_CODE, SECOND_MIDDLE_NAME  FROM OFFENDERS   where ROOT_OFFENDER_ID = :ROOT_OFFENDER_ID  ORDER BY LAST_NAME
}

 OCDALIAS_OFFID_INSERT_OFFENDER_IDENTIFIERS {
  insert into OFFENDER_IDENTIFIERS(OFFENDER_ID , OFFENDER_ID_SEQ , IDENTIFIER_TYPE , IDENTIFIER , ISSUED_AUTHORITY_TEXT , ISSUED_DATE , ROOT_OFFENDER_ID , CASELOAD_TYPE , MODIFY_DATETIME , VERIFIED_FLAG , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG ) values(:offenderId , :offenderIdSeq , :identifierType , :identifier , :issuedAuthorityText , :issuedDate , :rootOffenderId , :caseloadType , null , :verifiedFlag , current_timestamp , :createUserId , :sealFlag ) 
 }   
 
 OCDALIAS_OFFID_UPDATE_OFFENDER_IDENTIFIERS {
 UPDATE OFFENDER_IDENTIFIERS set OFFENDER_ID = :offenderId ,OFFENDER_ID_SEQ = :offenderIdSeq ,IDENTIFIER_TYPE = :identifierType , IDENTIFIER = :identifier ,ISSUED_AUTHORITY_TEXT = :issuedAuthorityText ,ISSUED_DATE = :issuedDate ,ROOT_OFFENDER_ID = :rootOffenderId , CASELOAD_TYPE = :caseloadType ,MODIFY_USER_ID = :modifyUserId ,MODIFY_DATETIME = current_timestamp ,VERIFIED_FLAG = :verifiedFlag , SEAL_FLAG = :sealFlag where OFFENDER_ID = :offenderId and OFFENDER_ID_SEQ = :offenderIdSeq 
 }   
 
 OCDALIAS_OFFID_DELETE_OFFENDER_IDENTIFIERS { 
 DELETE FROM OFFENDER_IDENTIFIERS where OFFENDER_ID = :offenderId  and OFFENDER_ID_SEQ = :offenderIdSeq
 }   

OCDALIAS_OFFID_FIND_OFFENDER_IDENTIFIERS {
 SELECT OFFENDER_ID ,OFFENDER_ID_SEQ ,IDENTIFIER_TYPE ,IDENTIFIER ,ISSUED_AUTHORITY_TEXT ,ISSUED_DATE ,ROOT_OFFENDER_ID ,CASELOAD_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,VERIFIED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG,
 case when (
	select
		count(*)
	from
		ROLE_INACCESSIBLE_REF_CODES
	where
		ROLE_INACCESSIBLE_REF_CODES.module_name = 'OCDALIAS'
		and ROLE_INACCESSIBLE_REF_CODES.role_id in (
		select
			role_id
		from
			staff_member_roles smr
		where
			staff_id = (
			select
				staff_id
			from
				staff_members sm
			where
				upper(user_id) = upper(:userId)))
		and ROLE_INACCESSIBLE_REF_CODES.DOMAIN = 'ID_TYPE' and ROLE_INACCESSIBLE_REF_CODES.code = OFFENDER_IDENTIFIERS.identifier_type) > 0 then 'N' else 'Y' end as domain_access 
		FROM OFFENDER_IDENTIFIERS   where OFFENDER_ID = :offenderId 
}

OCDALIAS_OFFID_FIND_ALL_OFFENDER_IDENTIFIERS {
 SELECT OFFENDER_ID ,OFFENDER_ID_SEQ ,IDENTIFIER_TYPE ,IDENTIFIER ,ISSUED_AUTHORITY_TEXT ,ISSUED_DATE ,ROOT_OFFENDER_ID ,CASELOAD_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,VERIFIED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG   FROM OFFENDER_IDENTIFIERS   where ROOT_OFFENDER_ID = :ROOT_OFFENDER_ID
}

 OCDALIAS_OFFNAME_INSERT_OFFENDERS {
  insert into OFFENDERS(OFFENDER_ID , OFFENDER_NAME_SEQ , ID_SOURCE_CODE , LAST_NAME , NAME_TYPE , FIRST_NAME , MIDDLE_NAME , BIRTH_DATE , SEX_CODE , SUFFIX , LAST_NAME_SOUNDEX , BIRTH_PLACE , BIRTH_COUNTRY_CODE , CREATE_DATE , LAST_NAME_KEY , ALIAS_OFFENDER_ID , FIRST_NAME_KEY , MIDDLE_NAME_KEY , OFFENDER_ID_DISPLAY , ROOT_OFFENDER_ID , CASELOAD_TYPE , MODIFY_DATETIME , ALIAS_NAME_TYPE , PARENT_OFFENDER_ID , UNIQUE_OBLIGATION_FLAG , SUSPENDED_FLAG , SUSPENDED_DATE , RACE_CODE , REMARK_CODE , ADD_INFO_CODE , BIRTH_COUNTY , BIRTH_STATE , MIDDLE_NAME_2 , TITLE , AGE , CREATE_USER_ID , LAST_NAME_ALPHA_KEY , CREATE_DATETIME , NAME_SEQUENCE , SEAL_FLAG, GENDER_CODE, SECOND_MIDDLE_NAME ) values(:offenderId , :offenderNameSeq , :idSourceCode , :lastName , :nameType , :firstName , :middleName , :birthDate , :sexCode , :suffix , :lastNameSoundex , :birthPlace , :birthCountryCode , :createDate , :lastNameKey , :aliasOffenderId , :firstNameKey , :middleNameKey , :offenderIdDisplay , :rootOffenderId , :caseloadType, NULL , :aliasNameType , :parentOffenderId , :uniqueObligationFlag , :suspendedFlag , :suspendedDate , :raceCode , :remarkCode , :addInfoCode , :birthCounty , :birthState , :middleName2 , :title , :age , :createUserId , :lastNameAlphaKey , current_timestamp , :nameSequence , :sealFlag, :genderCode, :secondMiddleName ) 
 }   
 
 OCDALIAS_OFFNAME_UPDATE_OFFENDERS {
 UPDATE OFFENDERS set OFFENDER_ID = :offenderId ,OFFENDER_NAME_SEQ = :offenderNameSeq ,ID_SOURCE_CODE = :idSourceCode ,LAST_NAME = :lastName , NAME_TYPE = :nameType ,FIRST_NAME = :firstName ,MIDDLE_NAME = :middleName ,BIRTH_DATE = :birthDate ,SEX_CODE = :sexCode ,SUFFIX = :suffix , LAST_NAME_SOUNDEX = :lastNameSoundex ,BIRTH_PLACE = :birthPlace ,BIRTH_COUNTRY_CODE = :birthCountryCode ,CREATE_DATE = :createDate , LAST_NAME_KEY = :lastNameKey ,ALIAS_OFFENDER_ID = :aliasOffenderId ,FIRST_NAME_KEY = :firstNameKey ,MIDDLE_NAME_KEY = :middleNameKey , OFFENDER_ID_DISPLAY = :offenderIdDisplay ,ROOT_OFFENDER_ID = :rootOffenderId ,CASELOAD_TYPE = :caseloadType ,MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = current_timestamp ,ALIAS_NAME_TYPE = :aliasNameType ,PARENT_OFFENDER_ID = :parentOffenderId ,UNIQUE_OBLIGATION_FLAG = :uniqueObligationFlag ,SUSPENDED_FLAG = :suspendedFlag ,SUSPENDED_DATE = :suspendedDate ,RACE_CODE = :raceCode , REMARK_CODE = :remarkCode ,ADD_INFO_CODE = :addInfoCode ,BIRTH_COUNTY = :birthCounty ,BIRTH_STATE = :birthState ,MIDDLE_NAME_2 = :middleName2 , TITLE = :title ,AGE = :age ,LAST_NAME_ALPHA_KEY = :lastNameAlphaKey ,NAME_SEQUENCE = :nameSequence ,SEAL_FLAG = :sealFlag,GENDER_CODE = :genderCode where OFFENDER_ID = :offenderId 
 }   
 
 OCDALIAS_OFFNAME_DELETE_OFFENDERS { 
 DELETE FROM OFFENDERS where OFFENDER_ID = :offenderId 
 }   

OCDALIAS_REQNAME_FIND_OFFENDER_BOOKINGS {
 SELECT OFFENDER_BOOK_ID ,BOOKING_BEGIN_DATE ,BOOKING_END_DATE ,BOOKING_NO ,OFFENDER_ID ,AGY_LOC_ID ,LIVING_UNIT_ID ,DISCLOSURE_FLAG ,IN_OUT_STATUS ,ACTIVE_FLAG ,BOOKING_STATUS ,YOUTH_ADULT_CODE ,FINGER_PRINTED_STAFF_ID ,SEARCH_STAFF_ID ,PHOTO_TAKING_STAFF_ID ,ASSIGNED_STAFF_ID ,CREATE_AGY_LOC_ID ,BOOKING_TYPE ,BOOKING_CREATED_DATE ,ROOT_OFFENDER_ID ,AGENCY_IML_ID ,SERVICE_FEE_FLAG ,EARNED_CREDIT_LEVEL ,EKSTRAND_CREDIT_LEVEL ,INTAKE_AGY_LOC_ID ,ACTIVITY_DATE ,INTAKE_CASELOAD_ID ,INTAKE_USER_ID ,CASE_OFFICER_ID ,CASE_DATE ,CASE_TIME ,COMMUNITY_ACTIVE_FLAG ,CREATE_INTAKE_AGY_LOC_ID ,COMM_STAFF_ID ,COMM_STATUS ,COMMUNITY_AGY_LOC_ID ,NO_COMM_AGY_LOC_ID ,COMM_STAFF_ROLE ,AGY_LOC_ID_LIST ,STATUS_REASON ,TOTAL_UNEXCUSED_ABSENCES ,REQUEST_NAME ,RECORD_USER_ID ,INTAKE_AGY_LOC_ASSIGN_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_BOOKINGS   where OFFENDER_BOOK_ID = :offenderBookId  
}

 OCDALIAS_REQNAME_UPDATE_OFFENDER_BOOKINGS {
 update OFFENDER_BOOKINGS set OFFENDER_BOOK_ID = :offenderBookId , BOOKING_BEGIN_DATE = :bookingBeginDate , BOOKING_END_DATE = :bookingEndDate , BOOKING_NO = :bookingNo , OFFENDER_ID = :offenderId , AGY_LOC_ID = :agyLocId , LIVING_UNIT_ID = :livingUnitId , DISCLOSURE_FLAG = :disclosureFlag , IN_OUT_STATUS = :inOutStatus , ACTIVE_FLAG = :activeFlag , BOOKING_STATUS = :bookingStatus , YOUTH_ADULT_CODE = :youthAdultCode , FINGER_PRINTED_STAFF_ID = :fingerPrintedStaffId , SEARCH_STAFF_ID = :searchStaffId , PHOTO_TAKING_STAFF_ID = :photoTakingStaffId , ASSIGNED_STAFF_ID = :assignedStaffId , CREATE_AGY_LOC_ID = :createAgyLocId , BOOKING_TYPE = :bookingType , BOOKING_CREATED_DATE = :bookingCreatedDate , ROOT_OFFENDER_ID = :rootOffenderId , AGENCY_IML_ID = :agencyImlId , SERVICE_FEE_FLAG = :serviceFeeFlag , EARNED_CREDIT_LEVEL = :earnedCreditLevel , EKSTRAND_CREDIT_LEVEL = :ekstrandCreditLevel , INTAKE_AGY_LOC_ID = :intakeAgyLocId , ACTIVITY_DATE = :activityDate , INTAKE_CASELOAD_ID = :intakeCaseloadId , INTAKE_USER_ID = :intakeUserId , CASE_OFFICER_ID = :caseOfficerId , CASE_DATE = :caseDate , CASE_TIME = :caseTime , COMMUNITY_ACTIVE_FLAG = :communityActiveFlag , CREATE_INTAKE_AGY_LOC_ID = :createIntakeAgyLocId , COMM_STAFF_ID = :commStaffId , COMM_STATUS = :commStatus , COMMUNITY_AGY_LOC_ID = :communityAgyLocId , NO_COMM_AGY_LOC_ID = :noCommAgyLocId , COMM_STAFF_ROLE = :commStaffRole , AGY_LOC_ID_LIST = :agyLocIdList , STATUS_REASON = :statusReason , TOTAL_UNEXCUSED_ABSENCES = :totalUnexcusedAbsences , REQUEST_NAME = :requestName , RECORD_USER_ID = :recordUserId , INTAKE_AGY_LOC_ASSIGN_DATE = :intakeAgyLocAssignDate , MODIFY_DATETIME = :modifyDatetime , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where OFFENDER_BOOK_ID = :offenderBookId 
 }   

OCDALIAS_OFF_BKG_ONCHECKDELETEMASTER_OFF_NAME_CUR {
 SELECT 1 FROM OFFENDERS O WHERE O.ROOT_OFFENDER_ID = :rootOffenderId
}


OCDALIAS_OFF_NAME_ONCHECKDELETEMASTER_OFF_ID_CUR {
 SELECT  count(*) FROM OFFENDER_IDENTIFIERS O WHERE O.OFFENDER_ID = :offenderId
}

OCDALIAS_OFF_ID_PREINSERT {
 select MAX(OFFENDER_ID_SEQ)::integer + 1 LV_SEQ from OFFENDER_IDENTIFIERS WHERE OFFENDER_ID = :offenderId
}

OCDALIAS_CGRICHK_OFFENDERS_C {
 SELECT  1 FROM    OFFENDER_IDENTIFIERS OFF_IDE WHERE   OFF_IDE.OFFENDER_ID = :offenderId
}

 OCDALIAS_UPDATE_WORKING_NAME_QUERY{
  update OFFENDER_BOOKINGS set OFFENDER_ID = :offenderId, modify_datetime =current_timestamp , modify_user_id =:modifyUserId where ROOT_OFFENDER_ID = :rootOffenderId and OFFENDER_BOOK_ID = :offenderBookId 
 }   

OCDALIAS_CHANGE_WORKING_NAME_QUERY_RETURN_BEAN{
    SELECT OFFENDER_ID, OFFENDER_NAME_SEQ, ID_SOURCE_CODE, LAST_NAME, NAME_TYPE , FIRST_NAME , MIDDLE_NAME , BIRTH_DATE , SEX_CODE, SUFFIX, LAST_NAME_SOUNDEX, BIRTH_PLACE, BIRTH_COUNTRY_CODE, CREATE_DATE, LAST_NAME_KEY, ALIAS_OFFENDER_ID, FIRST_NAME_KEY, MIDDLE_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, CASELOAD_TYPE, MODIFY_USER_ID, MODIFY_DATETIME, ALIAS_NAME_TYPE, PARENT_OFFENDER_ID, UNIQUE_OBLIGATION_FLAG, SUSPENDED_FLAG, SUSPENDED_DATE, RACE_CODE, REMARK_CODE, ADD_INFO_CODE, BIRTH_COUNTY, BIRTH_STATE, MIDDLE_NAME_2, TITLE, AGE, CREATE_USER_ID, LAST_NAME_ALPHA_KEY, CREATE_DATETIME, NAME_SEQUENCE, SEAL_FLAG,GENDER_CODE FROM OFFENDERS WHERE OFFENDER_ID = :offenderId AND ROOT_OFFENDER_ID = :rootOffenderId
}

OCDALIAS_MODIFIED_RECORD{
SELECT * FROM (SELECT * FROM OFFENDER_BOOKINGS ORDER BY MODIFY_DATETIME desc)A WHERE ROOT_OFFENDER_ID = :ROOT_OFFENDER_ID limit 1

}

OCDALIAS_COUNT_ROOTOFFENDER_ID{
SELECT COUNT(*) FROM OFFENDER_BOOKINGS WHERE ROOT_OFFENDER_ID = :rootOffenderId

}

OCDALIAS_GENERATE_OFFENDER_ID{
SELECT coalesce (MAX(OFFENDER_ID),0) + 1 FROM   OFFENDERS
}

OCDALIAS_GENERATE_OFFENDER_IDSEQ_IDENTIFIERS{
SELECT coalesce (MAX(OFFENDER_ID_SEQ)::int, 0)+1 FROM OFFENDER_IDENTIFIERS WHERE OFFENDER_ID = :offenderId AND ROOT_OFFENDER_ID = :rootOffenderId 
}

OCDALIAS_GET_GENDER_DESCRIPTION{
SELECT CODE, DESCRIPTION from REFERENCE_CODES WHERE DOMAIN = 'SEX'
}
OCDALIAS_VS_RANGECUR {
SELECT PROFILE_VALUE, PROFILE_VALUE_2 FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'AGE_RANGE'
  }
 OCDALIAS_GETTING_OLD_RECORD{
  select * from OFFENDERS where offender_id =:offenderId
 }
 OCDALIAS_GETTING_OLDATA{
 select * from OFFENDER_BOOKINGS where offender_book_id =:offenderBokkId
 }

