
  OCDADDRE_FIND_RGTOWN {
 select REF_CODE.DESCRIPTION , REF_CODE.CODE from REFERENCE_CODES REF_CODE where domain = 'CITY' and ((ACTIVE_FLAG = 'Y' and EXPIRED_DATE is null ) ) order by REF_CODE.LIST_SEQ , REF_CODE.CODE
}
	OCDADDRE_FIND_RGCOUNTRY {
 SELECT REF_CODE.DESCRIPTION, REF_CODE.CODE, REF_CODE.LIST_SEQ FROM REFERENCE_CODES REF_CODE WHERE DOMAIN = 'COUNTRY' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL )) ORDER BY REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCDADDRE_FIND_RGSDIR {
 SELECT REF_CODE.DESCRIPTION, REF_CODE.CODE FROM REFERENCE_CODES REF_CODE WHERE DOMAIN = 'STREET_DIR' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL )) ORDER BY REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCDADDRE_FIND_RGSTATE {
 SELECT REF_CODE.DESCRIPTION, REF_CODE.CODE, REF_CODE.LIST_SEQ FROM REFERENCE_CODES REF_CODE WHERE DOMAIN = 'PROV_STATE' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL )) ORDER BY REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCDADDRE_FIND_RGADDRESSTYPE {
SELECT REF_CODE.CODE, REF_CODE.DESCRIPTION FROM REFERENCE_CODES REF_CODE WHERE DOMAIN = 'ADDRESS_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCDADDRE_FIND_RGPHONETYPE {
select REF_CODE.CODE , REF_CODE.DESCRIPTION from REFERENCE_CODES REF_CODE where domain = 'PHONE_USAGE' and ACTIVE_FLAG = 'Y' and EXPIRED_DATE is null order by REF_CODE.LIST_SEQ , REF_CODE.CODE
}
   OCDADDRE_VADD_FIND_V_ADDRESSES {
 SELECT ADDRESS_ID, ADDRESS_TYPE, ADDRESS_TYPE_DESC, OWNER_CLASS, OWNER_ID, OWNER_SEQ, OWNER_CODE, START_DATE, END_DATE, ACTIVE_FLAG, FULL_ADDRESS, HOUSE, STREET, AREA, COUNTRY, SUITE_NUMBER, STREET_NUMBER, STREET_DIRECTION, STREET_DIRECTION_DESC, STREET_INFORMATION, CITY_CODE, CITY_NAME, PROV_STATE_CODE, PROV_STATE_DESC, ZIP_POSTAL_CODE, COUNTRY_CODE, COUNTRY_DESC, CAPACITY, COMMENT_TEXT, PRIMARY_FLAG, MAIL_FLAG, SERVICES_FLAG, NO_FIXED_ADDRESS_FLAG, SPECIAL_NEEDS, VALIDATED_FLAG, CONTACT_PERSON_NAME, BUSINESS_HOUR, MAIL_CARE_OF,LONGITUDE,LATITUDE,MESH_BLOCK,IS_ADDRESS_VALID,ADDRESS_LINE1 FROM V_ADDRESSES WHERE OWNER_ID = :OWNER_ID and OWNER_CLASS = 'OFF' ORDER BY PRIMARY_FLAG DESC,MAIL_FLAG DESC,ACTIVE_FLAG DESC, coalesce(START_DATE, '01-JAN-1900') DESC

}

  OCDADDRE_ADDR_FIND_ADDRESSES {
 SELECT ADDRESS_ID, OWNER_CLASS, OWNER_ID, OWNER_SEQ, OWNER_CODE, ADDRESS_TYPE, CITY_CODE, COUNTRY_CODE, VALIDATED_PAF_FLAG, PRIMARY_FLAG, MAIL_FLAG, CAPACITY, COMMENT_TEXT, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, NO_FIXED_ADDRESS_FLAG, SERVICES_FLAG, SPECIAL_NEEDS_CODE, CONTACT_PERSON_NAME, BUSINESS_HOUR, START_DATE, END_DATE, CITY_NAME, PROV_STATE_CODE, STREET, ZIP_POSTAL_CODE, SUITE_NUMBER, STREET_NUMBER, STREET_DIRECTION, MAIL_CARE_OF, SEAL_FLAG FROM ADDRESSES WHERE ADDRESS_ID = :ADDRESS_ID and OWNER_CLASS = 'OFF'

}
  OCDADDRE_ADDR_INSERT_ADDRESSES {
INSERT INTO ADDRESSES(ADDRESS_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,ADDRESS_TYPE ,CITY_CODE ,COUNTRY_CODE ,VALIDATED_PAF_FLAG ,PRIMARY_FLAG ,MAIL_FLAG ,CAPACITY ,COMMENT_TEXT ,CREATE_DATETIME ,CREATE_USER_ID  ,NO_FIXED_ADDRESS_FLAG ,SERVICES_FLAG ,SPECIAL_NEEDS_CODE ,CONTACT_PERSON_NAME ,BUSINESS_HOUR ,START_DATE ,END_DATE ,CITY_NAME ,PROV_STATE_CODE ,STREET ,ZIP_POSTAL_CODE ,SUITE_NUMBER ,STREET_NUMBER ,STREET_DIRECTION ,MAIL_CARE_OF ,SEAL_FLAG,LONGITUDE,LATITUDE,MESH_BLOCK,IS_ADDRESS_VALID,ADDRESS_LINE1, VALIDATED_PAYLOAD, MODIFY_USER_ID, MODIFY_DATETIME
) VALUES(:addressId ,:ownerClass ,:ownerId ,:ownerSeq ,:ownerCode ,:addressType ,:cityCode ,:countryCode , :validatedPafFlag ,:primaryFlag ,:mailFlag ,:capacity ,:commentText ,current_timestamp ,:createUserId , :noFixedAddressFlag ,:servicesFlag ,:specialNeedsCode ,:contactPersonName ,:businessHour ,:startDate ,:endDate ,:cityName , :provStateCode ,:street ,:zipPostalCode ,:suiteNumber ,:streetNumber ,:streetDirection ,:mailCareOf ,:sealFlag,:longitude,:latitude,:meshBlock,:isAddressValid,:streetAddress, :verifiedPayload, null, null )
}  

  OCDADDRE_ADDR_UPDATE_ADDRESSES {
UPDATE ADDRESSES set OWNER_ID=:ownerId,CITY_CODE=:cityCode ,COUNTRY_CODE=:countryCode ,PRIMARY_FLAG=:primaryFlag ,MAIL_FLAG=:mailFlag , COMMENT_TEXT=:commentText ,NO_FIXED_ADDRESS_FLAG=:noFixedAddressFlag ,START_DATE=:startDate ,END_DATE=:endDate ,CITY_NAME=:cityName , PROV_STATE_CODE=:provStateCode ,STREET=:street ,ZIP_POSTAL_CODE=:zipPostalCode ,SUITE_NUMBER=:suiteNumber ,STREET_NUMBER=:streetNumber , STREET_DIRECTION=:streetDirection,MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId,LONGITUDE=:longitude,LATITUDE=:latitude,MESH_BLOCK=:meshBlock,IS_ADDRESS_VALID=:isAddressValid,ADDRESS_LINE1=:streetAddress,MAIL_CARE_OF=:mailCareOf, VALIDATED_PAYLOAD=:verifiedPayload where ADDRESS_ID=:addressId
}  

	OCDADDRE_ADDR_DELETE_ADDRESSES { 
DELETE FROM ADDRESSES where ADDRESS_ID=:addressId
}  

  OCDADDRE_ADDRUSAGE_FIND_ADDRESS_USAGES {
 SELECT ADDRESS_ID ,ADDRESS_USAGE ,ACTIVE_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   
 FROM ADDRESS_USAGES WHERE ADDRESS_ID = :ADDRESS_ID
}

  OCDADDRE_ADDRUSAGE_INSERT_ADDRESS_USAGES {
INSERT INTO ADDRESS_USAGES(ADDRESS_ID ,ADDRESS_USAGE ,ACTIVE_FLAG ,CREATE_DATETIME ,CREATE_USER_ID  ,SEAL_FLAG,  MODIFY_USER_ID, MODIFY_DATETIME
)
VALUES(:addressId ,:addressUsage , 'Y' ,current_timestamp ,:createUserId ,:sealFlag, null, null )
}  

  OCDADDRE_ADDRUSAGE_UPDATE_ADDRESS_USAGES {
UPDATE ADDRESS_USAGES set ADDRESS_USAGE = :addressUsage, ACTIVE_FLAG=:activeFlag  , MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId, SEAL_FLAG=:sealFlag   
WHERE ADDRESS_ID = :addressId and ADDRESS_USAGE = :addressUsageTemp  
} 

OCDADDRE_ADDRUSAGE_DELETE_ADDRESS_USAGES { 
DELETE FROM ADDRESS_USAGES WHERE ADDRESS_ID = :addressId
} 

    OCDADDRE_PHONEADDR_FIND_PHONES {
 SELECT PHONE_ID, OWNER_CLASS, OWNER_ID, OWNER_SEQ, OWNER_CODE, PHONE_TYPE, PHONE_NO, EXT_NO, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG,FORMAT FROM PHONES WHERE OWNER_ID = :OWNER_ID and OWNER_CLASS =:OWNER_CLASS ORDER BY PHONE_TYPE

}

      OCDADDRE_PHONEADDR_INSERT_PHONES {
  INSERT INTO PHONES(PHONE_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,PHONE_TYPE ,PHONE_NO ,EXT_NO ,CREATE_DATETIME ,CREATE_USER_ID 
   ,SEAL_FLAG,FORMAT, MODIFY_USER_ID, MODIFY_DATETIME
    ) VALUES(NEXTVAL('PHONE_ID') ,:ownerClass ,:ownerId ,:ownerSeq ,:ownerCode ,:phoneType ,:phoneNo ,:extNo ,
  current_timestamp ,:createUserId ,:sealFlag,:format,null, null )
  }    
  
      OCDADDRE_PHONEADDR_UPDATE_PHONES {
  UPDATE PHONES set OWNER_CLASS=:ownerClass , OWNER_ID=:ownerId, PHONE_NO=:phoneNo, EXT_NO=:extNo, PHONE_TYPE=:phoneType,MODIFY_DATETIME=current_timestamp,MODIFY_USER_ID=:modifyUserId,FORMAT=:format where PHONE_ID=:phoneId
  }    
  
  	OCDADDRE_PHONEADDR_DELETE_PHONES { 
  DELETE FROM PHONES where PHONE_ID=:phoneId 
  }     

    OCDADDRE_EMAIL_FIND_INTERNET_ADDRESSES {
 SELECT INTERNET_ADDRESS_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,INTERNET_ADDRESS_CLASS ,INTERNET_ADDRESS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   
  FROM INTERNET_ADDRESSES WHERE OWNER_ID = :OWNER_ID and  OWNER_CLASS = 'OFF'
}

      OCDADDRE_EMAIL_INSERT_INTERNET_ADDRESSES {
  INSERT INTO INTERNET_ADDRESSES(INTERNET_ADDRESS_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,INTERNET_ADDRESS_CLASS ,INTERNET_ADDRESS 
  ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG, MODIFY_USER_ID, MODIFY_DATETIME
   )
  VALUES(NEXTVAL('INTERNET_ADDRESS_ID') ,:ownerClass ,:ownerId ,:ownerSeq ,:ownerCode ,:internetAddressClass ,:internetAddress ,current_timestamp ,
  :createUserId ,:sealFlag,null,null )
  }   
  
      OCDADDRE_EMAIL_UPDATE_INTERNET_ADDRESSES {
  UPDATE INTERNET_ADDRESSES set OWNER_CLASS=:ownerClass,OWNER_ID=:ownerId ,OWNER_SEQ=:ownerSeq ,OWNER_CODE=:ownerCode ,
  INTERNET_ADDRESS_CLASS=:internetAddressClass ,INTERNET_ADDRESS=:internetAddress  ,MODIFY_DATETIME=current_timestamp ,MODIFY_USER_ID=:modifyUserId ,SEAL_FLAG=:sealFlag where INTERNET_ADDRESS_ID=:internetAddressId  /* where null*/
  }   
  
  	OCDADDRE_EMAIL_DELETE_INTERNET_ADDRESSES { 
  DELETE FROM INTERNET_ADDRESSES where INTERNET_ADDRESS_ID=:internetAddressId  
  }   


	OCDADDRE_OFF_BKG_ONCHECKDELETEMASTER_V_ADD_CUR {
 SELECT 1 FROM V_ADDRESSES V WHERE V.OWNER_ID = :ROOTOFFENDERID
}

	OCDADDRE_OFF_BKG_ONCHECKDELETEMASTER_PHONE_GLOBAL_CUR {
 SELECT 1 FROM PHONES P WHERE P.OWNER_ID = :ROOTOFFENDERID
}

	OCDADDRE_OFF_BKG_ONCHECKDELETEMASTER_EMAIL_CUR {
 SELECT 1 FROM INTERNET_ADDRESSES I WHERE I.OWNER_ID = :ROOTOFFENDERID
}

	OCDADDRE_OFF_BKG_ONCHECKDELETEMASTER_ADDR_CUR {
 SELECT 1 FROM ADDRESSES A WHERE A.OWNER_ID = :ROOTOFFENDERID
}

	OCDADDRE_V_ADD_ONCHECKDELETEMASTER_ADDR_CUR {
 SELECT 1 FROM ADDRESSES A WHERE A.ADDRESS_ID = :ADDRESSID
}

	OCDADDRE_NBT_CITY_KEYLISTVAL_GET_CITY_DESCRIPTION_C {
 select
	COUNT(1)
from
	REFERENCE_CODES
where
	domain = 'CITY'
	and ACTIVE_FLAG = 'Y'
	and EXPIRED_DATE is null
	and UPPER(DESCRIPTION) like DESCRIPTION || '%'
	 
}

	OCDADDRE_ADDR_ONCHECKDELETEMASTER_PHONE_ADDR_CUR {
 SELECT 1 FROM PHONES P WHERE P.OWNER_ID = :ADDRESSID
}

	OCDADDRE_ADDR_ONCHECKDELETEMASTER_ADDR_USAGE_CUR {
 SELECT 1 FROM ADDRESS_USAGES A WHERE A.ADDRESS_ID = :ADDRESSID
}

	OCDADDRE_ADDR_WHENCREATERECORD_GET_COUNTRY_CUR  {
 SELECT DESCRIPTION, CODE FROM REFERENCE_CODES WHERE DOMAIN = :P_DOMAIN AND LIST_SEQ = 1 AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

	OCDADDRE_CREATE_FORM_GLOBALS {
 SELECT DESCRIPTION  FROM OMS_MODULES WHERE MODULE_NAME = :V_FORM_NAME 
}

	OCDADDRE_ADDRESS_TYPE_CHECK_ACTIVE_TYPE_CUR {
 SELECT COUNT (*) FROM ADDRESS_USAGES WHERE ADDRESS_ID = :ADDRESSID AND ACTIVE_FLAG = 'Y'
}

	OCDADDRE_VALIDATE_CITY_INFO_GET_CITY_DESCRIPTION_C {
  SELECT COUNT(1) FROM REFERENCE_CODES WHERE DOMAIN = 'CITY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL AND UPPER(DESCRIPTION) LIKE DESCRIPTION || '%'
}

	OCDADDRE_VALIDATE_CITY_INFO_GET_CITY_CODE_C {
 SELECT CODE, DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'CITY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL AND UPPER(DESCRIPTION) LIKE DESCRIPTION || '%'
}

	OCDADDRE_CHECK_HDC_ADDRESS_ACTIVE_CHECK_HDC_ADDRESS_CUR {
 SELECT A.ADDRESS_ID FROM ADDRESS_USAGES A, V_ADDRESSES B WHERE A.ACTIVE_FLAG = 'Y' AND A.ADDRESS_USAGE = 'HDC' AND A.ADDRESS_ID = B.ADDRESS_ID AND B.OWNER_ID = :OWNERID
}

	  OCDADDRE_CHECK_HDC_ADDRESS_ACTIVE {
   SELECT OFFENDER_CURFEW_ID FROM OFFENDER_CURFEWS OC WHERE OC.OFFENDER_BOOK_ID = CURFEW_ADDRESSES.OFFENDER_BOOK_ID AND APPROVAL_STATUS IS NULL )
  } 

	OCDADDRE_CHECK_HDC_ADDRESS_EXIST_CHECK_HDC_ADDRESS_CUR {
 SELECT A.ADDRESS_ID FROM ADDRESS_USAGES A, V_ADDRESSES B WHERE A.ADDRESS_USAGE = 'HDC' AND A.ADDRESS_ID = B.ADDRESS_ID AND B.OWNER_ID = :OWNERID AND A.ADDRESS_ID = :ADDRESSID
}

  OCDADDRE_ADDR_PREINSERT {
  SELECT NEXTVAL('ADDRESS_ID')   FROM DUAL 
}

 OCDADDRE_PHONES_PREINSERT {
SELECT NEXTVAL('PHONE_ID')  FROM DUAL
}

  OCDADDRE_ADDRESS_USAGE_COUNT {
SELECT COUNT(*) FROM ADDRESS_USAGES WHERE  ADDRESS_ID = :ADDRESS_ID  AND ADDRESS_USAGE = :ADDRESS_USAGE 
}

 OCDADDRE_INTERNET_ADDRESSES_PREINSERT {
  SELECT NEXTVAL('INTERNET_ADDRESS_ID') FROM DUAL 
}
  OCDADDRE_ADDRESSES_PREUPDATE {
  update ADDRESSES set PRIMARY_FLAG = 'N',MODIFY_DATETIME=current_timestamp ,MODIFY_USER_ID=:modifyUserId where OWNER_ID =:ownerId and OWNER_CLASS = 'OFF' and PRIMARY_FLAG = 'Y'
  }  
  OCDADDRE_ADDRESSES_PREUPDATE_MAILFLAG {
  update ADDRESSES set MAIL_FLAG = 'N',MODIFY_DATETIME=current_timestamp ,MODIFY_USER_ID=:modifyUserId where OWNER_ID =:ownerId and OWNER_CLASS = 'OFF' and MAIL_FLAG = 'Y'
  }  
  
  OCDADDRE_ADDRESSES_GETTING_OLRECORD{
  select * from addresses where address_id =:addressId
  }
