
OCDCCONT_FIND_RGPHONETYPE {
 	SELECT REF_CODE.DESCRIPTION  DESCRIPTION  ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'PHONE_USAGE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ
}

OCDCCONT_PHONES_FIND_PHONES {
 	SELECT PHONE_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,PHONE_TYPE ,PHONE_NO ,EXT_NO ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG,FORMAT   FROM PHONES  where OWNER_CLASS =:ownerClass AND OWNER_ID =:ownerId
}
 OCDCCONT_PHONES_INSERT_PHONES {
 INSERT INTO PHONES(PHONE_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,PHONE_TYPE ,PHONE_NO ,EXT_NO ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME,SEAL_FLAG,FORMAT) 
 	VALUES(nextval('phone_id'),:ownerClass ,:ownerId ,:ownerSeq ,:ownerCode ,:phoneType ,:phoneNo ,:extNo ,CURRENT_TIMESTAMP ,:createUserId ,NULL ,:sealFlag,:format  )
 }  
 
 OCDCCONT_PHONES_UPDATE_PHONES {
 	UPDATE PHONES set PHONE_ID  = :phoneId ,OWNER_CLASS  = :ownerClass ,OWNER_ID  = :ownerId ,OWNER_SEQ  = :ownerSeq ,OWNER_CODE  = :ownerCode ,PHONE_TYPE  = :phoneType ,PHONE_NO  = :phoneNo ,EXT_NO  = :extNo ,CREATE_DATETIME  = :createDatetime ,MODIFY_DATETIME  = :modifyDatetime ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag,FORMAT=:format  where PHONE_ID  = :phoneId 
 }  
 
 OCDCCONT_PHONES_DELETE_PHONES { 
 	DELETE FROM PHONES where PHONE_ID = :PhoneId
 }  


OCDCCONT_PHONES_PREINSERT_PREINSERT {
	SELECT coalesce (MAX(PHONE_ID),0) + 1 FROM PHONES
}

OCDCCONT_PHONES_PREINSERT_OWNERSEQ {
select
	coalesce (MAX(OWNER_SEQ),
	0) + 1
from
	PHONES
where
	OWNER_CLASS = :OWNER_CLASS
	and OWNER_ID = :OWNER_ID
}
