
OCDGNUMB_FIND_RGPHONETYPE {
 	SELECT REF_CODE.DESCRIPTION  DESCRIPTION   ,REF_CODE.CODE  CODE FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'PHONE_USAGE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ
}

OCDGNUMB_PHONES_FIND_PHONES {
 	SELECT PHONE_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,PHONE_TYPE ,PHONE_NO ,EXT_NO ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG,FORMAT   FROM PHONES 
}
  OCDGNUMB_PHONES_INSERT_PHONES {
  	INSERT INTO PHONES(PHONE_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,PHONE_TYPE ,PHONE_NO ,EXT_NO ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG ,FORMAT) VALUES(nextVal('phone_id') ,:ownerClass ,:ownerId ,:ownerSeq ,:ownerCode ,:phoneType ,:phoneNo ,:extNo ,current_timestamp ,:createUserId ,null ,:sealFlag,:format )
  }  
  
  OCDGNUMB_PHONES_UPDATE_PHONES {
  	UPDATE PHONES set OWNER_CLASS  = :ownerClass ,OWNER_ID  = :ownerId ,OWNER_SEQ  = :ownerSeq ,OWNER_CODE  = :ownerCode ,PHONE_TYPE  = :phoneType ,PHONE_NO  = :phoneNo ,EXT_NO  = :extNo ,CREATE_DATETIME  = :createDatetime ,MODIFY_DATETIME  = current_timestamp ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag,FORMAT=:format  WHERE PHONE_ID  = :phoneId
  }  
  
  OCDGNUMB_PHONES_DELETE_PHONES { 
  	DELETE FROM PHONES WHERE PHONE_ID  = :phoneId
  }  

OCDGNUMB_INTERNETADDR_FIND_INTERNET_ADDRESSES {
 	SELECT INTERNET_ADDRESS_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,INTERNET_ADDRESS_CLASS ,INTERNET_ADDRESS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM INTERNET_ADDRESSES 
}
  OCDGNUMB_INTERNETADDR_INSERT_INTERNET_ADDRESSES {
   insert into INTERNET_ADDRESSES(INTERNET_ADDRESS_ID , OWNER_CLASS , OWNER_ID , OWNER_SEQ , OWNER_CODE , INTERNET_ADDRESS_CLASS , INTERNET_ADDRESS , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(nextVal('internet_address_id') , :ownerClass , :ownerId , :ownerSeq , :ownerCode , :internetAddressClass , :internetAddress , current_timestamp , :createUserId , NULL , :sealFlag ) 
  }  
  
  OCDGNUMB_INTERNETADDR_UPDATE_INTERNET_ADDRESSES {
   update INTERNET_ADDRESSES set OWNER_CLASS = :ownerClass , OWNER_ID = :ownerId , OWNER_SEQ = :ownerSeq , OWNER_CODE = :ownerCode , INTERNET_ADDRESS_CLASS = :internetAddressClass , INTERNET_ADDRESS = :internetAddress , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where INTERNET_ADDRESS_ID = :internetAddressId 
  }  
  
  OCDGNUMB_INTERNETADDR_DELETE_INTERNET_ADDRESSES { 
  	DELETE FROM INTERNET_ADDRESSES WHERE INTERNET_ADDRESS_ID  = :internetAddressId
  }  


OCDGNUMB_PHONES_PREINSERT_PREINSERT {
	SELECT NEXTVAL('PHONE_ID') FROM PHONES
}

OCDGNUMB_INTERNET_ADDR_PREINSERT {
	SELECT NEXTVAL('INTERNET_ADDRESS_ID') FROM INTERNET_ADDRESSES

}

OCDGNUMB_GETTING_PHONES_OLD_DATA{
SELECT * FROM PHONES  WHERE PHONE_ID= :PHONEID
}

OCDGNUMB_DESCRIPTION_EMAIL{
select description from  reference_codes where domain='EMAIL_DOMAIN' and expired_date is null;
}
