
OCDLANGS_FIND_RGLANGSKILLS {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'LANG_SKILLS' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  REFERENCE_CODES.LIST_SEQ, REFERENCE_CODES.DESCRIPTION

}

OCDLANGS_FIND_RGPREFLANG {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'LANG' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  REFERENCE_CODES.LIST_SEQ, REFERENCE_CODES.DESCRIPTION

}

OCDLANGS_FIND_RGSECLANG {
SELECT
  DESCRIPTION, CODE, ACTIVE_FLAG
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'LANG' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  REFERENCE_CODES.LIST_SEQ, REFERENCE_CODES.DESCRIPTION

}

OCDLANGS_OFFPRIMLANG_FIND_OFFENDER_LANGUAGES {
 	SELECT OFFENDER_BOOK_ID ,LANGUAGE_TYPE ,LANGUAGE_CODE ,READ_SKILL ,SPEAK_SKILL ,WRITE_SKILL ,COMMENT_TEXT ,MODIFY_DATETIME ,MODIFY_USER_ID ,CREATE_DATETIME ,CREATE_USER_ID ,NUMERACY_SKILL ,PREFERED_WRITE_FLAG ,PREFERED_SPEAK_FLAG ,INTERPRETER_REQUESTED_FLAG ,SEAL_FLAG   FROM OFFENDER_LANGUAGES WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID and LANGUAGE_TYPE = 'PRIM'
}
OCDLANGS_OFFPRIMLANG_INSERT_OFFENDER_LANGUAGES {
insert into OFFENDER_LANGUAGES(OFFENDER_BOOK_ID , LANGUAGE_TYPE , LANGUAGE_CODE , READ_SKILL , SPEAK_SKILL , WRITE_SKILL , COMMENT_TEXT , MODIFY_DATETIME , CREATE_DATETIME , CREATE_USER_ID , NUMERACY_SKILL , PREFERED_WRITE_FLAG , PREFERED_SPEAK_FLAG , INTERPRETER_REQUESTED_FLAG , SEAL_FLAG ) values(:offenderBookId , :languageType , :languageCode , :readSkill , :speakSkill , :writeSkill , :commentText , NULL , CURRENT_TIMESTAMP , :createUserId , :numeracySkill , :preferedWriteFlag , :preferedSpeakFlag , :interpreterRequestedFlag , :sealFlag ) 
}   

OCDLANGS_OFFPRIMLANG_UPDATE_OFFENDER_LANGUAGES {
update OFFENDER_LANGUAGES set READ_SKILL = :readSkill , SPEAK_SKILL = :speakSkill , WRITE_SKILL = :writeSkill , COMMENT_TEXT = :commentText , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , NUMERACY_SKILL = :numeracySkill , PREFERED_WRITE_FLAG = :preferedWriteFlag , PREFERED_SPEAK_FLAG = :preferedSpeakFlag , INTERPRETER_REQUESTED_FLAG = :interpreterRequestedFlag , SEAL_FLAG = :sealFlag where OFFENDER_BOOK_ID = :offenderBookId and LANGUAGE_TYPE = :languageType and LANGUAGE_CODE = :languageCode
}   

OCDLANGS_OFFPRIMLANG_DELETE_OFFENDER_LANGUAGES { 
	DELETE FROM OFFENDER_LANGUAGES where OFFENDER_BOOK_ID  = :offenderBookId and LANGUAGE_TYPE  = :languageType
}   

OCDLANGS_OFFSECLANG_FIND_OFFENDER_LANGUAGES {
 	SELECT OFFENDER_BOOK_ID ,LANGUAGE_TYPE ,LANGUAGE_CODE ,READ_SKILL ,SPEAK_SKILL ,WRITE_SKILL ,COMMENT_TEXT ,MODIFY_DATETIME ,MODIFY_USER_ID ,CREATE_DATETIME ,CREATE_USER_ID ,NUMERACY_SKILL ,PREFERED_WRITE_FLAG ,PREFERED_SPEAK_FLAG ,INTERPRETER_REQUESTED_FLAG ,SEAL_FLAG   FROM OFFENDER_LANGUAGES   WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID and LANGUAGE_TYPE = 'SEC'
}
OCDLANGS_OFFSECLANG_INSERT_OFFENDER_LANGUAGES {
insert into OFFENDER_LANGUAGES(OFFENDER_BOOK_ID , LANGUAGE_TYPE , LANGUAGE_CODE , READ_SKILL , SPEAK_SKILL , WRITE_SKILL , COMMENT_TEXT , MODIFY_DATETIME , CREATE_DATETIME , CREATE_USER_ID , NUMERACY_SKILL , PREFERED_WRITE_FLAG , PREFERED_SPEAK_FLAG , INTERPRETER_REQUESTED_FLAG , SEAL_FLAG ) values(:offenderBookId , :languageType , :languageCodeTemp , :readSkill , :speakSkill , :writeSkill , :commentText , NULL , CURRENT_TIMESTAMP , :createUserId , :numeracySkill , :preferedWriteFlag , :preferedSpeakFlag , :interpreterRequestedFlag , :sealFlag ) 
} 

OCDLANGS_OFFSECLANG_UPDATE_OFFENDER_LANGUAGES {
update OFFENDER_LANGUAGES set READ_SKILL = :readSkill , SPEAK_SKILL = :speakSkill , WRITE_SKILL = :writeSkill, LANGUAGE_CODE = :languageCodeTemp, MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId where OFFENDER_BOOK_ID = :offenderBookId and LANGUAGE_TYPE = :languageType and LANGUAGE_CODE = :languageCode
} 

OCDLANGS_OFFSECLANG_DELETE_OFFENDER_LANGUAGES { 
	DELETE FROM OFFENDER_LANGUAGES where  OFFENDER_BOOK_ID  = :offenderBookId and LANGUAGE_TYPE  = :languageType and LANGUAGE_CODE  = :languageCode
} 


OCDLANGS_OFF_BKG_ONCHECKDELETEMASTER {
	SELECT 1 FROM OFFENDER_LANGUAGES O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OCDLANGS_GET_PREFERRED_DEFAULT {
	SELECT CODE, DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'LANG' AND ACTIVE_FLAG = 'Y' AND LIST_SEQ = 1
}

OCDLANGS_PREFERRED_LANG_UPDATE_OFFENDER_LANGUAGES {
update OFFENDER_LANGUAGES set INTERPRETER_REQUESTED_FLAG = :interpreterRequestedFlag, LANGUAGE_CODE = :languageCode, MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId where OFFENDER_BOOK_ID = :offenderBookId and LANGUAGE_TYPE = :languageType
} 
OCDLANGS_LANG_WRITE_FIND_OFFENDER_LANGUAGES {
SELECT OFFENDER_BOOK_ID ,LANGUAGE_TYPE ,LANGUAGE_CODE ,READ_SKILL ,SPEAK_SKILL ,WRITE_SKILL ,COMMENT_TEXT ,MODIFY_DATETIME ,MODIFY_USER_ID ,CREATE_DATETIME ,CREATE_USER_ID ,NUMERACY_SKILL ,PREFERED_WRITE_FLAG ,PREFERED_SPEAK_FLAG ,INTERPRETER_REQUESTED_FLAG ,SEAL_FLAG   FROM OFFENDER_LANGUAGES WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID and LANGUAGE_TYPE = 'PREF_WRITE'
}
OCDLANGS_LANG_SPEAK_FIND_OFFENDER_LANGUAGES {
SELECT OFFENDER_BOOK_ID ,LANGUAGE_TYPE ,LANGUAGE_CODE ,READ_SKILL ,SPEAK_SKILL ,WRITE_SKILL ,COMMENT_TEXT ,MODIFY_DATETIME ,MODIFY_USER_ID ,CREATE_DATETIME ,CREATE_USER_ID ,NUMERACY_SKILL ,PREFERED_WRITE_FLAG ,PREFERED_SPEAK_FLAG ,INTERPRETER_REQUESTED_FLAG ,SEAL_FLAG   FROM OFFENDER_LANGUAGES WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID and LANGUAGE_TYPE = 'PREF_SPEAK'
}
