
OCDOAPOP_FIND_RGCITY {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES RC
WHERE
  RC.DOMAIN = 'CITY' AND
  ((RC.ACTIVE_FLAG = 'Y' AND RC.EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, CODE

}

OCDOAPOP_FIND_RGCOUNTY {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES
WHERE
  DOMAIN='COUNTY' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, CODE

}

OCDOAPOP_FIND_RGCOUNTRY {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES RC
WHERE
  RC.DOMAIN = 'COUNTRY' AND
  ((RC.ACTIVE_FLAG = 'Y' AND RC.EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, CODE

}

OCDOAPOP_FIND_RGTYPE {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'ADDR_TYPE' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, CODE

}

OCDOAPOP_FIND_RGSPECIALNEEDS {
 	SELECT
  DESCRIPTION, CODE
FROM REFERENCE_CODES
WHERE
  DOMAIN = 'PS_NEEDS' AND
  ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ))
ORDER BY
  LIST_SEQ, CODE

}

OCDOAPOP_FIND_RGPROVSTATECODE {
 	SELECT
  REF_CODE4.DESCRIPTION, REF_CODE4.CODE
FROM REFERENCE_CODES REF_CODE4
WHERE
  DOMAIN = 'PROV_STATE' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  REF_CODE4.LIST_SEQ, REF_CODE4.DESCRIPTION

}

OCDOAPOP_FIND_RGSTREETDIR {
 	select
	DESCRIPTION ,
	CODE
from
	REFERENCE_CODES RC
where
	RC.DOMAIN = 'STREET_DIR'
	and ((RC.ACTIVE_FLAG = 'Y'
	and RC.EXPIRED_DATE is null )
	)
order by
	LIST_SEQ ,
	CODE

}

OCDOAPOP_ADDRESS_FIND_ADDRESSES {
 	SELECT ADDRESS_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,ADDRESS_TYPE ,CITY_CODE ,COUNTRY_CODE ,VALIDATED_PAF_FLAG ,PRIMARY_FLAG ,MAIL_FLAG ,CAPACITY ,COMMENT_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,NO_FIXED_ADDRESS_FLAG ,SERVICES_FLAG ,SPECIAL_NEEDS_CODE ,CONTACT_PERSON_NAME ,BUSINESS_HOUR ,START_DATE ,END_DATE ,CITY_NAME ,PROV_STATE_CODE ,STREET ,ZIP_POSTAL_CODE ,SUITE_NUMBER ,STREET_NUMBER ,STREET_DIRECTION ,MAIL_CARE_OF ,SEAL_FLAG ,LONGITUDE,LATITUDE,MESH_BLOCK,IS_ADDRESS_VALID,ADDRESS_LINE1  FROM ADDRESSES  
}
OCDOAPOP_ADDRESS_INSERT_ADDRESSES {
	INSERT INTO ADDRESSES(ADDRESS_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,ADDRESS_TYPE ,CITY_CODE ,COUNTRY_CODE ,VALIDATED_PAF_FLAG ,PRIMARY_FLAG ,MAIL_FLAG ,CAPACITY ,COMMENT_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,NO_FIXED_ADDRESS_FLAG ,SERVICES_FLAG ,SPECIAL_NEEDS_CODE ,CONTACT_PERSON_NAME ,BUSINESS_HOUR ,START_DATE ,END_DATE ,CITY_NAME ,PROV_STATE_CODE ,STREET ,ZIP_POSTAL_CODE ,SUITE_NUMBER ,STREET_NUMBER ,STREET_DIRECTION ,MAIL_CARE_OF ,SEAL_FLAG ,LONGITUDE,LATITUDE,MESH_BLOCK,IS_ADDRESS_VALID,ADDRESS_LINE1,VALIDATED_PAYLOAD) VALUES(:addressId ,:ownerClass ,:ownerId ,:ownerSeq ,:ownerCode ,:addressType ,:cityCode ,:countryCode ,:validatedPafFlag ,:primaryFlag ,:mailFlag ,:capacity ,:commentText ,current_timestamp ,:createUserId ,null ,:noFixedAddressFlag ,:servicesFlag ,:specialNeedsCode ,:contactPersonName ,:businessHour ,:startDate ,:endDate ,:cityName ,:provStateCode ,:street ,:zipPostalCode ,:suiteNumber ,:streetNumber ,:streetDirection ,:mailCareOf ,:sealFlag ,:longitude,:latitude,:meshBlock,:isAddressValid,:streetAddress,:verifiedPayload)
}  

OCDOAPOP_ADDRESS_UPDATE_ADDRESSES {
	UPDATE ADDRESSES set OWNER_CLASS  = :ownerClass ,OWNER_ID  = :ownerId ,OWNER_SEQ  = :ownerSeq ,OWNER_CODE  = :ownerCode ,ADDRESS_TYPE  = :addressType ,CITY_CODE  = :cityCode ,COUNTRY_CODE  = :countryCode ,VALIDATED_PAF_FLAG  = :validatedPafFlag ,PRIMARY_FLAG  = :primaryFlag ,MAIL_FLAG  = :mailFlag ,CAPACITY  = :capacity ,COMMENT_TEXT  = :commentText  ,MODIFY_DATETIME  = current_timestamp ,MODIFY_USER_ID  = :modifyUserId ,NO_FIXED_ADDRESS_FLAG  = :noFixedAddressFlag ,SERVICES_FLAG  = :servicesFlag ,SPECIAL_NEEDS_CODE  = :specialNeedsCode ,CONTACT_PERSON_NAME  = :contactPersonName ,BUSINESS_HOUR  = :businessHour ,START_DATE  = :startDate ,END_DATE  = :endDate ,CITY_NAME  = :cityName ,PROV_STATE_CODE  = :provStateCode ,STREET  = :street ,ZIP_POSTAL_CODE  = :zipPostalCode ,SUITE_NUMBER  = :suiteNumber ,STREET_NUMBER  = :streetNumber ,STREET_DIRECTION  = :streetDirection ,MAIL_CARE_OF  = :mailCareOf ,SEAL_FLAG  = :sealFlag,LONGITUDE=:longitude,LATITUDE=:latitude,MESH_BLOCK=:meshBlock,IS_ADDRESS_VALID=:isAddressValid,ADDRESS_LINE1=:streetAddress,VALIDATED_PAYLOAD=:verifiedPayload  WHERE ADDRESS_ID  = :addressId 
}  

OCDOAPOP_ADDRESS_DELETE_ADDRESSES { 
	DELETE FROM ADDRESSES WHERE ADDRESS_ID  = :addressId 
}  


OCDOAPOP_ADDRESS_WHENCREATERECORD_ {
	SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'COUNTRY' AND LIST_SEQ = 1
}

OCDOAPOP_ADDRESS_KEYDELREC {
	SELECT * FROM PHONES WHERE OWNER_CLASS = 'ADDR' AND OWNER_ID = :OWNER_ID
}

OCDOAPOP_OCDOAPOP_PREINSERT {
	
	SELECT NEXTVAL('ADDRESS_ID')   FROM DUAL 
}

OCDOAPOP_VALIDATE_CITY_INFO_CODE {
	SELECT COUNT(1) FROM REFERENCE_CODES WHERE DOMAIN = 'CITY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL AND UPPER(DESCRIPTION) LIKE LV_DESCRIPTION||'%'
}

OCDOAPOP_VALIDATE_CITY_INFO_DESCRIPTION {
	SELECT CODE, DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = 'CITY' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL AND UPPER(DESCRIPTION) LIKE LV_DESCRIPTION||'%'
}

OCDOAPOP_CITY_SYSTEM_PROFILE_ {
	SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'MAN_CITY_FLD'
}
