
OCDPERSO_FIND_RGCONTACTTYPE {
 	SELECT REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.CODE  CODE, REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'CONTACTS'  AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ
}

OCDPERSO_FIND_RGRELTYPE {
select RC.DESCRIPTION DESCRIPTION , RC.CODE CODE,CPT.list_seq LIST_SEQ,CPT.ACTIVE_FLAG from REFERENCE_CODES RC,CONTACT_PERSON_TYPES CPT  where
CPT.relationship_type =RC.code and 
RC."domain" ='RELATIONSHIP'
 and CPT.contact_type =:contactType order by list_seq 
}

OCDPERSO_FIND_RGLANGUAGECODE {
	SELECT   DESCRIPTION, CODE, ACTIVE_FLAG   FROM REFERENCE_CODES    WHERE DOMAIN = 'LANG' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY DESCRIPTION, LIST_SEQ
}

OCDPERSO_FIND_RGMARITALSTATUS {
	SELECT   DESCRIPTION NBT_MARITAL_STATUS ,          CODE MARITAL_STATUS     FROM REFERENCE_CODES    WHERE DOMAIN = 'MARITAL_STAT' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ
}

OCDPERSO_FIND_RGSEXCODE {
		SELECT DESCRIPTION NBT_SEX_CODE ,        CODE SEX_CODE    FROM REFERENCE_CODES  WHERE DOMAIN = 'SEX'  AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ
}

OCDPERSO_FIND_RGSEARCHTYPE {
	SELECT DESCRIPTION NBT_SEARCH_TYPE ,         CODE SEARCH_TYPE    FROM REFERENCE_CODES   WHERE DOMAIN = 'SEARCH_TYPE'  AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' )  ORDER BY LIST_SEQ
}

OCDPERSO_FIND_RGIDENTIFIERTYPE {
 	SELECT   DESCRIPTION  ,          CODE      FROM REFERENCE_CODES    WHERE DOMAIN = 'ID_TYPE' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ) OR '' = 'ENTER-QUERY' ) ORDER BY LIST_SEQ , CODE
}

OCDPERSO_OFFCNTPER_FIND_OFFENDER_CONTACT_PERSONS {
	SELECT OFFENDER_BOOK_ID ,PERSON_ID ,CONTACT_TYPE ,RELATIONSHIP_TYPE ,APPROVED_VISITOR_FLAG ,CASELOAD_TYPE ,MODIFY_DATETIME ,MODIFY_USER_ID ,COMMENT_TEXT ,CASE_INFO_NUMBER ,AWARE_OF_CHARGES_FLAG ,CAN_BE_CONTACTED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,EMERGENCY_CONTACT_FLAG ,NEXT_OF_KIN_FLAG ,ACTIVE_FLAG ,EXPIRY_DATE ,OFFENDER_CONTACT_PERSON_ID ,CONTACT_ROOT_OFFENDER_ID ,SEAL_FLAG   FROM OFFENDER_CONTACT_PERSONS   WHERE  OFFENDER_BOOK_ID = :offenderBookId and person_id is not null 
}
OCDPERSO_OFFCNTPER_INSERT_OFFENDER_CONTACT_PERSONS {
 insert into OFFENDER_CONTACT_PERSONS(OFFENDER_BOOK_ID , PERSON_ID , CONTACT_TYPE , RELATIONSHIP_TYPE , APPROVED_VISITOR_FLAG , CASELOAD_TYPE , COMMENT_TEXT , CASE_INFO_NUMBER , AWARE_OF_CHARGES_FLAG , CAN_BE_CONTACTED_FLAG , CREATE_DATETIME , CREATE_USER_ID , EMERGENCY_CONTACT_FLAG , NEXT_OF_KIN_FLAG , ACTIVE_FLAG , EXPIRY_DATE , OFFENDER_CONTACT_PERSON_ID , CONTACT_ROOT_OFFENDER_ID , SEAL_FLAG, MODIFY_DATETIME) values(:offenderBookId , :personId , :contactType , :relationshipType , :approvedVisitorFlag , :caseloadType , :commentText , :caseInfoNumber , :awareOfChargesFlag , :canBeContactedFlag , current_timestamp, :createUserId , :emergencyContactFlag , :nextOfKinFlag , :activeFlag , :expiryDate , nextval('OFFENDER_CONTACT_PERSON_ID'), :contactRootOffenderId , :sealFlag, NUll) 
}

OCDPERSO_OFFCNTPER_UPDATE_OFFENDER_CONTACT_PERSONS {
update OFFENDER_CONTACT_PERSONS set OFFENDER_BOOK_ID = :offenderBookId , PERSON_ID = :personId , CONTACT_TYPE = :contactType , RELATIONSHIP_TYPE = :relationshipType , APPROVED_VISITOR_FLAG = :approvedVisitorFlag , CASELOAD_TYPE = :caseloadType , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , COMMENT_TEXT = :commentText , CASE_INFO_NUMBER = :caseInfoNumber , AWARE_OF_CHARGES_FLAG = :awareOfChargesFlag , CAN_BE_CONTACTED_FLAG = :canBeContactedFlag , EMERGENCY_CONTACT_FLAG = :emergencyContactFlag , NEXT_OF_KIN_FLAG = :nextOfKinFlag , ACTIVE_FLAG = :activeFlag , EXPIRY_DATE = :expiryDate , OFFENDER_CONTACT_PERSON_ID = :offenderContactPersonId , CONTACT_ROOT_OFFENDER_ID = :contactRootOffenderId , SEAL_FLAG = :sealFlag where OFFENDER_CONTACT_PERSON_ID = :offenderContactPersonId	
}

OCDPERSO_OFFCNTPER_DELETE_OFFENDER_CONTACT_PERSONS { 
	DELETE FROM OFFENDER_CONTACT_PERSONS where OFFENDER_CONTACT_PERSON_ID = :offenderContactPersonId
}

OCDPERSO_PERADDR_FIND_V_PERSON_ADDRESSES {
	select ADDRESS_ID , ADDRESS_TYPE , ADDRESS_TYPE_DESC , PERSON_ID , START_DATE , END_DATE , ACTIVE_FLAG , HOUSE , STREET , AREA , COUNTRY , SUITE_NUMBER , STREET_NUMBER , STREET_DIRECTION , STREET_INFORMATION , CITY_CODE , CITY_NAME , PROV_STATE_CODE , PROV_STATE_DESC , ZIP_POSTAL_CODE , COUNTRY_CODE , COMMENT_TEXT , PRIMARY_FLAG , MAIL_FLAG , VALIDATED_FLAG,IS_ADDRESS_VALID,ADDRESS_LINE1  from V_PERSON_ADDRESSES where PERSON_ID = :personId order by primary_flag desc, mail_flag desc, active_flag desc, coalesce ( start_date, '01-JAN-1900' ) desc
}
OCDPERSO_PERIDENT_FIND_PERSON_IDENTIFIERS {
 	SELECT PERSON_ID ,ID_SEQ ,IDENTIFIER_TYPE ,IDENTIFIER ,ISSUED_AUTHORITY_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,ISSUED_DATE ,SEAL_FLAG   FROM PERSON_IDENTIFIERS   where  PERSON_ID = :personId
}
OCDPERSO_PERIDENT_INSERT_PERSON_IDENTIFIERS {
insert into PERSON_IDENTIFIERS(PERSON_ID , ID_SEQ , IDENTIFIER_TYPE , IDENTIFIER , ISSUED_AUTHORITY_TEXT , CREATE_DATETIME , CREATE_USER_ID , ISSUED_DATE , SEAL_FLAG, MODIFY_DATETIME) values(:personId , :idSeq , :identifierType , :identifier , :issuedAuthorityText , current_timestamp , :createUserId , :issuedDate , :sealFlag, NULL)
}

OCDPERSO_PERIDENT_UPDATE_PERSON_IDENTIFIERS {
update PERSON_IDENTIFIERS set PERSON_ID = :personId , ID_SEQ = :idSeq , IDENTIFIER_TYPE = :identifierType , IDENTIFIER = :identifier , ISSUED_AUTHORITY_TEXT = :issuedAuthorityText , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , ISSUED_DATE = :issuedDate , SEAL_FLAG = :sealFlag where PERSON_ID = :personId and ID_SEQ = :idSeq
}

OCDPERSO_PERIDENT_DELETE_PERSON_IDENTIFIERS { 
	DELETE FROM PERSON_IDENTIFIERS where PERSON_ID  = :personId AND ID_SEQ  = :idSeq
}

OCDPERSO_PERINFO_FIND_PERSONS {
 	SELECT PERSON_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,BIRTHDATE ,OCCUPATION_CODE ,CRIMINAL_HISTORY_TEXT ,NAME_TYPE ,ALIAS_PERSON_ID ,ROOT_PERSON_ID ,LANGUAGE_CODE ,COMPREHEND_ENGLISH_FLAG ,SEX ,BIRTH_PLACE ,EMPLOYER ,PROFILE_CODE ,INTERPRETER_REQUIRED ,PRIMARY_LANGUAGE_CODE ,MEMO_TEXT ,SUSPENDED_FLAG ,MARITAL_STATUS ,CITIZENSHIP ,DECEASED_DATE ,CORONER_NUMBER ,ATTENTION ,CARE_OF ,SUSPENDED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,STAFF_FLAG ,REMITTER_FLAG ,LAST_NAME_SOUNDEX ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,LAST_NAME_KEY ,SEAL_FLAG   FROM PERSONS WHERE PERSON_ID = :personId
}
OCDPERSO_PERINFO_UPDATE_PERSONS {
	update PERSONS set PERSON_ID = :personId , LAST_NAME = :lastName , FIRST_NAME = :firstName , MIDDLE_NAME = :middleName , BIRTHDATE = :birthdate , OCCUPATION_CODE = :occupationCode , CRIMINAL_HISTORY_TEXT = :criminalHistoryText , NAME_TYPE = :nameType , ALIAS_PERSON_ID = :aliasPersonId , LANGUAGE_CODE = :languageCode , COMPREHEND_ENGLISH_FLAG = :comprehendEnglishFlag , SEX = :sex , BIRTH_PLACE = :birthPlace , EMPLOYER = :employer , PROFILE_CODE = :profileCode , INTERPRETER_REQUIRED = :interpreterRequired , PRIMARY_LANGUAGE_CODE = :primaryLanguageCode , MEMO_TEXT = :memoText , SUSPENDED_FLAG = :suspendedFlag , MARITAL_STATUS = :maritalStatus , CITIZENSHIP = :citizenship , DECEASED_DATE = :deceasedDate , CORONER_NUMBER = :coronerNumber , ATTENTION = :attention , CARE_OF = :careOf , SUSPENDED_DATE = :suspendedDate , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , STAFF_FLAG = :staffFlag , REMITTER_FLAG = :remitterFlag , LAST_NAME_SOUNDEX = :lastNameSoundex , FIRST_NAME_KEY = :firstNameKey , MIDDLE_NAME_KEY = :middleNameKey , LAST_NAME_KEY = :lastNameKey , SEAL_FLAG = :sealFlag where PERSON_ID = :personId
}

OCDPERSO_PEREMP_FIND_PERSON_EMPLOYMENTS {
 	SELECT PERSON_ID ,EMPLOYMENT_SEQ ,OCCUPATION_CODE ,EMPLOYER_NAME ,HOURS_WEEK ,SCHEDULE_TYPE ,WAGE ,WAGE_PERIOD_CODE ,SUPERVISOR_NAME ,ADDRESS_1 ,ADDRESS_2 ,CITY ,PROV_STATE_CODE ,CONTACT_NUMBER ,CONTACT_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,EMPLOYMENT_DATE ,COMMENT_TEXT ,TERMINATION_DATE ,PHONE_AREA ,PHONE_EXT ,CREATE_DATETIME ,CREATE_USER_ID ,ACTIVE_FLAG ,ADDRESS ,SEAL_FLAG,FORMAT   FROM PERSON_EMPLOYMENTS    WHERE PERSON_ID = :personId   order by employment_seq desc
}
OCDPERSO_PEREMP_INSERT_PERSON_EMPLOYMENTS {
 insert into PERSON_EMPLOYMENTS(PERSON_ID , EMPLOYMENT_SEQ , OCCUPATION_CODE , EMPLOYER_NAME , HOURS_WEEK , SCHEDULE_TYPE , WAGE , WAGE_PERIOD_CODE , SUPERVISOR_NAME , ADDRESS_1 , ADDRESS_2 , CITY , PROV_STATE_CODE , CONTACT_NUMBER , CONTACT_TYPE , MODIFY_DATETIME , EMPLOYMENT_DATE , COMMENT_TEXT , TERMINATION_DATE , PHONE_AREA , PHONE_EXT , CREATE_DATETIME , CREATE_USER_ID , ACTIVE_FLAG , ADDRESS , SEAL_FLAG, FORMAT ) values(:personId , :employmentSeq , :occupationCode , :employerName , :hoursWeek , :scheduleType , :wage , :wagePeriodCode , :supervisorName , :address1 , :address2 , :city , :provStateCode , :contactNumber , :contactType , NULL , :employmentDate , :commentText , :terminationDate , :phoneArea , :phoneExt , current_timestamp, :createUserId , :activeFlag , :address , :sealFlag , :format) 
}

OCDPERSO_PEREMP_UPDATE_PERSON_EMPLOYMENTS {
	update PERSON_EMPLOYMENTS set PERSON_ID = :personId , EMPLOYMENT_SEQ = :employmentSeq , OCCUPATION_CODE = :occupationCode , EMPLOYER_NAME = :employerName , HOURS_WEEK = :hoursWeek , SCHEDULE_TYPE = :scheduleType , WAGE = :wage , WAGE_PERIOD_CODE = :wagePeriodCode , SUPERVISOR_NAME = :supervisorName , ADDRESS_1 = :address1 , ADDRESS_2 = :address2 , CITY = :city , PROV_STATE_CODE = :provStateCode , CONTACT_NUMBER = :contactNumber , CONTACT_TYPE = :contactType , MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = current_timestamp, EMPLOYMENT_DATE = :employmentDate , COMMENT_TEXT = :commentText , TERMINATION_DATE = :terminationDate , PHONE_AREA = :phoneArea , PHONE_EXT = :phoneExt , ACTIVE_FLAG = :activeFlag , ADDRESS = :address , SEAL_FLAG = :sealFlag ,FORMAT=:format   where PERSON_ID = :personId and EMPLOYMENT_SEQ = :employmentSeq
}

OCDPERSO_PEREMP_DELETE_PERSON_EMPLOYMENTS { 
	DELETE FROM PERSON_EMPLOYMENTS WHERE PERSON_ID  = :personId AND EMPLOYMENT_SEQ  = :employmentSeq
}


OCDPERSO_OFF_BKG_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM OFFENDER_CONTACT_PERSONS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OCDPERSO_CHECK_DUPLICATE_CONTACTS_ {
	SELECT PERSON_ID FROM OFFENDER_CONTACT_PERSONS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

OCDPERSO_CHANGE_ACTIVE_FLAG_ {
	SELECT COUNT(PERSON_ID) FROM OFFENDER_CONTACT_PERSONS WHERE OFFENDER_BOOK_ID = :OFFENDERBOOKID AND ACTIVE_FLAG = 'Y' AND PERSON_ID   = :PERSONID
}

OCUOCCUP_CHECKCHILDRECORDSCURONE {
SELECT COUNT(*)
      FROM offender_visits ov, offender_visit_visitors ovv where ov.offender_book_id = :offenderBookId 
       and ov.offender_visit_id = ovv.offender_visit_id  
       and ovv.PERSON_ID = :personId
}

OCUOCCUP_CHECKCHILDRECORDSCURTWO{
SELECT COUNT (*)
        FROM offender_contact_persons ocp, offender_person_restricts opr
      WHERE ocp.OFFENDER_BOOK_ID = :offenderBookId
        AND ocp.person_id =  :personId
        AND ocp.offender_contact_person_id = opr.offender_contact_person_id
}

OCUOCCUP_CHECKFUTUREVISITS {
SELECT COUNT (*)
        FROM offender_visits
       WHERE offender_book_id = :offenderBookId
       AND offender_visit_id IN (SELECT offender_visit_id
                                    FROM offender_visit_visitors
                                  WHERE person_id = :personId AND event_outcome = 'ATT') AND end_time >= current_date AND visit_status = 'SCH'

}
GET_ORDER_BY{
SELECT last_name, first_name, middle_name FROM persons WHERE person_id = :p_person_id
}