
OCUVERIF_WORKFL_FIND_WORK_FLOW_LOGS {
 	SELECT WORK_FLOW_ID ,WORK_FLOW_SEQ ,WORK_ACTION_CODE ,WORK_ACTION_DATE ,ACTION_USER_ID ,WORK_FLOW_STATUS ,CREATE_DATE ,LOCATE_AGY_LOC_ID ,CREATE_USER_ID ,CREATE_DATETIME ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG, comment   FROM WORK_FLOW_LOGS 
}

OCUVERIF_CGWHEN_NEW_FORM_INSTANCE_ { -- No Need to Migrate, There is no use of this query   
	SELECT  SYSDATE, USER FROM   SYS.DUAL
}

OCUVERIF_WORK_FLOW_ID {
SELECT WORK_FLOW_ID  FROM   WORK_FLOWS WHERE  OBJECT_CODE = 'ALERT' AND  OBJECT_ID  = :V_BOOK_ID AND   OBJECT_SEQ  = :V_ALERT_SEQ
}

OCUVERIF_GET_WORK_FLOW_SEQ {
SELECT coalesce (MAX (WORK_FLOW_SEQ), 0) + 1 FROM WORK_FLOW_LOGS WHERE WORK_FLOW_ID = :WORK_FLOW_ID
}
OCUVERIF_WORK_FLOW_COMMIT {
insert into WORK_FLOW_LOGS(WORK_FLOW_ID, WORK_FLOW_SEQ, CREATE_USER_ID, CREATE_DATE, WORK_ACTION_CODE, WORK_FLOW_STATUS, CREATE_DATETIME, MODIFY_DATETIME) values(:workFlowId, :workFlowSeq, :createUserId, :createDate, :workActionCode, :workFlowStatus, current_timestamp, null) 
}
 
 OCUVERIF_OFF_ALERT_UPDATE {
update OFFENDER_ALERTS set VERIFIED_FLAG = :verifiedFlag, modify_user_id = :modifyUserId, modify_datetime = current_timestamp where OFFENDER_BOOK_ID = :offenderBookId and ALERT_SEQ = :alertSeq
 }
 
 OCUVERIF_GET_USER_NAME{
 select last_name || ',' || ' '  || first_name  from staff_members sm  where user_id =:userId
 }
 OCUVERIF_OFF_VERIFY_UPDATE{
 update WORK_FLOW_LOGS set WORK_FLOW_STATUS = :status, comment = :comment, modify_datetime = current_timestamp,modify_user_id = :modifyUserId ,WORK_ACTION_CODE=:workActionCode where WORK_FLOW_ID = :workFlowId and WORK_FLOW_SEQ = :workFlowSeq
}

OCUVERIF_WORK_FLOW_INSERT {
  insert into WORK_FLOW_LOGS(WORK_FLOW_ID, WORK_FLOW_SEQ, CREATE_USER_ID, CREATE_DATE, WORK_ACTION_CODE, WORK_FLOW_STATUS, CREATE_DATETIME, MODIFY_DATETIME, comment) values(:workFlowId, :workFlowSeq, :createUserId, :createDate, :workActionCode,  :status, current_timestamp, null, :comment) 
}
OCUVERIF_UPDATE_CASEPLAN_NEXTREVIEW_DATE{
update CASE_PLANS set next_review_date=:nextReviewDate,modify_datetime=current_timestamp,modify_user_id=:modifyUserId,verified_flag =:verifiedFlag
where offender_book_id =:offenderBookId and case_plan_id =:casePlanId 
}
OCUVERIF_OFFENDER_SECURITY_LEVEL{
SELECT OFF_ASS.REVIEW_SUP_LEVEL_TYPE FROM OFFENDER_ASSESSMENTS OFF_ASS WHERE OFF_ASS.OFFENDER_BOOK_ID = :offenderBookId 
AND OFF_ASS.ASSESSMENT_SEQ = 
(SELECT MAX(OFF_ASS.ASSESSMENT_SEQ) FROM OFFENDER_ASSESSMENTS OFF_ASS, ASSESSMENTS ASS WHERE OFF_ASS.OFFENDER_BOOK_ID =
:offenderBookId AND OFF_ASS.ASSESSMENT_TYPE_ID = ASS.ASSESSMENT_ID AND ASS.CASELOAD_TYPE =
(SELECT CL.CASELOAD_TYPE FROM STAFF_MEMBERS SM, CASELOADS CL WHERE SM.USER_ID = :createUserId AND SM.WORKING_CASELOAD_ID = CL.CASELOAD_ID)
AND ASS.DETERMINE_SUP_LEVEL_FLAG ='Y' 
AND OFF_ASS.REVIEW_SUP_LEVEL_TYPE IS NOT null)
}
OCUVERIF_CASE_PLANS_UN_CLASS
{
SELECT PROFILE_VALUE
       FROM   SYSTEM_PROFILES
       WHERE  PROFILE_TYPE = 'CLIENT'
       AND    PROFILE_CODE = 'PENDING_STAT'
}
OCUVERIF_CASE_PLANS_PREINSERT {
	SELECT  REVIEW_PERIOD FROM  CASE_REVIEW_PERIODS WHERE  SUPERVISION_LEVEL = :supervisionLevel
}