
	OIDPINFO_FIND_CGFKOFFNAMEDSPDESCRIPTION {
 SELECT REFERENCE_CODES1.DESCRIPTION DSP_DESCRIPTION, REFERENCE_CODES1.LIST_SEQ DSP_LIST_SEQ, REFERENCE_CODES1.CODE BIRTH_COUNTRY_CODE FROM REFERENCE_CODES REFERENCE_CODES1 WHERE DOMAIN = 'COUNTRY' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL )) ORDER BY REFERENCE_CODES1.LIST_SEQ, REFERENCE_CODES1.DESCRIPTION

}

	OIDPINFO_FIND_CGFKOFFPDDSPDESCRIPTION {
    SELECT PFL_CODE.DESCRIPTION DESCRIPTION , PFL_CODE.PROFILE_TYPE, PFL_CODE.LIST_SEQ DSP_LIST_SEQ,
  PFL_CODE.PROFILE_CODE PROFILE_CODE, PFL_CODE.ACTIVE_FLAG FROM PROFILE_CODES PFL_CODE 
  WHERE 
   (:PROFILETYPE IN (SELECT PROFILE_TYPE FROM PROFILE_TYPES
  WHERE CODE_VALUE_TYPE = 'CODE' AND PROFILE_CATEGORY='PI' ) AND PROFILE_TYPE = :PROFILETYPE )
  OR (:PROFILETYPE IN (SELECT PROFILE_TYPE FROM PROFILE_TYPES WHERE CODE_VALUE_TYPE = 'TEXT' )
  AND PROFILE_CODE = 'XXX' ) ORDER BY PFL_CODE.LIST_SEQ, PFL_CODE.DESCRIPTION
}

	OIDPINFO_FIND_RGBIRTHSTATE {
 SELECT REFERENCE_CODES.DESCRIPTION, REFERENCE_CODES.CODE FROM REFERENCE_CODES REFERENCE_CODES WHERE DOMAIN = 'PROV_STATE' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL )) ORDER BY REFERENCE_CODES.LIST_SEQ, REFERENCE_CODES.DESCRIPTION

}

OIDPINFO_OFFNAME_FIND_OFFENDERS {
 SELECT OFFENDER_ID, OFFENDER_NAME_SEQ, ID_SOURCE_CODE, LAST_NAME, NAME_TYPE, FIRST_NAME, MIDDLE_NAME, BIRTH_DATE, SEX_CODE, SUFFIX, LAST_NAME_SOUNDEX, BIRTH_PLACE, BIRTH_COUNTRY_CODE, CREATE_DATE, LAST_NAME_KEY, ALIAS_OFFENDER_ID, FIRST_NAME_KEY, MIDDLE_NAME_KEY, OFFENDER_ID_DISPLAY, ROOT_OFFENDER_ID, CASELOAD_TYPE, MODIFY_USER_ID, MODIFY_DATETIME, ALIAS_NAME_TYPE, PARENT_OFFENDER_ID, UNIQUE_OBLIGATION_FLAG, SUSPENDED_FLAG, SUSPENDED_DATE, RACE_CODE, REMARK_CODE, ADD_INFO_CODE, BIRTH_COUNTY, BIRTH_STATE, MIDDLE_NAME_2, TITLE, AGE, CREATE_USER_ID, LAST_NAME_ALPHA_KEY, CREATE_DATETIME, NAME_SEQUENCE, SEAL_FLAG FROM OFFENDERS

}

OIDPINFO_OFFNAME_UPDATE_OFFENDERS {
UPDATE OFFENDERS set BIRTH_PLACE  = :birthPlace ,BIRTH_COUNTRY_CODE  = :birthCountryCode ,BIRTH_STATE  = :birthState,MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME =current_timestamp where
OFFENDER_ID = :offenderId
} 

OIDPINFO_OFFPD_FIND_OFFENDER_PROFILE_DETAILS {
 	SELECT OFFENDER_BOOK_ID , OPD.PROFILE_SEQ ,OPD.PROFILE_TYPE ,OPD.PROFILE_CODE ,OPD.LIST_SEQ ,COMMENT_TEXT ,CASELOAD_TYPE ,OPD.MODIFY_USER_ID ,OPD.MODIFY_DATETIME ,OPD.CREATE_DATETIME ,OPD.CREATE_USER_ID ,OPD.SEAL_FLAG,PT.CODE_VALUE_TYPE,PT.UPDATED_ALLOWED_FLAG,PT.MANDATORY_FLAG  FROM OFFENDER_PROFILE_DETAILS OPD INNER JOIN PROFILE_TYPES PT ON OPD.PROFILE_TYPE = PT.PROFILE_TYPE where OFFENDER_BOOK_ID = :OFFENDERBOOKID and PT.ACTIVE_FLAG = 'Y' ORDER BY LIST_SEQ , PROFILE_TYPE
}

OIDPINFO_OFFPD_UPDATE_OFFENDER_PROFILE_DETAILS {
UPDATE OFFENDER_PROFILE_DETAILS set PROFILE_CODE = :profileCode , LIST_SEQ = :listSeq ,COMMENT_TEXT = :commentText ,CASELOAD_TYPE = :caseloadType ,MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME =current_timestamp, SEAL_FLAG = :sealFlag where OFFENDER_BOOK_ID = :offenderBookId and PROFILE_SEQ = :profileSeq and PROFILE_TYPE = :profileType 
}   


	OIDPINFO_OFF_BKG_ONCHECKDELETEMASTER_OFF_PD_CUR {
 SELECT 1 FROM OFFENDER_PROFILE_DETAILS O WHERE O.OFFENDER_BOOK_ID = :OFFENDERBOOKID
}

	OIDPINFO_OFF_NAME_POSTQUERY_C_OFF_BIRTH_STATE {
 SELECT DESCRIPTION FROM   REFERENCE_CODES WHERE  CODE = :code AND    DOMAIN = 'PROV_STATE'
}

	OIDPINFO_PROFILE_CODE_POSTCHANGE {
 SELECT CODE_VALUE_TYPE LV_TEMP FROM   PROFILE_TYPES WHERE  PROFILE_TYPE = :PROFILE_TYPE
}

	OIDPINFO_DSP_DESCRIPTION_WHENVALIDATEITEM_PROFILE_TYPES_C {
 SELECT CODE_VALUE_TYPE FROM PROFILE_TYPES WHERE PROFILE_TYPE = :PROFILE_TYPE
}

	OIDPINFO_OFF_PD_WHENNEWRECORDINSTANCE_PROFILE_TYPES_C {
 SELECT CODE_VALUE_TYPE FROM PROFILE_TYPES WHERE PROFILE_TYPE = :PROFILETYPE
}

OIDPINFO_CGFKCHK_OFF_NAME_OFF_REF_CODE_C {
 SELECT REFERENCE_CODES1.DESCRIPTION, REFERENCE_CODES1.LIST_SEQ FROM REFERENCE_CODES REFERENCE_CODES1 WHERE REFERENCE_CODES1.CODE = :BIRTHCOUNTRYCODE AND DOMAIN = 'COUNTRY' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL))

}

OIDPINFO_CGFKLKP_OFF_NAME_OFF_REF_CODE_C {
SELECT REFERENCE_CODES1.CODE, REFERENCE_CODES1.LIST_SEQ FROM REFERENCE_CODES REFERENCE_CODES1 WHERE REFERENCE_CODES1.DESCRIPTION = :DSPDESCRIPTION AND DOMAIN = 'COUNTRY' AND ((ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL))
}

OIDPINFO_CGWHEN_NEW_FORM_INSTANCE_C {
 SELECT  SYSDATE(), UPPER(USER) FROM   DUAL
}

OIDPINFO_CGFKCHK_OFF_PD_OFF_PD_PFL_TYP_C {
 SELECT PFL_TYPE.DESCRIPTION FROM   PROFILE_TYPES PFL_TYPE WHERE  PFL_TYPE.PROFILE_TYPE = :PROFILETYPE and profile_category = 'PI'
}

OIDPINFO_CGFKCHK_OFF_PD_OFF_PD_PFL_COD_C {
 SELECT PFL_CODE.PROFILE_TYPE, PFL_CODE.DESCRIPTION, PFL_CODE.LIST_SEQ FROM PROFILE_CODES PFL_CODE WHERE PFL_CODE.PROFILE_CODE = :PROFILECODE AND ( ((ACTIVE_FLAG = 'Y' AND EXPIRY_DATE IS NULL)) AND (:PROFILETYPE IN (SELECT PROFILE_TYPE FROM PROFILE_TYPES WHERE CODE_VALUE_TYPE = 'CODE') AND PROFILE_TYPE = :PROFILETYPE) OR (:PROFILETYPE IN (SELECT PROFILE_TYPE FROM PROFILE_TYPES WHERE CODE_VALUE_TYPE = 'TEXT') AND PROFILE_CODE = 'XXX'))
}

OIDPINFO_CGFKLKP_OFF_PD_OFF_PD_PFL_COD {
 SELECT CODE_VALUE_TYPE FROM   PROFILE_TYPES OFF_PD WHERE  PROFILE_TYPE = OFF_PD.PROFILE_TYPE
}

OIDPINFO_CGFKLKP_OFF_PD_OFF_PD_PFL_COD_C {
select PFL_CODE.PROFILE_CODE, PFL_CODE.PROFILE_TYPE, PFL_CODE.LIST_SEQ from PROFILE_CODES PFL_CODE where PFL_CODE.DESCRIPTION = :DSPDESCRIPTION2 and ((ACTIVE_FLAG = 'Y' and EXPIRY_DATE is null)) and (:PROFILETYPE in ( select PROFILE_TYPE from PROFILE_TYPES where CODE_VALUE_TYPE = 'CODE') and PROFILE_TYPE = :PROFILETYPE) or (:PROFILETYPE in ( select PROFILE_TYPE from PROFILE_TYPES where CODE_VALUE_TYPE = 'TEXT') and PROFILE_CODE = 'XXX')
}

