
OIDPIDEN_FIND_RGPROFILE {
SELECT PFL_CODE.DESCRIPTION DSP_DESCRIPTION2, PFL_CODE.PROFILE_TYPE DSP_PROFILE_TYPE, PFL_CODE.LIST_SEQ DSP_LIST_SEQ ,PFL_CODE.PROFILE_CODE PROFILE_CODE, PFL_CODE.ACTIVE_FLAG FROM  PROFILE_CODES PFL_CODE, PROFILE_TYPES PFL_TYP  
 	WHERE PFL_TYP.PROFILE_TYPE = PFL_CODE.PROFILE_TYPE      
 	AND PFL_CODE.PROFILE_TYPE = :profileType      
 	AND PFL_TYP.CODE_VALUE_TYPE = 'CODE'   
 	AND PFL_TYP.PROFILE_CATEGORY = 'PA'   
 	AND PFL_CODE.ACTIVE_FLAG = 'Y'    
 	AND PFL_CODE.EXPIRY_DATE IS NULL  ORDER BY PFL_CODE.LIST_SEQ , PFL_CODE.DESCRIPTION
}
	OIDPIDEN_FIND_RGMARKTYPE {
 SELECT DESCRIPTION         ,LIST_SEQ          ,CODE     FROM REFERENCE_CODES   WHERE DOMAIN = 'MARK_TYPE'    AND (ACTIVE_FLAG = 'Y' OR :MODE = 'QUERY' ) ORDER BY LIST_SEQ , DESCRIPTION
}
	OIDPIDEN_FIND_RGBODYPART {
 SELECT DESCRIPTION         ,LIST_SEQ          ,CODE     FROM REFERENCE_CODES  WHERE DOMAIN = 'BODY_PART'     AND (ACTIVE_FLAG = 'Y' OR :MODE = 'QUERY' ) ORDER BY LIST_SEQ , DESCRIPTION
}
	OIDPIDEN_FIND_RGSIDE {
 SELECT DESCRIPTION          ,LIST_SEQ          ,CODE    FROM REFERENCE_CODES   WHERE DOMAIN = 'SIDE'     AND (ACTIVE_FLAG = 'Y' OR :MODE = 'QUERY' ) ORDER BY LIST_SEQ , DESCRIPTION
}
	OIDPIDEN_FIND_RGPARTORIENT {
 SELECT DESCRIPTION         ,LIST_SEQ         ,CODE     FROM REFERENCE_CODES   WHERE DOMAIN = 'PART_ORIENT'      AND (ACTIVE_FLAG = 'Y' OR :MODE = 'QUERY' ) ORDER BY LIST_SEQ , DESCRIPTION
}
	OIDPIDEN_FIND_RGRACECODE {
 SELECT  RC.DESCRIPTION  ,                 RC.CODE      FROM  REFERENCE_CODES  RC   WHERE  RC.DOMAIN IN ('ETHNICITY' )         AND  (RC.ACTIVE_FLAG = 'Y'          AND  RC.EXPIRED_DATE  IS NULL ) ORDER BY  RC.LIST_SEQ
}
OIDPIDEN_OFFPA_FIND_OFFENDER_PHYSICAL_ATTRIBUTES {
 SELECT OFFENDER_BOOK_ID ,ATTRIBUTE_SEQ ,HEIGHT_FT ,HEIGHT_IN ,HEIGHT_CM ,WEIGHT_LBS ,WEIGHT_KG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_PHYSICAL_ATTRIBUTES  where OFFENDER_BOOK_ID = :offenderBookId 
}

OIDPIDEN_VERIFY_OFFENDER_BOOK_ID {
SELECT count(*) FROM OFFENDER_PHYSICAL_ATTRIBUTES where OFFENDER_BOOK_ID =:offenderBookId
}

OIDPIDEN_OFFPA_INSERT_OFFENDER_PHYSICAL_ATTRIBUTES {
insert into OFFENDER_PHYSICAL_ATTRIBUTES(OFFENDER_BOOK_ID , ATTRIBUTE_SEQ , HEIGHT_FT , HEIGHT_IN , HEIGHT_CM , WEIGHT_LBS , WEIGHT_KG , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG,modify_datetime ) values(:offenderBookId , :attributeSeq , :heightFt , :heightIn , :heightCm , :weightLbs , :weightKg , CURRENT_TIMESTAMP, :createUserId , :sealFlag,NUll )
}

OIDPIDEN_OFFPA_UPDATE_OFFENDER_PHYSICAL_ATTRIBUTES {
update OFFENDER_PHYSICAL_ATTRIBUTES set  HEIGHT_FT = :heightFt,HEIGHT_IN =:heightIn,HEIGHT_CM =:heightCm,WEIGHT_LBS =:weightLbs,WEIGHT_KG=:weightKg , MODIFY_DATETIME = CURRENT_TIMESTAMP ,MODIFY_USER_ID = :modifyUserId where OFFENDER_BOOK_ID =:offenderBookId
}

OIDPIDEN_OFFPA_DELETE_OFFENDER_PHYSICAL_ATTRIBUTES { 
DELETE FROM OFFENDER_PHYSICAL_ATTRIBUTES where OFFENDER_BOOK_ID = :offenderBookId  and ATTRIBUTE_SEQ = :attributeSeq
}
OIDPIDEN_OFFRACE_FIND_OFFENDERS {
 SELECT OFFENDER_ID ,OFFENDER_NAME_SEQ ,ID_SOURCE_CODE ,LAST_NAME ,NAME_TYPE ,FIRST_NAME ,MIDDLE_NAME ,BIRTH_DATE ,SEX_CODE ,SUFFIX ,LAST_NAME_SOUNDEX ,BIRTH_PLACE ,BIRTH_COUNTRY_CODE ,CREATE_DATE ,LAST_NAME_KEY ,ALIAS_OFFENDER_ID ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,OFFENDER_ID_DISPLAY ,ROOT_OFFENDER_ID ,CASELOAD_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,ALIAS_NAME_TYPE ,PARENT_OFFENDER_ID ,UNIQUE_OBLIGATION_FLAG ,SUSPENDED_FLAG ,SUSPENDED_DATE ,RACE_CODE ,REMARK_CODE ,ADD_INFO_CODE ,BIRTH_COUNTY ,BIRTH_STATE ,MIDDLE_NAME_2 ,TITLE ,AGE ,CREATE_USER_ID ,LAST_NAME_ALPHA_KEY ,CREATE_DATETIME ,NAME_SEQUENCE ,SEAL_FLAG   FROM OFFENDERS WHERE OFFENDER_ID= :offenderId
}

OIDPIDEN_OFFRACE_UPDATE_OFFENDERS {
UPDATE OFFENDERS set OFFENDER_ID  = :offenderId ,OFFENDER_NAME_SEQ  = :offenderNameSeq ,ID_SOURCE_CODE  = :idSourceCode ,LAST_NAME  = :lastName ,NAME_TYPE  = :nameType ,FIRST_NAME  = :firstName ,MIDDLE_NAME  = :middleName ,BIRTH_DATE  = :birthDate ,SEX_CODE  = :sexCode ,SUFFIX  = :suffix ,LAST_NAME_SOUNDEX  = :lastNameSoundex ,BIRTH_PLACE  = :birthPlace ,BIRTH_COUNTRY_CODE  = :birthCountryCode ,LAST_NAME_KEY  = :lastNameKey ,ALIAS_OFFENDER_ID  = :aliasOffenderId ,FIRST_NAME_KEY  = :firstNameKey ,MIDDLE_NAME_KEY  = :middleNameKey ,OFFENDER_ID_DISPLAY  = :offenderIdDisplay ,ROOT_OFFENDER_ID  = :rootOffenderId ,CASELOAD_TYPE  = :caseloadType ,MODIFY_USER_ID  = :modifyUserId ,MODIFY_DATETIME  = current_timestamp ,ALIAS_NAME_TYPE  = :aliasNameType ,PARENT_OFFENDER_ID  = :parentOffenderId ,UNIQUE_OBLIGATION_FLAG  = :uniqueObligationFlag ,SUSPENDED_FLAG  = :suspendedFlag ,SUSPENDED_DATE  = :suspendedDate ,RACE_CODE  = :raceCode ,REMARK_CODE  = :remarkCode ,ADD_INFO_CODE  = :addInfoCode ,BIRTH_COUNTY  = :birthCounty ,BIRTH_STATE  = :birthState ,MIDDLE_NAME_2  = :middleName2 ,TITLE  = :title ,AGE  = :age ,LAST_NAME_ALPHA_KEY  = :lastNameAlphaKey  ,NAME_SEQUENCE  = :nameSequence ,SEAL_FLAG  = :sealFlag  where OFFENDER_ID =:offenderId
}

OIDPIDEN_OFFPD_FIND_OFFENDER_PROFILE_DETAILS {
 	SELECT OFFENDER_BOOK_ID , OPD.PROFILE_SEQ ,OPD.PROFILE_TYPE, PT.ACTIVE_FLAG ,OPD.PROFILE_CODE ,OPD.LIST_SEQ ,COMMENT_TEXT ,CASELOAD_TYPE ,OPD.MODIFY_USER_ID ,OPD.MODIFY_DATETIME ,OPD.CREATE_DATETIME ,OPD.CREATE_USER_ID ,OPD.SEAL_FLAG,PT.CODE_VALUE_TYPE  
	FROM OFFENDER_PROFILE_DETAILS OPD INNER JOIN PROFILE_TYPES PT ON OPD.PROFILE_TYPE = PT.PROFILE_TYPE
	where OFFENDER_BOOK_ID =:offnderBookId  AND PROFILE_SEQ = 1 ORDER BY LIST_SEQ 
}

OIDPIDEN_OFFPD_UPDATE_OFFENDER_PROFILE_DETAILS {
UPDATE OFFENDER_PROFILE_DETAILS set PROFILE_CODE  = :profileCode ,LIST_SEQ  = :listSeq ,COMMENT_TEXT  = :commentText ,CASELOAD_TYPE  = :caseloadType ,MODIFY_USER_ID  = :modifyUserId ,MODIFY_DATETIME  = current_timestamp ,SEAL_FLAG  = :sealFlag  where OFFENDER_BOOK_ID = :offenderBookId  and PROFILE_SEQ = :profileSeq  and PROFILE_TYPE = :profileType 
}

OIDPIDEN_OFFIM_FIND_OFFENDER_IDENTIFYING_MARKS {
 SELECT OFFENDER_BOOK_ID ,ID_MARK_SEQ ,BODY_PART_CODE ,MARK_TYPE ,SIDE_CODE ,PART_ORIENTATION_CODE ,COMMENT_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM OFFENDER_IDENTIFYING_MARKS   where OFFENDER_BOOK_ID = :offenderBookId 
}

GET_IDENTIFY_MARK_IMAGE{
SELECT IMAGE_THUMBNAIL,IMAGE_ID,ACTIVE_FLAG FROM IMAGES WHERE IMAGE_OBJECT_ID=:OFFENDER_BOOK_ID AND IMAGE_OBJECT_SEQ=:ID_MARK_SEQ AND IMAGE_VIEW_TYPE=:MARK_TYPE
}

OIDPIDEN_OFFIM_INSERT_OFFENDER_IDENTIFYING_MARKS {
insert into OFFENDER_IDENTIFYING_MARKS(OFFENDER_BOOK_ID , ID_MARK_SEQ , BODY_PART_CODE , MARK_TYPE , SIDE_CODE , PART_ORIENTATION_CODE , COMMENT_TEXT , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG, MODIFY_DATETIME ) values(:offenderBookId , :idMarkSeq , :bodyPartCode , :markType , :sideCode , :partOrientationCode , :commentText , CURRENT_TIMESTAMP , :createUserId , :sealFlag, NULL ) 
}

OIDPIDEN_OFFIM_UPDATE_OFFENDER_IDENTIFYING_MARKS {
UPDATE OFFENDER_IDENTIFYING_MARKS set BODY_PART_CODE  = :bodyPartCode ,MARK_TYPE  = :markType ,SIDE_CODE  = :sideCode ,PART_ORIENTATION_CODE  = :partOrientationCode ,COMMENT_TEXT  = :commentText ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId ,SEAL_FLAG  = :sealFlag  where OFFENDER_BOOK_ID = :offenderBookId  and ID_MARK_SEQ = :idMarkSeq 
}
OIDPIDEN_GETDESC_MARKTYPE {
 SELECT DESCRIPTION  FROM REFERENCE_CODES   WHERE DOMAIN = 'MARK_TYPE' AND CODE=:code 
}

OIDPIDEN_GETDESC_BODYPART {
 SELECT DESCRIPTION  FROM REFERENCE_CODES   WHERE DOMAIN = 'BODY_PART' AND CODE=:code 
}
	OIDPIDEN_OFFIM_DELETE_OFFENDER_IDENTIFYING_MARKS { 
DELETE FROM OFFENDER_IDENTIFYING_MARKS where OFFENDER_BOOK_ID = :offenderBookId  and ID_MARK_SEQ = :idMarkSeq
}

FIND_ID_MARK_SEQ_FOR_OFFENDER_IDENTIFYING_MARKS {
select coalesce (max(ID_MARK_SEQ),0)+1 from OFFENDER_IDENTIFYING_MARKS where OFFENDER_BOOK_ID=:offenderBookId
}


	OIDPIDEN_OFF_BKG_PREDELETE {
 DELETE FROM OFFENDERS O WHERE O.OFFENDER_ID = :OFFENDERID
}

	OIDPIDEN_NBT_DETAIL_DESC_WHENVALIDATEITEM_PROFILE_TYPES_C {
 SELECT CODE_VALUE_TYPE FROM PROFILE_TYPES WHERE PROFILE_TYPE = :PROFILETYPE
}

	OIDPIDEN_NBT_DETAIL_DESC_WHEN_NEW_ITEM_INSTANCE_PROFILE_TYPES_C {
 SELECT CODE_VALUE_TYPE FROM PROFILE_TYPES WHERE PROFILE_TYPE = PROFILETYPE
}

	OIDPIDEN_OFF_PD_WHENNEWRECORDINSTANCE_PROFILE_TYPES_C {
 SELECT CODE_VALUE_TYPE FROM PROFILE_TYPES WHERE PROFILE_TYPE = PROFILETYPE
}

	OIDPIDEN_OFF_PD_POSTQUERY_CHAR_DESC_CUR {
 SELECT DESCRIPTION FROM PROFILE_TYPES WHERE PROFILE_TYPE = :PROFILETYPE and profile_category = 'PA'
}

	OIDPIDEN_CALL_TO_SHOW_FINGERPRINT_OLD {
 SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_TYPE='CLIENT' AND PROFILE_CODE='FINGER_URL'
}

	OIDPIDEN_CGFKCHK_OFF_PD_OFF_PD_PFL_COD_VALUE_TYPE_CUR {
 SELECT CODE_VALUE_TYPE FROM PROFILE_TYPES WHERE PROFILE_TYPE = :PROFILETYPE
}

OIDPIDEN_GETTING_LISTSEQ
{
SELECT PROFILE_SEQ
        FROM OFFENDER_PROFILES
       WHERE OFFENDER_BOOK_ID =  :OFFENDER_BOOK_ID

}
OIDPIDEN_INSERT_OFFENDER_PROFILES
{
insert into offender_profiles (offender_book_id, profile_seq, check_date, create_datetime, create_user_id,modify_datetime) values (:offenderBookId, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, :createUserId,NULL)
}
OIDPIDEN_GETPROFILETYPES_AND_MINUS_PROFILE_DETAILS
{

SELECT DISTINCT profile_type
                 FROM profile_types
                WHERE profile_category = :profile_category
      EXCEPT
      SELECT DISTINCT profile_type
                 FROM offender_profile_details opd
                WHERE offender_book_id = :off_book_id AND EXISTS (SELECT NULL
                                                                   FROM profile_types
                                                                  WHERE profile_type = opd.profile_type AND profile_category = :profile_category)

}
OIDPIDEN_INSERT_LIST_PROFILE_DETAILS{
insert into offender_profile_details (offender_book_id, profile_seq, profile_type, profile_code, list_seq, comment_text, caseload_type, CREATE_DATETIME, CREATE_USER_ID) select :off_book_id, 1, profile_type, '', list_seq, '', :csld_type, current_timestamp, :userName from profile_types where active_flag = 'Y' and profile_category = :profile_category and profile_type in (:v_profile_types)
}
OIDPIDEN_CGFKCHK_OFF_PD_OFF_PD_PFL_COD_C {
 SELECT PFL_CODE.PROFILE_TYPE ,PFL_CODE.DESCRIPTION ,PFL_CODE.LIST_SEQ FROM   PROFILE_CODES PFL_CODE WHERE  PFL_CODE.PROFILE_CODE = :PROFILECODE AND    PFL_CODE.PROFILE_TYPE = :PROFILETYPE
}

OIDPIDEN_GET_OLD_LIST_OFFENDERS {
select* from OFFENDERS where OFFENDER_ID = :OFFENDERID
}