
OTURNUMB_OFFTXN_FIND_OFFENDER_TRANSACTIONS {
 	SELECT *  FROM OFFENDER_TRANSACTIONS WHERE
}
OTURNUMB_OFFTXN_INSERT_OFFENDER_TRANSACTIONS {
	INSERT INTO OFFENDER_TRANSACTIONS() VALUES(:)
}

OTURNUMB_OFFTXN_UPDATE_OFFENDER_TRANSACTIONS {
	UPDATE OFFENDER_TRANSACTIONS set /* where */
}


OTURNUMB_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

OTURNUMB_GET_OFFENDER_DETAILS {
SELECT o.last_name || ', ' || o.first_name LAST_NAME,   o.offender_id_display  FROM offenders o, offender_bookings ob
          WHERE ob.offender_book_id = :offenderBookId  AND ob.offender_id = o.offender_id
}
