INSERT INTO OMS_OWNER.MODULE_PRIVILEGES(MODULE_NAME, ROLE_ID, ACCESS_PRIVILEGE, VERIFICATION_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG) 
 SELECT 'OIDCUSTAD', 444, 'A', 'Y', current_timestamp, 'OMS_OWNER', current_timestamp, 'OMS_OWNER', NULL  
  WHERE NOT EXISTS (SELECT 1 FROM MODULE_PRIVILEGES WHERE module_name = 'OIDCUSTAD' AND role_id = 444);