
OUMAPASS_STAFF_FIND_STAFF_MEMBERS {
 	SELECT STAFF_ID ,ASSIGNED_CASELOAD_ID ,WORKING_STOCK_LOC_ID ,WORKING_CASELOAD_ID ,USER_ID ,BADGE_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,ABBREVIATION ,POSITION ,BIRTHDATE ,TERMINATION_DATE ,UPDATE_ALLOWED_FLAG ,DEFAULT_PRINTER_ID ,SUSPENDED_FLAG ,SUPERVISOR_STAFF_ID ,COMM_RECEIPT_PRINTER_ID ,PERSONNEL_TYPE ,AS_OF_DATE ,EMERGENCY_CONTACT ,ROLE ,SEX_CODE ,STATUS ,SUSPENSION_DATE ,SUSPENSION_REASON ,FORCE_PASSWORD_CHANGE_FLAG ,LAST_PASSWORD_CHANGE_DATE ,LICENSE_CODE ,LICENSE_EXPIRY_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,TITLE ,NAME_SEQUENCE ,QUEUE_CLUSTER_ID ,FIRST_LOGON_FLAG ,SUFFIX ,SEAL_FLAG   FROM STAFF_MEMBERS 
 	WHERE USER_ID NOT IN(SELECT USERNAME FROM DBA_USERS WHERE DEFAULT_TABLESPACE NOT IN ('TAG_DATA','USERS') UNION SELECT 'OMS_OWNER' FROM DUAL UNION SELECT 'INTERNAL' FROM DUAL ) AND 
 	
}
OUMAPASS_STAFF_UPDATE_STAFF_MEMBERS {
	UPDATE STAFF_MEMBERS set STAFF_ID  = :staffId ,ASSIGNED_CASELOAD_ID  = :assignedCaseloadId ,WORKING_STOCK_LOC_ID  = :workingStockLocId ,WORKING_CASELOAD_ID  = :workingCaseloadId ,USER_ID  = :userId ,BADGE_ID  = :badgeId ,LAST_NAME  = :lastName ,FIRST_NAME  = :firstName ,MIDDLE_NAME  = :middleName ,ABBREVIATION  = :abbreviation ,POSITION  = :position ,BIRTHDATE  = :birthdate ,TERMINATION_DATE  = :terminationDate ,UPDATE_ALLOWED_FLAG  = :updateAllowedFlag ,DEFAULT_PRINTER_ID  = :defaultPrinterId ,SUSPENDED_FLAG  = :suspendedFlag ,SUPERVISOR_STAFF_ID  = :supervisorStaffId ,COMM_RECEIPT_PRINTER_ID  = :commReceiptPrinterId ,PERSONNEL_TYPE  = :personnelType ,AS_OF_DATE  = :asOfDate ,EMERGENCY_CONTACT  = :emergencyContact ,ROLE  = :role ,SEX_CODE  = :sexCode ,STATUS  = :status ,SUSPENSION_DATE  = :suspensionDate ,SUSPENSION_REASON  = :suspensionReason ,FORCE_PASSWORD_CHANGE_FLAG  = :forcePasswordChangeFlag ,LAST_PASSWORD_CHANGE_DATE  = :lastPasswordChangeDate ,LICENSE_CODE  = :licenseCode ,LICENSE_EXPIRY_DATE  = :licenseExpiryDate ,CREATE_DATETIME  = :createDateTime ,CREATE_USER_ID  = :createUserId ,MODIFY_DATETIME  = :modifyDateTime ,MODIFY_USER_ID  = :modifyUserId ,TITLE  = :title ,NAME_SEQUENCE  = :nameSequence ,QUEUE_CLUSTER_ID  = :queueClusterId ,FIRST_LOGON_FLAG  = :firstLogonFlag ,SUFFIX  = :suffix ,SEAL_FLAG  = :sealFlag /* where */
}

OUMAPASS_STAFFAC_FIND_STAFF_ACCESSIBLE_CASELOADS {
 	SELECT CASELOAD_ID ,STAFF_ID ,UPDATE_ALLOWED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM STAFF_ACCESSIBLE_CASELOADS  /* where  */
}

OUMAPASS_CGWHEN_NEW_FORM_INSTANCE {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
OUMAPASS_L_USER_DB_EXISTS {
 SELECT 'Y'   FROM all_users WHERE username = upper(:p_username)
 }
 OUMAPASS_GET_TABLE_SPACE {
SELECT PROFILE_VALUE
        FROM SYSTEM_PROFILES
       WHERE SYSTEM_PROFILES.PROFILE_TYPE = 'SYS'
         AND SYSTEM_PROFILES.PROFILE_CODE = :PROFILE_CODE
         }

OMSS40_INSERT_OMS_USERS_LIST {
	INSERT INTO OMS_USERS_LIST(USER_ID,PASSWORD,CREATE_DATETIME,FAILED_LOGIN_ATTEMPTS,CREATE_USER_ID,CREATE_DATETIME)
    	VALUES(:userId, :password, CURRENT_TIMESTAMP, :failedLoginAttempts, :createUserId, current_timestamp)
}
