
OUMSMALA_FIND_CGFKSLRPOSITION {
SELECT REF_CODE.CODE  POSITION  ,REF_CODE.DESCRIPTION  DSP_DESCRIPTION6 FROM   REFERENCE_CODES REF_CODE WHERE (DOMAIN ='STAFF_POS' AND  (ACTIVE_FLAG = 'Y' OR ''<> 'NORMAL' ) ) ORDER BY  REF_CODE.LIST_SEQ ASC         ,REF_CODE.DESCRIPTION ASC         ,REF_CODE.CODE ASC
}

OUMSMALA_FIND_CGFKSLRROLE {
 	SELECT REF_CODE1.CODE  ROLE     ,REF_CODE1.DESCRIPTION  DSP_DESCRIPTION5 FROM   REFERENCE_CODES REF_CODE1 WHERE   (DOMAIN = 'STAFF_ROLE' AND (ACTIVE_FLAG = 'Y' OR '' <> 'NORMAL' ) ) ORDER BY  REF_CODE1.LIST_SEQ ASC         ,REF_CODE1.DESCRIPTION ASC         ,REF_CODE1.CODE ASC
}

OUMSMALA_FIND_CGFKSLRSTAFFUNIT {
 	SELECT REF_CODE1.CODE STAFF_UNIT ,REF_CODE1.DESCRIPTION DSP_DESCRIPTION7 FROM REFERENCE_CODES REF_CODE1 WHERE (DOMAIN = 'STAFF_UNIT' AND (ACTIVE_FLAG = 'Y' OR '' <> 'NORMAL' ) ) ORDER BY REF_CODE1.LIST_SEQ ASC  ,REF_CODE1.DESCRIPTION ASC  ,REF_CODE1.CODE ASC
}

OUMSMALA_FIND_CGFKSLRSCHEDULETYPE {
 	SELECT REF_CODE2.CODE  SCHEDULE_TYPE  ,REF_CODE2.DESCRIPTION  DSP_DESCRIPTION4 FROM   REFERENCE_CODES REF_CODE2 WHERE (DOMAIN ='SCHEDULE_TYP' AND  (ACTIVE_FLAG = 'Y' OR '' <> 'NORMAL' ) ) ORDER BY  REF_CODE2.LIST_SEQ ASC         ,REF_CODE2.DESCRIPTION ASC         ,REF_CODE2.CODE ASC
}

OUMSMALA_FIND_CGFKCALAGYLOCID {
 	SELECT AL.AGY_LOC_ID AGY_LOC_ID , AL.DESCRIPTION DESCRIPTION , AL.AGENCY_LOCATION_TYPE AGENCY_LOCATION_TYPE FROM AGENCY_LOCATIONS AL 
WHERE AGY_LOC_ID IN (SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID IN (SELECT CASELOAD_ID FROM STAFF_ACCESSIBLE_CASELOADS SAC WHERE SAC.STAFF_ID =:STAFFID ) )  ORDER BY AGY_LOC_ID
}

OUMSMALA_FIND_CGFKSACCASELOADID {
 	SELECT CAS3.CASELOAD_ID  CASELOAD_ID          ,CAS3.LIST_SEQ  DSP_LIST_SEQ        ,CAS3.DESCRIPTION  DSP_DESCRIPTION        ,CAS3.CASELOAD_TYPE  DSP_CASELOAD_TYPE FROM   CASELOADS CAS3 ORDER BY  CAS3.LIST_SEQ ASC         ,CAS3.CASELOAD_ID ASC         ,CAS3.DESCRIPTION ASC         ,CAS3.CASELOAD_TYPE ASC
}

OUMSMALA_SM_FIND_STAFF_MEMBERS {
 	SELECT   STAFF_ID,ASSIGNED_CASELOAD_ID,WORKING_STOCK_LOC_ID,WORKING_CASELOAD_ID,USER_ID, MAIL_ID, BADGE_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, ABBREVIATION , POSITION, BIRTHDATE , TERMINATION_DATE, UPDATE_ALLOWED_FLAG, DEFAULT_PRINTER_ID , SUSPENDED_FLAG, SUPERVISOR_STAFF_ID,COMM_RECEIPT_PRINTER_ID,PERSONNEL_TYPE,AS_OF_DATE , EMERGENCY_CONTACT, ROLE, SEX_CODE,STATUS , SUSPENSION_DATE, SUSPENSION_REASON,FORCE_PASSWORD_CHANGE_FLAG ,LAST_PASSWORD_CHANGE_DATE,LICENSE_CODE, LICENSE_EXPIRY_DATE, CREATE_DATETIME, CREATE_USER_ID , MODIFY_DATETIME , MODIFY_USER_ID , TITLE, NAME_SEQUENCE, QUEUE_CLUSTER_ID , FIRST_LOGON_FLAG, SUFFIX ,SEAL_FLAG  FROM STAFF_MEMBERS 
}
OUMSMALA_SM_FIND_FROM_CLAUSE_QUERY {
SELECT DISTINCT CAL.AGY_LOC_ID, SAC.STAFF_ID      FROM CASELOAD_AGENCY_LOCATIONS CAL , STAFF_ACCESSIBLE_CASELOADS SAC WHERE SAC.CASELOAD_ID = :CASELOADID AND  SAC.UPDATE_ALLOWED_FLAG = 'Y' AND STAFF_ID = :STAFFID  ORDER BY AGY_LOC_ID
}
OUMSMALA_SLR_FIND_STAFF_LOCATION_ROLES {
 	select
CAL_AGY_LOC_ID,
SAC_STAFF_ID,
FROM_DATE ,
TO_DATE ,
position ,
role,
SCHEDULE_TYPE ,
HOURS_PER_WEEK ,
SUPERVISOR_AGY_LOC_ID,
SUPERVISOR_STAFF_ID,
SUPERVISOR_FROM_DATE,
SUPERVISOR_POSITION ,
SUPERVISOR_ROLE ,
STAFF_UNIT,
CREATE_DATETIME ,
CREATE_USER_ID,
MODIFY_DATETIME ,
MODIFY_USER_ID ,
SEAL_FLAG,
ROW_ID,
STAFF_LOC_ROLE_ID,
FTE_STATUS
from
STAFF_LOCATION_ROLES
where
SAC_STAFF_ID = :STAFFID
and CAL_AGY_LOC_ID = :AGYLOCID
order by
TO_DATE desc,
FROM_DATE desc
}
OUMSMALA_SLR_INSERT_STAFF_LOCATION_ROLES {
insert into STAFF_LOCATION_ROLES(CAL_AGY_LOC_ID, SAC_STAFF_ID, FROM_DATE , TO_DATE , position , role, SCHEDULE_TYPE , HOURS_PER_WEEK , SUPERVISOR_AGY_LOC_ID, SUPERVISOR_STAFF_ID, SUPERVISOR_FROM_DATE, SUPERVISOR_POSITION , SUPERVISOR_ROLE , STAFF_UNIT, CREATE_DATETIME , CREATE_USER_ID, MODIFY_DATETIME , SEAL_FLAG , STAFF_LOC_ROLE_ID, FTE_STATUS) values(:calAgyLocId, :sacStaffId, :fromDate , :toDate , :position , :role, :scheduleType , :hoursPerWeek , :supervisorAgyLocId, :supervisorStaffId, :supervisorFromDate, :supervisorPosition , :supervisorRole , :staffUnit, CURRENT_TIMESTAMP , :createUserId, null , :sealFlag, nextval('staff_loc_role_id_seq'), :fteStatus)
}

OUMSMALA_SLR_UPDATE_STAFF_LOCATION_ROLES {
 update STAFF_LOCATION_ROLES set position =:position, role =:role, FROM_DATE =:fromDate, TO_DATE =:toDate, SCHEDULE_TYPE =:scheduleType, HOURS_PER_WEEK =:hoursPerWeek, SUPERVISOR_AGY_LOC_ID =:supervisorAgyLocId, SUPERVISOR_STAFF_ID =:supervisorStaffId, SUPERVISOR_FROM_DATE =:supervisorFromDate, SUPERVISOR_POSITION =:supervisorPosition, SUPERVISOR_ROLE =:supervisorRole, STAFF_UNIT =:staffUnit, MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID =:modifyUserId, SEAL_FLAG =:sealFlag, fte_status = :fteStatus  where SAC_STAFF_ID = :sacStaffId and CAL_AGY_LOC_ID = :calAgyLocId and ROW_ID = :rowId 
}


OUMSMALA_CGFKCHK_CAL_CSLD_AL_AGY_LOC_F {
	SELECT AL.DESCRIPTION ,AL.AGENCY_LOCATION_TYPE FROM   AGENCY_LOCATIONS AL WHERE  AL.AGY_LOC_ID = :AGYLOCID
}

OUMSMALA_CGFKCHK_SLR_C_SLR_SCHED_TYPE__ {
	SELECT REF_CODE2.LIST_SEQ ,REF_CODE2.DESCRIPTION FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.CODE = :SCHEDULETYPE AND     (DOMAIN ='SCHEDULE_TYP' AND (ACTIVE_FLAG = 'Y' OR :MODE <> 'NORMAL'))
}

OUMSMALA_CGFKCHK_SLR_C_SLR_ROLE_FK_ {
	SELECT REF_CODE1.LIST_SEQ ,REF_CODE1.DESCRIPTION FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :ROLE AND     (DOMAIN = 'STAFF_ROLE' AND (ACTIVE_FLAG = 'Y' OR :MODE <> 'NORMAL'))
}

OUMSMALA_CGFKCHK_SLR_C_SLR_POSN_FK_ {
	SELECT REF_CODE.LIST_SEQ ,REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :POSITION AND     (DOMAIN ='STAFF_POS' AND (ACTIVE_FLAG = 'Y' OR :MODE <> 'NORMAL'))
}

OUMSMALA_CGUVCHK_SLR_PK {
	SELECT  '1' FROM    STAFF_LOCATION_ROLES WHERE   CAL_AGY_LOC_ID = :PCALAGYLOCID AND     SAC_STAFF_ID = :SACSTAFFID AND     POSITION =:POSITION AND     ROLE = :ROLE AND     FROM_DATE = :FROMDATE
}

OUMSMALA_CGRICHK_STAFF_LOCATION_ROLES_ {
	SELECT  '1' FROM    OFFENDER_WORK_ASSIGNMENTS OFFASS WHERE   (OFFASS.CAL_AGY_LOC_ID = P_CAL_AGY_LOC_ID OR (OFFASS.CAL_AGY_LOC_ID IS NULL AND P_CAL_AGY_LOC_ID IS NULL )) AND     (OFFASS.SAC_STAFF_ID = P_SAC_STAFF_ID OR (OFFASS.SAC_STAFF_ID IS NULL AND P_SAC_STAFF_ID IS NULL )) AND     (OFFASS.POSITION = P_POSITION OR (OFFASS.POSITION IS NULL AND P_POSITION IS NULL )) AND     (OFFASS.ROLE = P_ROLE OR (OFFASS.ROLE IS NULL AND P_ROLE IS NULL )) AND     (OFFASS.FROM_DATE = P_FROM_DATE OR (OFFASS.FROM_DATE IS NULL AND P_FROM_DATE IS NULL ))
}

OUMSMALA_CGRICHK_STAFF_LOCATION_ROLES_ {
	SELECT  '1' FROM    ASSIGNMENT_TRANSFERS ASSTRA WHERE   (ASSTRA.CAL_AGY_LOC_ID_FROM = P_CAL_AGY_LOC_ID OR (ASSTRA.CAL_AGY_LOC_ID_FROM IS NULL AND P_CAL_AGY_LOC_ID IS NULL )) AND     (ASSTRA.SAC_STAFF_ID_FROM = P_SAC_STAFF_ID OR (ASSTRA.SAC_STAFF_ID_FROM IS NULL AND P_SAC_STAFF_ID IS NULL )) AND     (ASSTRA.POSITION_FROM = P_POSITION OR (ASSTRA.POSITION_FROM IS NULL AND P_POSITION IS NULL )) AND     (ASSTRA.ROLE_FROM = P_ROLE OR (ASSTRA.ROLE_FROM IS NULL AND P_ROLE IS NULL )) AND     (ASSTRA.FROM_DATE_FROM = P_FROM_DATE OR (ASSTRA.FROM_DATE_FROM IS NULL AND P_FROM_DATE IS NULL ))
}

OUMSMALA_CGRICHK_STAFF_LOCATION_ROLES_ {
	SELECT  '1' FROM    ASSIGNMENT_TRANSFERS ASSTRA WHERE   (ASSTRA.CAL_AGY_LOC_ID = P_CAL_AGY_LOC_ID OR (ASSTRA.CAL_AGY_LOC_ID IS NULL AND P_CAL_AGY_LOC_ID IS NULL )) AND     (ASSTRA.SAC_STAFF_ID = P_SAC_STAFF_ID OR (ASSTRA.SAC_STAFF_ID IS NULL AND P_SAC_STAFF_ID IS NULL )) AND     (ASSTRA.POSITION = P_POSITION OR (ASSTRA.POSITION IS NULL AND P_POSITION IS NULL )) AND     (ASSTRA.ROLE = P_ROLE OR (ASSTRA.ROLE IS NULL AND P_ROLE IS NULL )) AND     (ASSTRA.FROM_DATE = P_FROM_DATE OR (ASSTRA.FROM_DATE IS NULL AND P_FROM_DATE IS NULL ))
}
OUMSMALA_FROM_OFFENDER_WORK_ASSIGNMENTS {
 SELECT COUNT( * ) FROM OFFENDER_WORK_ASSIGNMENTS WHERE CAL_AGY_LOC_ID   =:calAgyLocId AND SAC_STAFF_ID     =:staffId AND POSITION= :position AND ROLE   = :role AND  TRUNC( FROM_DATE ) = :fromDate
}
OUMSMALA_FROM_OFFENDER_CASE_PLANS {
 SELECT COUNT( * ) FROM CASE_PLANS WHERE  CAL_AGY_LOC_ID   =:calagyLocId  AND SAC_STAFF_ID  = :staffId AND POSITION = :position AND ROLE  = :role AND TRUNC( FROM_DATE ) = :fromDate AND END_DATE IS NULL
 }
 OUMSMALA_OFFENDER_BOOK_ID_OFFENDER_WORK_ASSIGNMENTS {
 SELECT OFFENDER_BOOK_ID,SENTENCE_SEQ,OFFENDER_BOOK_ID_REQUEST,CHARGE_SEQ, REQUEST_SEQ  FROM OFFENDER_WORK_ASSIGNMENTS  WHERE  CAL_AGY_LOC_ID =  :calagyLocId  AND SAC_STAFF_ID  =  :staffId  AND POSITION   = :position
AND ROLE = :role  AND TRUNC( FROM_DATE ) = :fromDate
}
OUMSMALA_GET_DISCHARGE_DATE {
SELECT DISCHARGE_DATE FROM OFFENDER_SENTENCES WHERE OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID   AND SENTENCE_SEQ = :P_SENTENCE_SEQ
}
OUMSMALA_GET_DISCHARGE_DATE_FROM_OFFENDER_REQUESTS {
SELECT DISCHARGE_DATE  FROM OFFENDER_REQUESTS    WHERE OFFENDER_BOOK_ID = P_OFFENDER_BOOK_ID  AND CHARGE_SEQ = P_CHARGE_SEQ AND REQUEST_SEQ = P_REQUEST_SEQ
}
OUMSMALA_GET_DISCHARGE_DATE_FROM_OFFENDER_REQUESTS {
SELECT '1' FROM STAFF_LOCATION_ROLES SLR  WHERE SLR.SUPERVISOR_STAFF_ID = :staffId  AND SLR.SUPERVISOR_AGY_LOC_ID = :calagyLocId  AND SLR.SUPERVISOR_FROM_DATE = :fromDate  AND SLR.SUPERVISOR_POSITION = :position  AND SLR.SUPERVISOR_ROLE = :role  AND SLR.TO_DATE IS NULL
}
OUMSMALA_CONSTRAINT_VALIDATIONS {
 select
 tc.table_name
from
 information_schema.table_constraints as tc
join information_schema.key_column_usage as kcu on
 tc.constraint_name = kcu.constraint_name
 and tc.table_schema = kcu.table_schema
join information_schema.constraint_column_usage as ccu on
 ccu.constraint_name = tc.constraint_name
 and ccu.table_schema = tc.table_schema
where
 tc.constraint_type = 'FOREIGN KEY'
 and upper(ccu.table_name)= 'STAFF_LOCATION_ROLES'
 and upper(tc.CONSTRAINT_NAME)= :CONSTRAINTNAME
 and upper(tc.constraint_schema)= 'OMS_OWNER'

}
