TABLE_CUR_SELECT_OPERATION{
SELECT UPPER(TABLE_NAME) TABLE_NAME FROM ACCESSIBLE_FORM_TABLES WHERE ORIGINATING_FORM = :origForm AND DESTINATION_FORM = :destForm
}

LV_STMT_SELECT{
SELECT COUNT(0) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = :tableName AND COLUMN_NAME = 'offender_book_id' 
}

LV_STMT_IF_SELECT_ONE{
SELECT COUNT(*) FROM :tableName WHERE OFFENDER_BOOK_ID IN ( SELECT OFFENDER_BOOK_ID FROM OFFENDER_BOOKINGS WHERE ROOT_OFFENDER_ID = :offenderId)
}

LV_STMT_ELSE_SELECT{
SELECT COUNT(*)   FROM :tableName  WHERE OFFENDER_BOOK_ID = :bookId
}

LV_STMT_LAST_ELSE_SELECT_NEW{
SELECT COUNT(*) FROM :tableName WHERE offender_id = :offenderId 
--SELECT COUNT(*) FROM :tableName WHERE ROOT_OFFENDER_ID  = :offenderId
}

LV_STMT{
   SELECT COUNT(0) FROM ACCESSIBLE_FORM_TABLES WHERE TABLE_NAME=:TAB_NAME
}