package net.syscon.s4.pkgs.purge_offender;

import java.math.BigDecimal;

public interface PurgeOffenderService {
	
	void prOffenders(BigDecimal offenderId,String modifyUserId);
	void prBioSubjects(BigDecimal pRootOffenderId,String modifyUserId);
	void prBioScans(BigDecimal pSubjectId,String modifyUserId);
	void prBioFpSamples(BigDecimal pScanId, BigDecimal pSubjectId,String modifyUserId);
	void prBioEventLogs(BigDecimal pSubjectId,String modifyUserId);
	void prGlTransactions(BigDecimal offenderId,String modifyUserId);
    void prOffenders1(Long aliasOffenderId);
    void prOffenderBalances(BigDecimal offenderId,String modifyUserId);
    void prOffenderBookings(BigDecimal offenderId,String modifyUserId);
    void prAgencyIncidentParties(Integer offenderBookId);
    void prAgencyIncidentCharges(Integer agencyIncidentId,Integer partySeq);
    void prOicHearingResults(BigDecimal agencyIncidentId,BigDecimal chargeSeq,String modifyUserId);
    void prOffenderOicAppealPenltis(Integer oicApprealId,Integer oicHearingId,Integer resultSeq,String modifyUserId);
    void proffenderoicappelincidnts(Integer oicHearingId,Integer resultSeq,String modifyUserId);
    void prOffenderOicSancReviews(BigDecimal offenderBookId,Long pSanctionSeq,String modifyUserId);
    void prOffenderOicSanctions2(Integer pConsecutivOffndrBookId,Integer pConsecutiveSanctionSeq,String modifyUserId);
    void prOffenderOicSanctions1(Integer oicHearingId,Integer resultSeq,String modifyUserId);
    void prOffenderCaseNoteSents(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffndrCommnityConditions1(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderIndSchSents(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderLicenceSentences1(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderLicenceSentences2(Long offenderBookId,Long pLicenceSentenceSeq,String modifyUserId);
    void prOffenderProceedingSents(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderSentenceAdjusts(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderSentenceCharges1(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderSentenceHty(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderSentenceStatuses(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderSentenceTerms(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderSentenceUaEvents(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderUnpaidWorkAdj(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderSentences1(BigDecimal orderId,String modifyUserId);
    void prCourtEventSentences1(Long offenderBookId,Long sentenceSeq,String modifyUserId);
    void prOffenderCommunityFiles(BigDecimal offenderId,String modifyUserId);
    void prOffenderIdentifiers(BigDecimal offenderId,String modifyUserId);
    void prOffenderObliVerifications(BigDecimal offenderId,String modifyUserId);
    void prOffenderPaymentProfiles(BigDecimal offenderId,String modifyUserId);
    void prOffenderDeductions(BigDecimal offenderPaymentProfileId,String modifyUserId);
    void prOffenderAdjustmentTxns(String adjustmentUserId,String modifyUserId);
    void prOffenderBeneficiaries(Long offenderDeductionId,String modifyUserId);
    void prBeneficiaryTransactions(BigDecimal beneficiaryId,String modifyUserId);
    void prOffenderCrditPriorPymnts(BigDecimal beneficiaryId,String modifyUserId);
    void prOffenderMonBeneficiaries1(BigDecimal beneficiaryId,String modifyUserId);
    void prOffenderDeductionReceipts(Long offenderDeductionId,String modifyUserId);
    void prOffenderDeductionShadows(Long offenderDeductionId,String modifyUserId);
    void prOffenderMonBeneficiaries(Long offenderDeductionId,String modifyUserId);
    void prOffenderMonDeductions(Long offenderDeductionId,String modifyUserId);
    void prOffenderTierTxnFeeMonts(Long offenderDeductionId,String modifyUserId);
    void prOffenderTxnFeeDetails(Long offenderDeductionId,String modifyUserId);
    void prOffenderDeductions1(BigDecimal parentDeductionId,String modifyUserId);
    void prOffenderPlacementScores(BigDecimal rootOffenderId,String modifyUserId);
    void prOffenderTransactions(Long offenderId,String modifyUserId);
    void prOffendrCrditPriorPymnts1(Long txnId,Long txnEntrySeq,String modifyUserId);
    void prOffenderPayrollTxns(Long txnId,Long txnEntrySeq,String modifyUserId);
    void prOffenderTransactions1(Long txnId,Long txnEntrySeq,String modifyUserId);
    void prOffenderTrustAccountsTmp(Long offenderId,String modifyUserId);
    void prOffenderVitalSigns(Long offenderId,String modifyUserId);
    void prAddresses(BigDecimal ownerId,String ownerClass,String modifyUserId);
    void prAddressUsages(BigDecimal addressId,String modifyUserId);
    void prCourseActivities(Long servicesAddressId,String modifyUserId);
    void prCourseActivities1(Long parentCrsActyId,String modifyUserId);
    void prCourseActivityAreas(BigDecimal crsActyId,String modifyUserId);
    void prCourseActivityParties(BigDecimal crsActyId,String modifyUserId);
    void prCourseActivityProfiles(BigDecimal crsActyId,String modifyUserId);
    void prCourseActivityReviews(BigDecimal crsActyId,String modifyUserId);
    void prCourseSchedules(BigDecimal crsActyId);
    void prCourseScheduleRules(BigDecimal crsActyId,String modifyUserId);
    void prOffenderCourseAttendancs3(BigDecimal crsActyId,String modifyUserId);
    void prOffenderCourseSkills(Long eventId,String modifyUserId);
    void prOffenderProgramProfiles3(Long crsActyId);
    void prOffenderCourseApptGrps(BigDecimal offPrgrefId,String modifyUserId);
    void prOffenderCourseApptRules(Long offenderCourseApptRuleId,String modifyUserId);
    void prOffenderCourseAttendancs2(BigDecimal offPrgrefId,String modifyUserId);
    void prOffenderProgramProfiles2(Long offPrgrefId,String modifyUserId);
    void prCurfewAddresses1(BigDecimal addressId,String modifyUserId);
    void prCurfewAddressOccupants(BigDecimal pCurfewAddressId,String modifyUserId);
    void prOffenderExternalMovemnts1(BigDecimal toAddressId,String modifyUserId);
    void prOffenderExternalMovemnts2(BigDecimal fromAddressId,String modifyUserId);
    void prOffenderMailLogs1(BigDecimal pMailAddressId,String modifyUserId);
    void prOffenderMailRestrictions1(BigDecimal pRestrictionAddressId,String modifyUserId);
    void prPhones(BigDecimal ownerId,String ownerClass,String modifyUserId);
    void prOffenderNonAssociations(Long offenderId,String modifyUserId);
    void prOffenderNaDetails(Long offenderId,Long nsOffenderId,String modifyUserId);
    void prOffenderNonAssociations1(Long nsOffenderId,String modifyUserId);
    void prOffenderContactPersons(BigDecimal contactRootOffenderId,String modifyUserId);
    void prOffenderPersonRestricts(Integer offenderContactPersonId,String modifyUserId);
    void prOffenderTrustAccounts(Long offenderId,String modifyUserId);
    void prOffenderDeductions2(String caseloadId,Long offenderId);
    void prOffenderForeignCurrencies(String caseloadId,Long offenderId,String modifyUserId);
    void prOffenderSubAccounts(String caseloadId,Long offenderId,String modifyUserId);
    void prArrests(Long offenderBookId,String modifyUserId);
    void prBedAssignmentHistories(Integer offenderBookId,String modifyUserId);
    void prCaseAssociatedPersons(Long offenderBookId,String modifyUserId);
    void prCaseNotes(Long offenderBookId,String modifyUserId);
    void prCasePlans(Long offenderBookId,String modifyUserId);
    void prAssessmentSummaries(Long offenderBookId,Long casePlanId,String modifyUserId);
    void prOffenderCaseConditions(BigDecimal offenderBookId,BigDecimal casePlanId,String modifyUserId);
    void prOffenderActionPlans(BigDecimal offCaseCondId,String modifyUserId);
    void prOffenderCriminogenicNeeds(BigDecimal offenderBookId,BigDecimal casePlanId,String modifyUserId);
    void prOffenderActionPlans1(BigDecimal offCrimNeedId,String modifyUserId);
    void prPlanDetails(Long offenderBookId,Long casePlanId,String modifyUserId);
    void prCaseworkSteps(Long offenderBookId,Long casePlanId,Long detailSeq,String modifyUserId);
    void prCourtEvents(Integer offenderBookId,String modifyUserId);
    void prCourtEventCharges(BigDecimal eventId,String modifyUserId);
    void prCourtEventSentences(BigDecimal eventId,String modifyUserId);
    void prLinkCaseTxns(BigDecimal eventId,String modifyUserId);
    void prDocumentTemplateQueues(BigDecimal offenderBookId,String modifyUserId);
    void prGlTransactions1(BigDecimal offenderBookId,String modifyUserId);
    void prHdcRequestReferrals(Long offenderBookId,String modifyUserId);
    void prHdcBoardDecisions(Long hdcRequestReferralId,String modifyUserId);
    void prHdcGovernorDecisions(Long hdcRequestReferralId,String modifyUserId);
    void prHdcProbStaffComments(Long hdcRequestReferralId,String modifyUserId);
    void prHdcProbStaffResponses(Long hdcRequestReferralId,String modifyUserId);
    void prHdcRequestReferrals1(Long parentHdcRequestReferralId,String modifyUserId);
    void prIncidentCaseParties(Long offenderBookId,String modifyUserId);
    void prIwpDocuments(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderActivityEvents(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderAlerts(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderAssessments(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderAssets(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderAssociatedParties(Long offenderBookId,String modifyUserId);
    void prOffenderAssocPartyNotes(Long associatedPartyId,String modifyUserId);
    void prOffenderAssocPrtyContcts(Long associatedPartyId,String modifyUserId);
    void prOffenderAssocPCntNotifs(Long associatedPartyId,Long partySeq,String modifyUserId);
    void prOffenderAssocPNotifs(Long associatedPartyId,String modifyUserId);
    void prOffenderAuthorisdVisitors(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderAthorisdVisitors1(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderBailDetails(Long offenderBookId,String modifyUserId);
    void prOffenderBookingAgyLocs(Long offenderBookId,String modifyUserId);
    void prOffenderBookingDetails(Long offenderBookId,String modifyUserId);
    void prOffenderBookingEvents(Long offenderBookId,String modifyUserId);
    void prOffenderCases(Long offenderBookId,String modifyUserId);
    void prCourtEvents1(Integer caseId,String modifyUserId);
    void prLinkCaseTxns1(Long caseId,String modifyUserId);
    void prLinkCaseTxns2(Long caseId,String modifyUserId);
    void prOffenderAssociatedPartis1(Long caseId,String modifyUserId);
    void prOffenderCases1(BigDecimal combinedCaseId);
    void prOffenderCaseIdentifiers(Long caseId,String modifyUserId);
    void prOffenderCaseStatuses(Long caseId,String modifyUserId);
    void prOffenderCharges1(Long caseId,String modifyUserId);
    void prCourtEventCharges1(BigDecimal offenderChargeId,String modifyUserId);
    void prLinkCaseTxns3(BigDecimal offenderChargeId,String modifyUserId);
    void prOffenderSentenceCharges(Long offenderChargeId,String modifyUserId);
    void prOffenderLicenceSentences(Long caseId,String modifyUserId);
    void prOffenderSentences(BigDecimal caseId,String modifyUserId);
    void prOrders1(Long caseId,String modifyUserId);
    void prOrderPurposes(Long orderId,String modifyUserId);
    void prOffenderCaseNotes(Integer offenderBookId,String modifyUserId);
    void prOffenderCaseNoteSents1(Integer caseNoteId,String modifyUserId);
    void prOffCaseNoteRecipients(Integer caseNoteId,String modifyUserId);
    void prOffenderCharges(Long offenderBookId,String modifyUserId);
    void prOffenderCipDetails(Long offenderBookId,String modifyUserId);
    void prOffenderClassPrograms(Long offenderBookId,String modifyUserId);
    void prOffenderClothes(Long offenderBookId,String modifyUserId);
    void prOffenderClothingBundles(Long offenderBookId,String modifyUserId);
    void prOffenderClothingIssue(Long offenderBookId,String modifyUserId);
    void prOffenderClothingItems1(Long offenderClothingIssueId,String modifyUserId);
    void prOffenderClothingItems(Long offenderBookId,String modifyUserId);
    void prOffenderCodefendants(Long codOffenderBookId,String modifyUserId);
    void prOffenderCodefendants1(Long offenderBookId,String modifyUserId);
    void prOffenderComments(Long offenderBookId,String modifyUserId);
    void prOffendrCommnityConditions(Long offenderBookId,String modifyUserId);
    void prOffenderCommSupHistories(Long offenderBookId,String modifyUserId);
    void prOffenderCompactAgreements(Long offenderBookId,String modifyUserId);
    void prOffenderContactPersons1(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderCourseAttendances(Long offenderBookId,String modifyUserId);
    void prOffenderCurfews(Long offenderBookId,String modifyUserId);
    void prCurfewAddresses(BigDecimal offenderCurfewId,String modifyUserId);
    void prHdcPrisonStaffComments(BigDecimal offenderCurfewId,String modifyUserId);
    void prHdcRequestReferrals2(BigDecimal offenderCurfewId,String modifyUserId);
    void prOffenderDrugAdmissions(Long offenderBookId,String modifyUserId);
    void prOffenderDrugAdmDrugs(Long offenderDrugAdmissionId,String modifyUserId);
    void prOffenderDrugSamples(Long offenderBookId,String modifyUserId);
    void prOffenderDrugResults(Long offenderDrugSampleId,String modifyUserId);
    void prOffenderEducations(Long offenderBookId,String modifyUserId);
    void prOffenderEmployments(Long offenderBookId,String modifyUserId);
    void prOffenderEscapes(Integer offenderBookId,String modifyUserId);
    void prOffenderExpenses(Long offenderBookId,String modifyUserId);
    void prOffenderExternalMovements(Long offenderBookId,String modifyUserId);
    void prOffenderFileLocations(Long offenderBookId,String modifyUserId);
    void prOffenderGangAffiliations(Long offenderBookId,String modifyUserId);
    void prOffenderGangEvidences(Long offenderBookId,String modifyUserId);
    void prOffenderGangInvests(Long offenderBookId,String modifyUserId);
    void prOffenderGrievances(Long offenderBookId,String modifyUserId);
    void prOffenderGrievanceTxns(Long grievanceId,String modifyUserId);
    void prOffenderGrievStaffs(Long grievanceId,String modifyUserId);
    void prOffenderHospitalVisits(Long offenderBookId,String modifyUserId);
    void prOffenderHwd(Long offenderBookId,String modifyUserId);
    void prOffenderHwdCharges(Long hwdId,String modifyUserId);
    void prOffenderHwdHty(Long hwdId,String modifyUserId);
    void prOffenderIdentifyingMarks(Long offenderBookId,String modifyUserId);
    void prOffenderIepLevels(Long offenderBookId,String modifyUserId);
    void prOffenderImages(Long offenderBookId,String modifyUserId);
    void prOffenderImprisonStatuses(Long offenderBookId,String modifyUserId);
    void prOffenderIncome(Long offenderBookId,String modifyUserId);
    void prOffenderIndSchedules(Long offenderBookId,String modifyUserId);
    void prOffenderIndSchSents1(Long eventId,String modifyUserId);
    void prOffenderInternalMovements(Long offenderBookId,String modifyUserId);
    void prOffenderIntMovPersons(Long offenderBookId,Long movementSeq,String modifyUserId);
    void prOffenderInternalStatuses(Integer offenderBookId,String modifyUserId);
    void prOffenderInterventionTiers(Long offenderBookId,String modifyUserId);
    void prOffenderLanguages(Long offenderBookId,String modifyUserId);
    void prOffenderLiabilities(Long offenderBookId,String modifyUserId);
    void prOffenderMailLogs(Long offenderBookId,String modifyUserId);
    void prOffenderMailRestrictions(Long offenderBookId,String modifyUserId);
    void prOffendrMilitryDiscCtions(Long offenderBookId,String modifyUserId);
    void prOffenderMilitaryRecords(Long offenderBookId,String modifyUserId);
    void prOffenderMilitaryWarZones(Long offenderBookId,String modifyUserId);
    void prOffenderOasysPlans(Long offenderBookId,String modifyUserId);
    void prOffenderOasysConcerns(Long offenderBookId,Long planSeq,String modifyUserId);
    void prOffenderOsysRiskToOthrs(Long offenderBookId,Long planSeq,String modifyUserId);
    void prOffenderOasysSections(Long offenderBookId,Long planSeq,String modifyUserId);
    void prOffenderOasysObjectives(Long offenderBookId,Long planSeq,String sectionCode,String modifyUserId);
    void prOffenderOasysActions(BigDecimal objectiveId,String modifyUserId);
    void prOffenderOasysSupervisions(BigDecimal objectiveId, Long actionSeq,String modifyUserId);
    void prOffenderOicSanctions(Long offenderBookId,String modifyUserId);
    void prOffenderParoleHearings(Long offenderBookId,String modifyUserId);
    void prOffenderParoleDecisions(Long offenderBookId,Long paroleHearingSeq,String modifyUserId);
    void prOffenderParoleConditions(Long scheduleId,Integer paroleDecisionSeq,String modifyUserId);
    void prOffenderParoleStipultions(Long scheduleId,Integer paroleDecisionSeq,String modifyUserId);
    void prOffenderParolePlans(Long offenderBookId,String modifyUserId);
    void prOffenderPlanedActivities(Long offenderBookId,String modifyUserId);
    void prOffenderPptyContainers(Long offenderBookId,String modifyUserId);
    void prOffenderPptyItems(Long offenderBookId,String modifyUserId);
    void prOffenderPptyItemEvents(Integer offenderBookId,String modifyUserId);
    void prOffenderPptyItemTxns(Integer offenderBookId,Integer eventSeq,String modifyUserId);
    void prOffenderPrgObligations(Long offenderBookId,String modifyUserId);
    void prOffenderCourseAttendancs1(Long offenderPrgObligationId,String modifyUserId);
    void prOffenderIndSchedules1(Integer offenderPrgObligationId,String modifyUserId);
    void prOffenderObligationAdjs(Integer offenderPrgObligationId,String modifyUserId);
    void prOffenderPrgObligationHty(Integer offenderPrgObligationId,String modifyUserId);
    void prOffenderProgramProfiles1(Integer offenderPrgObligationId,String modifyUserId);
    void prOffenderProceedings(BigDecimal offenderBookId,String modifyUserId);
    void prCourtEvents2(Integer offenderProceedingId,String modifyUserId);
    void prOffenderProceedingSents1(BigDecimal offenderProceedingId,String modifyUserId);
    void prOffenderProfiles(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderProgramProfiles(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderPropertyBundles(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderProposedMvmnts(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderMovementDetails(Long offenderBookId,Long movementSeq,String modifyUserId);
    void proffenderptr(Long offenderBookId,String modifyUserId);
    void prExtOwnershipTransfer(Long ptrId,String modifyUserId);
    void prOffenderBookingAgyLocs1(BigDecimal ptrId,String modifyUserId);
    void prOffenderPtrDetails(BigDecimal ptrId,String modifyUserId);
    void prOffenderReferrals(Long offenderBookId,String modifyUserId);
    void prOffenderReleaseDetails(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderResidences(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderRestrictions(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderRiskPredictors(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderSentCalculations(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderStgAffiliations(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderStgDetails(BigDecimal offenderBookId,BigDecimal stgSeq,String modifyUserId);
    void prOffenderStgAssociations(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderSubstanceAbuses(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderSupervisingCourts(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderSupervisionLevels(BigDecimal offenderBookId,String modifyUserId);
    void prOffenderSupervisionPlans(Long offenderBookId,String supervisionLevelType,String modifyUserId);
    void prOffenderPlanedActivities1(Long offenderBookId,Long planSeq,String modifyUserId);
    void prOffenderSupervisionRates(Long offenderBookId,String supervisionType,String modifyUserId);
    void prOffenderTeamAssignments(Long offenderBookId,String modifyUserId);
    void prOffenderTeamAssignHty(Long offenderBookId,String modifyUserId);
    void prOffenderTemporaryAbsences(Long offenderBookId,String modifyUserId);
    void prOffenderTmpRelSchedules(Long offenderBookId,String modifyUserId);
    void prOffenderVisits(Long offenderBookId,String modifyUserId);
    void prOffenderVisitVisitors(BigDecimal offenderVisitId,String modifyUserId);
    void prOffenderVitalSigns1(Long offenderBookId,String modifyUserId);
    void prOrders(BigDecimal offenderBookId,String modifyUserId);
    void prReleasePlans(BigDecimal offenderBookId,String modifyUserId);
    void prRpOtherOccupants(BigDecimal releasePlanId,String modifyUserId);
    void prStaffWorks(BigDecimal offenderBookId,String modifyUserId);
    void prStaffWorkAssignments(BigDecimal staffWorkId,String modifyUserId);
    void prSupervisionTransactions(BigDecimal offenderBookId,String modifyUserId);
    void prTaskAssignmentHty(BigDecimal offenderBookId,String modifyUserId);
    void prAssignments(Long offenderBookId,String modifyUserId);
    void proffendercustodystatus(Long offenderBookId,String modifyUserId);
}
