OIMSLEVL_CHECK_LOV_DATA{
select assessment_class from assessments where active_flag = 'Y' and ASSESSMENT_ID = :ASSESSMENTID

}
OIMSLEVL_FIND_RGASSESSMENTSECTIONS {
 	SELECT DESCRIPTION DESCRIPTION , ASSESSMENT_CODE CODE FROM ASSESSMENTS WHERE  ASSESSMENT_CLASS = 'SECT'  AND PARENT_ASSESSMENT_ID= ::ASSESSMENTID AND (ACTIVE_FLAG = 'Y' OR ::MODE = 'ENTER-QUERY' )  ORDER BY LIST_SEQ ,ACTIVE_FLAG DESC , ASSESSMENT_CODE
}

OIMSLEVL_FIND_RGASSESSMENTTYPES {
 	SELECT DESCRIPTION DESCRIPTION , ASSESSMENT_CODE CODE FROM ASSESSMENTS WHERE  ASSESSMENT_CLASS = 'TYPE'  AND (CASELOAD_TYPE IN (SELECT CASELOAD_TYPE                          FROM CASELOADS                         WHERE CASELOAD_ID = (SELECT WORKING_CASELOAD_ID      FROM STAFF_MEMBERS        WHERE USER_ID = :userId) ) OR CASELOAD_TYPE='BOTH' ) ORDER BY LIST_SEQ , ACTIVE_FLAG DESC , ASSESSMENT_CODE
}

OIMSLEVL_FIND_RGASSESSMENTRESULTS {
 SELECT C.DESCRIPTION DESCRIPTION , R.SUPERVISION_LEVEL_TYPE CODE, R.ASSESSMENT_ID  FROM ASSESSMENT_RESULTS R , REFERENCE_CODES C WHERE R.ASSESSMENT_ID = :ASSESSMENT_ID AND R.SUPERVISION_LEVEL_TYPE= C.CODE AND C.DOMAIN = 'SUP_LVL_TYPE' AND (R.ACTIVE_FLAG = 'Y' OR ' ' = 'ENTER-QUERY' ) ORDER BY R.LIST_SEQ , R.ACTIVE_FLAG DESC , R.SUPERVISION_LEVEL_TYPE
}

OIMSLEVL_ASSTYPE_FIND_ASSESSMENTS {
 	SELECT ASSESSMENT_ID, ASSESSMENT_CLASS, PARENT_ASSESSMENT_ID, ASSESSMENT_CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EFFECTIVE_DATE, EXPIRY_DATE, SCORE, MUTUAL_EXCLUSIVE_FLAG, DETERMINE_SUP_LEVEL_FLAG,REQUIRE_EVALUATION_FLAG,REQUIRE_APPROVAL_FLAG,REVIEW_CYCLE_DAYS,CASELOAD_TYPE,REVIEW_FLAG,ASSESS_COMMENT,HIGH_VALUE,LOW_VALUE,SEARCH_CRITERIA_FLAG,OVERRIDEABLE_FLAG,ASSESSMENT_TYPE,CALCULATE_TOTAL_FLAG,MEASURE,CREATE_USER_ID,CREATE_DATE,MODIFY_USER_ID,MODIFY_DATETIME,CREATE_DATETIME,CELL_SHARING_ALERT_FLAG,TOTAL_PERCENT,SCREEN_CODE,SCHEDULE_COMPLETE_DAYS,SECT_SCORE_INCLUDE_FLAG,SECT_SCORE_OVERRIDE_FLAG,MEDICAL_FLAG FROM ASSESSMENTS 
}

OIMSLEVL_ASSTYPE_ASSSECT_FIND_ASSESSMENTS {
SELECT ASSESSMENT_ID, ASSESSMENT_CLASS, PARENT_ASSESSMENT_ID, ASSESSMENT_CODE, DESCRIPTION, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EFFECTIVE_DATE, EXPIRY_DATE, SCORE, MUTUAL_EXCLUSIVE_FLAG, DETERMINE_SUP_LEVEL_FLAG, REQUIRE_EVALUATION_FLAG, REQUIRE_APPROVAL_FLAG, REVIEW_CYCLE_DAYS, CASELOAD_TYPE, REVIEW_FLAG, ASSESS_COMMENT, HIGH_VALUE, LOW_VALUE, SEARCH_CRITERIA_FLAG, OVERRIDEABLE_FLAG, ASSESSMENT_TYPE, CALCULATE_TOTAL_FLAG, MEASURE, CREATE_USER_ID, CREATE_DATE, MODIFY_USER_ID, MODIFY_DATETIME, CREATE_DATETIME, CELL_SHARING_ALERT_FLAG, TOTAL_PERCENT, SCREEN_CODE, SCHEDULE_COMPLETE_DAYS, SECT_SCORE_INCLUDE_FLAG, SECT_SCORE_OVERRIDE_FLAG, MEDICAL_FLAG FROM ASSESSMENTS WHERE PARENT_ASSESSMENT_ID = :ASSESSMENT_ID
order by LIST_SEQ


}

OIMSLEVL_TYPEASSSUP_FIND_ASSESSMENT_SUPERVISIONS {
 	SELECT ASSESSMENT_ID ,SUPERVISION_LEVEL_TYPE,LIST_SEQ,MINI_SCORE,MAX_SCORE,EFFECTIVE_DATE,EXPIRY_DATE,MODIFY_USER_ID,UPDATE_ALLOWED_FLAG,ACTIVE_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG from ASSESSMENT_SUPERVISIONS where  ASSESSMENT_ID = :ASSESSMENTID  order by LIST_SEQ,ACTIVE_FLAG DESC, mini_score asc	
}

OIMSLEVL_TYPEASSSUP_ASSSECT_FIND_ASSESSMENT_SUPERVISIONS {
 	SELECT ASSESSMENT_ID ,SUPERVISION_LEVEL_TYPE,LIST_SEQ,MINI_SCORE,MAX_SCORE,EFFECTIVE_DATE,EXPIRY_DATE,MODIFY_USER_ID,UPDATE_ALLOWED_FLAG,ACTIVE_FLAG,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG from ASSESSMENT_SUPERVISIONS where  ASSESSMENT_ID = :ASSESSMENTID order by LIST_SEQ,ACTIVE_FLAG DESC, mini_score asc
}

OIMSLEVL_TYPEASSSUP_INSERT_ASSESSMENT_SUPERVISIONS {
 insert into ASSESSMENT_SUPERVISIONS(ASSESSMENT_ID , SUPERVISION_LEVEL_TYPE, LIST_SEQ, MINI_SCORE, MAX_SCORE, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_ALLOWED_FLAG, ACTIVE_FLAG, CREATE_DATETIME, CREATE_USER_ID, SEAL_FLAG, MODIFY_USER_ID, MODIFY_DATETIME) values(:assessmentId, :supervisionLevelType, :listSeq, :miniScore, :maxScore, :effectiveDate, :expiryDate, :updateAllowedFlag, :activeFlag, CURRENT_TIMESTAMP , :createUserId, :sealFlag, null, null) 
}

OIMSLEVL_TYPEASSSUP_UPDATE_ASSESSMENT_SUPERVISIONS {
   update ASSESSMENT_SUPERVISIONS set ASSESSMENT_ID = :assessmentId, SUPERVISION_LEVEL_TYPE = :supervisionLevelType, LIST_SEQ = :listSeq, MINI_SCORE = :miniScore, MAX_SCORE = :maxScore, EFFECTIVE_DATE = :effectiveDate, EXPIRY_DATE = :expiryDate, MODIFY_USER_ID =:modifyUserId, UPDATE_ALLOWED_FLAG =:updateAllowedFlag, ACTIVE_FLAG =:activeFlag, MODIFY_DATETIME = CURRENT_TIMESTAMP, SEAL_FLAG = :sealFlag where ASSESSMENT_ID = :assessmentId and SUPERVISION_LEVEL_TYPE = :supervisionLevelType 	
}

OIMSLEVL_TYPEASSSUP_DELETE_ASSESSMENT_SUPERVISIONS { 
	DELETE FROM ASSESSMENT_SUPERVISIONS 	
	where  ASSESSMENT_ID =   :assessmentId and SUPERVISION_LEVEL_TYPE =  :supervisionLevelType
}

OIMSLEVL_WHEN_VALIDATE_ITEAM_DEL {
SELECT COUNT(*)
           FROM DUAL
          WHERE EXISTS ( SELECT 'Y'
                          FROM OFFENDER_ASSESSMENTS
                         WHERE assessment_type_id = :ASSESSMENTID )
}
OIMSLEVL_UPDATE_ENFORCE_MIN_MAX_FLAG_IN_ASSESSMENT{
update assessments set enforce_min_max_flag=:enforcementFlag, modify_user_id =:modifyUserId ,modify_datetime = current_timestamp  where assessment_id =:assessmentId
}
OIMSLEVL_SELECT_ENFORCE_MIN_MAX_FLAG_FROM_ASSESSMENT
{
select enforce_min_max_flag from assessments where assessment_id =:assessmentId
}

OIMSLEVL_UPDATE_SECTIONS_DETAILS{
  UPDATE ASSESSMENTS SET SECT_SCORE_INCLUDE_FLAG=:sectScoreIncludeFlag ,SECT_SCORE_OVERRIDE_FLAG =:sectScoreOverrideFlag ,modify_user_id =:modifyUserId ,modify_datetime = current_timestamp  WHERE ASSESSMENT_ID =:assessmentId
}
