
OIMSENOT_FIND_CGFKNEXTSECTION {
 	SELECT DESCRIPTION , ASSESSMENT_CODE CODE ,  ASSESSMENT_ID FROM ASSESSMENTS WHERE PARENT_ASSESSMENT_ID = :parentId::int  AND ASSESSMENT_ID != :ASSESSMENTID::int  ORDER BY LIST_SEQ
}

OIMSENOT_FIND_CGFKSECTIONCODE {
 	SELECT DESCRIPTION ,ASSESSMENT_CODE CODE , ASSESSMENT_ID   FROM ASSESSMENTS WHERE PARENT_ASSESSMENT_ID = :ASSESSMENTID ORDER BY LIST_SEQ
}

OIMSENOT_FIND_CGFKSCORETYPE {
 	SELECT 'SECTION SCORE' DESCRIPTION , 'SECTION' CODE FROM DUAL UNION SELECT 'TOTAL SCORE' , 'TOTAL' FROM DUAL 
}

OIMSENOT_FIND_CGFKNEXTSECTIONFLAG {
 	SELECT 'YES' AS DESCRIPTION ,'Y' AS CODE FROM DUAL UNION SELECT 'NO' ,'N' FROM DUAL ORDER BY CODE DESC
}

OIMSENOT_ASSESSMENTS_FIND_ASSESSMENTS {
 	SELECT ASSESSMENT_ID ,ASSESSMENT_CLASS ,PARENT_ASSESSMENT_ID ,ASSESSMENT_CODE ,DESCRIPTION ,LIST_SEQ ,ACTIVE_FLAG ,UPDATE_ALLOWED_FLAG ,EFFECTIVE_DATE ,
 	EXPIRY_DATE ,SCORE ,MUTUAL_EXCLUSIVE_FLAG ,DETERMINE_SUP_LEVEL_FLAG ,REQUIRE_EVALUATION_FLAG ,REQUIRE_APPROVAL_FLAG ,REVIEW_CYCLE_DAYS ,CASELOAD_TYPE ,
 	REVIEW_FLAG ,ASSESS_COMMENT ,HIGH_VALUE ,LOW_VALUE ,SEARCH_CRITERIA_FLAG ,OVERRIDEABLE_FLAG ,ASSESSMENT_TYPE ,CALCULATE_TOTAL_FLAG ,MEASURE ,CREATE_USER_ID ,
 	CREATE_DATE ,MODIFY_USER_ID ,MODIFY_DATETIME ,CREATE_DATETIME ,CELL_SHARING_ALERT_FLAG ,TOTAL_PERCENT ,SCREEN_CODE ,SCHEDULE_COMPLETE_DAYS ,
 	SECT_SCORE_INCLUDE_FLAG ,SECT_SCORE_OVERRIDE_FLAG ,MEDICAL_FLAG ,SEAL_FLAG   FROM ASSESSMENTS   
}
OIMSENOT_ASSESSSECTIONNOTIFICATIONS_FIND_ASSESS_SECTION_NOTIFICATIONS {
 	SELECT ASSESSMENT_ID ,SCORE_SEQ ,SCORE_TYPE ,MIN_SCORE ,MAX_SCORE ,NEXT_SECTION_FLAG ,NEXT_ASSESSMENT_ID ,ACTIVE_FLAG ,
 	EXPIRY_DATE ,MESSAGE_TEXT ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM ASSESS_SECTION_NOTIFICATIONS 
 	 where ASSESSMENT_ID = :ASSESSMENT_ID order by min_score
}
OIMSENOT_ASSESSSECTIONNOTIFICATIONS_INSERT_ASSESS_SECTION_NOTIFICATIONS {
   insert into ASSESS_SECTION_NOTIFICATIONS(ASSESSMENT_ID , SCORE_SEQ , SCORE_TYPE , MIN_SCORE , MAX_SCORE , NEXT_SECTION_FLAG , NEXT_ASSESSMENT_ID , ACTIVE_FLAG , EXPIRY_DATE , MESSAGE_TEXT , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG, MODIFY_USER_ID, MODIFY_DATETIME ) values(:assessmentId , :scoreSeq , :scoreType , :minScore , :maxScore , :nextSectionFlag , :nextAssessmentId , :activeFlag , :expiryDate , :messageText , CURRENT_TIMESTAMP, :createUserId, :sealFlag,null,null ) 
}
OIMSENOT_ASSESSSECTIONNOTIFICATIONS_UPDATE_ASSESS_SECTION_NOTIFICATIONS {
 update ASSESS_SECTION_NOTIFICATIONS set ASSESSMENT_ID = :assessmentId , SCORE_SEQ = :scoreSeq , SCORE_TYPE = :scoreType , MIN_SCORE = :minScore , MAX_SCORE = :maxScore , NEXT_SECTION_FLAG = :nextSectionFlag , NEXT_ASSESSMENT_ID = :nextAssessmentId , ACTIVE_FLAG = :activeFlag , EXPIRY_DATE = :expiryDate , MESSAGE_TEXT = :messageText , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where ASSESSMENT_ID = :assessmentId and SCORE_SEQ = :scoreSeq 
}

OIMSENOT_ASSESSSECTIONNOTIFICATIONS_DELETE_ASSESS_SECTION_NOTIFICATIONS { 
	DELETE FROM ASSESS_SECTION_NOTIFICATIONS
	where ASSESSMENT_ID = :assessmentId and SCORE_SEQ = :scoreSeq
}



OIMSENOT_ASSESS_SECTION_NOTIFICATIONS_PREINSERT {
	SELECT MAX(SCORE_SEQ)  SCORE_SEQ FROM ASSESS_SECTION_NOTIFICATIONS WHERE ASSESSMENT_ID = :ASSESSMENTID
}

OIMSENOT_ASSESS_SECTION_NOTIFICATIONS_POSTQUERY {
	SELECT DESCRIPTION, Assessment_CODE,assessment_id  FROM ASSESSMENTS WHERE ASSESSMENT_ID = :NEXT_ASSESSMENT_ID
}