insert into reference_domains (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE, PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SUPER_SET_DOMAIN, SEAL_FLAG)
values ('INC_STF_EQUP', 'Equipment ', 'ACTIVE', 'OMS_OWNER', 'TAG', null, null, null, '06-NOV-20 03.14.55.157403000 PM', 'OMS_OWNER', '06-NOV-20 03.14.55.157409000 PM', null, null, null);

commit;