insert into reference_domains (DOMAIN, DESCRIPTION, DOMAIN_STATUS, OWNER_CODE, APPLN_CODE, OLD_CODE_TABLE, PARENT_DOMAIN, CODE_LENGTH, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SUPER_SET_DOMAIN, SEAL_FLAG)
values ('INC_STF_FRCE', 'Force Used', 'ACTIVE', 'OMS_OWNER', 'TAG', null, null, null, '06-NOV-20 03.14.55.136187000 PM', 'OMS_OWNER', '07-NOV-20 12.09.57.277347000 AM', 'OMS_OWNER', null, null);

commit;
