GET_WORK_ASSIGNMENT_ID{
SELECT WORK_ASSIGNMENT_ID
              FROM WORK_ASSIGNMENTS
             WHERE OFFENDER_ID = :OFF_ID
               AND CASELOAD_ID = :CSLD_ID
               AND WORK_ASSIGN_STATUS = 'ACT'
}

GET_WORK_ASSIGNMENT_STATUSES_SEQ{
SELECT MAX (STATUS_SEQ) + 1
                 FROM WORK_ASSIGNMENT_STATUSES
                WHERE WORK_ASSIGNMENT_ID = :WRK_ASGN_ID
}

WORK_ASSIGNMENT_STATUSES_INSERT{
 insert into WORK_ASSIGNMENT_STATUSES ( WORK_ASSIGNMENT_ID, STATUS_SEQ, UPDATE_DATE, UPDATE_TIME, MODIFY_DATETIME, COMMENT_TEXT, WORK_ASSIGN_STATUS, CREATE_USER_ID, CREATE_DATETIME ) values ( :WRK_ASGN_ID, :NEXT_STS_SEQ, TRUNC (:P_MOVEMENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Deactivation as of ' || TO_CHAR (:P_MOVEMENT_DATE, 'MM/DD/YYYY'), 'INA', :createUserId, CURRENT_TIMESTAMP )                  
 }
 
UPDATE_WORK_ASSIGNMENTS{
UPDATE WORK_ASSIGNMENTS SET WORK_ASSIGN_STATUS = 'INA', COMMENT_TEXT = 'Deactivation as of ' || (to_date(:P_MOVEMENT_DATE),'MM/DD/YYYY')::text, LAST_STATUS_MODIFY_DATE =  :P_MOVEMENT_DATE, LAST_STATUS_MODIFY_TIME = :P_MOVEMENT_DATE, MODIFY_DATETIME = CURRENT_TIMESTAMP, MODIFY_USER_ID = :modifyUserId WHERE OFFENDER_ID = :OFF_ID AND CASELOAD_ID = :CSLD_ID AND WORK_ASSIGN_STATUS = 'ACT'
}
 