
OUMASSMU_FIND_RGSTAFFMEMBERROLESROLE {
 	SELECT   OMS_ROLE.ROLE_CODE , OMS_ROLE.ROLE_NAME ROLE_NAME , OMS_ROLE.ROLE_ID ROLE_ID  FROM OMS_ROLES OMS_ROLE ORDER BY ROLE_SEQ
}

OUMASSMU_FIND_CGFKMODPRIVACCESSPRIVILEGE {
 	SELECT REF_CODE.CODE  CODE   ,REF_CODE.DESCRIPTION  DESCRIPTION        ,REF_CODE.LIST_SEQ  LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'ACCESS_PRIVI' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE.LIST_SEQ        ,REF_CODE.DESCRIPTION
}

OUMASSMU_FIND_CGFKMODPRIVMODULENAME {
 	SELECT OMS_MOD.MODULE_NAME MODULE_NAME  ,OMS_MOD.DESCRIPTION DESCRIPTION  ,OMS_MOD.MODULE_TYPE MODULE_TYPE FROM OMS_MODULES OMS_MOD WHERE MODULE_TYPE IN ('SCREEN' ,'MENU' ,'REPORT' , 'TAB' ) ORDER BY OMS_MOD.MODULE_NAME  ,OMS_MOD.MODULE_TYPE
}

OUMASSMU_OMSROLE_FIND_OMS_ROLES {
 	SELECT ROLE_ID ,ROLE_NAME ,ROLE_SEQ ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,ROLE_CODE ,PARENT_ROLE_CODE ,SEAL_FLAG  
 	FROM OMS_ROLES  
}
OUMASSMU_MODPRIV_FIND_MODULE_PRIVILEGES {
 	SELECT MP. MODULE_NAME , MP.ROLE_ID , MP.ACCESS_PRIVILEGE , MP.VERIFICATION_FLAG , MP.CREATE_DATETIME , MP.CREATE_USER_ID , MP.MODIFY_DATETIME , MP.MODIFY_USER_ID , MP.SEAL_FLAG, mod.description, mod.module_type 
	FROM MODULE_PRIVILEGES MP JOIN OMS_MODULES MOD ON  MOD.MODULE_NAME = MP.MODULE_NAME
	WHERE  MP.ROLE_ID = :ROLE_ID AND    MOD.MODULE_TYPE IN ('SCREEN','MENU','REPORT','TAB') ORDER BY MP.MODULE_NAME ASC
}
OUMASSMU_MODPRIV_INSERT_MODULE_PRIVILEGES {
insert into MODULE_PRIVILEGES(MODULE_NAME , ROLE_ID , ACCESS_PRIVILEGE , VERIFICATION_FLAG , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:moduleName , :roleId , :accessPrivilege , :verificationFlag , CURRENT_TIMESTAMP , :createUserId , null , :sealFlag )
}

OUMASSMU_MODPRIV_UPDATE_MODULE_PRIVILEGES {
   update MODULE_PRIVILEGES set MODULE_NAME = :moduleName , ROLE_ID = :roleId , ACCESS_PRIVILEGE = :accessPrivilege , VERIFICATION_FLAG = :verificationFlag , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID =:modifyUserId , SEAL_FLAG = :sealFlag where MODULE_NAME = :moduleName and ROLE_ID = :roleId 
}

OUMASSMU_MODPRIV_DELETE_MODULE_PRIVILEGES { 
	DELETE FROM MODULE_PRIVILEGES where MODULE_NAME  = :moduleName AND ROLE_ID  = :roleId
}


OUMASSMU_CGFKCHK_MOD_PRIV_MOD_PRIV_ACC {
	SELECT REF_CODE.DESCRIPTION ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :ACCESSPRIVILEGE AND     DOMAIN = 'ACCESS_PRIVI' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OUMASSMU_CGFKCHK_MOD_PRIV_MOD_PRIV_OMS {
	SELECT OMS_MOD.DESCRIPTION ,OMS_MOD.MODULE_TYPE FROM   OMS_MODULES OMS_MOD WHERE  OMS_MOD.MODULE_NAME = :MODULENAME AND     MODULE_TYPE IN ('SCREEN','MENU','REPORT','TAB')
}

OUMASSMU_CGUVCHK_MODULE_PRIVS_PK {
	SELECT  '1' FROM    MODULE_PRIVILEGES WHERE   MODULE_NAME = P_MODULE_NAME AND     ROLE_ID = P_ROLE_ID
}

OUMASSMU_CGWHEN_NEW_FORM_INSTANCE {
SELECT current_timestamp, 'OMS_OWNER'
}






