
OUMPERSO_FIND_RGPHONETYPE {
 	SELECT DESCRIPTION  , CODE   FROM REFERENCE_CODES   WHERE DOMAIN = 'PHONE_USAGE'    AND ACTIVE_FLAG = 'Y'    AND EXPIRED_DATE IS NULL  ORDER BY LIST_SEQ ,            DESCRIPTION
}

OUMPERSO_FIND_RGSUFFIX {
 	SELECT DESCRIPTION ,        CODE    FROM REFERENCE_CODES  WHERE DOMAIN = 'SUFFIX'    AND ACTIVE_FLAG = 'Y'    AND EXPIRED_DATE IS NULL  ORDER BY LIST_SEQ ,            CODE
}

OUMPERSO_FIND_RGSEXCODE {
 	SELECT DESCRIPTION  ,        CODE     FROM REFERENCE_CODES  WHERE DOMAIN = 'SEX'     AND ACTIVE_FLAG = 'Y'     AND EXPIRED_DATE IS NULL
}

OUMPERSO_FIND_RGSTATUS {
 	SELECT   DESCRIPTION  ,                   CODE     FROM REFERENCE_CODES    WHERE ( DOMAIN = 'STAFF_STATUS'           AND (ACTIVE_FLAG = 'Y' OR :MODE <> 'NORMAL' )           ) ORDER BY LIST_SEQ ASC ,           DESCRIPTION ASC ,          CODE ASC
}

OUMPERSO_FIND_RGPERSONNELTYPE {
 	SELECT DESCRIPTION         ,CODE         FROM REFERENCE_CODES WHERE DOMAIN = 'PERSONNEL_TP'   AND ACTIVE_FLAG = 'Y'    AND EXPIRED_DATE IS NULL ORDER BY  LIST_SEQ , DESCRIPTION
}

OUMPERSO_FIND_RGPOSITION {
 	SELECT   DESCRIPTION  ,          CODE   FROM REFERENCE_CODES    WHERE DOMAIN = 'PERSONNEL_PO'      AND ('PERSONNELTYPE' = 'PERSONNELTYPE' OR :MODE <> 'NORMAL' )      AND ACTIVE_FLAG = 'Y'      AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ , DESCRIPTION
}

OUMPERSO_STAFF_FIND_STAFF_MEMBERS {
 	SELECT STAFF_ID ,MAIL_ID, AD_USER, ASSIGNED_CASELOAD_ID ,WORKING_STOCK_LOC_ID ,WORKING_CASELOAD_ID ,USER_ID,USER_ID USERIDVAL ,BADGE_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,ABBREVIATION ,POSITION ,BIRTHDATE ,TERMINATION_DATE ,UPDATE_ALLOWED_FLAG ,DEFAULT_PRINTER_ID ,SUSPENDED_FLAG ,SUPERVISOR_STAFF_ID ,COMM_RECEIPT_PRINTER_ID ,PERSONNEL_TYPE ,AS_OF_DATE ,EMERGENCY_CONTACT ,ROLE ,SEX_CODE ,STATUS ,SUSPENSION_DATE ,SUSPENSION_REASON ,FORCE_PASSWORD_CHANGE_FLAG ,LAST_PASSWORD_CHANGE_DATE ,LICENSE_CODE ,LICENSE_EXPIRY_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,TITLE ,NAME_SEQUENCE ,QUEUE_CLUSTER_ID ,FIRST_LOGON_FLAG ,SUFFIX ,SEAL_FLAG   FROM STAFF_MEMBERS  /* where  */
}
OUMPERSO_STAFF_INSERT_STAFF_MEMBERS {
insert into STAFF_MEMBERS(STAFF_ID , MAIL_ID, AD_USER, ASSIGNED_CASELOAD_ID , WORKING_STOCK_LOC_ID , WORKING_CASELOAD_ID , USER_ID , BADGE_ID , LAST_NAME , FIRST_NAME , MIDDLE_NAME , ABBREVIATION , position , BIRTHDATE , TERMINATION_DATE , UPDATE_ALLOWED_FLAG , DEFAULT_PRINTER_ID , SUSPENDED_FLAG , SUPERVISOR_STAFF_ID , COMM_RECEIPT_PRINTER_ID , PERSONNEL_TYPE , AS_OF_DATE , EMERGENCY_CONTACT , role , SEX_CODE , STATUS , SUSPENSION_DATE , SUSPENSION_REASON , FORCE_PASSWORD_CHANGE_FLAG , LAST_PASSWORD_CHANGE_DATE , LICENSE_CODE , LICENSE_EXPIRY_DATE , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , TITLE , NAME_SEQUENCE , QUEUE_CLUSTER_ID , FIRST_LOGON_FLAG , SUFFIX , SEAL_FLAG ) values(:staffId , :mailId, :adUser, :assignedCaseloadId , :workingStockLocId , :workingCaseloadId , :userId , :badgeId , :lastName , :firstName , :middleName , :abbreviation , :position , :birthdate , :terminationDate , :updateAllowedFlag , :defaultPrinterId , :suspendedFlag , :supervisorStaffId , :commReceiptPrinterId , :personnelType , :asOfDate , :emergencyContact , :role , :sexCode , :status , :suspensionDate , :suspensionReason , :forcePasswordChangeFlag , :lastPasswordChangeDate , :licenseCode , :licenseExpiryDate , CURRENT_TIMESTAMP , :createUserId , null , :title , :nameSequence , :queueClusterId , :firstLogonFlag , :suffix , :sealFlag )
}

OUMPERSO_STAFF_UPDATE_STAFF_MEMBERS {
update STAFF_MEMBERS set STAFF_ID = :staffId , ASSIGNED_CASELOAD_ID = :assignedCaseloadId , WORKING_STOCK_LOC_ID = :workingStockLocId , WORKING_CASELOAD_ID = :workingCaseloadId , USER_ID = :userId , BADGE_ID = :badgeId , LAST_NAME = :lastName , FIRST_NAME = :firstName , MIDDLE_NAME = :middleName , ABBREVIATION = :abbreviation , position = :position , BIRTHDATE = :birthdate , TERMINATION_DATE = :terminationDate , UPDATE_ALLOWED_FLAG = :updateAllowedFlag , DEFAULT_PRINTER_ID = :defaultPrinterId , SUSPENDED_FLAG = :suspendedFlag , SUPERVISOR_STAFF_ID = :supervisorStaffId , COMM_RECEIPT_PRINTER_ID = :commReceiptPrinterId , PERSONNEL_TYPE = :personnelType , AS_OF_DATE = :asOfDate , EMERGENCY_CONTACT = :emergencyContact , role = :role , SEX_CODE = :sexCode , STATUS = :status , SUSPENSION_DATE = :suspensionDate , SUSPENSION_REASON = :suspensionReason , FORCE_PASSWORD_CHANGE_FLAG = :forcePasswordChangeFlag , LAST_PASSWORD_CHANGE_DATE = :lastPasswordChangeDate , LICENSE_CODE = :licenseCode , LICENSE_EXPIRY_DATE = :licenseExpiryDate , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , TITLE = :title , NAME_SEQUENCE = :nameSequence , QUEUE_CLUSTER_ID = :queueClusterId , FIRST_LOGON_FLAG = :firstLogonFlag , SUFFIX = :suffix , MAIL_ID = :mailId, SEAL_FLAG = :sealFlag where STAFF_ID = :staffId
}

OUMPERSO_IMAGE_FIND_IMAGES {
 	SELECT IMAGE_ID ,CAPTURE_DATE ,IMAGE_OBJECT_TYPE ,IMAGE_OBJECT_ID ,IMAGE_OBJECT_SEQ ,IMAGE_VIEW_TYPE ,IMAGE_THUMBNAIL ,ACTIVE_FLAG ,ORIENTATION_TYPE ,SEAL_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID   FROM IMAGES  where IMAGE_OBJECT_ID = :imageObjectId  AND ACTIVE_FLAG='Y'
}
OUMPERSO_VSTFADDR_FIND_V_STAFF_ADDRESSES {
 	SELECT ADDRESS_ID ,ADDRESS_TYPE ,ADDRESS_TYPE_DESC ,STAFF_ID ,LAST_NAME ,FIRST_NAME ,START_DATE ,END_DATE ,ACTIVE_FLAG ,HOUSE ,STREET ,AREA ,COUNTRY ,SUITE_NUMBER ,STREET_NUMBER ,STREET_DIRECTION ,STREET_DIRECTION_DESC ,STREET_INFORMATION ,CITY_CODE ,CITY_NAME ,PROV_STATE_CODE ,PROV_STATE_DESC ,ZIP_POSTAL_CODE ,COUNTRY_CODE ,COMMENT_TEXT ,PRIMARY_FLAG ,MAIL_FLAG ,VALIDATED_FLAG ,IS_ADDRESS_VALID,ADDRESS_LINE1   FROM V_STAFF_ADDRESSES   where  STAFF_ID = :staffId
}
OUMPERSO_ADDRPHONES_FIND_PHONES {
 	SELECT PHONE_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,PHONE_TYPE ,PHONE_NO ,EXT_NO ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG ,FORMAT  FROM PHONES   where OWNER_ID = :ownerId and OWNER_CLASS =:ownerClass
}
OUMPERSO_ADDRPHONES_INSERT_PHONES {
insert into PHONES(PHONE_ID , OWNER_CLASS , OWNER_ID , OWNER_SEQ , OWNER_CODE , PHONE_TYPE , PHONE_NO , EXT_NO , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG , FORMAT) values(:phoneId , :ownerClass , :ownerId , :ownerSeq , :ownerCode , :phoneType , :phoneNo , :extNo , CURRENT_TIMESTAMP , :createUserId , null , :sealFlag, :format )
}

OUMPERSO_ADDRPHONES_UPDATE_PHONES {
	update PHONES set PHONE_ID = :phoneId , OWNER_CLASS = :ownerClass , OWNER_ID = :ownerId , OWNER_SEQ = :ownerSeq , OWNER_CODE = :ownerCode , PHONE_TYPE = :phoneType , PHONE_NO = :phoneNo , EXT_NO = :extNo , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag,FORMAT=:format where PHONE_ID = :phoneId
}

OUMPERSO_ADDRPHONES_DELETE_PHONES { 
	DELETE FROM PHONES where  PHONE_ID = :phoneId
}

OUMPERSO_EMAILADDR_FIND_INTERNET_ADDRESSES {
 	SELECT INTERNET_ADDRESS_ID ,OWNER_CLASS ,OWNER_ID ,OWNER_SEQ ,OWNER_CODE ,INTERNET_ADDRESS_CLASS ,INTERNET_ADDRESS ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM INTERNET_ADDRESSES  where OWNER_ID = :ownerId and OWNER_CLASS='STF' /* where  */
}
OUMPERSO_EMAILADDR_INSERT_INTERNET_ADDRESSES {
insert into INTERNET_ADDRESSES(INTERNET_ADDRESS_ID , OWNER_CLASS , OWNER_ID , OWNER_SEQ , OWNER_CODE , INTERNET_ADDRESS_CLASS , INTERNET_ADDRESS , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:internetAddressId , :ownerClass , :ownerId , :ownerSeq , :ownerCode , :internetAddressClass , :internetAddress , CURRENT_TIMESTAMP , :createUserId , null , :sealFlag )
}

OUMPERSO_EMAILADDR_UPDATE_INTERNET_ADDRESSES {
    update INTERNET_ADDRESSES set INTERNET_ADDRESS_ID = :internetAddressId , OWNER_CLASS = :ownerClass , OWNER_ID = :ownerId , OWNER_SEQ = :ownerSeq , OWNER_CODE = :ownerCode , INTERNET_ADDRESS_CLASS = :internetAddressClass , INTERNET_ADDRESS = :internetAddress , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where INTERNET_ADDRESS_ID =:internetAddressId /* where */
}

OUMPERSO_EMAILADDR_DELETE_INTERNET_ADDRESSES { 
	DELETE FROM INTERNET_ADDRESSES   where INTERNET_ADDRESS_ID=:internetAddressId   
}


OUMPERSO_STAFF_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM TAG_IMAGES I WHERE I.IMAGE_OBJECT_ID = :STAFFID
}

OUMPERSO_STAFF_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM V_STAFF_ADDRESSES V WHERE V.STAFF_ID = :STAFFID
}

OUMPERSO_STAFF_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM PHONES P WHERE P.OWNER_ID = :STAFFID
}

OUMPERSO_STAFF_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM INTERNET_ADDRESSES I WHERE I.OWNER_ID = :STAFFID
}

OUMPERSO_STAFF_PREINSERT_ {
select NEXTVAL('STAFF_ID') from dual;
}

OUMPERSO_V_STF_ADDR_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM PHONES P WHERE P.OWNER_ID = :ADDRESSID
}

OUMPERSO_ADDR_PHONES_PREINSERT_ {
SELECT NEXTVAL('PHONE_ID')
}

OUMPERSO_STF_PHONES_PREINSERT_ {
SELECT NEXTVAL('PHONE_ID')
}

OUMPERSO_EMAIL_ADDR_PREINSERT_ {
SELECT NEXTVAL('INTERNET_ADDRESS_ID')
}

OUMPERSO_GET_STAFF_DETAILS {
	SELECT * FROM STAFF_MEMBERS WHERE MODIFY_DATETIME >= :fromDate or  CREATE_DATETIME >= :fromDate
}
PHONES_T2_GET_ADDRESS_OBJECT {
select * from PHONES where phone_id=:phoneId
}
OUMPERSO_CHECK_MAILID {
	select mail_id from staff_members where staff_id = :staffId
}
