
OUMPERSD_FIND_CGFKSTAFFLICENSECODE {
 	SELECT REF_CODE.CODE LICENSE_CODE  ,REF_CODE.DESCRIPTION DSP_DESCRIPTION FROM REFERENCE_CODES REF_CODE WHERE DOMAIN = 'TPT_VEH_LIC' AND ((ACTIVE_FLAG = 'Y'AND EXPIRED_DATE IS NULL ) OR ::MODE = 'QUERY' )
}

OUMPERSD_STAFF_FIND_STAFF_MEMBERS {
 	SELECT STAFF_ID ,ASSIGNED_CASELOAD_ID ,WORKING_STOCK_LOC_ID ,WORKING_CASELOAD_ID ,USER_ID ,BADGE_ID ,LAST_NAME ,FIRST_NAME ,MIDDLE_NAME ,ABBREVIATION ,POSITION ,BIRTHDATE ,TERMINATION_DATE ,UPDATE_ALLOWED_FLAG ,DEFAULT_PRINTER_ID ,SUSPENDED_FLAG ,SUPERVISOR_STAFF_ID ,COMM_RECEIPT_PRINTER_ID ,PERSONNEL_TYPE ,AS_OF_DATE ,EMERGENCY_CONTACT ,ROLE ,SEX_CODE ,STATUS ,SUSPENSION_DATE ,SUSPENSION_REASON ,FORCE_PASSWORD_CHANGE_FLAG ,LAST_PASSWORD_CHANGE_DATE ,LICENSE_CODE ,LICENSE_EXPIRY_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,TITLE ,NAME_SEQUENCE ,QUEUE_CLUSTER_ID ,FIRST_LOGON_FLAG ,SUFFIX ,SEAL_FLAG   FROM STAFF_MEMBERS
}
OUMPERSD_STAFF_UPDATE_STAFF_MEMBERS {
	UPDATE STAFF_MEMBERS set STAFF_ID  = :staffId ,ASSIGNED_CASELOAD_ID  = :assignedCaseloadId ,WORKING_STOCK_LOC_ID  = :workingStockLocId ,WORKING_CASELOAD_ID  = :workingCaseloadId ,USER_ID  = :userId ,BADGE_ID  = :badgeId ,LAST_NAME  = :lastName ,FIRST_NAME  = :firstName ,MIDDLE_NAME  = :middleName ,ABBREVIATION  = :abbreviation ,POSITION  = :position ,BIRTHDATE  = :birthdate ,TERMINATION_DATE  = :terminationDate ,UPDATE_ALLOWED_FLAG  = :updateAllowedFlag ,DEFAULT_PRINTER_ID  = :defaultPrinterId ,SUSPENDED_FLAG  = :suspendedFlag ,SUPERVISOR_STAFF_ID  = :supervisorStaffId ,COMM_RECEIPT_PRINTER_ID  = :commReceiptPrinterId ,PERSONNEL_TYPE  = :personnelType ,AS_OF_DATE  = :asOfDate ,EMERGENCY_CONTACT  = :emergencyContact ,ROLE  = :role ,SEX_CODE  = :sexCode ,STATUS  = :status ,SUSPENSION_DATE  = :suspensionDate ,SUSPENSION_REASON  = :suspensionReason ,FORCE_PASSWORD_CHANGE_FLAG  = :forcePasswordChangeFlag ,LAST_PASSWORD_CHANGE_DATE  = :lastPasswordChangeDate ,LICENSE_CODE  = :licenseCode ,LICENSE_EXPIRY_DATE  = :licenseExpiryDate ,MODIFY_DATETIME  = CURRENT_TIMESTAMP ,MODIFY_USER_ID  = :modifyUserId ,TITLE  = :title ,NAME_SEQUENCE  = :nameSequence ,QUEUE_CLUSTER_ID  = :queueClusterId ,FIRST_LOGON_FLAG  = :firstLogonFlag ,SUFFIX  = :suffix ,SEAL_FLAG  = :sealFlag  where STAFF_ID  = :staffId 
}


OUMPERSD_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO   V_FORM_DESC FROM   OMS_MODULES WHERE  MODULE_NAME = V_FORM_NAME
}

OUMPERSD_CGFKCHK_STAFF_STAFF_REF_CODE__ {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :LICENSECODE AND     DOMAIN = 'TPT_VEH_LIC' AND ((ACTIVE_FLAG = 'Y'AND EXPIRED_DATE IS NULL) OR :MODE = 'QUERY')
}

OUMPERSD_CGWHEN_NEW_FORM_INSTANCE_ {
SELECT current_timestamp, 'OMS_OWNER'

}
