
OUMROLES_OMSROLE_FIND_OMS_ROLES {
 	SELECT ROLE_ID ,ROLE_NAME ,ROLE_SEQ ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,ROLE_CODE ,PARENT_ROLE_CODE ,SEAL_FLAG   FROM OMS_ROLES  
}
OUMROLES_OMSROLE_INSERT_OMS_ROLES_TEST {
 insert into OMS_ROLES(ROLE_ID , ROLE_NAME , ROLE_SEQ , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , ROLE_CODE , PARENT_ROLE_CODE , SEAL_FLAG ) values( nextval('role_id') , :roleName , :roleSeq , current_timestamp , :createUserId , null , :roleCode , :parentRoleCode , :sealFlag ) 
}

 OUMROLES_OMSROLE_UPDATE_OMS_ROLES {
update OMS_ROLES set ROLE_NAME = :roleName , ROLE_SEQ = :roleSeq , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , ROLE_CODE = :roleCode , PARENT_ROLE_CODE = :parentRoleCode , SEAL_FLAG = :sealFlag where ROLE_ID = :roleId
}

OUMROLES_OMSROLE_DELETE_OMS_ROLES { 
	DELETE FROM OMS_ROLES WHERE ROLE_ID  = :roleId
}


OUMROLES_OMS_ROLE_PREINSERT {
	SELECT COALESCE(MAX(ROLE_ID),0)+1 FROM OMS_ROLES 
}
