
OUMUSERS_FIND_RGSTAFFASSIGNEDCASELOAD {
 	SELECT CSLD1.CASELOAD_ID   ,        CSLD1.DESCRIPTION   ,        CSLD1.LIST_SEQ     FROM CASELOADS CSLD1   WHERE ACTIVE_FLAG = 'Y'   ORDER BY CSLD1.LIST_SEQ  ,CSLD1.DESCRIPTION
}

OUMUSERS_FIND_RGSTAFFMEMBERROLESROLE {
 	SELECT   OMS_ROLE.ROLE_CODE , OMS_ROLE.ROLE_NAME  , OMS_ROLE.ROLE_ID ROLE_ID      FROM OMS_ROLES OMS_ROLE ORDER BY ROLE_SEQ
}

OUMUSERS_FIND_RGSTAFFACCASELOADID {
 	SELECT CSLD.CASELOAD_ID CASELOAD_ID   , CSLD.DESCRIPTION   , CSLD.LIST_SEQ  FROM CASELOADS CSLD WHERE ACTIVE_FLAG = 'Y' ORDER BY CSLD.LIST_SEQ  ,CSLD.DESCRIPTION
}

OUMUSERS_STAFF_FIND_STAFF_MEMBERS {
SELECT
    staff_id,
    assigned_caseload_id,
    working_stock_loc_id,
    working_caseload_id,
    user_id,
    user_id useridval,
    badge_id,
    last_name,
    first_name,
    middle_name,
    abbreviation,
    position,
    birthdate,
    termination_date,
    update_allowed_flag,
    default_printer_id,
    suspended_flag,
    supervisor_staff_id,
    comm_receipt_printer_id,
    personnel_type,
    as_of_date,
    emergency_contact,
    role,
    sex_code,
    status,
    suspension_date,
    suspension_reason,
    force_password_change_flag,
    last_password_change_date,
    license_code,
    license_expiry_date,
    create_datetime,
    create_user_id,
    modify_datetime,
    modify_user_id,
    title,
    name_sequence,
    queue_cluster_id,
    first_logon_flag,
    suffix,
    seal_flag,
    mail_id,
    ad_user
FROM
    staff_members
    
    
}
OUMUSERS_STAFF_UPDATE_STAFF_MEMBERS {

update staff_members set assigned_caseload_id = :assignedCaseloadId, user_id = :userId, termination_date = :terminationDate, modify_datetime = current_timestamp, modify_user_id =:modifyUserId  where staff_id = :staffId
	}

OUMUSERS_STAFF_DELETE_STAFF_MEMBERS { 
	DELETE FROM STAFF_MEMBERS/* where */
}

OUMUSERS_STAFFAC_FIND_STAFF_ACCESSIBLE_CASELOADS {
 	SELECT CASELOAD_ID ,STAFF_ID ,UPDATE_ALLOWED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM STAFF_ACCESSIBLE_CASELOADS  where STAFF_ID = :staffId ORDER BY CASELOAD_ID 

}
OUMUSERS_STAFFAC_INSERT_STAFF_ACCESSIBLE_CASELOADS {
insert into STAFF_ACCESSIBLE_CASELOADS(CASELOAD_ID , STAFF_ID , UPDATE_ALLOWED_FLAG , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:caseloadId , :staffId , :updateAllowedFlag , current_timestamp , :createUserId , null , :sealFlag )
}

OUMUSERS_STAFFAC_UPDATE_STAFF_ACCESSIBLE_CASELOADS {
 update STAFF_ACCESSIBLE_CASELOADS set CASELOAD_ID = :caseloadId , STAFF_ID = :staffId , UPDATE_ALLOWED_FLAG = :updateAllowedFlag , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where CASELOAD_ID = :caseloadId and STAFF_ID = :staffId
}

OUMUSERS_STAFFAC_DELETE_STAFF_ACCESSIBLE_CASELOADS { 
	DELETE FROM STAFF_ACCESSIBLE_CASELOADS  where STAFF_ID  = :staffId and CASELOAD_ID  = :caseloadId
}

OUMUSERS_STAFFMEMBERROLES_FIND_STAFF_MEMBER_ROLES {
 	SELECT STAFF_ID ,ROLE_ID ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,ROLE_CODE ,SEAL_FLAG   FROM STAFF_MEMBER_ROLES   where  STAFF_ID = :staffId  ORDER BY ROLE_CODE
 	}
OUMUSERS_STAFFMEMBERROLES_INSERT_STAFF_MEMBER_ROLES {
insert into STAFF_MEMBER_ROLES(STAFF_ID , ROLE_ID , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , ROLE_CODE , SEAL_FLAG ) values(:staffId , :roleId , current_timestamp , :createUserId , null , :roleCode , :sealFlag )
}

OUMUSERS_STAFFMEMBERROLES_DELETE_STAFF_MEMBER_ROLES { 
	DELETE FROM STAFF_MEMBER_ROLES where ROLE_ID = :roleId and STAFF_ID = :staffId 
}


OUMUSERS_CAL_FIND_CASELOAD_AGENCY_LOCATIONS {
 	SELECT CASELOAD_ID ,AGY_LOC_ID ,UPDATE_ALLOWED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM CASELOAD_AGENCY_LOCATIONS  where CASELOAD_ID = :caseloadId
}
OUMUSERS_CAL_UPDATE_CASELOAD_AGENCY_LOCATIONS {
	update CASELOAD_AGENCY_LOCATIONS set CASELOAD_ID = :caseloadId , AGY_LOC_ID = :agyLocId , UPDATE_ALLOWED_FLAG = :updateAllowedFlag , MODIFY_DATETIME = current_timestamp , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag 
}


OUMUSERS_CGFKCHK_STAFF_STAFF_CSLD_F1_ {
	SELECT CSLD1.DESCRIPTION ,CSLD1.LIST_SEQ FROM   CASELOADS CSLD1 WHERE  CSLD1.CASELOAD_ID = :ASSIGNEDCASELOADID
}

OUMUSERS_CGFKCHK_STAFF_AC_STAFF_AC_CSL_ {
	SELECT CSLD.DESCRIPTION ,CSLD.LIST_SEQ FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID
}

OUMUSERS_CGFKCHK_STAFF_MEMBER_ROLES_ST_ {
	SELECT OMS_ROLE.ROLE_NAME FROM   OMS_ROLES OMS_ROLE WHERE  OMS_ROLE.ROLE_CODE = :ROLECODE
}

OUMUSERS_CGRICHK_STAFF_MEMBERS_ {
	SELECT  '1' FROM    PERSONNEL_IDENTIFICATIONS PER_IDE WHERE   PER_IDE.STAFF_ID = P_STAFF_ID
}

OUMUSERS_CGRICHK_STAFF_MEMBERS_ {
	SELECT  '1' FROM    PERSONNEL_ISSUED_CARDS PIC WHERE   PIC.STAFF_ID = P_STAFF_ID
}

OUMUSERS_CGRICHK_STAFF_MEMBERS_ {
	SELECT  '1' FROM    OFFENDER_MEDICAL_SCREENINGS OMS WHERE   OMS.STAFF_ID = P_STAFF_ID
}

OUMUSERS_CGRICHK_STAFF_MEMBERS_ {
	SELECT  '1' FROM    OFFENDER_BOOKINGS OFF_BKG WHERE   OFF_BKG.ASSIGNED_STAFF_ID = P_STAFF_ID
}

OUMUSERS_CGRICHK_STAFF_MEMBERS_ {
	SELECT  '1' FROM    OFFENDER_BOOKINGS OFF_BKG WHERE   OFF_BKG.PHOTO_TAKING_STAFF_ID = P_STAFF_ID
}

OUMUSERS_CGRICHK_STAFF_MEMBERS_ {
	SELECT  '1' FROM    OFFENDER_BOOKINGS OFF_BKG WHERE   OFF_BKG.SEARCH_STAFF_ID = P_STAFF_ID
}

OUMUSERS_CGRICHK_STAFF_MEMBERS_ {
	SELECT  '1' FROM    OFFENDER_BOOKINGS OFF_BKG WHERE   OFF_BKG.FINGER_PRINTED_STAFF_ID = P_STAFF_ID
}

OUMUSERS_CGFKCHK_CAL_CSLD_AL_AGY_LOC_F_ {
	SELECT AL.DESCRIPTION ,AL.AGENCY_LOCATION_TYPE FROM   AGENCY_LOCATIONS AL WHERE  AL.AGY_LOC_ID = :AGYLOCID
}
OUMUSERS_USERID_CHECK_CUR {
SELECT COUNT(*) FROM STAFF_MEMBERS WHERE USER_ID = :V_USER_ID
}

OUMUSERS_C_SYSTEM_USERS {
  SELECT USERNAME
   FROM (
   SELECT  USERNAME
     FROM  DBA_USERS
    WHERE  DEFAULT_TABLESPACE NOT IN  ('TAG_DATA','USERS')
    UNION
   SELECT  'OMS_OWNER' 
    UNION
   SELECT  'INTERNAL' 
    ) AS Y
  WHERE USERNAME =:userid
   
}
OUMUSERS_VALIDATE_USERID {
SELECT
instr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', substr(upper(:userid), 1, 1))
}

OUMUSERS_CASELOAD_DATA { 
select CASELOAD_ID ,STAFF_ID  from STAFF_ACCESSIBLE_CASELOADS where staff_id=(select staff_id from staff_members where USER_ID = :userId ) ORDER BY CREATE_DATETIME
}

 OUMUSERS_IMAGE_EXECUTEQUERY {
 SELECT * FROM IMAGES WHERE IMAGE_OBJECT_TYPE = 'STAFF' AND IMAGE_OBJECT_ID = :STAFF_ID AND ACTIVE_FLAG = 'Y'
}
OUMUSERS_TRIGGER_STAFFEXCEQUERY{
SELECT * FROM STAFF_MEMBERS WHERE STAFF_ID=:STAFF_ID
}
OUMUSERS_CASELOAD_ASSIGNED_COUNT_FOR_STAFF {
select count(*) from staff_members where staff_id=:staffId AND assigned_caseload_id=:caseloadId
}
OUMUSERS_RESET_PASSWORD{ 
update OMS_USERS_LIST set password =:password , modify_datetime = current_timestamp, modify_user_id =:modifyUserId where  USER_ID = :userId;
}

OUMUSERS_USER_DATA {
	SELECT USER FROM DUAL;
}

OUMUSERS_CASELOAD_WORKING_CASELOAD_COUNT_FOR_STAFF {
select count(*) from staff_members where staff_id=:staffId AND working_caseload_id=:caseloadId
}
