
OIMCTACT_FIND_RGRELATIONSHIPTYPE {
 	SELECT
  RF.CODE, RF.DESCRIPTION DESCRIPTION
FROM REFERENCE_CODES RF
WHERE
  DOMAIN = 'RELATIONSHIP' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  RF.LIST_SEQ, RF.DESCRIPTION

}

OIMCTACT_FIND_RGCONTACTTYPE {
 	SELECT
  RF.CODE, RF.DESCRIPTION DESCRIPTION
FROM REFERENCE_CODES RF
WHERE
  DOMAIN = 'CONTACTS' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  RF.LIST_SEQ, RF.DESCRIPTION

}

OIMCTACT_CONTACTPERSONTYPES_FIND_CONTACT_PERSON_TYPES {
 	SELECT CONTACT_TYPE,RELATIONSHIP_TYPE,LIST_SEQ,ACTIVE_FLAG,UPDATE_ALLOWED_FLAG,MODIFY_USER_ID,EXPIRY_DATE,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG from CONTACT_PERSON_TYPES 
}
OIMCTACT_CONTACTPERSONTYPES_INSERT_CONTACT_PERSON_TYPES {
  insert into CONTACT_PERSON_TYPES(CONTACT_TYPE, RELATIONSHIP_TYPE, LIST_SEQ, ACTIVE_FLAG, UPDATE_ALLOWED_FLAG, EXPIRY_DATE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG ) values(:contactType, :relationshipType, :listSeq, :activeFlag, :updateAllowedFlag, :expiryDate, CURRENT_TIMESTAMP , :createUserId, NULL , :sealFlag)
}

OIMCTACT_CONTACTPERSONTYPES_UPDATE_CONTACT_PERSON_TYPES {
 update CONTACT_PERSON_TYPES set CONTACT_TYPE = :contactType, RELATIONSHIP_TYPE = :relationshipType, 
 LIST_SEQ = :listSeq, ACTIVE_FLAG = :activeFlag, EXPIRY_DATE =:expiryDate,
 MODIFY_USER_ID = :modifyUserId, MODIFY_DATETIME = CURRENT_TIMESTAMP where CONTACT_TYPE = :contactType and RELATIONSHIP_TYPE = :relationshipType
} 

OIMCTACT_CONTACT_PERSON_TYPES_POSTQUERY_ {
	SELECT SM.LAST_NAME || ', ' || SM.FIRST_NAME
FROM STAFF_MEMBERS SM
WHERE
  SM.USER_ID = UPPER(:LV_USER_ID) 

}
