
OIMPRFCA_FIND_CGFKPFLTYPECODEVALUETYPE {
 	SELECT
  REF_CODE.CODE CODE_VALUE_TYPE , REF_CODE.DOMAIN DSP_DOMAIN,
  REF_CODE.DESCRIPTION DSP_DESCRIPTION, REF_CODE.LIST_SEQ DSP_LIST_SEQ,
  REF_CODE.ACTIVE_FLAG DSP_ACTIVE_FLAG, REF_CODE.EXPIRED_DATE DSP_EXPIRED_DATE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'VALUE_TYPE' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY REF_CODE.LIST_SEQ

}

OIMPRFCA_PFLCAT_FIND_PROFILE_CATEGORIES {
 	SELECT PROFILE_CATEGORY, DESCRIPTION, RECHECK_FLAG, LIST_SEQ, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, MODIFY_USER_ID, SEAL_FLAG FROM PROFILE_CATEGORIES
}
OIMPRFCA_PFLCAT_INSERT_PROFILE_CATEGORIES {
 insert into profile_categories ( profile_category, description, recheck_flag, list_seq, create_datetime, create_user_id, modify_datetime, seal_flag ) values (:profileCategory, :description, :recheckFlag, :listSeq, CURRENT_TIMESTAMP, :createUserId, NULL, :sealFlag) 
} 

OIMPRFCA_PFLCAT_UPDATE_PROFILE_CATEGORIES {
 update PROFILE_CATEGORIES set profile_category = :profileCategory, description = :description, recheck_flag = :recheckFlag, list_seq = :listSeq, modify_datetime = CURRENT_TIMESTAMP, modify_user_id = :modifyUserId, seal_flag = :sealFlag where PROFILE_CATEGORY = :profileCategory
} 

OIMPRFCA_PFLCAT_DELETE_PROFILE_CATEGORIES { 
	DELETE FROM PROFILE_CATEGORIES where PROFILE_CATEGORY = :profileCategory
} 

OIMPRFCA_PFLTYPE_FIND_PROFILE_TYPES {
 	SELECT
  PROFILE_TYPE, PROFILE_CATEGORY, DESCRIPTION, LIST_SEQ, MANDATORY_FLAG,
  UPDATED_ALLOWED_FLAG, CODE_VALUE_TYPE, ACTIVE_FLAG,
	EXPIRY_DATE, MODIFY_USER_ID, MODIFIED_DATE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG FROM PROFILE_TYPES where PROFILE_CATEGORY = :profileCategory ORDER BY LIST_SEQ, PROFILE_TYPE

}
OIMPRFCA_PFLTYPE_INSERT_PROFILE_TYPES {
 insert into PROFILE_TYPES ( PROFILE_TYPE, PROFILE_CATEGORY, DESCRIPTION, LIST_SEQ, MANDATORY_FLAG, UPDATED_ALLOWED_FLAG, CODE_VALUE_TYPE, ACTIVE_FLAG, EXPIRY_DATE, MODIFIED_DATE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG ) values (:profileType, :profileCategory, :description, :listSeq, :mandatoryFlag, :updatedAllowedFlag, :codeValueType, :activeFlag, :expiryDate, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, :createUserId, NULL, :sealFlag) 
} 

OIMPRFCA_PFLTYPE_UPDATE_PROFILE_TYPES {
 update PROFILE_TYPES set PROFILE_TYPE =:profileType, PROFILE_CATEGORY =:profileCategory, DESCRIPTION =:description, LIST_SEQ =:listSeq, MANDATORY_FLAG =:mandatoryFlag, UPDATED_ALLOWED_FLAG =:updatedAllowedFlag, CODE_VALUE_TYPE =:codeValueType, ACTIVE_FLAG =:activeFlag, EXPIRY_DATE =:expiryDate, 
 MODIFY_USER_ID = :modifyUserId, MODIFIED_DATE = CURRENT_TIMESTAMP, MODIFY_DATETIME = CURRENT_TIMESTAMP, SEAL_FLAG =:sealFlag where PROFILE_TYPE =:profileType
} 


OIMPRFCA_PFL_CAT_ONCHECKDELETEMASTER_ {
	SELECT 1 FROM PROFILE_TYPES P WHERE P.PROFILE_CATEGORY = :PROFILECATEGORY
}

OIMPRFCA_CGFKCHK_PFL_TYPE_PFL_TYPE_REF_ {
	SELECT REF_CODE.DOMAIN ,REF_CODE.DESCRIPTION ,REF_CODE.LIST_SEQ ,REF_CODE.ACTIVE_FLAG ,REF_CODE.EXPIRED_DATE FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :CODEVALUETYPE AND     DOMAIN = 'VALUE_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OIMPRFCA_CGWHEN_NEW_FORM_INSTANCE_ {
SELECT current_timestamp, 'OMS_OWNER' from dual d 
}
