
OIMPRFCO_PFLTYPE_FIND_PROFILE_TYPES {
 	SELECT PROFILE_TYPE ,PROFILE_CATEGORY ,DESCRIPTION ,LIST_SEQ ,MANDATORY_FLAG ,UPDATED_ALLOWED_FLAG ,CODE_VALUE_TYPE ,ACTIVE_FLAG ,EXPIRY_DATE ,MODIFY_USER_ID ,MODIFIED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,SEAL_FLAG   FROM PROFILE_TYPES WHERE CODE_VALUE_TYPE = 'CODE'
}
OIMPRFCO_PFLCODE_FIND_PROFILE_CODES {
 	SELECT PROFILE_TYPE ,PROFILE_CODE ,DESCRIPTION ,LIST_SEQ ,UPDATE_ALLOWED_FLAG ,ACTIVE_FLAG ,EXPIRY_DATE ,USER_ID ,MODIFIED_DATE ,CREATE_DATETIME ,CREATE_USER_ID ,MODIFY_DATETIME ,MODIFY_USER_ID ,SEAL_FLAG   FROM PROFILE_CODES WHERE PROFILE_TYPE = :profileType ORDER BY LIST_SEQ
}
OIMPRFCO_PFLCODE_INSERT_PROFILE_CODES {
insert into PROFILE_CODES(PROFILE_TYPE , PROFILE_CODE , DESCRIPTION , LIST_SEQ , UPDATE_ALLOWED_FLAG , ACTIVE_FLAG , EXPIRY_DATE , USER_ID , MODIFIED_DATE , CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME , SEAL_FLAG ) values(:profileType , :profileCode , :description , :listSeq , :updateAllowedFlag , :activeFlag , :expiryDate , :userId , :modifiedDate , CURRENT_TIMESTAMP , :createUserId , NULL , :sealFlag ) 
}

OIMPRFCO_PFLCODE_UPDATE_PROFILE_CODES {
 update PROFILE_CODES set PROFILE_TYPE = :profileType , PROFILE_CODE = :profileCode , DESCRIPTION = :description , LIST_SEQ = :listSeq , UPDATE_ALLOWED_FLAG = :updateAllowedFlag , ACTIVE_FLAG = :activeFlag , EXPIRY_DATE = :expiryDate , USER_ID = :userId , MODIFIED_DATE = :modifiedDate , MODIFY_DATETIME = CURRENT_TIMESTAMP , MODIFY_USER_ID = :modifyUserId , SEAL_FLAG = :sealFlag where PROFILE_TYPE = :profileType and PROFILE_CODE = :profileCode
}

OIMPRFCO_PFLCODE_DELETE_PROFILE_CODES { 
	DELETE FROM PROFILE_CODES where PROFILE_TYPE = :profileType AND PROFILE_CODE  = :profileCode
}


OIMPRFCO_CGUVCHK_PROFILE_CODES_PK_ {
	SELECT  '1' FROM    PROFILE_CODES WHERE   PROFILE_TYPE = P_PROFILE_TYPE AND     PROFILE_CODE = P_PROFILE_CODE
}

OIMPRFCO_CGWHEN_NEW_FORM_INSTANCE_ {
SELECT CURRENT_TIMESTAMP,:createUserId from dual
}

OIMPRFCO_CGRICHK_PROFILE_CODES {
	SELECT  count(*) FROM    OFFENDER_PROFILE_DETAILS OFF_PD WHERE   OFF_PD.PROFILE_CODE = :profileCode
}

OIMPRFCO_GET_USER_ID {
SELECT STAFF_ID
        FROM STAFF_MEMBERS
       WHERE USER_ID = upper(:createUserId)
}
