
OIISHLOG_FIND_CGFKAGYSHILAGYACTIVITYCOD {
 	SELECT REF_CODE.CODE  code    ,REF_CODE.DESCRIPTION  description FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'ACT_TYPE' AND ACTIVE_FLAG = 'Y'  AND EXPIRED_DATE IS NULL ORDER BY LIST_SEQ
}

OIISHLOG_FIND_RGAGENCY {
 	SELECT AL.AGY_LOC_ID code, AL.DESCRIPTION  DESCRIPTION  FROM AGENCY_LOCATIONS AL , CASELOAD_AGENCY_LOCATIONS CAL WHERE CAL.CASELOAD_ID = :CASELOADID AND AL.AGY_LOC_ID = CAL.AGY_LOC_ID AND AL.AGENCY_LOCATION_TYPE = 'INST' AND AL.AGY_LOC_ID NOT IN ('TRN' , 'OUT' ) AND ((:MODE = 'ENTER-QUERY' ) OR (:MODE != 'ENTER-QUERY' AND AL.ACTIVE_FLAG = 'Y' ) ) ORDER BY AL.LIST_SEQ , AL.DESCRIPTION
}

OIISHLOG_FIND_RGLOCATION {
 	SELECT  C.DESCRIPTION  , C.INTERNAL_LOCATION_CODE INTERNAL_LOCATION_CODE , C.INTERNAL_LOCATION_ID INTERNAL_LOCATION_ID  FROM INT_LOC_USAGE_LOCATIONS A , 	  INTERNAL_LOCATION_USAGES B , 	  AGENCY_INTERNAL_LOCATIONS C WHERE A.INTERNAL_LOCATION_USAGE_ID = B.INTERNAL_LOCATION_USAGE_ID    AND B.INTERNAL_LOCATION_USAGE='SHIFT'    AND B.AGY_LOC_ID = :AGENCYNAME    AND A.INTERNAL_LOCATION_ID = C.INTERNAL_LOCATION_ID    AND ((C.ACTIVE_FLAG = 'Y' AND C.DEACTIVATE_DATE IS NULL )         OR (:MODE = 'ENTER-QUERY' ) )  
}

OIISHLOG_FIND_RGSTAFF {
 	SELECT STAFF.LAST_NAME||', '||STAFF.FIRST_NAME description  ,  STAFF.STAFF_ID STAFF_ID  FROM STAFF_MEMBERS STAFF  WHERE STAFF_ID IN (SELECT STAFF_ID FROM STAFF_ACCESSIBLE_CASELOADS  WHERE CASELOAD_ID =  :CASELOADID )  AND STATUS = 'ACTIVE' ORDER BY STAFF.LAST_NAME , STAFF.FIRST_NAME
}

OIISHLOG_AGYSHIL_FIND_AGENCY_SHIFT_LOGS {
 	SELECT STAFF_ID ,SHIFT_LOG_SEQ ,LOG_DATE ,LOG_TIME ,AGY_ACTIVITY_CODE ,INTERNAL_LOCATION_ID2 ,INTERNAL_LOCATION_ID ,INTERNAL_LOCATION_ID3 ,MODIFY_USER_ID ,MODIFY_DATETIME ,LOCK_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG ,OBSERVATION_TEXT   FROM AGENCY_SHIFT_LOGS  
}
OIISHLOG_AGYSHIL_INSERT_AGENCY_SHIFT_LOGS {
insert into AGENCY_SHIFT_LOGS(STAFF_ID , SHIFT_LOG_SEQ , LOG_DATE , LOG_TIME , AGY_ACTIVITY_CODE , INTERNAL_LOCATION_ID2 , INTERNAL_LOCATION_ID , INTERNAL_LOCATION_ID3 , MODIFY_USER_ID , MODIFY_DATETIME , LOCK_FLAG , CREATE_DATETIME , CREATE_USER_ID , SEAL_FLAG , OBSERVATION_TEXT ) values(:staffId , :shiftLogSeq , :logDate , :logTime , :agyActivityCode , :internalLocationId2 , :internalLocationId , :internalLocationId3 , null , null , :lockFlag , :createDatetime , :createUserId , :sealFlag , :observationText )
}


OIISHLOG_CGFKCHK_AGY_SHIL_AGY_SHIL_AGY_ {
	SELECT  '1' FROM   AGENCY_SHIFT_LOGS WHERE  SHIFT_LOG_SEQ = :SHIFTLOGSEQ
}

OIISHLOG_CGFKCHK_AGY_SHIL_AGY_SHIL_REF_ {
	SELECT REF_CODE.DESCRIPTION FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :AGYACTIVITYCODE AND     DOMAIN = 'ACT_TYPE'
}


OIISHLOG_CGFKCHK_AGY_SHIL_AGY_SHIL_2c {
	SELECT AL.DESCRIPTION ,AGY_INTL.DESCRIPTION FROM   AGENCY_INTERNAL_LOCATIONS AGY_INTL, AGENCY_LOCATIONS AL WHERE  AGY_INTL.INTERNAL_LOCATION_ID = :AGY_SHIL.INTERNAL_LOCATION_ID AND  AL.AGY_LOC_ID = AGY_INTL.AGY_LOC_ID AND  AL.AGENCY_LOCATION_TYPE = 'INST' AND  AGY_INTL.AGY_LOC_ID IN (SELECT AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS WHERE CASELOAD_ID = :GLOBAL.CASELOAD_ID)
}

OIISHLOG_CGFKLKP_AGY_SHIL_AGY_SHIL_AGY_ {
	SELECT AGY_INTL.INTERNAL_LOCATION_ID FROM AGENCY_INTERNAL_LOCATIONS AGY_INTL WHERE (AGY_INTL.AGY_LOC_ID = :DSPAGYLOCID OR :DSPAGYLOCID IS NULL) AND (AGY_INTL.DESCRIPTION = :DSPDESCRIPTION2 OR :DSPDESCRIPTION2 IS NULL) AND AGY_INTL.ACTIVE_FLAG = 'Y' AND AGY_INTL.INTERNAL_LOCATION_TYPE = 'INST' AND AGY_INTL.PARENT_INTERNAL_LOCATION_ID IS NULL AND EXISTS ( SELECT CA.AGY_LOC_ID FROM CASELOAD_AGENCY_LOCATIONS CA WHERE CA.CASELOAD_ID = :CASELOADID AND CA.AGY_LOC_ID = AGY_INTL.AGY_LOC_ID)
}

OIISHLOG_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}

