
OCUALERT_ALERT_FIND_OFFENDER_ALERTS {
 	SELECT ALERT_DATE ,OFFENDER_BOOK_ID ,ROOT_OFFENDER_ID ,ALERT_SEQ ,ALERT_TYPE ,ALERT_CODE ,AUTHORIZE_PERSON_TEXT ,CREATE_DATE ,ALERT_STATUS ,VERIFIED_FLAG ,EXPIRY_DATE ,COMMENT_TEXT ,CASELOAD_ID ,MODIFY_USER_ID ,MODIFY_DATETIME ,CASELOAD_TYPE ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG
 	FROM OFFENDER_ALERTS   where  OFFENDER_BOOK_ID = :OFFENDER_BOOK_ID  ORDER BY ALERT_STATUS ASC,CREATE_DATETIME DESC
}
OCUALERT_FIND_REFERENCE_CODES {
    SELECT DESCRIPTION, CODE, PARENT_CODE, 
    	PARENT_DOMAIN, DOMAIN, LIST_SEQ 
	    FROM REFERENCE_CODES
	   WHERE  DOMAIN = :DOMAIN AND CODE = :CODE
    }
OCUALERT_FIND_REFERENCE_DESCRIPTION {    
     SELECT DESCRIPTION, CODE FROM REFERENCE_CODES WHERE ACTIVE_FLAG = 'Y' AND DOMAIN = :DOMAIN
	}