  
	OCUCOFFE_FIND_RGALIASNAMETYPE {
 SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'NAME_TYPE' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCUCOFFE_FIND_RGIDENTIFIERTYPE {
SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'ID_TYPE' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCUCOFFE_FIND_RGOFFSUFFIX {
 SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'SUFFIX' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCUCOFFE_FIND_RGOFFSEX {
 SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'SEX' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCUCOFFE_FIND_RGOFFRACE {
 SELECT
  REF_CODE.DESCRIPTION, REF_CODE.CODE
FROM REFERENCE_CODES REF_CODE
WHERE
  DOMAIN = 'ETHNICITY' AND
  ACTIVE_FLAG = 'Y' AND
  EXPIRED_DATE IS NULL
ORDER BY
  REF_CODE.LIST_SEQ, REF_CODE.CODE

}
	OCUCOFFE_FIND_RGIDSOURCE {
 SELECT REF_CODE.DESCRIPTION         ,REF_CODE.CODE   FROM REFERENCE_CODES REF_CODE  WHERE DOMAIN = 'ID_SOURCE'    AND ACTIVE_FLAG = 'Y'    AND EXPIRED_DATE IS NULL  ORDER BY REF_CODE.LIST_SEQ , REF_CODE.CODE
}
OCUCOFFE_OFF_FIND_OFFENDERS {
 select
	OFFENDER_ID ,
	OFFENDER_NAME_SEQ ,
	ID_SOURCE_CODE ,
	LAST_NAME ,
	NAME_TYPE ,
	FIRST_NAME ,
	MIDDLE_NAME ,
	BIRTH_DATE ,
	SEX_CODE ,
	SUFFIX ,
	LAST_NAME_SOUNDEX ,
	BIRTH_PLACE ,
	BIRTH_COUNTRY_CODE ,
	CREATE_DATE ,
	LAST_NAME_KEY ,
	ALIAS_OFFENDER_ID ,
	FIRST_NAME_KEY ,
	MIDDLE_NAME_KEY ,
	OFFENDER_ID_DISPLAY ,
	ROOT_OFFENDER_ID ,
	CASELOAD_TYPE ,
	MODIFY_USER_ID ,
	MODIFY_DATETIME ,
	ALIAS_NAME_TYPE ,
	PARENT_OFFENDER_ID ,
	UNIQUE_OBLIGATION_FLAG ,
	SUSPENDED_FLAG ,
	SUSPENDED_DATE ,
	RACE_CODE ,
	REMARK_CODE ,
	ADD_INFO_CODE ,
	BIRTH_COUNTY ,
	BIRTH_STATE ,
	MIDDLE_NAME_2 ,
	TITLE ,
	AGE ,
	CREATE_USER_ID ,
	LAST_NAME_ALPHA_KEY ,
	CREATE_DATETIME ,
	NAME_SEQUENCE ,
	SEAL_FLAG
from
	OFFENDERS 
}

OCUCOFFE_OFF_INSERT_OFFENDERS {
insert into OFFENDERS(OFFENDER_ID , OFFENDER_NAME_SEQ , ID_SOURCE_CODE , LAST_NAME , NAME_TYPE , FIRST_NAME , MIDDLE_NAME , BIRTH_DATE , SEX_CODE , SUFFIX , LAST_NAME_SOUNDEX , BIRTH_PLACE , BIRTH_COUNTRY_CODE , CREATE_DATE , LAST_NAME_KEY , ALIAS_OFFENDER_ID , FIRST_NAME_KEY , MIDDLE_NAME_KEY , OFFENDER_ID_DISPLAY , ROOT_OFFENDER_ID , CASELOAD_TYPE , MODIFY_DATETIME , ALIAS_NAME_TYPE , PARENT_OFFENDER_ID , UNIQUE_OBLIGATION_FLAG , SUSPENDED_FLAG , SUSPENDED_DATE , RACE_CODE , REMARK_CODE , ADD_INFO_CODE , BIRTH_COUNTY , BIRTH_STATE , MIDDLE_NAME_2 , TITLE , AGE , CREATE_USER_ID , LAST_NAME_ALPHA_KEY , CREATE_DATETIME , NAME_SEQUENCE , SEAL_FLAG, GENDER_CODE , SECOND_MIDDLE_NAME ) values(:offenderId , :offenderNameSeq , :idSourceCode , :lastName , :nameType , :firstName , :middleName , :birthDate , :sexCode , :suffix , :lastNameSoundex , :birthPlace , :birthCountryCode , :createDate , :lastNameKey , :aliasOffenderId , :firstNameKey , :middleNameKey , :offenderIdDisplay , :rootOffenderId , :caseloadType , NULL , :aliasNameType , :parentOffenderId , :uniqueObligationFlag , :suspendedFlag , :suspendedDate , :raceCode , :remarkCode , :addInfoCode , :birthCounty , :birthState , :middleName2 , :title , :age , :createUserId , :lastNameAlphaKey , current_timestamp , :nameSequence , :sealFlag, :genderCode, :secondMiddleName ) 
}

OCUCOFFE_ALIAS_FIND_OFFENDERS {
 SELECT OFFENDER_ID ,OFFENDER_NAME_SEQ ,ID_SOURCE_CODE ,LAST_NAME ,NAME_TYPE ,FIRST_NAME ,MIDDLE_NAME ,BIRTH_DATE ,SEX_CODE ,SUFFIX ,LAST_NAME_SOUNDEX ,BIRTH_PLACE ,BIRTH_COUNTRY_CODE ,CREATE_DATE ,LAST_NAME_KEY ,ALIAS_OFFENDER_ID ,FIRST_NAME_KEY ,MIDDLE_NAME_KEY ,OFFENDER_ID_DISPLAY ,ROOT_OFFENDER_ID ,CASELOAD_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,ALIAS_NAME_TYPE ,PARENT_OFFENDER_ID ,UNIQUE_OBLIGATION_FLAG ,SUSPENDED_FLAG ,SUSPENDED_DATE ,RACE_CODE ,REMARK_CODE ,ADD_INFO_CODE ,BIRTH_COUNTY ,BIRTH_STATE ,MIDDLE_NAME_2 ,TITLE ,AGE ,CREATE_USER_ID ,LAST_NAME_ALPHA_KEY ,CREATE_DATETIME ,NAME_SEQUENCE ,SEAL_FLAG ,GENDER_CODE , SECOND_MIDDLE_NAME , (select description from reference_codes rc  where "domain" = 'SEX' and code =OFFENDERS.sex_code) as SEXCODEDESC  FROM OFFENDERS
}


OCUCOFFE_OFF_INSERT_OFFENDERS_EXTERNAL_SEARCH {
insert into OFFENDERS_EXTERNAL_SEARCH(EXTERNAL_ID, OFFENDER_ID , LAST_NAME , FIRST_NAME , MIDDLE_NAME , BIRTH_DATE , SEX_CODE , BIRTH_PLACE, BIRTH_COUNTRY_CODE , CREATE_DATE, REQUEST_STATUS , CREATE_DATETIME , CREATE_USER_ID , GENDER_CODE, SECOND_MIDDLE_NAME,modify_datetime) values(:externalId, :offenderId , :lastName , :firstName , :middleName , :birthDate , :sexCode, :birthPlace , :birthCountryCode , :createDate, :requestStatus , current_timestamp , :createUserId , :genderCode, :secondMiddleName,null) 
}
OCUCOFFE_OFF_INSERT_OFFENDERS_EXTERNAL_SEARCH_ID {
	SELECT nextval('EXTERNAL_SEARCH_SEQUENCE') FROM DUAL
}


OCUCOFFE_OFFID_FIND_OFFENDER_IDENTIFIERS {
 SELECT OFFENDER_ID ,OFFENDER_ID_SEQ ,IDENTIFIER_TYPE ,IDENTIFIER ,ISSUED_AUTHORITY_TEXT ,ISSUED_DATE ,ROOT_OFFENDER_ID ,CASELOAD_TYPE ,MODIFY_USER_ID ,MODIFY_DATETIME ,VERIFIED_FLAG ,CREATE_DATETIME ,CREATE_USER_ID ,SEAL_FLAG   FROM OFFENDER_IDENTIFIERS  
}
OCUCOFFE_OFFID_INSERT_OFFENDER_IDENTIFIERS {
insert
	into
	OFFENDER_IDENTIFIERS(OFFENDER_ID ,
	OFFENDER_ID_SEQ ,
	IDENTIFIER_TYPE ,
	IDENTIFIER ,
	ISSUED_AUTHORITY_TEXT ,
	ISSUED_DATE ,
	ROOT_OFFENDER_ID ,
	CASELOAD_TYPE ,
	VERIFIED_FLAG ,
	CREATE_DATETIME ,
	CREATE_USER_ID ,
	SEAL_FLAG ,modify_datetime)
values(:offenderId ,
:offenderIdSeq ,
:identifierType ,
trim(:identifier) ,
:issuedAuthorityText ,
:issuedDate ,
:rootOffenderId ,
:caseloadType ,
:verifiedFlag ,
current_timestamp ,
:createUserId ,
:sealFlag,null )
}  

OCUCOFFE_OFFID_UPDATE_OFFENDER_IDENTIFIERS {
UPDATE OFFENDER_IDENTIFIERS set IDENTIFIER_TYPE = :identifierType , IDENTIFIER = :identifier , ISSUED_AUTHORITY_TEXT = :issuedAuthorityText , ISSUED_DATE = :issuedDate , ROOT_OFFENDER_ID = :rootOffenderId , CASELOAD_TYPE = :caseloadType , MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = current_timestamp , VERIFIED_FLAG = :verifiedFlag , SEAL_FLAG = :sealFlag where OFFENDER_ID = :offenderId and OFFENDER_ID_SEQ = :offenderIdSeq
} 
--
--
	OCUCOFFE_OFF_ONCHECKDELETEMASTER_OFF_ID_ALL_CUR {
 SELECT 1 FROM OFFENDER_IDENTIFIERS O WHERE O.ROOT_OFFENDER_ID = :ROOTOFFENDERID
}

	OCUCOFFE_OFF_ONCHECKDELETEMASTER_ALIAS_CUR {
 SELECT 1 FROM OFFENDERS O WHERE O.ROOT_OFFENDER_ID = :ROOTOFFENDERID
}

	OCUCOFFE_ALIAS_ONCHECKDELETEMASTER_OFF_ID_CUR {
 SELECT 1 FROM OFFENDER_IDENTIFIERS O WHERE O.OFFENDER_ID = :OFFENDERID
}

	OCUCOFFE_OCUCOFFE_WHENNEWRECORDINSTANCE_DEFAULT_SEQ_CUR {
 SELECT DESCRIPTION, CODE FROM REFERENCE_CODES WHERE DOMAIN = 'ID_SOURCE' AND LIST_SEQ = 1 -- @@@ VIKAS GROVER, 03/DEC/08 - ISSUE#4359 - ID SOURCE FIELD SHOULD NOT DEFAULT TO FIRST SEQ IF IT'S INACTIVE AND ACTIVE_FLAG = 'Y'
}

	OCUCOFFE_OCUCOFFE_WHENNEWFORMINSTANCE {
 SELECT  cast(USERENV_number('SESSIONID') as text) FROM  DUAL
}

	OCUCOFFE_OCUCOFFE_POSTQUERY_REFERENCE_CODES_C {
 SELECT DESCRIPTION FROM REFERENCE_CODES WHERE DOMAIN = :P_DOMAIN AND CODE = :P_CODE
}

	OCUCOFFE_OCUCOFFE_POSTINSERT_GET_ROOT_OFFENDER_ID_C {
 SELECT ROOT_OFFENDER_ID FROM OFFENDERS WHERE OFFENDER_ID = :OFFENDERID
}

OCUCOFFE_OCUCOFFE_PREINSERT_GET_NEXT_ALIAS_C {          
 SELECT nextval('OFFENDER_ID') FROM DUAL
}

EXTERNAL_SEARCH_PREINSERT_GET_NEXT {          
 SELECT NEXTVAL('EXTERNAL_SEARCH_SEQUENCE') FROM DUAL
}


	OCUCOFFE_OCUCOFFE_PREINSERT_GET_NEXT_IDENTIFIER_C {
 SELECT coalesce(MAX(OFFENDER_ID_SEQ::int),0) + 1 FROM OFFENDER_IDENTIFIERS WHERE OFFENDER_ID = :OFFENDERID
}

	OCUCOFFE_OCUCOFFE_PREINSERT_RECORD_EX {
select
	'X'
from
	OFFENDER_IDENTIFIERS
where
	ROOT_OFFENDER_ID = :LV_ROOT_OFFENDER_ID
	and IDENTIFIER_TYPE = :LV_IDENTIFIER_TYPE
	and IDENTIFIER = :LV_IDENTIFIER
}

OCUCOFFE_CREATE_FORM_GLOBALS{
SELECT DESCRIPTION  FROM OMS_MODULES WHERE MODULE_NAME = :MODULE_NAME
}

	OCUCOFFE_AGE_VALIDATION_VS_RANGECUR {
 SELECT PROFILE_VALUE ,PROFILE_VALUE_2 FROM SYSTEM_PROFILES WHERE PROFILE_TYPE = 'CLIENT' AND PROFILE_CODE = 'AGE_RANGE'
}

	OCUCOFFE_AGE_VALIDATION_VS_AGECUR {                          
SELECT TAG_HEADER_GET_AGE(date_trunc('day', :BIRTHDATE::timestamp)) AGE from dual

}

	OCUCOFFE_VALIDATE_ALIASES_CHECK_FOR_DUP_OFF_CUR {
	 select
	COUNT(*)
from
	OFFENDERS
where
	LAST_NAME = :lastName
	and ( FIRST_NAME = :firstName
	or ( coalesce(:firstName::text, '') = ''
	and coalesce(FIRST_NAME::text, '') = ''))
	and ( MIDDLE_NAME = :middleName
	or ( coalesce(:middleName::text, '') = ''
	and coalesce(MIDDLE_NAME::text, '') = ''))
	and ( SUFFIX = :suffix
	or ( coalesce(:suffix::text, '') = ''
	and coalesce(SUFFIX::text, '') = ''))
	and ( BIRTH_DATE = :birthDate
	or (coalesce(:birthDate::text, '') = ''
	and coalesce(BIRTH_DATE::text, '') = ''))
	and ( ALIAS_NAME_TYPE = :aliasNameType
	or ( coalesce(ALIAS_NAME_TYPE::text, '') = ''
	and coalesce(:aliasNameType::text, '') = ''))
	and OFFENDER_ID <> coalesce(:offenderId , 00000)

}

	OCUCOFFE_VALIDATE_ALIASES_CHECK_DUP_NAME_CUR {
	 SELECT OMS_SEARCH_check_offender(:lastName,:birthdate::date) CNT FROM dual
}   
  
         OCUCOFFE_CHECK_PNC_EXISTS {
  SELECT OMS_SEARCH_GET_OFFENDER_ID() FROM  dual
 }

	OCUCOFFE_CHECK_PNC_EXISTS_GET_PNC_EXC {
 SELECT COUNT (*) FROM OFFENDER_IDENTIFIERS OFF_IND WHERE OFF_IND.IDENTIFIER_TYPE = 'PNC' AND OFF_IND.IDENTIFIER = :P_IDENTIFIER AND OFF_IND.ROOT_OFFENDER_ID = :P_ROOT_OFF_ID
}

OCUCOFFE_GET_OFFENDER_MIN_AGE {
SELECT YOUNG_OFFENDER_AGE FROM CASELOAD_ADM_OTHER_PROFILES WHERE CASELOAD_ID = :CASELOADID
}

OCUCOFFE_CHECK_OFFENDER_ID_DISPLAY {
	select
	OMS_SEARCH_CHECK_OFFENDER_ID_DISPLAY (:offenderIdDisplay)
from
	DUAL
}
OCUCOFFE_GET_CURRENT_DATE {
	SELECT SYSDATE() FROM DUAL
}

OCUCOFFE_CHECK_PNC_VALIDATION {
SELECT CASE WHEN PNC_VALIDATION(:IDENTIFIER) THEN 'TRUE' ELSE 'FALSE' END as VALID FROM DUAL

} 

OCUCOFFE_CHECK_PNC_EXISTS_GET_PNC_EX {
 SELECT COUNT (*) FROM OFFENDER_IDENTIFIERS OFF_IND WHERE OFF_IND.IDENTIFIER_TYPE = 'PNC' AND OFF_IND.IDENTIFIER = :IDENTIFIER AND OFF_IND.ROOT_OFFENDER_ID = :ROOTOFFID
}

OCUCOFFE_GET_ID_DISPLAY_PROFILE_VALUES {
SELECT PROFILE_VALUE FROM SYSTEM_PROFILES WHERE PROFILE_CODE = 'ID_DISPLAY' AND PROFILE_TYPE = 'CLIENT'

}

