
OTMCSLIM_FIND_CGFKCSLDLIMCASELOADID {
 	SELECT CSLD.CASELOAD_ID  CASELOAD_ID    ,CSLD.DESCRIPTION DESCRIPTION    FROM   CASELOADS CSLD 
ORDER BY  CSLD.LIST_SEQ  ,CSLD.DESCRIPTION
}

OTMCSLIM_FIND_CGFKCSLDLIMLIMITTYPE {
 	SELECT REF_CODE1.CODE  LIMIT_TYPE  /* CG$FK */        ,REF_CODE1.DESCRIPTION  DSP_DESCRIPTION3        ,REF_CODE1.LIST_SEQ  DSP_LIST_SEQ3 FROM   REFERENCE_CODES REF_CODE1 WHERE   DOMAIN = 'LIMIT_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE1.LIST_SEQ        ,REF_CODE1.DESCRIPTION
}

OTMCSLIM_FIND_CGFKCSLDLIMPERIODTYPE {
 	SELECT REF_CODE2.CODE  PERIOD_TYPE  /* CG$FK */        ,REF_CODE2.DESCRIPTION  DSP_DESCRIPTION2        ,REF_CODE2.LIST_SEQ  DSP_LIST_SEQ2 FROM   REFERENCE_CODES REF_CODE2 WHERE   DOMAIN = 'PERIOD_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL ORDER BY  REF_CODE2.LIST_SEQ        ,REF_CODE2.DESCRIPTION
}

OTMCSLIM_CSLDLIM_FIND_CASELOAD_LIMITS {
 	SELECT  * FROM CASELOAD_LIMITS   
 	}
OTMCSLIM_CSLDLIM_INSERT_CASELOAD_LIMITS {
	INSERT INTO CASELOAD_LIMITS(CASELOAD_ID,LIMIT_TYPE,PERIOD_TYPE,LIMIT_AMOUNT,MODIFY_USER_ID,MODIFY_DATE,LIST_SEQ,CREATE_DATETIME,CREATE_USER_ID,MODIFY_DATETIME,SEAL_FLAG )
	VALUES(:caseloadId,:limitType,:periodType,:limitAmount,:modifyUserId,:modifyDate,:listSeq,:createDatetime,:createUserId,:modifyDatetime,:sealFlag)
}

OTMCSLIM_CSLDLIM_UPDATE_CASELOAD_LIMITS {
	UPDATE CASELOAD_LIMITS set LIMIT_AMOUNT =:limitAmount where CASELOAD_ID	=:caseloadId AND LIMIT_TYPE=:limitType
}

OTMCSLIM_CSLDLIM_DELETE_CASELOAD_LIMITS { 
	DELETE FROM CASELOAD_LIMITS where CASELOAD_ID	=:caseloadId AND LIMIT_TYPE=:limitType
}


OTMCSLIM_CGFKCHK_CSLD_LIM_CSLD_LIM_CSL_ {
	SELECT CSLD.DESCRIPTION ,CSLD.LIST_SEQ FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID
}

OTMCSLIM_CGFKCHK_CSLD_LIM_CSLD_LIM_PER_ {
	SELECT REF_CODE2.DESCRIPTION ,REF_CODE2.LIST_SEQ FROM   REFERENCE_CODES REF_CODE2 WHERE  REF_CODE2.CODE = :PERIODTYPE AND     DOMAIN = 'PERIOD_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OTMCSLIM_CGFKCHK_CSLD_LIM_CSLD_LIM_TYP_ {
	SELECT REF_CODE1.DESCRIPTION ,REF_CODE1.LIST_SEQ FROM   REFERENCE_CODES REF_CODE1 WHERE  REF_CODE1.CODE = :LIMITTYPE AND     DOMAIN = 'LIMIT_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OTMCSLIM_GETCASELOADIDDESC {
SELECT CSLD.DESCRIPTION   
      FROM   CASELOADS CSLD
      WHERE  CSLD.CASELOAD_ID = :caseloadId
      }