
OTMFREEZ_FIND_CGFKFREDISTXNTYPE {
 	SELECT TXN_TYPE.TXN_TYPE TXN_TYPE   ,TXN_TYPE.DESCRIPTION    FROM TRANSACTION_TYPES TXN_TYPE WHERE TXN_TYPE.TXN_USAGE IN ('D' ,'C' ) AND TXN_TYPE.CASELOAD_TYPE = :caseloadType
}

OTMFREEZ_FIND_CGFKFREDISACCOUNTCODE {
 	SELECT AC_CODE.ACCOUNT_CODE  ACCOUNT_CODE        ,AC_CODE.SUB_ACCOUNT_TYPE  SUB_ACCOUNT_TYPE        ,AC_CODE.ACCOUNT_NAME  ACCOUNT_NAME     FROM   ACCOUNT_CODES AC_CODE WHERE   AC_CODE.SUB_ACCOUNT_TYPE IS NOT NULL AND AC_CODE.CASELOAD_TYPE = :caseloadType
}

OTMFREEZ_FREDIS_FIND_FREEZE_DISBURSEMENTS {
 	SELECT  * FROM FREEZE_DISBURSEMENTS  WHERE 
}
OTMFREEZ_FREDIS_INSERT_FREEZE_DISBURSEMENTS {	
insert into FREEZE_DISBURSEMENTS(CASELOAD_TYPE, ACCOUNT_CODE, TXN_TYPE, FREEZE_FLAG, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG) values(:caseloadType, :accountCode, :txnType, :freezeFlag, current_timestamp, :createUserId, current_timestamp, :sealFlag) 
}

OTMFREEZ_FREDIS_UPDATE_FREEZE_DISBURSEMENTS {
UPDATE FREEZE_DISBURSEMENTS SET FREEZE_FLAG=:freezeFlag,MODIFY_USER_ID=:modifyUserId,MODIFY_DATETIME=current_timestamp  WHERE  ACCOUNT_CODE=:accountCode  and TXN_TYPE=:txnType
} 

OTMFREEZ_FREDIS_DELETE_FREEZE_DISBURSEMENTS { 
	DELETE FROM FREEZE_DISBURSEMENTS where ACCOUNT_CODE=:accountCode  and TXN_TYPE=:txnType 
}


OTMFREEZ_CGFKCHK_FRE_DIS_FRE_DIS_TXN_T {
 SELECT TXN_TYPE.DESCRIPTION ,TXN_TYPE.ACTIVE_FLAG ,TXN_TYPE.TXN_USAGE ,TXN_TYPE.EXPIRY_DATE ,TXN_TYPE.ALL_CASELOAD_FLAG ,TXN_TYPE.LIST_SEQ ,TXN_TYPE.UPDATE_ALLOWED_FLAG ,TXN_TYPE.MODIFY_USER_ID ,TXN_TYPE.MANUAL_INVOICE_FLAG ,TXN_TYPE.MODIFY_DATE ,TXN_TYPE.CREDIT_OBLIGATION_TYPE ,TXN_TYPE.GROSS_NET_FLAG ,TXN_TYPE.CASELOAD_TYPE FROM TRANSACTION_TYPES TXN_TYPE WHERE TXN_TYPE.TXN_TYPE = :TXNTYPE AND TXN_TYPE.TXN_USAGE IN ('D','C') AND TXN_TYPE.CASELOAD_TYPE = :CASELOADTYPE
}

OTMFREEZ_CGFKCHK_FRE_DIS_FRE_DIS_ACT_C{
 SELECT AC_CODE.SUB_ACCOUNT_TYPE ,AC_CODE.ACCOUNT_NAME FROM ACCOUNT_CODES AC_CODE WHERE AC_CODE.ACCOUNT_CODE = :ACCOUNTCODE AND AC_CODE.SUB_ACCOUNT_TYPE IS NOT NULL AND AC_CODE.CASELOAD_TYPE = :CASELOADTYPE
}

OTMFREEZ_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
OTMFREEZ_CGFKCHK_FRE_DIS_FRE_DIS_TXN_DESCRIPTION {
SELECT TXN_TYPE.DESCRIPTION FROM TRANSACTION_TYPES TXN_TYPE WHERE TXN_TYPE.TXN_TYPE = :txnType AND TXN_TYPE.TXN_USAGE IN ('D','C') AND TXN_TYPE.CASELOAD_TYPE = :caseloadType
}
OTMFREEZ_CGFKCHK_FRE_DIS_FRE_DIS_TXN_USAGE {
SELECT TXN_TYPE.TXN_USAGE FROM TRANSACTION_TYPES TXN_TYPE WHERE TXN_TYPE.TXN_TYPE = :txnType AND TXN_TYPE.TXN_USAGE IN ('D','C') AND TXN_TYPE.CASELOAD_TYPE = :caseloadType
}
OTMFREEZ_GET_TXN_USAGE {
SELECT TXN_USAGE FROM TRANSACTION_TYPES WHERE TXN_TYPE=:txnType 
 }
OTMFREEZ_GET_TXN_CODE {
SELECT TXN_TYPE FROM TRANSACTION_TYPES WHERE DESCRIPTION=:description and CASELOAD_TYPE=:caseloadType
}
