
OTMMBALA_FIND_CGFKOFFSUBATRUSTACCOUNTCO {
 	SELECT AC_CODE.ACCOUNT_CODE  ACCOUNT_CODE  /* CG$FK */        ,AC_CODE.SUB_ACCOUNT_TYPE          ,AC_CODE.ACCOUNT_NAME  DESCRIPTION FROM   ACCOUNT_CODES AC_CODE WHERE   SUB_ACCOUNT_TYPE IS NOT NULL ORDER BY  AC_CODE.ACCOUNT_CODE        ,AC_CODE.SUB_ACCOUNT_TYPE
}

OTMMBALA_OFFSUBA_FIND_OFFENDER_SUB_ACCOUNTS {
 	SELECT CASELOAD_ID, OFFENDER_ID, TRUST_ACCOUNT_CODE, BALANCE, MINIMUM_BALANCE, HOLD_BALANCE, LAST_TXN_ID, MODIFY_DATE, MODIFY_USER_ID, LIST_SEQ, IND_DATE, IND_DAYS, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG  FROM OFFENDER_SUB_ACCOUNTS WHERE OFFENDER_ID = :OFFENDERID AND CASELOAD_ID = :CASELOADID ORDER BY TRUST_ACCOUNT_CODE
}
OTMMBALA_OFFSUBA_UPDATE_OFFENDER_SUB_ACCOUNTS {
--	UPDATE OFFENDER_SUB_ACCOUNTS set CASELOAD_ID=:caseloadId, OFFENDER_ID=:offenderId, TRUST_ACCOUNT_CODE=:trustAccountCode, BALANCE=:balance, MINIMUM_BALANCE=:minimumBalance, HOLD_BALANCE=:holdBalance, LAST_TXN_ID=:lastTxnId, MODIFY_DATE=:modifyDate, MODIFY_USER_ID=:modifyUserId, LIST_SEQ=:listSeq, IND_DATE=:indDate, IND_DAYS=:indDays, CREATE_DATETIME=:createDatetime, CREATE_USER_ID=:createUserId, MODIFY_DATETIME=:modifyDatetime, SEAL_FLAG=:sealFlag WHERE CASELOAD_ID=:caseloadId AND OFFENDER_ID=:offenderId AND TRUST_ACCOUNT_CODE=:trustAccountCode
    update OFFENDER_SUB_ACCOUNTS set CASELOAD_ID =:caseloadId, OFFENDER_ID =:offenderId, TRUST_ACCOUNT_CODE =:trustAccountCode, BALANCE =:balance, MINIMUM_BALANCE =:minimumBalance, HOLD_BALANCE =:holdBalance, LAST_TXN_ID =:lastTxnId, MODIFY_DATE =CURRENT_TIMESTAMP, MODIFY_USER_ID =:modifyUserId, LIST_SEQ =:listSeq, IND_DATE =:indDate, IND_DAYS =:indDays, MODIFY_DATETIME = CURRENT_TIMESTAMP, SEAL_FLAG =:sealFlag where CASELOAD_ID =:caseloadId and OFFENDER_ID =:offenderId and TRUST_ACCOUNT_CODE =:trustAccountCode
}

OTMMBALA_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT  FROM SYSTEM_PROFILES  /* where  */
}

OTMMBALA_CGFKCHK_OFF_SUBA_OFF_SUBA_AC__ {
	SELECT AC_CODE.SUB_ACCOUNT_TYPE ,AC_CODE.ACCOUNT_NAME FROM   ACCOUNT_CODES AC_CODE WHERE  AC_CODE.ACCOUNT_CODE = :TRUSTACCOUNTCODE AND     SUB_ACCOUNT_TYPE IS NOT NULL
}

OTMMBALA_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
