
OTMOFLIM_FIND_CGFKOFFLIMLIMITTYPE {
 	SELECT REF_CODE.CODE  CODE  /* CG$FK */        ,REF_CODE.DESCRIPTION DESCRIPTION  FROM   REFERENCE_CODES REF_CODE WHERE   DOMAIN = 'LIMIT_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
 ORDER BY  REF_CODE.LIST_SEQ,REF_CODE.DESCRIPTION
}

OTMOFLIM_OFFLIM_FIND_OFFENDER_LIMITS {
 	SELECT CASELOAD_ID, OFFENDER_ID, LIMIT_TYPE, LIMIT_AMOUNT, MODIFY_USER_ID, MODIFY_DATE, LIST_SEQ, PERIOD_TYPE, CREATE_DATETIME, CREATE_USER_ID, MODIFY_DATETIME, SEAL_FLAG FROM OFFENDER_LIMITS WHERE CASELOAD_ID = :CASELOADID AND OFFENDER_ID = :OFFENDERID
}
OTMOFLIM_OFFLIM_INSERT_OFFENDER_LIMITS {
	INSERT INTO OFFENDER_LIMITS(CASELOAD_ID,OFFENDER_ID,LIMIT_TYPE,LIMIT_AMOUNT,MODIFY_DATE, LIST_SEQ,PERIOD_TYPE,CREATE_DATETIME, CREATE_USER_ID,MODIFY_DATETIME, SEAL_FLAG)
	VALUES(:caseloadId,:offenderId,:limitType,:limitAmount,:modifyDate,:listSeq,:periodType,current_timestamp,:createUserId,current_timestamp,:sealFlag)
}

OTMOFLIM_OFFLIM_UPDATE_OFFENDER_LIMITS {
	UPDATE OFFENDER_LIMITS set LIMIT_AMOUNT =:limitAmount ,modify_datetime = current_timestamp ,modify_user_id =:modifyUserId  where CASELOAD_ID =:caseloadId and OFFENDER_ID=:offenderId and LIMIT_TYPE=:limitType
}

OTMOFLIM_OFFLIM_DELETE_OFFENDER_LIMITS { 
	DELETE FROM OFFENDER_LIMITS  where CASELOAD_ID =:caseloadId and OFFENDER_ID=:offenderId and LIMIT_TYPE=:limitType
}

OTMOFLIM_SYSPFL_FIND_SYSTEM_PROFILES {
 	SELECT *  FROM SYSTEM_PROFILES  /* where  */
}

OTMOFLIM_CGFKCHK_OFF_LIM_OFF_LIM_TYPE__ {
	SELECT REF_CODE.DESCRIPTION ,REF_CODE.LIST_SEQ FROM   REFERENCE_CODES REF_CODE WHERE  REF_CODE.CODE = :LIMITTYPE AND     DOMAIN = 'LIMIT_TYPE' AND ACTIVE_FLAG = 'Y' AND EXPIRED_DATE IS NULL
}

OTMOFLIM_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
