GET_EXT_LOCATION{
SELECT EXT1.TO_AGY_LOC_ID, EXT1.TO_ADDRESS_ID, EXT1.TO_CITY, EXT1.TO_COUNTRY_CODE FROM OFFENDER_EXTERNAL_MOVEMENTS EXT1 WHERE EXT1.OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID AND EXT1.MOVEMENT_SEQ = ( SELECT MAX(EXT2.MOVEMENT_SEQ) FROM OFFENDER_EXTERNAL_MOVEMENTS EXT2 WHERE EXT2.OFFENDER_BOOK_ID = EXT1.OFFENDER_BOOK_ID ) LIMIT 1

}
