GET_DEFAULTS_CUR{
 SELECT agy_loc_id, living_unit_id FROM caseload_adm_other_profiles WHERE caseload_id = :p_caseload_id
}

GET_LV_CAPACITY{
 SELECT capacity FROM living_units WHERE living_unit_id = :p_living_unit_id
}   

GET_ADMISSION_TYPE_CUR{
 SELECT OEM.MOVEMENT_TYPE, OEM.MOVEMENT_REASON_CODE
        FROM OFFENDER_EXTERNAL_MOVEMENTS OEM
       WHERE OEM.OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID
         AND OEM.MOVEMENT_SEQ =
             (SELECT MAX(MOVEMENT_SEQ)
                FROM OFFENDER_EXTERNAL_MOVEMENTS
               WHERE OFFENDER_BOOK_ID = :P_OFFENDER_BOOK_ID)
 } 
 
 GET_RECAPTURE_CUR{
  SELECT IN_MOVEMENT_REASON_CODE
        FROM MOVEMENT_REASONS
       WHERE MOVEMENT_TYPE = 'REL'
         AND MOVEMENT_REASON_CODE = :P_MVT_REASON
         AND ESC_RECAP_FLAG = 'Y'
}         
 
GET_MESSAGE_NUMBER{
SELECT MESSAGE_NUMBER FROM CASELOAD_ADM_OTHER_PROFILES WHERE
YOUNG_OFFENDER_AGE >= :P_OFFENDER_AGE AND CASELOAD_ID = :P_CASELOAD_ID
 }    
 
 
GET_TRUST_ACCOUNT_FLAG{
 SELECT TRUST_ACCOUNT_FLAG
        FROM CASELOAD_ADM_OTHER_PROFILES
       WHERE CASELOAD_ID = :P_CASELOAD_ID
  }     