
OTMISAMB_FIND_CGFKINSTMNBALCASELOADID {
 	SELECT CSLD.CASELOAD_ID  CODE  /* CG$FK */        ,CSLD.DESCRIPTION  ,CSLD.LIST_SEQ  LIST_SEQ FROM   CASELOADS CSLD ORDER BY  CSLD.LIST_SEQ        ,CSLD.DESCRIPTION
}

OTMISAMB_FIND_CGFKINSTMNBALACCOUNTCODE {
 	SELECT TO_CHAR(AC_CODE.ACCOUNT_CODE)  CODE  /* CG$FK */        ,AC_CODE.SUB_ACCOUNT_TYPE        ,AC_CODE.ACCOUNT_NAME FROM   ACCOUNT_CODES AC_CODE WHERE   SUB_ACCOUNT_TYPE IS NOT NULL ORDER BY  AC_CODE.ACCOUNT_CODE        ,AC_CODE.SUB_ACCOUNT_TYPE
}

OTMISAMB_FIND_CGFKINSTMNBALAGYLOCID {
 	SELECT CSLD_AL.AGY_LOC_ID  CODE  /* CG$FK */        ,CSLD_AL.CASELOAD_ID  DESCRIPTION FROM   CASELOAD_AGENCY_LOCATIONS CSLD_AL WHERE   CASELOAD_ID = :caseloadId
}

OTMISAMB_INSTMNBAL_FIND_INSTITUTION_MINI_BALANCES {
 	SELECT *  FROM INSTITUTION_MINI_BALANCES 
}
OTMISAMB_INSTMNBAL_INSERT_INSTITUTION_MINI_BALANCES {
--	INSERT INTO INSTITUTION_MINI_BALANCES(CASELOAD_ID, AGY_LOC_ID, ACCOUNT_CODE, MINIMUM_ACCOUNT_BALANCE, MODIFY_DATE, IND_DAYS)
--	VALUES(:caseloadId, :agyLocId, :accountCode, :minimumAccountBalance, TRUNC(SYSDATE), :indDays)
 insert into INSTITUTION_MINI_BALANCES(CASELOAD_ID, AGY_LOC_ID, ACCOUNT_CODE, MINIMUM_ACCOUNT_BALANCE, MODIFY_DATE, IND_DAYS, CREATE_DATETIME , CREATE_USER_ID , MODIFY_DATETIME ) values(:caseloadId, :agyLocId, :accountCode, :minimumAccountBalance, CURRENT_TIMESTAMP , :indDays, CURRENT_TIMESTAMP , :createUserId , CURRENT_TIMESTAMP) 
}

OTMISAMB_INSTMNBAL_UPDATE_INSTITUTION_MINI_BALANCES {
--	UPDATE INSTITUTION_MINI_BALANCES set MINIMUM_ACCOUNT_BALANCE = :minimumAccountBalance, IND_DAYS = :indDays  WHERE  CASELOAD_ID = :caseloadId AND AGY_LOC_ID = :agyLocId AND ACCOUNT_CODE = :accountCode
	 update INSTITUTION_MINI_BALANCES set MINIMUM_ACCOUNT_BALANCE = :minimumAccountBalance, IND_DAYS = :indDays, MODIFY_USER_ID = :modifyUserId , MODIFY_DATETIME = CURRENT_TIMESTAMP where CASELOAD_ID = :caseloadId and AGY_LOC_ID = :agyLocId and ACCOUNT_CODE = :accountCode
}

OTMISAMB_INSTMNBAL_DELETE_INSTITUTION_MINI_BALANCES { 
	DELETE FROM INSTITUTION_MINI_BALANCES WHERE  CASELOAD_ID = :caseloadId AND AGY_LOC_ID = :agyLocId AND ACCOUNT_CODE = :accountCode
}


OTMISAMB_CGFKCHK_INST_MNBAL_INST_MB_CS_ {
	SELECT CSLD.DESCRIPTION ,CSLD.LIST_SEQ FROM   CASELOADS CSLD WHERE  CSLD.CASELOAD_ID = :CASELOADID
}

OTMISAMB_CGFKCHK_INST_MNBAL_INST_MB2_ {
	SELECT CSLD_AL.CASELOAD_ID FROM   CASELOAD_AGENCY_LOCATIONS CSLD_AL WHERE  CSLD_AL.AGY_LOC_ID = :AGYLOCID AND     CASELOAD_ID = :CASELOADID
}

OTMISAMB_CGFKCHK_INST_MNBAL_INST_MB_AC_ {
	SELECT AC_CODE.SUB_ACCOUNT_TYPE ,AC_CODE.ACCOUNT_NAME FROM   ACCOUNT_CODES AC_CODE WHERE  AC_CODE.ACCOUNT_CODE = :ACCOUNTCODE AND     SUB_ACCOUNT_TYPE IS NOT NULL
}

OTMISAMB_CGWHEN_NEW_FORM_INSTANCE_ {
	SELECT  SYSDATE, USER FROM    SYS.DUAL
}
