
OIUSMSEL_FIND_RGR01 {
 	SELECT INITCAP(LAST_NAME ||', '||FIRST_NAME ) NAME , USER_ID FROM OMS_OWNER.STAFF_MEMBERS WHERE USER_ID IS NOT NULL
}

OIUSMSEL_STAFFMEMBERS_FIND_V_STAFF_MEMBER{
SELECT STAFF_ID,ASSIGNED_CASELOAD_ID,WORKING_STOCK_LOC_ID,WORKING_CASELOAD_ID,USER_ID,BADGE_ID,LAST_NAME,FIRST_NAME,MIDDLE_NAME,ABBREVIATION,
POSITION,BIRTHDATE,TERMINATION_DATE,UPDATE_ALLOWED_FLAG,DEFAULT_PRINTER_ID,SUSPENDED_FLAG,SUPERVISOR_STAFF_ID,COMM_RECEIPT_PRINTER_ID,PERSONNEL_TYPE,
AS_OF_DATE,EMERGENCY_CONTACT,ROLE,SEX_CODE,STATUS,SUSPENSION_DATE,SUSPENSION_REASON,FORCE_PASSWORD_CHANGE_FLAG,LAST_PASSWORD_CHANGE_DATE,LICENSE_CODE
CREATE_USER_ID,MODIFY_USER_ID,TITLE,NAME_SEQUENCE,QUEUE_CLUSTER_ID,FIRST_LOGON_FLAG,SUFFIX from V_STAFF_MEMBER
}
OIUSMSEL_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
