
OUIAFLAT_LOGINALERTSBLK_FIND_TAG$LOGIN_ALERTS {
 	SELECT LOG_DATE,LOG_TIME,IP_ADDRESS,HOST,OS_USER,DB_USER,TOOL FROM TAG$LOGIN_ALERTS 
}

OUIAFLAT_CREATE_FORM_GLOBALSCREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
