
OUIAUACT_FIND_RGSTFMEMBER {
 	SELECT INITCAP(LAST_NAME ||', '||FIRST_NAME ) NAME , USER_ID FROM V_STAFF_MEMBER WHERE USER_ID IS NOT NULL
}


OUIAUACT_CREATE_FORM_GLOBALS {
	SELECT DESCRIPTION INTO V_FORM_DESC FROM OMS_MODULES WHERE MODULE_NAME = V_FORM_NAME
}
OUIAUACT_FIND_DETAILS {
SELECT sessionid session_id, NTIMESTAMP# stamp, DECODE (INSTR (clientid, ':', 1, 2), 1, 'INTERNAL', SUBSTR (clientid, INSTR (clientid, ':', 1, 2) + 1) ) os_user,  DECODE (INSTR (clientid, ':'), 1, 'INTERNAL', SUBSTR (clientid, 1, INSTR (clientid, ':') - 1) ) clientip FROM fga_log$ WHERE obj$name = :P_USERNAME AND ( ntimestamp# >= SYS_EXTRACT_UTC (TO_TIMESTAMP(TO_CHAR(:P_DATEFROM,'MM/DD/YYYY')||TO_CHAR(:P_TIMEFROM,'HH24:MI'),'MM/DD/YYYY HH24:MI') AT TIME ZONE 'UTC') AND ntimestamp# <= SYS_EXTRACT_UTC (TO_TIMESTAMP(TO_CHAR(:P_DATETO,'MM/DD/YYYY')||TO_CHAR(:P_TIMETO,'HH24:MI'),'MM/DD/YYYY HH24:MI') AT TIME ZONE 'UTC') )
ORDER BY ntimestamp# DESC
}
SESSION { 
alter session set time_zone='-7:00'
}